;  
;   HX34FIRM -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA

; Firmware is in slot 3-3, RAM in in slot 3-0
; 7FFF is mapper
;
; x11xxxxx	select SRAM in page 2 (8000H-87FFH)
; x00xxxxx	select ROM in page 2
; xxxxxx00	select ROM segement 0 in page 2 (screencopy, japanese wordprocessor)
; xxxxxx01	select ROM segement 1 in page 2 (japanese wordprocessor)
; xxxxxx10	select ROM segement 2 in page 2 (european wordprocessor)
; xxxxxx11	select ROM segement 3 in page 2 (japanese wordprocessor)

; kxxxxxxx	COPY key

SR8000	EQU	08000H			; saved vdp registers
SR8040	EQU	08040H			; saved vdp color registers
SR8060	EQU	08060H			; saved vdp latch register (14)
SR8061	EQU	08061H			; saved vdp i/o 099H last written high byte
SR8062	EQU	08062H			; saved vdp i/o 099H last written low byte



	.Z80
	ORG	4000H
X.0000	EQU	0000H	; -CS-I
J.0001	EQU	0001H	; J---I
J.0002	EQU	0002H	; J---I
I.0003	EQU	0003H	; ----I
I.0004	EQU	0004H	; ----I
I.0007	EQU	0007H	; ----I
C.0008	EQU	0008H	; -C--I
I.0009	EQU	0009H	; ----I
C.000A	EQU	000AH	; -C--I
J.000B	EQU	000BH	; J----
RDSLT	EQU	000CH	; -C--I
I.000D	EQU	000DH	; ----I
I$000E	EQU	000EH	; ----I
I.000F	EQU	000FH	; ----I
C.0010	EQU	0010H	; -C--I
I$0013	EQU	0013H	; ----I
WRSLT	EQU	0014H
C.0014	EQU	0014H	; -C--I
I.0015	EQU	0015H	; ----I
I$0016	EQU	0016H	; ----I
I$0017	EQU	0017H	; ----I
C.0018	EQU	0018H	; -C--I
CALSLT	EQU	001CH	; -C---
I.001E	EQU	001EH	; ----I
C.0020	EQU	0020H	; -C--I
C.0028	EQU	0028H	; -C---
I.002D	EQU	002DH	; ----I
X.0030	EQU	0030H	; -CS-I
I$0032	EQU	0032H	; ----I
I.0036	EQU	0036H	; ----I
C.0038	EQU	0038H	; -C---
WRTVDP	EQU	0047H	; JC---
I.004B	EQU	004BH	; ----I
D$0050	EQU	0050H	; --S--
I.005A	EQU	005AH	; ----I
I$0060	EQU	0060H	; ----I
I.0061	EQU	0061H	; ----I
I$0064	EQU	0064H	; ----I
I.0066	EQU	0066H	; ----I
I.0067	EQU	0067H	; ----I
I$0069	EQU	0069H	; ----I
I.006B	EQU	006BH	; ----I
I$006C	EQU	006CH	; ----I
I$0072	EQU	0072H	; ----I
I$0075	EQU	0075H	; ----I
I.0078	EQU	0078H	; ----I
I$007B	EQU	007BH	; ----I
I$007D	EQU	007DH	; ----I
I$007E	EQU	007EH	; ----I
I$009B	EQU	009BH	; ----I
CHSNS	EQU	009CH	; -C---
CHGET	EQU	009FH	; -C---
CHPUT	EQU	00A2H	; -C---
LPTOUT	EQU	00A5H	; -C---
LPTSTT	EQU	00A8H	; -C---
QINLIN	EQU	00B4H	; -C---
BREAKX	EQU	00B7H	; -C--I
BEEP	EQU	00C0H	; -C---
TAPION	EQU	00E1H	; -C---
TAPIN	EQU	00E4H	; -C---
TAPIOF	EQU	00E7H	; -C---
TAPOON	EQU	00EAH	; -C---
TAPOUT	EQU	00EDH	; -C---
TAPOOF	EQU	00F0H	; -C--I
STMOTR	EQU	00F3H
I$00F5	EQU	00F5H	; ----I
I.00F6	EQU	00F6H	; ----I
I$00F7	EQU	00F7H	; ----I
I$00F8	EQU	00F8H	; ----I
I$00F9	EQU	00F9H	; ----I
I.0100	EQU	0100H	; ----I
I$0109	EQU	0109H	; ----I
I.0125	EQU	0125H	; ----I
I.012C	EQU	012CH	; ----I
I.0130	EQU	0130H	; ----I
I$0133	EQU	0133H	; ----I
I$0135	EQU	0135H	; ----I
I$0136	EQU	0136H	; ----I
I$0142	EQU	0142H	; ----I
I$0144	EQU	0144H	; ----I
I$0146	EQU	0146H	; ----I
I$0148	EQU	0148H	; ----I
I$014A	EQU	014AH	; ----I
I$014B	EQU	014BH	; ----I
I$014C	EQU	014CH	; ----I
I$014E	EQU	014EH	; ----I
I$0150	EQU	0150H	; ----I
I.0152	EQU	0152H	; ----I
I.0154	EQU	0154H	; ----I
KILBUF	EQU	0156H
I$0158	EQU	0158H	; ----I
I$015A	EQU	015AH	; ----I
I$0162	EQU	0162H	; ----I
I$0164	EQU	0164H	; ----I
I$0166	EQU	0166H	; ----I
I$0168	EQU	0168H	; ----I
I$016A	EQU	016AH	; ----I
C.016B	EQU	016BH	; -C---
I$016C	EQU	016CH	; ----I
I$016E	EQU	016EH	; ----I
I$0170	EQU	0170H	; ----I
I$0172	EQU	0172H	; ----I
I$0174	EQU	0174H	; ----I
I$0176	EQU	0176H	; ----I
I$0178	EQU	0178H	; ----I
I$0179	EQU	0179H	; ----I
I$017A	EQU	017AH	; ----I
I$0180	EQU	0180H	; ----I
I$0183	EQU	0183H	; ----I
I.0184	EQU	0184H	; ----I
I$0187	EQU	0187H	; ----I
I$0188	EQU	0188H	; ----I
I.018B	EQU	018BH	; ----I
I$018D	EQU	018DH	; ----I
I$018F	EQU	018FH	; ----I
I.0193	EQU	0193H	; ----I
I.0197	EQU	0197H	; ----I
I.0199	EQU	0199H	; ----I
I.019B	EQU	019BH	; ----I
I$01A1	EQU	01A1H	; ----I
I.01A6	EQU	01A6H	; ----I
I.01A7	EQU	01A7H	; ----I
I$01AA	EQU	01AAH	; ----I
I$01AC	EQU	01ACH	; ----I
I$01AE	EQU	01AEH	; ----I
I$01B2	EQU	01B2H	; ----I
I$01B8	EQU	01B8H	; ----I
I.01BE	EQU	01BEH	; ----I
I$01C0	EQU	01C0H	; ----I
I$01C2	EQU	01C2H	; ----I
I$01C3	EQU	01C3H	; ----I
I$01C7	EQU	01C7H	; ----I
I$01C8	EQU	01C8H	; ----I
I$01C9	EQU	01C9H	; ----I
I$01CA	EQU	01CAH	; ----I
I.01CC	EQU	01CCH	; ----I
I$01CF	EQU	01CFH	; ----I
I$01E3	EQU	01E3H	; ----I
I.01E4	EQU	01E4H	; ----I
I.01E6	EQU	01E6H	; ----I
I$01E7	EQU	01E7H	; ----I
I$01EA	EQU	01EAH	; ----I
I$01ED	EQU	01EDH	; ----I
I.01F1	EQU	01F1H	; ----I
I$01F5	EQU	01F5H	; ----I
I.01F9	EQU	01F9H	; ----I
I$01FB	EQU	01FBH	; ----I
I$01FD	EQU	01FDH	; ----I
I.01FF	EQU	01FFH	; ----I
I.0200	EQU	0200H	; ----I
I$0201	EQU	0201H	; ----I
I$0203	EQU	0203H	; ----I
I$020C	EQU	020CH	; ----I
I$020F	EQU	020FH	; ----I
I.0212	EQU	0212H	; ----I
I$0213	EQU	0213H	; ----I
I$0214	EQU	0214H	; ----I
I.0215	EQU	0215H	; ----I
I$0223	EQU	0223H	; ----I
I.0229	EQU	0229H	; ----I
I.022A	EQU	022AH	; ----I
D.0230	EQU	0230H	; --S--
I$0233	EQU	0233H	; ----I
I$0258	EQU	0258H	; ----I
I.0300	EQU	0300H	; ----I
I.0352	EQU	0352H	; ----I
I.0400	EQU	0400H	; ----I
I.0401	EQU	0401H	; ----I
I.0402	EQU	0402H	; ----I
I.0403	EQU	0403H	; ----I
I$0406	EQU	0406H	; ----I
I$0409	EQU	0409H	; ----I
I$040C	EQU	040CH	; ----I
I$040F	EQU	040FH	; ----I
I$0412	EQU	0412H	; ----I
I.0415	EQU	0415H	; ----I
I$0417	EQU	0417H	; ----I
I$04B0	EQU	04B0H	; ----I
I$0504	EQU	0504H	; ----I
I$052B	EQU	052BH	; ----I
I$0530	EQU	0530H	; ----I
I$0554	EQU	0554H	; ----I
I$0555	EQU	0555H	; ----I
I.0600	EQU	0600H	; ----I
I$0602	EQU	0602H	; ----I
I$0612	EQU	0612H	; ----I
I$0794	EQU	0794H	; ----I
I.0800	EQU	0800H	; ----I
I$0801	EQU	0801H	; ----I
I.0802	EQU	0802H	; ----I
I$0804	EQU	0804H	; ----I
D.0830	EQU	0830H	; --S--
I$083E	EQU	083EH	; ----I
C.08C9	EQU	08C9H	; -C---
I$08D5	EQU	08D5H	; ----I
I.0900	EQU	0900H	; ----I
I$090F	EQU	090FH	; ----I
I$0960	EQU	0960H	; ----I
I$0A05	EQU	0A05H	; ----I
I$0A13	EQU	0A13H	; ----I
I$0A1D	EQU	0A1DH	; ----I
I$0AB7	EQU	0AB7H	; ----I
I$0B02	EQU	0B02H	; ----I
I.0B12	EQU	0B12H	; ----I
I$0B3E	EQU	0B3EH	; ----I
I$0C02	EQU	0C02H	; ----I
I$0C03	EQU	0C03H	; ----I
I$0C07	EQU	0C07H	; ----I
I$0C69	EQU	0C69H	; ----I
I$0CDC	EQU	0CDCH	; ----I
I$0D0C	EQU	0D0CH	; ----I
I$0D32	EQU	0D32H	; ----I
I$0D38	EQU	0D38H	; ----I
I$0DFD	EQU	0DFDH	; ----I
I.0E03	EQU	0E03H	; ----I
I$0E04	EQU	0E04H	; ----I
I$0E08	EQU	0E08H	; ----I
I.0E0F	EQU	0E0FH	; ----I
I$0E14	EQU	0E14H	; ----I
I$0E15	EQU	0E15H	; ----I
I.0E34	EQU	0E34H	; ----I
I$0F06	EQU	0F06H	; ----I
I$0F09	EQU	0F09H	; ----I
D.0F3E	EQU	0F3EH	; --S-I
I.0F42	EQU	0F42H	; ----I
I.0FCE	EQU	0FCEH	; ----I
I$1002	EQU	1002H	; ----I
I$1013	EQU	1013H	; ----I
I$110F	EQU	110FH	; ----I
I$1202	EQU	1202H	; ----I
I$1204	EQU	1204H	; ----I
I$1207	EQU	1207H	; ----I
I.120A	EQU	120AH	; ----I
I.120D	EQU	120DH	; ----I
I.1210	EQU	1210H	; ----I
I$12C0	EQU	12C0H	; ----I
I.1312	EQU	1312H	; ----I
I$1402	EQU	1402H	; ----I
I.1404	EQU	1404H	; ----I
I.1407	EQU	1407H	; ----I
I.140A	EQU	140AH	; ----I
I.140D	EQU	140DH	; ----I
I.140E	EQU	140EH	; ----I
I.1410	EQU	1410H	; ----I
I.1413	EQU	1413H	; ----I
I$1415	EQU	1415H	; ----I
D$1430	EQU	1430H	; --S--
J$1437	EQU	1437H	; J----
I$1500	EQU	1500H	; ----I
J$150B	EQU	150BH	; J----
I$1600	EQU	1600H	; ----I
D.1632	EQU	1632H	; --S--
I$1707	EQU	1707H	; ----I
I.1802	EQU	1802H	; ----I
I$1804	EQU	1804H	; ----I
I$1810	EQU	1810H	; ----I
D.1834	EQU	1834H	; --S--
I$1844	EQU	1844H	; ----I
I$184F	EQU	184FH	; ----I
I$1850	EQU	1850H	; ----I
I$190E	EQU	190EH	; ----I
I$1A07	EQU	1A07H	; ----I
I$1A15	EQU	1A15H	; ----I
D.1A36	EQU	1A36H	; --S--
I$1B31	EQU	1B31H	; ----I
I$1B36	EQU	1B36H	; ----I
D$1B3E	EQU	1B3EH	; --S--
I.1B51	EQU	1B51H	; ----I
I$1BF8	EQU	1BF8H	; ----I
I.1C02	EQU	1C02H	; ----I
I$1C04	EQU	1C04H	; ----I
I$1C13	EQU	1C13H	; ----I
D.1C38	EQU	1C38H	; --S--
I$1D00	EQU	1D00H	; ----I
I$1E0A	EQU	1E0AH	; ----I
I$2000	EQU	2000H	; ----I
I.2002	EQU	2002H	; ----I
J.20DD	EQU	20DDH	; J----
I.2121	EQU	2121H	; ----I
D$212D	EQU	212DH	; ---L-
I$2202	EQU	2202H	; ----I
I$2207	EQU	2207H	; ----I
I$2309	EQU	2309H	; ----I
D$232D	EQU	232DH	; --S--
I$2403	EQU	2403H	; ----I
I$2407	EQU	2407H	; ----I
I.240A	EQU	240AH	; ----I
I.240D	EQU	240DH	; ----I
I$2410	EQU	2410H	; ----I
I.2413	EQU	2413H	; ----I
I$2500	EQU	2500H	; ----I
I$2580	EQU	2580H	; ----I
I$272B	EQU	272BH	; ----I
I.2800	EQU	2800H	; ----I
I$2803	EQU	2803H	; ----I
I$2807	EQU	2807H	; ----I
I$280B	EQU	280BH	; ----I
I$2A00	EQU	2A00H	; ----I
I$2A04	EQU	2A04H	; ----I
I$2A0C	EQU	2A0CH	; ----I
I$2A10	EQU	2A10H	; ----I
D$2B02	EQU	2B02H	; ---L-
I$2C00	EQU	2C00H	; ----I
I$2C04	EQU	2C04H	; ----I
I.2C13	EQU	2C13H	; ----I
I$2C16	EQU	2C16H	; ----I
I$2C26	EQU	2C26H	; ----I
D$2C2B	EQU	2C2BH	; ---L-
I$2D00	EQU	2D00H	; ----I
C$2D1B	EQU	2D1BH	; -C---
I$2D21	EQU	2D21H	; ----I
I$2D44	EQU	2D44H	; ----I
I$2D49	EQU	2D49H	; ----I
I$2E10	EQU	2E10H	; ----I
I$2E15	EQU	2E15H	; ----I
I$2F00	EQU	2F00H	; ----I
I$3007	EQU	3007H	; ----I
I$300F	EQU	300FH	; ----I
D.3030	EQU	3030H	; --S--
D.3031	EQU	3031H	; --S-I
D.3032	EQU	3032H	; --S--
I$3033	EQU	3033H	; ----I
D.3036	EQU	3036H	; --S-I
J$3104	EQU	3104H	; J----
I$3130	EQU	3130H	; ----I
I.3201	EQU	3201H	; ----I
I$321B	EQU	321BH	; ----I
D.3230	EQU	3230H	; --S--
I.3300	EQU	3300H	; ----I
I$3400	EQU	3400H	; ----I
D$3401	EQU	3401H	; --S--
I$3403	EQU	3403H	; ----I
I$3416	EQU	3416H	; ----I
D$3420	EQU	3420H	; --S--
D$3435	EQU	3435H	; --S--
I$3501	EQU	3501H	; ----I
I$3531	EQU	3531H	; ----I
D$3605	EQU	3605H	; ---L-
I$3609	EQU	3609H	; ----I
I.3613	EQU	3613H	; ----I
I$3700	EQU	3700H	; ----I
I$3732	EQU	3732H	; ----I
I$3803	EQU	3803H	; ----I
I.3812	EQU	3812H	; ----I
D$3827	EQU	3827H	; ---L-
I$3839	EQU	3839H	; ----I
D$3926	EQU	3926H	; ---L-
I$3939	EQU	3939H	; ----I
I$3A00	EQU	3A00H	; ----I
I.3A03	EQU	3A03H	; ----I
I.3A11	EQU	3A11H	; ----I
I.3A12	EQU	3A12H	; ----I
C$3AFF	EQU	3AFFH	; -C---
D$3B2D	EQU	3B2DH	; ---L-
I$3C00	EQU	3C00H	; ----I
D$3D3B	EQU	3D3BH	; ---L-
I$3E12	EQU	3E12H	; ----I
I$3E16	EQU	3E16H	; ----I
J$C101	EQU	0C101H	; J----
J$C200	EQU	0C200H	; J----
I$C300	EQU	0C300H	; ----I
J$C4DE	EQU	0C4DEH	; J----
C$C5DE	EQU	0C5DEH	; -C---
C$C601	EQU	0C601H	; -C---
J$CA00	EQU	0CA00H	; J----
C$CC00	EQU	0CC00H	; -C---
C$CD00	EQU	0CD00H	; -C---
C$CD01	EQU	0CD01H	; -C---
I$CEBF	EQU	0CEBFH	; ----I
I.CEC0	EQU	0CEC0H	; ----I
C$CF0D	EQU	0CF0DH	; -C---
I.CF35	EQU	0CF35H	; ----I
I.CF37	EQU	0CF37H	; ----I
I.CF38	EQU	0CF38H	; ----I
I$D0D0	EQU	0D0D0H	; ----I
I$D0F0	EQU	0D0F0H	; ----I
I.D110	EQU	0D110H	; ----I
J$D300	EQU	0D300H	; J----
C$D505	EQU	0D505H	; -C---
I$D8C9	EQU	0D8C9H	; ----I
I$D8D0	EQU	0D8D0H	; ----I
C.D8FB	EQU	0D8FBH	; -C--I
C$D900	EQU	0D900H	; -C---
D.D905	EQU	0D905H	; --SLI
D.D906	EQU	0D906H	; --SL-
D.D907	EQU	0D907H	; --SLI
D.D908	EQU	0D908H	; --SL-
D.D909	EQU	0D909H	; --SL-
D.D90B	EQU	0D90BH	; --SL-
D.D90D	EQU	0D90DH	; --SL-
D.D90E	EQU	0D90EH	; --SL-
D.D90F	EQU	0D90FH	; --SL-
I.D912	EQU	0D912H	; ----I
D.D919	EQU	0D919H	; --SL-
D.D91B	EQU	0D91BH	; --S-I
D.D91C	EQU	0D91CH	; --S--
D.D921	EQU	0D921H	; --SL-
D.D923	EQU	0D923H	; --SL-
I.D924	EQU	0D924H	; ----I
I.D94D	EQU	0D94DH	; ----I
D$D950	EQU	0D950H	; --S--
I.D955	EQU	0D955H	; ----I
D$D958	EQU	0D958H	; --S--
D$D95C	EQU	0D95CH	; --S--
I.D95D	EQU	0D95DH	; ----I
I$D965	EQU	0D965H	; ----I
I.D98D	EQU	0D98DH	; ----I
I$D995	EQU	0D995H	; ----I
I$D9AD	EQU	0D9ADH	; ----I
D.D9B5	EQU	0D9B5H	; --S-I
I$D9BA	EQU	0D9BAH	; ----I
I$D9BB	EQU	0D9BBH	; ----I
I.D9C2	EQU	0D9C2H	; ----I
I.D9C4	EQU	0D9C4H	; ----I
I.D9C7	EQU	0D9C7H	; ----I
I.D9C8	EQU	0D9C8H	; ----I
I$D9C9	EQU	0D9C9H	; ----I
D.D9CB	EQU	0D9CBH	; --SL-
I.D9CC	EQU	0D9CCH	; ----I
I.D9D2	EQU	0D9D2H	; ----I
D.D9E0	EQU	0D9E0H	; --SLI
D.D9E1	EQU	0D9E1H	; --SL-
D.D9E2	EQU	0D9E2H	; --SL-
I.D9EA	EQU	0D9EAH	; ----I
I$D9EE	EQU	0D9EEH	; ----I
I$D9F2	EQU	0D9F2H	; ----I
I.D9FA	EQU	0D9FAH	; ----I
I$D9FE	EQU	0D9FEH	; ----I
I$DA02	EQU	0DA02H	; ----I
I.DA1B	EQU	0DA1BH	; ----I
I$DA1C	EQU	0DA1CH	; ----I
I$DA23	EQU	0DA23H	; ----I
I.DA2B	EQU	0DA2BH	; ----I
I$DA2C	EQU	0DA2CH	; ----I
I$DA33	EQU	0DA33H	; ----I
D.DA3D	EQU	0DA3DH	; --SL-
D.DA5E	EQU	0DA5EH	; --SL-
D.DA62	EQU	0DA62H	; --SL-
D.DA64	EQU	0DA64H	; --S--
D$DA66	EQU	0DA66H	; --S--
D.DA67	EQU	0DA67H	; --SL-
D.DA69	EQU	0DA69H	; --SL-
D.DA6A	EQU	0DA6AH	; --SL-
D.DA6B	EQU	0DA6BH	; --SL-
D.DA6C	EQU	0DA6CH	; --SLI
D.DA6D	EQU	0DA6DH	; --SL-
D.DA6E	EQU	0DA6EH	; --SLI
D.DA6F	EQU	0DA6FH	; --SL-
D.DA70	EQU	0DA70H	; --SLI
D.DA71	EQU	0DA71H	; --SL-
D.DA72	EQU	0DA72H	; --SL-
D.DA73	EQU	0DA73H	; --SL-
D.DA74	EQU	0DA74H	; --SL-
D.DA75	EQU	0DA75H	; --SL-
D.DA76	EQU	0DA76H	; --SL-
D.DA77	EQU	0DA77H	; --SL-
D.DA79	EQU	0DA79H	; --SL-
D.DA7A	EQU	0DA7AH	; --SL-
D.DA7B	EQU	0DA7BH	; --SL-
D.DA7C	EQU	0DA7CH	; --SL-
D.DA7D	EQU	0DA7DH	; --SL-
D.DA7E	EQU	0DA7EH	; --SL-
D.DA7F	EQU	0DA7FH	; --SL-
D.DA80	EQU	0DA80H	; --SLI
D.DA81	EQU	0DA81H	; --SL-
I$DA82	EQU	0DA82H	; ----I
I.DA83	EQU	0DA83H	; ----I
D.DA88	EQU	0DA88H	; --SL-
D.DA8B	EQU	0DA8BH	; --SLI
D.DA8C	EQU	0DA8CH	; --SL-
D.DA8E	EQU	0DA8EH	; --SL-
D.DA8F	EQU	0DA8FH	; --SL-
D.DA94	EQU	0DA94H	; --SL-
D.DA95	EQU	0DA95H	; --SLI
D.DA96	EQU	0DA96H	; --SL-
D.DA97	EQU	0DA97H	; --SL-
D.DA98	EQU	0DA98H	; ---LI
I$DA99	EQU	0DA99H	; ----I
I$DA9F	EQU	0DA9FH	; ----I
I.DAAC	EQU	0DAACH	; ----I
D.DAAE	EQU	0DAAEH	; ---L-
I$DAAF	EQU	0DAAFH	; ----I
D.DAB1	EQU	0DAB1H	; ---LI
I$DAB3	EQU	0DAB3H	; ----I
I$DAB6	EQU	0DAB6H	; ----I
I$DAB9	EQU	0DAB9H	; ----I
I$DABC	EQU	0DABCH	; ----I
D.DAC1	EQU	0DAC1H	; ---L-
D.DAC2	EQU	0DAC2H	; ---LI
D.DAC3	EQU	0DAC3H	; ---L-
D.DAC4	EQU	0DAC4H	; --SL-
D.DAC5	EQU	0DAC5H	; --SL-
D.DAC6	EQU	0DAC6H	; --SL-
D.DAC7	EQU	0DAC7H	; --SL-
D.DAC8	EQU	0DAC8H	; --SL-
D.DAC9	EQU	0DAC9H	; --SL-
D.DACA	EQU	0DACAH	; --S--
D.DAD0	EQU	0DAD0H	; --SL-
D.DAD6	EQU	0DAD6H	; --S--
D.DAD8	EQU	0DAD8H	; --SL-
D.DAD9	EQU	0DAD9H	; --S--
I$DADA	EQU	0DADAH	; ----I
I$DADF	EQU	0DADFH	; ----I
C$DAE1	EQU	0DAE1H	; -C---
D.DAFB	EQU	0DAFBH	; --SL-
D.DAFD	EQU	0DAFDH	; --SL-
J$DB00	EQU	0DB00H	; J----
D.DB02	EQU	0DB02H	; --SL-
D.DB0E	EQU	0DB0EH	; --SL-
D.DB0F	EQU	0DB0FH	; --SL-
D.DB10	EQU	0DB10H	; --SL-
C$DC00	EQU	0DC00H	; -C---
C$E042	EQU	0E042H	; -C---
D$E102	EQU	0E102H	; --S--
I$E109	EQU	0E109H	; ----I
C$E201	EQU	0E201H	; -C---
J$E401	EQU	0E401H	; J----
J$EA0B	EQU	0EA0BH	; J----

CNSDFG	EQU	0F3DEH	; --S--
PUTPNT	EQU	0F3F8H	; --S--
GETPNT	EQU	0F3FAH	; --S--
LPTPOS	EQU	0F415H	; --S--
I$F420	EQU	0F420H	; ----I
I.F528	EQU	0F528H	; ----I
I.F52B	EQU	0F52BH	; ----I
I$F52C	EQU	0F52CH	; ----I
D$F530	EQU	0F530H	; --S--
D$F532	EQU	0F532H	; --S--
I$F54F	EQU	0F54FH	; ----I
I$F550	EQU	0F550H	; ----I
D.F55E	EQU	0F55EH	; --SL-
D.F55F	EQU	0F55FH	; --SL-
D.F560	EQU	0F560H	; --SL-
D.F561	EQU	0F561H	; --SLI
D.F562	EQU	0F562H	; --SLI
D.F563	EQU	0F563H	; --SLI
D.F564	EQU	0F564H	; --SL-
D.F565	EQU	0F565H	; --SL-
I$F567	EQU	0F567H	; ----I
I.F56E	EQU	0F56EH	; ----I
I$F5A0	EQU	0F5A0H	; ----I
I.F5B0	EQU	0F5B0H	; ----I
I$F5B8	EQU	0F5B8H	; ----I
I.F5C0	EQU	0F5C0H	; ----I
I$F5C8	EQU	0F5C8H	; ----I
I.F5D0	EQU	0F5D0H	; ----I
VALTYP	EQU	0F663H	; ----I
DAC	EQU	0F7F6H	; ----I
FILTAB	EQU	0F860H	; ---L-
NULBUF	EQU	0F862H	; ---L-
PTRFIL	EQU	0F864H	; --S--
FILNAM	EQU	0F866H	; ----I
D.F86C	EQU	0F86CH	; --SL-
FILNM2	EQU	0F871H	; ----I
D$F877	EQU	0F877H	; ---L-
D.F878	EQU	0F878H	; --S--
FNKSTR	EQU	0F87FH	; ----I

C.F882	EQU	0F882H	; -C---
I.F8CF	EQU	0F8CFH	; ----I
I$F8DF	EQU	0F8DFH	; ----I
I$F8EF	EQU	0F8EFH	; ----I

CHRCNT	EQU	0FAF9H	; --SL-
ROMA	EQU	0FAFAH	; ----I
MODE	EQU	0FAFCH	; ---L-

RSTMP	EQU	0FB03H	; --SL-
RSFCB	EQU	0FB04H	; --SL-
RSIQLN	EQU	0FB06H	; --SLI
MEXBIH	EQU	0FB07H	; J---I
OLDSTT	EQU	0FB0CH	; J---I
OLDINT	EQU	0FB11H	; J---I
DEVNUM	EQU	0FB16H	; ---LI
DATCNT	EQU	0FB17H	; ---LI
D$FB18	EQU	0FB18H	; ---L-
D.FB1A	EQU	0FB1AH	; --SLI
D.FB1B	EQU	0FB1BH	; --SLI
ERRORS	EQU	0FB1CH	; --SLI
ESTBLS	EQU	0FB1DH	; --S-I
COMMSV	EQU	0FB1EH	; --SL-
LSTCOM	EQU	0FB1FH	; --SL-
HOKVLD	EQU	0FB20H	; ----I
ONGSBF	EQU	0FBD8H	; ----I
OLDKEY	EQU	0FBE0H	; ---LI
KEYBUF	EQU	0FBF0H	; ----I
HIMEM	EQU	0FC4AH	; --S--
TRPTBL	EQU	0FC82H	; ----I
INTFLG	EQU	0FC9BH	; --SL-
CSRSR	EQU	0FCA9H	; ---L-

SLTWRK	EQU	0FD09H
; SLTWRK + main_slot*32 + sub_slot*8 + page*2.

D.FD0D	EQU	SLTWRK + 0*32 + 0*8 + 2*2 + 0	; slot 0-0, page 2: in spooler interrupt flag
D.FD19	EQU	SLTWRK + 0*32 + 2*8 + 0*2 + 0	; slot 0-2, page 0: ?
D.FD7F	EQU	SLTWRK + 3*32 + 2*8 + 3*2 + 0	; slot 3-2, page 3: spooler get pointer / toshiba rs232 found flag
D.FD81	EQU	SLTWRK + 3*32 + 3*8 + 0*2 + 0	; slot 3-3, page 0: spooler put pointer
C.FD83	EQU	SLTWRK + 3*32 + 3*8 + 1*2 + 0	; slot 3-3, page 1,2,3: old H.TIMI (Spooler)
D.FD88	EQU	C.FD83+5			; slot 3-3, page 3: spooler empty flag

PROCNM	EQU	0FD89H	; ----I
H.KEYI	EQU	0FD9AH	; --SLI
H.TIMI	EQU	0FD9FH	; ----I

I.FF00	EQU	0FF00H	; ----I
I$FF02	EQU	0FF02H	; ----I
H.NEWS	EQU	0FF3EH	; --S-I
H.LPTO	EQU	0FFB6H	; --S-I
I.FFC0	EQU	0FFC0H	; ----I
EXTBIO	EQU	0FFCAH	; -CS-I
DISINT	EQU	0FFCFH	; ----I
D.FFFF	EQU	0FFFFH	; --S-I

I4000:	DEFB	"AB"			; extension header
I4002:	DEFW	C4075			; extension INIT handler
I4004:	DEFW	C502E			; extension STATEMENT handler
I4006:	DEFW	C420A			; extension DEVICE handler
        DEFW    0			; extension BASIC program (no BASIC program)
        DEFS    6,0			; extension reserved

I4010:	DEFB	010H			; +00 MSX serial features (no TxReady INT, No Sync detect, No Timer INT, No CD, No RI)
	DEFB	000H			; +01 MSX serial version (version 1.0)
	DEFB	000H			; +02 reserved
	JP	J4040			; +03 RS232.INIT
	JP	C4282			; +06 RS232.OPEN
	JP	C4F98			; +09 RS232.STAT
	JP	C42E7			; +0C RS232.GETCHR
	JP	C4E17			; +0F RS232.SNDCHR
	JP	C42B2			; +12 RS232.CLOSE
	JP	J406A			; +15 RS232.EOF
	JP	C4339			; +18 RS232.LOC
	JP	C4364			; +1B RS232.LOF
	JP	C43A1			; +1E RS232.BACKUP
	JP	C4F1B			; +21 RS232.SNDBRK
	JP	C4F80			; +24 RS232.DTR
	RET				; +27 Reserved (with version 1.0)
	RET
	RET
	RET				; +2A Reserved (with version 1.0)
	RET
	RET
	RET				; +2D Reserved (with version 1.0)
	RET
	RET


J4040:	EI
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	IY,-13
	ADD	IY,SP
	LD	SP,IY
	PUSH	IY
	POP	DE
	LD	C,13 
J4051:	CALL	C44E1
	LD	(DE),A
I4055:	INC	DE
	DEC	C
	JR	NZ,J4051
	CALL	C4B0D
	PUSH	AF
	LD	IY,13+2
	ADD	IY,SP
	POP	AF
	LD	SP,IY
	POP	HL
	POP	DE
	POP	BC
	RET

J406A:	LD	HL,0
I406D:	CALL	C4C88
	RET	Z
	CALL	C4381
	RET

;	  Subroutine ROM extension INIT handler
;	     Inputs  ________________________
;	     Outputs ________________________

C4075:	IN	A,(82H)			; read MSX serial system status register
	BIT	3,A			; reserved bit 3 should be '1'
	RET	Z			; nope, quit MSX serial INIT
	LD	A,0FEH			; enable RxReady interupt, reserved bits 7-4 '1'
	OUT	(82H),A			; write MSX serial interrupt mask register
	IN	A,(82H)
	BIT	3,A			; reserved bit 3 should be '0'
	RET	NZ			; nope, quit MSX serial INIT
	CPL
	LD	(D.FD7F),A		; toshiba MSX serial found
	CALL	C4C74
	LD	IY,I4155
	CALL	C4B0D
	CALL	C4143
	DI
	LD	DE,OLDINT
	LD	HL,H.KEYI
	LD	BC,5
	LDIR
	LD	DE,OLDSTT
	LD	HL,H.NEWS
	LD	BC,5
	LDIR
	CALL	C4C58
	LD	(H.KEYI+1),A
	LD	(H.NEWS+1),A
	LD	A,0F7H
	LD	(H.KEYI+0),A
	LD	(H.NEWS+0),A
	LD	HL,I4C82
	LD	(H.KEYI+2),HL
	LD	HL,I4A11
	LD	(H.NEWS+2),HL
	LD	A,0C9H
	LD	(H.KEYI+4),A
	LD	(H.NEWS+4),A
	EI
	LD	HL,HOKVLD
	BIT	0,(HL)
	JR	NZ,J40E4
	SET	0,(HL)
	LD	HL,EXTBIO
	LD	B,05H	; 5 
J40DF:	LD	(HL),0C9H
	INC	HL
	DJNZ	J40DF
J40E4:	XOR	A
	LD	DE,8*256+1
	CALL	EXTBIO
	LD	HL,DEVNUM
	LD	(HL),A
	XOR	A
	LD	DE,0*256+1
	CALL	EXTBIO
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	(HL),A
	LD	DE,MEXBIH
	DI
I4100:	LD	HL,EXTBIO
	LD	BC,5
	LDIR
	CALL	C4C58
	LD	(EXTBIO+1),A
	LD	A,0F7H
	LD	(EXTBIO+0),A
	LD	HL,I43F6
	LD	(EXTBIO+2),HL
	LD	A,0C9H
	LD	(EXTBIO+4),A
	LD	BC,L412B
	LD	HL,I412B
	LD	DE,DISINT
	LDIR
	EI
	RET

I412B:	PUSH	DE
	LD	E,2
	JR	J4133

?4130:	PUSH	DE
	LD	E,3
J4133:	LD	D,0
	PUSH	IX
	PUSH	IY
	CALL	EXTBIO
	EI
	POP	IY
	POP	IX
	POP	DE
	RET

L412B	EQU	$-I412B

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4143:	XOR	A
	LD	(D.FB1B),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4147:	PUSH	HL
	LD	HL,DATCNT
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	POP	HL
	RET

I4155:	JR	C,J41A5
	LD	SP,I4858
	LD	C,(HL)
	LD	C,(HL)
	LD	C,(HL)
	OR	B
	INC	B
	OR	B
	INC	B
	NOP

;	  Subroutine ROM extension STATEMENT handler (MSX serial statements)
;	     Inputs  ________________________
;	     Outputs ________________________

J4162:	LD	A,(D.FD7F)
	OR	A			; toshiba MSX serial found ?
	SCF
	RET	Z			; nope, quit
	EI
	PUSH	HL
	POP	IX
	LD	DE,I41B7
	CALL	C4175
	RET	C
	PUSH	DE
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4175:	PUSH	BC
	PUSH	HL
J4177:	LD	HL,PROCNM
	LD	A,(DE)
	INC	A
	JR	Z,J4190
	CALL	C4194
	JR	Z,J4188
	INC	DE
	INC	DE
	INC	DE
	JR	J4177

J4188:	EX	DE,HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	AND	A
	JR	J4191

J4190:	SCF
J4191:	POP	HL
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4194:	LD	A,(DE)
	CALL	C4B04
	LD	C,A
	LD	A,(HL)
	CALL	C4B04
	CP	C
	JR	NZ,J41A6
	AND	A
	RET	Z
	INC	DE
	INC	HL
	JR	C4194
J41A5	EQU	$-1

J41A6:	LD	A,(DE)
	AND	A
	JR	Z,J41AD
	INC	DE
	JR	J41A6

J41AD:	LD	A,(HL)
	AND	A
	JR	Z,J41B4
	INC	HL
	JR	J41AD

J41B4:	LD	A,L
	OR	H
	RET

I41B7:	DEFB	"COMINI"
	DEFB	0
	DEFW	I45AE
	DEFB	"COMDTR"
	DEFB	0
	DEFW	I4671
	DEFB	"COMSTAT"
	DEFB	0
	DEFW	I468F
	DEFB	"COMBREAK"
	DEFB	0
	DEFW	I46B3
	DEFB	"COMTERM"
	DEFB	0
	DEFW	I46F8
	DEFB	"COM"
	DEFB	0
	DEFW	I4968
	DEFB	"COMON"
	DEFB	0
	DEFW	I49C0
	DEFB	"COMOFF"
	DEFB	0
	DEFW	I49A2
	DEFB	"COMSTOP"
	DEFB	0
	DEFW	I49DE
	DEFB	0FFH

;	  Subroutine ROM extension DEVICE handler
;	     Inputs  ________________________
;	     Outputs ________________________

C420A:	PUSH	HL
	LD	L,A
	LD	A,(D.FD7F)
	OR	A			; toshiba MSX serial found ?
	LD	A,L
	POP	HL
	JR	Z,J424F			; nope, return device not recognized
	EI
	CP	0FFH
	JP	NZ,J4251
	LD	HL,PROCNM
	LD	A,(HL)
	CP	"C"
	JR	NZ,J424F
	INC	HL
	LD	A,(HL)
	CP	"O"
	JR	NZ,J424F
	INC	HL
	LD	A,(HL)
	CP	"M"
	JR	NZ,J424F
	INC	HL
	LD	A,(HL)
	AND	A
	JR	NZ,J4236
	DEC	HL
	LD	A,"0"
J4236:	SUB	"0"
	JR	C,J424F
	CP	0AH	; 10 
	JR	NC,J424F
	PUSH	BC
	PUSH	AF
	LD	A,(DEVNUM)
	AND	0FH	; 15 
	LD	B,A
	POP	AF
	CP	B
	POP	BC
	JR	NZ,J424F
	INC	HL
	LD	A,(HL)
	AND	A
	RET	Z
J424F:	SCF
	RET

J4251:	PUSH	HL
	PUSH	AF
	LD	HL,I4262
	ADD	A,L
	LD	L,A
	JR	NC,J425B
	INC	H
J425B:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	POP	AF
	EX	(SP),HL
	RET

I4262:	HALT

?4263:	LD	B,D
	OR	D
	LD	B,D
	SBC	A,D
	LD	B,H
	CALL	NC,C$E042
	LD	B,D
	DEC	HL
	LD	B,E
	LD	E,(HL)
	LD	B,E
	LD	A,B
	LD	B,E
	CP	B
	LD	B,H
	AND	C
	LD	B,E

	LD	C,127
	CALL	C4282
	JP	C,J448E
	LD	(PTRFIL),HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4282:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	(RSFCB),HL
	LD	A,C
	LD	(RSIQLN),A
	LD	(HL),E
	XOR	A
	INC	HL
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	INC	HL
	INC	HL
	LD	(HL),A
	CALL	C4143
	LD	A,E
	CP	08H	; 8 
	JR	Z,J42AD
	LD	HL,D.FB1B
	SET	3,(HL)
	DI
	CALL	C4C7B
	CALL	C4F6D			; RTS=1
	EI
	SCF
J42AD:	CCF
	POP	HL
	POP	DE
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C42B2:	PUSH	HL
	LD	HL,(RSFCB)
	LD	A,(HL)
	CP	02H	; 2 
	SCF
	CCF
	JR	NZ,J42C2
	LD	A,1AH
	CALL	C4E17
J42C2:	DI
	CALL	C4FBE
	CALL	C4F75
	CALL	C4C74
	EI
	LD	HL,D.FB1B
	RES	3,(HL)
	POP	HL
	RET

?42D4:	LD	A,C
	CALL	C4E17
	EI
	JP	C,J44C4
	JP	Z,J44C4
	RET

?42E0:	CALL	C42E7
	JP	M,J44C4
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C42E7:	PUSH	HL
	PUSH	BC
	CALL	C43B9
	LD	C,(HL)
	LD	(HL),00H
	DEC	HL
	LD	A,(HL)
	LD	(D.FB1A),A
	LD	(HL),00H
	INC	HL
	AND	A
	JR	NZ,J4321
	LD	A,C
	AND	A
	JR	NZ,J430D
	CALL	C4C9C
I4300	EQU	$-1
	EI
	LD	C,A
	JP	M,J4321
	CALL	C4EDE
	JR	C,J4321
	JR	Z,J4321
J430D:	PUSH	HL
	LD	HL,(RSFCB)
	LD	A,(HL)
	POP	HL
	CP	04H	; 4 
	JR	Z,J4325
	LD	A,C
	CP	1AH
	JR	NZ,J4325
	LD	(HL),A
	AND	A
	SCF
	JR	J4328

J4321:	OR	80H
	JR	J4327

J4325:	XOR	A
	INC	A
J4327:	LD	A,C
J4328:	POP	BC
	POP	HL
	RET

?432B:	PUSH	HL
	CALL	C4339
J432F:	LD	(DAC+2),HL
	LD	HL,VALTYP
	LD	(HL),2
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4339:	PUSH	AF
	EI
	LD	HL,(RSFCB)
	LD	A,(HL)
	CP	01H	; 1 
	JR	NZ,J4356
	CALL	C43B1
	JR	Z,J434E
	SUB	1AH
	JR	Z,J4359
	LD	A,01H	; 1 
J434E:	PUSH	BC
	CALL	C43C0
	ADD	A,B
	POP	BC
	JR	J4359

J4356:	CALL	C4C88
J4359:	LD	L,A
	LD	H,00H
	POP	AF
	RET

?435E:	PUSH	HL
	CALL	C4364
J4362:	JR	J432F

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4364:	PUSH	AF
	EI
	CALL	C4339
	PUSH	DE
	EX	DE,HL
	LD	A,(RSIQLN)
	LD	L,A
	LD	H,00H
	AND	A
	SBC	HL,DE
	INC	HL
	POP	DE
	POP	AF
	RET

?4378:	PUSH	HL
	CALL	C4381
	JP	M,J44C4
	JR	J4362

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4381:	PUSH	BC
	LD	B,A
	EI
	CALL	C42E7
	JP	M,J439E
	PUSH	BC
	LD	C,A
	CALL	C43A1
	POP	BC
	CP	1AH
	JR	Z,J439A
	XOR	A
	LD	L,A
	LD	H,A
	INC	A
	JR	J439E

J439A:	LD	HL,D.FFFF
	SCF
J439E:	LD	A,B
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C43A1:	PUSH	HL
	CALL	C43B9
	LD	(HL),C
	PUSH	AF
	DEC	HL
	LD	A,(D.FB1A)
	AND	38H	; "8"
	LD	(HL),A
	POP	AF
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C43B1:	PUSH	HL
	CALL	C43B9
	LD	A,(HL)
	POP	HL
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C43B9:	LD	HL,(RSFCB)
	INC	HL
	INC	HL
	INC	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C43C0:	PUSH	AF
	PUSH	HL
	LD	B,00H
	CALL	C4C97
	JR	Z,J43D6
	LD	C,A
J43CA:	CALL	C43D9
	LD	A,(HL)
	CP	1AH
	JR	Z,J43D6
	INC	B
	DEC	C
	JR	NZ,J43CA
J43D6:	POP	HL
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C43D9:	PUSH	DE
	LD	A,(D$FB18)
	LD	HL,RSIQLN
	ADD	A,B
	JR	C,J43E6
	CP	(HL)
	JR	C,J43E7
J43E6:	SUB	(HL)
J43E7:	LD	HL,(RSFCB)
	LD	E,09H	; 9 
	LD	D,00H
	ADD	HL,DE
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	POP	DE
	RET

I43F6:	EI
	PUSH	AF
	LD	A,D
	INC	A
	JP	Z,J444B
	DEC	A
	JP	NZ,J445E
	LD	A,E
	AND	A
	JR	Z,J4411
	DEC	A
	JR	Z,J441E
	DEC	A
	JR	Z,J4424
	DEC	A
	JR	Z,J4438
	JP	J4479

J4411:	LD	A,08H	; 8 
	CALL	C44CB
	LD	A,00H
	CALL	C44CB
	JP	J4479

J441E:	POP	AF
	INC	A
	PUSH	AF
	JP	J4479

J4424:	CALL	C4A52
	JR	Z,J4435
	PUSH	BC
	CALL	C4DE3
	EI
	NOP
	POP	BC
	DI
	CALL	C4C74
	EI
J4435:	JP	J4479

J4438:	CALL	C4A52
	JR	Z,J4448
	DI
I443E:	CALL	C4C7B
	CALL	C4F6D			; RTS=1
	CALL	C4DC9			; signal sender to resume sending
	EI
J4448:	JP	J4479

J444B:	LD	A,E
	AND	A
	JR	NZ,J445C
	CALL	C447D
	LD	A,00H
	CALL	C44CB
	LD	A,00H
	CALL	C44CB
J445C:	JR	J4479

J445E:	CP	08H	; 8 
	JR	NZ,J4479
	LD	A,E
	AND	A
	JR	Z,J446C
	CP	01H	; 1 
	JR	Z,J4476
	JR	J4479

J446C:	CALL	C447D
	LD	A,00H
	CALL	C44CB
	JR	J4479

J4476:	POP	AF
	INC	A
	PUSH	AF
J4479:	POP	AF
	JP	MEXBIH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C447D:	CALL	C4C58
	CALL	C44CB
	LD	A,10H	; 16 
	CALL	C44CB
	LD	A,40H	; "@"
	CALL	C44CB
	RET

J448E:	LD	IX,DERNMF
	JR	J44C8

?4494:	LD	IX,DERIER
	JR	J44C8

?449A:	LD	IX,DERSOO
	JR	J44C8

J44A0:	LD	IX,DERFAO
	JR	J44C8

J44A6:	LD	IX,DERFNO
	JR	J44C8

J44AC:	LD	IX,M481C
	JR	J44C8

J44B2:	LD	IX,SNERR
	JR	J44C8

J44B8:	LD	IX,FCERR
	JR	J44C8

J44BE:	LD	IX,TMERR
	JR	J44C8

J44C4:	LD	IX,DIOERR
J44C8:	JP	C459D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C44CB:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	E,A
	LD	A,B
	LD	IX,WRSLT
	CALL	C45A2
	EI
	INC	HL
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C44E1:	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	A,B
	LD	IX,RDSLT
	CALL	C45A2
	EI
	INC	HL
	POP	IX
	POP	DE
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C44F4:	PUSH	IX
	LD	IX,BREAKX
	CALL	C45A2
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4500:	PUSH	BC
	LD	B,A
	LD	A,(D.F561)
	AND	A
	JR	Z,J4526
	LD	A,B
	CP	20H	; " "
	JR	NC,J4526
	LD	A,5EH	; "^"
	CALL	C4528
	LD	A,B
	ADD	A,40H	; "@"
	CALL	C4528
	LD	A,B
	CP	0AH	; 10 
	POP	BC
	RET	NZ
	LD	A,0DH	; 13 
	CALL	C4528
	LD	A,0AH	; 10 
	JR	C4528

J4526:	LD	A,B
	POP	BC
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4528:	PUSH	AF
	CALL	CHPUT
	EI
	LD	A,(D.F563)
	AND	A
	JR	Z,J4539
	POP	AF
	PUSH	AF
	CALL	LPTOUT
	EI
J4539:	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C453B:	LD	A,(HL)
	EX	(SP),HL
	CP	(HL)
	JP	NZ,J44B2
	INC	HL
	EX	(SP),HL
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4543:	PUSH	IX
	LD	IX,CHRGTR
	EXX
	PUSH	HL
	EXX
	CALL	C459D
	EXX
	POP	HL
	EXX
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4555:	PUSH	IX
	LD	IX,FRMEVL
	CALL	C459D
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4561:	PUSH	IX
	LD	IX,GETUIN
	CALL	C459D
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C456D:	PUSH	IX
	LD	IX,GETBYT
	CALL	C459D
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4579:	PUSH	IX
	LD	IX,PTRGET
	CALL	C459D
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4585:	PUSH	IX
	LD	IX,FRESTR
	CALL	C459D
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4591:	PUSH	IX
	LD	IX,DOCNVF
	CALL	C459D
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C459D:	CALL	C45A2
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C45A2:	PUSH	IY
	LD	IY,(EXPTBL+0-1)
	CALL	CALSLT
	POP	IY
	RET

;	  Subroutine _COMINI handler
;	     Inputs  ________________________
;	     Outputs ________________________

I45AE:	CALL	C4A58
	CALL	C4A52
	DI
	CALL	C4C74
	EI
	LD	A,(COMMSV)
	LD	(D.F560),A
	LD	IY,I$F567
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	BC,13
	PUSH	IY
	POP	DE
	LD	HL,I4155
	LDIR
	POP	HL
	POP	DE
	POP	BC
	LD	A,B
	AND	C
	INC	A
	JR	NZ,J45EE
	LD	A,D
	AND	A
	JP	Z,J465A
	CP	3AH	; ":"
	JP	Z,J465A
	CP	29H	; ")"
	JP	Z,J4657
	CALL	C453B
	INC	L
	JR	J4614

J45EE:	PUSH	HL
	EXX
	PUSH	HL
	EXX
	POP	HL
	LD	A,B
	AND	A
	JR	Z,J4607
	PUSH	IY
	POP	DE
J45FA:	LD	A,(HL)
	CP	20H	; " "
	JR	Z,J4603
	CALL	C4B04
I4600	EQU	$-2
	LD	(DE),A
J4603:	INC	DE
	INC	HL
	DJNZ	J45FA
J4607:	POP	HL
	DEC	HL
	CALL	C4543
	CP	29H	; ")"
	JR	Z,J4657
	CALL	C453B
	INC	L
J4614:	CP	2CH	; ","
	JR	Z,J462E
	CALL	C4561
	LD	(IY+8),E
	LD	(IY+9),D
	LD	A,(HL)
	CP	29H	; ")"
	JR	NZ,J462E
	LD	(IY+10),E
	LD	(IY+11),D
	JR	J4657

J462E:	CALL	C453B
	INC	L
	CP	2CH	; ","
	JR	Z,J4644
	CALL	C4561
	LD	(IY+10),E
	LD	(IY+11),D
	LD	A,(HL)
	CP	29H	; ")"
	JR	Z,J4657
J4644:	CALL	C453B
	INC	L
	CP	29H	; ")"
	JR	Z,J4657
	CALL	C456D
	LD	(IY+12),A
	CALL	C453B
	ADD	HL,HL
	DEC	HL
J4657:	CALL	C4543
J465A:	EI
	CALL	C4B0D
	JP	C,J44B8
	CALL	C4A52
	CALL	NZ,C4C7B
	LD	A,(D.F560)
	BIT	5,A
	CALL	NZ,C4F6D		; RTS=1
	AND	A
	RET

;	  Subroutine _COMDTR handler
;	     Inputs  ________________________
;	     Outputs ________________________

I4671:	CALL	C4A58
	CALL	C4AC1
	CALL	C453B
	INC	L
	CALL	C4A52
	JP	Z,J44A6
	CALL	C4561
	CALL	C453B
	ADD	HL,HL
	LD	A,D
	OR	E
	CALL	C4F80
	EI
	RET

;	  Subroutine _COMSTAT handler
;	     Inputs  ________________________
;	     Outputs ________________________

I468F:	CALL	C4A58
	CALL	C4AC1
	CALL	C453B
	INC	L
	CALL	C4A52
	JP	Z,J44A6
	CALL	C4579
	PUSH	HL
	CALL	C4F98
	LD	(DAC+2),HL
	POP	HL
	CALL	C4ACB
	CALL	C453B
	ADD	HL,HL
	AND	A
	RET

;	  Subroutine _COMBREAK handler
;	     Inputs  ________________________
;	     Outputs ________________________

I46B3:	CALL	C4A58
	CALL	C4AC1
	CALL	C4A52
	JP	Z,J44A6
	LD	A,D
	CP	2CH	; ","
	JR	Z,J46D4
	AND	A
	JR	Z,J46CF
	CP	3AH	; ":"
	JR	Z,J46CF
	CALL	C453B
	ADD	HL,HL
J46CF:	LD	DE,C.000A
	JR	J46DE

J46D4:	CALL	C4543
	CALL	C4561
	CALL	C453B
	ADD	HL,HL
J46DE:	PUSH	HL
	LD	HL,J.0002
	AND	A
	SBC	HL,DE
	JP	NC,J44B8
	POP	HL
	CALL	C4F1B
	EI
	LD	A,00H
	INC	A
	CALL	C4EDE
	JP	C,J44C4
	AND	A
	RET

;	  Subroutine _COMTERM handler
;	     Inputs  ________________________
;	     Outputs ________________________

I46F8:	CALL	C4A58
	CALL	C4AC1
	LD	A,D
	AND	A
	JR	Z,J470A
	CP	3AH	; ":"
	JR	Z,J470A
	CALL	C453B
	ADD	HL,HL
J470A:	LD	(D.F565),HL
	CALL	C4A52
	JP	NZ,J44A0
	XOR	A
	LD	(D.F55E),A
	LD	(D.F563),A
	LD	(D.F561),A
	LD	(D.F562),A
	LD	HL,I.F8CF
	LD	DE,I.F56E
	LD	BC,48
	PUSH	BC
	PUSH	HL
	LDIR
	POP	HL
	POP	BC
	LD	B,C
	PUSH	HL
J4731:	LD	(HL),00H
	INC	HL
	DJNZ	J4731
	POP	DE
	LD	HL,I491A
	LD	BC,5
	PUSH	BC
	LDIR
	POP	BC
	LD	DE,I$F8DF
	PUSH	BC
	LDIR
	POP	BC
	LD	DE,I$F8EF
	PUSH	BC
	LDIR
	POP	BC
	LD	A,(CSRSR)
	LD	(D.F564),A
	CALL	C493B
	LD	HL,(NULBUF)
	LD	E,04H	; 4 
	LD	C,120
	CALL	C4282
J4762:	EI
	CALL	C4339
	LD	A,L
	OR	H
	JR	Z,J4794
	CALL	C4929
	JR	C,J47C9
	LD	C,A
	LD	A,(D.F55E)
	AND	A
	JR	NZ,J4786
	LD	A,C
	CP	1BH
	JR	NZ,J4781
	LD	A,01H	; 1 
	LD	(D.F55E),A
	LD	A,C
J4781:	CALL	C4500
	JR	J479D

J4786:	XOR	A
	LD	(D.F55E),A
	LD	A,C
	CP	1BH
	JR	NZ,J4781
	CALL	C4500
	JR	J47EC

J4794:	CALL	C4F6D			; RTS=1
	CALL	C4DC9			; signal sender to resume sending
	EI
	JR	C,J47C9
J479D:	CALL	C495D			; STOP or CTRL-STOP pressed ?
	CALL	NZ,C4933		; yep,
	CALL	C44F4
	JR	C,J47C9
	CALL	CHSNS
	EI
	JR	Z,J4762
	CALL	CHGET
	EI
	CP	0A0H
	JP	Z,J48F9
	CALL	C492E
	LD	C,A
	LD	A,(D.F562)
	AND	A
	JP	Z,J4762
	LD	A,C
	CALL	C4500
	JP	J4762

J47C9:	CALL	C42B2
	LD	HL,I.F56E
	LD	DE,I.F8CF
	LD	BC,48
	LDIR
	LD	HL,(D.F565)
	LD	A,(D.F564)
	AND	A
	PUSH	AF
	CALL	Z,C494B
	POP	AF
	CALL	NZ,C493B
	XOR	A
	DI
	LD	(INTFLG),A		; reset STOP or CTRL-STOP flag
	RET

J47EC:	LD	A,(D.F561)
	AND	A
	JP	NZ,J4762
	CALL	C494B
	LD	A,0FFH
	LD	(D.F55F),A
J47FB:	CALL	C4929
	JP	C,J47C9
I4800	EQU	$-1
	CP	3AH	; ":"
	JR	NZ,J47FB
	CALL	C48C7
	JP	C,J487E
I4809	EQU	$-2
	AND	A
	JR	Z,J4855
	LD	B,A
	LD	E,A
	CALL	C48BC
	JP	C,J487E
	CALL	C48C7
	JP	C,J487E
I481C:	ADD	A,L
	ADD	A,H
	ADD	A,E
	LD	E,A
J4820:	CALL	C48C7
	JR	C,J487E
	LD	(HL),A
	ADD	A,E
	LD	E,A
	INC	HL
	DJNZ	J4820
	CALL	C48C7
	JR	C,J487E
	ADD	A,E
	JR	NZ,J487E
	LD	A,47H	; "G"
	CALL	C492E
	LD	A,(D.F55F)
	AND	A
	JR	Z,J4849
	INC	A
	LD	(D.F55F),A
	LD	A,2AH	; "*"
	CALL	C4500
	JR	J4852

J4849:	DEC	A
	LD	(D.F55F),A
	LD	A,7FH
	CALL	C4500
J4852:	JP	J47FB

J4855:	CALL	C48BC
I4858:	JR	C,J487E
	LD	A,H
	OR	L
	JR	NZ,J4886
	CALL	C48C7
	JR	C,J487E
	CP	01H	; 1 
	JR	NZ,J487E
	CALL	C48C7
	JR	C,J487E
	CP	0FFH
	JR	NZ,J487E
J4870:	LD	A,47H	; "G"
	CALL	C492E
	CALL	C4954
	CALL	C493B
	JP	J4762

J487E:	LD	A,42H	; "B"
	CALL	C492E
	JP	J47FB

J4886:	CALL	C48C7
	JR	C,J487E
	CP	01H	; 1 
	JR	NZ,J487E
	ADD	A,L
	ADD	A,H
	LD	E,A
	CALL	C48C7
	JR	C,J487E
	ADD	A,E
	JR	NZ,J487E
	CALL	C4929
	JP	C,J47C9
	CP	0AH	; 10 
	JR	NZ,J4870
	LD	A,47H	; "G"
	CALL	C492E
	CALL	C4954
	PUSH	IX
	PUSH	HL
	LD	HL,I48B4
	EX	(SP),HL
	JP	(HL)

I48B4:	POP	IX
	CALL	C493B
	JP	J4762

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C48BC:	CALL	C48C7
	RET	C
	LD	H,A
	CALL	C48C7
	RET	C
	LD	L,A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C48C7:	PUSH	BC
	CALL	C4929
	JR	C,J48E2
	CALL	C48E4
	JR	C,J48E2
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	B,A
	CALL	C4929
	JR	C,J48E2
	CALL	C48E4
	JR	C,J48E2
	ADD	A,B
J48E2:	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C48E4:	CALL	C4B04
	SUB	30H	; "0"
	RET	C
	CP	0AH	; 10 
	JR	C,J48F7
	SUB	11H	; 17 
	RET	C
	CP	06H	; 6 
	CCF
	RET	C
	ADD	A,0AH	; 10 
J48F7:	AND	A
	RET

J48F9:	CALL	CHGET
	EI
	SUB	06H	; 6 
	JR	Z,J490C
	DEC	A
	JR	Z,J4911
	DEC	A
	JR	NZ,J4917
	LD	HL,D.F563
	JR	J4914

J490C:	LD	HL,D.F561
	JR	J4914

J4911:	LD	HL,D.F562
J4914:	LD	A,(HL)
	CPL
	LD	(HL),A
J4917:	JP	J4762

I491A:	AND	B
	LD	B,00H
	LD	L,H
	LD	L,C
	AND	B
	RLCA
	NOP
	LD	L,B
	LD	H,(HL)
	AND	B
	EX	AF,AF'
	NOP
	LD	(HL),B
	LD	H,L
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4929:	CALL	C4C9C
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C492E:	CALL	C4E17
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4933:	LD	DE,I$0064
I4936:	CALL	C4F1B
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C493B:	LD	A,1BH
	CALL	C4500
	LD	A,79H	; "y"
J4942:	CALL	C4500
	LD	A,35H	; "5"
J4947:	CALL	C4500
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C494B:	LD	A,1BH
	CALL	C4500
	LD	A,78H	; "x"
	JR	J4942

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4954:	LD	A,0DH	; 13 
	CALL	C4500
	LD	A,0AH	; 10 
	JR	J4947

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C495D:	LD	A,(INTFLG)
	AND	A			; STOP or CTRL-STOP pressed ?
	RET	Z			; nope, quit
	XOR	A
	LD	(INTFLG),A		; reset STOP or CTRL-STOP flag
	INC	A
	RET

;	  Subroutine _COM handler
;	     Inputs  ________________________
;	     Outputs ________________________

I4968:	CALL	C4A58
	CALL	C4AC1
	CALL	C4A45
	JP	C,J44B8
	CALL	C453B
	INC	L
	CALL	C453B
	ADC	A,L
	LD	IX,LINGET
	CALL	C459D
	PUSH	HL
	LD	A,E
	OR	D
	JR	Z,J4994
	LD	IX,FNDLIN
	CALL	C459D
	JP	NC,J44AC
	LD	E,C
	LD	D,B
J4994:	CALL	C4A32
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	CALL	C453B
	ADD	HL,HL
	AND	A
	RET

;	  Subroutine _COMOFF handler
;	     Inputs  ________________________
;	     Outputs ________________________

I49A2:	CALL	C4A58
	CALL	C4AC1
	LD	A,D
	AND	A
	JR	Z,J49B4
	CP	3AH	; ":"
	JR	Z,J49B4
	CALL	C453B
	ADD	HL,HL
J49B4:	CALL	C4A45
	JP	C,J44B8
	LD	IX,OFFTRP
	JR	J4A07

;	  Subroutine _COMON handler
;	     Inputs  ________________________
;	     Outputs ________________________

I49C0:	CALL	C4A58
	CALL	C4AC1
	LD	A,D
	AND	A
	JR	Z,J49D2
	CP	3AH	; ":"
	JR	Z,J49D2
	CALL	C453B
	ADD	HL,HL
J49D2:	CALL	C4A45
	JP	C,J44B8
	LD	IX,ONTRP
	JR	J49FA

;	  Subroutine _COMSTOP handler
;	     Inputs  ________________________
;	     Outputs ________________________

I49DE:	CALL	C4A58
	CALL	C4AC1
	LD	A,D
	AND	A
	JR	Z,J49F0
	CP	3AH	; ":"
	JR	Z,J49F0
	CALL	C453B
	ADD	HL,HL
J49F0:	CALL	C4A45
	JP	C,J44B8
	LD	IX,STPTRP
J49FA:	PUSH	HL
	PUSH	AF
	CALL	C4A32
	LD	A,(HL)
	AND	01H	; 1 
	CALL	Z,C4147
	POP	AF
	POP	HL
J4A07:	PUSH	HL
	CALL	C4A32
	CALL	C459D
	POP	HL
	AND	A
	RET

I4A11:	EI
	CALL	C4C88
	PUSH	HL
	CALL	NZ,C4A1D
	POP	HL
	JP	OLDSTT

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4A1D:	CALL	C4A32
D$4A20:	LD	A,(HL)
	AND	01H	; 1 
	RET	Z
	LD	A,(HL)
	OR	04H	; 4 
	CP	(HL)
	RET	Z
	CP	05H	; 5 
	RET	NZ
	LD	(HL),A
	LD	HL,ONGSBF
	INC	(HL)
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4A32:	CALL	C4A45
	JP	C,J44B8
	PUSH	BC
	LD	C,A
	ADD	A,A
	ADD	A,C
	LD	C,A
	LD	B,00H
	LD	HL,TRPTBL+18*3
	ADD	HL,BC
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4A45:	LD	A,(DEVNUM)
	AND	0F0H
	RRCA
	RRCA
	RRCA
	RRCA
	CP	06H	; 6 
	CCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4A52:	LD	A,(D.FB1B)
	BIT	3,A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4A58:	DEC	HL
	CALL	C4543
	LD	D,A
	JR	NZ,J4A66
J4A5F:	XOR	A
	LD	BC,D.FFFF
	PUSH	HL
	JR	J4AA4

J4A66:	CP	28H	; "("
	JP	Z,J4A71
	CP	2CH	; ","
	JR	Z,J4A5F
	JR	J4A79

J4A71:	CALL	C4543
	LD	D,A
	CP	2CH	; ","
	JR	Z,J4A5F
J4A79:	CALL	C4555
	PUSH	HL
	CALL	C4585
	LD	C,00H
	LD	B,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	A,B
	AND	A
	JR	Z,J4AA4
	INC	HL
	LD	A,(HL)
	CP	3AH	; ":"
	JR	Z,J4A96
	DEC	HL
	XOR	A
	JR	J4AA4

J4A96:	DEC	HL
	LD	A,(HL)
	SUB	30H	; "0"
	JR	C,J4ABE
	CP	0AH	; 10 
	JR	NC,J4ABE
	INC	HL
	INC	HL
	DEC	B
	DEC	B
J4AA4:	LD	E,A
	LD	A,(DEVNUM)
	AND	0FH	; 15 
	PUSH	HL
	EXX
	POP	HL
	EXX
	POP	HL
	PUSH	AF
	DEC	HL
	CALL	C4543
	LD	D,A
	POP	AF
	CP	E
	RET	Z
J4AB8:	POP	HL
	PUSH	IX
	POP	HL
	SCF
	RET

J4ABE:	POP	HL
	JR	J4AB8

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4AC1:	LD	A,B
	OR	C
	RET	Z
	LD	A,B
	AND	C
	INC	A
	RET	Z
	JP	J44B8

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4ACB:	PUSH	HL
	LD	HL,VALTYP
	LD	A,(HL)
	CP	2
	JR	Z,J4AF9
	CP	4
	JR	Z,J4AE9
	CP	8
	JP	NZ,J44BE
	LD	(HL),2
	PUSH	DE
	LD	A,8
	CALL	C4591
	LD	C,8
	JR	J4AF3

J4AE9:	LD	(HL),02H	; 2 
	PUSH	DE
	LD	A,4
	CALL	C4591
	LD	C,4
J4AF3:	POP	DE
	LD	HL,DAC
	JR	J4AFE

J4AF9:	LD	HL,DAC+2
	LD	C,2
J4AFE:	LD	B,0
	LDIR
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4B04:	CP	61H	; "a"
	RET	C
	CP	7BH	; "{"
	RET	NC
	SUB	20H	; " "
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4B0D:	LD	A,(IY+0)
	SUB	35H	; "5"
	CP	04H	; 4 
	JR	NC,J4B2E
	LD	B,A
	LD	D,A
	CALL	C4BD9
	LD	A,(IY+1)
	CP	45H	; "E"
	JR	Z,J4B30
	CP	4FH	; "O"
	JR	Z,J4B32
	CP	49H	; "I"
	JR	Z,J4B36
	CP	4EH	; "N"
	JR	Z,J4B3C
J4B2E:	SCF
	RET

J4B30:	SET	3,B
J4B32:	SET	2,B
	JR	J4B3C

J4B36:	LD	A,B
	CP	03H	; 3 
	JR	Z,J4B2E
	INC	B
J4B3C:	RLC	B
	RLC	B
	LD	A,(IY+2)
	SUB	31H	; "1"
	CP	03H	; 3 
	JR	NC,J4B2E
	INC	A
	RRCA
	RRCA
	OR	B
	LD	B,A
	LD	C,00H
	LD	A,(IY+3)
	CP	58H	; "X"
	JR	NZ,J4B5B
	SET	0,C
	JR	J4B5F

J4B5B:	CP	4EH	; "N"
	JR	NZ,J4B2E
J4B5F:	LD	A,(IY+4)
	CP	48H	; "H"
	JR	NZ,J4B6A
	SET	1,C
	JR	J4B6E

J4B6A:	CP	4EH	; "N"
	JR	NZ,J4B2E
J4B6E:	LD	A,(IY+5)
	CP	41H	; "A"
	JR	NZ,J4B79
	SET	3,C
	JR	J4B7D

J4B79:	CP	4EH	; "N"
	JR	NZ,J4B2E
J4B7D:	LD	A,(IY+6)
	CP	41H	; "A"
	JR	NZ,J4B88
	SET	2,C
	JR	J4B8C

J4B88:	CP	4EH	; "N"
	JR	NZ,J4B2E
J4B8C:	LD	A,(IY+7)
	CP	53H	; "S"
	JR	NZ,J4B9C
	LD	A,D
	CP	02H	; 2 
	JR	NZ,J4B2E
	SET	4,C
	JR	J4BA0

J4B9C:	CP	4EH	; "N"
	JR	NZ,J4B2E
J4BA0:	LD	A,C
	LD	(ERRORS),A
	LD	A,02H	; 2 
	OR	B
	LD	(LSTCOM),A
	CALL	C4EF0
	LD	E,(IY+8)
	LD	D,(IY+9)
	CALL	C4BED
J4BB6:	JP	C,J4B2E
	LD	C,00H
	CALL	C5017
	LD	E,(IY+10)
	LD	D,(IY+11)
	CALL	C4BED
	JR	C,J4BB6
	LD	C,01H	; 1 
	CALL	C5017
	LD	A,(IY+12)
	LD	(RSTMP),A
	CALL	C4F83
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4BD9:	PUSH	AF
	PUSH	BC
	XOR	03H	; 3 
	LD	C,0FFH
	JR	Z,J4BE6
	LD	B,A
J4BE2:	SRL	C
	DJNZ	J4BE2
J4BE6:	LD	A,C
	LD	(ESTBLS),A
	POP	BC
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4BED:	PUSH	HL
	BIT	7,D
	JR	Z,J4BFF
	LD	A,E
	AND	D
	INC	A
	JR	Z,J4C1B
	LD	HL,X.0000
	SBC	HL,DE
	EX	DE,HL
	JR	J4C1A

J4BFF:	LD	HL,I4C1E
J4C02:	LD	C,(HL)
	INC	HL
	LD	B,(HL)
I4C05:	INC	HL
	LD	A,B
	OR	C
	JR	Z,J4C1B
I4C09	EQU	$-1
	PUSH	HL
	LD	L,E
	LD	H,D
	AND	A
	SBC	HL,BC
	POP	HL
	JR	Z,J4C17
	INC	HL
	INC	HL
	JR	J4C02

J4C17:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
J4C1A:	SCF
J4C1B:	CCF
	POP	HL
	RET

I4C1E:	LD	(X.0000),A
	ADD	HL,BC
	LD	C,E
	DEFB	0,0
	LD	B,6EH	; "n"
	NOP
	RLA
	INC	B
	INC	L
	LD	BC,I$0180
	LD	E,B
	LD	(BC),A
	RET	NZ
	NOP
	OR	B
	INC	B
	LD	H,B
I4C35:	NOP
I4C36:	EX	AF,AF'
	RLCA
	LD	B,B
	NOP
	RET	NC
	RLCA
	LD	A,(D.6000)
	ADD	HL,BC
	JR	NC,J4C42
J4C42:	DJNZ	J4C52
	JR	NZ,J4C46
J4C46:	RET	NZ
	LD	(DE),A
	JR	J4C4A

J4C4A:	JR	NZ,J4C68
	DJNZ	J4C4E
J4C4E:	ADD	A,B
	DEC	H
	INC	C
	DEFB	0
J4C52:	DEFB	0
	LD	C,E
	LD	B,00H
	DEFB	0,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4C58:	PUSH	BC
	PUSH	HL
	IN	A,(0A8H)
	RRCA
	RRCA
	AND	03H	; 3 
	LD	C,A
	LD	B,00H
	LD	HL,EXPTBL
	ADD	HL,BC
	OR	(HL)
J4C68:	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	0CH	; 12 
	OR	C
	POP	HL
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4C74:	PUSH	AF
	LD	A,0FFH
	OUT	(82H),A
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4C7B:	PUSH	AF
	LD	A,0FEH
	OUT	(82H),A
	POP	AF
	RET

I4C82:	CALL	C4D0C
	JP	OLDINT

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4C88:	CALL	C4C97
	PUSH	BC
	LD	B,A
	CALL	C43B1
	JR	Z,J4C94
	LD	A,01H	; 1 
J4C94:	ADD	A,B
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4C97:	LD	A,(DATCNT)
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4C9C:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	HL,DATCNT
J4CA2:	EI
	CALL	C44F4
	JR	C,J4D04
	LD	A,(HL)
	AND	A
	JR	NZ,J4CB8
	CALL	C4F6D			; RTS=1
	CALL	C4DC9			; signal sender to resume sending
	JR	C,J4D04
	JR	Z,J4D04
	JR	J4CA2

J4CB8:	DI
	DEC	(HL)
	CALL	C4DAE
	LD	C,(HL)
	LD	B,81H
	INC	HL
	LD	A,(HL)
	LD	(D.FB1A),A
	AND	A
	JR	NZ,J4CFC
	DEC	B
	LD	A,C
	CP	0DH	; 13 
	JR	NZ,J4CFC
	LD	HL,(FILTAB)
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,(RSFCB)
	RST	20H
	JR	NZ,J4CFC
	PUSH	BC
	CALL	C4DE3
	EI
	JR	C,J4CF9
	JR	Z,J4CF9
	CALL	C4F75
	CALL	C5006
J4CE9:	CALL	C5012
	JR	NC,J4CE9
	CALL	C5006
J4CF1:	CALL	C5012
	JR	NC,J4CF1
	POP	BC
	JR	J4CFC

J4CF9:	POP	BC
	JR	J4D04

J4CFC:	LD	A,C
	OR	A
	DEC	B
J4CFF:	EI
	POP	BC
	POP	DE
	POP	HL
	RET

J4D04:	PUSH	AF
	POP	BC
	RES	7,C
	PUSH	BC
	POP	AF
	JR	J4CFF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4D0C:	CALL	C4F68
	RET	Z
	CALL	C4F4E
	LD	HL,ESTBLS
	AND	(HL)
	LD	C,A
	CALL	C4F54
	LD	B,A
	AND	A
	JR	NZ,J4D39
	LD	HL,D.FB1B
	LD	A,C
	CP	11H	; 17 
	JR	Z,J4D2F
	CP	13H	; 19 
	JR	NZ,J4D4A
	SET	2,(HL)
	JR	J4D31

J4D2F:	RES	2,(HL)
J4D31:	LD	A,(ERRORS)
	BIT	0,A
	RET	NZ
	JR	J4D4A

J4D39:	AND	20H	; " "
	JR	Z,J4D62
	LD	A,C
	AND	A
	JR	NZ,J4D62
	LD	HL,D.FB1B
	SET	4,(HL)
	LD	B,00H
	JR	J4D62

J4D4A:	LD	A,(ERRORS)
	BIT	4,A
	JR	Z,J4D62
	LD	HL,D.FB1B
	LD	A,C
	SUB	0FH	; 15 
	JR	NZ,J4D5C
	RES	7,(HL)
	RET

J4D5C:	INC	A
	JR	NZ,J4D62
	SET	7,(HL)
	RET

J4D62:	LD	HL,DATCNT
	LD	A,(RSIQLN)
	CP	(HL)
	RET	Z
	INC	(HL)
	INC	HL
	PUSH	BC
	CALL	C4DAE
	POP	BC
	LD	A,(ERRORS)
	BIT	4,A
	LD	A,C
	JR	Z,J4D87
	CP	20H	; " "
	JR	C,J4D87
	LD	A,(D.FB1B)
	BIT	7,A
	LD	A,C
	JR	Z,J4D87
	OR	80H
J4D87:	LD	(HL),A
	PUSH	HL
	LD	HL,DATCNT
	LD	A,(RSIQLN)
	SUB	(HL)
	POP	HL
	JR	NZ,J4D95
	SET	7,B
J4D95:	CP	10H	; 16 
	CALL	C,C4DE3
	LD	A,B
	INC	HL
	LD	(HL),A
	DEC	HL
	AND	A
	RET	NZ
	LD	A,(ERRORS)
	BIT	3,A
	RET	Z
	LD	A,(HL)
	CP	0DH	; 13 
	RET	NZ
	LD	C,0AH	; 10 
	JR	J4D62

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4DAE:	INC	HL
	LD	A,(HL)
	LD	C,A
	INC	A
	PUSH	HL
	LD	HL,RSIQLN
	CP	(HL)
	POP	HL
	JR	C,J4DBB
	XOR	A
J4DBB:	LD	(HL),A
	EX	DE,HL
	LD	HL,(RSFCB)
	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	BC,I.0009
	ADD	HL,BC
	RET

;         Subroutine signal sender to resume sending
;	     Inputs  ________________________
;	     Outputs ________________________

C4DC9:	DI
	LD	A,(D.FB1B)
	BIT	1,A
	JR	NZ,J4DD4
	XOR	A
	INC	A
	RET

J4DD4:	LD	C,11H	; 17 
	CALL	C4DFF
	RET	C
	RET	Z
	PUSH	HL
	LD	HL,D.FB1B
	RES	1,(HL)
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4DE3:	DI
	XOR	A
	INC	A
	LD	A,(D.FB1B)
	BIT	1,A
	RET	NZ
	PUSH	HL
	LD	HL,D.FB1B
	SET	1,(HL)
	POP	HL
	LD	C,13H	; 19 
	CALL	C4DFF
	CALL	C4FBE
	CALL	C4F75
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4DFF:	LD	A,(ERRORS)
I4E00	EQU	$-2
	BIT	0,A
	JR	NZ,J4E09
	XOR	A
	INC	A
	RET

J4E09:	CALL	C4FBE
	PUSH	DE
	CALL	C4FCD
	POP	DE
	RET	C
	RET	Z
	LD	A,C
	JP	C4F51

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4E17:	EI
	PUSH	BC
	LD	C,A
	LD	A,(ERRORS)
	BIT	4,A
	JR	Z,J4E59
	LD	A,C
	CP	20H	; " "
	JR	C,J4E59
	LD	A,(D.FB1B)
	BIT	0,A
	JR	NZ,J4E43
	BIT	7,C
	JR	Z,J4E59
	LD	A,0EH	; 14 
	CALL	C4E5B
	JR	C,J4EA5
	JR	Z,J4EA5
	PUSH	HL
	LD	HL,D.FB1B
	SET	0,(HL)
	POP	HL
	JR	J4E57

J4E43:	BIT	7,C
	JR	NZ,J4E57
	LD	A,0FH	; 15 
	CALL	C4E5B
	JR	C,J4EA5
	JR	Z,J4EA5
	PUSH	HL
	LD	HL,D.FB1B
	RES	0,(HL)
	POP	HL
J4E57:	RES	7,C
J4E59:	LD	A,C
	POP	BC
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4E5B:	PUSH	HL
	LD	HL,ERRORS
	BIT	2,(HL)
	POP	HL
	JR	Z,J4E7A
	CP	0AH	; 10 
	JR	NZ,J4E7A
	LD	A,(D.FB1B)
	BIT	5,A
	LD	A,0AH	; 10 
	JR	Z,J4E7A
	PUSH	HL
	LD	HL,D.FB1B
	RES	5,(HL)
	POP	HL
	AND	A
	RET

J4E7A:	PUSH	BC
	LD	C,A
	PUSH	DE
	CALL	C4EAB
	POP	DE
	JR	C,J4EA5
	JR	Z,J4EA5
	CALL	C4FBE
	CALL	C4FCD
	JR	C,J4EA5
	JR	Z,J4EA5
	LD	A,C
	CALL	C4F51
	EI
	PUSH	HL
	LD	HL,D.FB1B
	CP	0DH	; 13 
	JR	NZ,J4EA0
	SET	5,(HL)
	JR	J4EA2

J4EA0:	RES	5,(HL)
J4EA2:	POP	HL
	XOR	A
	INC	A
J4EA5:	CALL	C4EDE
	LD	A,C
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4EAB:	LD	A,(ERRORS)
	BIT	0,A
	JR	Z,J4EDB
	LD	A,(RSTMP)
	LD	D,A
J4EB6:	LD	E,64H	; "d"
J4EB8:	CALL	C5006
J4EBB:	EI
	CALL	C44F4
	DI
	RET	C
	LD	A,(D.FB1B)
	BIT	2,A
	JR	Z,J4EDB
	LD	A,(RSTMP)
	AND	A
	JR	Z,J4EBB
	CALL	C5012
	JR	NC,J4EBB
	AND	A
	DEC	E
	JR	NZ,J4EB8
	DEC	D
	JR	NZ,J4EB6
	RET

J4EDB:	XOR	A
	INC	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4EDE:	PUSH	HL
	LD	HL,D.FB1A
	LD	(HL),00H
	JR	C,J4EEC
	JR	NZ,J4EEE
	SET	6,(HL)
	JR	J4EEE

J4EEC:	SET	2,(HL)
J4EEE:	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4EF0:	XOR	A
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	LD	A,40H	; "@"
	OUT	(81H),A
	PUSH	AF
	POP	AF
	LD	A,(LSTCOM)
	OUT	(81H),A
	PUSH	AF
	POP	AF
	CALL	C4F4E
	CALL	C4F54
	LD	A,07H	; 7 
	CALL	C4FFE
	CALL	C4F4E
	JP	C4F54

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F1B:	PUSH	BC
	DI
	CALL	C4C74
	EI
	LD	A,(COMMSV)
	OR	08H	; 8 
	LD	B,A
J4F27:	CALL	C44F4
	JR	C,J4F3C
	CALL	C4FBE
	XOR	A
	CALL	C4F51
	LD	A,B
	CALL	C4FFE
I4F35	EQU	$-2
	DEC	DE
	LD	A,E
	OR	D
	JR	NZ,J4F27
J4F3C:	PUSH	AF
	CALL	C4FBE
	LD	A,B
	AND	0F7H
	CALL	C4FFE
	DI
	CALL	C4C7B
	EI
	POP	AF
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F4E:	IN	A,(80H)
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F51:	OUT	(80H),A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F54:	IN	A,(81H)
	AND	38H	; "8"
	PUSH	AF
	LD	A,(COMMSV)
	PUSH	AF
	OR	10H	; 16 
	CALL	C4FFE
	POP	AF
	CALL	C4FFE
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F68:	IN	A,(81H)
	AND	02H	; 2 
	RET

;         Subroutine RTS=1
;	     Inputs  ________________________
;	     Outputs ________________________

C4F6D:	PUSH	AF
	LD	A,(COMMSV)
	SET	5,A
	JR	J4F7B

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F75:	PUSH	AF
	LD	A,(COMMSV)
	RES	5,A
J4F7B:	CALL	C4FFE
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F80:	AND	A
	JR	Z,J4F8C
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F83:	DI
	PUSH	AF
	LD	A,(COMMSV)
	OR	02H	; 2 
	JR	J4F93

J4F8C:	DI
	PUSH	AF
	LD	A,(COMMSV)
	AND	0FDH
J4F93:	CALL	C4FFE
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4F98:	PUSH	AF
	IN	A,(82H)
	LD	L,0C1H
	XOR	L
	AND	L
	LD	L,A
	IN	A,(81H)
	AND	80H
	JR	Z,J4FA8
	SET	3,L
J4FA8:	DI
	LD	A,(D.FB1B)
	BIT	4,A
	JR	Z,J4FB7
	SET	2,L
	RES	4,A
	LD	(D.FB1B),A
J4FB7:	EI
	LD	A,(D.FB1A)
	LD	H,A
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4FBE:	PUSH	AF
J4FBF:	EI
	NOP
	NOP
	DI
	IN	A,(81H)
	AND	05H	; 5 
	CP	05H	; 5 
	JR	NZ,J4FBF
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4FCD:	LD	A,(ERRORS)
	BIT	1,A
	JR	Z,J4FFB
	LD	A,(RSTMP)
	LD	D,A
J4FD8:	LD	E,100
J4FDA:	CALL	C5006
J4FDD:	CALL	C44F4
	EI
	RET	C
	IN	A,(82H)
	BIT	7,A
	JR	Z,J4FFB
	LD	A,(RSTMP)
	AND	A
	JR	Z,J4FDD
	CALL	C5012
	JR	NC,J4FDD
	AND	A
	DEC	E
	JR	NZ,J4FDA
	DEC	D
	JR	NZ,J4FD8
	RET

J4FFB:	XOR	A
	INC	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C4FFE:	OUT	(81H),A
	LD	(COMMSV),A
	PUSH	AF
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5006:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	A,0B0H
	LD	C,86H
	LD	DE,04800H
	JR	J5024

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5012:	IN	A,(82H)
	RLCA
	RLCA
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5017:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	A,C
	LD	B,C
	ADD	A,84H
	LD	C,A
	LD	A,B
	RRCA
	RRCA
	OR	36H	; "6"
J5024:	OUT	(87H),A
	OUT	(C),E
	OUT	(C),D
	POP	DE
	POP	BC
	POP	AF
	RET

;
; Toshiba firmware
;
;	

;	  Subroutine ROM extension STATEMENT handler
;	     Inputs  ________________________
;	     Outputs ________________________

C502E:	EI
	PUSH	HL
	LD	HL,I508E
	CALL	C5078
	JP	NC,J515E		; SPOLON
	LD	HL,I5095
	CALL	C5078
	JP	NC,J51AE		; SPOLOFF
	LD	HL,I509D
	CALL	C5078
	JP	NC,J51DE		; LCOPY
	LD	HL,I50A3
	CALL	C5078
	JP	NC,J5061		; JWP
	LD	HL,I50A7
	CALL	C5078
	JP	NC,J5067		; EWP
	POP	HL
	JP	J4162			; MSX serial STATEMENT handler

;	  Subroutine _JWP
;	     Inputs  ________________________
;	     Outputs ________________________

J5061:	CALL	C506D			; check HIMEM
	JP	J6235			; start japanese wordprocessor

;	  Subroutine _EWP
;	     Inputs  ________________________
;	     Outputs ________________________

J5067:	CALL	C506D			; check HIMEM
	JP	J61E3			; start european wordprocessor

;	  Subroutine check HIMEM
;	     Inputs  ________________________
;	     Outputs ________________________

C506D:	LD	A,(HIMEM+1)
	CP	HIGH 0DE00H
	RET	NC
	LD	E,7
	JP	J61C8			; BASIC out of memory error

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5078:	LD	BC,16
	LD	DE,PROCNM
J507E:	LD	A,(DE)
	OR	A
	JR	Z,J5089
	INC	DE
	CPI
	JR	NZ,J508C
	JR	J507E

J5089:	LD	A,(HL)
	OR	A
	RET	Z
J508C:	SCF
	RET

I508E:	DEFB	"SPOLON"
	DEFB	0

I5095:	DEFB	"SPOLOFF"
	DEFB	0

I509D:	DEFB	"LCOPY"
	DEFB	0

I50A3:	DEFB	"JWP"
	DEFB	0

I50A7:	DEFB	"EWP"
	DEFB	0

C50AB:	LD	HL,D.FD19 + 1
	LD	(HL),77H
	INC	HL
	LD	(HL),0C9H

;	  Subroutine Spooler interrupt handler
;	     Inputs  ________________________
;	     Outputs ________________________

C50B4:	XOR	A
	LD	B,A
	LD	HL,D.FD0D
	XOR	A
	OR	(HL)			; already in spooler interrupt handler ?
	LD	A,B
	RET	NZ			; yep, quit
	LD	(HL),H			; flag in spooler interrupt handler
	PUSH	AF
	PUSH	HL
	CALL	C50ED			; if queue is not empty and printer ready, print byte
	CALL	C50DC			; if queue is not empyy and printer ready soon, print byte
	CALL	C50ED			; if queue is not empty and printer ready, print byte
	CALL	C50DC			; if queue is not empyy and printer ready soon, print byte
	CALL	C50ED			; if queue is not empty and printer ready, print byte
	CALL	C50ED			; if queue is not empty and printer ready, print byte
	CALL	C50ED			; if queue is not empty and printer ready, print byte
	CALL	C.FD83
	POP	HL
	XOR	A
	LD	(HL),A			; flag not in spooler interrupt handler
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C50DC:	EI
	LD	A,(D.FD88)
	OR	A			; spooler queue empty ?
	RET	Z			; yep, quit
	LD	B,60
J50E4:	CALL	LPTSTT			; printer ready ?
	JR	NZ,J50F7		; yep,
	DEC	B
	RET	Z
	JR	J50E4

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C50ED:	EI
	LD	A,(D.FD88)
	OR	A			; spooler queue empty ?
	RET	Z			; yep, quit
	CALL	LPTSTT			; printer ready ?
	RET	Z			; nope, quit
J50F7:	LD	A,83H			; slot 3-0 (RAM)
	LD	HL,(D.FD7F)		; spooler GET pointer
	CALL	RDSLT
	EI
	CALL	M08C9			; write byte to printer port (NOT ACCORDING TO MSX RULES!)
	INC	HL
	BIT	7,H
	JR	Z,J510A
	LD	H,0
J510A:	LD	(D.FD7F),HL
	LD	DE,(D.FD81)
	RST	20H
	RET	NZ
	XOR	A
	LD	(D.FD88),A		; spooler queue empty
	RET

;	  Subroutine H.LPTO handler
;	     Inputs  ________________________
;	     Outputs ________________________

C5118:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
J511C:	EI
	CALL	BREAKX			; CTRL-STOP pressed ?
	JR	NC,J512C		; nope,
	XOR	A
	LD	(LPTPOS),A
	POP	AF
	SCF
J5128:	POP	BC
	POP	DE
	POP	HL
	RET

J512C:	DI
	LD	HL,(D.FD81)		; put pointer
	LD	DE,(D.FD7F)		; get pointer
	RST	20H			; buffer empty or full ?
	JR	NZ,J513D		; nope, put in buffer
	LD	A,(D.FD88)
	OR	A			; spooler queue empty ?
	JR	NZ,J511C		; nope, buffer is full, keep waiting
J513D:	POP	AF
	PUSH	AF
	LD	E,A
	LD	A,83H			; slot 3-0 (RAM)
	CALL	WRSLT
	INC	HL
	BIT	7,H			; end of buffer reached ?
	JR	Z,J514C
	LD	H,0			; yep, warp around
J514C:	LD	A,0FFH
	LD	(D.FD81),HL		; update put pointer
	LD	(D.FD88),A		; spooler queue not empty
	EI

;	+0	+0	af
;	+2	+2	bc
;	+4	+4	de
;	+6	+6	hl
;       +8      +8      callf BIOS registers
;       +10     +18     returnaddress CALLF caller
;       +12     +20     returnaddress hook caller

	LD	HL,22
	ADD	HL,SP
	LD	(HL),0D3H
	POP	AF
	JR	J5128

;	  Subroutine _SPOLON
;	     Inputs  ________________________
;	     Outputs ________________________

J515E:	LD	E,36H
	LD	A,(SLTWRK + 0*32 + 0*8 + 0*2 +0)
	BIT	5,A			; ramdisk disabled ?
	JP	NZ,J61C8		; yep, BASIC File already open
	BIT	6,A			; ramdisk in use ?
	JP	NZ,J61C8		; yep, BASIC File already open
	LD	BC,5
	LD	HL,H.TIMI
	LD	DE,C.FD83
	DI
	LDIR				; save H.TIMI
	LD	C,5
	LD	HL,I51A4
	LD	DE,H.TIMI
	LDIR				; install spooler H.TIMI handler
	LD	C,5
	LD	HL,I51A9
	LD	DE,H.LPTO
	LDIR				; install spooler H.LPTO handler
	XOR	A
	LD	(D.FD88),A		; spooler queue empty
	LD	HL,D.FD7F
	LD	B,4
J5196:	LD	(HL),A
	INC	HL
	DJNZ	J5196			; initialize spooler GET/PUT pointers
	DEC	A
	LD	HL,SLTWRK + 0*32 + 0*8 + 0*2 +0
	SET	5,(HL)			; ramdisk disabled
	EI
	POP	HL
	XOR	A
	RET

I51A4:	RST	30H
	DEFB	08FH			; slot 3-3
	DEFW	C50B4
	RET

I51A9:	RST	30H
	DEFB	08FH			; slot 3-3
	DEFW	C5118
	RET

;	  Subroutine _SPOLOFF
;	     Inputs  ________________________
;	     Outputs ________________________

J51AE:	LD	E,36H
	LD	A,(SLTWRK + 0*32 + 0*8 + 0*2 +0)
	BIT	6,A			; ramdisk in use ?
	JP	NZ,J61C8		; yep, BASIC File already open
	BIT	5,A			; ramdisk disabled ?
	JR	Z,J51DC			; nope, quit
	LD	BC,5
	LD	HL,C.FD83
	LD	DE,H.TIMI
	DI
	LDIR
	LD	A,0C9H
	LD	(H.LPTO+0),A
	XOR	A
	LD	(LPTPOS),A
	LD	HL,SLTWRK + 0*32 + 0*8 + 0*2 +0
	RES	5,(HL)			; ramdisk enabled
	EI
	LD	A,0DH	; 13 
	CALL	C.08C9
J51DC:	POP	HL
	RET

;	  Subroutine _LCOPY
;	     Inputs  ________________________
;	     Outputs ________________________

J51DE:	LD	E,3BH
	LD	A,(SLTWRK + 0*32 + 0*8 + 0*2 +0)
	BIT	5,A			; ramdisk disabled ?
	JP	Z,J61C8			; nope, BASIC File not OPEN error
	LD	E,36H
	LD	A,(D.FD88)
	OR	A			; spooler queue empty ?
	JP	NZ,J61C8		; nope, BASIC File already open error
	LD	E,35H
	LD	A,(D.FD81+0)
	OR	A
	JR	NZ,J5200
	LD	A,(D.FD81+1)
	OR	A
	JP	Z,J61C8			; BASIC File not found
J5200:	DI
	LD	HL,0
	LD	(D.FD7F),HL
	LD	A,0FFH
	LD	(D.FD88),A		; spooler queue not empty
	POP	HL
	XOR	A
	EI
	RET

;	  Subroutine interrupt handler (COPY key)
;	     Inputs  ________________________
;	     Outputs ________________________

C5210:	LD	A,(D.7FFF)
	OR	60H			; 01100000b: looks like invoke SRAM on page 2
	LD	(D.7FFF),A
	LD	(D.80BE),SP		; save stack pointer
	LD	SP,I87FF		; temporary stack in SRAM
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	IX
	PUSH	IY
	CALL	C5934			; display ready for screen print ?
	CP	128+15
	JR	Z,J5242			; nope, quit
	CALL	C5BBB			; save PSG volume and silence
	CALL	C52EF			; save RP501 registers
	CALL	C5259			; screen print
I5236:	CALL	C5B9D			; wait for STOP pressed and released
	CALL	C531C			; restore RP501 registers
	CALL	C5BD7			; restore PSG volume
	CALL	C59D3			; restore VDP registers
J5242:	POP	IY
	POP	IX
	POP	BC
	POP	DE
	POP	HL
	LD	SP,(D.80BE)		; restore stack pointer
	LD	A,(D.7FFF)
	AND	9FH			; 10011111b: looks like invoke ROM on page 2
	LD	(D.7FFF),A
	XOR	A			; interrupt handled
	JP	M1437

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5259:	LD	A,(D.80A0)
	AND	0FEH			; screenmode 0 (TEXT40/TEXT80) ?
	JR	NZ,J52AF		; nope,

; screen print TEXT40/TEXT80

	LD	HL,I5295		; long toshiba pasopia iq string
	CALL	C592B			; send string to printer
	CALL	C532B			; send date and time to printer
	CALL	C550B
	XOR	A
J526D:	LD	(D.80B9),A
	CALL	C5928			; send vertical init string to printer
	XOR	A
J5274:	LD	(X.80B8),A
	CALL	C5603
	CALL	C5664
	LD	A,(X.80B8)
	INC	A
	LD	HL,D.80C4
	CP	(HL)
	JR	NZ,J5274
	LD	A,(D.80B9)
	INC	A
	LD	HL,D.80C3
	CP	(HL)
	JR	NZ,J526D
	CALL	C573A			; 2 newlines to printer
	RET

I5295:	DEFB	"   "
I5298:	DEFB	"TOSHIBA  PASOPIA IQ   "
	DEFB	0

J52AF:	LD	HL,I5295		; long toshiba pasopia iq string
	IN	A,(90H)
	BIT	0,A			; unknown printer bit (8/16 switch ?)
	JR	NZ,J52BB
	LD	HL,I5298		; short toshiba pasopia iq string
J52BB:	CALL	C592B			; send string to printer
	CALL	C532B			; send date and time to printer
	CALL	C5380
	LD	A,0FCH
J52C6:	LD	(X.80B8),A
	CALL	C5922
	LD	A,(SR8000+23)		; saved vdp register 23
J52CF:	LD	(D.80B9),A
	CALL	C570D
	CALL	C5731
	LD	A,(D.80B9)
	INC	A
	LD	HL,D.80C3
	CP	(HL)
	JR	NZ,J52CF
	LD	A,(X.80B8)
	SUB	04H
	CP	0FCH
	JR	NZ,J52C6
	CALL	C573A			; 2 newlines to printer
	RET

;	  Subroutine save RP501 registers
;	     Inputs  ________________________
;	     Outputs ________________________

C52EF:	LD	HL,I8140
	IN	A,(0B4H)
	LD	(HL),A
	LD	A,13
	OUT	(0B4H),A
	IN	A,(0B5H)
	INC	HL
	LD	(HL),A
	LD	HL,I8142
	XOR	A
	OUT	(0B5H),A		; select RP-501 bank 0
	LD	A,12
J5305:	OUT	(0B4H),A
	PUSH	AF
	IN	A,(0B5H)
	AND	0FH
	LD	(HL),A
	INC	HL
	POP	AF
	DEC	A
	JR	NZ,J5305		; save bank 0
	LD	A,13
	OUT	(0B4H),A
	LD	A,(HL)
	OR	08H
	OUT	(0B5H),A
	RET

;	  Subroutine restore RP501 registers
;	     Inputs  ________________________
;	     Outputs ________________________

C531C:	LD	HL,I8141
	LD	A,0DH
I5321:	OUT	(0B4H),A
	LD	A,(HL)
	OUT	(0B5H),A
	DEC	HL
	LD	A,(HL)
	OUT	(0B4H),A
	RET

;	  Subroutine send date and time to printer
;	     Inputs  ________________________
;	     Outputs ________________________

C532B:	LD	HL,I8142
	LD	A,(HL)			; saved RP501 register 12
	ADD	A,8
	CP	0AH	; 10 
	JR	C,J5338
I5335:	LD	A,(HL)			; saved RP501 register 12
I5336:	DEC	A
	DEC	A
J5338:	OR	"0"
	CALL	C5B51			; send byte to printer
	INC	HL			; saved RP501 register 11
	LD	A,(HL)
	OR	"0"
	CALL	C5B51			; send byte to printer
	INC	HL			; saved RP501 register 10
	LD	B,2
J5347:	PUSH	BC
	LD	A,"/"
	CALL	C5B51			; send byte to printer
	CALL	C5374
	POP	BC
	DJNZ	J5347
	LD	A," "
	CALL	C5B51			; send byte to printer
	LD	A," "
	CALL	C5B51			; send byte to printer
	INC	HL			; next saved RP501 register
	CALL	C5374
	LD	A,":"
	CALL	C5B51			; send byte to printer
	CALL	C5374
	LD	A,13
	CALL	C5B51			; send byte to printer
	LD	A,10
	CALL	C5B51			; send byte to printer
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5374:	LD	B,2
J5376:	LD	A,(HL)
	INC	HL			; next saved RP501 register
	OR	"0"
	CALL	C5B51			; send byte to printer
	DJNZ	J5376
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5380:	LD	HL,(D.80AB)
	LD	A,(D.80B2)
	LD	DE,I8200
	LD	B,0A0H
J538B:	CALL	C5B22			; read byte from VRAM
	LD	(DE),A
	INC	DE
	INC	HL
	LD	A,(D.80B2)
	DJNZ	J538B
	IN	A,(90H)
	BIT	0,A			; unknown printer bit (8/16 switch ?)
	JR	NZ,J53B0
	LD	HL,I54CB		; <esc>S1152
	LD	(X.80D6),HL
	LD	HL,I54BD		; <esc>P<esc>T12
	CALL	C592B			; send string to printer
	LD	HL,I5EF5		; handler
	LD	(D.80D8),HL
	JR	J53C2

J53B0:	LD	HL,I54E3		; <esc>I0768
	LD	(X.80D6),HL
	LD	HL,I54C4		; <esc>M<esc>T16
	CALL	C592B			; send string to printer
	LD	HL,I5E88		; handler
	LD	(D.80D8),HL
J53C2:	LD	A,(SR8000+9)		; saved vdp register 9
	AND	80H			; 192 lines mode ?
	JR	Z,J53DA			; yep,
	LD	A,212
	LD	(D.80C3),A
	LD	HL,(X.80D6)
	LD	DE,12
	ADD	HL,DE
	LD	(X.80D6),HL		; update vertical init string
	JR	J53DF

J53DA:	LD	A,192
	LD	(D.80C3),A
J53DF:	LD	A,(SR8000+23)
	LD	B,A			; saved vdp register 23
	LD	A,(D.80C3)
	LD	(D.8122),A
	ADD	A,B
	LD	(D.80C3),A
	LD	IX,SR8040
	LD	HL,I8100
	LD	B,16
J53F6:	LD	A,(IX+0)
	LD	D,(IX+1)
	INC	IX
	INC	IX
	CALL	C5853
	LD	(HL),A
	INC	HL
	DJNZ	J53F6
	XOR	A
	LD	DE,D.813A
	CALL	C5FE6
	LD	A,(D.80C0)
	OR	A			; color 0 transparent ?
	JR	NZ,J5463		; nope,
	LD	A,(D.80A0)
	CP	07H			; screenmode 6 ?
	JR	NZ,J544E		; nope,
	LD	A,(SR8000+7)		; saved vdp register 7
	AND	0FH
	PUSH	AF
	RRCA
	RRCA
	AND	03H	; 3 
	LD	DE,X.8132
	CALL	C5FE6
	POP	AF
	AND	03H	; 3 
	LD	DE,D.8134
	CALL	C5FE6
	LD	A,(X.8132)
I5436	EQU	$-1
	LD	C,A
	LD	A,(D.8134)
	ADD	A,C
	RRA
	LD	(D.813A),A
	LD	A,(D.8135)
	LD	C,A
	LD	A,(D.8133)
	ADD	A,C
	RRA
	LD	(D.813B),A
	JR	J5463

J544E:	LD	HL,I8100
	PUSH	HL
	LD	A,(SR8000+7)		; saved vdp register 7
	AND	0FH
	JR	Z,J545B
	LD	L,A
	LD	A,(HL)
J545B:	POP	HL
	LD	(HL),A
	LD	DE,D.813A
	CALL	C5FE6
J5463:	LD	A,(D.80A0)		; screenmode
	LD	HL,I5876
	LD	(D.80D0),HL
	LD	HL,I5BF9
	LD	(D.80D2),HL
	LD	HL,I58D0
	LD	(D.80D4),HL
	CP	02H			; screenmode 3 ?
	RET	Z			; yep, quit
	LD	HL,I5749
	LD	(D.80D0),HL
	CP	03H	; 3 
	RET	Z
	CP	04H	; 4 
	RET	Z
	LD	HL,I5D14
	LD	(D.80D2),HL
	CP	05H	; 5 
	RET	Z
	LD	HL,I580E
	LD	(D.80D0),HL
	CP	06H	; 6 
	RET	Z
	CP	07H	; 7 
	RET	Z
	LD	HL,I583E
	LD	(D.80D0),HL
	LD	HL,I58E1
	LD	(D.80D4),HL
	CP	08H	; 8 
	RET	Z
	LD	HL,I5914
	LD	(D.80D4),HL
	LD	HL,J54FB
	LD	DE,I8100
	LD	BC,16
	LDIR
	RET

I54BD:	DEFB	27,"P"
	DEFB	27,"T12"
	DEFB	0

I54C4:	DEFB	27,"M"
	DEFB	27,"T16"
	DEFB	0

I54CB:	DEFB	13,10
	DEFB	27,"S1152"
	DEFB	0,0,0,0

	DEFB	13,10
	DEFB	27,"S1272"
	DEFB	0,0,0,0

I54E3:	DEFB	13,10
	DEFB	"   "
	DEFB	27,"I0768"
	DEFB	0

	DEFB	13,10
	DEFB	"   "
	DEFB	27,"I0848"
	DEFB	0

J54FB:	DEFB	000H
	DEFB	001H
	DEFB	00CH
	DEFB	00DH
	DEFB	060H
	DEFB	061H
	DEFB	06CH
	DEFB	06DH
	DEFB	09DH
	DEFB	003H
	DEFB	01CH
	DEFB	01FH
	DEFB	0E0H
	DEFB	0E3H
	DEFB	0FCH
	DEFB	0FFH

C550B:	LD	A,(SR8000+7)		; saved vdp register 7
	LD	(D.813C),A
	PUSH	AF
	AND	0FH	; 15 
	LD	DE,X.8132
	CALL	C5FD9
	POP	AF
	RRCA
	RRCA
	RRCA
	RRCA
	AND	0FH	; 15 
	LD	DE,D.8134
	CALL	C5FD9
	LD	HL,X.8132
	LD	DE,D.8134
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J5545
	INC	HL
	INC	DE
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J5545
	LD	A,(D.813C)
	AND	0FH	; 15 
	LD	H,A
	RRCA
	RRCA
	RRCA
	RRCA
	OR	H
	LD	(D.813C),A
J5545:	LD	HL,I55F7
	LD	(X.80D6),HL
	LD	HL,(D.80A7)
	LD	A,H
	AND	0FEH
	LD	H,A
	XOR	A
	LD	L,A
	LD	(D.80A7),HL
	LD	A,(SR8000+9)		; saved vdp register 9
	AND	80H			; 212 lines mode ?
	JR	NZ,J5565		; yep,
	LD	A,48
	LD	(D.80C3),A
	JR	J556A

J5565:	LD	A,48+5
	LD	(D.80C3),A
J556A:	LD	A,(D.80A0)
	OR	A			; screenmode 0 TEXT40 ?
	JR	NZ,J5577		; nope,
	LD	A,40
	LD	(D.80C4),A
	JR	J55D5

J5577:	LD	A,80
	LD	(D.80C4),A
	LD	A,(SR8000+12)		; saved vdp register 12
	LD	(D.813D),A
	PUSH	AF
	AND	0FH	; 15 
	LD	DE,I8136
	CALL	C5FD9
	POP	AF
	RRCA
	RRCA
	RRCA
	RRCA
	AND	0FH	; 15 
	LD	DE,I8138
	CALL	C5FD9
	LD	HL,X.8132
	LD	DE,I8136
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J55B7
	INC	DE
	INC	HL
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J55B7
	LD	A,(D.813C)
	AND	0FH	; 15 
	LD	H,A
	LD	A,(D.813D)
	AND	0F0H
	OR	H
	LD	(D.813D),A
J55B7:	LD	HL,I8136
	LD	DE,I8138
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J55D5
	INC	DE
	INC	HL
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J55D5
	LD	A,(D.813D)
	AND	0FH	; 15 
	LD	H,A
	RRCA
	RRCA
	RRCA
	RRCA
	OR	H
	LD	(D.813D),A
J55D5:	IN	A,(90H)
	BIT	0,A			; unknown printer bit (8/16 switch ?)
	JR	NZ,J55E2
	LD	HL,I55E9
	CALL	C592B			; send string to printer
	RET

J55E2:	LD	HL,I55F0
	CALL	C592B			; send string to printer
	RET

I55E9:	DEC	DE
	LD	C,(HL)
	DEC	DE
	LD	D,H
	LD	SP,I.0036

I55F0:	DEC	DE
	LD	B,H
	DEC	DE
	LD	D,H
	LD	SP,I.0036
I55F7:	DEC	C
	LD	A,(BC)
	JR	NZ,J561B
	JR	NZ,J5618
	LD	D,E
	JR	NC,J5634
	JR	C,J5632
	NOP

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5603:	LD	HL,(D.80A5)
	LD	A,(X.80B8)
	LD	E,A
	LD	D,0
	ADD	HL,DE
	LD	A,(D.80C4)
	LD	E,A
	LD	A,(D.80B9)
	SRL	A
	CALL	C5BB0
J5618	EQU	$-1
	LD	A,(D.80AF)
J561B	EQU	$-1
	CALL	C5B22			; read byte from VRAM
	LD	HL,(D.80A9)
I5621	EQU	$-1
	LD	DE,8
	CALL	C5BB0
	LD	BC,4
	LD	A,(D.80B9)
	BIT	0,A
	JR	Z,J5633
J5632:	ADD	HL,BC
J5633:	LD	A,(D.80B1)
J5634	EQU	$-2
	LD	DE,I80F0
	CALL	C5B40			; read block from VRAM
	LD	DE,I8300
	LD	B,6
J5641:	PUSH	BC
	LD	HL,I80F0
	LD	B,4
J5647:	LD	C,(HL)
	BIT	7,C
	JR	NZ,J5652
	RES	1,A
	RES	0,A
	JR	J5656

J5652:	SET	1,A
	SET	0,A
J5656:	RRCA
	RRCA
	RL	C
	LD	(HL),C
	INC	HL
	DJNZ	J5647
	LD	(DE),A
	INC	DE
	POP	BC
	DJNZ	J5641
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5664:	PUSH	BC
	PUSH	HL
	LD	A,(D.80A0)
	OR	A			; screenmode 0 TEXT40 ?
	JR	NZ,J5686		; nope,
	LD	A,(D.813C)
	CALL	C56FB
	LD	HL,I8300
	LD	B,6
J5677:	LD	A,(HL)
	INC	HL
	PUSH	AF
	CALL	C5B51			; send byte to printer
	POP	AF
	CALL	C5B51			; send byte to printer
	DJNZ	J5677
	POP	HL
	POP	BC
	RET

J5686:	LD	A,(SR8000+13)		; saved vdp register 13
	AND	0F0H			; ON
	LD	A,(D.813C)
	JR	Z,J56E9
	LD	DE,10
	LD	HL,0
	LD	A,(D.80B9)
	SRL	A
	CALL	C5BB0
	LD	A,(X.80B8)
	RRCA
	RRCA
	RRCA
	AND	0FH	; 15 
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(D.80A7)
	ADD	HL,DE
	LD	A,(X.80B0)
	CALL	C5B22			; read byte from VRAM
	LD	C,A
	LD	A,(X.80B8)
	AND	07H	; 7 
	LD	B,A
	INC	B
	LD	A,01H	; 1 
J56BF:	RRCA
	DJNZ	J56BF
	AND	C
	LD	A,(D.813C)
	JR	Z,J56E9
	AND	0FH	; 15 
	LD	B,A
	LD	A,(D.813D)
	LD	C,A
	AND	0FH	; 15 
	CP	B
	LD	A,C
	JR	Z,J56E9
	CALL	C56FB
	LD	HL,I8300
	LD	B,6
J56DD:	LD	A,(HL)
	XOR	0FFH
	CALL	C5B51			; send byte to printer
	INC	HL
	DJNZ	J56DD
	POP	HL
	POP	BC
	RET

J56E9:	CALL	C56FB
	LD	HL,I8300
	LD	B,6
J56F1:	LD	A,(HL)
	CALL	C5B51			; send byte to printer
	INC	HL
	DJNZ	J56F1
	POP	HL
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C56FB:	LD	B,A
	RRCA
	RRCA
	RRCA
	RRCA
	CP	B
	RET	NZ
	LD	HL,I8300
	XOR	A
	LD	B,6
J5708:	LD	(HL),A
	INC	HL
	DJNZ	J5708
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C570D:	LD	HL,I80F0
	LD	B,8
	LD	A,0F0H
J5714:	LD	(HL),A
	INC	HL
	DJNZ	J5714
	LD	HL,(D.80D0)
	LD	DE,I5720
	PUSH	DE
	JP	(HL)

I5720:	LD	HL,(D.80D4)
	LD	DE,I5728
	PUSH	DE
	JP	(HL)

I5728:	LD	HL,(D.80D2)
	LD	DE,I5730
	PUSH	DE
	JP	(HL)

I5730:	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5731:	LD	HL,I5739
	PUSH	HL
	LD	HL,(D.80D8)
	JP	(HL)

I5739:	RET

;	  Subroutine 2 newlines to printer
;	     Inputs  ________________________
;	     Outputs ________________________

C573A:	LD	B,2
J573C:	LD	A,13
	CALL	C5B51			; send byte to printer
	LD	A,10
	CALL	C5B51			; send byte to printer
	DJNZ	J573C
	RET

I5749:	LD	A,(X.80B8)
	RRCA
	RRCA
	RRCA
	AND	1FH
	LD	(D.80B5),A
	LD	A,(D.80B9)
	LD	B,A
	RRCA
	RRCA
	RRCA
	AND	1FH
	LD	(D.80B6),A
	LD	A,B
	AND	07H	; 7 
	LD	(D.80B7),A
	LD	HL,(D.80A5)
	LD	A,(D.80B5)
	LD	L,A
	LD	A,(D.80B6)
	LD	DE,32
	CALL	C5BB0
	LD	A,(D.80AF)
	CALL	C5B22			; read byte from VRAM
	LD	(D.80B4),A
	LD	HL,(D.80A9)
	LD	A,(D.80A0)
	CP	03H			; screenmode 1 ?
	JR	Z,J5792			; yep,
	LD	A,(D.80B6)
	AND	38H	; "8"
	LD	D,A
	LD	E,00H
	ADD	HL,DE
J5792:	LD	A,(D.80B4)
	LD	DE,8
	CALL	C5BB0
	LD	A,(D.80B7)
	ADD	A,L
	LD	L,A
	LD	A,(D.80B1)
	CALL	C5B22			; read byte from VRAM
	LD	HL,I80F3
	LD	(HL),A
	LD	A,(X.80B8)
	BIT	2,A
	JR	NZ,J57B3
	RRD
J57B3:	XOR	A
	RRD
	LD	B,04H	; 4 
J57B8:	LD	(HL),A
	RRCA
	DEC	HL
	DJNZ	J57B8
	LD	A,(D.80A0)
	CP	03H			; screenmode 1 ?
	JR	NZ,J57D5		; nope,
	LD	HL,(D.80A7)
	LD	A,(D.80B4)
	RRCA
	RRCA
	RRCA
	AND	1FH
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	JR	J57EC

J57D5:	LD	HL,(D.80A7)
	LD	A,(D.80B6)
	AND	38H	; "8"
	LD	D,A
	LD	A,(D.80B7)
	LD	E,A
	ADD	HL,DE
	LD	A,(D.80B4)
	LD	DE,8
	CALL	C5BB0
J57EC:	LD	A,(X.80B0)
	CALL	C5B22			; read byte from VRAM
	LD	HL,I80C6
	LD	(HL),A
	XOR	A
	RRD
	LD	E,(HL)
	LD	D,A
	LD	HL,I80F0
	LD	B,04H	; 4 
J5800:	LD	A,(HL)
	BIT	0,A
	JR	Z,J5808
	LD	A,E
	JR	J5809

J5808:	LD	A,D
J5809:	LD	(HL),A
	INC	HL
	DJNZ	J5800
	RET

I580E:	LD	HL,(D.80A5)
	LD	A,(X.80B8)
	LD	E,A
	LD	A,(D.80B9)
	SRL	A
	RR	E
	LD	D,A
	ADD	HL,DE
	LD	A,(D.80AF)
	LD	BC,2
	LD	DE,I80F0
	CALL	C5B40			; read block from VRAM
	LD	A,(D$80F1)
	LD	(D$80F2),A
	LD	HL,I80F0
	LD	B,02H	; 2 
J5835:	XOR	A
	RRD
	INC	HL
	LD	(HL),A
	INC	HL
	DJNZ	J5835
	RET

I583E:	LD	DE,I80F0
	LD	A,(X.80B8)
	LD	L,A
	LD	A,(D.80B9)
	LD	H,A
	LD	BC,4
	LD	A,(D.80AF)
	CALL	C5B40			; read block from VRAM
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5853:	PUSH	HL
	LD	H,A
	RRA
	LD	H,A
	AND	03H
	LD	L,A
	LD	A,H
	RRA
	AND	1CH
	OR	L
	LD	L,A
	LD	A,D
	RRCA
	RRCA
	RRCA
	AND	0E0H
	OR	L
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5869:	PUSH	HL
	PUSH	BC
	LD	HL,I60C8
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	LD	A,(HL)
	POP	BC
	POP	HL
	RET

I5876:	LD	HL,(D.80A5)
	LD	A,(X.80B8)
	RRCA
	RRCA
	RRCA
	AND	1FH
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(D.80B9)
	RRCA
	RRCA
	RRCA
	AND	1FH
	LD	(D.80B6),A
	LD	DE,32
	CALL	C5BB0
	LD	A,(D.80AF)
	CALL	C5B22			; read byte from VRAM
	LD	HL,(D.80A9)
	LD	DE,8
	CALL	C5BB0
	LD	A,(D.80B9)
	RRCA
	RRCA
	AND	07H	; 7 
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(D.80B1)
	CALL	C5B22			; read byte from VRAM
	LD	HL,I80F0
	LD	(HL),A
	LD	A,(X.80B8)
	AND	04H	; 4 
	JR	Z,J58C6
	XOR	A
	RRD
	JR	J58C9

J58C6:	XOR	A
	RLD
J58C9:	LD	B,04H	; 4 
J58CB:	LD	(HL),A
	INC	HL
	DJNZ	J58CB
	RET

I58D0:	LD	DE,I80F0
	LD	B,04H	; 4 
J58D5:	LD	A,(DE)
	CALL	C5F95
	CALL	C5869
	LD	(DE),A
	INC	DE
	DJNZ	J58D5
	RET

I58E1:	LD	HL,I80F0
	LD	B,04H	; 4 
J58E6:	XOR	A
	RRD
	LD	DE,X.8132
	CALL	C5FD9
	LD	A,(HL)
	LD	DE,D.8134
	CALL	C5FD9
	LD	A,(D.8135)
	LD	C,A
	LD	A,(D.8133)
	ADD	A,C
	RRA
	LD	D,A
	LD	A,(D.8134)
	LD	C,A
	LD	A,(X.8132)
	ADD	A,C
	RRA
	CALL	C5853
	CALL	C5869
	LD	(HL),A
	INC	HL
	DJNZ	J58E6
	RET

I5914:	LD	HL,I80F0
	LD	B,04H	; 4 
J5919:	LD	A,(HL)
	CALL	C5869
	LD	(HL),A
	INC	HL
	DJNZ	J5919
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5922:	LD	HL,I8300
	LD	(D.8120),HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5928:	LD	HL,(X.80D6)		; vertical init string

;	  Subroutine send string to printer
;	     Inputs  ________________________
;	     Outputs ________________________

C592B:	LD	A,(HL)
	OR	A
	RET	Z
	CALL	C5B51			; send byte to printer
	INC	HL
	JR	C592B

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5934:	XOR	A
	LD	(D.80C8),A		; assume blink not enabled
	LD	A,6
	CALL	C5B78			; read keyboard row 6
	LD	B,A
	BIT	1,A			; CTRL pressed ?
	JR	NZ,C5962		; nope, restore vdp status register and quit
	LD	A,B
	AND	01H
	LD	(D.80E5),A		; SHIFT status
	LD	A,(SR8000+1)		; saved vdp register 1
	BIT	6,A			; display enabled ?
	JR	Z,C5962			; nope, restore vdp status register and quit
	LD	A,2
	OUT	(99H),A
	LD	A,128+15
	OUT	(99H),A			; select VDP status register 2
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(99H)			; read VDP status register
	LD	(D.80C9),A
	BIT	0,A			; command executing ?
	JR	Z,J596C			; nope,

;	  Subroutine restore vdp status register
;	     Inputs  ________________________
;	     Outputs ________________________

C5962:	LD	A,(SR8000+15)		; saved vdp register 15
	OUT	(99H),A
	LD	A,128+15
	OUT	(99H),A			; select VDP status register
	RET

J596C:	CALL	C5962			; restore vdp status register
	CALL	C5A07			; get screen mode
	CALL	C5A61			; get screen addressing
	LD	A,(D.80A0)
	CP	06H			; screenmode 0, 3, 1, 2 or 4 ?
	RET	C			; yep, quit
	LD	A,(SR8000+2)		; saved vdp register 2
	AND	20H			; A14=1 ?
	RET	Z			; nope, skip odd/even check, quit
	LD	A,(SR8000+13)
	LD	B,A			; saved vdp register 13
	AND	0F0H			; ON
	JR	Z,J59AE			; odd/even is disabled,
	RRCA
	RRCA
	RRCA
	RRCA
	LD	H,A
	LD	A,B			; saved vdp register 13
	AND	0FH
	SUB	H
	JR	NC,J59AE
J5994:	CALL	C59C0
	LD	A,0F0H			; display odd page

J5999:	OUT	(99H),A
	LD	A,128+13
	OUT	(99H),A			; vdp blink register
	LD	(D.80C8),A
	LD	A,(SR8000+9)		; saved vdp register 9
	AND	0F3H			; IL = 0, EO = 0
	OUT	(99H),A
	LD	A,128+9
	OUT	(99H),A			; interlace off
	RET

J59AE:	LD	A,(SR8000+9)		; saved vdp register 9
	AND	04H			; EO = 0 ?
	JR	Z,J59BC			; yep,
	LD	A,(D.80C9)		; vdp status register 2
	AND	04H			; unknown bit, should be 1
	JR	Z,J5994
J59BC:	LD	A,0FH			; blinking off
	JR	J5999			; interlace off, even/odd off and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C59C0:	LD	A,(D.80A0)
	CP	08H			; screenmode 7 or 8 ?
	JR	C,J59CC			; nope,
	XOR	A
	LD	(D.80AF),A
	RET

J59CC:	LD	HL,0
	LD	(D.80A5),HL
	RET

;	  Subroutine restore VDP registers
;	     Inputs  ________________________
;	     Outputs ________________________

C59D3:	LD	A,(SR8060)
	OUT	(99H),A
	LD	A,128+14
	OUT	(99H),A			; write adress latch register
	LD	A,(SR8062)
	OUT	(99H),A
	LD	A,(SR8061)
	OUT	(99H),A
	LD	A,(D.80C8)
	OR	A			; blink enabled ?
	RET	Z			; nope, quit
	LD	A,(SR8000+13)		; saved vdp register 13
	OUT	(99H),A
	LD	A,128+13
	OUT	(99H),A			; vdp blink register
	LD	A,(SR8000+2)		; saved vdp register 2
	OUT	(99H),A
	LD	A,128+2
	OUT	(99H),A			; vdp pattern name table base address
	LD	A,(SR8000+9)		; saved vdp register 9
	OUT	(99H),A
	LD	A,128+9
	OUT	(99H),A			; vdp register 9
	RET

;	  Subroutine get screen mode
;	     Inputs  ________________________
;	     Outputs ________________________

C5A07:	LD	A,(SR8000+0)		; saved vdp register 0
	LD	C,A
	LD	A,(SR8000+1)		; saved vdp register 1
	LD	B,A
	AND	18H			; M1 M2
	CP	10H			; TEXT40 or TEXT80 ?
	JR	Z,J5A26			; yep,
	CP	08H			; screenmode 3 ?
	JR	Z,J5A2F			; yep,
	LD	A,C
	AND	0EH			; M5 M4 M3
	RRCA
	ADD	A,3
	CP	10			; screenmode 8 ?
	JR	NZ,J5A31		; nope,
	DEC	A			; screenmode 8 = 9
	JR	J5A31

J5A26:	LD	A,C
	AND	04H
	RRCA
	RRCA
	LD	(D.80A0),A		; TEXT40 = 0, TEXT80 = 1
	RET

J5A2F:	LD	A,2			; screenmode 3 = 2
J5A31:	LD	(D.80A0),A
	LD	A,B
	AND	03H			; 8*8 sprites without magnification ?
	JR	Z,J5A45			; yep,
	CP	03H			; 16*16 sprites with magnification ?
	JR	Z,J5A41			; yep,
	LD	A,0F0H
	JR	J5A47

J5A41:	LD	A,0E0H
	JR	J5A47

J5A45:	LD	A,0F8H
J5A47:	LD	(D.80A2),A
	LD	A,B
	RRCA
	AND	01H
	LD	(D.80A3),A		; sprite size
	LD	A,(SR8000+8)		; saved vdp register 8
	LD	B,A
	AND	20H			; transparent mode
	LD	(D.80C0),A
	LD	A,B
	AND	02H			; sprite disable
	LD	(D.80A4),A
	RET

;	  Subroutine get screen addressing
;	     Inputs  ________________________
;	     Outputs ________________________

C5A61:	LD	B,02H	; 2 
	LD	A,(SR8000+2)		; saved vdp register 2
	LD	H,A
	LD	L,0
	CALL	C5AED
	LD	(D.80A5),HL
	LD	(D.80AF),A
	LD	B,06H	; 6 
	LD	A,(SR8000+10)		; saved vdp register 10
	LD	H,A
	LD	A,(SR8000+3)		; saved vdp register 3
	LD	L,A
	CALL	C5AED
	LD	(D.80A7),HL
	LD	(X.80B0),A
	LD	B,03H	; 3 
	LD	A,(SR8000+4)		; saved vdp register 4
	LD	H,A
	LD	L,00H
	CALL	C5AED
	LD	(D.80A9),HL
	LD	(D.80B1),A
	LD	B,07H	; 7 
	LD	A,(SR8000+11)		; saved vdp register 11
	LD	H,A
	LD	A,(SR8000+5)		; saved vdp register 5
	LD	L,A
	CALL	C5AED
	LD	(D.80AB),HL
	LD	(D.80B2),A
	LD	B,03H	; 3 
	LD	A,(SR8000+6)		; saved vdp register 6
	LD	H,A
	LD	L,00H
	CALL	C5AED
	LD	(D.80AD),HL
	LD	(X.80B3),A
	LD	A,(D.80A0)		; screenmode
	LD	HL,I5AF6
	LD	DE,2
	CALL	C5BB0
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	A,D
	OR	E
	JR	Z,J5AD9
	LD	HL,D.80A5
	LD	B,8
J5AD2:	LD	A,(DE)
	AND	(HL)
	LD	(HL),A
	INC	HL
	INC	DE
	DJNZ	J5AD2
J5AD9:	LD	A,(D.80A0)
	BIT	3,A			; screenmode 7 or 8 ?
	RET	Z			; nope, quit
	LD	HL,(D.80A5)
	XOR	A
	SLA	H
	RLA
	LD	(D.80AF),A
	LD	(D.80A5),HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5AED:	XOR	A
J5AEE:	SLA	L
	RL	H
	DJNZ	J5AEE
	RLA
	RET

I5AF6:	DEFB	0,0
	LD	A,(BC)
	LD	E,E
	DEFB	0,0,0,0
	LD	(DE),A
	LD	E,E
	LD	(DE),A
	LD	E,E
	LD	A,(DE)
	LD	E,E
	LD	A,(DE)
	LD	E,E
	LD	A,(DE)
	LD	E,E
J5B08:	LD	A,(DE)
	LD	E,E
	NOP
	RET	P
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	NOP
	RET	PO
	NOP
	RET	PO
	RST	38H
	RST	38H
	NOP
	ADD	A,B
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	NOP
	DEFB	0FEH

;	  Subroutine read byte from VRAM
;	     Inputs  AHL = VRAM address
;	     Outputs ________________________

C5B22:	PUSH	BC
	LD	B,H
	RL	B
	RLA
	RL	B
	RLA
	AND	07H
	OUT	(99H),A
	LD	A,128+14
	OUT	(99H),A
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH
	OUT	(99H),A			; set VRAM address latch for reading
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(98H)
	POP	BC
	RET

;	  Subroutine read block from VRAM
;	     Inputs  AHL = VRAM address, BC = size
;	     Outputs ________________________

C5B40:	CALL	C5B22			; read byte from VRAM
	DEC	BC
	LD	(DE),A
J5B45:	INC	DE
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(98H)
	LD	(DE),A
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J5B45
	RET

;	  Subroutine send byte to printer
;	     Inputs  ________________________
;	     Outputs ________________________

C5B51:	PUSH	AF
	PUSH	BC
	LD	B,4
J5B55:	CALL	C5B8B			; CTRL-STOP pressed ?
	JR	Z,J5B6C			; yep,
	CALL	C5B73			; get printer status
	JR	C,J5B55			; busy, wait
	DJNZ	J5B55
	POP	BC
	POP	AF
	OUT	(91H),A			; set data
	XOR	A
	OUT	(90H),A
	INC	A
	OUT	(90H),A			; strobe
	RET

J5B6C:	LD	SP,I87F5
	LD	HL,I5236
	JP	(HL)

;	  Subroutine get printer status
;	     Inputs  ________________________
;	     Outputs ________________________

C5B73:	IN	A,(90H)
	RRCA
	RRCA
	RET

;	  Subroutine read keyboard row
;	     Inputs  ________________________
;	     Outputs ________________________

C5B78:	PUSH	BC
	LD	B,A
	IN	A,(0AAH)
	PUSH	AF
	AND	0F0H
	OR	B
	OUT	(0AAH),A
	IN	A,(0A9H)
	LD	B,A
	POP	AF
	OUT	(0AAH),A
	LD	A,B
	POP	BC
	RET

;	  Subroutine CTRL-STOP pressed ?
;	     Inputs  ________________________
;	     Outputs ________________________

C5B8B:	LD	A,6
	CALL	C5B78			; read keyboard row 6
	BIT	1,A			; CTRL pressed ?
	RET	NZ			; nope, quit
	LD	A,7
	CALL	C5B78			; read keyboard row 7
	BIT	4,A			; STOP pressed ?
	RET	NZ			; nope, quit
	XOR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5B9D:	LD	A,7
	CALL	C5B78			; read keyboard row 7
	BIT	4,A			; STOP pressed ?
	JR	NZ,C5B9D		; nope,wait
J5BA6:	LD	A,7
	CALL	C5B78			; read keyboard row 7
	BIT	4,A			; STOP pressed ?
	JR	Z,J5BA6			; yep, wait
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5BB0:	PUSH	BC
	LD	B,A
	INC	B
J5BB3:	ADD	HL,DE
	DJNZ	J5BB3
	OR	A
	SBC	HL,DE
	POP	BC
	RET

;	  Subroutine save PSG volume and silence
;	     Inputs  ________________________
;	     Outputs ________________________

C5BBB:	LD	HL,I80E0
	IN	A,(0A0H)
	LD	(D.813F),A
	LD	A,8
	LD	B,3
	LD	E,0
J5BC9:	PUSH	AF
	CALL	C5BEC			; read PSG register
	LD	(HL),A
	POP	AF
	CALL	C5BF1			; write PSG register
	INC	A
	INC	HL
	DJNZ	J5BC9
	RET

;	  Subroutine restore PSG volume
;	     Inputs  ________________________
;	     Outputs ________________________

C5BD7:	LD	HL,I80E0
	LD	B,3
	LD	A,8
J5BDE:	LD	E,(HL)
	CALL	C5BF1
	INC	HL
	INC	A
	DJNZ	J5BDE
	LD	A,(D.813F)
	OUT	(0A0H),A
	RET

;	  Subroutine read PSG register
;	     Inputs  ________________________
;	     Outputs ________________________

C5BEC:	OUT	(0A0H),A
	IN	A,(0A2H)
	RET

;	  Subroutine write PSG register
;	     Inputs  ________________________
;	     Outputs ________________________

C5BF1:	PUSH	AF
	OUT	(0A0H),A
	LD	A,E
	OUT	(0A1H),A
	POP	AF
	RET

I5BF9:	LD	A,(D.80A4)
	OR	A			; sprites disabled ?
	RET	NZ			; yep, quit
	LD	A,(X.80B8)
	LD	(D.80CD),A
	CALL	C5C1D
	LD	A,(D.80B7)
	OR	A
	RET	Z
	LD	B,03H	; 3 
J5C0E:	PUSH	BC
	LD	A,(D.80CD)
	INC	A
	LD	(D.80CD),A
	CALL	C5C1D
	POP	BC
	DJNZ	J5C0E
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5C1D:	XOR	A
	LD	(D.80B7),A
	LD	HL,I8200
	LD	(D.80CB),HL
	LD	B,20H	; " "
J5C29:	LD	HL,(D.80CB)
	LD	A,(HL)
	CP	0D0H
	RET	Z
	INC	A
	LD	D,A
	LD	A,(D.80B9)
	SUB	D
	LD	(D.80B6),A
	LD	D,A
	LD	A,(D.80A2)
	AND	D
	CALL	Z,C5C50
	OR	A
	RET	Z
	LD	HL,(D.80CB)
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(D.80CB),HL
	DJNZ	J5C29
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5C50:	LD	A,(D.80B7)
	INC	A
	CP	05H	; 5 
	RET	Z
	LD	(D.80B7),A
	INC	HL
	LD	A,(HL)
	LD	(D.80B5),A
	INC	HL
	LD	A,(HL)
	LD	(D.80B4),A
	INC	HL
	LD	A,(HL)
	LD	(D.80CA),A
	LD	D,A
	AND	0FH	; 15 
	JR	NZ,J5C77
	LD	A,(D.80C0)
	OR	A			; color 0 transparent ?
	JR	NZ,J5C77		; nope,
	LD	A,0FFH
	RET

J5C77:	BIT	7,D
	JR	Z,J5C8D
	LD	A,(D.80B5)
	OR	A
	SUB	20H	; " "
	LD	(D.80B5),A
	JR	NC,J5C8D
	LD	A,(D.80CD)
	OR	A
	CP	0E0H
	RET	NC
J5C8D:	LD	A,(D.80B5)
	LD	D,A
	LD	A,(D.80CD)
	SUB	D
	LD	(D.80B5),A
	LD	HL,D.80A2
	AND	(HL)
	RET	NZ
	LD	A,(D.80A3)
	OR	A			; sprite size 8x8 ?
	JP	Z,J5CAC			; yep,
	LD	A,(D.80B4)
	AND	0FCH
	LD	(D.80B4),A
J5CAC:	LD	HL,(D.80AD)
	LD	A,(D.80B4)
	LD	DE,8
	CALL	C5BB0
	LD	A,(SR8000+1)		; saved vdp register 1
	AND	010H			; sprite magnified ?
	JR	Z,J5CCF			; nope,
	LD	A,(D.80B6)
	SRA	A
	LD	(D.80B6),A
	LD	A,(D.80B5)
	SRA	A
	LD	(D.80B5),A
J5CCF:	LD	A,(D.80B6)
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(D.80B5)
	AND	08H	; 8 
	JR	Z,J5CE1
	LD	DE,C.0010
	ADD	HL,DE
J5CE1:	LD	A,(X.80B3)
	CALL	C5B22			; read byte from VRAM
	LD	D,A
	PUSH	BC
	LD	A,(D.80B5)
	LD	B,A
	INC	B
	LD	A,01H	; 1 
J5CF0:	RRCA
	DJNZ	J5CF0
	POP	BC
	AND	D
	JR	NZ,J5CFA
	LD	A,0FFH
	RET

J5CFA:	LD	A,(D.80CD)
	AND	03H	; 3 
	LD	E,A
	LD	D,00H
	LD	HL,I80F0
	ADD	HL,DE
	LD	A,(D.80CA)
	AND	0FH	; 15 
	CALL	C5F95
	CALL	C5869
	LD	(HL),A
	XOR	A
	RET

I5D14:	LD	A,(D.80A4)
	OR	A			; sprites disabled ?
	RET	NZ			; yep, quit
	LD	A,(X.80B8)
	LD	(D.80CD),A
	CALL	C5D38
	LD	A,(D.80CF)
	OR	A
	RET	Z
	LD	B,03H	; 3 
J5D29:	PUSH	BC
	LD	A,(D.80CD)
	INC	A
	LD	(D.80CD),A
	CALL	C5D38
	POP	BC
	DJNZ	J5D29
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5D38:	XOR	A
	LD	(D.80B7),A
	LD	(D.80CF),A
	LD	(D.80CE),A
	LD	(D.80DA),A
	LD	(X.80DB),A
	LD	HL,I8200
	LD	(D.80CB),HL
	LD	B,20H	; " "
J5D50:	LD	HL,(D.80CB)
	LD	A,(HL)
	CP	0D8H
	JR	Z,J5D7C
	INC	A
	LD	D,A
	LD	A,(D.80B9)
	SUB	D
	LD	(D.80B6),A
	LD	D,A
	LD	A,(D.80A2)
	AND	D
	CALL	Z,C5DA2
	LD	HL,(D.80CB)
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(D.80CB),HL
	LD	A,(X.80DB)
	INC	A
	LD	(X.80DB),A
	DJNZ	J5D50
J5D7C:	LD	A,(D.80DA)
	OR	A
	RET	Z
	LD	A,(D.80CD)
	AND	03H	; 3 
	LD	E,A
	LD	D,00H
	LD	HL,I80F0
	ADD	HL,DE
	LD	A,(D.80CE)
	AND	0FH	; 15 
	JR	NZ,J5D9A
	LD	A,(D.80C0)
	OR	A			; color 0 transparent ?
	RET	Z			; yep, quit
	XOR	A
J5D9A:	CALL	C5F95
	CALL	C5869
	LD	(HL),A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5DA2:	LD	A,(D.80B7)
	INC	A
	CP	09H	; 9 
	RET	Z
	LD	(D.80B7),A
	INC	HL
	LD	A,(HL)
	LD	(D.80B5),A
	INC	HL
	LD	A,(HL)
	LD	(D.80B4),A
	LD	HL,(D.80AB)
	DEC	H
	DEC	H
	LD	DE,16
	LD	A,(X.80DB)
	CALL	C5BB0
	LD	A,(SR8000+1)		; saved vdp register 1
	AND	01H			; sprite magnified ?
	LD	A,(D.80B6)
	JR	Z,J5DD0			; nope,
	SRA	A
J5DD0:	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(D.80B2)
	CALL	C5B22			; read byte from VRAM
	LD	(D.80CA),A
	BIT	6,A
	JR	NZ,J5DED
	LD	A,(D.80DA)
	OR	A
	JP	NZ,J5E84
	LD	A,01H	; 1 
	LD	(D.80CF),A
J5DED:	LD	A,(D.80CF)
	OR	A
	RET	Z
	LD	A,(D.80CA)
	BIT	7,A
	JR	Z,J5E0B
	LD	A,(D.80B5)
	OR	A
	SUB	20H	; " "
	LD	(D.80B5),A
	JR	NC,J5E0B
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5E04:	LD	A,(D.80CD)
	OR	A
	CP	0E0H
	RET	NC
J5E0B:	LD	A,(D.80B5)
	LD	D,A
	LD	A,(D.80CD)
	SUB	D
	LD	(D.80B5),A
	LD	D,A
	LD	A,(D.80A2)
	AND	D
	RET	NZ
	LD	A,(D.80A3)
	OR	A			; sprite size 8x8 ?
	JR	Z,J5E2A			; yep,
	LD	A,(D.80B4)
	AND	0FCH
	LD	(D.80B4),A
J5E2A:	LD	HL,(D.80AD)
	LD	A,(D.80B4)
	LD	DE,8
	CALL	C5BB0
	LD	A,(SR8000+1)		; saved vdp register 1
	AND	01H			; sprites magnified ?
	JR	Z,J5E4D			; nope,
	LD	A,(D.80B6)
	SRA	A
	LD	(D.80B6),A
	LD	A,(D.80B5)
	SRA	A
	LD	(D.80B5),A
J5E4D:	LD	A,(D.80B6)
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(D.80B5)
	AND	08H	; 8 
	JR	Z,J5E5F
	LD	DE,C.0010
	ADD	HL,DE
J5E5F:	LD	A,(X.80B3)
	CALL	C5B22			; read byte from VRAM
	LD	D,A
	PUSH	BC
	LD	A,(D.80B5)
	LD	B,A
	INC	B
	LD	A,01H	; 1 
J5E6E:	RRCA
	DJNZ	J5E6E
	POP	BC
	AND	D
	RET	Z
	LD	HL,D.80CE
	LD	A,(D.80CA)
	AND	0FH	; 15 
	OR	(HL)
	LD	(HL),A
	LD	A,0FFH
	LD	(D.80DA),A
	RET

J5E84:	POP	HL
	JP	J5D7C

I5E88:	LD	HL,I80F0
	LD	A,(HL)
	LD	DE,I8110
	CALL	C5ED3
	INC	HL
	LD	A,(HL)
	LD	DE,I8114
	CALL	C5ED3
	INC	HL
	LD	A,(HL)
	LD	DE,I8118
	CALL	C5ED3
	INC	HL
	LD	A,(HL)
	LD	DE,I811C
	CALL	C5ED3
	LD	IX,I8110
	LD	B,04H	; 4 
J5EB0:	LD	A,(IX+8)
	RRCA
	RRCA
	RRCA
	RRCA
	LD	C,A
	LD	A,(IX+12)
	OR	C
	CALL	C5B51			; send byte to printer
	LD	A,(IX+0)
	RRCA
	RRCA
	RRCA
	RRCA
	LD	C,A
	LD	A,(IX+4)
	OR	C
	CALL	C5B51			; send byte to printer
	INC	IX
	DJNZ	J5EB0
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5ED3:	PUSH	HL
	PUSH	DE
	PUSH	AF
	LD	A,(D.80E5)
	OR	A			; SHIFT pressed ?
	JR	NZ,J5EE3		; nope,
	POP	AF
	LD	H,A
	LD	A,18H
	SUB	H
	JR	J5EE4

J5EE3:	POP	AF
J5EE4:	LD	HL,I6064
	LD	DE,4
	CALL	C5BB0
	POP	DE
	LD	BC,4
	LDIR
	POP	HL
	RET

I5EF5:	LD	HL,I80F0
	LD	A,(HL)
	LD	DE,I8110
	CALL	C5F6E
	INC	HL
	LD	A,(HL)
	LD	DE,I8114
	CALL	C5F6E
	INC	HL
	LD	A,(HL)
	LD	DE,I8118
	CALL	C5F6E
	INC	HL
	LD	A,(HL)
	LD	DE,I811C
	CALL	C5F6E
	LD	IX,I8110
	LD	HL,(D.8120)
	LD	B,4
J5F20:	LD	A,(IX+8)
	RLCA
	RLCA
	RLCA
	LD	C,A
	LD	A,(IX+12)
	OR	C
	CALL	C5B51			; send byte to printer
	LD	A,(IX+0)
	RLCA
	RLCA
	RLCA
	LD	C,A
	LD	A,(IX+4)
	OR	C
	LD	(HL),A
	INC	HL
	INC	IX
	BIT	0,B
	CALL	NZ,C5F90
	DJNZ	J5F20
	LD	(D.8120),HL
	LD	A,(D.80B9)
	INC	A
	LD	C,A
	LD	A,(D.80C3)
	CP	C
	RET	NZ
	CALL	C5922
	LD	HL,I8300
	LD	A,(D.8122)
	LD	B,A
J5F5B:	PUSH	BC
	LD	B,4
J5F5E:	LD	A,(HL)
	CALL	C5B51			; send byte to printer
	INC	HL
	BIT	0,B
	CALL	NZ,C5F90
	DJNZ	J5F5E
	POP	BC
	DJNZ	J5F5B
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5F6E:	PUSH	HL
	PUSH	DE
	PUSH	AF
	LD	A,(D.80E5)
	OR	A			; SHIFT pressed ?
	JR	NZ,J5F7E		; nope,
	POP	AF
	LD	H,A
	LD	A,18H
	SUB	H
	JR	J5F7F

J5F7E:	POP	AF
J5F7F:	LD	HL,D.6000
	LD	DE,4
	CALL	C5BB0
	POP	DE
	LD	BC,4
	LDIR
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5F90:	XOR	A
	CALL	C5B51			; send byte to printer
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5F95:	PUSH	DE
	LD	D,A
	LD	A,(D.80A0)
	CP	07H			; screenmode 6 ?
	LD	A,D
	POP	DE
	JR	Z,J5FA8			; yep,
	PUSH	HL
	LD	HL,I8100
	LD	L,A
	LD	A,(HL)
	POP	HL
	RET

J5FA8:	PUSH	BC
	PUSH	DE
	PUSH	AF
	RRCA
	RRCA
	AND	03H	; 3 
	LD	DE,X.8132
	CALL	C5FD9
	POP	AF
	AND	03H	; 3 
	LD	DE,D.8134
	CALL	C5FD9
	LD	A,(D.8135)
	LD	C,A
	LD	A,(D.8133)
	OR	A
	ADD	A,C
	RRA
	LD	D,A
	LD	A,(D.8134)
	LD	C,A
	LD	A,(X.8132)
	OR	A
	ADD	A,C
	RRA
	CALL	C5853
	POP	DE
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5FD9:	OR	A
	JR	NZ,C5FE6
	LD	A,(D.813A)
	LD	(DE),A
	INC	DE
	LD	A,(D.813B)
	LD	(DE),A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C5FE6:	OR	A
	JR	NZ,J5FED
	LD	(DE),A
	INC	DE
	LD	(DE),A
	RET

J5FED:	PUSH	HL
	PUSH	DE
	RLCA
	LD	HL,SR8040
	LD	E,A
	LD	D,0
	ADD	HL,DE
	POP	DE
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	LD	A,(HL)
	LD	(DE),A
	POP	HL
	RET

D.6000:	RLCA
	RLCA
	RLCA
	RLCA
	NOP
	LD	B,07H	; 7 
	RLCA
	NOP
	RLCA
	DEC	B
	DEC	B
	LD	(BC),A
	DEC	B
	DEC	B
	INC	BC
	LD	(BC),A
	DEC	B
	LD	(BC),A
	INC	B
	NOP
	INC	BC
	INC	BC
	DEC	B
	DEC	B
	DEC	B
	DEC	B
	DEC	B
	NOP
	RLCA
	RLCA
	NOP
	LD	(BC),A
	INC	B
	DEC	B
	LD	(BC),A
	NOP
	DEC	B
	DEC	B
	DEC	B
	LD	BC,I.0402
	LD	(BC),A
	NOP
	INC	BC
	INC	BC
	LD	(BC),A
	NOP
	INC	BC
	LD	B,00H
	NOP
	INC	BC
	INC	BC
	DEFB	0,0
	LD	BC,I.0300
	LD	BC,I.0401
	INC	B
	NOP
	LD	BC,I.0402
	NOP
	LD	BC,I.0003
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	DEFB	0,0
	INC	BC
	DEFB	0,0
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	NOP
	LD	BC,J.0002
	NOP
	LD	(BC),A
	LD	BC,X.0000
	NOP
	LD	(BC),A
	DEFB	0,0,0,0,0
I6064:	RRCA
	RRCA
	RRCA
	RRCA
	RRCA
	ADD	HL,BC
	ADD	HL,BC
	RRCA
	RRCA
	INC	BC
	INC	BC
	INC	BC
	INC	BC
	INC	BC
	INC	C
	INC	C
	RLCA
	RLCA
	RLCA
	NOP
	DEC	B
	LD	(BC),A
	DEC	B
	RLCA
	NOP
	DEC	B
	LD	(BC),A
	RLCA
	DEC	B
	LD	(BC),A
	DEC	B
	NOP
	LD	(BC),A
	INC	B
	INC	B
	DEC	B
	NOP
	INC	BC
	INC	BC
	LD	(BC),A
	NOP
	LD	A,(BC)
	INC	B
	LD	A,(BC)
	LD	BC,I.0402
	LD	(BC),A
	NOP
	INC	BC
	LD	B,00H
	NOP
	INC	BC
	INC	BC
	NOP
	LD	BC,I.0401
	INC	B
	NOP
	LD	BC,I.0300
	NOP
	LD	(BC),A
	INC	BC
	DEFB	0,0
	LD	BC,I.0402
	LD	(BC),A
	NOP
	LD	(BC),A
	LD	(BC),A
	DEFB	0,0
	INC	BC
	DEFB	0,0
	LD	(BC),A
	LD	BC,X.0000
	LD	BC,J.0002
	NOP
	LD	(BC),A
	NOP
	LD	(BC),A
	NOP
	LD	(BC),A
	DEFB	0,0,0,0,0,0
I60C8:	DEFB	0,0
	INC	BC
	INC	BC
	DEFB	0,0
	INC	BC
	INC	BC
	NOP
	LD	BC,I.0403
	NOP
	LD	BC,I.0403
	LD	B,06H	; 6 
	INC	C
	INC	C
	LD	B,06H	; 6 
	INC	C
	INC	C
	RLCA
	RLCA
	DEC	C
	LD	C,07H	; 7 
	RLCA
	DEC	C
	LD	C,00H
	NOP
	INC	BC
	INC	BC
	DEFB	0,0
	INC	BC
	INC	BC
	NOP
	LD	BC,I.0403
	NOP
	LD	BC,I.0403
	LD	B,06H	; 6 
	INC	C
	INC	C
	LD	B,06H	; 6 
	INC	C
	INC	C
	RLCA
	RLCA
	DEC	C
	LD	C,07H	; 7 
	RLCA
	DEC	C
	LD	C,01H	; 1 
I6109:	LD	BC,I$0504
J610B	EQU	$-1
	LD	BC,I.0401
	DEC	B
	LD	(BC),A
	LD	(BC),A
	DEC	B
	DEC	B
	LD	(BC),A
	LD	(BC),A
	DEC	B
	DEC	B
	RLCA
	EX	AF,AF'
	DEC	C
	LD	C,07H	; 7 
	EX	AF,AF'
	DEC	C
	LD	C,08H	; 8 
	EX	AF,AF'
	LD	C,0FH	; 15 
	EX	AF,AF'
	EX	AF,AF'
	LD	C,0FH	; 15 
	LD	BC,I.0401
	DEC	B
	LD	BC,I.0401
	DEC	B
	LD	(BC),A
	LD	(BC),A
	DEC	B
	DEC	B
	LD	(BC),A
	LD	(BC),A
	DEC	B
	DEC	B
	RLCA
	EX	AF,AF'
	DEC	C
	LD	C,07H	; 7 
	EX	AF,AF'
	DEC	C
	LD	C,08H	; 8 
	EX	AF,AF'
	LD	C,0FH	; 15 
	EX	AF,AF'
	EX	AF,AF'
	LD	C,0FH	; 15 
	ADD	HL,BC
	ADD	HL,BC
	RRCA
	DJNZ	J6156
	ADD	HL,BC
	RRCA
	DJNZ	J615B
	LD	A,(BC)
	DJNZ	J6165
	LD	A,(BC)
	LD	A,(BC)
J6156:	DJNZ	J6169
	LD	(DE),A
	INC	DE
	DEC	D
J615B:	LD	D,12H	; 18 
	INC	DE
	DEC	D
	LD	D,13H	; 19 
	INC	D
	LD	D,17H
	INC	DE
J6165:	INC	D
	LD	D,17H
	ADD	HL,BC
J6169:	ADD	HL,BC
	RRCA
	DJNZ	J6176
	ADD	HL,BC
	RRCA
	DJNZ	J617B
	LD	A,(BC)
	DJNZ	J6185
	LD	A,(BC)
	LD	A,(BC)
J6176:	DJNZ	J6189
	LD	(DE),A
	INC	DE
	INC	D
J617B:	LD	D,12H	; 18 
	INC	DE
	INC	D
	LD	D,13H	; 19 
	INC	D
	LD	D,17H
	INC	DE
J6185:	INC	D
	LD	D,17H
	LD	A,(BC)
J6189:	DEC	BC
	DJNZ	J619D
	LD	A,(BC)
	DEC	BC
	DJNZ	J61A1
	DEC	BC
	INC	C
	LD	DE,I.0B12
	INC	C
	LD	DE,I.1312
	INC	D
	LD	D,17H
	INC	DE
J619D:	INC	D
	RLA
	RLA
	DEC	D
J61A1:	DEC	D
	RLA
	RLA
	DEC	D
	DEC	D
	JR	J61C0

?61A8:	LD	A,(BC)
	DEC	BC
	DJNZ	J61BD
	LD	A,(BC)
	DEC	BC
	DJNZ	J61C1
	DEC	BC
	INC	C
	LD	DE,I.0B12
	INC	C
	LD	DE,I.1312
	INC	D
	RLA
	RLA
	INC	DE
J61BD:	INC	D
	RLA
	RLA
J61C0:	DEC	D
J61C1:	DEC	D
	JR	J61DC

?61C4:	DEC	D
	DEC	D
	JR	J61E0			; clear keyboard input buffer

J61C8:	LD	IY,0
	LD	IX,M406F+3
	CALL	CALSLT

;	  Subroutine beep
;	     Inputs  ________________________
;	     Outputs ________________________

C61D3:	PUSH	IX
	CALL	BEEP
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C61DB:	XOR	A
	CALL	C$D900			; sort of hook
	RET	NZ
	JP	KILBUF

;	  Subroutine about to start european word processor
;	     Inputs  ________________________
;	     Outputs ________________________

J61E3:	LD	HL,I621F
J61E6:	LD	A,(HL)
	OR	A
	JR	Z,J61F0
	CALL	CHPUT
	INC	HL
	JR	J61E6

J61F0:	CALL	QINLIN
	JR	NC,J61F8		; input not stopped, continue
J61F5:	POP	HL
	XOR	A
	RET

J61F8:	INC	HL
	LD	A,(HL)
	AND	0DFH
	CP	"Y"
	JR	NZ,J61F5		; not 'Y', quit
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,J61F5		; more than just 'Y', quit
	LD	SP,(HIMEM)
	LD	A,0FCH
	OUT	(0A8H),A		; select primairy slot 3 on page 3,2 and 1
	LD	A,(D.7FFF)
	AND	0FCH
	OR	02H			; select segment 2
	LD	(D.7FFF),A
	LD	A,3CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3 and 0 (RAM), secundairy slot 3 on page 2 and 1 (FIRMWARE)
	JP	S28000			; start word processor

I621F:	DEFB	13,10
	DEFB	"Are you sure (Y/N) "
	DEFB	0

;	  Subroutine about to start japanese word processor
;	     Inputs  ________________________
;	     Outputs ________________________

J6235:	LD	HL,I621F
J6238:	LD	A,(HL)
	OR	A
	JR	Z,J6242
	CALL	CHPUT
	INC	HL
	JR	J6238

J6242:	CALL	QINLIN
	JR	NC,J624A
J6247:	POP	HL
	XOR	A
	RET

J624A:	INC	HL
	LD	A,(HL)
	AND	0DFH
	CP	"Y"
	JR	NZ,J6247
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,J6247

J6257:	LD	HL,C.D8FB
	LD	B,5+5
J625C:	LD	(HL),0C9H
	INC	HL
	DJNZ	J625C
	LD	SP,(HIMEM)
	CALL	C61DB			; clear keyboard buffer
	CALL	C7C68
	CALL	C7CBC
	CALL	C7E3C
	CALL	C7E24
J6274:	CALL	C7F14
	CALL	C7F56
	LD	SP,(HIMEM)
	CALL	C61DB			; clear keyboard buffer
	XOR	A
	LD	(D.DAD9),A
	LD	HL,I$1600
	LD	BC,I8897
	CALL	C7C44
	JP	J63B1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6291:	LD	C,0D0H
J6293:	CALL	C634E
	LD	B,10
J6298:	CALL	C633D
	RET	C
	CP	C
J629D:	JR	NZ,J6293
J629F:	DJNZ	J6298
	LD	B,11
	LD	HL,FILNM2
J62A6:	CALL	C633D
	RET	C
	LD	(HL),A
	INC	HL
	DJNZ	J62A6
	CALL	TAPIOF
	LD	A,(D.F86C)
	LD	B,A
	LD	A,(D$F877)
	CP	B
	JR	NZ,J62E4
	LD	B,06H	; 6 
	LD	HL,FILNAM
J62C0:	LD	A,(HL)
	CP	20H	; " "
	JR	NZ,J62CA
	INC	HL
	DJNZ	J62C0
	JR	J62DC

J62CA:	LD	BC,7
	LD	HL,FILNM2
	LD	DE,FILNAM
J62D3:	LD	A,(DE)
	INC	DE
	CPI
	JR	NZ,J62E4
	JP	PE,J62D3
J62DC:	LD	HL,I62EC
	CALL	C62F4
	OR	A
	RET

J62E4:	LD	HL,I62F0
	CALL	C62F4
	JR	C6291

I62EC:	LD	L,C
	INC	C
	CP	(HL)
	RLCA
I62F0:	LD	BC,I$1707
	EX	AF,AF'
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C62F4:	LD	DE,I.D9CC
	LD	BC,4
	LDIR
	EX	DE,HL
	LD	(HL),67H	; "g"
	INC	HL
	LD	(HL),00H
	INC	HL
	LD	B,06H	; 6 
	LD	DE,FILNM2
J6308:	LD	A,(DE)
	PUSH	DE
	CALL	C7C50
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	POP	DE
	INC	DE
	DJNZ	J6308
	LD	(HL),00H
	INC	HL
	LD	(HL),00H
	XOR	A
	LD	(D.DAD9),A
	LD	HL,I.0E0F
	LD	BC,I.D9CC
	CALL	C7C44
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6328:	CALL	C634E
	RET	C
J632C:	CALL	C633D
	RET	C
	LD	(HL),A
	LD	(HL),A
	INC	HL
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J632C
	CALL	TAPIOF
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C633D:	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	TAPIN
	JP	NC,J639B
J6346:	CALL	TAPIOF
	POP	BC
	POP	DE
	POP	HL
	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C634E:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	TAPION
	JP	NC,J639A
	POP	AF
	JR	J6346

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C635B:	LD	A,0D0H
	CALL	C6391
	RET	C
	LD	B,0AH	; 10 
J6363:	CALL	C63A6
	RET	C
	DJNZ	J6363
	LD	B,0BH	; 11 
	LD	HL,FILNAM
J636E:	LD	A,(HL)
	INC	HL
	CALL	C63A6
	RET	C
	DJNZ	J636E
	CALL	TAPOOF
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C637B:	XOR	A
	CALL	C6391
	RET	C
J6380:	LD	A,(HL)
	CALL	C63A6
	RET	C
	LD	A,(HL)
	INC	HL
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J6380
	CALL	TAPOOF
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6391:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	TAPOON
	JR	C,J639F
J639A:	POP	AF
J639B:	POP	BC
	POP	DE
	POP	HL
	RET

J639F:	POP	AF
	CALL	TAPOOF
	SCF
	JR	J639B

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C63A6:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	TAPOUT
	JR	C,J639F
	JR	J639A

J63B1:	CALL	C7BD2
	DEC	A
	JP	Z,J63E4
	DEC	A
	JP	Z,J713E
	DEC	A
	JP	Z,J71C9
	DEC	A
	JP	Z,J7134
	DEC	A
	JR	Z,J63CA
	JP	J726C

J63CA:	CALL	C7EC0
	LD	A,0CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3,2 and 0 (RAM), secunairy slot 3 on page 1 (FIRMWARE)
	JP	J6274

J63D5:	XOR	A
	LD	(D.D91C),A
	CALL	C7F38
	CALL	C7A37
	CALL	C7F32
	JR	J63FE

J63E4:	CALL	C7F56
	LD	HL,I$0013
	LD	DE,I4001
	LD	A,40H	; "@"
	CALL	C7F02
	CALL	C7A37
	CALL	C7A20
	CALL	C7A93
	CALL	C7F1A
J63FE:	LD	SP,(HIMEM)
	XOR	A
	LD	(D.DAD9),A
	CALL	C74D0			; get keyboard input #2
	JR	C,J63FE			; aborted,
	LD	HL,OLDKEY+6
	BIT	1,(HL)			; CTRL pressed ?
	JR	Z,J63FE			; yep,
	LD	HL,J63FE
	PUSH	HL
	CP	7FH			; DELETE ?
	JP	Z,J6641			; yep,
	CP	20H			; normal character ?
	JP	NC,J6580		; yep,
	CP	0DH			; RETURN ?
	JP	Z,J66BF			; yep,
	CP	1BH			; ESCAPE ?
	JP	Z,J64C9			; yep,
	CP	01H			; CTRL-A
	JP	Z,J648B			; yep,
	CP	18H			; SELECT ?
	JP	Z,J6274			; yep,
	PUSH	AF
	LD	A,(OLDKEY+6)
	LD	H,A			; keyboard row 6
	POP	AF
	CP	1CH			; CURSOR RIGHT ?
	JR	NZ,J6449		; nope,
	LD	A,H
	CP	0FEH			; SHIFT pressed ?
	JP	Z,J6664			; yep,
	XOR	A
	CALL	C7690
	RET

J6449:	CP	1DH			; CURSOR LEFT ?
	JR	NZ,J6457		; nope,
	LD	A,H
	CP	0FEH			; SHIFT pressed ?
	JP	Z,J666D			; yep,
	XOR	A
	JP	C7870

J6457:	CP	1EH			; CURSOR UP ?
	JR	NZ,J6465		; nope,
	LD	A,H
	CP	0FEH			; SHIFT pressed ?
	JP	Z,J6672
	XOR	A
	JP	C752F

J6465:	CP	1FH			; CURSOR DOWN ?
	JR	NZ,J6473		; nope,
	LD	A,H
	CP	0FEH			; SHIFT pressed ?
	JP	Z,J6677			; yep,
	XOR	A
	JP	C75E4

J6473:	CP	12H			; INSERT ?
	JP	Z,J667C			; yep,
	CP	08H			; BACKSPACE ?
	JP	Z,J66D5			; yep,
	CP	09H			; TAB ?
	JP	Z,J672B			; yep,

J6482:	CALL	C61DB			; clear keyboard buffer
	CALL	C61D3			; beep
	JP	J63FE

J648B:	CALL	C74D0			; get keyboard input #2
	CP	0F0H
	JR	C,J649B
	JP	Z,J6D2A
	CP	0FAH
	JR	NC,J6482
	JR	J64A0

J649B:	SUB	40H	; "@"
	JP	J6580

J64A0:	LD	HL,I6562
J64A3:	DEC	A
	AND	0FH	; 15 
	CP	03H	; 3 
	JR	C,J64AF
	CP	06H	; 6 
	JP	Z,J6B47
J64AF:	SLA	A
	CALL	C7CEF			; HL = HL + A
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	JP	(HL)

J64B9:	XOR	A
	LD	(D.DA8E),A
	CALL	C7C4A
	JP	C,J63FE
	CALL	C6589
	JP	J63FE

J64C9:	CALL	C74D0			; get keyboard input #2
	CP	1BH			; ESCAPE ?
	JR	Z,J6537			; yep,
	CP	"8"
	JP	Z,J7B7F
	CP	"7"
	JP	Z,J6C90
	CP	"-"
	JR	Z,J64B9
	CP	"9"
	JP	Z,J6DB9
	CP	"0"
	JP	Z,J703D
	CP	09H			; TAB ?
	JP	Z,J6756			; yep,
	CP	1EH			; CURSOR UP ?
	JP	Z,J6769			; yep,
	CP	12H			; INSERT ?
	JP	Z,J676F			; yep,
	CP	7FH			; DELETE ?
	JP	Z,J67B4			; yep,
	CP	"<"
	JR	NZ,J6528
	LD	A,(D.DB02)
	XOR	0FFH
	LD	(D.DB02),A
	OR	A
	LD	HL,X.0000
	JR	Z,J6511
	LD	HL,I$0554
J6511:	PUSH	AF
	LD	C,00H
	CALL	C7F6E
	POP	AF
	LD	HL,I$0555
	JR	Z,J6520
	LD	HL,X.0000
J6520:	LD	C,01H	; 1 
	CALL	C7F6E
	JP	J63FE

J6528:	CP	">"
	JR	NZ,J653D
	LD	A,(D.DA8F)
	XOR	0FFH
	LD	(D.DA8F),A
	JP	J6769

J6537:	CALL	C7C1A
	JP	J63E4

J653D:	CP	"?"
	JR	Z,J6551
	CP	31H	; "1"
	JP	C,J6482
	CP	37H	; "7"
	JP	NC,J6482
	LD	HL,I6574
	JP	J64A3

J6551:	CALL	C7E30
	JP	J6482

?6557:	LD	A,0CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3,2 and 0 (RAM), secunairy slot 3 on page 1 (FIRMWARE)
	CALL	C7F14
	JP	J63E4

I6562:	INC	E
	LD	L,L
	INC	HL
	LD	L,L
	RST	08H
	LD	L,A
	BIT	5,L
	LD	L,B
	LD	(HL),B
	RET	NC
	LD	(HL),B
	LD	B,A
	LD	L,E
	ADC	A,D
	LD	L,E
	RST	08H
	LD	L,(HL)
I6574:	POP	DE
	LD	L,B
	LD	D,L
	LD	L,C
	LD	E,L
	LD	L,C
	OR	B
	LD	L,C
	RET	M
	LD	L,C
	CPL
	LD	L,H
J6580:	CALL	C7C50
	CALL	C6589
	JP	J63FE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6589:	LD	HL,I.006B
	RST	20H
	JR	Z,J65BC
	INC	HL
	RST	20H
	JR	Z,J65A3
J6593:	LD	A,(D.D923)
	OR	A
	JR	Z,C65F8
	CALL	C668E
	JR	NC,C65F8
J659E:	CALL	C61D3			; beep
	SCF
	RET

J65A3:	LD	HL,(D.D909)
	DEC	HL
	DEC	HL
	DEC	HL
	BIT	6,(HL)
	JR	NZ,J6593
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	A,D
	CALL	C7CB6
	JR	NC,J65D5
	LD	DE,I$006C
	JR	J6593

J65BC:	LD	HL,(D.D909)
	DEC	HL
	DEC	HL
	DEC	HL
	BIT	6,(HL)
	JR	NZ,J6593
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	A,D
	CALL	C7CB0
	JR	NC,J65D5
	LD	DE,I.006B
	JR	J6593

J65D5:	LD	(HL),D
	DEC	HL
	LD	(HL),E
	DEC	HL
	LD	B,(HL)
	LD	A,(D.D905)
	OR	A
	RET	Z
	DEC	A
	ADD	A,A
	LD	H,A
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J65EA
	SLA	H
J65EA:	INC	H
	INC	H
	LD	A,(D.D906)
	LD	L,A
	ADD	A,A
	ADD	A,L
	LD	L,A
	LD	A,B
	CALL	C7AE5
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C65F8:	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JR	NC,J659E
	LD	A,(D.D905)
I6601	EQU	$-2
	ADD	A,A
	LD	H,A
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J660D
J660B:	SLA	H
J660D:	INC	H
	INC	H
	LD	A,(D.D906)
	LD	L,A
	ADD	A,A
	ADD	A,L
	LD	L,A
	LD	BC,(D.D909)
	LD	A,(BC)
	PUSH	AF
	LD	A,(D.DA7D)
	OR	A
	JR	NZ,J6626
	POP	AF
	AND	3FH	; "?"
	PUSH	AF
J6626:	XOR	A
	LD	(D.DA7D),A
	POP	AF
	LD	(BC),A
	CALL	C7AE5
	LD	HL,(D.D909)
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	LD	A,(D.DAD8)
	INC	A
	RET	Z
	XOR	A
	CALL	C7690
I663E	EQU	$-1
	OR	A
	RET

J6641:	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JP	NC,J6482
	LD	A,(D.D923)
	OR	A
	JR	Z,J6656
	CALL	C668E
	JP	C,J63FE
J6656:	LD	HL,(D.D909)
	LD	(HL),00H
	LD	DE,I.0125
	CALL	C65F8
	JP	J63FE

J6664:	CALL	C7E66
J6667:	CALL	NC,C7A93
	JP	J63FE

J666D:	CALL	C7E6C
	JR	J6667

J6672:	CALL	C7E72
	JR	J6667

J6677:	CALL	C7E78
	JR	J6667

J667C:	CALL	C6682
	JP	J63FE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6682:	LD	A,(D.D923)
	XOR	0FFH
	LD	(D.D923),A
	CALL	C66BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C668E:	PUSH	DE
	LD	HL,(D.D909)
	CALL	C6FB1
	JR	C,J66BA
	RST	20H
	JR	Z,J66BA
	OR	A
	PUSH	DE
	EX	DE,HL
	SBC	HL,DE
	LD	B,H
	LD	C,L
	POP	DE
	LD	H,D
	LD	L,E
	DEC	HL
	INC	DE
	INC	DE
	PUSH	BC
	LDDR
	INC	HL
	LD	(HL),00H
	INC	HL
	LD	(HL),61H	; "a"
	INC	HL
	LD	(HL),00H
	POP	BC
	INC	BC
	INC	BC
	INC	BC
	CALL	C7A49
J66BA:	POP	DE
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C66BC:	JP	J7E7E

J66BF:	CALL	C66C5
	JP	J63FE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C66C5:	CALL	C7E84
	PUSH	AF
	XOR	A
	CALL	C75E4
	CALL	C7F1A
	POP	AF
	CALL	NZ,C7A93
	RET

J66D5:	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JP	NC,J6482
	INC	HL
	LD	A,(HL)
	CP	25H	; "%"
	JR	NZ,J66EB
	INC	HL
	LD	A,(HL)
	CP	01H	; 1 
	JP	Z,J6482
J66EB:	LD	HL,(D.D909)
	LD	DE,X.8000
	LD	A,H
	CP	D
	JR	NZ,J66FA
	LD	A,L
	CP	E
	JP	Z,J6482
J66FA:	CALL	C6FB1
	OR	A
	EX	DE,HL
	SBC	HL,DE
	LD	B,H
	LD	C,L
	LD	HL,(D.D909)
	LD	D,H
	LD	E,L
	DEC	DE
I6709:	DEC	DE
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C670A:	DEC	DE
	LD	A,(DE)
	CP	0FCH
	JP	NC,J6482
	PUSH	BC
	LDIR
	EX	DE,HL
	LD	(HL),00H
	INC	HL
	LD	(HL),25H	; "%"
	INC	HL
	LD	(HL),01H	; 1 
	POP	BC
	INC	BC
	INC	BC
	INC	BC
	CALL	C7A49
	XOR	A
	CALL	C7870
	JP	J63FE

J672B:	LD	HL,(D.D909)
	LD	DE,I.CF35
	RST	20H
	JP	Z,J6482
	LD	A,(D.D923)
	OR	A
	JR	Z,J673E
	CALL	C668E
J673E:	XOR	A
	CALL	C7690
	LD	HL,I.D924
	LD	A,(D.D90D)
	OR	A
	JP	Z,J63FE
	CALL	C7CEF			; HL = HL + A
	LD	A,(HL)
	OR	A
	JR	Z,J672B
	JP	J63FE

J6756:	LD	HL,I.D924
	LD	A,(D.D90D)
	CALL	C7CEF			; HL = HL + A
	LD	A,(HL)
	XOR	0FFH
	LD	(HL),A
	CALL	C7C2C
	JP	J63FE

J6769:	CALL	C7E8A
	JP	J63E4

J676F:	LD	A,(D.D90D)
	OR	A
	JP	NZ,J6482
	CALL	C7A37
	LD	BC,I86F3
	LD	HL,I.0215
	CALL	C7C3E
J6782:	CALL	C61DB			; clear keyboard buffer
	CALL	C74D0			; get keyboard input #2
	JP	NC,J6791		; not aborted,
J678B:	CALL	C7A37
	JP	J63FE

J6791:	CP	30H	; "0"
	JR	Z,J678B
	JR	C,J679B
	CP	3AH	; ":"
	JR	C,J67A0
J679B:	CALL	C61D3			; beep
	JR	J6782

J67A0:	SUB	30H	; "0"
J67A2:	PUSH	AF
	CALL	C70F3
	JR	NC,J67AB
	CALL	C61D3			; beep
J67AB:	POP	AF
	DEC	A
	JR	NZ,J67A2
	CALL	C7A93
	JR	J678B

J67B4:	LD	HL,(D.D919)
	PUSH	HL
	LD	A,(D.D905)
	PUSH	AF
	LD	A,(D.D906)
	PUSH	AF
	LD	B,08H	; 8 
	LD	HL,I.D9C2
J67C5:	LD	A,(HL)
	PUSH	AF
	INC	HL
	DJNZ	J67C5
	LD	A,(D.D90D)
	PUSH	AF
	OR	A
	JR	Z,J67DC
I67D0	EQU	$-1
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JR	C,J67DC
	JP	J6482

J67DC:	LD	BC,I86B9
	CALL	C6F5E
	LD	HL,(D.D90B)
	LD	A,0CEH
	CP	H
	JR	NZ,J67F0
	LD	A,0BFH
	CP	L
	JP	C,J6EF5
J67F0:	LD	HL,(D.D90B)
	INC	HL
	INC	HL
	INC	HL
	LD	A,(D.D90E)
	CP	27H	; "'"
	JR	Z,J6803
	LD	A,(HL)
	CP	0FCH
	JP	NC,J6EF5
J6803:	PUSH	HL
	LD	A,0CCH
	LD	(D.DAD9),A
	LD	HL,I$2E15
	LD	BC,I86B9
	CALL	C7C3E
	DEC	H
	DEC	H
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J681C
	DEC	H
	DEC	H
J681C:	LD	BC,I8713
	CALL	C7C3E
	POP	HL
	LD	DE,(D.D909)
	XOR	A
	SBC	HL,DE
	EX	DE,HL
J682B:	LD	(HL),00H
	INC	HL
	DEC	DE
	LD	(HL),25H	; "%"
	INC	HL
	DEC	DE
	LD	(HL),01H	; 1 
	INC	HL
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J682B
	PUSH	HL
	LD	B,H
	LD	C,L
	LD	A,(D.D906)
	LD	H,A
	LD	A,(D.D908)
	SUB	H
	LD	H,A
	LD	A,(D.D90D)
	OR	A
	JR	NZ,J6855
	LD	A,(D.D90E)
	CP	27H	; "'"
	JR	NZ,J6855
	INC	H
J6855:	LD	A,H
	OR	A
	JR	Z,J687C
	LD	A,(D.D90D)
	LD	L,A
	LD	A,(D.D90E)
	INC	A
	SUB	L
	JR	NC,J6865
J6864:	DEC	H
J6865:	LD	A,H
	OR	A
	JR	Z,J687A
	LD	A,C
	SUB	78H	; "x"
	LD	C,A
	LD	A,B
	SBC	A,00H
	LD	B,A
	PUSH	BC
	PUSH	HL
	CALL	C70A9
	POP	HL
	POP	BC
	JR	J6864

J687A:	POP	HL
	PUSH	BC
J687C:	POP	HL
	EXX
	POP	AF
	LD	(D.D90E),A
	LD	HL,I$D9C9
	LD	B,08H	; 8 
J6887:	POP	AF
	LD	(HL),A
	DEC	HL
	DJNZ	J6887
	POP	AF
	LD	(D.D908),A
	POP	AF
	LD	(D.D907),A
	POP	HL
	LD	(D.D919),HL
	LD	HL,(D.D909)
	LD	(D.D90B),HL
	PUSH	HL
	EXX
	POP	DE
	RST	20H
	JR	NZ,J68AD
J68A4:	CALL	C7F32
	CALL	C7A20
	JP	J6984

J68AD:	CALL	C6FB1
	RST	20H
	JR	Z,J68A4
	LD	DE,(D.D909)
	XOR	A
	PUSH	HL
	SBC	HL,DE
	LD	B,A
J68BC:	DEC	HL
	DEC	HL
	DEC	HL
	INC	B
	LD	A,L
	OR	H
	JR	NZ,J68BC
	LD	A,B
	PUSH	AF
	CALL	C7F32
	CALL	C7A20
	POP	AF
	POP	DE
	JP	J698D

?68D1:	XOR	A
	LD	(D.DA3D),A
J68D5:	LD	HL,(D.D909)
	LD	A,(D.D90D)
	OR	A
	JR	Z,J68E4
	LD	D,A
	ADD	A,A
	ADD	A,D
	CALL	C7D04			; HL = HL - A
J68E4:	CALL	C6FB1
	JR	NC,J68EF
J68E9:	CALL	C61D3			; beep
	JP	J63FE

J68EF:	RST	20H
	JR	Z,J68E9
	PUSH	HL
	XOR	A
	PUSH	DE
	EX	DE,HL
	SBC	HL,DE
	CP	H
	JR	NZ,J68E9
	LD	A,78H	; "x"
	SUB	L
	JR	C,J68E9
	JP	Z,J68E9
	POP	DE
	LD	H,D
	LD	L,E
	LD	C,A
	LD	B,A
J6908:	LD	A,(DE)
	OR	A
	JR	NZ,J68E9
	INC	DE
	DEC	B
	LD	A,(DE)
	CP	25H	; "%"
	JR	NZ,J68E9
	INC	DE
	DEC	B
	LD	A,(DE)
	CP	01H	; 1 
	JR	NZ,J68E9
	INC	DE
	DJNZ	J6908
	LD	A,(D.DA3D)
	OR	A
	LD	A,C
	JR	NZ,J692B
	BIT	0,A
	JR	Z,J692A
	SUB	03H	; 3 
J692A:	RRCA
J692B:	OR	A
	JR	Z,J68E9
	PUSH	AF
	LD	D,H
	LD	E,L
	CALL	C7CEF			; HL = HL + A
	EX	DE,HL
	POP	AF
	POP	BC
	PUSH	HL
	SBC	HL,BC
	LD	B,H
	LD	C,L
	POP	HL
	DEC	DE
	DEC	HL
	LDDR
	INC	HL
J6942:	LD	(HL),00H
	INC	HL
	LD	(HL),61H	; "a"
	INC	HL
	LD	(HL),00H
	INC	HL
	SUB	03H	; 3 
	JR	NZ,J6942
	CALL	C7A49
	JP	J63FE

?6955:	LD	A,0FFH
	LD	(D.DA3D),A
	JP	J68D5

?695D:	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JP	NC,J6482
	INC	HL
	LD	A,(HL)
	CP	25H	; "%"
	JR	NZ,J6973
	INC	HL
	LD	A,(HL)
	CP	01H	; 1 
	JP	Z,J6482
J6973:	LD	BC,I86EB
	CALL	C6CFC
	CALL	C70F3
	JR	C,J6984
	LD	A,(D.D90D)
	OR	A
	JR	NZ,J698D
J6984:	CALL	C7A93
	CALL	C7A37
	JP	J63FE

J698D:	EX	DE,HL
	PUSH	AF
	CALL	C6FB1
	XOR	A
	EX	DE,HL
	SBC	HL,DE
	LD	B,H
	LD	C,L
	LD	H,D
	LD	L,E
	DEC	DE
	DEC	DE
	DEC	DE
	PUSH	DE
	LDIR
	EX	DE,HL
	LD	(HL),00H
	INC	HL
	LD	(HL),25H	; "%"
	INC	HL
	LD	(HL),01H	; 1 
	POP	DE
	POP	AF
	DEC	A
	JR	NZ,J698D
	JR	J6984

?69B0:	LD	BC,I86DB
	CALL	C6F5E
	LD	HL,(D.D909)
	LD	DE,(D.D90B)
J69BD:	LD	A,(HL)
	CP	0FCH
	JP	NC,J6EF2
	CALL	C69D6
	JR	C,J69CD
	AND	0DFH
	XOR	10H	; 16 
	LD	(HL),A
J69CD:	RST	20H
	JP	Z,J6F59
	INC	HL
	INC	HL
	INC	HL
	JR	J69BD

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C69D6:	PUSH	AF
	PUSH	HL
	INC	HL
	LD	A,(HL)
	CP	25H	; "%"
	JR	Z,J69E6
	CP	52H	; "R"
	JR	Z,J69F0
J69E2:	POP	HL
	POP	AF
	OR	A
	RET

J69E6:	INC	HL
	LD	A,(HL)
	CP	01H	; 1 
	JR	NZ,J69E2
J69EC:	POP	HL
	POP	AF
	SCF
	RET

J69F0:	INC	HL
	LD	A,(HL)
	CP	03H	; 3 
	JR	NZ,J69E2
	JR	J69EC

?69F8:	CALL	C7A37
	LD	HL,I.0215
	LD	BC,I86E3
	CALL	C7C3E
	XOR	A
	LD	(D.DAD9),A
	CALL	C61DB			; clear keyboard buffer
J6A0B:	CALL	C74D0			; get keyboard input #2
	JP	C,J6C08			; aborted,
	LD	HL,(D.D909)
	LD	(D.DAD6),HL
	PUSH	AF
	LD	A,(OLDKEY+6)
	CP	0FBH			; KANA pressed ?
	JP	Z,J6A57			; yep,
	CP	0FEH			; SHIFT pressed ?
I6A21	EQU	$-1
	JP	Z,J6AA0			; yep,
	CP	0FFH
	JR	NZ,J6A52
	POP	AF
	CP	1CH			; CURSOR RIGHT ?
	JR	NZ,J6A34		; nope,
	XOR	A
	CALL	C7690
	JR	J6A0B

J6A34:	CP	1DH			; CURSOR LEFT ?
	JR	NZ,J6A3E		; nope,
	XOR	A
	CALL	C7870
	JR	J6A0B

J6A3E:	CP	1EH			; CURSOR UP ?
	JR	NZ,J6A48		; nope,
	XOR	A
	CALL	C752F
	JR	J6A0B

J6A48:	CP	1FH			; CURSOR DOWN ?
	JR	NZ,J6A52		; nope,
	XOR	A
	CALL	C75E4
	JR	J6A0B

J6A52:	CALL	C61D3			; beep
	JR	J6A0B

J6A57:	POP	AF
	CP	1CH
	JR	NZ,J6A6D
	LD	A,02H	; 2 
	CALL	C6AF5
	XOR	A
	CALL	C7690
	LD	A,08H	; 8 
J6A67:	CALL	C6AEA
	JP	J6A0B

J6A6D:	CP	1DH
	JR	NZ,J6A7E
	LD	A,08H	; 8 
	CALL	C6AF5
	XOR	A
	CALL	C7870
	LD	A,02H	; 2 
	JR	J6A67

J6A7E:	CP	1EH
	JR	NZ,J6A8F
	LD	A,04H	; 4 
	CALL	C6AF5
	XOR	A
	CALL	C752F
	LD	A,01H	; 1 
	JR	J6A67

J6A8F:	CP	1FH
	JR	NZ,J6A52
	LD	A,01H	; 1 
	CALL	C6AF5
	XOR	A
	CALL	C75E4
	LD	A,04H	; 4 
	JR	J6A67

J6AA0:	POP	AF
	CP	1CH
	JR	NZ,J6AB6
	LD	A,0FDH
	CALL	C6B0B
	XOR	A
	CALL	C7690
	LD	A,0F7H
J6AB0:	CALL	C6B00
	JP	J6A0B

J6AB6:	CP	1DH
	JR	NZ,J6AC7
	LD	A,0F7H
	CALL	C6B0B
	XOR	A
	CALL	C7870
	LD	A,0FDH
	JR	J6AB0

J6AC7:	CP	1EH
	JR	NZ,J6AD8
	LD	A,0FBH
	CALL	C6B0B
	XOR	A
	CALL	C752F
	LD	A,0FEH
	JR	J6AB0

J6AD8:	CP	1FH
	JP	NZ,J6A52
	LD	A,0FEH
	CALL	C6B0B
	XOR	A
	CALL	C75E4
	LD	A,0FBH
	JR	J6AB0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6AEA:	LD	B,A
	LD	HL,(D.D909)
	LD	DE,(D.DAD6)
	RST	20H
	RET	Z
	LD	A,B
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6AF5:	LD	B,A
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	RET	NC
	OR	B
	JR	J6B14

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6B00:	LD	B,A
	LD	HL,(D.D909)
	LD	DE,(D.DAD6)
	RST	20H
	RET	Z
	LD	A,B
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6B0B:	LD	B,A
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	RET	NC
	AND	B
J6B14:	LD	(HL),A
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	BIT	2,A
	JR	Z,J6B2E
	LD	HL,I.0061
	RST	20H
	JR	Z,J6B29
	LD	HL,I.0125
	RST	20H
	JR	NZ,J6B37
J6B29:	LD	DE,I.0352
	JR	J6B37

J6B2E:	LD	HL,I.0352
	RST	20H
	JR	NZ,J6B37
	LD	DE,I.0125
J6B37:	LD	A,0FFH
	LD	(D.DA7D),A
	LD	(D.DAD8),A
	CALL	C65F8
	XOR	A
	LD	(D.DAD8),A
	RET

J6B47:	LD	HL,I.0215
	LD	BC,I8B3F
	CALL	C6F61
	LD	HL,(D.D90B)
	LD	DE,(D.D909)
	PUSH	HL
	XOR	A
	SBC	HL,DE
	CP	H
	JR	NZ,J6B6B
	LD	A,L
	CP	2CH	; ","
	JR	NC,J6B6B
	POP	HL
	EX	DE,HL
	INC	DE
J6B66:	LD	A,(HL)
	CP	0FCH
	JR	C,J6B6E
J6B6B:	JP	J6C24

J6B6E:	BIT	6,A
	JR	NZ,J6B6B
	INC	HL
	LD	A,(HL)
	CP	25H	; "%"
	JR	NZ,J6B7F
	INC	HL
	LD	A,(HL)
	CP	01H	; 1 
	JR	Z,J6B6B
	DEC	HL
J6B7F:	INC	HL
	INC	HL
	RST	20H
	JR	C,J6B66
	CALL	C7E90
	JP	J6C08

?6B8A:	CALL	C7A37
	LD	BC,I867D
	LD	HL,I.0215
	CALL	C7C3E
	LD	BC,I8641
	CALL	C7C3E
	LD	BC,I8697
	CALL	C6F61
	LD	HL,(D.D909)
	LD	DE,(D.D90B)
J6BA9:	LD	A,(HL)
	CP	0FCH
	JP	NC,J6B6B
	RST	20H
	JR	Z,J6BB7
	INC	HL
	INC	HL
	INC	HL
	JR	J6BA9

J6BB7:	CALL	C7EAE
	LD	HL,I$D0D0
J6BBD:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,D
	OR	E
	JR	Z,J6BC8
	ADD	HL,DE
	JR	J6BBD

J6BC8:	PUSH	HL
	LD	DE,I$D8C9
	OR	A
	EX	DE,HL
	SBC	HL,DE
	JP	C,J6C0B
	PUSH	HL
	POP	BC
	LD	HL,(D.D90B)
	LD	DE,(D.D909)
	SBC	HL,DE
	PUSH	HL
	PUSH	BC
	POP	DE
	EX	DE,HL
	SBC	HL,DE
	JP	C,J6C0B
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	EX	DE,HL
	POP	HL
	DEC	HL
	DEC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	BC,(D.D909)
J6BF7:	LD	A,(BC)
	LD	(HL),A
	INC	BC
	INC	HL
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J6BF7
	LD	(HL),00H
	INC	HL
	LD	(HL),00H
	CALL	C7EA8
J6C08:	JP	J63D5

J6C0B:	CALL	C7A37
	LD	BC,I8729
	LD	HL,I.0215
J6C14:	XOR	A
	LD	(D.D91C),A
	CALL	C7C3E
	CALL	C61D3			; beep
	CALL	C74D0			; get keyboard input #2
I6C21:	JP	J6C08

J6C24:	CALL	C7A37
	LD	HL,I.0215
	LD	BC,I8733
	JR	J6C14

?6C2F:	LD	BC,I8703
	CALL	C6F5E
	LD	DE,(D.D90B)
	LD	HL,(D.D909)
J6C3C:	LD	A,(HL)
	CP	0FCH
	JR	C,J6C47
	CALL	C7F32
	JP	J6C24

J6C47:	INC	HL
	INC	HL
	INC	HL
	RST	20H
	JR	C,J6C3C
	LD	C,0EH	; 14 
	LD	A,04H	; 4 
	CALL	C7E36
	XOR	A
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	LD	A,40H
	OUT	(99H),A			; set VRAM address latch for writing = 0
	LD	HL,(D.D909)
	LD	DE,(D.D90B)
	INC	DE
	INC	DE
	INC	DE
J6C67:	LD	B,3
J6C69:	LD	A,(HL)
	OUT	(98H),A
	INC	HL
	EX	(SP),HL
	EX	(SP),HL
	DJNZ	J6C69
	RST	20H
	JR	NZ,J6C67
	LD	A,0FFH
	OUT	(98H),A
	LD	(D.DA5E),A
	JP	J6C08

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6C7E:	LD	C,0EH	; 14 
	LD	A,04H	; 4 
	CALL	C7E36
	LD	A,L
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	LD	A,H
	OUT	(99H),A			; set VRAM address latch for reading
	EX	(SP),HL
	EX	(SP),HL
	RET

J6C90:	LD	A,(D.DA5E)
	OR	A
	JP	Z,J6482
	LD	HL,X.0000
	CALL	C6C7E
	IN	A,(98H)
	CP	0FFH
	JP	Z,J6482
	LD	BC,I8703
	CALL	C6CFC
	LD	HL,X.0000
J6CAD:	PUSH	HL
	LD	A,(INTFLG)
	OR	A			; STOP or CTRL-STOP pressed ?
	JP	NZ,J6C08		; yep,
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JR	C,J6CC3
J6CBD:	CALL	C61D3			; beep
	JP	J6C08

J6CC3:	POP	HL
	CALL	C6C7E
	IN	A,(98H)
	CP	0FFH
	JP	Z,J6C08
	LD	A,(D.D923)
	OR	A
	JR	Z,J6CDB
	PUSH	HL
	CALL	C668E
	POP	HL
	JR	C,J6CBD
J6CDB:	PUSH	HL
	CALL	C6C7E
	IN	A,(98H)
	LD	HL,(D.D909)
	LD	(HL),A
	IN	A,(98H)
	LD	E,A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(98H)
	LD	D,A
	LD	A,0FFH
	LD	(D.DA7D),A
	CALL	C65F8
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	JP	J6CAD

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6CFC:	LD	HL,I.0215
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6CFF:	LD	A,0CCH
	LD	(D.DAD9),A
	CALL	C7C3E
	LD	BC,I8671
	CALL	C7C3E
J6D0D:	CALL	C74D0			; get keyboard input #2
	JP	C,J6C08			; aborted,
	CP	0DH			; RETURN ?
	JR	NZ,J6D0D		; nope, again
	XOR	A
	LD	(D.DAD9),A
	RET

?6D1C:	LD	A,0F1H
	LD	BC,I8A73
	JR	J6D2F

?6D23:	LD	A,0F2H
	LD	BC,I8A7B
	JR	J6D2F

J6D2A:	LD	A,0F0H
	LD	BC,I8A6B
J6D2F:	LD	(D.D91C),A
	LD	HL,I6D38
	CALL	C7F7A
I6D38:	JP	C,J63FE
	PUSH	AF
	XOR	A
	LD	(D.DAD9),A
	POP	AF
	OR	A
	JR	NZ,J6D51
	PUSH	HL
	PUSH	BC
	CALL	C6589
	POP	BC
	LD	HL,I6D38
	EX	(SP),HL
	JP	J7F86

J6D51:	CP	0F1H
	JR	NZ,J6D5F
	CALL	C6589
	LD	HL,I6D38
	PUSH	HL
	JP	J7F8C

J6D5F:	CP	0F2H
	JP	NZ,J6D6F
	PUSH	HL
	CALL	C6589
	LD	HL,I6D38
	EX	(SP),HL
	JP	J7EA2

J6D6F:	CP	0F0H
	JR	NZ,J6D7E
	PUSH	HL
	CALL	C6589
	LD	HL,I6D38
	EX	(SP),HL
	JP	J7E2A

J6D7E:	CP	12H	; 18 
	JR	NZ,J6D87
	CALL	C6682
	JR	J6DAD

J6D87:	CP	1CH
	JR	NZ,J6D91
	XOR	A
	CALL	C7690
	JR	J6DAD

J6D91:	CP	1DH
	JR	NZ,J6D9B
	XOR	A
	CALL	C7870
	JR	J6DAD

J6D9B:	CP	1EH
	JR	NZ,J6DA5
	XOR	A
	CALL	C752F
	JR	J6DAD

J6DA5:	CP	1FH
	JR	NZ,J6DAD
	XOR	A
	CALL	C75E4
J6DAD:	LD	A,0CCH
	LD	(D.DAD9),A
	LD	HL,I6D38
	PUSH	HL
	JP	J7F80

J6DB9:	LD	BC,I8B4B
	CALL	C6CFC
	CALL	C7E96
	JP	C,J63D5
	CALL	C7C26
	JP	J63D5

?6DCB:	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JP	NC,J6482
	CALL	C7A37
	LD	HL,I.0215
	LD	BC,I869B
	CALL	C7C3E
	LD	A,15H
	LD	(D.D9B5),A
	CALL	C7A20
J6DE8:	XOR	A
	LD	(D.D90F),A
J6DEC:	CALL	C74D0			; get keyboard input #2
	JR	NC,J6DFE		; not aborted,
	LD	A,(D.D90F)
	OR	A
	JR	Z,J6DFB
	XOR	A
	CALL	C7690
J6DFB:	JP	J6F7A

J6DFE:	CP	1CH			; CURSOR RIGHT ?
	JR	NZ,J6E08		; nope,
J6E02:	XOR	A
	CALL	C7690
	JR	J6DE8

J6E08:	CP	1DH			; CURSOR LEFT ?
	JR	NZ,J6E12		; nope,
	XOR	A
	CALL	C7870
	JR	J6DE8

J6E12:	CP	1EH			; CURSOR UP ?
	JR	NZ,J6E1C		; nope,
	XOR	A
	CALL	C752F
	JR	J6DE8

J6E1C:	CP	1FH			; CURSOR DOWN ?
	JR	NZ,J6E26		; nope,
	XOR	A
	CALL	C75E4
	JR	J6DE8

J6E26:	CP	12H			; INSERT ?
	JR	NZ,J6E35		; nope,
	CALL	C6682
	LD	A,(D.D90F)
	OR	A
	JR	Z,J6DE8
	JR	J6E02

J6E35:	CP	0DH			; RETURN ?
	JR	NZ,J6E3E		; nope,
	CALL	C66C5
	JR	J6DE8

J6E3E:	CP	20H			; control character ?
	JR	NC,J6E4A		; nope,
J6E42:	CALL	C61D3			; beep
	CALL	C61DB			; clear keyboard buffer
	JR	J6DEC

J6E4A:	CP	7FH			; DELETE ?
	JR	Z,J6E42			; yep,
	PUSH	AF
	LD	A,(D.D923)
	OR	A
	JR	Z,J6E63
	LD	A,(D.D90F)
	OR	A
	JR	NZ,J6E63
	CALL	C668E
	JR	NC,J6E63
	POP	AF
	JR	J6E42

J6E63:	POP	AF
	SUB	20H	; " "
	CP	60H	; "`"
	JR	C,J6E7A
	CP	66H	; "f"
	JR	C,J6E42
	CP	80H
	JR	C,J6E7A
	SUB	20H	; " "
	CP	0A0H
	JR	C,J6E7A
	SUB	20H	; " "
J6E7A:	EX	AF,AF'
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JR	NC,J6E42
	LD	A,(D.D90F)
	OR	A
	JR	NZ,J6E96
	LD	A,(HL)
	BIT	6,A
	JR	NZ,J6E95
	SET	6,A
	LD	(HL),A
	INC	HL
	LD	(HL),00H
	DEC	HL
J6E95:	INC	HL
J6E96:	INC	HL
	EX	AF,AF'
	LD	(HL),A
	LD	HL,(D.D909)
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	A,(D.D905)
	ADD	A,A
	LD	H,A
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J6EAF
	LD	A,H
	ADD	A,A
	LD	H,A
J6EAF:	LD	A,02H	; 2 
	ADD	A,H
	LD	H,A
	LD	A,(D.D906)
	LD	L,A
	ADD	A,A
	ADD	A,L
	LD	L,A
	LD	A,B
	CALL	C7AE5
	LD	A,(D.D90F)
	XOR	0FFH
	LD	(D.D90F),A
	JP	NZ,J6DEC
	CALL	C7690
	JP	J6DEC

?6ECF:	LD	HL,D.D9B5
	LD	(HL),13H	; 19 
	CALL	C7A20
	LD	BC,I8717
	CALL	C6F5E
	LD	HL,(D.D909)
	LD	DE,(D.D90B)
	PUSH	DE
	PUSH	HL
	INC	HL
	LD	A,(HL)
	CP	25H	; "%"
	JR	NZ,J6F0C
	INC	HL
	LD	A,(HL)
	CP	01H	; 1 
	JR	NZ,J6F0C
J6EF2:	CALL	C7A93
J6EF5:	LD	A,0CCH
	LD	(D.DAD9),A
	LD	BC,I8737
	LD	HL,I$0E15
	LD	A,(D.DA8F)
	OR	A
	JP	Z,J6C14
	LD	H,08H	; 8 
	JP	J6C14

J6F0C:	INC	DE
	LD	A,(DE)
	CP	25H	; "%"
	JR	NZ,J6F18
	INC	DE
	LD	A,(DE)
	CP	01H	; 1 
	JR	Z,J6EF2
J6F18:	POP	HL
	CALL	C6FB1
	JR	C,J6EF2
	POP	HL
	EX	DE,HL
	OR	A
	SBC	HL,DE
	JR	C,J6EF2
	LD	HL,(D.D909)
	LD	DE,(D.D90B)
J6F2C:	INC	DE
	INC	DE
	INC	DE
	PUSH	DE
	CALL	C6FB1
	JR	C,J6EF2
	OR	A
	PUSH	DE
	EX	DE,HL
	SBC	HL,DE
	LD	C,L
	LD	B,H
	POP	DE
	LD	H,D
	LD	L,E
	DEC	HL
	INC	DE
	INC	DE
	LDDR
	INC	HL
	LD	A,(HL)
	AND	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),0A0H
	INC	HL
	LD	(HL),02H	; 2 
	LD	BC,I.0004
	ADD	HL,BC
	POP	DE
	EX	DE,HL
	RST	20H
	EX	DE,HL
	JR	NC,J6F2C
J6F59:	CALL	C7A93
	JR	J6F7A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6F5E:	LD	HL,I.0215
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6F61:	LD	A,0CCH
	LD	(D.DAD9),A
	CALL	C7C3E
	LD	BC,I86A3
	CALL	C7C3E
	LD	BC,I86A9
	CALL	C7C3E
J6F75:	CALL	C74D0			; get keyboard input #2
	JR	NC,J6F85		; not aborted,
J6F7A:	LD	HL,D.D9B5
	LD	(HL),14H	; 20 
	CALL	C7A20
	JP	J63D5

J6F85:	CP	1CH			; CURSOR RIGHT ?
	JR	NZ,J6F8E		; nope,
	CALL	C7690
	JR	J6F75

J6F8E:	CP	1DH			; CURSOR LEFT ?
	JR	NZ,J6F97		; nope,
	CALL	C7870
	JR	J6F75

J6F97:	CP	1EH			; CURSOR UP ?
	JR	NZ,J6FA0		; nope,
	CALL	C752F
	JR	J6F75

J6FA0:	CP	1FH			; CURSOR DOWN ?
	JR	NZ,J6FA9		; nope,
	CALL	C75E4
	JR	J6F75

J6FA9:	CP	0DH			; RETURN ?
	RET	Z			; yep, quit
	CALL	C61D3			; beep
	JR	J6F75

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C6FB1:	PUSH	HL
J6FB2:	LD	A,(HL)
	CP	0FCH
	JR	C,J6FBB
	SCF
	EX	DE,HL
	POP	HL
	RET

J6FBB:	PUSH	HL
	EX	DE,HL
	POP	HL
	INC	HL
	LD	A,(HL)
	INC	HL
	CP	25H	; "%"
	JR	Z,J6FC8
J6FC5:	INC	HL
	JR	J6FB2

J6FC8:	LD	A,(HL)
	CP	01H	; 1 
	JR	NZ,J6FC5
	POP	HL
	RET

?6FCF:	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FCH
	JR	NC,J7010
	CALL	C7A37
	LD	BC,I867D
	LD	HL,I.0215
	CALL	C7C3E
	LD	BC,I863B
	CALL	C7C3E
	LD	BC,I8697
	CALL	C7033
	XOR	A
	LD	(D.DAD9),A
J6FF3:	LD	A,(INTFLG)
	OR	A			; STOP or CTRL-STOP pressed ?
	JP	NZ,J6C08		; yep,
	LD	A,(D.D923)
	OR	A
	JR	Z,J7007
	PUSH	HL
	CALL	C668E
	POP	HL
	JR	C,J7010
J7007:	LD	BC,(D.D909)
	LD	A,(BC)
	CP	0FCH
	JR	C,J7016
J7010:	CALL	C61D3			; beep
	JP	J6C08

J7016:	LD	A,(HL)
	LD	(BC),A
	INC	HL
	PUSH	DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	HL
	LD	A,0FFH
	LD	(D.DA7D),A
	CALL	C65F8
	POP	HL
	POP	DE
	DEC	DE
	DEC	DE
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J6FF3
	JP	J6C08

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7033:	CALL	C6CFF
	CALL	C7EB4
	JP	C,J6C08
	RET

J703D:	CALL	C7A37
	LD	BC,I867D
	LD	HL,I.0215
	CALL	C7C3E
	LD	BC,I86B9
	CALL	C7033
	PUSH	HL
	ADD	HL,DE
	PUSH	HL
	PUSH	HL
	LD	HL,I$D8D0
	POP	BC
	XOR	A
	SBC	HL,BC
	PUSH	HL
	POP	BC
	POP	HL
	POP	DE
	DEC	DE
	DEC	DE
	LDIR
	CALL	C7EA8
	JP	J6C08

?7068:	LD	A,(D.D90D)
	OR	A
	JP	NZ,J6482
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FDH
	JR	Z,J70A0
	CALL	C70F3
	JP	C,J6482
	LD	(HL),0FDH
	INC	HL
	LD	(HL),7FH
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	PUSH	HL
	LD	(HL),0FDH
J7089:	INC	HL
	LD	(HL),0DFH
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	POP	DE
	EX	DE,HL
	LD	BC,I$0072
	LDIR
	CALL	C66C5
J709A:	CALL	C7A93
	JP	J63FE

J70A0:	LD	BC,(D.D909)
	CALL	C70A9
	JR	J709A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C70A9:	PUSH	BC
	PUSH	BC
	LD	HL,I.CEC0
	OR	A
	SBC	HL,BC
	JR	Z,J70CC
	LD	B,H
	LD	C,L
	LD	DE,I.0078
	POP	HL
	ADD	HL,DE
	POP	DE
	LDIR
J70BD:	LD	B,28H	; "("
	EX	DE,HL
J70C0:	LD	(HL),00H
	INC	HL
	LD	(HL),25H	; "%"
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	DJNZ	J70C0
	RET

J70CC:	POP	HL
	POP	DE
	JR	J70BD

?70D0:	LD	A,(D.D90D)
	OR	A
	JP	NZ,J6482
	LD	HL,(D.D909)
	LD	A,(HL)
	CP	0FEH
	JR	Z,J70A0
	CALL	C70F3
	JP	C,J6482
	LD	(HL),0FEH
	INC	HL
	LD	(HL),0E0H
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	PUSH	HL
	LD	(HL),0FEH
	JR	J7089

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C70F3:	LD	HL,(D.D909)
	LD	DE,I.CF37
	LD	B,H
	LD	C,L
	LD	HL,I$CEBF
	PUSH	HL
	OR	A
	SBC	HL,BC
	JR	Z,J7131
	JR	C,J7131
	LD	B,H
	LD	C,L
	INC	BC
	POP	HL
	LDDR
	INC	HL
	PUSH	HL
J710E:	PUSH	HL
	LD	(HL),00H
	INC	HL
	LD	(HL),25H	; "%"
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	POP	DE
	EX	DE,HL
	LD	BC,I$0075
	LDIR
	LD	HL,I.CEC0
I7121	EQU	$-1
	LD	A,(HL)
	CP	0FCH
	JR	NC,J710E
	POP	HL
	PUSH	HL
	LD	DE,I.0078
	ADD	HL,DE
	PUSH	HL
	POP	DE
	POP	HL
	RET

J7131:	POP	HL
	SCF
	RET

J7134:	LD	SP,(HIMEM)
	CALL	C7C32
	JP	J6274

J713E:	LD	SP,(HIMEM)
	CALL	C7BD8
	JP	C,J6274
	DEC	A
	JR	Z,J7155
	DEC	A
	JR	Z,J7185
	LD	HL,J713E
	PUSH	HL
	JP	J71DD

J7155:	CALL	C7C14
	JR	C,J713E
	LD	BC,I8B6F
	CALL	C71AB
	XOR	A
	LD	(D.F86C),A
	CALL	C6291
	JR	C,J713E
	CALL	C7CBC
	LD	HL,I.CF38
	LD	DE,X.8000
	PUSH	DE
	OR	A
	SBC	HL,DE
J7176:	LD	DE,(D.F878)
	RST	20H
	JR	NC,J717E
	EX	DE,HL
J717E:	POP	HL
	OR	A
	CALL	C6328
	JR	J713E

J7185:	CALL	C7E60
	JR	C,J713E
	CALL	C7C14
	JR	C,J713E
	LD	BC,I870D
	CALL	C71AB
	XOR	A
	LD	(D.F86C),A
	CALL	C6291
	JR	C,J713E
	CALL	C7E60
	PUSH	HL
	LD	DE,I.CF38
	EX	DE,HL
	OR	A
	SBC	HL,DE
	JR	J7176

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C71AB:	PUSH	BC
	LD	HL,I$2D00
	LD	DE,I$1002
	LD	A,40H	; "@"
	CALL	C7F50
	POP	BC
	LD	HL,I$2F00
	CALL	C7C44
	LD	BC,I8713
	CALL	C7C3E
	XOR	A
	LD	(D.DAD9),A
	RET

J71C9:	LD	SP,(HIMEM)
	CALL	C7BDE
	JP	C,J6274
	DEC	A
	JR	Z,J71EB
	DEC	A
	JR	Z,J720F
	LD	HL,J71C9
	PUSH	HL
J71DD:	LD	A,(D.D9CB)
	CPL
	LD	(D.D9CB),A
	CALL	STMOTR
	CALL	C61D3			; beep
	RET

J71EB:	LD	A,(X.8000)
	CP	0FEH
	JR	Z,J71C9
	CALL	C7C14
	JR	C,J71C9
	LD	BC,I8B75
	CALL	C71AB
	CALL	C7E5A
	PUSH	DE
	PUSH	HL
	OR	A
	CALL	C635B
	JR	C,J71C9
	POP	DE
	POP	HL
	CALL	C637B
	JR	J71C9

J720F:	LD	A,(X.8000)
	CP	0FEH
	JP	Z,J71C9
	CALL	C7C14
	JR	C,J71C9
	LD	BC,I865B
	CALL	C71AB
	XOR	A
	LD	(D.F86C),A
	CALL	C6291
	JR	C,J71C9
	LD	HL,X.8000
	LD	DE,(D.F878)
	LD	BC,J71C9
	PUSH	BC
	CALL	C634E
	RET	C
J723A:	CALL	C633D
	RET	C
	CP	(HL)
	INC	HL
	JR	NZ,J724B
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J723A
	CALL	TAPIOF
	RET

J724B:	CALL	TAPIOF
	CALL	C61D3			; beep
	LD	HL,I.0E0F
	LD	BC,I8659
	CALL	C7C44
	LD	BC,I8737
	CALL	C7C3E
	CALL	C61DB			; clear keyboard buffer
	CALL	C61D3			; beep
	CALL	C74AE			; get keyboard input
	JP	J71C9

J726C:	CALL	C7BE4
	JP	C,J6274
	DEC	A
	JP	Z,J7480
	DEC	A
	JR	Z,J727C
	JP	J7281

J727C:	CALL	C7EBA
	JR	J726C

J7281:	LD	SP,(HIMEM)
	CALL	C7BF0
	JP	C,J726C
	DEC	A
	JR	Z,J72A6
	DEC	A
	JP	Z,J7401
	CALL	C7BF6
	JR	J7281

;	  Subroutine RS232 open
;	     Inputs  ________________________
;	     Outputs ________________________

C7297:	LD	A,LOW (I4010+6)
I7299:	LD	(C.F882+2),A		; RS232.OPEN
	LD	HL,I$F420
	LD	C,254
	CALL	C.F882			; RS232 bios call
	EI
	RET

J72A6:	LD	SP,(HIMEM)
	CALL	C7BFC
	JP	C,J7281
	DEC	A
	JR	Z,J72B5
	JR	J72D4

J72B5:	LD	HL,X.8000
	LD	A,0FEH
J72BA:	CP	(HL)
	JR	Z,J72C2
	INC	HL
	INC	HL
	INC	HL
	JR	J72BA

J72C2:	LD	DE,I.CF37
	RST	20H
	JR	C,J72CD
	CALL	C61D3			; beep
	JR	J72A6

J72CD:	LD	DE,I.0078
	ADD	HL,DE
	EX	DE,HL
	JR	J72DA

J72D4:	CALL	C7CBC
	LD	DE,X.8000
J72DA:	PUSH	DE
	LD	BC,I89DD
	CALL	C71AB
	POP	DE
	PUSH	DE
	LD	E,1			; mode = input
	CALL	C7297			; RS232 open
	POP	DE
J72E9:	LD	HL,I.CF38
	RST	20H
	JR	NZ,J72FE
	LD	BC,I89D1
J72F2:	LD	HL,I.140E
	CALL	C7C44
J72F8:	CALL	C73DF			; RS232 close
	JP	J72A6

J72FE:	CALL	C73D5			; RS232 get character
	JR	C,J72F8
	JP	M,J736F
	CALL	C7375
	JR	C,J736C
	CALL	C73D5			; RS232 get character
	JR	C,J736C
	JP	M,J736C
	CALL	C7389
	JR	C,J736C
	CALL	C73D5			; RS232 get character
	JR	C,J736B
	JP	M,J736B
	CALL	C7375
	JR	C,J736B
	CALL	C73D5			; RS232 get character
	JR	C,J736B
	JP	M,J736B
	CALL	C7389
	JR	C,J736B
	CALL	C73D5			; RS232 get character
I7335:	JR	C,J736A
I7336	EQU	$-1
	JP	M,J736A
	CALL	C7375
	JR	C,J736A
	CALL	C73D5			; RS232 get character
	JR	C,J736A
	JP	M,J736A
	CALL	C7389
	JR	C,J736A
	LD	A,(D.DB10)
	OR	A
	JP	NZ,J72E9
	PUSH	DE
	LD	DE,0*256+2
	CALL	EXTBIO
	POP	DE			; DISINT
	CALL	C73A8
	PUSH	DE
	LD	DE,0*256+3
	CALL	EXTBIO
	POP	DE			; ENAINT
	EI
	JP	J72E9

J736A:	DEC	DE
J736B:	DEC	DE
J736C:	CALL	C739D
J736F:	LD	BC,I89C3
	JP	J72F2

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7375:	SUB	30H	; "0"
	RET	C
	CP	10H	; 16 
	JR	C,J737E
	SUB	07H	; 7 
J737E:	AND	0FH	; 15 
	RLCA
	RLCA
	RLCA
	RLCA
	LD	(D.DB0F),A
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7389:	SUB	30H	; "0"
	RET	C
	CP	10H	; 16 
	JR	C,J7392
	SUB	07H	; 7 
J7392:	AND	0FH	; 15 
	LD	H,A
	LD	A,(D.DB0F)
	OR	H
	LD	(DE),A
	INC	DE
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C739D:	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,25H	; "%"
	LD	(DE),A
	INC	DE
	LD	A,01H	; 1 
	LD	(DE),A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C73A8:	PUSH	DE
	PUSH	DE
	LD	HL,I$0612
	LD	DE,I$3803
	LD	BC,I.3A12
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J73BF
	LD	H,04H	; 4 
	LD	D,3AH	; ":"
	LD	B,3CH	; "<"
J73BF:	PUSH	BC
	LD	BC,I.0212
	CALL	C7ED8
	POP	BC
	POP	HL
	DEC	HL
	LD	D,(HL)
	DEC	HL
	LD	E,(HL)
	DEC	HL
	LD	A,(HL)
	LD	H,B
	LD	L,C
	CALL	C7AE5
	POP	DE
	RET

;	  Subroutine RS232 get character
;	     Inputs  ________________________
;	     Outputs ________________________

C73D5:	LD	A,LOW (I4010+12)
	LD	(C.F882+2),A		; RS232.GETCHR
	CALL	C.F882			; RS232 bios call
	EI
	RET

;	  Subroutine RS232 close
;	     Inputs  ________________________
;	     Outputs ________________________

C73DF:	DI
	CALL	BREAKX
	JR	C,C73DF
	EI
	CALL	C61D3			; beep
	LD	A,LOW (I4010+18)
	LD	(C.F882+2),A		; RS232.CLOSE
	CALL	C.F882			; RS232 bios call
	LD	HL,0
J73F4:	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,J73F4
	CALL	C61DB			; clear keyboard buffer
	XOR	A
	LD	(INTFLG),A		; reset STOP or CTRL-STOP flag
	RET

J7401:	LD	SP,(HIMEM)
	CALL	C7C02
	JP	C,J7281
	CP	0DH	; 13 
	JR	NZ,J7401
	LD	E,2			; mode = output
	CALL	C7297			; RS232 open
	LD	DE,X.8000
	PUSH	DE
	LD	BC,I8A1B
	CALL	C71AB
	POP	DE
J741F:	LD	A,(DE)
	CP	0FEH
	JR	NZ,J742A
J7424:	CALL	C73DF			; RS232 close
	JP	J7401

J742A:	LD	B,3
J742C:	PUSH	BC
	CALL	C7447			; high nibble to hex
	CALL	C745A			; RS232 send character
	CALL	C7456			; low nibble to hex, next
	CALL	C745A			; RS232 send character
	POP	BC
	DJNZ	J742C
	LD	A,(D.DB10)
	OR	A
	JR	NZ,J741F
	CALL	C73A8
	JR	J741F

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7447:	LD	A,(DE)
	RLCA
	RLCA
	RLCA
	RLCA
J744C:	AND	0FH
	ADD	A,"0"
	CP	"9"+1
	RET	C
	ADD	A,07H
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7456:	LD	A,(DE)
	INC	DE
	JR	J744C

;	  Subroutine RS232 send character
;	     Inputs  ________________________
;	     Outputs ________________________

C745A:	PUSH	AF
	LD	A,LOW (I4010+15)
	LD	(C.F882+2),A		; RS232.SNDCHR
	POP	AF
	PUSH	DE
	CALL	C.F882			; RS232 bios call
	EI
	POP	DE
	JR	Z,J7475			; timeout,
	RET	NC			; no error, quit
	LD	BC,I8A0F
J746D:	LD	HL,I.140E
	CALL	C7C44
	JR	J7424

J7475:	LD	BC,I8A01
	JR	J746D

J747A:	CALL	BREAKX
	JR	C,J747A
	RET

J7480:	LD	SP,(HIMEM)
	CALL	C7C08
	JP	C,J726C
	DEC	A
	JR	Z,J74A4
	DEC	A
	JR	Z,J74A9
	DEC	A
	DEC	A
	JR	Z,J7499
	CALL	C7BC0
	JR	J7480

J7499:	LD	BC,I8647
	CALL	C71AB
	CALL	C7C6E
	JR	J7480

J74A4:	CALL	C7EC6
	JR	J7480

J74A9:	CALL	C7ECC
	JR	J7480

;	  Subroutine get keyboard input
;	     Inputs  ________________________
;	     Outputs ________________________

C74AE:	EI
	XOR	A
	CALL	C.D8FB			; sort of hook
	RET	NZ
	LD	A,(INTFLG)
	OR	A			; STOP or CTRL-STOP pressed ?
	JR	NZ,J74C8		; yep,
	CALL	CHSNS			; keyboard input available ?
	JR	Z,C74AE			; nope, try again
	CALL	CHGET			; get keyboard input
	CP	3
	JR	Z,J74C8
	OR	A
	RET

J74C8:	XOR	A
	LD	(INTFLG),A		; reset STOP or CTRL-STOP flag
	LD	A,3
	SCF
	RET

;	  Subroutine get keyboard input #2
;	     Inputs  ________________________
;	     Outputs ________________________

C74D0:	EI
	XOR	A
	CALL	C.D8FB			; sort of hook
	RET	NZ
	LD	A,(INTFLG)
	OR	A			; STOP or CTRL-STOP pressed ?
	JR	NZ,J74C8		; yep, quit
	PUSH	HL
	LD	HL,D.D91B
	LD	A,(MODE)
	AND	01H
	CP	(HL)
	JR	Z,J74F2
	LD	(D.D91B),A
	XOR	A
	LD	(CHRCNT),A
	CALL	C7CAA
J74F2:	LD	A,(MODE)
	AND	01H
	JR	Z,J7520
	PUSH	DE
	LD	HL,I$D9BB
	LD	(HL),20H
	DEC	HL
	LD	(HL),20H
	LD	DE,ROMA
	LD	A,(CHRCNT)
	SUB	1
	JR	C,J7514
	JR	Z,J7512
	LD	A,(DE)
	LD	(HL),A
	INC	HL
	INC	DE
J7512:	LD	A,(DE)
	LD	(HL),A
J7514:	LD	A,02H	; 2 
	LD	HL,I$D9BA
	LD	DE,I$1C13
	CALL	C7F74
	POP	DE
J7520:	POP	HL
	CALL	CHSNS
	JR	Z,C74D0
	CALL	CHGET
	CP	3
	JR	Z,J74C8
	OR	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C752F:	PUSH	HL
	PUSH	DE
	PUSH	BC
	OR	A
	JR	NZ,J757C
	LD	A,(D.D906)
	OR	A
	JR	NZ,J754C
	LD	HL,(D.D909)
	LD	DE,I8078
	RST	20H
	JR	NC,J756C
J7544:	CALL	C61D3			; beep
	POP	BC
	POP	DE
	POP	HL
	SCF
	RET

J754C:	DEC	A
	LD	(D.D906),A
	LD	(D.D908),A
J7553:	CALL	C75BB
	LD	HL,(D.D909)
	LD	A,120
	CALL	C7D04			; HL = HL - A
	LD	(D.D909),HL
	LD	(D.D90B),HL
J7564:	CALL	C7F1A
	POP	BC
	POP	DE
	POP	HL
	OR	A
	RET

J756C:	LD	HL,(D.D919)
	LD	A,78H
	CALL	C7D04			; HL = HL - A
	LD	(D.D919),HL
	CALL	C7D24
	JR	J7553

J757C:	LD	HL,(D.D90B)
	LD	DE,(D.D909)
	LD	A,120
	CALL	C7D04			; HL = HL - A
	RST	20H
	JR	C,J7544
	LD	A,(D.D908)
	OR	A
	JR	Z,J75A0
	DEC	A
	LD	(D.D908),A
J7595:	LD	(D.D90B),HL
	CALL	C75BB
J759B:	CALL	C7F20
	JR	J7564

J75A0:	LD	A,(D.D906)
	INC	A
	LD	(D.D906),A
	LD	DE,(D.D919)
	LD	A,78H
	CALL	C7D0D			; DE = DE - A
	LD	(D.D919),DE
	PUSH	HL
	CALL	C7D24
	POP	HL
	JR	J7595

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C75BB:	LD	HL,I.D9C4
	DEC	(HL)
	LD	A,(HL)
	CP	0FFH
	JR	NZ,J75D8
	LD	(HL),09H	; 9 
	DEC	HL
	DEC	(HL)
	LD	A,(HL)
	CP	0FFH
	JR	NZ,J75D8
	LD	(HL),09H	; 9 
	DEC	HL
	DEC	(HL)
	LD	A,(HL)
	CP	00H
	JR	NZ,J75D8
	LD	(HL),1AH
J75D8:	LD	HL,I.D9C2
	LD	DE,I.2C13
	LD	A,03H	; 3 
	CALL	C7F74
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C75E4:	PUSH	HL
	PUSH	DE
	PUSH	BC
	OR	A
	JR	NZ,J7626
	LD	A,(D.D906)
	CP	05H	; 5 
	JR	NZ,J760B
	LD	HL,(D.D909)
	LD	DE,I.CEC0
	RST	20H
	JP	NC,J7544
	LD	HL,(D.D919)
	LD	A,78H
	CALL	C7CEF			; HL = HL + A
	LD	(D.D919),HL
	CALL	C7D59
	JR	J7612

J760B:	INC	A
	LD	(D.D906),A
	LD	(D.D908),A
J7612:	CALL	C7663
	LD	HL,(D.D909)
	LD	A,78H
	CALL	C7CEF			; HL = HL + A
	LD	(D.D909),HL
	LD	(D.D90B),HL
	JP	J7564

J7626:	LD	A,(D.D908)
	CP	05H	; 5 
	JR	NZ,J764E
	LD	HL,(D.D90B)
	LD	DE,I.CEC0
	RST	20H
	JP	NC,J7544
	LD	HL,(D.D919)
	LD	A,78H
	CALL	C7CEF			; HL = HL + A
	LD	(D.D919),HL
	CALL	C7D59
	LD	A,(D.D906)
	DEC	A
	LD	(D.D906),A
	JR	J7652

J764E:	INC	A
	LD	(D.D908),A
J7652:	CALL	C7663
	LD	HL,(D.D90B)
	LD	A,78H
	CALL	C7CEF			; HL = HL + A
	LD	(D.D90B),HL
	JP	J759B

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7663:	LD	HL,I.D9C4
	LD	A,(HL)
	INC	A
	LD	(HL),A
	CP	0AH	; 10 
	JR	NZ,J7684
	LD	(HL),00H
	DEC	HL
	LD	A,(HL)
	INC	A
	LD	(HL),A
	CP	0AH	; 10 
	JR	NZ,J7684
	LD	(HL),00H
	DEC	HL
	LD	A,(HL)
	CP	1AH
	JR	NZ,J7683
	LD	(HL),01H	; 1 
	JR	J7684

J7683:	INC	(HL)
J7684:	LD	HL,I.D9C2
	LD	DE,I.2C13
	LD	A,03H	; 3 
	CALL	C7F74
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7690:	PUSH	HL
	PUSH	DE
	PUSH	BC
	OR	A
	JP	NZ,J7773
	LD	HL,(D.D909)
	LD	DE,I.CF35
	RST	20H
	JP	Z,J7544
	LD	HL,D.D905
	LD	D,0EH	; 14 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J76AE
	LD	D,1DH
J76AE:	LD	A,D
	CP	(HL)
	JP	NZ,J774B
	LD	A,(D.D90D)
	CP	27H	; "'"
	JR	NZ,J7727
	XOR	A
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	(D.D905),A
	LD	(D.D907),A
	LD	HL,(D.D909)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	A,(D.D906)
	CP	05H	; 5 
	JR	Z,J76F5
	INC	A
	LD	(D.D906),A
	LD	(D.D908),A
	LD	HL,(D.D919)
	LD	BC,I.004B
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J76F0
	LD	BC,I.001E
J76F0:	OR	A
	SBC	HL,BC
	JR	J7705

J76F5:	LD	HL,(D.D919)
	LD	BC,I.002D
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J7704
	LD	BC,I.005A
J7704:	ADD	HL,BC
J7705:	LD	(D.D919),HL
	LD	HL,I.D9C7
	LD	(HL),1AH
	INC	HL
	LD	(HL),01H	; 1 
	DEC	HL
	LD	DE,I.3613
	LD	A,02H	; 2 
	CALL	C7F74
	CALL	C7663
J771C:	CALL	C7F1A
	CALL	C7A93
J7722:	POP	BC
	POP	DE
	POP	HL
	OR	A
	RET

J7727:	INC	A
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	HL,(D.D909)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	HL,(D.D919)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D919),HL
J7743:	CALL	C784F
	CALL	C7D83
	JR	J7722

J774B:	LD	A,(D.D905)
	INC	A
	LD	(D.D905),A
	LD	(D.D907),A
	LD	A,(D.D90D)
	INC	A
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	HL,(D.D909)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D909),HL
	LD	(D.D90B),HL
	CALL	C784F
	CALL	C7F1A
	JR	J7722

J7773:	LD	HL,(D.D90B)
	LD	DE,I.CF35
	RST	20H
	JP	Z,J7544
	LD	HL,D.D907
	LD	D,0EH	; 14 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J778A
	LD	D,1DH
J778A:	LD	A,D
	CP	(HL)
	LD	A,(HL)
	JP	NZ,J7832
	LD	A,(D.D90E)
	CP	27H	; "'"
	JR	NZ,J780F
	XOR	A
	LD	(D.D90E),A
	LD	(D.D907),A
	LD	A,(D.D905)
	LD	H,A
	LD	A,(D.DA8F)
	OR	A
	LD	A,19H
	JR	Z,J77AC
	LD	A,0AH	; 10 
J77AC:	ADD	A,H
	LD	(D.D905),A
	LD	HL,(D.D90B)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D90B),HL
	LD	A,(D.D908)
	CP	05H	; 5 
	JR	Z,J77DB
	INC	A
	LD	(D.D908),A
	LD	HL,(D.D919)
	LD	BC,I.004B
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J77D3
	LD	BC,I.001E
J77D3:	OR	A
	SBC	HL,BC
	LD	(D.D919),HL
	JR	J77F5

J77DB:	LD	HL,(D.D919)
	LD	BC,I.002D
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J77EA
	LD	BC,I.005A
J77EA:	ADD	HL,BC
	LD	(D.D919),HL
	LD	A,(D.D906)
	DEC	A
	LD	(D.D906),A
J77F5:	LD	HL,I.D9C7
	LD	(HL),1AH
	INC	HL
	LD	(HL),01H	; 1 
	DEC	HL
	LD	DE,I.3613
I77FF	EQU	$-2
I7800	EQU	$-1
	LD	A,02H	; 2 
	CALL	C7F74
	CALL	C7663
J7809:	CALL	C7F20
	JP	J771C

J780F:	INC	A
	LD	(D.D90E),A
	LD	A,(D.D905)
	DEC	A
	LD	(D.D905),A
	LD	HL,(D.D90B)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D90B),HL
	LD	HL,(D.D919)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D919),HL
	CALL	C7F20
	JP	J7743

J7832:	INC	A
	LD	(D.D907),A
	LD	A,(D.D90E)
	INC	A
	LD	(D.D90E),A
	LD	HL,(D.D90B)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D90B),HL
	CALL	C784F
	CALL	C7F20
	JP	J7722

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C784F:	LD	HL,I.D9C8
	LD	A,(HL)
	INC	A
	LD	(HL),A
	CP	0AH	; 10 
	JR	NZ,J7864
	LD	(HL),00H
	DEC	HL
	LD	A,(HL)
	CP	1AH
	JR	NZ,J7863
	LD	(HL),00H
J7863:	INC	(HL)
J7864:	LD	HL,I.D9C7
	LD	DE,I.3613
	LD	A,02H	; 2 
	CALL	C7F74
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7870:	PUSH	HL
	PUSH	DE
	PUSH	BC
	OR	A
	JP	NZ,J7949
	LD	HL,(D.D909)
	LD	DE,X.8000
	RST	20H
	JP	Z,J7544
	LD	A,(D.D905)
	OR	A
	JP	NZ,J7923
	LD	A,(D.D90D)
	OR	A
	JR	NZ,J78FE
	LD	A,27H	; "'"
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	H,0EH	; 14 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J78A0
	LD	H,1DH
J78A0:	LD	A,H
	LD	(D.D905),A
	LD	(D.D907),A
	LD	HL,(D.D909)
	DEC	HL
	DEC	HL
	DEC	HL
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	A,(D.D906)
	OR	A
	JR	Z,J78D2
	DEC	A
	LD	(D.D906),A
	LD	(D.D908),A
	LD	HL,(D.D919)
	LD	BC,I.004B
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J78CF
	LD	BC,I.001E
J78CF:	ADD	HL,BC
	JR	J78E4

J78D2:	LD	HL,(D.D919)
	LD	BC,I.002D
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J78E1
	LD	BC,I.005A
J78E1:	OR	A
	SBC	HL,BC
J78E4:	LD	(D.D919),HL
	LD	HL,I.D9C7
	LD	(HL),04H	; 4 
	INC	HL
	LD	(HL),00H
	DEC	HL
	LD	DE,I.3613
	LD	A,02H	; 2 
	CALL	C7F74
	CALL	C75BB
	JP	J771C

J78FE:	DEC	A
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	HL,(D.D909)
	DEC	HL
	DEC	HL
	DEC	HL
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	HL,(D.D919)
	DEC	HL
	DEC	HL
	DEC	HL
	LD	(D.D919),HL
	CALL	C7A03
J791D:	CALL	C7DD9
	JP	J7722

J7923:	DEC	A
	LD	(D.D905),A
	LD	(D.D907),A
	LD	A,(D.D90D)
	DEC	A
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	HL,(D.D909)
	DEC	HL
	DEC	HL
	DEC	HL
	LD	(D.D909),HL
	LD	(D.D90B),HL
	CALL	C7A03
	CALL	C7F1A
	JP	J7722

J7949:	LD	HL,(D.D90B)
	LD	DE,(D.D909)
	DEC	HL
	DEC	HL
	DEC	HL
	RST	20H
	JP	C,J7544
	LD	(D.D90B),HL
	LD	A,(D.D907)
	OR	A
	JP	NZ,J79EF
	LD	A,(D.D90E)
	OR	A
	JR	NZ,J79D2
	LD	A,27H	; "'"
	LD	(D.D90E),A
	LD	HL,I$190E
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J7978
	LD	HL,I$0A1D
J7978:	LD	A,(D.D905)
	SUB	H
	LD	(D.D905),A
	LD	A,L
	LD	(D.D907),A
	LD	A,(D.D908)
	OR	A
	JR	NZ,J79A4
	LD	A,(D.D906)
	INC	A
	LD	(D.D906),A
	LD	HL,(D.D919)
	LD	BC,I.002D
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J799F
	LD	BC,I.005A
J799F:	OR	A
	SBC	HL,BC
	JR	J79B8

J79A4:	DEC	A
	LD	(D.D908),A
	LD	HL,(D.D919)
	LD	BC,I.004B
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J79B7
	LD	BC,I.001E
J79B7:	ADD	HL,BC
J79B8:	LD	(D.D919),HL
	LD	HL,I.D9C7
	LD	(HL),04H	; 4 
	INC	HL
	LD	(HL),00H
	DEC	HL
	LD	DE,I.3613
	LD	A,02H	; 2 
	CALL	C7F74
	CALL	C75BB
	JP	J7809

J79D2:	DEC	A
	LD	(D.D90E),A
	LD	A,(D.D905)
	INC	A
	LD	(D.D905),A
	LD	HL,(D.D919)
	DEC	HL
	DEC	HL
	DEC	HL
	LD	(D.D919),HL
	CALL	C7A03
	CALL	C7F20
	JP	J791D

J79EF:	DEC	A
	LD	(D.D907),A
	LD	A,(D.D90E)
	DEC	A
	LD	(D.D90E),A
	CALL	C7A03
	CALL	C7F20
	JP	J7722

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7A03:	LD	HL,I.D9C8
	DEC	(HL)
	LD	A,(HL)
	CP	0FFH
	JR	NZ,J7A14
	LD	(HL),09H	; 9 
	DEC	HL
	DEC	(HL)
	JR	NZ,J7A14
	LD	(HL),1AH
J7A14:	LD	HL,I.D9C7
	LD	DE,I.3613
	LD	A,02H	; 2 
	CALL	C7F74
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7A20:	PUSH	HL
	PUSH	BC
	LD	HL,I$0213
	LD	BC,I$D9AD
	LD	A,44H	; "D"
	LD	(D.DAD9),A
	CALL	C7BB9			; display string
	XOR	A
	LD	(D.DAD9),A
	POP	BC
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7A37:	PUSH	HL
	PUSH	DE
	PUSH	AF
	LD	HL,C.0014
	LD	DE,I4004
	LD	A,0C0H
	CALL	C7F02
	POP	AF
	POP	DE
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7A49:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	XOR	A
	LD	(D.DAD9),A
	LD	D,01H	; 1 
	LD	A,B
	OR	C
	JR	Z,J7A6F
	LD	A,(D.D905)
	LD	D,A
	ADD	A,A
	ADD	A,D
	CALL	C7CFD			; BC = BC + A
	LD	H,B
	LD	L,C
	LD	BC,I.0078
	LD	D,01H	; 1 
	OR	A
J7A68:	SBC	HL,BC
	JR	C,J7A6F
	INC	D
	JR	J7A68

J7A6F:	LD	A,(D.D905)
	LD	E,A
	ADD	A,A
	ADD	A,E
	LD	HL,(D.D909)
	CALL	C7D04			; HL = HL - A
	PUSH	HL
	POP	IX
	LD	A,(D.D906)
	LD	B,A
	ADD	A,D
	LD	D,A
	ADD	A,A
	ADD	A,D
	CP	11H	; 17 
	JR	C,J7A8C
	LD	A,10H	; 16 
J7A8C:	LD	C,A
	LD	A,B
	ADD	A,A
	ADD	A,B
	LD	L,A
	JR	J7AAA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7A93:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C7E18
	CALL	C7C2C
	LD	A,0FFH
	LD	(D.DB0E),A
	LD	IX,(D.D919)
	LD	L,00H
	LD	C,10H	; 16 
J7AAA:	PUSH	BC
	PUSH	IX
	LD	H,02H	; 2 
	LD	B,0FH	; 15 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J7AB9
	LD	B,1EH
J7AB9:	LD	A,(IX+0)
	LD	E,(IX+1)
	LD	D,(IX+2)
	CALL	C7AE5
	INC	IX
	INC	IX
	INC	IX
	DJNZ	J7AB9
	POP	IX
	LD	BC,I.0078
	ADD	IX,BC
	POP	BC
	INC	L
	INC	L
	INC	L
	LD	A,L
	CP	C
	JR	C,J7AAA
	XOR	A
	LD	(D.DB0E),A
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7AE5:	CP	0FCH
	JR	NC,J7AF0
	BIT	6,A
	CALL	NZ,C7EF6
	JR	NZ,J7AFC
J7AF0:	PUSH	AF
	LD	A,(D.DA8F)
	OR	A
	CALL	Z,C7EE4
	CALL	NZ,C7EEA
	POP	AF
J7AFC:	PUSH	DE
	LD	D,A
	LD	A,(D.DB0E)
	OR	A
	LD	A,D
	POP	DE
	JR	NZ,J7B0F
J7B06:	CP	0FCH
	JP	C,J7EFC
	XOR	A
	JP	J7EFC

J7B0F:	OR	A
	RET	Z
	JR	J7B06

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7B13:	PUSH	AF
	LD	A,0CCH
	LD	(D.DAD9),A
	LD	A,(D.DA8F)
	OR	A
	CALL	Z,C7EE4
	CALL	NZ,C7EEA
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7B25:	PUSH	AF
	PUSH	BC
	CALL	C7B41
	LD	HL,I.D955
	LD	DE,I.D95D
	LD	B,8
J7B32:	LD	C,(HL)
	LD	A,(DE)
	LD	(HL),A
	LD	A,C
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J7B32
	LD	DE,I.D94D
	POP	BC
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  HL = kanji code ?
;	     Outputs ________________________

C7B41:	LD	A,H
	CP	0FFH
	JR	NZ,J7B5B
	LD	B,5
J7B48:	SLA	L
	RL	H
	DJNZ	J7B48
	RES	7,H
	LD	DE,I.D94D
	LD	BC,32
	CALL	C7C20			; copy from/to lower 32KB RAM
	JR	J7B7B

J7B5B:	AND	0F0H
	JP	NZ,J7E1E
	SLA	L
	RL	H
	SLA	L
	RL	H
	RRC	L
	RRC	L
	LD	A,H
	OUT	(0D9H),A
	LD	A,L
	OUT	(0D8H),A
	LD	B,32
	LD	C,0D9H
	LD	HL,I.D94D
	INIR
J7B7B:	LD	DE,I.D94D
	RET

J7B7F:	CALL	C7C38
	JP	J63E4

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7B85:	LD	A,0CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3,2 and 0 (RAM), secunairy slot 3 on page 1 (FIRMWARE)
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	POP	HL
	LD	BC,6
	LD	DE,I$F5A0
	PUSH	DE
	LDIR
	POP	IX
	POP	HL
	POP	DE
	POP	BC
J7B9E:	LD	A,3CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3 and 0 (RAM), secundairy slot 3 on page 2 and 1 (FIRMWARE)
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BA4:	LD	A,0CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3,2 and 0 (RAM), secunairy slot 3 on page 1 (FIRMWARE)
	PUSH	IX
	POP	HL
	DEC	HL
	DEC	HL
	DEC	HL
	LD	BC,I$007E
	LD	DE,I.F528
	LDIR
	JR	J7B9E

;	  Subroutine display string
;	     Inputs  ________________________
;	     Outputs ________________________

C7BB9:	EXX
	LD	HL,S098E3
	JP	J7BE2			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BC0:	EXX
	LD	HL,S0A2EB
	JR	J7BE2			; call routine in segment 0 and quit

?7BC6:	EXX
	LD	HL,S0A125
	JR	J7BE2			; call routine in segment 0 and quit

?7BCC:	EXX
	LD	HL,S0A0F1
	JR	J7BE2			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BD2:	EXX
	LD	HL,S09C93
	JR	J7BE2			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BD8:	EXX
	LD	HL,S098EF
	JR	J7BE2			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BDE:	EXX
	LD	HL,S0995F
J7BE2:	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BE4:	EXX
	LD	HL,S099C3
	JR	J7C30			; call routine in segment 0 and quit

?7BEA:	EXX
	LD	HL,S09A06
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BF0:	EXX
	LD	HL,S09A58
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BF6:	EXX
	LD	HL,S09AC3
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7BFC:	EXX
	LD	HL,S09B80
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C02:	EXX
	LD	HL,S09BBA
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C08:	EXX
	LD	HL,S09BF5
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine operate selection menu
;	     Inputs  ________________________
;	     Outputs ________________________

C7C0E:	EXX
	LD	HL,S09351		; operate selection menu
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C14:	EXX
	LD	HL,S09222
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C1A:	EXX
	LD	HL,S093E6
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine copy from/to lower 32KB RAM
;	     Inputs  ________________________
;	     Outputs ________________________

C7C20:	EXX
	LD	HL,S08000
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C26:	EXX
	LD	HL,S09866
	JR	J7C30			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C2C:	EXX
	LD	HL,S09838
J7C30:	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C32:	EXX
	LD	HL,S09D10
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C38:	EXX
	LD	HL,S095E1
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C3E:	EXX
	LD	HL,S098CD
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C44:	EXX
	LD	HL,S098C1
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C4A:	EXX
	LD	HL,S08023
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C50:	EXX
	LD	HL,S08D9B
	JR	J7C78			; call routine in segment 0 and quit

?7C56:	EXX
	LD	HL,S08CE6
	JR	J7C78			; call routine in segment 0 and quit

?7C5C:	EXX
	LD	HL,S08FAF
	JR	J7C78			; call routine in segment 0 and quit

?7C62:	EXX
	LD	HL,S08C65
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C68:	EXX
	LD	HL,S0907C
	JR	J7C78			; call routine in segment 0 and quit

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7C6E:	EXX
	LD	HL,S0A290
	JR	J7C78			; call routine in segment 0 and quit

?7C74:	EXX
	LD	HL,S080FC

;	  Subroutine call routine in segment 0
;	     Inputs  ________________________
;	     Outputs ________________________

J7C78:	EXX
	PUSH	HL
	PUSH	AF
	LD	A,(D.7FFF)
	LD	(D.DAD0),A		; save old segment
	AND	0FCH			; select segment 0
J7C83:	LD	(D.7FFF),A
	LD	A,(D.DAD0)
	LD	H,A			; saved old segment
	POP	AF
	EX	(SP),HL			; save old segment
	PUSH	IX
	EXX
	PUSH	HL
	EXX
	POP	IX			; address
	PUSH	IY
	LD	IY,08F00H		; slot 3-3
	CALL	CALSLT
	EI
	POP	IY
	POP	IX
	EX	(SP),HL
	PUSH	AF			; old segment
	LD	A,H
	LD	(D.7FFF),A		; restore segment
	POP	AF
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7CAA:	EXX
	LD	HL,S18000
	JR	J7CC6			; call routine in segment 1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7CB0:	EXX
	LD	HL,S18041
	JR	J7CC6			; call routine in segment 1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7CB6:	EXX
	LD	HL,S18096
	JR	J7CC6			; call routine in segment 1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7CBC:	EXX
	LD	HL,S180C6
	JR	J7CC6			; call routine in segment 1

?7CC2:	EXX
	LD	HL,S18163

;	  Subroutine call routine in segment 1
;	     Inputs  ________________________
;	     Outputs ________________________

J7CC6:	EXX
	PUSH	HL
	PUSH	AF
	LD	A,(D.7FFF)
	LD	(D.DAD0),A		; save old segment
	AND	0FCH
	OR	01H			; select segment 1
	JP	J7C83

;	  Subroutine read byte from RAM
;	     Inputs  HL = address
;	     Outputs A = byte

C7CD6:	LD	A,83H			; slot 3-0 (RAM)
	PUSH	BC
	PUSH	DE
	CALL	RDSLT
	POP	DE
	POP	BC
	RET

;	  Subroutine write byte to RAM
;	     Inputs  DE = address, A = byte
;	     Outputs ________________________

C7CE0:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	H,D
	LD	L,E
	LD	E,A
	LD	A,83H			; slot 3-0 (RAM)
	CALL	WRSLT
	POP	HL
	POP	DE
	POP	BC
	RET

;	  Subroutine HL = HL + A
;	     Inputs  ________________________
;	     Outputs ________________________

C7CEF:	ADD	A,L
	LD	L,A
	LD	A,0
	ADC	A,H
	LD	H,A
	RET

;	  Subroutine DE = DE + A
;	     Inputs  ________________________
;	     Outputs ________________________

C7CF6:	ADD	A,E
	LD	E,A
	LD	A,0
	ADC	A,D
	LD	D,A
	RET

;	  Subroutine BC = BC + A
;	     Inputs  ________________________
;	     Outputs ________________________

C7CFD:	ADD	A,C
	LD	C,A
	LD	A,0
	ADC	A,B
D$7D02:	LD	B,A
	RET

;	  Subroutine HL = HL - A
;	     Inputs  ________________________
;	     Outputs ________________________

C7D04:	PUSH	DE
	LD	E,A
	LD	D,0
	OR	A
I7D09:	SBC	HL,DE
	POP	DE
	RET

;	  Subroutine DE = DE - A
;	     Inputs  ________________________
;	     Outputs ________________________

C7D0D:	PUSH	HL
	EX	DE,HL
	LD	E,A
	LD	D,0
	OR	A
	SBC	HL,DE
	EX	DE,HL
	POP	HL
	RET

;	  Subroutine BC = BC - A
;	     Inputs  ________________________
;	     Outputs ________________________

?7D18:	PUSH	HL
	LD	H,B
	LD	L,C
	LD	C,A
	LD	B,0
	SBC	HL,BC
	LD	B,H
	LD	C,L
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7D24:	LD	HL,I400F
	LD	BC,J4012
	LD	DE,I400F
	CALL	C7EDE
	CALL	C7C2C
	LD	IX,(D.D919)
	LD	HL,I.0200
J7D3A:	LD	B,0FH	; 15 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J7D44
	LD	B,1EH
J7D44:	LD	A,(IX+0)
	LD	E,(IX+1)
	LD	D,(IX+2)
	CALL	C7AE5
	INC	IX
	INC	IX
	INC	IX
	DJNZ	J7D44
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7D59:	LD	HL,I.0003
	LD	BC,X.0000
	LD	DE,I400F
	CALL	C7ED8
	XOR	A
	LD	(D.DAD9),A
	CALL	C7C2C
	LD	HL,I.0078
	LD	A,L
	ADD	HL,HL
	ADD	HL,HL
	CALL	C7CEF
	LD	DE,(D.D919)
	ADD	HL,DE
	PUSH	HL
	POP	IX
	LD	HL,I$020F
	JP	J7D3A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7D83:	LD	HL,I.0600
	LD	BC,I.0200
	LD	DE,I.3812
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J7D96
	LD	H,04H	; 4 
	LD	D,3AH	; ":"
J7D96:	CALL	C7ED8
	CALL	C7C2C
	LD	HL,(D.D919)
	LD	A,(D.DA8F)
	OR	A
	LD	A,2AH	; "*"
	LD	DE,I$3A00
	JR	Z,J7DAF
	LD	A,57H	; "W"
	LD	DE,I$3C00
J7DAF:	CALL	C7CEF
	PUSH	HL
	POP	IX
	EX	DE,HL
J7DB6:	LD	B,06H	; 6 
J7DB8:	LD	A,(IX+0)
	LD	E,(IX+1)
	LD	D,(IX+2)
	CALL	C7AE5
	LD	DE,I.0078
	ADD	IX,DE
	INC	L
	INC	L
	INC	L
	DEC	H
	DEC	H
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J7DD6
	DEC	H
	DEC	H
J7DD6:	DJNZ	J7DB8
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7DD9:	LD	HL,I.3A12
	LD	BC,I$3E12
	LD	DE,I.3812
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J7DEC
	LD	H,3CH	; "<"
	LD	D,3AH	; ":"
J7DEC:	CALL	C7EDE
	CALL	C7C2C
	LD	IX,(D.D919)
	LD	HL,I.0200
	JP	J7DB6

?7DFC:	LD	A,0CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3,2 and 0 (RAM), secunairy slot 3 on page 1 (FIRMWARE)
	LD	D,H
	LD	E,L
	LD	(HL),00H
	INC	HL
	LD	(HL),25H	; "%"
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	EX	DE,HL
	LD	BC,I4F35
	LDIR
	LD	A,3CH
	LD	(D.FFFF),A		; secundairy slot 0 on page 3 and 0 (RAM), secundairy slot 3 on page 2 and 1 (FIRMWARE)
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E18:	EXX
	LD	HL,S38062
	JR	J7E46			; call routine in segment 3

J7E1E:	EXX
	LD	HL,S3A747
	JR	J7E46			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E24:	EXX
	LD	HL,S3A363
	JR	J7E46			; call routine in segment 3

J7E2A:	EXX
	LD	HL,S3A426
	JR	J7E46			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E30:	EXX
	LD	HL,S39A21
	JR	J7E46			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E36:	EXX
	LD	HL,S38170
	JR	J7E46			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E3C:	EXX
	LD	HL,S39E08
	JR	J7E46			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E42:	EXX
	LD	HL,S39AC8
J7E46:	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E48:	EXX
	LD	HL,S39C13
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E4E:	EXX
	LD	HL,S39F18
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E54:	EXX
	LD	HL,S39F74
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E5A:	EXX
	LD	HL,S39DE5
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E60:	EXX
	LD	HL,S39DC1
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E66:	EXX
	LD	HL,S39265
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E6C:	EXX
	LD	HL,S392F3
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E72:	EXX
	LD	HL,S39374
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E78:	EXX
	LD	HL,S393EE
	JR	J7EBE			; call routine in segment 3

J7E7E:	EXX
	LD	HL,S3946A
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E84:	EXX
	LD	HL,S39485
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E8A:	EXX
	LD	HL,S394D7
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E90:	EXX
	LD	HL,S3950D
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E96:	EXX
	LD	HL,S3956C
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7E9C:	EXX
	LD	HL,S3911F
	JR	J7EBE			; call routine in segment 3

J7EA2:	EXX
	LD	HL,S38F16
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EA8:	EXX
	LD	HL,S395AA
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EAE:	EXX
	LD	HL,S39591
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EB4:	EXX
	LD	HL,S395C3
	JR	J7EBE			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EBA:	EXX
	LD	HL,S39624
J7EBE:	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EC0:	EXX
	LD	HL,S39764
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EC6:	EXX
	LD	HL,S3969C
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7ECC:	EXX
	LD	HL,S39702
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7ED2:	EXX
	LD	HL,S3957B
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7ED8:	EXX
	LD	HL,S38637
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EDE:	EXX
	LD	HL,S3866A
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EE4:	EXX
	LD	HL,S38239
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EEA:	EXX
	LD	HL,S381D3
	JR	J7F36			; call routine in segment 3

;	  Subroutine display character
;	     Inputs  ________________________
;	     Outputs ________________________

C7EF0:	EXX
	LD	HL,S382A4
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7EF6:	EXX
	LD	HL,S38368
	JR	J7F36			; call routine in segment 3

J7EFC:	EXX
	LD	HL,S383AC
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F02:	EXX
	LD	HL,S380CE
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F08:	EXX
	LD	HL,S381C4
	JR	J7F36			; call routine in segment 3

?7F0E:	EXX
	LD	HL,S386AA
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F14:	EXX
	LD	HL,S387DB
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F1A:	EXX
	LD	HL,S3871A
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F20:	EXX
	LD	HL,S38786
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F26:	EXX
	LD	HL,S38799
	JR	J7F36			; call routine in segment 3

?7F2C:	EXX
	LD	HL,S387F3
	JR	J7F36			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F32:	EXX
	LD	HL,S38800
J7F36:	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F38:	EXX
	LD	HL,S38823
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F3E:	EXX
	LD	HL,S38845
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F44:	EXX
	LD	HL,S3882B
	JR	J7F92			; call routine in segment 3

?7F4A:	EXX
	LD	HL,S381A8
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F50:	EXX
	LD	HL,S380BE
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F56:	EXX
	LD	HL,S3807F
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F5C:	EXX
	LD	HL,S38000
	JR	J7F92			; call routine in segment 3

?7F62:	EXX
	LD	HL,S38188
	JR	J7F92			; call routine in segment 3

?7F68:	EXX
	LD	HL,S3817B
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F6E:	EXX
	LD	HL,S38195
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F74:	EXX
	LD	HL,S3828F
	JR	J7F92			; call routine in segment 3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C7F7A:	EXX
	LD	HL,S3885F
	JR	J7F92			; call routine in segment 3

J7F80:	EXX
	LD	HL,S38894
	JR	J7F92			; call routine in segment 3

J7F86:	EXX
	LD	HL,S38DC0
	JR	J7F92			; call routine in segment 3

J7F8C:	EXX
	LD	HL,S38EEC
	JR	J7F92			; call routine in segment 3

;	  Subroutine call routine in segment 3
;	     Inputs  ________________________
;	     Outputs ________________________

J7F92:	EXX
	PUSH	HL
	PUSH	AF
	LD	A,(D.7FFF)
	LD	(D.DAD0),A		; save old segment
	AND	0FCH
	OR	03H			; select segment 3
	JP	J7C83

?7FA2:	NOP
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I$3700
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4600
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I$3400
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4100
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I$2000
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4800
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4100
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4E00
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4300
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I4800
	LD	B,B
	LD	BC,I.0900
	LD	B,B
	LD	BC,I$C300
	LD	H,C
	LD	H,D
	DEFB	0,0

D.7FFF:	DEFB	0

