;  
;   HX34-3 -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA
;
	.Z80
	ORG	8000H
;
C.0000	EQU	0000H	; -C--I
I.0001	EQU	0001H	; ----I
I$0002	EQU	0002H	; ----I
I$0003	EQU	0003H	; ----I
D.0004	EQU	0004H	; --S-I
CPMADR	EQU	0006H	; ----I
I$0008	EQU	0008H	; ----I
I$0009	EQU	0009H	; ----I
C.000C	EQU	000CH	; -C--I
I.000D	EQU	000DH	; ----I
I.000E	EQU	000EH	; ----I
I.000F	EQU	000FH	; ----I
I.0010	EQU	0010H	; ----I
I$0011	EQU	0011H	; ----I
I.0012	EQU	0012H	; ----I
C.0014	EQU	0014H	; -C---
I.0016	EQU	0016H	; ----I
I$0018	EQU	0018H	; ----I
C.001C	EQU	001CH	; -C---
I$001F	EQU	001FH	; ----I
X.0020	EQU	0020H	; -C-L-
I$0021	EQU	0021H	; ----I
I$0023	EQU	0023H	; ----I
C$0024	EQU	0024H	; -C---
C$0030	EQU	0030H	; -C---
C.0038	EQU	0038H	; -C---
I$003C	EQU	003CH	; ----I
I$003D	EQU	003DH	; ----I
I$0044	EQU	0044H	; ----I
C.004D	EQU	004DH	; -C---
I$0050	EQU	0050H	; ----I
FCB1	EQU	005CH	; -C---
FCB1.1	EQU	005DH	; ----I
I$005F	EQU	005FH	; ----I
I.0060	EQU	0060H	; ----I
I.0061	EQU	0061H	; ----I
I$0064	EQU	0064H	; ----I
I.0078	EQU	0078H	; ----I
I$007F	EQU	007FH	; ----I
C.009C	EQU	009CH	; -C---
C.009F	EQU	009FH	; -C---
C.00A2	EQU	00A2H	; -C---
C$00B4	EQU	00B4H	; -C---
C$00B7	EQU	00B7H	; -C---
C.00C3	EQU	00C3H	; -C---
C.00C6	EQU	00C6H	; -C---
I$00FF	EQU	00FFH	; ----I
I.0100	EQU	0100H	; ----I
I$0101	EQU	0101H	; ----I
I$0104	EQU	0104H	; ----I
I$0117	EQU	0117H	; ----I
D.0120	EQU	0120H	; --S-I
I$012C	EQU	012CH	; ----I
I.0141	EQU	0141H	; ----I
I.0143	EQU	0143H	; ----I
I.0145	EQU	0145H	; ----I
I$0146	EQU	0146H	; ----I
I$0147	EQU	0147H	; ----I
I$0149	EQU	0149H	; ----I
I.014B	EQU	014BH	; ----I
I$014C	EQU	014CH	; ----I
I$014D	EQU	014DH	; ----I
I.014E	EQU	014EH	; ----I
I.0150	EQU	0150H	; ----I
I.0152	EQU	0152H	; ----I
I.0153	EQU	0153H	; ----I
I.0154	EQU	0154H	; ----I
I.0155	EQU	0155H	; ----I
C.0156	EQU	0156H	; -C--I
I$0157	EQU	0157H	; ----I
I$0158	EQU	0158H	; ----I
C.015F	EQU	015FH	; -C---
I$01F5	EQU	01F5H	; ----I
I.01F9	EQU	01F9H	; ----I
I$01FF	EQU	01FFH	; ----I
I.0200	EQU	0200H	; ----I
I$0201	EQU	0201H	; ----I
I.0203	EQU	0203H	; ----I
I$0206	EQU	0206H	; ----I
I$0207	EQU	0207H	; ----I
I$0209	EQU	0209H	; ----I
I$020C	EQU	020CH	; ----I
I$020F	EQU	020FH	; ----I
I$0213	EQU	0213H	; ----I
I.0215	EQU	0215H	; ----I
I.0216	EQU	0216H	; ----I
I$021E	EQU	021EH	; ----I
I$0258	EQU	0258H	; ----I
I$0299	EQU	0299H	; ----I
I$02FF	EQU	02FFH	; ----I
I$035F	EQU	035FH	; ----I
I$0373	EQU	0373H	; ----I
I$03BF	EQU	03BFH	; ----I
I.0400	EQU	0400H	; ----I
C$0404	EQU	0404H	; -C---
I.0415	EQU	0415H	; ----I
I$041D	EQU	041DH	; ----I
I$0550	EQU	0550H	; ----I
I$058D	EQU	058DH	; ----I
I$05A0	EQU	05A0H	; ----I
I$0627	EQU	0627H	; ----I
I$073A	EQU	073AH	; ----I
I.0800	EQU	0800H	; ----I
I.0802	EQU	0802H	; ----I
I.081E	EQU	081EH	; ----I
I.0B9B	EQU	0B9BH	; ----I
I$0C0E	EQU	0C0EH	; ----I
I.0D0D	EQU	0D0DH	; ----I
I.0E0F	EQU	0E0FH	; ----I
I$0E15	EQU	0E15H	; ----I
I.0E1D	EQU	0E1DH	; ----I
I$0E9B	EQU	0E9BH	; ----I
I.0F00	EQU	0F00H	; ----I
I$1002	EQU	1002H	; ----I
I$100F	EQU	100FH	; ----I
I.1200	EQU	1200H	; ----I
I.1202	EQU	1202H	; ----I
I.1206	EQU	1206H	; ----I
I$1208	EQU	1208H	; ----I
I$1209	EQU	1209H	; ----I
I.1215	EQU	1215H	; ----I
I$140D	EQU	140DH	; ----I
I$160E	EQU	160EH	; ----I
I.1802	EQU	1802H	; ----I
I$1A03	EQU	1A03H	; ----I
I$1A07	EQU	1A07H	; ----I
D.1B00	EQU	1B00H	; ---L-
D.1B2F	EQU	1B2FH	; --SL-
D$1B50	EQU	1B50H	; --S--
D$1B52	EQU	1B52H	; ---L-
D$1B53	EQU	1B53H	; --S--
I.1D00	EQU	1D00H	; ----I
I$1E13	EQU	1E13H	; ----I
D.202E	EQU	202EH	; --S-I
I$2042	EQU	2042H	; ----I
I.2045	EQU	2045H	; ----I
I$204C	EQU	204CH	; ----I
I.204E	EQU	204EH	; ----I
I$2050	EQU	2050H	; ----I
I$2052	EQU	2052H	; ----I
I.2054	EQU	2054H	; ----I
I.205F	EQU	205FH	; ----I
I$2120	EQU	2120H	; ----I
I$2121	EQU	2121H	; ----I
I$220C	EQU	220CH	; ----I
I$220F	EQU	220FH	; ----I
D.2500	EQU	2500H	; --S-I
I$2613	EQU	2613H	; ----I
I$27FD	EQU	27FDH	; ----I
I$27FE	EQU	27FEH	; ----I
I$27FF	EQU	27FFH	; ----I
I.2800	EQU	2800H	; ----I
I$2802	EQU	2802H	; ----I
I$2804	EQU	2804H	; ----I
D.2930	EQU	2930H	; --S--
I$2938	EQU	2938H	; ----I
D$2A3E	EQU	2A3EH	; ---L-
I.2C02	EQU	2C02H	; ----I
I$2C0D	EQU	2C0DH	; ----I
I$2C4E	EQU	2C4EH	; ----I
I$2E06	EQU	2E06H	; ----I
I$3020	EQU	3020H	; ----I
D$3030	EQU	3030H	; --S--
I$3031	EQU	3031H	; ----I
I$3035	EQU	3035H	; ----I
I$3131	EQU	3131H	; ----I
I$3133	EQU	3133H	; ----I
I$3136	EQU	3136H	; ----I
I$3201	EQU	3201H	; ----I
I$3231	EQU	3231H	; ----I
D.3233	EQU	3233H	; --S-I
I.3401	EQU	3401H	; ----I
I$340A	EQU	340AH	; ----I
D$3439	EQU	3439H	; ---L-
I$3613	EQU	3613H	; ----I
D$373D	EQU	373DH	; --S--
D$3839	EQU	3839H	; --S--
I$3A0E	EQU	3A0EH	; ----I
I$3A17	EQU	3A17H	; ----I
I$3C08	EQU	3C08H	; ----I
I$3C13	EQU	3C13H	; ----I
I.3E17	EQU	3E17H	; ----I
I.4000	EQU	4000H	; ----I
I.4002	EQU	4002H	; ----I
I$4004	EQU	4004H	; ----I
I$4005	EQU	4005H	; ----I
I$4009	EQU	4009H	; ----I
I$400B	EQU	400BH	; ----I
I$4010	EQU	4010H	; ----I
D$423D	EQU	423DH	; --S--
C$4444	EQU	4444H	; -C---
D$4501	EQU	4501H	; ---L-
I$4858	EQU	4858H	; ----I
D.4F3D	EQU	4F3DH	; --S--
I$5020	EQU	5020H	; ----I
D$5200	EQU	5200H	; ---L-
D$5201	EQU	5201H	; ---L-
C$5E5E	EQU	5E5EH	; -C---
C.61D3	EQU	61D3H	; -C---
C.61DB	EQU	61DBH	; -C---
C.6291	EQU	6291H	; -C---
C.6328	EQU	6328H	; -C---
C.635B	EQU	635BH	; -C---
C.637B	EQU	637BH	; -C---
I$63CD	EQU	63CDH	; ----I
J$6557	EQU	6557H	; J----
I$6C3A	EQU	6C3AH	; ----I
C.71AB	EQU	71ABH	; -C---
D$733A	EQU	733AH	; --S--
C.74AE	EQU	74AEH	; -C---
C.74D0	EQU	74D0H	; -C---
C.75BB	EQU	75BBH	; -C---
C.7663	EQU	7663H	; -C---
I.7800	EQU	7800H	; ----I
C.784F	EQU	784FH	; -C---
C.7A03	EQU	7A03H	; -C---
C.7A37	EQU	7A37H	; -C---
I$7A60	EQU	7A60H	; ----I
C.7AE5	EQU	7AE5H	; -C---
C.7B13	EQU	7B13H	; -C---
C.7B25	EQU	7B25H	; -C---
C$7BC6	EQU	7BC6H	; -C---
C.7BCC	EQU	7BCCH	; -C---
C$7BEA	EQU	7BEAH	; -C---
C.7C14	EQU	7C14H	; -C---
C.7C3E	EQU	7C3EH	; -C---
C.7C44	EQU	7C44H	; -C---
C.7C50	EQU	7C50H	; -C---
C$7C56	EQU	7C56H	; -C---
C$7C5C	EQU	7C5CH	; -C---
C.7C62	EQU	7C62H	; -C---
C$7C74	EQU	7C74H	; -C---
C$7CB0	EQU	7CB0H	; -C---
C$7CB6	EQU	7CB6H	; -C---
C$7CBC	EQU	7CBCH	; -C---
C.7CC2	EQU	7CC2H	; -C---
C.7CD6	EQU	7CD6H	; -C---
C.7CE0	EQU	7CE0H	; -C---
C.7CEF	EQU	7CEFH	; -C---
C$7D04	EQU	7D04H	; -C---
J$7EC0	EQU	7EC0H	; J----
I.C000	EQU	0C000H	; ----I
J$CAEA	EQU	0CAEAH	; J----
I$CC67	EQU	0CC67H	; ----I
I$CEBF	EQU	0CEBFH	; ----I
I.CF38	EQU	0CF38H	; ----I
I.CFC0	EQU	0CFC0H	; ----I
I.CFC1	EQU	0CFC1H	; ----I
I$CFC5	EQU	0CFC5H	; ----I
I.CFC9	EQU	0CFC9H	; ----I
I$CFD1	EQU	0CFD1H	; ----I
I$CFD9	EQU	0CFD9H	; ----I
I.CFF0	EQU	0CFF0H	; ----I
I.CFF1	EQU	0CFF1H	; ----I
I.D0D0	EQU	0D0D0H	; ----I
I.D0F0	EQU	0D0F0H	; ----I
I.D110	EQU	0D110H	; ----I
I.D130	EQU	0D130H	; ----I
I$D142	EQU	0D142H	; ----I
I$D150	EQU	0D150H	; ----I
D.D380	EQU	0D380H	; --SL-
D.D382	EQU	0D382H	; --SL-
D.D3C7	EQU	0D3C7H	; ---L-
D.D3CA	EQU	0D3CAH	; ---L-
I$D3CB	EQU	0D3CBH	; ----I
D.D3CC	EQU	0D3CCH	; ---L-
I.D3CE	EQU	0D3CEH	; ----I
D$D3D6	EQU	0D3D6H	; --S--
D$D3D8	EQU	0D3D8H	; --S--
D.D3DE	EQU	0D3DEH	; --SL-
D.D3DF	EQU	0D3DFH	; --SL-
D$D3E0	EQU	0D3E0H	; --S--
D.D3E2	EQU	0D3E2H	; --SL-
D.D3E4	EQU	0D3E4H	; --SL-
D.D3E6	EQU	0D3E6H	; ---LI
D.D3E7	EQU	0D3E7H	; --SL-
D.D8A0	EQU	0D8A0H	; --SL-
D.D8A2	EQU	0D8A2H	; --SL-
D.D8A4	EQU	0D8A4H	; --SL-
D.D8A5	EQU	0D8A5H	; --SL-
D.D8A8	EQU	0D8A8H	; --SL-
D.D8AA	EQU	0D8AAH	; --SL-
D.D8AC	EQU	0D8ACH	; --SL-
I$D8AD	EQU	0D8ADH	; ----I
I$D8D9	EQU	0D8D9H	; ----I
I$D8E0	EQU	0D8E0H	; ----I
D.D905	EQU	0D905H	; --SLI
D.D906	EQU	0D906H	; --SL-
D.D907	EQU	0D907H	; --SL-
D.D908	EQU	0D908H	; --SL-
D.D909	EQU	0D909H	; --SL-
D.D90B	EQU	0D90BH	; --SL-
D.D90D	EQU	0D90DH	; --SLI
D.D90E	EQU	0D90EH	; --SL-
D.D919	EQU	0D919H	; --SL-
D.D91C	EQU	0D91CH	; --SL-
D.D923	EQU	0D923H	; ---L-
D.D94D	EQU	0D94DH	; --S-I
D$D94E	EQU	0D94EH	; --S--
I$D95D	EQU	0D95DH	; ----I
I.D97D	EQU	0D97DH	; ----I
D.D9BF	EQU	0D9BFH	; --S--
I$D9C2	EQU	0D9C2H	; ----I
I$D9C7	EQU	0D9C7H	; ----I
I$D9C8	EQU	0D9C8H	; ----I
D.D9E0	EQU	0D9E0H	; --SL-
D.D9E1	EQU	0D9E1H	; --SL-
D.D9E3	EQU	0D9E3H	; --SL-
D.D9E5	EQU	0D9E5H	; --SL-
D.D9E7	EQU	0D9E7H	; --SL-
D.DA3B	EQU	0DA3BH	; --SL-
D.DA3C	EQU	0DA3CH	; --SLI
D.DA67	EQU	0DA67H	; --SL-
D.DA6A	EQU	0DA6AH	; --SLI
D.DA8F	EQU	0DA8FH	; --SL-
D.DA90	EQU	0DA90H	; --SLI
D.DA91	EQU	0DA91H	; --SL-
D.DA92	EQU	0DA92H	; --SLI
D.DA93	EQU	0DA93H	; --SL-
D.DA94	EQU	0DA94H	; --SL-
D.DA98	EQU	0DA98H	; ---L-
I$DA9F	EQU	0DA9FH	; ----I
I$DAAF	EQU	0DAAFH	; ----I
D.DAC6	EQU	0DAC6H	; --SL-
D.DACD	EQU	0DACDH	; --SL-
D.DAD9	EQU	0DAD9H	; --SL-
I$DADB	EQU	0DADBH	; ----I
D.DAFF	EQU	0DAFFH	; --SL-
D.DB00	EQU	0DB00H	; --SLI
D.DB01	EQU	0DB01H	; --SL-
D.DB03	EQU	0DB03H	; --SLI
D.DB04	EQU	0DB04H	; --SLI
D.DB05	EQU	0DB05H	; --SL-
D.DB06	EQU	0DB06H	; --SL-
D.DB08	EQU	0DB08H	; --SL-
D.DB09	EQU	0DB09H	; --SL-
D.DB0A	EQU	0DB0AH	; --SL-
D.DB0B	EQU	0DB0BH	; --SL-
D.DB0C	EQU	0DB0CH	; --SLI
D$DB0D	EQU	0DB0DH	; --S--
I$F000	EQU	0F000H	; ----I
D$F323	EQU	0F323H	; --S--
C.F37D	EQU	0F37DH	; -C---
D.F3B1	EQU	0F3B1H	; --S--
D.F3DC	EQU	0F3DCH	; ---L-
I.F800	EQU	0F800H	; ----I
D$F862	EQU	0F862H	; ---L-
D.F866	EQU	0F866H	; ---LI
D.F86C	EQU	0F86CH	; --S--
D.F86D	EQU	0F86DH	; --S--
D$F86E	EQU	0F86EH	; --S--
D$F878	EQU	0F878H	; ---L-
D$F879	EQU	0F879H	; ---L-
I$F87F	EQU	0F87FH	; ----I
D.F922	EQU	0F922H	; --S--
I.FA00	EQU	0FA00H	; ----I
I.FA08	EQU	0FA08H	; ----I
I.FA10	EQU	0FA10H	; ----I
D$FB20	EQU	0FB20H	; ---L-
D.FBE0	EQU	0FBE0H	; ---LI
I$FC9B	EQU	0FC9BH	; ----I
D$FCC2	EQU	0FCC2H	; ---L-
D$FCC3	EQU	0FCC3H	; ---L-
I.FF00	EQU	0FF00H	; ----I
C$FF04	EQU	0FF04H	; -C---
D.FFA7	EQU	0FFA7H	; ---L-
I$FFC0	EQU	0FFC0H	; ----I
C$FFCA	EQU	0FFCAH	; -C---
D.FFFF	EQU	0FFFFH	; --S-I
;
I.8000:	LD	HL,I$8052
	LD	BC,I$0299
	DI	
	OTIR	
	LD	BC,I$0E9B
	OTIR	
	LD	C,00H
	LD	IY,D.8032
J$8014:	LD	L,(IY)
	LD	H,(IY+1)
	INC	IY
	INC	IY
	 CALL	C.8195
;
	INC	C
	LD	A,C
	CP	11H	; 17 
	JR	NZ,J$8014
;
	LD	HL,(D.8032)
	LD	C,00H
	 CALL	C.8195
;
	JP	J$86AA
;
;	-----------------
D.8032:	DEFB	0,0
	LD	H,(HL)
	LD	B,11H	; 17 
	LD	B,51H	; "Q"
	LD	BC,I$0117
	DAA	
	INC	BC
	LD	D,C
	LD	BC,I$0627
	LD	(HL),C
	LD	BC,I$0373
	LD	H,C
	LD	B,64H	; "d"
	LD	B,11H	; 17 
	INC	B
	LD	H,L
	LD	(BC),A
	LD	H,(HL)
	LD	B,77H	; "w"
	RLCA	
I$8052:	NOP	
	SUB	C
	LD	A,(BC)
	LD	H,B
	RRA	
	DEFB	0,0
	RST	30H
;
	LD	E,00H
	EX	AF,AF'
	DEFB	0,0
	LD	BC,C.0000
	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	XOR	A
	LD	(D.DAD9),A
	 CALL	C.817B
;
	LD	A,02H	; 2 
	 CALL	C.8142
;
	 CALL	C.8111
;
	LD	HL,I$80B3
I.8078:	LD	BC,I.0B9B
	OTIR	
	JR	J.8096
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.807F:	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	 CALL	C.817B
;
	LD	A,02H	; 2 
	 CALL	C.8142
;
	 CALL	C.8111
;
	LD	HL,I$80A8
	LD	BC,I.0B9B
	OTIR	
J.8096:	IN	A,(99H)
	BIT	0,A
	JR	NZ,J.8096
;
	XOR	A
	 CALL	C.8142
;
	 CALL	C.8188
;
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET	
;
;	-----------------
I$80A8:	DEFB	0,0,0,0,0
	LD	(BC),A
	 CALL	NC,C.0000
;
	NOP	
	RET	NZ
;
I$80B3:	DEFB	0,0,0,0,0
	LD	(BC),A
	SUB	A
	DEFB	0,0,0
	RET	NZ
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.80BE:	PUSH	AF
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$80CD
;
	SRL	H
	LD	A,0FH	; 15 
	ADD	A,H
	LD	H,A
	SRL	D
J$80CD:	POP	AF
	PUSH	AF
	AND	0F0H
	LD	B,A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	ADD	A,B
	LD	(D.DAD9),A
	 CALL	C.817B
;
	LD	A,02H	; 2 
	 CALL	C.8142
;
	 CALL	C.8111
;
	PUSH	DE
	 CALL	C.8121
;
	POP	HL
	 CALL	C.8121
;
	POP	AF
	LD	H,A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0FH	; 15 
	OUT	(9BH),A
	XOR	A
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
	LD	A,H
	AND	0FH	; 15 
	ADD	A,80H
	OUT	(9BH),A
J$8103:	IN	A,(99H)
	BIT	0,A
	JR	NZ,J$8103
;
	XOR	A
	 CALL	C.8142
;
	 CALL	C.8188
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8111:	LD	A,24H	; "$"
	JR	J$8117
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8115:	LD	A,20H	; " "
J$8117:	DI	
	OUT	(99H),A
	LD	A,91H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(99H),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8121:	DI	
	PUSH	HL
	LD	C,L
	LD	L,H
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
	LD	L,C
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8142:	PUSH	BC
	DI	
	LD	C,0FH	; 15 
	 CALL	C.8170
;
	POP	BC
	RET	
;
;	-----------------
?.814B:	DI	
	PUSH	AF
	PUSH	BC
	LD	A,H
	RLCA	
	RLCA	
	AND	03H	; 3 
	LD	C,0EH	; 14 
	 CALL	C.8170
;
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH	; "?"
	ADD	A,40H	; "@"
	OUT	(99H),A
	POP	BC
	POP	AF
	LD	H,A
J$8165:	PUSH	BC
	POP	BC
	LD	A,H
	OUT	(98H),A
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$8165
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8170:	DI	
	OUT	(99H),A
	LD	A,C
	ADD	A,80H
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.817B:	PUSH	AF
	PUSH	BC
	DI	
	LD	A,40H	; "@"
	LD	C,01H	; 1 
	 CALL	C.8170
;
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8188:	PUSH	AF
	PUSH	BC
	LD	A,60H	; "`"
	LD	C,01H	; 1 
	 CALL	C.8170
;
	EI	
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8195:	PUSH	BC
	PUSH	AF
	LD	A,C
	LD	C,10H	; 16 
	 CALL	C.8170
;
	LD	A,L
	OUT	(9AH),A
	LD	A,H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9AH),A
	POP	AF
	POP	BC
	RET	
;
;	-----------------
?.81A8:	PUSH	AF
	PUSH	HL
	LD	HL,I$03BF
	RST	20H
;
	JR	C,J$81C0
;
	LD	HL,I$035F
	RST	20H
;
	JR	NC,J$81BA
;
J$81B6:	POP	HL
	POP	AF
	SCF	
	RET	
;
;	-----------------
J$81BA:	LD	HL,I$005F
	RST	20H
;
	JR	NC,J$81B6
;
J$81C0:	POP	HL
	POP	AF
	OR	A
	RET	
;
;	-----------------
?.81C4:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	A,(D.DA8F)
	OR	A
	LD	A,02H	; 2 
	JP	Z,J.8244
;
	JP	J.81DE
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$81D3:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	 CALL	C.7B25
;
	LD	A,02H	; 2 
	POP	HL
J.81DE:	PUSH	HL
	PUSH	AF
	 CALL	C.835A
;
	DI	
	LD	C,10H	; 16 
J$81E6:	LD	A,H
	AND	0C0H
	RLCA	
	RLCA	
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	LD	A,8EH
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(99H),A
	LD	A,(DE)
	INC	DE
	LD	(D.DACD),A
	PUSH	HL
	LD	B,04H	; 4 
J$8207:	LD	A,(D.DACD)
	PUSH	BC
	LD	C,A
	LD	A,(D.DAD9)
	RLC	C
	JR	NC,J$8217
;
	AND	0FH	; 15 
	OR	10H	; 16 
J$8217:	RLC	C
	JR	NC,J$821F
;
	AND	0F0H
	OR	01H	; 1 
J$821F:	EX	AF,AF'
	LD	A,C
	LD	(D.DACD),A
	POP	BC
	EX	AF,AF'
	OUT	(98H),A
	DJNZ	J$8207
;
	POP	HL
	INC	H
	DEC	C
	JR	NZ,J$81E6
;
	POP	AF
	POP	HL
	INC	H
	DEC	A
	JR	NZ,J.81DE
;
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8239:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	 CALL	C.7B25
;
	LD	A,02H	; 2 
	POP	HL
J.8244:	PUSH	HL
	PUSH	AF
	 CALL	C.835A
;
	DI	
	LD	C,10H	; 16 
J$824C:	LD	A,H
	AND	0C0H
	RLCA	
	RLCA	
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	LD	A,8EH
	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(99H),A
	LD	A,(DE)
	INC	DE
	LD	(D.DACD),A
	PUSH	HL
	LD	B,08H	; 8 
J$826D:	LD	A,(D.DACD)
	RLCA	
	LD	(D.DACD),A
	LD	A,(D.DAD9)
	JR	NC,J$827B
;
	LD	A,11H	; 17 
J$827B:	OUT	(98H),A
	DJNZ	J$826D
;
	POP	HL
	INC	H
	DEC	C
	JR	NZ,J$824C
;
	POP	AF
	POP	HL
	INC	H
	INC	H
	DEC	A
	JR	NZ,J.8244
;
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$828F:	PUSH	BC
	LD	B,A
	LD	A,44H	; "D"
	LD	(D.DAD9),A
	EX	DE,HL
J$8297:	LD	A,(DE)
	INC	DE
	 CALL	C$82A4
;
	DJNZ	J$8297
;
	XOR	A
	LD	(D.DAD9),A
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$82A4:	CP	0DH	; 13 
	JR	NZ,J$82AC
;
	LD	H,00H
	INC	L
	RET	
;
;	-----------------
J$82AC:	PUSH	BC
	PUSH	DE
	LD	DE,(D.0004)
	CP	1BH
	JR	NC,J$82B9
;
	LD	DE,I$845F
J$82B9:	PUSH	HL
	LD	H,00H
	LD	B,03H	; 3 
J$82BE:	SLA	A
	RL	H
	DJNZ	J$82BE
;
	LD	L,A
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	PUSH	HL
	 CALL	C.8111
;
	 CALL	C.8121
;
I$82CF:	LD	HL,I$0201
	 CALL	C.8121
;
	POP	HL
	INC	H
	INC	H
	PUSH	HL
	EX	DE,HL
	LD	A,(HL)
	INC	HL
	RLCA	
	LD	(D.DACD),A
	LD	A,(D.DAD9)
	JR	NC,J$82E7
;
	LD	A,11H	; 17 
J$82E7:	 CALL	C.833C
;
	OUT	(9BH),A
	XOR	A
	EX	(SP),HL
	OUT	(9BH),A
	LD	A,0F0H
	EX	(SP),HL
	OUT	(9BH),A
	 CALL	C.817B
;
	LD	A,02H	; 2 
	 CALL	C.8142
;
	LD	A,0ACH
	LD	C,11H	; 17 
	 CALL	C.8170
;
	LD	C,08H	; 8 
	LD	B,07H	; 7 
	JR	J.8314
;
;	-----------------
J$830A:	DEC	C
	JR	Z,J.8331
;
	LD	A,(HL)
	LD	(D.DACD),A
	INC	HL
	LD	B,08H	; 8 
J.8314:	IN	A,(99H)
	BIT	0,A
	JR	Z,J.8331
;
	LD	A,(D.DACD)
	RLCA	
	LD	(D.DACD),A
	LD	A,(D.DAD9)
	JR	NC,J$8328
;
	LD	A,11H	; 17 
J$8328:	 CALL	C.833C
;
	OUT	(9BH),A
	DJNZ	J.8314
;
	JR	J$830A
;
;	-----------------
J.8331:	XOR	A
	 CALL	C.8142
;
	 CALL	C.8188
;
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.833C:	PUSH	HL
	LD	H,A
	AND	0FH	; 15 
	CP	01H	; 1 
	JR	NZ,J$834A
;
	LD	A,H
	AND	0F0H
	ADD	A,0EH	; 14 
	LD	H,A
J$834A:	LD	A,H
	AND	0F0H
	CP	10H	; 16 
	JR	NZ,J$8357
;
	LD	A,H
	AND	0FH	; 15 
	ADD	A,0E0H
	LD	H,A
J$8357:	LD	A,H
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.835A:	SLA	H
	SLA	H
	SLA	L
	SLA	L
	SLA	L
	LD	A,L
	LD	L,H
	LD	H,A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8368:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	DE
	LD	H,00H
	LD	A,E
	CP	60H	; "`"
	JR	C,J$8376
;
	LD	H,03H	; 3 
J$8376:	LD	L,A
	 CALL	C.7B25
;
	EX	DE,HL
	LD	DE,I.D97D
	LD	BC,I.0010
	LDIR	
	POP	DE
	LD	H,00H
	LD	A,D
	CP	60H	; "`"
	JR	C,J$838D
;
	LD	H,03H	; 3 
J$838D:	LD	L,A
	 CALL	C.7B25
;
	LD	HL,I.D97D
	LD	DE,I$D95D
	LD	BC,I.0010
	LDIR	
	LD	DE,D.D94D
	LD	A,(D.DA8F)
	OR	A
	LD	A,02H	; 2 
	POP	HL
	JP	Z,J.8244
;
	JP	J.81DE
;
;	-----------------
?.83AC:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	HL
	PUSH	AF
	AND	0FH	; 15 
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	HL,I$8537
	 CALL	C.7CEF
;
	LD	DE,D.D94D
	LD	BC,I.0010
	LDIR	
	POP	AF
	BIT	4,A
	JR	Z,J$83D3
;
	LD	A,0FFH
	LD	(D.D94D),A
	LD	(D$D94E),A
J$83D3:	POP	HL
	DEC	H
	DEC	H
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J$83DE
;
	DEC	H
	DEC	H
J$83DE:	INC	L
	INC	L
	 CALL	C.835A
;
	LD	A,08H	; 8 
	LD	DE,D.D94D
	DI	
J.83E9:	PUSH	AF
	PUSH	HL
	LD	C,02H	; 2 
	LD	A,H
	AND	0C0H
	RLCA	
	RLCA	
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(99H),A
J.8402:	LD	A,(DE)
	INC	DE
	LD	(D.DACD),A
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$843D
;
	LD	B,04H	; 4 
J$840F:	LD	A,(D.DACD)
	PUSH	BC
	LD	C,A
	LD	A,(D.DAD9)
	RLC	C
	JR	NC,J$841F
;
	AND	0FH	; 15 
	OR	10H	; 16 
J$841F:	RLC	C
	JR	NC,J$8427
;
	AND	0F0H
	OR	01H	; 1 
J$8427:	EX	AF,AF'
	LD	A,C
	LD	(D.DACD),A
	POP	BC
	EX	AF,AF'
	OUT	(98H),A
	DJNZ	J$840F
;
	DEC	C
	JR	NZ,J.8402
;
	POP	HL
	POP	AF
	INC	H
	DEC	A
	JR	NZ,J.83E9
;
	JR	J$845A
;
;	-----------------
J$843D:	LD	B,08H	; 8 
J$843F:	LD	A,(D.DACD)
	RLCA	
	LD	(D.DACD),A
	LD	A,(D.DAD9)
	JR	NC,J$844D
;
	LD	A,11H	; 17 
J$844D:	OUT	(98H),A
	DJNZ	J$843F
;
	DEC	C
	JR	NZ,J.8402
;
	POP	HL
	POP	AF
	INC	H
	DEC	A
	JR	NZ,J.83E9
;
J$845A:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$845F:	NOP	
	INC	A
	LD	B,D
	LD	B,(HL)
	LD	E,D
	LD	H,D
	LD	B,D
	INC	A
	NOP	
	EX	AF,AF'
	JR	J$8493
;
;	-----------------
?.846B:	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	LD	A,00H
	INC	A
	LD	B,D
	LD	(BC),A
	INC	C
	JR	NC,J$84B6
;
	LD	A,(HL)
	NOP	
	INC	A
	LD	B,D
	LD	(BC),A
	INC	A
	LD	(BC),A
	LD	B,D
	INC	A
	NOP	
	INC	B
	INC	C
	INC	D
	INC	H
	LD	A,(HL)
	INC	B
	INC	B
	NOP	
	LD	A,(HL)
	LD	B,B
	LD	A,B
	INC	B
	LD	(BC),A
	LD	B,H
	JR	C,J$8490
;
J$8490:	INC	E
	JR	NZ,J.84D3
;
J$8493:	LD	A,H
	LD	B,D
	LD	B,D
	INC	A
	NOP	
	LD	A,(HL)
	LD	B,D
	INC	B
	EX	AF,AF'
	DJNZ	J$84AE
;
	DJNZ	J$84A0
;
J$84A0:	INC	A
	LD	B,D
	LD	B,D
	INC	A
	LD	B,D
	LD	B,D
	INC	A
	NOP	
	INC	A
	LD	B,D
	LD	B,D
	LD	A,02H	; 2 
	INC	B
J$84AE:	JR	C,J$84B0
;
J$84B0:	INC	A
	JR	NZ,J.84D3
;
	JR	NZ,J$84D5
;
	JR	NZ,J$84F3
J$84B6	EQU	$-1
;
	NOP	
	INC	A
	INC	B
	INC	B
	INC	B
	INC	B
	INC	B
	INC	A
	NOP	
	LD	A,(HL)
	LD	B,D
	LD	B,D
	LD	B,D
	LD	B,D
	LD	B,D
	LD	A,(HL)
	DEFB	0,0,0,0
	LD	A,00H
	DEFB	0,0,0
	LD	A,(HL)
	LD	(BC),A
	LD	(BC),A
J.84D3:	INC	B
	JR	Z,J$84E6
J$84D5	EQU	$-1
;
	EX	AF,AF'
	JR	J$84D8
J$84D8	EQU	$-1
;
;	-----------------
?.84D9:	CP	L
	EX	AF,AF'
	LD	A,(HL)
	EX	AF,AF'
	INC	B
	JR	C,J$84E0
;
J$84E0:	DJNZ	J$8560
;
	LD	(DE),A
	LD	(DE),A
	LD	(DE),A
	LD	(DE),A
J$84E6:	INC	H
	NOP	
	EX	AF,AF'
	EX	AF,AF'
	LD	A,(HL)
	EX	AF,AF'
	EX	AF,AF'
	DJNZ	J$850F
;
	JR	J$856F
;
;	-----------------
?.84F1:	INC	B
	INC	H
J$84F3:	JR	J$850D
;
;	-----------------
?.84F5:	INC	H
	LD	B,D
	NOP	
	INC	L
	LD	E,(HL)
	 CALL	Z,C$5E5E
;
	LD	D,D
	LD	E,(HL)
	NOP	
	EX	AF,AF'
	INC	D
	LD	A,49H	; "I"
	LD	A,08H	; 8 
	LD	A,A
	SUB	D
	LD	D,H
J$8509:	JR	C,J$8509
;
J$850B:	DJNZ	J$850B
;
J$850D:	DJNZ	J$851F
;
J$850F:	INC	E
	JR	Z,J$8590
;
	LD	HL,(D$2A3E)
	LD	A,46H	; "F"
	DEFB	0,0
	JR	J$8557
;
;	-----------------
?.851B:	LD	A,(HL)
	RST	38H
	DEFB	0,0
J$851F:	LD	E,(HL)
	AND	B
	LD	E,A
	 CALL	NZ,C$4444
;
	LD	B,H
	LD	C,H
	LD	C,B
	OR	48H	; "H"
	RST	38H
	JP	PE,J$CAEA
;
	LD	C,D
	DEFB	0,0,0,0,0,0,0,0
I$8537:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,C.0000
J$8557	EQU	$-1
	DEFB	0,0,0,0,0
	LD	BC,I$00FF
J$8560:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0
	LD	BC,I$01FF
J$856F	EQU	$-1
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,C.0000
	DEFB	0,0,0,0,0,0,0
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
J$8590	EQU	$-2
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	RST	38H
	DEFB	0,0,0,0,0,0,0,0
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	RST	38H
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	DEFB	0,0,0,0,0,0,0
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	DEFB	0,0,0,0,0,0,0
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.FF00
	DEFB	0,0,0,0,0,0,0,0,0
	LD	BC,I.0100
	NOP	
	LD	BC,I.FF00
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
	LD	BC,I.FF00
	RST	38H
	DEFB	0,0,0,0,0,0,0,0
	LD	BC,I.0100
	NOP	
	LD	BC,I.FF00
	RST	38H
	LD	BC,I.0100
	NOP	
	LD	BC,I.0100
	NOP	
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8637:	 CALL	C.817B
;
	LD	A,02H	; 2 
	 CALL	C.8142
;
	 CALL	C.8115
;
	PUSH	DE
	PUSH	BC
	 CALL	C.8121
;
	POP	HL
	 CALL	C.8121
;
	POP	HL
	 CALL	C.8121
;
	XOR	A
	OUT	(9BH),A
J$8652:	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
	LD	A,0D0H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
J$865C:	IN	A,(99H)
	BIT	0,A
	JR	NZ,J$865C
;
	XOR	A
	 CALL	C.8142
;
	 CALL	C.8188
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.866A:	 CALL	C.817B
;
	LD	A,02H	; 2 
	 CALL	C.8142
;
	 CALL	C.8115
;
	PUSH	DE
	PUSH	BC
	 CALL	C.868A
;
	POP	HL
	 CALL	C.868A
;
	POP	HL
	 CALL	C.8121
;
	XOR	A
	OUT	(9BH),A
	LD	A,0CH	; 12 
	JP	J$8652
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.868A:	LD	C,L
	LD	L,H
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	DEC	HL
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
	LD	L,C
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	DEC	HL
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(9BH),A
	RET	
;
;	-----------------
J$86AA:	 CALL	C.817B
;
	LD	HL,I$F000
	 CALL	C.882B
I.86B1	EQU	$-2
;
	LD	HL,I$8706
	LD	B,10H	; 16 
J$86B8:	LD	A,(HL)
	INC	HL
	OUT	(98H),A
	EX	(SP),HL
	EX	(SP),HL
	DJNZ	J$86B8
;
	LD	HL,I.F800
	 CALL	C.882B
;
	LD	B,20H	; " "
J$86C8:	LD	A,27H	; "'"
	OUT	(98H),A
	EX	(SP),HL
	EX	(SP),HL
	DJNZ	J$86C8
;
	LD	B,20H	; " "
J$86D2:	LD	A,29H	; ")"
	OUT	(98H),A
	EX	(SP),HL
	EX	(SP),HL
	DJNZ	J$86D2
;
	LD	B,20H	; " "
J$86DC:	LD	A,27H	; "'"
	OUT	(98H),A
	EX	(SP),HL
	EX	(SP),HL
	DJNZ	J$86DC
;
	LD	HL,I.FA00
	 CALL	C.882B
;
	LD	HL,I$8716
	LD	C,06H	; 6 
J$86EF:	PUSH	HL
	LD	B,04H	; 4 
J$86F2:	LD	A,(HL)
	INC	HL
	OUT	(98H),A
	EX	(SP),HL
	EX	(SP),HL
	DJNZ	J$86F2
;
	POP	HL
	DEC	C
	JR	NZ,J$86EF
;
	LD	A,0D8H
	OUT	(98H),A
	 CALL	C.8188
;
	RET	
;
;	-----------------
I$8706:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
	NOP	
I$8716:	PUSH	DE
	DEFB	0,0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.871A:	LD	A,(D.D906)
	CP	06H	; 6 
I$871F:	JP	NC,J.87F3
;
	LD	H,0FH	; 15 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$872C
I$8729	EQU	$-1
;
	LD	H,1EH
J$872C:	LD	A,(D.D905)
	LD	D,A
	CP	H
	JP	NC,J.87F3
;
	LD	HL,I.FA00
	 CALL	C.882B
;
	LD	A,(D.D906)
J$873D:	LD	B,A
	ADD	A,A
	ADD	A,B
	ADD	A,02H	; 2 
	ADD	A,A
	ADD	A,A
	ADD	A,A
	SUB	03H	; 3 
	LD	C,A
	OUT	(98H),A
	SLA	D
	SLA	D
	SLA	D
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J$8758
;
	SLA	D
J$8758:	LD	A,08H	; 8 
	ADD	A,D
	LD	D,A
	OUT	(98H),A
	LD	A,01H	; 1 
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	XOR	A
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	LD	A,C
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	LD	A,08H	; 8 
	ADD	A,D
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	LD	A,(D.DA8F)
	OR	A
	LD	A,01H	; 1 
	JR	Z,J$877E
;
	XOR	A
J$877E:	OUT	(98H),A
	XOR	A
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	RET	
;
;	-----------------
?.8786:	 CALL	C.871A
;
	LD	HL,I.FA08
	 CALL	C.882B
;
	LD	A,(D.D907)
	LD	D,A
	LD	A,(D.D908)
	JP	J$873D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8799:	LD	HL,I.FA10
	 CALL	C.882B
;
	LD	A,(D.D9E1)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,04H	; 4 
	LD	L,A
	OUT	(98H),A
	LD	A,(D.D9E0)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	H,A
	OUT	(98H),A
	LD	A,01H	; 1 
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	XOR	A
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	LD	A,L
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	LD	A,08H	; 8 
	ADD	A,H
	EX	(SP),HL
I$87C7:	EX	(SP),HL
	OUT	(98H),A
	LD	A,(D.DA8F)
	OR	A
	LD	A,01H	; 1 
	JR	Z,J$87D3
;
	XOR	A
J$87D3:	OUT	(98H),A
	XOR	A
	EX	(SP),HL
	EX	(SP),HL
	OUT	(98H),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$87DB:	PUSH	HL
	PUSH	BC
	PUSH	AF
	LD	HL,I.FA00
	 CALL	C.882B
;
	LD	B,18H
J.87E6:	XOR	A
	OUT	(98H),A
I$87E9:	PUSH	IX
	POP	IX
	DJNZ	J.87E6
;
	POP	AF
	POP	BC
	POP	HL
	RET	
;
;	-----------------
J.87F3:	PUSH	HL
	PUSH	BC
	PUSH	AF
	LD	HL,I.FA00
J.87F9:	 CALL	C.882B
;
	LD	B,08H	; 8 
	JR	J.87E6
;
;	-----------------
?.8800:	PUSH	HL
	PUSH	BC
	PUSH	AF
	LD	A,(D.D907)
	LD	(D.D905),A
	LD	A,(D.D908)
	LD	(D.D906),A
	LD	HL,(D.D90B)
	LD	(D.D909),HL
	LD	A,(D.D90E)
	LD	(D.D90D),A
	 CALL	C.871A
;
	LD	HL,I.FA08
	JR	J.87F9
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8823:	PUSH	HL
	PUSH	BC
	PUSH	AF
	LD	HL,I.FA10
	JR	J.87F9
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.882B:	PUSH	AF
	PUSH	BC
	DI	
	LD	C,0EH	; 14 
	LD	A,H
	AND	0C0H
	RLCA	
	RLCA	
	 CALL	C.8170
;
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(99H),A
	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.8845:	PUSH	AF
	PUSH	BC
	DI	
	LD	C,0EH	; 14 
	LD	A,H
	AND	0C0H
	RLCA	
	RLCA	
	 CALL	C.8170
;
	LD	A,L
	OUT	(99H),A
	LD	A,H
	AND	3FH	; "?"
	EX	(SP),HL
	EX	(SP),HL
	OUT	(99H),A
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.885F:	LD	HL,I.D130
	LD	(D.D9E3),HL
	LD	(D.D9E5),HL
	LD	(D.D9E7),HL
J$886B:	LD	A,0CCH
	LD	(D.DAD9),A
	LD	HL,I.0215
	 CALL	C.7C3E
;
	LD	HL,(D.D9E7)
	LD	DE,I.D130
	RST	20H
;
	JR	NZ,J.8891
;
J.887F:	LD	A,(D.DA8F)
	OR	A
	LD	A,07H	; 7 
	JR	Z,J$8889
;
	LD	A,04H	; 4 
J$8889:	LD	(D.D9E0),A
	LD	A,16H
	LD	(D.D9E1),A
J.8891:	 CALL	C.8799
;
J.8894:	 CALL	C.74D0
;
	JR	NC,J$88BA
;
	 CALL	C.61D3
;
	LD	HL,(D.D9E7)
	LD	DE,I.D130
	RST	20H
;
	JR	NZ,J.8894
;
	XOR	A
	LD	(D.D91C),A
	 CALL	C.7A37
;
	XOR	A
	LD	(D.DAD9),A
	 CALL	C.8823
;
	SCF	
	RET	
;
;	-----------------
J.88B5:	 CALL	C.61DB
;
	JR	J.8894
;
;	-----------------
J$88BA:	LD	HL,D.FBE0
	BIT	1,(HL)
	JR	Z,J.88B5
;
	BIT	2,(HL)
	JR	Z,J.88B5
;
	BIT	0,(HL)
	JR	Z,J$88F5
;
	LD	D,0F0H
	LD	BC,J.8A6B
	BIT	5,(HL)
	JR	Z,J.88E2
;
	INC	D
	LD	BC,I.8A73
	BIT	6,(HL)
	JR	Z,J.88E2
;
	BIT	7,(HL)
	JR	NZ,J$88FA
;
	LD	BC,I.8A7B
	INC	D
J.88E2:	LD	A,(D.D91C)
	CP	0F3H
	JR	NC,J.88B5
;
	LD	A,D
	LD	(D.D91C),A
	PUSH	BC
	 CALL	C.61DB
;
	POP	BC
	JP	J$886B
;
;	-----------------
J$88F5:	CP	0DH	; 13 
	JP	Z,J$8D53
;
J$88FA:	CP	7FH
	JP	Z,J.8C1D
;
	CP	20H	; " "
	JR	NC,J$892C
;
	CP	08H	; 8 
	JP	Z,J$8CB9
;
	CP	0DH	; 13 
	JP	Z,J$8E12
;
	CP	1CH
	JP	Z,J$8B41
;
	CP	1DH
	JP	Z,J$8BAF
;
	CP	1EH
	JP	Z,J$8AC3
;
	CP	1FH
	JP	Z,J$8ADE
;
	CP	12H	; 18 
	JP	Z,J$8ABC
;
	 CALL	C.61DB
;
	JP	J.8894
;
;	-----------------
J$892C:	 CALL	C$8A61
;
	JP	C,J.8894
;
	PUSH	AF
	LD	HL,(D.D9E7)
	LD	DE,I$D8E0
	RST	20H
;
	JR	NZ,J$8981
;
	POP	AF
	 CALL	C.61D3
;
	 CALL	C.7A37
;
	 CALL	C.8823
;
	LD	HL,I.0415
	LD	BC,I$8A83
	 CALL	C.7C44
;
	LD	H,00H
	LD	B,02H	; 2 
J.8953:	INC	HL
	LD	A,H
	OR	L
	JR	NZ,J.8953
;
	DJNZ	J.8953
;
J.895A:	 CALL	C.61D3
;
	 CALL	C.61DB
;
	 CALL	C.7A37
;
	LD	A,(D.D91C)
	LD	BC,J.8A6B
	CP	0F1H
	JR	C,J.8975
;
	LD	BC,I.8A73
	JR	Z,J.8975
;
	LD	BC,I.8A7B
J.8975:	LD	HL,I.0215
	 CALL	C.7C3E
;
	 CALL	C.90E8
;
	JP	J.8891
;
;	-----------------
J$8981:	LD	HL,(D.D9E7)
	LD	A,(D.D91C)
	CP	0F3H
	JR	C,J.8998
;
	LD	DE,I$D142
	RST	20H
;
	JR	NZ,J.8998
;
	POP	AF
	 CALL	C.61D3
;
	JP	J.88B5
;
;	-----------------
J.8998:	LD	DE,(D.D9E5)
	PUSH	HL
	OR	A
	SBC	HL,DE
	LD	B,H
	LD	C,L
	POP	HL
	JR	Z,J$89AB
;
	LD	D,H
	LD	E,L
	DEC	HL
	INC	DE
	LDDR	
J$89AB:	LD	HL,(D.D9E5)
	POP	AF
	 CALL	C.7C50
;
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(D.D9E5),HL
	LD	HL,(D.D9E7)
	INC	HL
	INC	HL
	LD	(D.D9E7),HL
	PUSH	DE
	LD	DE,(D.D9E5)
	RST	20H
;
	JR	NZ,J$8A15
;
	LD	A,(D.D9E0)
	RLCA	
	LD	H,A
	LD	L,15H
	POP	DE
	 CALL	C.7B13
;
	LD	A,(D.DA8F)
	OR	A
	LD	HL,I.1215
	LD	BC,I.0E1D
	LD	DE,I.2C02
	JR	Z,J$89EB
;
	LD	H,0AH	; 10 
	LD	BC,I.081E
	LD	DE,I.3401
J$89EB:	LD	A,(D.D9E0)
	CP	C
	JR	Z,J$89F8
;
	ADD	A,E
	LD	(D.D9E0),A
	JP	J.8891
;
;	-----------------
J$89F8:	LD	E,02H	; 2 
	LD	C,L
	PUSH	AF
	 CALL	C.8637
;
	POP	AF
	LD	DE,I.0061
J$8A03:	LD	HL,(D.D9E3)
	INC	HL
	INC	HL
	LD	(D.D9E3),HL
J$8A0B:	LD	L,15H
	RLCA	
	LD	H,A
	 CALL	C.7B13
;
	JP	J.8891
;
;	-----------------
J$8A15:	LD	A,(D.DA8F)
	OR	A
	LD	HL,I.1215
	LD	BC,I.0E1D
	LD	DE,I$2802
	JR	Z,J$8A2C
;
	LD	H,0AH	; 10 
	LD	BC,I.081E
	LD	DE,I$3201
J$8A2C:	LD	A,(D.D9E0)
	CP	C
	JR	NZ,J$8A3E
;
	SUB	E
	LD	E,02H	; 2 
	LD	C,L
	PUSH	AF
	 CALL	C.8637
;
	POP	AF
	POP	DE
	JR	J$8A03
;
;	-----------------
J$8A3E:	PUSH	AF
	ADD	A,E
	LD	(D.D9E0),A
	EX	AF,AF'
	LD	BC,I.3E17
	LD	HL,I$3A17
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$8A52
;
	LD	H,3CH	; "<"
J$8A52:	EX	AF,AF'
	RLCA	
	LD	E,A
	LD	A,B
	SUB	E
	LD	D,A
	LD	E,02H	; 2 
	 CALL	C.866A
;
	POP	AF
	POP	DE
	JR	J$8A0B
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8A61:	CP	0DEH
	JR	Z,J.8A6B
;
	CP	0DFH
	JR	Z,J.8A6B
;
	OR	A
	RET	
;
;	-----------------
J.8A6B:	LD	B,A
	LD	HL,(D.D9E5)
	LD	DE,I.D130
	RST	20H
;
I.8A73:	LD	A,B
	RET	Z
;
	DEC	HL
	LD	D,(HL)
	DEC	HL
	LD	E,(HL)
	CP	0DEH
I.8A7B:	PUSH	AF
	LD	A,D
	JR	NZ,J$8A87
;
	 CALL	C$7CB0
;
	JR	NC,J$8A8C
I$8A83	EQU	$-1
;
J$8A84:	POP	AF
	OR	A
	RET	
;
;	-----------------
J$8A87:	 CALL	C$7CB6
;
	JR	C,J$8A84
;
J$8A8C:	LD	(HL),E
	INC	HL
	LD	(HL),D
	LD	A,(D.DA8F)
	OR	A
	LD	H,02H	; 2 
	JR	Z,J$8A99
;
	LD	H,01H	; 1 
J$8A99:	LD	A,(D.D9E0)
	SUB	H
	RLCA	
	LD	H,A
I$8A9F:	LD	L,15H
	 CALL	C.7B13
;
	POP	AF
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8AA7:	PUSH	AF
	LD	A,(D.D91C)
	CP	0F3H
	JR	NC,J.8AB9
;
I$8AAF:	LD	A,(D.FBE0)
	CP	0FEH
	JR	NZ,J.8AB9
;
	POP	AF
	OR	A
	RET	
;
;	-----------------
J.8AB9:	POP	AF
	SCF	
I$8ABB:	RET	
;
;	-----------------
J$8ABC:	 CALL	C.8AA7
;
	RET	NC
;
	JP	J.8894
;
;	-----------------
J$8AC3:	 CALL	C.8AA7
;
	RET	NC
;
	LD	HL,(D.D9E3)
	LD	DE,I.D130
	RST	20H
;
	EX	DE,HL
	LD	(D.D9E3),HL
	LD	(D.D9E5),HL
I$8AD5:	JP	Z,J.887F
;
	 CALL	C.90E8
;
	JP	J.887F
;
;	-----------------
J$8ADE:	 CALL	C.8AA7
;
	RET	NC
;
	LD	HL,(D.D9E7)
	LD	DE,(D.D9E5)
	RST	20H
;
	JP	Z,J.8894
;
I$8AED:	LD	DE,I.D130
	XOR	A
	SBC	HL,DE
	OR	H
	JR	NZ,J.8B1D
;
	SRL	L
	LD	A,(D.DA8F)
	OR	A
	LD	A,0BH	; 11 
	LD	BC,I$0207
	JR	Z,J$8B08
;
	LD	A,1AH
I$8B05:	LD	BC,I$0104
J$8B08:	CP	L
	JR	C,J.8B1D
;
	XOR	A
J$8B0C:	ADD	A,B
	DEC	L
	JR	NZ,J$8B0C
;
	ADD	A,C
	LD	(D.D9E0),A
	LD	HL,(D.D9E7)
	LD	(D.D9E5),HL
	JP	J.8891
;
;	-----------------
J.8B1D:	LD	A,(D.DA8F)
I$8B1F	EQU	$-1
	OR	A
	LD	DE,I.0016
	LD	A,1DH
	JR	Z,J$8B2C
;
	LD	E,34H	; "4"
	LD	A,1EH
J$8B2C:	LD	(D.D9E0),A
	LD	HL,(D.D9E7)
	LD	(D.D9E5),HL
	XOR	A
	SBC	HL,DE
	LD	(D.D9E3),HL
	 CALL	C.90E8
;
	JP	J.8891
;
;	-----------------
J$8B41:	 CALL	C.8AA7
;
	RET	NC
;
	LD	HL,(D.D9E7)
	LD	DE,(D.D9E5)
	RST	20H
;
	JP	Z,J.8894
;
	LD	A,(D.DA8F)
	OR	A
	LD	DE,I.2C02
	LD	HL,I.1215
	LD	BC,I.0E1D
	JR	Z,J$8B67
;
	LD	BC,I.081E
	LD	H,0AH	; 10 
	LD	DE,I.3401
J$8B67:	LD	A,(D.D9E0)
	CP	C
	JR	Z,J$8B7C
;
	ADD	A,E
	LD	(D.D9E0),A
I.8B6F	EQU	$-2
	LD	HL,(D.D9E5)
	INC	HL
I.8B75:	INC	HL
	LD	(D.D9E5),HL
	JP	J.8891
I$8B7B	EQU	$-1
;
;	-----------------
J$8B7C:	LD	E,02H	; 2 
	PUSH	BC
	LD	C,L
	 CALL	C.8637
;
	LD	HL,(D.D9E5)
	INC	HL
	INC	HL
	LD	(D.D9E5),HL
	LD	HL,(D.D9E3)
	INC	HL
I$8B8F:	INC	HL
	LD	(D.D9E3),HL
	LD	HL,(D.D9E5)
	LD	DE,(D.D9E7)
	RST	20H
;
I$8B9B:	LD	DE,I.0061
	JR	Z,J$8BA3
;
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
J$8BA3:	POP	BC
	RLC	C
	LD	H,C
	LD	L,15H
	 CALL	C.7B13
;
	JP	J.8894
;
;	-----------------
J$8BAF:	 CALL	C.8AA7
;
	RET	NC
;
	LD	HL,(D.D9E5)
	LD	DE,I.D130
	RST	20H
;
	JP	Z,J.8894
I$8BBB	EQU	$-2
;
	LD	HL,(D.D9E3)
	RST	20H
;
	JR	NZ,J.8BDF
;
J$8BC3:	LD	A,(D.DA8F)
	OR	A
	LD	E,02H	; 2 
	JR	Z,J.8BCD
;
	LD	E,01H	; 1 
J.8BCD:	LD	A,(D.D9E0)
	SUB	E
	LD	(D.D9E0),A
	LD	HL,(D.D9E5)
	DEC	HL
	DEC	HL
	LD	(D.D9E5),HL
	JP	J.8891
;
;	-----------------
J.8BDF:	LD	A,(D.DA8F)
	OR	A
	LD	HL,I$3A0E
	LD	BC,I.3E17
	LD	DE,I$2C0D
	JR	Z,J$8BF4
;
	LD	HL,I$3C08
I$8BF1:	LD	DE,I$340A
J$8BF4:	LD	A,(D.D9E0)
	CP	E
	JR	NZ,J$8BC3
;
	PUSH	HL
	LD	L,C
	LD	E,02H	; 2 
	 CALL	C.866A
;
	LD	HL,(D.D9E5)
I$8C03	EQU	$-1
	DEC	HL
	DEC	HL
	LD	(D.D9E5),HL
	LD	HL,(D.D9E3)
	DEC	HL
	LD	D,(HL)
	DEC	HL
I$8C0F:	LD	E,(HL)
	LD	(D.D9E3),HL
	POP	HL
	LD	H,L
	LD	L,15H
	 CALL	C.7B13
;
	JP	J.8894
I$8C1B	EQU	$-2
;
;	-----------------
J.8C1D:	LD	HL,(D.D9E7)
	LD	DE,(D.D9E5)
	RST	20H
;
	JP	Z,J.8891
I$8C27	EQU	$-1
;
	PUSH	HL
	PUSH	DE
	OR	A
	SBC	HL,DE
	DEC	HL
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,J$8C4A
;
	POP	DE
	POP	HL
	DEC	HL
	DEC	HL
	LD	(D.D9E7),HL
	LD	A,(D.D9E0)
	LD	DE,I.0061
J$8C40:	RLCA	
	LD	H,A
	LD	L,15H
	 CALL	C.7B13
;
	JP	J.8891
;
;	-----------------
J$8C4A:	LD	B,H
	LD	C,L
	POP	DE
	LD	H,D
	LD	L,E
	INC	HL
	INC	HL
	LDIR	
	POP	HL
	DEC	HL
	DEC	HL
	LD	(D.D9E7),HL
	LD	A,(D.DA8F)
	OR	A
	LD	DE,I$041D
I$8C5F	EQU	$-1
	JR	Z,J$8C65
;
	LD	DE,I$021E
J$8C65:	LD	A,(D.D9E0)
	CP	E
	JR	NZ,J$8C73
;
	LD	HL,(D.D9E5)
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	JR	J$8C40
;
;	-----------------
J$8C73:	RLCA	
	LD	B,A
	LD	A,E
	RLCA	
	SUB	B
	PUSH	DE
	LD	D,A
	LD	E,02H	; 2 
	LD	C,15H
	LD	L,C
	POP	AF
	PUSH	AF
	ADD	A,B
	LD	H,A
	 CALL	C.8637
;
	POP	DE
	RLC	E
	LD	B,E
	LD	A,(D.D9E0)
	RLCA	
	LD	C,A
	LD	A,E
	SUB	C
	ADD	A,D
	LD	D,A
	LD	A,(D.DA8F)
	OR	A
	LD	A,D
	JR	NZ,J$8C9B
;
	RRCA	
J$8C9B:	SUB	02H	; 2 
	LD	HL,(D.D9E5)
	 CALL	C.7CEF
;
	LD	DE,(D.D9E7)
	RST	20H
;
	LD	DE,I.0061
	JR	NC,J$8CB0
;
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
J$8CB0:	LD	H,B
	LD	L,15H
	 CALL	C.7B13
;
	JP	J.8891
;
;	-----------------
J$8CB9:	LD	HL,(D.D9E5)
	LD	DE,I.D130
	RST	20H
;
	JP	Z,J.8C1D
;
	LD	HL,(D.D9E3)
	RST	20H
;
	JR	NZ,J$8CE5
;
J$8CC9:	LD	HL,(D.D9E5)
	DEC	HL
	DEC	HL
	LD	(D.D9E5),HL
	LD	A,(D.DA8F)
	OR	A
	LD	E,02H	; 2 
	JR	Z,J$8CDB
;
	LD	E,01H	; 1 
J$8CDB:	LD	A,(D.D9E0)
	SUB	E
	LD	(D.D9E0),A
	JP	J.8C1D
;
;	-----------------
J$8CE5:	LD	A,(D.DA8F)
	OR	A
	LD	E,0DH	; 13 
	JR	Z,J$8CEF
;
	LD	E,0AH	; 10 
J$8CEF:	LD	A,(D.D9E0)
	CP	E
	JR	NZ,J$8CC9
;
	LD	A,(D.DA8F)
	OR	A
	LD	HL,I$160E
	LD	DE,I.0802
	LD	BC,I$1A07
	JR	Z,J$8D0C
;
	LD	HL,I$1208
	LD	BC,I$140D
	LD	D,0AH	; 10 
J$8D0C:	PUSH	HL
	PUSH	BC
	LD	L,17H
	LD	C,L
	 CALL	C.866A
;
	POP	BC
	LD	HL,(D.D9E5)
	LD	A,C
	 CALL	C$7D04
;
	LD	D,(HL)
	DEC	HL
	LD	E,(HL)
	POP	HL
	LD	H,L
	LD	L,15H
	 CALL	C.7B13
;
	LD	HL,(D.D9E3)
	DEC	HL
	DEC	HL
	LD	(D.D9E3),HL
	LD	HL,(D.D9E5)
	PUSH	HL
	DEC	HL
	DEC	HL
	LD	(D.D9E5),HL
	LD	HL,(D.D9E7)
	PUSH	HL
	DEC	HL
	DEC	HL
	LD	(D.D9E7),HL
	POP	HL
	POP	DE
	XOR	A
	SBC	HL,DE
	JP	Z,J.8894
;
	LD	B,H
	LD	C,L
	LD	H,D
	LD	L,E
	DEC	DE
	DEC	DE
	LDIR	
	JP	J.8894
;
;	-----------------
J$8D53:	LD	A,(D.D91C)
	CP	0F3H
	JP	NC,J.88B5
;
	LD	HL,(D.D9E5)
	LD	DE,I.D130
	XOR	A
	SBC	HL,DE
	JP	Z,J.8894
;
	CP	H
	JR	NZ,J$8D77
;
	LD	A,(D.DA8F)
	OR	A
	LD	A,17H
	JR	Z,J$8D74
;
	LD	A,35H	; "5"
J$8D74:	CP	L
	JR	NC,J$8DAE
;
J$8D77:	 CALL	C.7A37
;
	 CALL	C.8823
;
	LD	HL,I.0415
	LD	BC,I$8A9F
	 CALL	C.7C44
;
J$8D86:	 CALL	C.74D0
;
	JP	C,J.895A
;
	CP	0DH	; 13 
	JR	NZ,J$8D86
;
	 CALL	C.7A37
;
	LD	A,(D.D91C)
	LD	BC,J.8A6B
	CP	0F1H
	JR	C,J.8DA5
;
	LD	BC,I.8A73
	JR	Z,J.8DA5
;
	LD	BC,I.8A7B
J.8DA5:	LD	HL,I.0215
	 CALL	C.7C3E
;
	 CALL	C.90E8
;
J$8DAE:	LD	HL,(D.D9E5)
	LD	DE,I.D130
	OR	A
	SBC	HL,DE
	LD	B,H
	LD	C,L
	EX	DE,HL
J$8DBA:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	XOR	A
	RET	
;
;	-----------------
?.8DC0:	DEC	BC
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$8DBA
;
J$8DC6:	LD	HL,(D.D9E7)
	LD	DE,(D.D9E5)
	RST	20H
;
	JR	NZ,J$8DEF
;
	LD	HL,I.D130
	LD	(D.D9E7),HL
J$8DD6:	LD	(D.D9E5),HL
	LD	(D.D9E3),HL
	LD	A,(D.DA8F)
	OR	A
	LD	A,07H	; 7 
	JR	Z,J$8DE6
;
	LD	A,04H	; 4 
J$8DE6:	LD	(D.D9E0),A
	 CALL	C.90E8
;
	JP	J.8891
;
;	-----------------
J$8DEF:	OR	A
	SBC	HL,DE
	LD	B,H
	LD	C,L
	EX	DE,HL
	LD	DE,I.D130
	LDIR	
	LD	HL,(D.D9E5)
	LD	DE,I.D130
	SBC	HL,DE
	LD	B,H
	LD	C,L
	LD	HL,(D.D9E7)
	OR	A
	SBC	HL,BC
	LD	(D.D9E7),HL
	LD	HL,I.D130
	JR	J$8DD6
;
;	-----------------
J$8E12:	LD	HL,(D.D9E5)
	LD	DE,I.D130
	XOR	A
	SBC	HL,DE
	OR	H
	JP	NZ,J.895A
;
	LD	A,1EH
	CP	L
	JP	C,J.895A
;
	LD	A,(D.D91C)
	CP	0F1H
	JP	NZ,J$8EFB
;
	 CALL	C.8F52
;
	JP	C,J.895A
;
	JP	J$9158
;
;	-----------------
J.8E36:	JP	J$8F90
;
;	-----------------
J.8E39:	JP	C,J.895A
;
	JP	Z,J$8EEC
;
	JP	J$A43B
;
;	-----------------
J.8E42:	XOR	A
	 CALL	C.7CC2
;
	CP	0FFH
	JP	Z,J.895A
;
	 CALL	C.7A37
;
	LD	A,(D.D9E0)
	LD	(D.DA3B),A
J$8E54:	LD	A,01H	; 1 
	LD	(D.D9E0),A
	XOR	A
	LD	(D.DA3C),A
	LD	IX,I.D110
	LD	HL,I.0215
	LD	B,0AH	; 10 
J$8E66:	LD	D,(IX+1)
	LD	E,(IX)
	 CALL	C.7B13
;
	INC	IX
	INC	IX
	INC	H
	INC	H
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$8E7D
;
	INC	H
	INC	H
J$8E7D:	DJNZ	J$8E66
;
J.8E7F:	 CALL	C.8799
;
J.8E82:	 CALL	C.74D0
;
	JR	NC,J$8E90
;
	LD	A,(D.DA3B)
	LD	(D.D9E0),A
	JP	J.895A
;
;	-----------------
J$8E90:	CP	1CH
	JR	NZ,J$8EA7
;
	LD	A,(D.D9E0)
	CP	1CH
	JR	Z,J.8E82
;
	ADD	A,03H	; 3 
	LD	(D.D9E0),A
	LD	HL,D.DA3C
	INC	(HL)
	INC	(HL)
	JR	J.8E7F
;
;	-----------------
J$8EA7:	CP	1DH
	JR	NZ,J$8EBE
;
	LD	A,(D.D9E0)
	CP	01H	; 1 
	JR	Z,J.8E82
;
	SUB	03H	; 3 
	LD	(D.D9E0),A
	LD	HL,D.DA3C
	DEC	(HL)
	DEC	(HL)
	JR	J.8E7F
;
;	-----------------
J$8EBE:	CP	1EH
	JR	NZ,J$8ECA
;
	LD	A,01H	; 1 
J$8EC4:	 CALL	C.7CC2
;
	JP	J$8E54
;
;	-----------------
J$8ECA:	CP	1FH
	JR	NZ,J$8ED2
;
	LD	A,02H	; 2 
	JR	J$8EC4
;
;	-----------------
J$8ED2:	CP	0DH	; 13 
	JR	NZ,J.8E82
;
	LD	HL,I.D110
	LD	A,(D.DA3C)
	 CALL	C.7CEF
;
	LD	E,(HL)
	INC	HL
	LD	A,(HL)
	LD	D,A
	OR	E
	JP	Z,J.8E82
;
	LD	A,(D.D91C)
	OR	A
	RET	
;
;	-----------------
J$8EEC:	 CALL	C.7A37
;
	LD	BC,I.8A73
J.8EF2:	LD	HL,I.0215
	 CALL	C.7C3E
;
	JP	J$8DC6
;
;	-----------------
J$8EFB:	CP	0F2H
	JP	NZ,J$8F32
;
	 CALL	C.8F52
;
	JP	C,J.895A
;
	XOR	A
	 CALL	C.7C62
;
	JP	C,J.895A
;
	 CALL	C.911F
;
	JP	C,J.895A
;
	LD	HL,I.D110
J$8F16:	LD	E,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	D,A
	OR	E
	JR	Z,J$8F22
;
	LD	A,0F2H
	OR	A
	RET	
;
;	-----------------
J$8F22:	LD	A,(D.D91C)
	CP	0F1H
	JP	Z,J$900B
;
	 CALL	C.7A37
;
	LD	BC,I.8A7B
	JR	J.8EF2
;
;	-----------------
J$8F32:	CP	0F0H
	JR	Z,J$8F4F
;
	LD	HL,(D.D9E5)
	LD	DE,(D.D9E7)
	RST	20H
;
	JP	NZ,J.8894
;
	LD	HL,I.D130
	RST	20H
;
	JP	Z,J.8894
;
	 CALL	C.8F52
;
	JP	C,J.8894
;
	RET	
;
;	-----------------
J$8F4F:	JP	J$A3BC
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8F52:	LD	BC,I.D0F0
	LD	HL,I.D130
J.8F58:	LD	DE,(D.D9E5)
	RST	20H
;
	JR	NZ,J$8F65
;
	XOR	A
	LD	(BC),A
	INC	BC
	XOR	A
	LD	(BC),A
	RET	
;
;	-----------------
J$8F65:	LD	E,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	CP	01H	; 1 
	JR	Z,J$8F73
;
	CP	02H	; 2 
	JR	Z,J$8F82
;
J.8F71:	SCF	
	RET	
;
;	-----------------
J$8F73:	LD	A,E
	CP	30H	; "0"
	JR	C,J.8F71
;
	CP	80H
	JR	C,J$8F7E
;
	JR	J$8F87
;
;	-----------------
J$8F7E:	LD	(BC),A
	INC	BC
	JR	J.8F58
;
;	-----------------
J$8F82:	LD	A,E
	CP	37H	; "7"
	JR	NC,J.8F71
;
J$8F87:	SUB	80H
	PUSH	HL
	 CALL	C$7C5C
;
	POP	HL
	JR	J.8F58
;
;	-----------------
J$8F90:	LD	HL,I$90C5
J$8F93:	LD	DE,I.D0F0
J$8F96:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J.8FA4
;
	INC	HL
	INC	DE
	OR	A
	JR	NZ,J$8F96
;
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	JP	(HL)
;
;	-----------------
J.8FA4:	XOR	A
	INC	HL
	CP	(HL)
	JR	NZ,J.8FA4
;
	INC	HL
	INC	HL
	INC	HL
	LD	A,0FFH
	CP	(HL)
	JR	NZ,J$8F93
;
	OR	A
	JP	J.8E39
;
;	-----------------
?.8FB5:	 CALL	C.900F
;
	 CALL	C.9047
;
	JR	J.8FD4
;
;	-----------------
?.8FBD:	 CALL	C.900F
;
	 CALL	C.9086
;
	JR	J.8FD4
;
;	-----------------
?.8FC5:	 CALL	C.900F
;
	 CALL	C.9086
;
	LD	(HL),61H	; "a"
	INC	HL
	LD	(HL),00H
	INC	HL
	 CALL	C.9047
;
J.8FD4:	 CALL	C.7A37
;
	 CALL	C.8823
;
	LD	HL,I.0215
	LD	IX,I.D110
	LD	B,0FH	; 15 
J$8FE3:	LD	E,(IX)
	INC	IX
	LD	D,(IX)
	INC	IX
	 CALL	C.7B13
;
	DJNZ	J$8FE3
;
J$8FF2:	 CALL	C.61DB
;
	 CALL	C.74D0
;
	JR	NC,J$9001
;
	 CALL	C.7A37
;
	SCF	
	JP	J.8E39
;
;	-----------------
J$9001:	CP	0DH	; 13 
	JR	NZ,J$8FF2
;
	LD	HL,I.D110
	JP	J$8F16
;
;	-----------------
J$900B:	XOR	A
	JP	J.8E39
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.900F:	LD	C,0DH	; 13 
	XOR	A
	LD	IX,I.01F9
	 CALL	C.015F
;
	LD	B,09H	; 9 
	LD	HL,I.CFC0
	LD	C,0AH	; 10 
J$9020:	LD	IX,I$01F5
	 CALL	C.015F
;
	LD	(HL),A
	INC	HL
	DEC	C
	DJNZ	J$9020
;
	LD	C,0DH	; 13 
	LD	A,08H	; 8 
	LD	IX,I.01F9
	 CALL	C.015F
;
	LD	HL,I.D110
	LD	(HL),00H
	LD	D,H
	LD	E,L
	INC	DE
	LD	C,1FH
	LDIR	
	LD	HL,I.D110
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9047:	LD	DE,I$CFC5
	LD	A,(DE)
	AND	03H	; 3 
	JR	Z,J$9056
;
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
J$9056:	INC	DE
	LD	A,(DE)
	AND	0FH	; 15 
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	LD	(HL),7EH	; "~"
	INC	HL
I$9064:	LD	(HL),08H	; 8 
	INC	HL
	INC	DE
	LD	A,(DE)
	AND	07H	; 7 
	JR	Z,J$9074
;
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
J$9074:	INC	DE
	LD	A,(DE)
	AND	0FH	; 15 
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	LD	(HL),0CCH
	INC	HL
	LD	(HL),0DH	; 13 
	INC	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9086:	LD	DE,I.CFC0
	LD	A,(DE)
	AND	01H	; 1 
	JR	Z,J$9095
;
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
J$9095:	INC	DE
	LD	A,(DE)
	AND	0FH	; 15 
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	LD	(HL),0EEH
	INC	HL
	LD	(HL),06H	; 6 
	INC	HL
	INC	DE
	LD	A,(DE)
	AND	03H	; 3 
	JR	Z,J$90B3
;
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
J$90B3:	INC	DE
	LD	A,(DE)
	AND	0FH	; 15 
	OR	30H	; "0"
	LD	(HL),A
	INC	HL
	LD	(HL),01H	; 1 
	INC	HL
	LD	(HL),9CH
	INC	HL
	LD	(HL),0CH	; 12 
	INC	HL
	RET	
;
;	-----------------
I$90C5:	CP	H
	SBC	A,0BAH
	CP	B
	NOP	
	OR	L
	ADC	A,A
	CP	H
	SBC	A,0B6H
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	NOP	
	OR	L
	ADC	A,A
	SET	0,D
	SBC	A,0B9H
	NOP	
	CP	L
	ADC	A,A
	SET	0,(HL)
	POP	BC
	NOP	
	CP	L
	ADC	A,A
	ADD	A,0C1H
	CP	H
	SBC	A,00H
	PUSH	BC
	ADC	A,A
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.90E8:	LD	A,(D.DA8F)
	OR	A
	LD	HL,I$0E15
	LD	B,0CH	; 12 
	JR	Z,J$90F7
;
	LD	H,08H	; 8 
	LD	B,1BH
J$90F7:	LD	IX,(D.D9E3)
J$90FB:	PUSH	HL
	PUSH	IX
	POP	DE
	LD	HL,(D.D9E7)
	RST	20H
;
	POP	HL
	JR	Z,J.9116
;
	LD	E,(IX)
	LD	D,(IX+1)
	 CALL	C.7B13
;
	INC	IX
	INC	IX
	DJNZ	J$90FB
;
	RET	
;
;	-----------------
J.9116:	LD	DE,I.0061
	 CALL	C.7B13
;
	DJNZ	J.9116
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.911F:	 CALL	C.7A37
;
	 CALL	C.8823
;
	LD	HL,I.0215
	LD	IX,I.D110
	LD	B,0FH	; 15 
J$912E:	LD	E,(IX)
	INC	IX
	LD	D,(IX)
	INC	IX
	 CALL	C.7B13
;
	DJNZ	J$912E
;
J$913D:	 CALL	C.61DB
;
	 CALL	C.74AE
;
	JR	NC,J$914A
;
	 CALL	C.7A37
;
	SCF	
	RET	
;
;	-----------------
J$914A:	CP	1FH
	JR	NZ,J$9153
;
	 CALL	C.7C62
;
	JR	C.911F
;
;	-----------------
J$9153:	CP	0DH	; 13 
	JR	NZ,J$913D
;
	RET	
;
;	-----------------
J$9158:	LD	HL,I.D0F0
	LD	A,(HL)
	AND	0DFH
	CP	4AH	; "J"
	JP	NZ,J.8E36
;
	INC	HL
	LD	A,(HL)
	AND	0DFH
	CP	48H	; "H"
	JP	NZ,J$91C2
;
	INC	HL
	 CALL	C.9244
;
	JP	C,J.8E36
;
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	D,A
	 CALL	C.9244
;
	JP	C,J.8E36
;
	ADD	A,D
	LD	D,A
	 CALL	C.9244
;
	JP	C,J.8E36
;
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	E,A
	 CALL	C.9244
;
	JP	C,J.8E36
;
	ADD	A,E
	LD	E,A
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,J.8E36
;
	EX	DE,HL
	LD	DE,I$FFC0
	RST	20H
;
	JR	NC,J$91BC
;
	LD	DE,I$7A60
	RST	20H
;
	JP	NC,J.8E36
;
	LD	DE,I$2120
	RST	20H
;
	JP	C,J.8E36
;
	LD	A,L
	CP	20H	; " "
	JP	C,J.8E36
;
	CP	80H
	JP	NC,J.8E36
;
	 CALL	C.A6FE
;
J$91BC:	EX	DE,HL
	LD	A,(D.D91C)
	OR	A
	RET	
;
;	-----------------
J$91C2:	 CALL	C.9244
;
	JP	C,J.8E36
;
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	D,A
	 CALL	C.9244
;
	JP	C,J.8E36
;
	ADD	A,D
	LD	D,A
	 CALL	C.9244
;
	JP	C,J.8E36
;
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	E,A
	 CALL	C.9244
;
	JP	C,J.8E36
;
	ADD	A,E
	LD	E,A
	INC	HL
	LD	A,(HL)
	OR	A
	JP	NZ,J.8E36
;
	EX	DE,HL
	LD	DE,I$9064
	RST	20H
;
	JP	NC,J.8E36
;
	LD	A,L
	CP	01H	; 1 
	JP	C,J.8E36
;
	CP	95H
	JP	NC,J.8E36
;
	LD	A,H
	CP	01H	; 1 
	JP	C,J.8E36
;
	CP	95H
	JP	NC,J.8E36
;
	 CALL	C.9224
;
	JP	C,J.8E36
;
	LD	H,A
	LD	A,L
	 CALL	C.9224
;
	JP	C,J.8E36
;
	LD	L,A
	 CALL	C.A6FE
;
	EX	DE,HL
	LD	A,(D.D91C)
	OR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9224:	LD	B,A
	AND	0FH	; 15 
	CP	0AH	; 10 
	JR	C,J$922D
;
	SCF	
	RET	
;
;	-----------------
J$922D:	LD	C,A
	XOR	A
	SRL	B
	SRL	B
	SRL	B
	SRL	B
	OR	B
	LD	A,00H
	JR	Z,J$9240
;
J$923C:	ADD	A,0AH	; 10 
	DJNZ	J$923C
;
J$9240:	ADD	A,C
	ADD	A,20H	; " "
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9244:	LD	A,(HL)
	INC	HL
	CP	30H	; "0"
	RET	C
;
	CP	3AH	; ":"
	JR	NC,J$9250
;
	AND	0FH	; 15 
	RET	
;
;	-----------------
J$9250:	OR	20H	; " "
	CP	61H	; "a"
	RET	C
;
	CP	67H	; "g"
	JR	C,J$925B
;
	SCF	
	RET	
;
;	-----------------
J$925B:	SUB	57H	; "W"
	RET	
;
;	-----------------
?.925E:	LD	A,(D.D923)
	OR	A
	RET	Z
;
	SCF	
	RET	
;
;	-----------------
?.9265:	LD	A,(D.D90D)
	LD	D,A
	LD	A,26H	; "&"
	CP	D
	RET	C
;
	LD	HL,D.D905
	LD	A,(D.DA8F)
	OR	A
	LD	A,0EH	; 14 
	JR	Z,J$927A
;
	LD	A,1DH
J$927A:	CP	(HL)
	JR	Z,J$92AE
;
	LD	(D.D907),A
	SUB	(HL)
	LD	D,A
	LD	HL,D.D90D
	PUSH	AF
	ADD	A,(HL)
	LD	(HL),A
	INC	HL
	LD	(HL),A
	LD	A,D
	ADD	A,A
	ADD	A,D
	LD	D,A
	LD	HL,(D.D909)
	 CALL	C.7CEF
;
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	A,(D.D907)
	LD	(D.D905),A
	POP	AF
J$92A1:	PUSH	AF
	 CALL	C.784F
;
	POP	AF
	DEC	A
	JR	NZ,J$92A1
;
	 CALL	C.871A
;
	SCF	
	RET	
;
;	-----------------
J$92AE:	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J.92BF
;
	LD	A,(D.D90D)
	CP	19H
	JR	NC,J.92BF
;
	LD	A,0FH	; 15 
	JR	J$92C5
;
;	-----------------
J.92BF:	LD	HL,D.D90D
	LD	A,27H	; "'"
	SUB	(HL)
J$92C5:	LD	D,A
	LD	HL,D.D90D
	PUSH	AF
	ADD	A,(HL)
	LD	(HL),A
	INC	HL
	LD	(HL),A
	LD	A,D
	ADD	A,A
	ADD	A,D
	LD	D,A
	LD	HL,(D.D909)
	 CALL	C.7CEF
;
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	HL,(D.D919)
	LD	A,D
	 CALL	C.7CEF
;
	LD	(D.D919),HL
	POP	AF
J$92E9:	PUSH	AF
	 CALL	C.784F
;
	POP	AF
	DEC	A
	JR	NZ,J$92E9
;
	OR	A
	RET	
;
;	-----------------
?.92F3:	LD	HL,D.D90D
	LD	A,(HL)
	LD	D,01H	; 1 
	CP	D
	RET	C
;
	LD	A,(D.D905)
	OR	A
	JR	Z,J$9331
;
	LD	D,A
	PUSH	AF
	XOR	A
	LD	(D.D905),A
	LD	(D.D907),A
	LD	A,(HL)
	SUB	D
	LD	(HL),A
	INC	HL
	LD	(HL),A
	LD	A,D
	ADD	A,A
	ADD	A,D
	LD	D,A
	LD	HL,(D.D909)
	LD	A,L
	SUB	D
	LD	L,A
	LD	A,H
	SBC	A,00H
	LD	H,A
	LD	(D.D909),HL
	LD	(D.D90B),HL
	POP	AF
J$9324:	PUSH	AF
	 CALL	C.7A03
;
	POP	AF
	DEC	A
	JR	NZ,J$9324
;
	 CALL	C.871A
;
	SCF	
	RET	
;
;	-----------------
J$9331:	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J.9340
;
	LD	A,(HL)
	CP	0FH	; 15 
	JR	C,J.9340
;
	LD	A,0FH	; 15 
	JR	J$9341
;
;	-----------------
J.9340:	LD	A,(HL)
J$9341:	LD	D,A
	PUSH	AF
	LD	A,(HL)
	SUB	D
	LD	(HL),A
	INC	HL
	LD	(HL),A
	LD	A,D
	ADD	A,A
	ADD	A,D
	LD	D,A
	LD	HL,(D.D909)
	LD	A,L
	SUB	D
	LD	L,A
	LD	A,H
	SBC	A,00H
	LD	H,A
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	HL,(D.D919)
	LD	A,L
	SUB	D
	LD	L,A
	LD	A,H
	SBC	A,00H
	LD	H,A
	LD	(D.D919),HL
	POP	AF
J$936A:	PUSH	AF
	 CALL	C.7A03
;
	POP	AF
	DEC	A
	JR	NZ,J$936A
;
	OR	A
	RET	
;
;	-----------------
?.9374:	LD	HL,(D.D909)
	LD	DE,I.8078
	RST	20H
;
	RET	C
;
	LD	A,(D.D906)
	OR	A
	JR	Z,J$93A6
;
	PUSH	AF
	LD	DE,I.0078
J$9386:	OR	A
	SBC	HL,DE
	DEC	A
	JR	NZ,J$9386
;
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	(D.D906),A
	LD	(D.D908),A
	POP	AF
J$9399:	PUSH	AF
	 CALL	C.75BB
;
	POP	AF
	DEC	A
	JR	NZ,J$9399
;
	 CALL	C.871A
;
	SCF	
	RET	
;
;	-----------------
J$93A6:	LD	DE,I$82CF
	RST	20H
;
	LD	A,06H	; 6 
	JR	NC,J$93BF
;
	XOR	A
	LD	DE,I.8078
	LD	BC,I.0078
	PUSH	AF
J$93B6:	POP	AF
	INC	A
	SBC	HL,BC
	PUSH	AF
	RST	20H
;
	JR	NC,J$93B6
;
	POP	AF
J$93BF:	LD	HL,(D.D909)
	PUSH	AF
	LD	DE,I.0078
J$93C6:	OR	A
	SBC	HL,DE
	DEC	A
	JR	NZ,J$93C6
;
	LD	(D.D909),HL
	LD	(D.D90B),HL
	POP	AF
	PUSH	AF
	LD	HL,(D.D919)
J$93D7:	OR	A
	SBC	HL,DE
	DEC	A
	JR	NZ,J$93D7
;
	LD	(D.D919),HL
	POP	AF
J$93E1:	PUSH	AF
	 CALL	C.75BB
;
	POP	AF
	DEC	A
	JR	NZ,J$93E1
;
	 CALL	C.871A
;
	OR	A
	RET	
;
;	-----------------
?.93EE:	LD	DE,(D.D909)
	LD	HL,I$CEBF
	RST	20H
;
	RET	C
;
	LD	A,(D.D906)
	CP	05H	; 5 
	JR	Z,J$9427
;
	LD	H,A
	LD	A,05H	; 5 
	SUB	H
	EX	DE,HL
	LD	DE,I.0078
	LD	B,A
	PUSH	AF
J$9408:	ADD	HL,DE
	DJNZ	J$9408
;
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	A,05H	; 5 
	LD	(D.D906),A
	LD	(D.D908),A
	POP	AF
J$941A:	PUSH	AF
	 CALL	C.7663
;
	POP	AF
	DEC	A
	JR	NZ,J$941A
;
	 CALL	C.871A
;
	SCF	
	RET	
;
;	-----------------
J$9427:	LD	HL,I$CC67
	RST	20H
;
	LD	A,06H	; 6 
	JR	NC,J$9443
;
	LD	HL,(D.D909)
	LD	DE,I.CF38
	LD	BC,I.0078
	XOR	A
	PUSH	AF
J$943A:	POP	AF
	ADD	HL,BC
	INC	A
	PUSH	AF
	RST	20H
;
	JR	C,J$943A
;
	POP	AF
	DEC	A
J$9443:	LD	HL,(D.D909)
	LD	DE,I.0078
	LD	B,A
J$944A:	ADD	HL,DE
	DJNZ	J$944A
;
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	B,A
	LD	HL,(D.D919)
J$9457:	ADD	HL,DE
	DJNZ	J$9457
;
	LD	(D.D919),HL
J$945D:	PUSH	AF
	 CALL	C.7663
;
	POP	AF
	DEC	A
	JR	NZ,J$945D
;
	 CALL	C.871A
;
	OR	A
	RET	
;
;	-----------------
?.946A:	LD	HL,I.F800
	 CALL	C.882B
;
	LD	B,20H	; " "
	LD	A,(D.D923)
	OR	A
	LD	A,27H	; "'"
	JR	Z,J.947C
;
	LD	A,2DH	; "-"
J.947C:	OUT	(98H),A
	PUSH	IX
	POP	IX
	DJNZ	J.947C
;
	RET	
;
;	-----------------
?.9485:	LD	A,(D.D905)
	LD	D,A
	LD	A,(D.D90D)
	CP	D
	PUSH	AF
	LD	B,A
	ADD	A,A
	ADD	A,B
	LD	B,A
	LD	HL,(D.D909)
	LD	A,L
	SUB	B
	LD	L,A
	LD	A,H
	SBC	A,00H
	LD	H,A
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	A,(D.D90D)
	SUB	D
	LD	D,A
	ADD	A,A
	ADD	A,D
	LD	D,A
	LD	HL,(D.D919)
	LD	A,L
	SUB	D
	LD	L,A
	LD	A,H
	SBC	A,00H
	LD	H,A
	LD	(D.D919),HL
	XOR	A
	LD	(D.D905),A
	LD	(D.D907),A
	LD	(D.D90D),A
	LD	(D.D90E),A
	INC	A
	LD	HL,I$D9C8
	LD	(HL),A
	LD	A,1AH
	DEC	HL
	LD	(HL),A
	LD	A,02H	; 2 
	LD	DE,I$3613
	 CALL	C$828F
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.94D7:	XOR	A
	LD	(D.D905),A
	LD	(D.D907),A
	LD	(D.D906),A
	LD	(D.D908),A
	LD	(D.D90D),A
	LD	(D.D90E),A
	LD	HL,I.8000
	LD	(D.D909),HL
	LD	(D.D90B),HL
	LD	(D.D919),HL
	LD	HL,I$D9C2
	LD	(HL),1AH
	INC	HL
	LD	(HL),00H
	INC	HL
	LD	(HL),01H	; 1 
	LD	HL,I$D9C7
	LD	(HL),1AH
	INC	HL
	LD	(HL),01H	; 1 
	 CALL	C$87DB
;
	RET	
;
;	-----------------
?.950D:	 CALL	C.7A37
;
	LD	A,0F3H
	LD	(D.D91C),A
	LD	BC,I.86B1
	 CALL	C.885F
;
	LD	HL,(D.D909)
	LD	DE,(D.D90B)
	INC	DE
	INC	DE
	INC	DE
	XOR	A
	PUSH	AF
	LD	BC,I.D110
J$952A:	PUSH	DE
	PUSH	BC
	INC	HL
	LD	A,83H
	 CALL	C.000C
;
	POP	BC
	LD	(BC),A
	INC	HL
	INC	BC
	PUSH	BC
	LD	A,83H
	 CALL	C.000C
;
	POP	BC
	LD	(BC),A
	INC	HL
	INC	BC
	POP	DE
	POP	AF
	INC	A
	PUSH	AF
	RST	20H
;
	JR	NZ,J$952A
;
	LD	HL,I.D110
	LD	DE,I.D0F0
	POP	AF
	 CALL	C$7C56
;
	JR	NC,J$9555
;
	OR	A
	RET	
;
;	-----------------
J$9555:	 CALL	C.61D3
;
	 CALL	C.8823
;
	 CALL	C.7A37
;
	LD	HL,I.0215
	LD	BC,I$8729
	 CALL	C.7C3E
;
	 CALL	C.74D0
;
	SCF	
	RET	
;
;	-----------------
?.956C:	 CALL	C.7A37
;
	LD	A,0F4H
	LD	(D.D91C),A
	LD	BC,I.86B1
	 CALL	C.885F
;
	RET	
;
;	-----------------
?.957B:	 CALL	C.7A37
;
	 CALL	C.8823
;
	LD	HL,I.0215
	LD	BC,I$871F
	 CALL	C.7C3E
;
	 CALL	C.61DB
;
	 CALL	C.74AE
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9591:	LD	A,3CH	; "<"
	LD	(D.FFFF),A
	LD	A,0FFH
	OUT	(0A8H),A
	LD	HL,I.1D00
	LD	DE,I.D0D0
	LD	BC,I.0800
	LDIR	
	LD	A,0FCH
	OUT	(0A8H),A
	RET	
;
;	-----------------
?.95AA:	LD	A,3CH	; "<"
	LD	(D.FFFF),A
	LD	A,0FFH
	OUT	(0A8H),A
	LD	DE,I.1D00
	LD	HL,I.D0D0
	LD	BC,I.0800
	LDIR	
	LD	A,0FCH
	OUT	(0A8H),A
	RET	
;
;	-----------------
?.95C3:	 CALL	C$9591
;
J$95C6:	LD	HL,I.D0D0
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,D
	OR	E
	JR	NZ,J.95D3
;
	SCF	
	RET	
;
;	-----------------
J.95D3:	PUSH	HL
	PUSH	HL
	POP	IX
	PUSH	DE
	PUSH	DE
	 CALL	C.7A37
;
	POP	HL
	LD	BC,I.0215
J$95E0:	LD	A,(IX)
	LD	E,(IX+1)
	LD	D,(IX+2)
	INC	IX
	INC	IX
	INC	IX
	PUSH	HL
	LD	H,B
	LD	L,C
	 CALL	C.7AE5
;
	LD	B,H
	LD	C,L
	POP	HL
	LD	A,B
	CP	3EH	; ">"
	JR	Z,J$9604
;
	DEC	HL
	DEC	HL
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,J$95E0
;
J$9604:	POP	DE
	POP	HL
J$9606:	PUSH	HL
	EI	
	 CALL	C.61DB
;
	 CALL	C.74D0
;
	POP	HL
	RET	C
;
	CP	1FH
	JR	NZ,J$961F
;
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,D
	OR	E
	JR	Z,J$95C6
;
	JR	J.95D3
;
;	-----------------
J$961F:	CP	0DH	; 13 
	RET	Z
;
	JR	J$9606
;
;	-----------------
J.9624:	 CALL	C$7BEA
;
	RET	C
;
	DEC	A
	JR	NZ,J$9630
;
	 CALL	C$7C74
;
	JR	J.9624
;
;	-----------------
J$9630:	DEC	A
	JR	Z,J$9635
;
	JR	J$9669
;
;	-----------------
J$9635:	 CALL	C.7C14
;
	JR	C,J.9624
;
	LD	BC,I.8B6F
	 CALL	C.71AB
;
	LD	A,0F0H
	LD	(D.F86C),A
	OR	A
	 CALL	C.6291
;
	JR	C,J.9624
;
	LD	HL,I.D0D0
	PUSH	HL
	LD	DE,I.0800
	OR	A
	 CALL	C.6328
;
	POP	HL
	JR	C,J.9624
;
	LD	DE,I.7800
J$965C:	LD	A,(HL)
	 CALL	C.7CE0
;
	INC	HL
	INC	DE
	LD	A,D
	CP	80H
	JR	NZ,J$965C
;
	JR	J.9624
;
;	-----------------
J$9669:	 CALL	C.7C14
;
	JR	C,J.9624
;
	LD	BC,I.8B75
	 CALL	C.71AB
;
	LD	A,0F0H
	LD	(D.F86C),A
	OR	A
	 CALL	C.635B
;
	JP	C,J.9624
;
	LD	HL,I.7800
	LD	DE,I.D0D0
	PUSH	DE
J$9687:	 CALL	C.7CD6
;
	LD	(DE),A
	INC	HL
	INC	DE
	LD	A,H
	CP	80H
	JR	NZ,J$9687
;
	POP	HL
	LD	DE,I.0800
	OR	A
	 CALL	C.637B
;
	JR	J.9624
;
;	-----------------
?.969C:	 CALL	C.7C14
;
	RET	C
;
	LD	BC,I.8B6F
	 CALL	C.71AB
;
	LD	A,0FFH
	LD	(D.F86C),A
	OR	A
	 CALL	C.6291
;
	RET	C
;
	LD	A,(D$F878)
	DEC	A
	CP	0AH	; 10 
	RET	NC
;
	INC	A
	LD	DE,I.2800
J$96BB:	PUSH	AF
	PUSH	DE
	LD	HL,I.D0D0
	LD	DE,I.0800
	OR	A
	 CALL	C.6328
;
	JR	NC,J$96DA
;
	POP	DE
J$96CA:	POP	AF
	LD	HL,I.2800
	LD	(D.DA67),HL
	LD	A,0FFH
	LD	DE,I.2800
	 CALL	C.7CE0
;
	RET	
;
;	-----------------
J$96DA:	POP	DE
	LD	A,D
	CP	78H	; "x"
	JR	Z,J$96CA
;
	LD	HL,I.D0D0
J.96E3:	LD	A,(HL)
	 CALL	C.7CE0
;
	INC	DE
	INC	HL
	LD	A,H
	CP	0D8H
	JR	NZ,J.96E3
;
	LD	A,L
	CP	0D0H
	JR	NZ,J.96E3
;
	POP	AF
	DEC	A
	JR	NZ,J$96BB
;
	LD	HL,(D$F879)
	LD	DE,I.2800
	ADD	HL,DE
	LD	(D.DA67),HL
	RET	
;
;	-----------------
?.9702:	LD	HL,(D.DA67)
	LD	DE,I.2800
	RST	20H
;
	RET	Z
;
	 CALL	C.7C14
;
	RET	C
;
	LD	BC,I.8B75
	 CALL	C.71AB
;
	LD	A,0FFH
	LD	(D.F86C),A
	LD	HL,(D.DA67)
	LD	DE,I.2800
	OR	A
	SBC	HL,DE
	LD	(D$F86E),HL
	SRA	H
	SRA	H
	SRA	H
	INC	H
	LD	A,H
	LD	(D.F86D),A
	OR	A
	PUSH	AF
	 CALL	C.635B
;
	JR	NC,J$9739
;
J.9737:	POP	AF
	RET	
;
;	-----------------
J$9739:	LD	HL,I.2800
J$973C:	LD	DE,I.D0D0
J.973F:	 CALL	C.7CD6
;
	LD	(DE),A
	INC	HL
	INC	DE
	LD	A,D
	CP	0D8H
	JR	NZ,J.973F
;
	LD	A,E
	CP	0D0H
	JR	NZ,J.973F
;
	PUSH	HL
	LD	HL,I.D0D0
	LD	DE,I.0800
	OR	A
	 CALL	C.637B
;
	POP	HL
	JR	C,J.9737
;
	POP	AF
	DEC	A
	JR	Z,J.9737
;
	PUSH	AF
	JR	J$973C
;
;	-----------------
J.9764:	 CALL	C.807F
;
	LD	HL,I.0200
	LD	DE,I.1802
	LD	A,60H	; "`"
	 CALL	C.80BE
;
	LD	HL,I.0400
	LD	BC,I$8AAF
	 CALL	C.7C44
;
	LD	HL,I.0016
	LD	DE,I.4002
	LD	A,0D0H
	 CALL	C.80BE
;
	LD	HL,I.0216
	LD	BC,I$8B1F
	 CALL	C.7C44
;
	LD	HL,I$0002
	LD	DE,I$4010
	LD	A,0C0H
	 CALL	C.80BE
;
	LD	HL,I.0203
	LD	BC,I$8ABB
	 CALL	C.7C44
;
	LD	HL,I$0206
	LD	BC,I$87C7
	 CALL	C.7C44
;
	LD	HL,I$0209
	LD	BC,I$87E9
	 CALL	C.7C44
;
	LD	HL,I$020C
	LD	BC,I$8AD5
	 CALL	C.7C44
;
	LD	HL,I$020F
	LD	BC,I$8AED
	 CALL	C.7C44
;
	LD	HL,I.0012
	LD	DE,I$4004
	LD	A,40H	; "@"
	 CALL	C.80BE
;
	LD	HL,I$0213
	LD	BC,I$8B05
	 CALL	C.7C44
;
	LD	H,04H	; 4 
	LD	A,(D.DA8F)
	OR	A
	LD	L,01H	; 1 
	JR	Z,J$97E7
;
	LD	L,08H	; 8 
J$97E7:	LD	(D.D9E0),HL
	 CALL	C$9A8F
;
	LD	A,44H	; "D"
	LD	(D.DAD9),A
	LD	BC,D.DB04
	LD	HL,I$2613
	 CALL	C.9A78
;
	LD	A,0CCH
	LD	(D.DAD9),A
J.9800:	LD	HL,I.1206
	LD	DE,I.1802
	LD	A,0C0H
	 CALL	C.80BE
;
	LD	A,(D.DA8F)
	OR	A
	LD	BC,I.1206
	JR	Z,J$9816
;
	LD	B,18H
J$9816:	LD	HL,I$DA9F
J$9819:	LD	A,(HL)
	CP	0FFH
	JR	Z,J.982D
;
	LD	E,A
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	HL
	PUSH	BC
	POP	HL
	 CALL	C$8368
;
	LD	B,H
	LD	C,L
	POP	HL
	JR	J$9819
;
;	-----------------
J.982D:	LD	BC,I$DAAF
	LD	HL,I$2E06
	 CALL	C.9A58
;
	 CALL	C.9AA8
;
J.9839:	LD	BC,D.DA90
	LD	HL,I$220C
	 CALL	C.9A58
;
	LD	BC,D.DA92
	LD	HL,I$220F
	 CALL	C.9A58
;
	LD	A,44H	; "D"
	LD	(D.DAD9),A
	LD	BC,D.DB03
	LD	HL,I$1E13
	 CALL	C.9A78
;
	LD	A,0CCH
	LD	(D.DAD9),A
J.985E:	 CALL	C.8799
;
	 CALL	C.61DB
;
	 CALL	C.74AE
;
	JR	NC,J$986D
;
	 CALL	C.8823
;
	RET	
;
;	-----------------
J$986D:	CP	1EH
	JR	NZ,J$9884
;
	LD	A,(D.D9E1)
	CP	04H	; 4 
	JR	Z,J.985E
;
	SUB	03H	; 3 
	CP	11H	; 17 
	JR	NZ,J$987F
;
	DEC	A
J$987F:	LD	(D.D9E1),A
	JR	J.985E
;
;	-----------------
J$9884:	CP	1FH
	JR	NZ,J$989B
;
	LD	A,(D.D9E1)
	CP	14H	; 20 
	JR	Z,J.985E
;
	ADD	A,03H	; 3 
	CP	13H	; 19 
	JR	NZ,J$9896
;
	INC	A
J$9896:	LD	(D.D9E1),A
	JR	J.985E
;
;	-----------------
J$989B:	CP	1CH
	JR	NZ,J$9908
;
	LD	A,(D.D9E1)
	CP	04H	; 4 
	JR	NZ,J$98B1
;
	 CALL	C.94D7
;
	LD	A,0FFH
	LD	(D.DA8F),A
	JP	J.9764
;
;	-----------------
J$98B1:	CP	0AH	; 10 
	JR	NZ,J$98E1
;
	LD	A,(D.DA94)
	CP	0FFH
	JP	Z,J.985E
;
	OR	A
	LD	A,(D.DA98)
	JR	NZ,J$98D8
;
	BIT	1,A
	JP	Z,J.985E
;
	LD	A,01H	; 1 
J.98CA:	PUSH	AF
	 CALL	C.9AA8
;
	POP	AF
	LD	(D.DA94),A
	 CALL	C$7BC6
;
	JP	J.982D
;
;	-----------------
J$98D8:	BIT	2,A
	JP	Z,J.985E
;
	LD	A,0FFH
	JR	J.98CA
;
;	-----------------
J$98E1:	CP	07H	; 7 
	JP	NZ,J.985E
;
	LD	A,(D.DAC6)
	OR	A
	LD	A,(D.DA6A)
	JR	NZ,J$98F6
;
	CP	03H	; 3 
	JP	Z,J.985E
;
	JR	J$98FB
;
;	-----------------
J$98F6:	CP	19H
	JP	Z,J.985E
;
J$98FB:	INC	A
	LD	(D.DA6A),A
	 CALL	C.9AA8
;
	 CALL	C.7BCC
;
	JP	J.9800
;
;	-----------------
J$9908:	CP	1DH
	JR	NZ,J$995A
;
	LD	A,(D.D9E1)
	CP	04H	; 4 
	JR	NZ,J$991D
;
	 CALL	C.94D7
;
	XOR	A
	LD	(D.DA8F),A
	JP	J.9764
;
;	-----------------
J$991D:	CP	0AH	; 10 
	JR	NZ,J$9941
;
	LD	A,(D.DA94)
	OR	A
	JP	Z,J.985E
;
	CP	01H	; 1 
	LD	A,(D.DA98)
	JR	NZ,J$9937
;
	BIT	0,A
	JP	Z,J.985E
;
	XOR	A
	JR	J$993E
;
;	-----------------
J$9937:	BIT	1,A
	JP	Z,J.985E
;
	LD	A,01H	; 1 
J$993E:	JP	J.98CA
;
;	-----------------
J$9941:	CP	07H	; 7 
	JP	NZ,J.985E
;
	LD	A,(D.DA6A)
	OR	A
	JP	Z,J.985E
;
	DEC	A
J$994E:	LD	(D.DA6A),A
	 CALL	C.9AA8
;
	 CALL	C.7BCC
;
	JP	J.9800
;
;	-----------------
J$995A:	CP	0BH	; 11 
	JR	NZ,J$9978
;
	LD	A,(D.FBE0)
	CP	0FCH
	JP	NZ,J.985E
;
	LD	A,(D.D9E1)
	CP	07H	; 7 
	JP	NZ,J.985E
;
	LD	A,(D.DAC6)
	CPL	
	LD	(D.DAC6),A
	XOR	A
	JR	J$994E
;
;	-----------------
J$9978:	CP	0DH	; 13 
	JP	Z,J$99D4
;
	CP	30H	; "0"
	JP	C,J.985E
;
	CP	3AH	; ":"
	JP	NC,J.985E
;
	LD	B,A
	LD	A,(D.D9E1)
	CP	0DH	; 13 
	JR	NZ,J$99A4
;
	LD	A,(D.FFA7)
	CP	0C9H
	JP	Z,J.985E
;
	LD	A,(D.DA91)
	LD	(D.DA90),A
	LD	A,B
	LD	(D.DA91),A
	JP	J.9839
;
;	-----------------
J$99A4:	CP	10H	; 16 
	JR	NZ,J$99BD
;
	LD	A,(D.FFA7)
	CP	0C9H
	JP	Z,J.985E
;
	LD	A,(D.DA93)
	LD	(D.DA92),A
	LD	A,B
	LD	(D.DA93),A
	JP	J.9839
;
;	-----------------
J$99BD:	CP	14H	; 20 
	JP	NZ,J.985E
;
	LD	A,(D.DB04)
	OR	30H	; "0"
	CP	B
	JP	C,J.985E
;
	LD	A,B
	AND	0FH	; 15 
	LD	(D.DB03),A
	JP	J.9839
;
;	-----------------
J$99D4:	LD	A,(D.D9E1)
	CP	14H	; 20 
	JR	Z,J$99FA
;
	LD	A,(D.FFA7)
	CP	0C9H
	RET	Z
;
	LD	BC,I.8B75
	 CALL	C.71AB
;
	LD	HL,D.DA6A
	LD	DE,I.D0D0
	LD	BC,FCB1.1
	LDIR	
	 CALL	C$A326
;
	OR	A
	 CALL	NZ,C.9CE1
;
	RET	
;
;	-----------------
J$99FA:	LD	A,(D.DB03)
	LD	B,A
	LD	HL,I.0001
	OR	A
	JR	Z,J$9A0A
;
	RLCA	
	ADD	A,02H	; 2 
	LD	H,A
	INC	A
	LD	L,A
J$9A0A:	LD	A,H
	OUT	(0FFH),A
	LD	A,L
	OUT	(0FEH),A
	LD	A,B
	LD	(D.DB03),A
	LD	(D.D9BF),A
	 CALL	C.8823
;
	LD	HL,I$63CD
	PUSH	HL
	JP	J$7EC0
;
;	-----------------
?.9A21:	LD	A,(D.DB04)
	OR	A
	RET	Z
;
	 CALL	C.74D0
;
	CP	30H	; "0"
	RET	C
;
	CP	3AH	; ":"
	RET	NC
;
	AND	0FH	; 15 
	LD	B,A
	LD	A,(D.DB04)
	CP	B
	RET	C
;
	LD	A,B
	AND	0FH	; 15 
	NOP	
	LD	B,A
	LD	HL,I.0001
	OR	A
	JR	Z,J$9A48
;
	RLCA	
	ADD	A,02H	; 2 
	LD	H,A
	INC	A
	LD	L,A
J$9A48:	LD	A,H
	OUT	(0FFH),A
	LD	A,L
	OUT	(0FEH),A
	LD	A,B
	LD	(D.DB03),A
	LD	(D.D9BF),A
	JP	J$6557
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9A58:	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$9A64
;
	SRL	H
	LD	A,0FH	; 15 
	ADD	A,H
	LD	H,A
J$9A64:	LD	A,(BC)
	OR	30H	; "0"
	LD	D,01H	; 1 
	LD	E,A
	PUSH	BC
	 CALL	C.7B13
;
	POP	BC
	INC	BC
	LD	A,(BC)
	OR	30H	; "0"
	LD	E,A
	 CALL	C.7B13
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9A78:	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$9A84
;
	SRL	H
	LD	A,0FH	; 15 
	ADD	A,H
	LD	H,A
J$9A84:	LD	A,(BC)
	OR	30H	; "0"
	LD	D,01H	; 1 
	LD	E,A
	XOR	A
	 CALL	C.7AE5
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9A8F:	LD	A,(D.DA8F)
	OR	A
	LD	HL,I$1A03
	LD	DE,I.0802
	JR	Z,J$9A9D
;
	LD	H,26H	; "&"
J$9A9D:	LD	A,0F3H
	 CALL	C.80BE
;
	LD	A,0CCH
	LD	(D.DAD9),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9AA8:	LD	A,(D.DA94)
	OR	A
	LD	HL,I$1209
	LD	DE,I.0802
	JR	Z,J.9ABD
;
	DEC	A
	LD	D,0CH	; 12 
	LD	H,1EH
	JR	Z,J.9ABD
;
	LD	H,2EH	; "."
J.9ABD:	LD	A,0F3H
	 CALL	C.80BE
;
	LD	A,0CCH
	LD	(D.DAD9),A
	RET	
;
;	-----------------
?.9AC8:	RET	C
;
	PUSH	AF
	LD	A,(D.FFA7)
	CP	0C9H
	JR	NZ,J$9ADA
;
	POP	AF
	CP	04H	; 4 
	JR	Z,J$9AD8
;
	OR	A
	RET	
;
;	-----------------
J$9AD8:	SCF	
	RET	
;
;	-----------------
J$9ADA:	POP	AF
	CP	03H	; 3 
	RET	Z
;
	CP	04H	; 4 
	JP	Z,J.A033
;
	CP	01H	; 1 
	JR	Z,J$9AEB
;
	 CALL	C.9DC1
;
	RET	C
;
J$9AEB:	 CALL	C.9C80
;
	RET	C
;
	RET	Z
;
	LD	BC,I$8B8F
	LD	DE,I$8B9B
	LD	H,00H
	 CALL	C.9B23
;
	RET	C
;
	PUSH	AF
	LD	BC,I.8B6F
	 CALL	C.71AB
;
	POP	AF
	CP	01H	; 1 
	JR	Z,J$9B10
;
	 CALL	C.9DC1
;
	LD	DE,I.CF38
	JR	J$9B19
;
;	-----------------
J$9B10:	 CALL	C$7CBC
;
	LD	HL,I.8000
	LD	DE,I.CF38
J$9B19:	XOR	A
	 CALL	C.A276
;
	OR	A
	 CALL	NZ,C.9CE1
;
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9B23:	PUSH	AF
	PUSH	DE
	PUSH	BC
	LD	A,H
	 CALL	C$A2E2
;
	OR	A
	JR	Z,J$9B35
;
	 CALL	C.9CE1
;
	POP	BC
	POP	DE
	POP	AF
	SCF	
	RET	
;
;	-----------------
J$9B35:	 CALL	C.807F
;
	LD	HL,I.0200
	LD	DE,I.1802
	LD	A,60H	; "`"
	 CALL	C.80BE
;
	LD	HL,I.0400
	POP	BC
	 CALL	C.7C44
;
	LD	HL,I.0016
	LD	DE,I.4002
	LD	A,0D0H
	 CALL	C.80BE
;
	LD	HL,I.0216
	POP	BC
	 CALL	C.7C44
;
	LD	B,0FFH
	LD	HL,I.D0D0
J$9B61:	LD	A,(HL)
	INC	B
	OR	A
	JR	Z,J$9B6D
;
	LD	A,06H	; 6 
	 CALL	C.7CEF
;
	JR	J$9B61
;
;	-----------------
J$9B6D:	LD	A,B
	LD	(D.DB01),A
	LD	A,01H	; 1 
J.9B73:	LD	(D.DB00),A
	 CALL	C$9D3F
;
	JR	C,J.9B7D
;
	LD	C,00H
J.9B7D:	PUSH	BC
	 CALL	C.9D21
;
	 CALL	C.61DB
;
	 CALL	C.74AE
;
	POP	BC
	JR	NC,J$9B8D
;
	POP	AF
	SCF	
	RET	
;
;	-----------------
J$9B8D:	 CALL	C.9D21
;
	CP	1FH
	JR	NZ,J$9BB2
;
	LD	A,(D.FBE0)
	CP	0FEH
	JR	Z,J$9BAC
;
	LD	A,09H	; 9 
	CP	C
	JR	C,J.9B7D
;
	INC	C
	INC	C
	LD	A,(D.DAFF)
	CP	C
	JR	NC,J.9B7D
;
	DEC	C
	DEC	C
	JR	J.9B7D
;
;	-----------------
J$9BAC:	LD	A,(D.DB00)
	INC	A
	JR	J.9B73
;
;	-----------------
J$9BB2:	CP	1EH
	JR	NZ,J$9BD4
;
	LD	A,(D.FBE0)
	CP	0FEH
	JR	Z,J$9BC8
;
	LD	A,01H	; 1 
	CP	C
	JP	NC,J.9B7D
;
	DEC	C
	DEC	C
	JP	J.9B7D
;
;	-----------------
J$9BC8:	LD	A,(D.DB00)
	CP	01H	; 1 
	JP	Z,J.9B7D
;
	DEC	A
	JP	J.9B73
;
;	-----------------
J$9BD4:	CP	1CH
	JR	NZ,J$9BE4
;
	LD	A,(D.DAFF)
	CP	C
	JP	Z,J.9B7D
;
	SET	0,C
	JP	J.9B7D
;
;	-----------------
J$9BE4:	CP	1DH
	JR	NZ,J$9BED
;
	RES	0,C
	JP	J.9B7D
;
;	-----------------
J$9BED:	CP	0DH	; 13 
	JP	NZ,J.9B7D
;
	LD	A,(D.DB00)
	DEC	A
	RLCA	
	RLCA	
	LD	H,A
	RLCA	
	ADD	A,H
	ADD	A,C
	LD	H,00H
	LD	L,A
	ADD	HL,HL
	LD	D,H
	LD	E,L
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.D0D0
	ADD	HL,DE
	LD	DE,D.F866
	LD	BC,CPMADR
	LDIR	
	POP	AF
	OR	A
	RET	
;
;	-----------------
?.9C13:	RET	C
;
	PUSH	AF
	LD	A,(D.FFA7)
	CP	0C9H
	JR	NZ,J$9C25
;
	POP	AF
	CP	04H	; 4 
	JR	Z,J$9C23
;
	OR	A
	RET	
;
;	-----------------
J$9C23:	SCF	
	RET	
;
;	-----------------
J$9C25:	POP	AF
	CP	03H	; 3 
	RET	Z
;
	CP	02H	; 2 
	RET	Z
;
	CP	04H	; 4 
	JP	Z,J.A033
;
	 CALL	C.9C80
;
	RET	C
;
	RET	Z
;
J$9C36:	LD	HL,I.8000
	LD	A,83H
	 CALL	C.000C
;
	CP	0FEH
	JR	NZ,J$9C44
;
	SCF	
	RET	
;
;	-----------------
J$9C44:	 CALL	C.7C14
;
	RET	C
;
	LD	A,(D.F866)
	CP	20H	; " "
	JR	Z,J$9C36
;
	LD	BC,I.8B75
	 CALL	C.71AB
;
	 CALL	C$9DE5
;
	LD	DE,I.8000
	ADD	HL,DE
	EX	DE,HL
J$9C5D:	XOR	A
J$9C5E:	PUSH	HL
	PUSH	DE
	 CALL	C.A1E7
;
	OR	A
	JR	Z,J$9C7C
;
	CP	03H	; 3 
	JR	Z,J$9C72
;
	 CALL	C.9CE1
;
	POP	DE
	POP	HL
	RET	C
;
	JR	J$9C5D
;
;	-----------------
J$9C72:	 CALL	C.9CE1
;
	POP	DE
	POP	HL
	RET	C
;
	XOR	A
	SCF	
	JR	J$9C5E
;
;	-----------------
J$9C7C:	POP	DE
	POP	HL
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9C80:	PUSH	AF
	LD	HL,I.000D
	LD	DE,I$4009
	XOR	A
	 CALL	C.80BE
;
	LD	HL,I$0C0E
	LD	DE,I$2804
	LD	A,0C0H
	 CALL	C.80BE
;
	LD	HL,I.0E0F
	LD	BC,I$8B7B
	 CALL	C.7C44
;
J$9C9F:	LD	HL,I.0E0F
	LD	DE,I$1002
J.9CA5:	LD	A,0F3H
	PUSH	HL
	PUSH	DE
	 CALL	C.80BE
;
	 CALL	C.61DB
;
	 CALL	C.74AE
;
	POP	DE
	POP	HL
	PUSH	AF
	PUSH	HL
	PUSH	DE
	LD	A,0F3H
	 CALL	C.80BE
;
	POP	DE
	POP	HL
	POP	AF
	JR	NC,J$9CC4
;
	POP	AF
	SCF	
	RET	
;
;	-----------------
J$9CC4:	CP	1CH
	JR	NZ,J$9CCC
;
	LD	H,22H	; """
	JR	J.9CA5
;
;	-----------------
J$9CCC:	CP	1DH
	JR	Z,J$9C9F
;
	CP	0DH	; 13 
	JR	NZ,J.9CA5
;
	LD	A,0EH	; 14 
	CP	H
	JR	NZ,J$9CDC
;
	POP	AF
	OR	A
	RET	
;
;	-----------------
J$9CDC:	POP	AF
	LD	H,A
	XOR	A
	LD	A,H
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9CE1:	PUSH	AF
	LD	HL,I.000D
	LD	DE,I$400B
	XOR	A
	 CALL	C.80BE
;
	POP	AF
	LD	BC,I$8BBB
	DEC	A
	JR	Z,J.9D02
;
	LD	BC,J.8BDF
	DEC	A
	JR	Z,J.9D02
;
	LD	BC,J.8BCD
	DEC	A
	JR	Z,J.9D02
;
	LD	BC,I$8BF1
J.9D02:	LD	HL,I$100F
	 CALL	C.7C44
;
J$9D08:	 CALL	C.61DB
;
	 CALL	C.74AE
;
	JR	C,J$9D14
;
	CP	0DH	; 13 
	JR	NZ,J$9D08
;
J$9D14:	PUSH	AF
	LD	HL,I.000D
	LD	DE,I$4005
	XOR	A
	 CALL	C.80BE
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9D21:	PUSH	AF
	PUSH	BC
	LD	DE,I.1802
	LD	H,06H	; 6 
	BIT	0,C
	JR	Z,J$9D2E
;
	LD	H,22H	; """
J$9D2E:	LD	L,04H	; 4 
	SRL	C
	LD	A,C
	RLCA	
	ADD	A,C
	ADD	A,L
	LD	L,A
	LD	A,0F3H
	 CALL	C.80BE
;
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9D3F:	LD	A,(D.DB00)
	DEC	A
	RLCA	
	RLCA	
	LD	H,A
	RLCA	
	ADD	A,H
	LD	H,A
	INC	H
	LD	A,(D.DB01)
	SUB	H
	JR	NC,J$9D56
;
	LD	HL,D.DB00
	DEC	(HL)
	SCF	
	RET	
;
;	-----------------
J$9D56:	CP	0CH	; 12 
	JR	C,J$9D5C
;
	LD	A,0BH	; 11 
J$9D5C:	LD	(D.DAFF),A
	LD	HL,I.0203
	LD	DE,I$3C13
	LD	A,0C0H
	 CALL	C.80BE
;
	LD	A,(D.DB00)
	DEC	A
	RLCA	
	RLCA	
	LD	H,A
	RLCA	
	ADD	A,H
	LD	H,00H
	LD	L,A
	ADD	HL,HL
	LD	D,H
	LD	E,L
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.D0D0
	ADD	HL,DE
	LD	B,H
	LD	C,L
	LD	L,04H	; 4 
	LD	E,00H
J$9D85:	LD	H,06H	; 6 
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J.9D8F
;
	LD	H,12H	; 18 
J.9D8F:	LD	D,00H
J$9D91:	PUSH	DE
	LD	A,(BC)
	INC	BC
	 CALL	C.7C50
;
	LD	A,(D.DA8F)
	OR	A
	 CALL	Z,C$8239
;
	 CALL	NZ,C$81D3
;
	POP	DE
	INC	D
	LD	A,06H	; 6 
	CP	D
	JR	NZ,J$9D91
;
	LD	A,(D.DAFF)
	CP	E
	RET	Z
;
	INC	H
	INC	H
	LD	A,(D.DA8F)
	OR	A
	JR	NZ,J$9DB7
;
	INC	H
	INC	H
J$9DB7:	INC	E
	BIT	0,E
	JR	NZ,J.9D8F
;
	INC	L
	INC	L
	INC	L
	JR	J$9D85
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9DC1:	PUSH	AF
	LD	HL,I.8000
J$9DC5:	LD	A,83H
	 CALL	C.000C
;
	CP	0FEH
	JR	Z,J$9DD4
;
	LD	DE,I.0078
	ADD	HL,DE
	JR	J$9DC5
;
;	-----------------
J$9DD4:	PUSH	HL
	EX	DE,HL
	LD	HL,I.CF38
	OR	A
	SBC	HL,DE
	POP	HL
	JR	Z,J$9DE2
;
	POP	AF
	OR	A
	RET	
;
;	-----------------
J$9DE2:	POP	AF
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9DE5:	LD	HL,I.8000
	PUSH	HL
J$9DE9:	LD	A,83H
	 CALL	C.000C
;
	CP	0FEH
	JR	Z,J$9DF8
;
	LD	DE,I.0078
	ADD	HL,DE
	JR	J$9DE9
;
;	-----------------
J$9DF8:	LD	DE,I.0078
	ADD	HL,DE
	POP	DE
	XOR	A
	SBC	HL,DE
	LD	(D.F86C),A
	LD	(D.F86D),HL
	OR	A
	RET	
;
;	-----------------
?.9E08:	LD	A,(D.FFA7)
	CP	0C9H
	LD	B,02H	; 2 
	JR	Z,J.9E28
;
	 CALL	C$A320
;
	OR	A
	JR	NZ,J.9E28
;
	LD	HL,I.D0D0
	LD	DE,D.DA6A
	LD	BC,FCB1.1
	LDIR	
	 CALL	C.9EB4
;
	 CALL	C$9EE4
;
J.9E28:	LD	A,0FFH
	OUT	(0FFH),A
	IN	A,(0FFH)
	BIT	2,A
	LD	A,00H
	OUT	(0FFH),A
	JR	Z,J$9E4A
;
	IN	A,(0FFH)
	LD	H,09H	; 9 
	BIT	4,A
	JR	Z,J.9E57
;
	LD	H,06H	; 6 
	BIT	3,A
	JR	Z,J.9E57
;
	LD	H,02H	; 2 
	BIT	2,A
	JR	Z,J.9E57
;
J$9E4A:	LD	B,03H	; 3 
	LD	HL,I.8000
J.9E4F:	INC	HL
	LD	A,H
	OR	L
	JR	NZ,J.9E4F
;
	DJNZ	J.9E4F
;
	RET	
;
;	-----------------
J.9E57:	LD	A,H
	LD	(D.DB04),A
	LD	B,00H
	DI	
J$9E5E:	LD	A,(D.DB04)
	CP	B
	RET	Z
;
	LD	A,0FFH
	OUT	(0A8H),A
	PUSH	BC
	LD	A,B
	INC	A
	RLCA	
	ADD	A,02H	; 2 
	OUT	(0FCH),A
	LD	HL,I.C000
	LD	DE,C.0000
	LD	BC,I.4000
	LDIR	
	INC	A
	OUT	(0FCH),A
	LD	A,01H	; 1 
	OUT	(0FFH),A
	LD	HL,I.C000
	LD	DE,C.0000
	LD	BC,I.4000
	LDIR	
	XOR	A
	OUT	(0FFH),A
	LD	A,03H	; 3 
	OUT	(0FCH),A
	LD	A,0FCH
	OUT	(0A8H),A
	POP	BC
	INC	B
	JR	J$9E5E
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9E9B:	LD	HL,I$9EC3
	LD	DE,D.F866
	LD	BC,D.0004
	LDIR	
	LD	A,(D.DA92)
	OR	30H	; "0"
	LD	(DE),A
	INC	DE
	LD	A,(D.DA93)
	OR	30H	; "0"
	LD	(DE),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9EB4:	 CALL	C.9E9B
;
	LD	HL,I.7800
	LD	DE,I.8000
	LD	A,0F0H
	 CALL	C.A276
;
	RET	
;
;	-----------------
I$9EC3:	LD	B,A
	LD	B,C
	LD	C,C
	LD	C,D
I$9EC7:	LD	C,D
	LD	D,L
	LD	C,E
	LD	D,L
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9ECB:	LD	HL,I$9EC7
	LD	DE,D.F866
	LD	BC,D.0004
	LDIR	
	LD	A,(D.DA90)
	OR	30H	; "0"
	LD	(DE),A
	INC	DE
	LD	A,(D.DA91)
	OR	30H	; "0"
	LD	(DE),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9EE4:	 CALL	C.9ECB
;
	LD	HL,D.2500
	LD	DE,I.7800
	LD	A,0FFH
	 CALL	C.A276
;
	OR	A
	JR	NZ,J$9EFA
;
	DEC	HL
	LD	(D.DA67),HL
	RET	
;
;	-----------------
J$9EFA:	PUSH	AF
	LD	HL,I.2800
	LD	(D.DA67),HL
	LD	E,0FFH
	LD	A,83H
	 CALL	C.0014
;
	LD	HL,D.2500
	LD	A,83H
	 CALL	C.0014
;
	LD	A,83H
	INC	HL
	 CALL	C.0014
;
	POP	AF
	RET	
;
;	-----------------
?.9F18:	CP	01H	; 1 
	RET	Z
;
	PUSH	AF
	LD	A,(D.FFA7)
	CP	0C9H
	JR	NZ,J$9F2C
;
	POP	AF
	CP	04H	; 4 
	JR	Z,J$9F2A
;
	OR	A
	RET	
;
;	-----------------
J$9F2A:	SCF	
	RET	
;
;	-----------------
J$9F2C:	POP	AF
	CP	04H	; 4 
	JP	Z,J$A03A
;
	 CALL	C.9C80
;
	RET	C
;
	RET	Z
;
	CP	02H	; 2 
	JR	NZ,J$9F4A
;
	LD	BC,I.8B6F
	 CALL	C.71AB
;
	 CALL	C.9EB4
;
	OR	A
	 CALL	NZ,C.9CE1
;
	SCF	
	RET	
;
;	-----------------
J$9F4A:	LD	BC,I.8B75
	 CALL	C.71AB
;
	 CALL	C.9E9B
;
	OR	A
J$9F54:	LD	HL,I.7800
	LD	DE,I.8000
	LD	A,0F0H
	 CALL	C.A1E7
;
	OR	A
	JR	NZ,J$9F64
;
	SCF	
	RET	
;
;	-----------------
J$9F64:	CP	03H	; 3 
	JR	NZ,J$9F6F
;
	 CALL	C.9CE1
;
	RET	C
;
	SCF	
	JR	J$9F54
;
;	-----------------
J$9F6F:	 CALL	C.9CE1
;
	SCF	
	RET	
;
;	-----------------
?.9F74:	CP	04H	; 4 
	RET	NC
;
	PUSH	AF
	LD	A,(D.FFA7)
	CP	0C9H
	JR	NZ,J$9F88
;
	POP	AF
	CP	03H	; 3 
	JR	Z,J$9F86
;
	OR	A
	RET	
;
;	-----------------
J$9F86:	SCF	
	RET	
;
;	-----------------
J$9F88:	POP	AF
	CP	03H	; 3 
	JP	Z,J$A041
;
	PUSH	AF
	CP	02H	; 2 
	JR	NZ,J.9FB8
;
	LD	A,83H
	LD	HL,I.2800
	 CALL	C.000C
;
	CP	0FFH
	JR	NZ,J.9FB8
;
	LD	A,83H
	LD	HL,D.2500
	 CALL	C.000C
;
	CP	0FFH
	JR	NZ,J.9FB8
;
	LD	A,83H
	INC	HL
	 CALL	C.000C
;
	CP	0FFH
	JR	NZ,J.9FB8
;
	POP	AF
	SCF	
	RET	
;
;	-----------------
J.9FB8:	POP	AF
	 CALL	C.9C80
;
	RET	C
;
	RET	Z
;
	CP	01H	; 1 
	JR	NZ,J$A007
;
	LD	BC,I.8B6F
	 CALL	C.71AB
;
	 CALL	C.9ECB
;
	LD	HL,D.2500
	LD	DE,I.7800
	LD	A,0FFH
	 CALL	C.A276
;
	OR	A
	JR	NZ,J$9FDF
;
	DEC	HL
	LD	(D.DA67),HL
	SCF	
	RET	
;
;	-----------------
J$9FDF:	PUSH	AF
	 CALL	C.9CE1
;
	POP	AF
	CP	02H	; 2 
	JR	NZ,J$9FEA
;
	SCF	
	RET	
;
;	-----------------
J$9FEA:	LD	HL,I.2800
	LD	(D.DA67),HL
	LD	E,0FFH
	LD	A,83H
	 CALL	C.0014
;
	LD	HL,D.2500
	LD	A,83H
	 CALL	C.0014
;
	LD	A,83H
	INC	HL
	 CALL	C.0014
;
	SCF	
	RET	
;
;	-----------------
J$A007:	LD	BC,I.8B75
	 CALL	C.71AB
;
	OR	A
J$A00E:	PUSH	AF
	 CALL	C.9ECB
;
	POP	AF
	LD	HL,D.2500
	LD	DE,(D.DA67)
	INC	DE
	LD	A,0FFH
	 CALL	C.A1E7
;
	OR	A
	JR	Z,J$A02A
;
	CP	03H	; 3 
	JR	Z,J$A02C
;
	 CALL	C.9CE1
;
J$A02A:	SCF	
	RET	
;
;	-----------------
J$A02C:	 CALL	C.9CE1
;
	RET	C
;
	SCF	
	JR	J$A00E
;
;	-----------------
J.A033:	LD	H,00H
	LD	BC,I$8C03
	JR	J.A046
;
;	-----------------
J$A03A:	LD	H,0F0H
	LD	BC,I$8C1B
	JR	J.A046
;
;	-----------------
J$A041:	LD	H,0FFH
	LD	BC,I$8C0F
J.A046:	LD	DE,I$8C27
	PUSH	HL
	 CALL	C.9B23
;
	POP	HL
	RET	C
;
	PUSH	HL
	LD	BC,I$8C5F
	 CALL	C.71AB
;
	POP	HL
	LD	A,H
	 CALL	C$A347
;
	OR	A
	 CALL	NZ,C.9CE1
;
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A061:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	C,1AH
	LD	DE,I.CFF0
	 CALL	C.F37D
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.A072:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	HL,I.CFF0
	LD	DE,I.CFF1
	LD	BC,I$007F
	LD	(HL),00H
	LDIR	
	POP	BC
	POP	DE
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A086:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	HL,I.CFC0
	LD	DE,I.CFC1
	LD	BC,I$0023
	LD	(HL),00H
	LDIR	
	POP	BC
	POP	DE
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A09A:	LD	DE,I.CFC1
J$A09D:	LD	HL,D.F866
	LD	BC,CPMADR
	LDIR	
	EX	DE,HL
	LD	(HL),20H	; " "
	INC	HL
	LD	(HL),20H	; " "
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0AC:	LD	DE,I$CFD1
	JR	J$A09D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A0B1:	LD	DE,I.CFC9
J$A0B4:	LD	HL,I$A0D4
	LD	A,(D.D8A4)
	LD	BC,I$0003
	CP	00H
	JR	Z,J.A0D1
;
	ADD	HL,BC
	CP	0FFH
	JR	Z,J.A0D1
;
	ADD	HL,BC
	CP	0F0H
	JR	Z,J.A0D1
;
	ADD	HL,BC
	CP	80H
	JR	Z,J.A0D1
;
	ADD	HL,BC
J.A0D1:	LDIR	
	RET	
;
;	-----------------
I$A0D4:	LD	C,D
	LD	B,H
	LD	B,E
	LD	C,D
	LD	B,E
	LD	B,E
	LD	C,D
	LD	B,L
	LD	D,H
	LD	D,E
	LD	E,C
	LD	D,E
	LD	HL,I$2121
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0E3:	LD	DE,I$CFD9
	JR	J$A0B4
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0E8:	LD	HL,I.CFC1
	LD	B,06H	; 6 
J$A0ED:	LD	(HL),3FH	; "?"
	INC	HL
	DJNZ	J$A0ED
;
	LD	(HL),20H	; " "
	INC	HL
	LD	(HL),20H	; " "
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A0F8:	LD	HL,I.CFC9
	LD	B,03H	; 3 
J$A0FD:	LD	(HL),24H	; "$"
	INC	HL
	DJNZ	J$A0FD
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A103:	LD	E,00H
	 CALL	C.A2C1
;
	LD	HL,(D.D8A2)
	LD	BC,(D.D8A0)
	PUSH	BC
	OR	A
	SBC	HL,BC
	PUSH	HL
	LD	E,H
	 CALL	C.A2C1
;
	POP	DE
	PUSH	DE
	 CALL	C.A2C1
;
	POP	DE
	POP	HL
J$A11F:	LD	A,D
	OR	E
	JR	Z,J$A136
;
	LD	A,83H
	PUSH	DE
	 CALL	C.000C
;
	LD	E,A
	PUSH	HL
	 CALL	C.A2C1
;
	POP	HL
	POP	DE
	RET	C
;
	RET	NZ
;
	INC	HL
	DEC	DE
	JR	J$A11F
;
;	-----------------
J$A136:	 CALL	C$A2DA
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A13A:	 CALL	C.A2A3
;
	RET	C
;
	JR	NZ,J.A182
;
	 CALL	C.A2A3
;
	RET	C
;
	JR	NZ,J.A182
;
	LD	C,E
	PUSH	BC
	 CALL	C.A2A3
;
	POP	BC
	RET	C
;
	JR	NZ,J.A182
;
	LD	D,C
	LD	HL,(D.D8A0)
	PUSH	HL
	ADD	HL,DE
	LD	BC,(D.D8A2)
	OR	A
	SBC	HL,BC
	POP	HL
	JR	C,J.A168
;
	JR	Z,J.A168
;
	EX	DE,HL
	LD	H,B
	LD	L,C
	OR	A
	SBC	HL,DE
	EX	DE,HL
J.A168:	LD	A,D
	OR	E
	RET	Z
;
	PUSH	HL
	PUSH	DE
	 CALL	C.A2A3
;
	LD	A,E
	POP	DE
	POP	HL
	RET	C
;
	JR	NZ,J.A182
;
	PUSH	DE
	LD	E,A
	LD	A,83H
	 CALL	C.0014
;
	POP	DE
	INC	HL
	DEC	DE
	JR	J.A168
;
;	-----------------
J.A182:	XOR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A184:	LD	HL,I$D8AD
	LD	(D$F323),HL
	LD	DE,I$A194
	EX	DE,HL
	LD	BC,I$0011
	LDIR	
	RET	
;
;	-----------------
I$A194:	XOR	A
	RET	C
;
	LD	A,8FH
	LD	H,40H	; "@"
	 CALL	C$0024
;
	LD	HL,(D.D8A8)
	LD	SP,(D.D8AA)
	JP	(HL)
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A1A5:	LD	(D.D8AA),SP
	LD	HL,I$A1BF
	LD	(D.D8A8),HL
	PUSH	BC
	 CALL	C$A184
;
	 CALL	C$A061
;
	POP	BC
	LD	DE,I.CFC0
	 CALL	C.F37D
;
	OR	A
	RET	
;
;	-----------------
I$A1BF:	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A1C1:	LD	C,16H
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A1C5:	LD	C,13H	; 19 
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A1C9:	LD	C,0FH	; 15 
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A1CD:	LD	C,10H	; 16 
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A1D1:	LD	C,11H	; 17 
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A1D5:	LD	C,12H	; 18 
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A1D9:	LD	C,14H	; 20 
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A1DD:	LD	C,15H
	JR	J.A1E3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A1E1:	LD	C,17H
J.A1E3:	 CALL	C$A1A5
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A1E7:	LD	(D.D8A4),A
	LD	(D.D8A0),HL
	LD	(D.D8A2),DE
	SBC	A,A
	LD	(D.D8A5),A
	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0B1
;
	 CALL	C.A1D1
;
	JR	C,J.A262
;
	JR	NZ,J$A20B
;
	LD	A,(D.D8A5)
	OR	A
	JR	Z,J$A26A
;
J$A20B:	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0F8
;
	 CALL	C$A1C1
;
	JR	C,J.A262
;
	JR	NZ,J$A26E
;
	XOR	A
	LD	(D.D8AC),A
	 CALL	C$A103
;
	JR	C,J.A262
;
	JR	Z,J$A23B
;
	 CALL	C.A1CD
;
	JR	C,J.A262
;
	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0F8
;
	 CALL	C.A1C5
;
	JR	C,J.A262
;
	JR	J$A272
;
;	-----------------
J$A23B:	 CALL	C.A1CD
;
	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0B1
;
	 CALL	C.A1C5
;
	JR	C,J.A262
;
	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0F8
;
	 CALL	C$A0AC
;
	 CALL	C$A0E3
;
	 CALL	C$A1E1
;
	JR	C,J.A262
;
	XOR	A
	RET	
;
;	-----------------
J.A262:	LD	A,01H	; 1 
	SCF	
	RET	
;
;	-----------------
?.A266:	LD	A,02H	; 2 
	SCF	
	RET	
;
;	-----------------
J$A26A:	LD	A,03H	; 3 
	SCF	
	RET	
;
;	-----------------
J$A26E:	LD	A,04H	; 4 
	SCF	
	RET	
;
;	-----------------
J$A272:	LD	A,05H	; 5 
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A276:	LD	(D.D8A0),HL
	LD	(D.D8A2),DE
	LD	(D.D8A4),A
	XOR	A
	LD	(D.D8AC),A
	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0B1
;
	 CALL	C$A1C9
;
	JR	C,J.A29B
;
	JR	NZ,J$A29F
;
	 CALL	C$A13A
;
	JR	C,J.A29B
;
	XOR	A
	RET	
;
;	-----------------
J.A29B:	LD	A,01H	; 1 
	SCF	
	RET	
;
;	-----------------
J$A29F:	LD	A,02H	; 2 
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A2A3:	LD	A,(D.D8AC)
	OR	A
	JR	NZ,J$A2AE
;
	 CALL	C$A1D9
;
	RET	C
;
	RET	NZ
;
J$A2AE:	LD	A,(D.D8AC)
	LD	C,A
	LD	B,00H
	LD	HL,I.CFF0
	ADD	HL,BC
	LD	E,(HL)
	INC	A
	AND	7FH
	LD	(D.D8AC),A
	XOR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A2C1:	LD	A,(D.D8AC)
	LD	C,A
	LD	B,00H
	LD	HL,I.CFF0
	ADD	HL,BC
	LD	(HL),E
	INC	A
	AND	7FH
	LD	(D.D8AC),A
	JR	NZ,J$A2D8
;
	 CALL	C.A1DD
;
	RET	
;
;	-----------------
J$A2D8:	XOR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A2DA:	LD	A,(D.D8AC)
	OR	A
	 CALL	NZ,C.A1DD
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A2E2:	LD	(D.D8A4),A
	LD	HL,I.D0D0
	LD	(D.D8A0),HL
	 CALL	C.A086
;
	 CALL	C$A0E8
;
	 CALL	C.A0B1
;
	 CALL	C.A1D1
;
	JR	C,J.A318
;
	JR	NZ,J$A31C
;
J$A2FB:	LD	DE,(D.D8A0)
	LD	HL,I.CFF1
	LD	BC,CPMADR
	LDIR	
	LD	(D.D8A0),DE
	 CALL	C$A1D5
;
	JR	C,J.A318
;
	JR	Z,J$A2FB
;
	XOR	A
	LD	HL,(D.D8A0)
	LD	(HL),A
	RET	
;
;	-----------------
J.A318:	LD	A,01H	; 1 
	SCF	
	RET	
;
;	-----------------
J$A31C:	LD	A,02H	; 2 
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A320:	 CALL	C.A32C
;
	JP	C.A276
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A326:	 CALL	C.A32C
;
	JP	C.A1E7
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A32C:	LD	HL,I$A341
	LD	DE,D.F866
	LD	BC,CPMADR
	LDIR	
	LD	HL,I.D0D0
	LD	DE,I$D150
	LD	A,80H
	SCF	
	RET	
;
;	-----------------
I$A341:	LD	C,D
	LD	D,A
	LD	D,B
	LD	D,B
	LD	D,D
	LD	C,L
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A347:	LD	(D.D8A4),A
	 CALL	C.A086
;
	 CALL	C.A09A
;
	 CALL	C.A0B1
;
	 CALL	C.A1C5
;
	JR	C,J$A35C
;
	JR	NZ,J$A35F
;
	XOR	A
	RET	
;
;	-----------------
J$A35C:	LD	A,01H	; 1 
	RET	
;
;	-----------------
J$A35F:	LD	A,02H	; 2 
	SCF	
	RET	
;
;	-----------------
?.A363:	 CALL	C$A782
;
	LD	A,(D$FCC2)
	OR	A
	JR	Z,J$A37B
;
	LD	A,81H
J$A36E:	 CALL	C.A3A0
;
	JR	NC,J.A39C
;
	ADD	A,04H	; 4 
	CP	91H
	JR	NZ,J$A36E
;
	JR	J$A382
;
;	-----------------
J$A37B:	LD	A,01H	; 1 
	 CALL	C.A3A0
;
	JR	NC,J.A39C
;
J$A382:	LD	A,(D$FCC3)
	OR	A
	JR	Z,J$A396
;
	LD	A,82H
J$A38A:	 CALL	C.A3A0
;
	JR	NC,J.A39C
;
	ADD	A,04H	; 4 
	CP	92H
	JR	NZ,J$A38A
;
	RET	
;
;	-----------------
J$A396:	LD	A,02H	; 2 
	 CALL	C.A3A0
;
	RET	C
;
J.A39C:	LD	(D.DB05),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A3A0:	PUSH	AF
	PUSH	AF
	LD	HL,I.4000
	 CALL	C.000C
;
	CP	4AH	; "J"
	JR	NZ,J$A3B8
;
	POP	AF
	INC	HL
	 CALL	C.000C
;
	CP	4BH	; "K"
	JR	NZ,J$A3B9
;
	POP	AF
	OR	A
	RET	
;
;	-----------------
J$A3B8:	POP	AF
J$A3B9:	POP	AF
	SCF	
	RET	
;
;	-----------------
J$A3BC:	LD	A,(D.DB05)
	OR	A
	JP	Z,J.895A
;
	 CALL	C.A6AE
;
	LD	BC,C.0000
	LD	A,(D.DB05)
	PUSH	AF
	POP	IY
	LD	IX,I.4002
	 CALL	C.001C
;
	OR	A
	JP	Z,J.895A
;
	 CALL	C.A517
;
	XOR	A
	 CALL	C.A57E
;
	 CALL	C.A50A
;
	 CALL	C.7A37
;
	 CALL	C.8823
;
J$A3EA:	LD	HL,I.0215
	LD	IX,I.D110
	LD	B,0FH	; 15 
J$A3F3:	LD	E,(IX)
	INC	IX
	LD	D,(IX)
	INC	IX
	 CALL	C.7B13
;
	DJNZ	J$A3F3
;
J$A402:	 CALL	C.61DB
;
	 CALL	C.74D0
;
	JP	C,J.895A
;
	CP	1FH
	JR	NZ,J$A41C
;
	 CALL	C.A517
;
	LD	A,01H	; 1 
	 CALL	C.A57E
;
	 CALL	C.A50A
;
	JR	J$A3EA
;
;	-----------------
J$A41C:	CP	0DH	; 13 
	JR	NZ,J$A402
;
	 CALL	C$A524
;
	LD	HL,I.D110
	LD	E,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	D,A
	OR	E
	JR	Z,J$A432
;
	LD	A,0F0H
	OR	A
	RET	
;
;	-----------------
J$A432:	 CALL	C.7A37
;
	LD	BC,J.8A6B
	JP	J.8EF2
;
;	-----------------
J$A43B:	LD	A,(D.DB05)
	OR	A
	JP	Z,J.8E42
;
	 CALL	C.A6AE
;
	LD	BC,I.0001
	LD	A,(D.DB05)
	PUSH	AF
	POP	IY
	LD	IX,I.4002
	 CALL	C.001C
;
	OR	A
	JP	Z,J.8E42
;
	 CALL	C.A517
;
	XOR	A
	 CALL	C.A627
;
	 CALL	C.A50A
;
	 CALL	C.7A37
;
	LD	A,(D.D9E0)
	LD	(D.DA3B),A
J$A46C:	LD	A,01H	; 1 
	LD	(D.D9E0),A
	XOR	A
	LD	(D.DA3C),A
	LD	IX,I.D110
	LD	HL,I.0215
	LD	B,0AH	; 10 
J$A47E:	LD	D,(IX+1)
	LD	E,(IX)
	 CALL	C.7B13
;
	INC	IX
	INC	IX
	INC	H
	INC	H
	LD	A,(D.DA8F)
	OR	A
	JR	Z,J$A495
;
	INC	H
	INC	H
J$A495:	DJNZ	J$A47E
;
J.A497:	 CALL	C.8799
;
J.A49A:	 CALL	C.74D0
;
	JR	NC,J$A4A8
;
	LD	A,(D.DA3B)
	LD	(D.D9E0),A
	JP	J.895A
;
;	-----------------
J$A4A8:	CP	1CH
	JR	NZ,J$A4BF
;
	LD	A,(D.D9E0)
	CP	1CH
	JR	Z,J.A49A
;
	ADD	A,03H	; 3 
	LD	(D.D9E0),A
	LD	HL,D.DA3C
	INC	(HL)
	INC	(HL)
	JR	J.A497
;
;	-----------------
J$A4BF:	CP	1DH
	JR	NZ,J$A4D6
;
	LD	A,(D.D9E0)
	CP	01H	; 1 
	JR	Z,J.A49A
;
	SUB	03H	; 3 
	LD	(D.D9E0),A
	LD	HL,D.DA3C
	DEC	(HL)
	DEC	(HL)
	JR	J.A497
;
;	-----------------
J$A4D6:	CP	1EH
	JR	NZ,J$A4E8
;
	LD	A,0FFH
J$A4DC:	 CALL	C.A517
;
	 CALL	C.A627
;
	 CALL	C.A50A
;
	JP	J$A46C
;
;	-----------------
J$A4E8:	CP	1FH
	JR	NZ,J$A4F0
;
	LD	A,01H	; 1 
	JR	J$A4DC
;
;	-----------------
J$A4F0:	CP	0DH	; 13 
	JR	NZ,J.A49A
;
	LD	HL,I.D110
	LD	A,(D.DA3C)
	 CALL	C.7CEF
;
	LD	E,(HL)
	INC	HL
	LD	A,(HL)
	LD	D,A
	OR	E
	JP	Z,J.A49A
;
	LD	A,(D.D91C)
	OR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A50A:	PUSH	AF
	LD	A,0FCH
	OUT	(0A8H),A
	LD	A,3CH	; "<"
	LD	(D.FFFF),A
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A517:	DI	
	PUSH	AF
	LD	A,0FFH
	OUT	(0A8H),A
	LD	A,3CH	; "<"
	LD	(D.FFFF),A
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A524:	 CALL	C.A517
;
	LD	HL,(D.DB0C)
	LD	A,0FFH
	CP	H
	JR	NZ,J.A536
;
	CP	L
	JR	NZ,J.A536
;
J$A532:	 CALL	C.A50A
;
	RET	
;
;	-----------------
J.A536:	LD	BC,D.2500
J$A539:	LD	A,(BC)
	INC	BC
	LD	E,A
	LD	A,(BC)
	INC	BC
	LD	D,A
	 CALL	C.A694
;
	JR	Z,J$A568
;
	PUSH	HL
	LD	HL,D.FFFF
	 CALL	C.A694
;
	POP	HL
	JR	NZ,J$A539
;
J$A54E:	PUSH	HL
	LD	HL,I$27FD
	LD	DE,I$27FF
	LD	BC,I$02FF
	LDDR	
	LD	HL,I$27FE
	LD	(HL),0FFH
	INC	HL
	LD	(HL),0FFH
	POP	HL
	LD	(D.2500),HL
	JR	J$A532
;
;	-----------------
J$A568:	PUSH	HL
	LD	D,B
	LD	E,C
	LD	HL,I.2800
	XOR	A
	SBC	HL,BC
	JR	Z,J$A57B
;
	LD	B,H
	LD	C,L
	LD	H,D
	LD	L,E
	DEC	DE
	DEC	DE
	LDIR	
J$A57B:	POP	HL
	JR	J$A54E
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A57E:	OR	A
	JR	NZ,J$A5C1
;
	LD	HL,I.1200
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,I.FF00
	 CALL	C.A694
;
	LD	HL,I.1202
	JR	Z,J$A5E6
;
	 CALL	C.A69A
;
	LD	HL,D.DB0C
	LD	(HL),0FFH
	INC	HL
	LD	(HL),0FFH
	LD	HL,I.1200
	LD	BC,I.D110
J.A5A3:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	HL
	LD	HL,D.FFFF
	 CALL	C.A694
;
	POP	HL
	RET	Z
;
	LD	A,E
	AND	7FH
	LD	E,A
	EX	DE,HL
	 CALL	C.A6FE
;
	EX	DE,HL
	LD	A,E
	LD	(BC),A
	INC	BC
	LD	A,D
	LD	(BC),A
	INC	BC
	JR	J.A5A3
;
;	-----------------
J$A5C1:	LD	HL,(D.DB0C)
	LD	A,0FFH
	CP	H
	JR	NZ,J$A5CB
;
	CP	L
	RET	Z
;
J$A5CB:	LD	HL,(D.DB06)
J$A5CE:	BIT	7,(HL)
	JR	NZ,J$A5D6
;
	INC	HL
	INC	HL
	JR	J$A5CE
;
;	-----------------
J$A5D6:	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	0FH	; 15 
	CP	02H	; 2 
	JR	NZ,J$A5E4
;
	XOR	A
	JR	C.A57E
;
;	-----------------
J$A5E4:	INC	HL
	INC	HL
J$A5E6:	LD	(D.DB06),HL
	LD	BC,I.D110
	 CALL	C.A69A
;
J$A5EF:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	A,E
	AND	7FH
	BIT	7,E
	LD	E,A
	EX	DE,HL
	 CALL	C.A6FE
;
	EX	DE,HL
	PUSH	AF
	LD	A,E
	LD	(BC),A
	INC	BC
	LD	A,D
	LD	(BC),A
	INC	BC
	POP	AF
	JR	Z,J$A5EF
;
	LD	A,(HL)
	INC	HL
	LD	(D.DB0C),A
	LD	A,(HL)
	INC	HL
	LD	(D$DB0D),A
J$A612:	LD	A,(HL)
	INC	HL
	INC	HL
	AND	0FH	; 15 
	CP	02H	; 2 
	JP	Z,J.A5A3
;
J$A61C:	LD	A,(HL)
	INC	HL
	INC	HL
	BIT	7,A
	JR	Z,J$A61C
;
	INC	HL
	INC	HL
	JR	J$A612
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A627:	SUB	01H	; 1 
	JR	C,J$A658
;
	JR	Z,J$A63E
;
	LD	HL,(D.DB06)
	LD	DE,I$003C
	SBC	HL,DE
	LD	DE,I.1202
	 CALL	C.A694
;
	RET	C
;
	JR	J.A65B
;
;	-----------------
J$A63E:	LD	HL,(D.DB06)
	LD	B,0AH	; 10 
J$A643:	LD	A,06H	; 6 
	 CALL	C.7CEF
;
	PUSH	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,D.FFFF
	 CALL	C.A694
;
	POP	HL
	RET	Z
;
	DJNZ	J$A643
;
	JR	J.A65B
;
;	-----------------
J$A658:	LD	HL,I.1202
J.A65B:	LD	(D.DB06),HL
	 CALL	C.A69A
;
	LD	HL,(D.DB06)
	LD	B,0AH	; 10 
	LD	DE,I.D110
J$A669:	PUSH	BC
	PUSH	HL
	PUSH	DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,D.FFFF
	 CALL	C.A694
;
	JR	NZ,J$A67B
;
	POP	DE
	POP	HL
	POP	BC
	RET	
;
;	-----------------
J$A67B:	LD	A,E
	AND	7FH
	LD	E,A
	EX	DE,HL
	 CALL	C.A6FE
;
	POP	DE
	LD	A,L
	LD	(DE),A
	INC	DE
	LD	A,H
	LD	(DE),A
	INC	DE
	POP	HL
	LD	A,06H	; 6 
	 CALL	C.7CEF
;
	POP	BC
	DJNZ	J$A669
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A694:	LD	A,H
	SUB	D
	RET	NZ
;
	LD	A,L
	SUB	E
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A69A:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	HL,I.D110
	LD	(HL),00H
	LD	D,H
	LD	E,L
	INC	DE
	LD	BC,I$001F
	LDIR	
	POP	BC
	POP	DE
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A6AE:	LD	HL,I.D130
	LD	BC,I.D0D0
J$A6B4:	LD	DE,(D.D9E5)
	RST	20H
;
	JR	NZ,J$A6C1
;
	LD	A,0FFH
	LD	(BC),A
	INC	BC
	LD	(BC),A
	RET	
;
;	-----------------
J$A6C1:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	EX	DE,HL
	 CALL	C$A6D2
;
	LD	A,L
	LD	(BC),A
	INC	BC
	LD	A,H
	LD	(BC),A
	INC	BC
	EX	DE,HL
	JR	J$A6B4
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A6D2:	PUSH	AF
	PUSH	DE
	LD	DE,I.0400
	RST	20H
;
	LD	A,20H	; " "
	JR	C,J$A6E0
;
	LD	A,30H	; "0"
	SBC	HL,DE
J$A6E0:	 CALL	C$A6EC
;
	ADD	A,H
	LD	H,A
	LD	A,20H	; " "
	ADD	A,L
	LD	L,A
	POP	DE
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A6EC:	PUSH	AF
	PUSH	DE
	XOR	A
	LD	DE,I.0060
J$A6F2:	SBC	HL,DE
	JR	C,J$A6F9
;
	INC	A
	JR	J$A6F2
;
;	-----------------
J$A6F9:	ADD	HL,DE
	LD	H,A
	POP	DE
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A6FE:	PUSH	AF
	PUSH	DE
	LD	DE,I$3020
	 CALL	C.A694
;
	JR	C,J$A72B
;
	LD	DE,I$5020
	 CALL	C.A694
;
	JR	C,J$A717
;
	LD	D,10H	; 16 
	LD	A,H
	SUB	50H	; "P"
	JR	J.A71C
;
;	-----------------
J$A717:	LD	D,04H	; 4 
	LD	A,H
	SUB	30H	; "0"
J.A71C:	LD	H,A
	LD	A,L
	SUB	20H	; " "
	LD	E,A
	LD	L,H
	LD	H,00H
	 CALL	C$A732
;
	ADD	HL,DE
	POP	DE
	POP	AF
	RET	
;
;	-----------------
J$A72B:	LD	D,00H
	LD	A,H
	SUB	20H	; " "
	JR	J.A71C
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A732:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	A,L
	OR	A
	JR	Z,J$A743
;
	LD	B,L
	LD	HL,C.0000
	LD	DE,I.0060
J$A740:	ADD	HL,DE
	DJNZ	J$A740
;
J$A743:	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.A747:	LD	A,(D.DB08)
	OR	A
	JR	NZ,J$A75B
;
	LD	HL,D.D94D
	LD	B,20H	; " "
J$A752:	LD	(HL),0FFH
	INC	HL
	DJNZ	J$A752
;
	LD	DE,D.D94D
	RET	
;
;	-----------------
J$A75B:	SLA	L
	RL	H
	SLA	L
	RL	H
	RRC	L
	RRC	L
	LD	A,(D.DB09)
	LD	C,A
	OUT	(C),H
	LD	A,(D.DB0A)
	LD	C,A
	OUT	(C),L
	LD	A,(D.DB0B)
	LD	C,A
	LD	B,20H	; " "
	LD	HL,D.D94D
	INIR	
	LD	DE,D.D94D
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A782:	LD	DE,I$D8D9
	LD	A,0D8H
	 CALL	C.A7B4
;
	JR	NC,J.A7A5
;
	LD	A,0DAH
	 CALL	C.A7B4
;
	JR	NC,J.A7A5
;
	LD	DE,I$DADB
	LD	A,0DBH
	 CALL	C.A7B4
;
	JR	NC,J.A7A5
;
	LD	A,0DAH
	 CALL	C.A7B4
;
	JR	NC,J.A7A5
;
	RET	
;
;	-----------------
J.A7A5:	LD	(D.DB0B),A
	LD	A,E
	LD	(D.DB09),A
	LD	A,D
	LD	(D.DB0A),A
	LD	(D.DB08),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A7B4:	PUSH	DE
	PUSH	AF
	LD	C,D
	LD	A,38H	; "8"
	OUT	(C),A
	LD	C,E
	LD	A,05H	; 5 
	OUT	(C),A
	POP	AF
	PUSH	AF
	LD	C,A
	LD	B,20H	; " "
	LD	HL,D.D94D
	PUSH	HL
	INIR	
	LD	B,20H	; " "
	POP	DE
	LD	HL,I$A7E1
J$A7D1:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$A7DD
;
	INC	HL
	INC	DE
	DJNZ	J$A7D1
;
	POP	AF
	POP	DE
	OR	A
	RET	
;
;	-----------------
J$A7DD:	POP	AF
	POP	DE
	SCF	
	RET	
;
;	-----------------
I$A7E1:	NOP	
	LD	A,A
	LD	B,B
	LD	B,B
	LD	B,B
	LD	B,B
	LD	B,B
	LD	B,B
	NOP	
	 CALL	M,C$0404
;
	INC	B
	INC	B
	INC	B
	INC	B
	LD	B,B
	LD	B,B
	LD	B,B
	LD	B,B
	LD	B,B
	LD	B,B
	LD	A,A
	LD	B,B
	INC	B
	INC	B
	INC	B
	INC	B
	INC	B
	INC	B
	 CALL	M,C$FF04
;
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	LD	(DE),A
	LD	(HL),C
	INC	E
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	LD	(HL),5AH	; "Z"
	JR	J$A964
;
;	-----------------
?.A90A:	INC	H
	LD	E,D
	JR	NZ,J$A968
;
	LD	(DE),A
	LD	(HL),C
	LD	D,H
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	PUSH	BC
	LD	E,C
	LD	B,B
	LD	E,D
	LD	B,H
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	BIT	3,D
	LD	A,H
	LD	E,E
	LD	(DE),A
	LD	(HL),C
	INC	L
	LD	E,D
	INC	DE
	LD	E,D
	LD	SP,HL
	LD	E,C
	SUB	A
	LD	E,C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	JR	Z,J$A98C
;
	XOR	A
	LD	E,C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	D,H
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	B,B
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	HALT	
;
;	-----------------
?.A95B:	LD	E,C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
J$A964:	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
J$A968:	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	A,(DE)
	LD	(HL),E
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	ADD	HL,DE
	LD	(HL),C
	JR	J$A9D4
;
;	-----------------
?.A97A:	INC	DE
	LD	E,D
	INC	H
	LD	E,D
	JR	Z,J$A9DA
;
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
J$A98C:	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	D,H
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	B,H
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	C,A
	LD	(HL),E
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	JR	NZ,J$AA14
;
	INC	E
	LD	E,D
	INC	L
	LD	E,D
	LD	(HL),5AH	; "Z"
	ADD	A,A
	LD	E,D
	ADD	A,A
	LD	E,D
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	XOR	A
	LD	E,C
	LD	SP,HL
	LD	E,C
	PUSH	BC
	LD	E,C
	SUB	A
	LD	E,C
	LD	(DE),A
	LD	(HL),C
	BIT	3,D
J$A9D4:	LD	A,H
	LD	E,E
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
J$A9DA:	LD	(DE),A
	LD	(HL),C
	INC	BC
	LD	E,A
	LD	C,H
	LD	H,B
	ADC	A,A
	LD	E,L
	DEC	A
	LD	E,(HL)
	LD	(DE),A
	LD	(HL),C
	POP	BC
	LD	H,C
	LD	(HL),H
	LD	H,D
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	LD	(DE),A
	LD	(HL),C
	RET	M
;
	XOR	C
	LD	D,A
	XOR	D
	AND	D
	XOR	D
	LD	(BC),A
	XOR	E
	DEC	DE
	LD	E,C
	SCF	
	INC	H
	LD	B,(HL)
	LD	SP,D.0120
	LD	B,E
	LD	BC,I.0145
	LD	C,(HL)
	LD	BC,I.0154
	LD	B,L
	LD	BC,I$2052
	JR	NZ,J$AA2E
;
	JR	NZ,J$AA30
;
	JR	NZ,J$AA32
;
	LD	B,(HL)
	LD	(D.0120),A
J$AA14	EQU	$-2
	LD	C,C
	LD	BC,I.014E
	LD	B,H
	LD	BC,I.0145
	LD	C,(HL)
	LD	BC,I.2054
	JR	NZ,J$AA44
;
	JR	NZ,J$AA46
;
	JR	NZ,J$AA48
;
	LD	B,(HL)
	INC	SP
	JR	NZ,J$AA2D
;
	LD	D,D
J$AA2D:	LD	BC,I$0158
J$AA2E	EQU	$-2
J$AA30:	LD	C,D
	LD	BC,I.0155
J$AA32	EQU	$-2
	LD	D,E
	LD	BC,I.2054
	JR	NZ,J$AA5A
;
	JR	NZ,J$AA5C
;
	JR	NZ,J$AA5E
;
	LD	B,(HL)
	INC	(HL)
	JR	NZ,J$AA43
;
	LD	E,A
J$AA43:	LD	BC,I.0150
J$AA44	EQU	$-2
J$AA46:	LD	B,C
	LD	BC,I$0147
J$AA48	EQU	$-2
	LD	B,L
	LD	BC,I.205F
	JR	NZ,J$AA70
;
	JR	NZ,J$AA72
;
	JR	NZ,J$AA74
;
	JR	NZ,J$AA76
;
	NOP	
	DEC	DE
	LD	E,C
	SCF	
J$AA5A:	INC	H
	LD	B,(HL)
J$AA5C:	LD	SP,D.0120
J$AA5E	EQU	$-1
	LD	C,L
	LD	BC,I.0141
	LD	D,D
	LD	BC,I.014B
	LD	E,A
	LD	BC,I$2042
	JR	NZ,J$AA8D
;
	JR	NZ,J$AA8F
;
	JR	NZ,J$AA91
J$AA70	EQU	$-1
;
	LD	B,(HL)
J$AA72:	LD	(D.0120),A
J$AA74	EQU	$-1
	LD	C,L
J$AA76:	LD	BC,I.0141
	LD	D,D
	LD	BC,I.014B
	LD	E,A
	LD	BC,I.2045
	JR	NZ,J$AAA3
;
	JR	NZ,J$AAA5
;
	JR	NZ,J$AAA7
;
	JR	NZ,J$AAA9
;
	JR	NZ,J$AAAB
;
	JR	NZ,J$AAAD
;
J$AA8D:	JR	NZ,J$AAAF
;
J$AA8F:	JR	NZ,J$AAB1
;
J$AA91:	JR	NZ,J$AAB3
;
	JR	NZ,J$AAB5
;
	JR	NZ,J$AAB7
;
	JR	NZ,J$AAB9
;
	JR	NZ,J$AABB
;
	JR	NZ,J$AABD
;
	JR	NZ,J$AABF
;
	JR	NZ,J$AAC1
;
	NOP	
	DEC	DE
J$AAA3:	LD	E,C
	SCF	
J$AAA5:	INC	H
	LD	B,(HL)
J$AAA7:	LD	SP,D.0120
J$AAA9	EQU	$-1
	LD	E,A
J$AAAB:	LD	BC,I$014D
J$AAAD	EQU	$-1
	LD	C,A
J$AAAF:	LD	BC,C.0156
J$AAB1	EQU	$-1
	LD	B,L
J$AAB3:	LD	BC,I.205F
J$AAB5	EQU	$-1
	JR	NZ,J$AAD8
J$AAB7	EQU	$-1
;
	JR	NZ,J$AADA
J$AAB9	EQU	$-1
;
	JR	NZ,J$AADC
J$AABB	EQU	$-1
;
	LD	B,(HL)
J$AABD:	LD	(D.0120),A
J$AABF	EQU	$-1
	LD	E,A
J$AAC1:	LD	BC,I.0143
	LD	C,A
	LD	BC,I.0150
	LD	E,C
	LD	BC,I.205F
	JR	NZ,J$AAEE
;
	JR	NZ,J$AAF0
;
	JR	NZ,J$AAF2
;
	LD	B,(HL)
	INC	SP
	JR	NZ,J$AAD7
;
	LD	B,H
J$AAD7:	LD	BC,I.0145
J$AAD8	EQU	$-2
J$AADA:	LD	C,H
	LD	BC,I.0145
J$AADC	EQU	$-2
	LD	D,H
	LD	BC,I.2045
	JR	NZ,J$AB04
;
	JR	NZ,J$AB06
;
	JR	NZ,J$AB08
;
	LD	B,(HL)
	INC	(HL)
	JR	NZ,J$AAED
;
	LD	D,D
J$AAED:	LD	BC,I.0145
J$AAEE	EQU	$-2
J$AAF0:	LD	D,E
	LD	BC,I.0154
J$AAF2	EQU	$-2
	LD	C,A
	LD	BC,I.0152
	LD	B,L
	JR	NZ,J$AB1B
;
	JR	NZ,J$AB1D
;
	JR	NZ,J$AB1F
;
	JR	NZ,J$AB21
;
	NOP	
	DEC	DE
	LD	E,C
J$AB04:	SCF	
	INC	H
J$AB06:	LD	B,(HL)
	LD	SP,D.0120
J$AB08	EQU	$-2
	LD	E,A
	LD	BC,I$0146
	LD	C,C
	LD	BC,I.014E
	LD	B,H
	LD	BC,I.205F
	JR	NZ,J$AB38
;
	JR	NZ,J$AB3A
;
	JR	NZ,J$AB3C
J$AB1B	EQU	$-1
;
	LD	B,(HL)
J$AB1D:	LD	(D.0120),A
J$AB1F	EQU	$-1
	LD	D,D
J$AB21:	LD	BC,I.0145
	LD	D,B
	LD	BC,I$014C
	LD	B,C
	LD	BC,I.0143
	LD	B,L
	JR	NZ,J$AB4F
;
	JR	NZ,J$AB51
;
	JR	NZ,J$AB53
;
	JR	NZ,J$AB55
;
	JR	NZ,J$AB57
;
	JR	NZ,J$AB59
J$AB38	EQU	$-1
;
	JR	NZ,J$AB5B
J$AB3A	EQU	$-1
;
	JR	NZ,J$AB5D
J$AB3C	EQU	$-1
;
	JR	NZ,J$AB5F
;
	JR	NZ,J$AB61
;
	JR	NZ,J$AB63
;
	JR	NZ,J$AB65
;
	JR	NZ,J$AB67
;
	JR	NZ,J$AB69
;
	JR	NZ,J$AB6B
;
	JR	NZ,J$AB6D
;
	NOP	
	DEC	D
J$AB4F:	ADD	HL,DE
	LD	A,(BC)
J$AB51:	NOP	
	LD	SP,I$3131
J$AB53	EQU	$-2
J$AB55:	LD	SP,C.0000
J$AB57	EQU	$-1
	DEFB	0
J$AB59:	DEFB	0,0
J$AB5B:	DEFB	0
	RST	38H
J$AB5D:	RST	38H
	RST	38H
J$AB5F:	RST	38H
	NOP	
J$AB61:	RST	38H
	RST	38H
J$AB63:	RST	38H
	LD	(BC),A
J$AB65:	LD	B,D
	LD	B,09H	; 9 
J$AB67	EQU	$-1
	INC	BC
J$AB69:	EX	AF,AF'
	LD	B,C
J$AB6B:	LD	BC,C.0000
J$AB6D	EQU	$-1
	DEC	L
	DEC	L
	RST	38H
	INC	B
	JR	NZ,J$ABB9
;
	LD	H,H
	LD	L,C
	LD	(HL),H
	JR	NZ,J$AB79
;
J$AB79:	JR	NZ,J$ABBF
;
	LD	H,L
	LD	L,H
	LD	H,L
	LD	(HL),H
	LD	H,L
	JR	NZ,J$AB82
;
J$AB82:	JR	NZ,J$ABC7
;
	LD	L,A
	LD	(HL),B
	LD	A,C
	JR	NZ,J$AB89
;
J$AB89:	JR	NZ,J.ABD8
;
	LD	L,A
	HALT	
;
;	-----------------
?.AB8D:	LD	H,L
	JR	NZ,J$AB90
;
J$AB90:	JR	NZ,J.ABD8
;
	LD	L,C
	LD	L,(HL)
	LD	H,H
	JR	NZ,J$AB97
;
J$AB97:	JR	NZ,J$ABEB
;
	LD	H,L
	LD	(HL),B
	LD	L,H
	LD	H,C
	LD	H,E
	LD	H,L
	JR	NZ,J$ABA1
;
J$ABA1:	LD	B,(HL)
	LD	L,C
	LD	L,(HL)
	LD	H,H
	LD	A,(D$5200)
	LD	H,L
	LD	(HL),B
	LD	L,H
	LD	H,C
	LD	H,E
	LD	H,L
	JR	NZ,J$AC27
;
	LD	L,C
	LD	(HL),H
	LD	L,B
	LD	A,(D.1B00)
	LD	C,E
	LD	C,(HL)
	LD	H,L
J$ABB9:	LD	A,B
	LD	(HL),H
	JR	NZ,J$AC2C
;
	LD	H,E
	LD	H,E
J$ABBF:	LD	(HL),L
	LD	(HL),D
	LD	H,L
	LD	L,(HL)
	LD	H,E
	LD	H,L
	LD	A,(D$5201)
J$ABC7	EQU	$-1
	LD	BC,I.0145
	LD	D,H
	LD	BC,I.0155
	LD	D,D
	LD	BC,I$2C4E
	JR	NZ,J$AC26
;
	LD	(HL),L
	LD	L,C
	LD	(HL),H
J.ABD8:	LD	A,(D$4501)
	LD	BC,I.0153
	LD	B,E
	NOP	
	DEC	DE
	LD	C,E
	LD	C,A
	LD	(HL),L
	LD	(HL),H
	JR	NZ,J$AC56
;
	LD	H,(HL)
	JR	NZ,J.AC57
;
	LD	H,L
J$ABEB:	LD	L,L
	LD	L,A
	LD	(HL),D
	LD	A,C
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	C,C
	LD	H,A
	LD	L,(HL)
	LD	L,A
	LD	(HL),D
	LD	H,L
	JR	NZ,J$AC5E
;
	LD	H,C
	LD	(HL),E
	LD	H,L
	CCF	
	JR	NZ,J$AC29
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	JR	NZ,J$AC07
;
J$AC07:	DEC	DE
	LD	C,E
	LD	C,(HL)
	LD	L,A
	LD	(HL),H
	JR	NZ,J$AC74
;
	LD	L,A
	LD	(HL),L
	LD	L,(HL)
	LD	H,H
	LD	L,20H	; " "
	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$AC1C
;
	LD	B,L
J$AC1C:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$AC42
;
	NOP	
	DEC	DE
	LD	C,E
	LD	D,D
J$AC26:	LD	H,L
J$AC27:	LD	(HL),B
	LD	L,H
J$AC29:	LD	H,C
	LD	H,E
	LD	H,L
J$AC2C:	CCF	
	JR	NZ,J.AC57
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	C,(HL)
	LD	L,A
	JR	NZ,J$ACA7
;
	LD	H,L
	LD	L,L
	LD	L,A
	LD	(HL),D
	LD	A,C
	JR	NZ,J$ACB4
;
	LD	(HL),B
J$AC42:	LD	H,C
	LD	H,E
	LD	H,L
	LD	L,20H	; " "
	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$AC4F
;
	LD	B,L
J$AC4F:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$AC75
;
	NOP	
J$AC56:	DEC	DE
J.AC57:	LD	C,E
	LD	C,(HL)
	LD	L,A
	JR	NZ,J$ACC9
;
	LD	H,L
	LD	L,L
J$AC5E:	LD	L,A
	LD	(HL),D
	LD	A,C
	JR	NZ,J$ACD6
;
	LD	(HL),B
	LD	H,C
	LD	H,E
	LD	H,L
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	BC,I$0157
	LD	B,C
	LD	BC,I$0149
	LD	D,H
	NOP	
J$AC74:	DEC	DE
J$AC75:	LD	C,E
	LD	C,L
	LD	H,C
	LD	(HL),D
	LD	L,E
	LD	H,L
	LD	(HL),D
	JR	NZ,J$ACE3
;
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	B,D
	LD	L,H
	LD	L,A
	LD	H,E
	LD	L,E
	JR	NZ,J.ACF6
;
	LD	(HL),E
	JR	NZ,J$AD04
;
	LD	L,A
	LD	L,A
	JR	NZ,J.ACF6
;
	LD	L,C
	LD	H,A
	LD	L,00H
	JR	NZ,J$ACEC
;
	LD	B,L
	LD	D,E
	LD	D,H
	LD	C,A
	LD	D,D
	LD	B,L
	JR	NZ,J$ACA2
;
J$ACA2:	DEC	DE
	LD	C,E
	LD	C,(HL)
	LD	L,A
	JR	NZ,J$AD1C
J$ACA7	EQU	$-1
;
	LD	H,L
	LD	A,B
	LD	(HL),H
	JR	NZ,J$AD21
;
	LD	L,A
	JR	NZ,J$AD22
;
	LD	H,L
	LD	(HL),E
	LD	(HL),H
	LD	L,A
J$ACB4:	LD	(HL),D
	LD	H,L
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	B,E
	LD	H,C
	LD	L,(HL)
	DAA	
	LD	(HL),H
	JR	NZ,J$AD33
;
	LD	H,L
	LD	(HL),E
	LD	(HL),H
	LD	L,A
	LD	(HL),D
	LD	H,L
	LD	L,00H
J$ACC9:	DEC	DE
	LD	C,E
	LD	B,E
	LD	H,C
	LD	L,(HL)
	DAA	
	LD	(HL),H
	JR	NZ,J$AD35
;
	LD	L,A
	LD	(HL),B
	LD	A,C
	LD	L,00H
J$ACD6	EQU	$-1
	DEC	DE
	LD	C,E
	LD	B,E
	LD	H,C
	LD	L,(HL)
	DAA	
	LD	(HL),H
	JR	NZ,J$AD4D
;
	LD	L,A
	HALT	
;
;	-----------------
?.ACE2:	LD	H,L
J$ACE3:	LD	L,00H
	JR	NZ,J$AD07
;
	JR	NZ,J.AD09
;
	JR	NZ,J$AD0B
;
	JR	NZ,J$AD53
J$ACEC	EQU	$-1
;
	LD	(HL),D
	LD	H,L
	LD	H,L
	JR	NZ,J$ACF2
;
J$ACF2:	DEC	DE
	LD	E,C
	JR	NZ,J$AD36
;
J.ACF6:	JR	NZ,J$AD4B
;
	LD	B,E
	LD	D,D
	LD	B,L
	LD	B,L
	LD	C,(HL)
	JR	NZ,J$AD55
;
	LD	B,C
	LD	D,D
	LD	C,C
	LD	B,C
	LD	B,D
J$AD04:	LD	C,H
	LD	B,L
	LD	D,E
J$AD07:	JR	NZ,J.AD09
;
J.AD09:	DEC	DE
	LD	E,C
J$AD0B:	DEC	H
	CPL	
	LD	SP,D.202E
	LD	C,H
	LD	H,L
	LD	L,(HL)
	LD	H,A
	LD	(HL),H
	LD	L,B
	JR	NZ,J$AD87
;
	LD	H,(HL)
	JR	NZ,J$AD7F
;
	LD	L,C
J$AD1C:	LD	(HL),E
	LD	(HL),B
	LD	L,H
	LD	H,C
	LD	A,C
J$AD21:	LD	H,L
J$AD22:	LD	H,H
	JR	NZ,J$AD91
;
	LD	L,C
	LD	L,(HL)
	LD	H,L
	DEC	DE
	LD	E,C
	DEC	H
	LD	C,L
	JR	Z,J$AD5F
;
	DEC	A
	SCF	
	ADD	HL,SP
	INC	L
	LD	(D$373D),A
J$AD33	EQU	$-2
J$AD35:	SCF	
J$AD36:	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	DAA	
	CPL	
	LD	(D.202E),A
	LD	C,E
	LD	H,L
	LD	A,C
	LD	H,E
	LD	L,H
	LD	L,C
	LD	H,E
	LD	L,E
	DEC	DE
	LD	E,C
	DAA	
	LD	C,H
J$AD4B:	JR	Z,J$AD7E
;
J$AD4D:	DEC	A
	LD	C,A
	LD	C,(HL)
	INC	L
	LD	(D.4F3D),A
J$AD53	EQU	$-1
	LD	B,(HL)
J$AD55:	LD	B,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	ADD	HL,HL
	CPL	
	INC	SP
	LD	L,20H	; " "
J$AD5F:	LD	B,D
	LD	H,L
	LD	H,L
	LD	(HL),B
	JR	NZ,J$ADD8
;
	LD	L,A
	LD	(HL),L
	LD	L,(HL)
	LD	H,H
	DEC	DE
	LD	E,C
	ADD	HL,HL
	LD	C,H
	JR	Z,J$ADA0
;
	DEC	A
	LD	C,A
	LD	C,(HL)
	INC	L
	LD	(D.4F3D),A
	LD	B,(HL)
	LD	B,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	DEC	HL
	CPL	
J$AD7E:	INC	(HL)
J$AD7F:	LD	L,20H	; " "
	LD	B,E
	LD	L,A
	LD	L,H
	LD	L,A
	LD	(HL),L
	LD	(HL),D
J$AD87:	DEC	DE
	LD	E,C
	DEC	HL
	LD	B,B
	JR	Z,J$ADBE
;
	DEC	A
	LD	B,D
	LD	L,H
	LD	(HL),L
J$AD91:	LD	H,L
	INC	L
	LD	(D$423D),A
	LD	L,H
	LD	H,C
	LD	H,E
	LD	L,E
	INC	L
	INC	SP
	DEC	A
	LD	B,A
	LD	(HL),D
	LD	H,L
J$ADA0:	LD	H,L
	LD	L,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	DEC	(HL)
	CPL	
	LD	B,L
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$AE23
;
	LD	L,B
	LD	H,L
	JR	NZ,J$AE1C
;
	LD	(HL),H
	LD	H,L
	LD	L,L
	JR	NZ,J$AE26
;
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
	LD	(HL),D
	JR	Z,J$ADF0
J$ADBE	EQU	$-1
;
	DEC	L
	INC	(HL)
	DEC	SP
	JR	NZ,J$ADF4
;
	JR	NZ,J.AE2F
;
	LD	(HL),E
	JR	NZ,J$AE2A
;
	LD	L,H
	LD	L,H
	ADD	HL,HL
	JR	NZ,J.AE2F
;
	LD	L,(HL)
	LD	H,H
	JR	NZ,J$AE42
;
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$ADD9
;
J$ADD8:	LD	D,D
J$ADD9:	LD	BC,I.0145
	LD	D,H
	LD	BC,I.0155
	LD	D,D
	LD	BC,I.204E
	LD	A,(D.1B00)
	LD	E,C
	JR	NZ,J$AE2D
;
	JR	NZ,J$AE39
;
	LD	B,C
	LD	C,C
	LD	C,(HL)
	JR	NZ,J$AE3E
J$ADF0	EQU	$-1
;
	LD	B,L
	LD	C,(HL)
	LD	D,L
J$ADF4:	JR	NZ,J$ADF6
;
J$ADF6:	DEC	DE
	LD	E,C
	INC	H
	ADD	HL,SP
	LD	SP,D.202E
	LD	D,A
	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$AE7A
;
	LD	L,B
	LD	H,L
	JR	NZ,J$AE7E
;
	LD	H,L
	LD	A,B
	LD	(HL),H
	NOP	
	DEC	DE
	LD	E,C
	LD	H,39H	; "9"
	LD	(D.202E),A
	LD	D,B
	LD	(HL),D
	LD	L,C
	LD	L,(HL)
	LD	(HL),H
	LD	L,C
	LD	L,(HL)
J$AE1C:	LD	H,A
	JR	NZ,J$AE93
;
	LD	L,B
	LD	H,L
	JR	NZ,J$AE97
;
J$AE23:	LD	H,L
	LD	A,B
	LD	(HL),H
J$AE26:	NOP	
	DEC	DE
	LD	E,C
	JR	Z,J$AE64
J$AE2A	EQU	$-1
;
	INC	SP
	LD	L,20H	; " "
J$AE2D	EQU	$-1
	LD	C,H
J.AE2F:	LD	L,A
	LD	H,C
	LD	H,H
	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$AEAB
;
	LD	L,B
	LD	H,L
J$AE39:	JR	NZ,J$AEAF
;
	LD	H,L
	LD	A,B
	LD	(HL),H
J$AE3E:	JR	NZ,J$AEA6
;
	LD	(HL),D
	LD	L,A
J$AE42:	LD	L,L
	JR	NZ,J$AEB9
;
	LD	H,C
	LD	(HL),B
	LD	H,L
	CPL	
	LD	H,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	NOP	
	DEC	DE
	LD	E,C
	LD	HL,(D$3439)
	LD	L,20H	; " "
	LD	D,E
	LD	H,C
	HALT	
;
;	-----------------
?.AE58:	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$AED1
;
	LD	L,B
	LD	H,L
	JR	NZ,J$AED5
;
	LD	H,L
	LD	A,B
	LD	(HL),H
J$AE64:	JR	NZ,J$AEDA
;
	LD	L,A
	JR	NZ,J.AEDD
;
	LD	H,C
	LD	(HL),B
	LD	H,L
	CPL	
	LD	H,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	NOP	
	DEC	DE
	LD	E,C
	INC	L
	ADD	HL,SP
	DEC	(HL)
	LD	L,20H	; " "
	LD	D,H
J$AE7A:	LD	L,A
	JR	NZ,J$AEE2
;
	LD	(HL),D
J$AE7E:	LD	H,C
	LD	(HL),E
	LD	H,L
	JR	NZ,J$AEF7
;
	LD	H,L
	LD	A,B
	LD	(HL),H
	NOP	
	DEC	DE
	LD	E,C
	LD	L,39H	; "9"
	LD	(HL),2EH	; "."
	JR	NZ,J$AEDF
;
	LD	(HL),D
	LD	L,A
	LD	H,A
	LD	(HL),D
J$AE93:	LD	H,C
	LD	L,L
	JR	NZ,J$AF0D
;
J$AE97:	LD	H,C
	LD	(HL),D
	LD	L,C
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	LD	(HL),E
	NOP	
	DEC	DE
	LD	E,C
	JR	NC,J.AEDD
;
	SCF	
	LD	L,20H	; " "
J$AEA6	EQU	$-1
	LD	B,E
	LD	L,A
	LD	L,L
	LD	L,L
J$AEAB:	LD	(HL),L
	LD	L,(HL)
	LD	L,C
	LD	H,E
J$AEAF:	LD	H,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$AF2C
;
	LD	L,C
	LD	H,C
	JR	NZ,J$AF0C
J$AEB9	EQU	$-1
;
	LD	D,E
	DEC	L
	LD	(D.3233),A
	LD	B,E
	NOP	
	DEC	DE
	LD	E,C
	LD	(D$3839),A
	LD	L,20H	; " "
	LD	D,H
	LD	L,A
	JR	NZ,J$AF38
;
	LD	H,L
	LD	H,C
	HALT	
;
;	-----------------
?.AECF:	LD	H,L
	JR	NZ,J.AF46
J$AED1	EQU	$-1
;
	LD	L,B
	LD	H,L
	JR	NZ,J.AF46
J$AED5	EQU	$-1
;
	LD	(HL),D
	LD	L,A
	LD	H,A
	LD	(HL),D
J$AEDA:	LD	H,C
	LD	L,L
	NOP	
J.AEDD:	DEC	DE
	LD	E,C
J$AEDF:	DEC	(HL)
	ADD	HL,SP
	LD	B,L
J$AEE2:	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$AF5C
;
	LD	L,B
	LD	H,L
	JR	NZ,J$AF5F
;
	LD	H,L
	LD	H,E
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$AF62
;
	LD	(HL),L
	LD	L,L
	LD	H,D
J$AEF7:	LD	H,L
	LD	(HL),D
	LD	A,(D.1B00)
	LD	E,C
	JR	NZ,J$AF3D
;
	JR	NZ,J$AF55
;
	LD	C,A
	JR	NZ,J$AF50
;
	LD	B,L
	LD	B,C
	LD	D,(HL)
	LD	B,L
	JR	NZ,J.AF5E
;
	LD	C,B
	LD	B,L
J$AF0C:	JR	NZ,J.AF5E
J$AF0D	EQU	$-1
;
	LD	D,D
	LD	C,A
	LD	B,A
	LD	D,D
	LD	B,C
	LD	C,L
	JR	NZ,J$AF16
;
J$AF16:	DEC	DE
	LD	E,C
	DEC	HL
	LD	A,41H	; "A"
	LD	(HL),D
	LD	H,L
	JR	NZ,J$AF98
;
	LD	L,A
	LD	(HL),L
	JR	NZ,J$AF96
;
	LD	(HL),L
	LD	(HL),D
	LD	H,L
	CCF	
	JR	NZ,J$AF51
;
	LD	E,C
	CPL	
	LD	C,(HL)
J$AF2C:	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	JR	NZ,J$AF72
;
	JR	NZ,J$AF84
;
	LD	D,D
	LD	C,A
	LD	B,A
	LD	D,D
J$AF38:	LD	B,C
	LD	C,L
	JR	NZ,J.AF92
;
	LD	B,C
J$AF3D:	LD	D,D
	LD	C,C
	LD	B,C
	LD	B,D
	LD	C,H
	LD	B,L
	LD	D,E
	JR	NZ,J.AF46
;
J.AF46:	DEC	DE
	LD	E,C
	LD	H,3AH	; ":"
	LD	SP,D.202E
	LD	D,E
	LD	H,E
	LD	(HL),D
J$AF50:	LD	H,L
J$AF51:	LD	H,L
	LD	L,(HL)
	NOP	
	DEC	DE
J$AF55:	LD	E,C
	JR	Z,J.AF92
;
	LD	(D.202E),A
	LD	D,B
J$AF5C:	LD	(HL),D
	LD	L,C
J.AF5E:	LD	L,(HL)
J$AF5F:	LD	(HL),H
	LD	L,C
	LD	L,(HL)
J$AF62:	LD	H,A
	NOP	
	DEC	DE
	LD	E,C
	JR	NZ,J$AFA8
;
	JR	NZ,J$AFBA
;
	LD	D,D
	LD	C,C
	LD	C,(HL)
	LD	D,H
	LD	C,C
	LD	C,(HL)
	LD	B,A
	JR	NZ,J$AFC9
J$AF72	EQU	$-1
;
	LD	B,C
	LD	D,D
	LD	C,C
	LD	B,C
	LD	B,D
	LD	C,H
	LD	B,L
	LD	D,E
	JR	NZ,J$AF7D
;
J$AF7D:	DEC	DE
	LD	E,C
	JR	NZ,J$AFC0
;
	JR	NZ,J$AFD7
;
	LD	B,L
J$AF84:	LD	E,B
	LD	D,H
	JR	NZ,J$AFCD
;
	LD	D,D
	LD	B,C
	LD	D,E
	LD	D,L
	LD	D,D
	LD	B,L
	JR	NZ,J$AF90
;
J$AF90:	JR	NZ,J$AFE5
;
J.AF92:	LD	B,C
	LD	D,(HL)
	LD	B,L
	JR	NZ,J$AF97
J$AF96	EQU	$-1
;
J$AF97:	DEC	DE
J$AF98:	LD	C,E
	LD	SP,D.202E
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$AFC2
;
	JR	NZ,J$AFD6
;
	LD	L,20H	; " "
	LD	D,H
	LD	H,C
J$AFA8:	LD	(HL),B
	LD	H,L
	NOP	
	DEC	DE
	LD	C,E
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$B021
;
	LD	H,C
	LD	L,L
	LD	H,L
	LD	A,(D.1B00)
	LD	C,E
J$AFBA:	LD	D,A
	LD	L,B
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$B032
;
J$AFC0:	LD	H,L
	LD	H,C
J$AFC2:	LD	H,H
	LD	A,C
	INC	L
	JR	NZ,J$B037
;
	LD	(HL),D
	LD	H,L
J$AFC9:	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$AFCE
;
J$AFCD:	LD	D,D
J$AFCE:	LD	BC,I.0145
	LD	D,H
	LD	BC,I.0155
	LD	D,D
J$AFD6:	LD	BC,I.204E
J$AFD7	EQU	$-2
	NOP	
	DEC	DE
	LD	C,E
	LD	D,E
	LD	H,C
	HALT	
;
;	-----------------
?.AFDF:	LD	L,C
	LD	L,(HL)
	LD	H,A
	LD	L,2EH	; "."
	LD	L,00H
J$AFE5	EQU	$-1
	DEC	DE
	LD	C,E
	LD	D,(HL)
	LD	H,L
	LD	(HL),D
	LD	L,C
	LD	H,(HL)
	LD	A,C
	LD	L,C
	LD	L,(HL)
	LD	H,A
	LD	L,2EH	; "."
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	D,E
	LD	H,C
	HALT	
;
;	-----------------
?.AFFA:	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$B06E
;
	LD	(HL),B
	LD	H,L
	LD	(HL),D
	LD	H,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$B06C
;
	LD	L,A
	LD	L,L
	LD	(HL),B
	LD	L,H
	LD	H,L
	LD	(HL),H
	LD	H,L
	LD	H,H
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	D,(HL)
	LD	H,L
	LD	(HL),D
	LD	L,C
	LD	H,(HL)
	LD	A,C
	CCF	
	JR	NZ,J$B046
;
	LD	E,C
	CPL	
	LD	C,(HL)
J$B021:	ADD	HL,HL
	JR	NZ,J$B024
;
J$B024:	DEC	DE
	LD	C,E
	LD	D,E
	LD	H,C
	HALT	
;
;	-----------------
?.B029:	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$B093
;
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
J$B032:	INC	L
	JR	NZ,J$B085
;
	LD	(HL),D
	LD	H,L
J$B037:	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B03C
;
	LD	B,L
J$B03C:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$B062
;
	DEC	DE
	LD	C,E
	LD	B,C
	LD	H,D
J$B046:	LD	L,A
	LD	(HL),D
	LD	(HL),H
	LD	H,L
	LD	H,H
	LD	L,20H	; " "
	LD	D,D
	LD	H,L
	LD	(HL),H
	LD	(HL),L
	LD	(HL),D
	LD	L,(HL)
	JR	NZ,J$B0C9
;
	LD	L,A
	JR	NZ,J$B0C5
;
	LD	H,C
	LD	L,C
	LD	L,(HL)
	JR	NZ,J$B0CA
;
	LD	H,L
	LD	L,(HL)
	LD	(HL),L
	CCF	
	JR	NZ,J$B08B
J$B062	EQU	$-1
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	C,(HL)
	LD	L,A
J$B06C:	JR	NZ,J$B0E2
;
J$B06E:	LD	H,L
	LD	A,B
	LD	(HL),H
	LD	L,20H	; " "
	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B07B
;
	LD	B,L
J$B07B:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$B0A1
;
	NOP	
	DEC	DE
	LD	C,E
	LD	D,(HL)
J$B085:	LD	H,L
	LD	(HL),D
	LD	L,C
	LD	H,(HL)
	LD	A,C
	JR	NZ,J$B0F1
J$B08B	EQU	$-1
;
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
	LD	L,20H	; " "
	LD	D,D
J$B093:	LD	H,L
	LD	(HL),H
	LD	(HL),D
	LD	A,C
	CCF	
	JR	NZ,J$B0C2
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
J$B0A1:	LD	D,(HL)
	LD	H,L
	LD	(HL),D
	LD	L,C
	LD	H,(HL)
	LD	A,C
	JR	NZ,J$B0F8
;
	LD	C,E
	LD	L,20H	; " "
	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B0B4
;
	LD	B,L
J$B0B4:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$B0DA
;
	NOP	
	DEC	DE
	LD	C,E
	LD	D,H
	LD	L,A
	JR	NZ,J$B122
;
	LD	H,D
J$B0C2:	LD	L,A
	LD	(HL),D
	LD	(HL),H
J$B0C5:	INC	L
	JR	NZ,J$B138
;
	LD	(HL),D
J$B0C9:	LD	H,L
J$B0CA:	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B0CF
;
	LD	B,E
J$B0CF:	LD	BC,I.0154
	LD	D,D
	LD	BC,I$204C
	LD	H,C
	LD	L,(HL)
	LD	H,H
	JR	NZ,J$B0DC
J$B0DA	EQU	$-1
;
	LD	D,E
J$B0DC:	LD	BC,I.0154
	LD	C,A
	LD	BC,I$2050
J$B0E2	EQU	$-1
	NOP	
	DEC	DE
	LD	C,E
	LD	D,A
	LD	L,B
	LD	L,C
	LD	H,E
	LD	L,B
	JR	NZ,J$B15C
;
	LD	L,(HL)
	LD	H,L
	JR	NZ,J$B155
;
J$B0F1:	LD	L,A
	JR	NZ,J$B16D
;
	LD	L,A
	LD	(HL),L
	JR	NZ,J$B16F
;
J$B0F8:	LD	H,C
	LD	L,(HL)
	LD	(HL),H
	CCF	
	NOP	
	DEC	DE
	LD	C,E
	LD	B,H
	LD	L,A
	JR	NZ,J$B17C
;
	LD	L,A
	LD	(HL),L
	JR	NZ,J$B17E
;
	LD	H,C
	LD	L,(HL)
	LD	(HL),H
	JR	NZ,J$B172
;
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$B175
;
	LD	L,C
	LD	(HL),D
	LD	H,L
	LD	H,E
	LD	(HL),H
	LD	L,A
	LD	(HL),D
	LD	A,C
	CCF	
	JR	NZ,J$B144
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
J$B122:	LD	C,E
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$B18E
;
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
	LD	L,20H	; " "
	LD	D,D
	LD	H,L
	LD	(HL),H
	LD	(HL),D
	LD	A,C
	CCF	
	JR	NZ,J$B15F
;
	LD	E,C
J$B138:	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	B,H
	LD	L,C
	LD	(HL),D
	LD	H,L
	LD	H,E
	LD	(HL),H
J$B144:	LD	L,A
	LD	(HL),D
	LD	A,C
	JR	NZ,J.B1B2
;
	LD	(HL),E
	JR	NZ,J.B1B2
;
	LD	(HL),L
	LD	L,H
	LD	L,H
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	B,(HL)
	LD	L,C
J$B155:	LD	L,H
	LD	H,L
	JR	NZ,J$B1BA
;
	LD	L,H
	LD	(HL),D
	LD	H,L
J$B15C:	LD	H,C
	LD	H,H
	LD	A,C
J$B15F:	JR	NZ,J$B1C6
;
	LD	A,B
	LD	L,C
	LD	(HL),E
	LD	(HL),H
	LD	(HL),E
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	B,L
	LD	(HL),D
	LD	H,C
J$B16D:	LD	(HL),E
	LD	H,L
J$B16F:	JR	NZ,J$B1E0
;
	LD	L,H
J$B172:	LD	H,H
	JR	NZ,J$B1DB
;
J$B175:	LD	L,C
	LD	L,H
	LD	H,L
	CCF	
	JR	NZ,J$B1A3
;
	LD	E,C
J$B17C:	CPL	
	LD	C,(HL)
J$B17E:	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	D,E
	LD	H,C
	HALT	
;
;	-----------------
?.B185:	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$B1F9
;
	LD	(HL),B
	LD	H,L
	LD	(HL),D
	LD	H,C
J$B18E:	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$B1F7
;
	LD	L,A
	LD	L,L
	LD	(HL),B
	LD	L,H
	LD	H,L
	LD	(HL),H
	LD	H,L
	LD	H,H
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	D,B
	LD	(HL),D
	LD	H,L
J$B1A3:	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B1A8
;
	LD	B,L
J$B1A8:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$B1CE
;
	NOP	
	JR	NZ,J$B1FD
;
	LD	C,A
J.B1B2:	LD	B,C
	LD	B,H
	JR	NZ,J$B1B6
;
J$B1B6:	DEC	DE
	LD	C,E
	LD	D,H
	LD	H,L
J$B1BA:	LD	A,B
	LD	(HL),H
	JR	NZ,J$B21F
;
	LD	L,H
	LD	(HL),D
	LD	H,L
	LD	H,C
	LD	H,H
	LD	A,C
	JR	NZ,J$B22B
;
J$B1C6:	LD	A,B
	LD	L,C
	LD	(HL),E
	LD	(HL),H
	LD	(HL),E
	LD	L,00H
	DEC	DE
J$B1CE:	LD	C,E
	LD	C,H
	LD	L,A
	LD	H,C
	LD	H,H
	JR	NZ,J$B243
;
	LD	H,L
	LD	(HL),A
	JR	NZ,J$B24D
;
	LD	H,L
	LD	A,B
J$B1DB:	LD	(HL),H
	CCF	
	JR	NZ,J$B207
;
	LD	E,C
J$B1E0:	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$B25A
;
	LD	H,C
	LD	L,L
	LD	H,L
	LD	A,(X.0020)
	DEC	DE
	LD	C,E
	LD	C,H
	LD	L,A
	LD	H,C
J$B1F7:	LD	H,H
	LD	L,C
J$B1F9:	LD	L,(HL)
	LD	H,A
	LD	L,2EH	; "."
J$B1FD:	LD	L,00H
	DEC	DE
	LD	C,E
	LD	C,H
	LD	L,A
	LD	H,C
	LD	H,H
	LD	L,C
	LD	L,(HL)
J$B207:	LD	H,A
	JR	NZ,J$B26F
;
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
	LD	L,20H	; " "
	LD	D,D
	LD	H,L
	LD	(HL),H
	LD	(HL),D
	LD	A,C
	JR	NZ,J$B23F
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	C,H
J$B21F:	LD	L,A
	LD	H,C
	LD	H,H
	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$B296
;
	LD	(HL),B
	LD	H,L
	LD	(HL),D
	LD	H,C
J$B22B:	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$B294
;
	LD	L,A
	LD	L,L
	LD	(HL),B
	LD	L,H
	LD	H,L
	LD	(HL),H
	LD	H,L
	LD	H,H
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	C,(HL)
	LD	L,A
J$B23F:	JR	NZ,J$B2B4
;
	LD	(HL),B
	LD	H,C
J$B243:	LD	H,E
	LD	H,L
	JR	NZ,J$B2BB
;
	LD	L,A
	JR	NZ,J$B2B6
;
	LD	L,A
	LD	H,C
	LD	H,H
J$B24D:	JR	NZ,J$B2C3
;
	LD	L,B
	LD	L,C
	LD	(HL),E
	JR	NZ,J$B2BA
;
	LD	L,C
	LD	L,H
	LD	H,L
	LD	L,00H
	DEC	DE
J$B25A:	LD	C,E
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$B2CF
;
	LD	L,A
	LD	(HL),H
	JR	NZ,J$B2CB
;
	LD	L,A
	LD	(HL),L
	LD	L,(HL)
	LD	H,H
	LD	L,00H
	DEC	DE
	LD	C,E
	LD	C,H
	LD	L,A
J$B26F:	LD	H,C
	LD	H,H
	JR	NZ,J$B2E2
;
	LD	(HL),H
	LD	L,B
	LD	H,L
	LD	(HL),D
	JR	NZ,J$B2DF
;
	LD	L,C
	LD	L,H
	LD	H,L
	CCF	
	JR	NZ,J$B2A7
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	JR	NZ,J$B2DA
;
	LD	B,C
	LD	D,B
	LD	B,L
	JR	NZ,J$B28B
;
J$B28B:	DEC	DE
	LD	C,E
	LD	B,(HL)
	LD	L,A
	LD	(HL),L
	LD	L,(HL)
	LD	H,H
	LD	A,(D.1B00)
J$B294	EQU	$-1
	LD	C,E
J$B296:	LD	D,E
	LD	L,E
	LD	L,C
	LD	(HL),B
	JR	NZ,J$B2D6
;
	NOP	
	JR	NZ,J$B2E3
;
	LD	C,C
	LD	D,E
	LD	C,E
	JR	NZ,J$B2A4
;
J$B2A4:	JR	NZ,J$B2EA
;
	LD	C,C
J$B2A7:	LD	D,D
	LD	B,L
	LD	B,E
	LD	D,H
	LD	C,A
	LD	D,D
	LD	E,C
	JR	NZ,J$B2B0
;
J$B2B0:	DEC	DE
	LD	C,E
	LD	C,(HL)
	LD	L,A
J$B2B4:	JR	NZ,J$B32A
;
J$B2B6:	LD	H,L
	LD	A,B
	LD	(HL),H
	JR	NZ,J$B321
J$B2BA	EQU	$-1
;
J$B2BB:	LD	L,C
	LD	L,H
	LD	H,L
	LD	L,20H	; " "
	LD	D,B
	LD	(HL),D
	LD	H,L
J$B2C3:	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B2C8
;
	LD	B,L
J$B2C8:	LD	BC,I.0153
J$B2CB:	LD	B,E
	JR	NZ,J$B2EE
;
	NOP	
J$B2CF:	DEC	DE
	LD	C,E
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	(HL),B
	LD	L,H
J$B2D6:	LD	H,C
	LD	A,C
	JR	NZ,J$B34C
;
J$B2DA:	LD	H,L
	LD	(HL),E
	LD	(HL),H
	CCF	
	JR	NZ,J$B308
J$B2DF	EQU	$-1
;
	LD	E,C
	CPL	
J$B2E2:	LD	C,(HL)
J$B2E3:	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	D,H
	LD	L,A
	LD	(HL),H
J$B2EA:	LD	H,C
	LD	L,H
	JR	NZ,J$B30E
;
J$B2EE:	JR	NZ,J$B310
;
	JR	NZ,J$B358
;
	LD	L,C
	LD	L,H
	LD	H,L
	JR	Z,J$B36A
;
	ADD	HL,HL
	LD	L,20H	; " "
	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B302
;
	LD	B,L
J$B302:	LD	BC,I.0153
	LD	B,E
	JR	NZ,J$B328
;
J$B308:	NOP	
	JR	NZ,J$B35B
;
	LD	D,D
	LD	C,C
	LD	C,(HL)
J$B30E:	LD	D,H
	JR	NZ,J$B311
J$B310	EQU	$-1
;
J$B311:	DEC	DE
	LD	E,C
	LD	(D.1B2F),HL
	LD	C,E
	LD	SP,D.202E
	LD	C,(HL)
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
	LD	(HL),D
	JR	NZ,J.B391
J$B321	EQU	$-1
;
	LD	H,(HL)
	JR	NZ,J.B391
;
	LD	L,C
	LD	L,(HL)
	LD	H,L
J$B328:	LD	(HL),E
	JR	NZ,J$B39B
J$B32A	EQU	$-1
;
	LD	H,L
	LD	(HL),D
	JR	NZ,J$B39F
;
	LD	H,C
	LD	H,A
	LD	H,L
	DEC	DE
	LD	E,C
	LD	(D$1B50),HL
	LD	C,E
	JR	Z,J$B36C
;
	JR	NC,J$B369
;
	LD	SP,I$3231
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	INC	H
	CPL	
	DEC	DE
	LD	C,E
	LD	(D.202E),A
	LD	D,H
	LD	L,A
J$B34C:	LD	(HL),B
	JR	NZ,J$B3BC
;
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	L,C
	LD	L,(HL)
	DEC	DE
	LD	E,C
	INC	H
	LD	D,D
J$B358:	DEC	DE
	LD	C,E
	JR	Z,J$B38F
J$B35B	EQU	$-1
;
	DEC	L
	LD	(D.2930),A
	NOP	
	DEC	DE
	LD	E,C
	LD	H,2FH	; "/"
	DEC	DE
	LD	C,E
	INC	SP
	LD	L,20H	; " "
J$B369	EQU	$-1
J$B36A:	LD	B,D
	LD	L,A
J$B36C:	LD	(HL),H
	LD	(HL),H
	LD	L,A
	LD	L,L
	JR	NZ,J$B3DF
;
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	L,C
	LD	L,(HL)
	DEC	DE
	LD	E,C
	LD	H,52H	; "R"
	DEC	DE
	LD	C,E
	JR	Z,J$B3B2
;
	DEC	L
	LD	(D.2930),A
	NOP	
	DEC	DE
	LD	E,C
	JR	Z,J$B3B7
;
	DEC	DE
	LD	C,E
	INC	(HL)
	LD	L,20H	; " "
	LD	C,H
	LD	H,L
J$B38F:	LD	H,(HL)
	LD	(HL),H
J.B391:	JR	NZ,J$B400
;
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	L,C
	LD	L,(HL)
	DEC	DE
	LD	E,C
	JR	Z,J$B3EE
J$B39B	EQU	$-1
;
	DEC	DE
	LD	C,E
	JR	Z,J$B3D0
J$B39F	EQU	$-1
;
	DEC	L
	ADD	HL,SP
	ADD	HL,SP
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	LD	HL,(D.1B2F)
	LD	C,E
	DEC	(HL)
	LD	L,20H	; " "
	LD	C,B
	LD	H,L
	LD	H,C
	LD	H,H
J$B3B2:	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$B424
;
J$B3B7:	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	L,C
	LD	L,(HL)
J$B3BC:	DEC	DE
	LD	E,C
	LD	HL,(D$1B52)
	LD	C,E
	JR	Z,J$B3F5
;
	DEC	L
	LD	SP,I$2938
	NOP	
	DEC	DE
	LD	E,C
	INC	L
	CPL	
	DEC	DE
	LD	C,E
	LD	(HL),2EH	; "."
J$B3D0	EQU	$-1
	JR	NZ,J$B416
;
	LD	L,B
	LD	H,C
	LD	(HL),D
	LD	H,C
	LD	H,E
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J.B44D
;
	LD	H,L
	LD	(HL),D
J$B3DF:	JR	NZ,J.B44D
;
	LD	L,C
	LD	L,(HL)
	LD	H,L
	DEC	DE
	LD	E,C
	INC	L
	LD	D,B
	DEC	DE
	LD	C,E
	JR	Z,J$B41F
;
	DEC	(HL)
	DEC	L
J$B3EE:	LD	SP,D.3233
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
J$B3F5:	LD	L,2FH	; "/"
	DEC	DE
	LD	C,E
	SCF	
	LD	L,20H	; " "
	LD	C,H
	LD	L,C
	LD	L,(HL)
	LD	H,L
J$B400:	JR	NZ,J.B475
;
	LD	(HL),B
	LD	H,C
	LD	H,E
	LD	L,C
	LD	L,(HL)
	LD	H,A
	DEC	DE
	LD	E,C
	LD	L,53H	; "S"
	DEC	DE
	LD	C,E
	JR	Z,J$B441
;
	DEC	L
	INC	SP
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
J$B416:	JR	NC,J$B447
;
	DEC	DE
	LD	C,E
	JR	C,J$B44A
;
	JR	NZ,J.B475
;
	LD	L,A
J$B41F:	LD	(HL),D
	LD	H,H
	JR	NZ,J$B49A
;
	LD	(HL),D
J$B424:	LD	H,C
	LD	(HL),B
	DEC	DE
	LD	E,C
	JR	NC,J$B47D
;
	DEC	DE
	LD	C,E
	JR	Z,J$B487
;
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	E,C
	LD	(D.1B2F),A
	LD	C,E
	ADD	HL,SP
	LD	L,20H	; " "
	LD	C,D
	LD	(HL),L
	LD	(HL),E
	LD	(HL),H
	LD	L,C
	LD	H,(HL)
J$B441:	LD	L,C
	LD	H,E
	LD	H,C
	LD	(HL),H
	LD	L,C
	LD	L,A
J$B447:	LD	L,(HL)
	DEC	DE
	LD	E,C
J$B44A:	LD	(D$1B53),A
J.B44D:	LD	C,E
	JR	Z,J$B4A9
;
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	B,E
	LD	L,B
	LD	H,C
	LD	L,(HL)
	LD	H,A
	LD	H,L
	JR	NZ,J$B4D2
;
	LD	L,B
	LD	H,L
	LD	(HL),E
	LD	H,L
	JR	NZ,J$B4DA
;
	LD	H,C
	LD	L,H
	LD	(HL),L
	LD	H,L
	LD	(HL),E
	CCF	
	JR	NZ,J$B494
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	B,L
	LD	L,(HL)
J.B475:	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$B4EE
;
	LD	L,B
	LD	H,L
	JR	NZ,J$B4E7
J$B47D	EQU	$-1
;
	LD	(HL),H
	LD	H,L
	LD	L,L
	JR	NZ,J$B4F1
;
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
J$B487:	LD	(HL),D
	JR	Z,J$B4BA
;
	DEC	L
	ADD	HL,SP
	DEC	SP
	JR	NZ,J$B4BF
;
	JR	NZ,J.B4FA
;
	LD	(HL),E
	JR	NZ,J$B4F5
;
J$B494:	LD	L,H
	LD	L,H
	ADD	HL,HL
	JR	NZ,J.B4FA
;
	LD	L,(HL)
J$B49A:	LD	H,H
	JR	NZ,J$B50D
;
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B4A4
;
	LD	D,D
J$B4A4:	LD	BC,I.0145
	LD	D,H
	LD	BC,I.0155
J$B4A9	EQU	$-2
	LD	D,D
	LD	BC,I.204E
	LD	A,(D.1B00)
	LD	C,E
	LD	C,A
	LD	(HL),L
	LD	(HL),H
	JR	NZ,J$B527
;
	LD	H,(HL)
	JR	NZ,J$B52D
J$B4BA	EQU	$-1
;
	LD	H,C
	LD	L,(HL)
	LD	H,A
	LD	H,L
J$B4BF:	NOP	
	DEC	DE
	LD	C,E
	LD	C,C
	LD	(HL),E
	JR	NZ,J$B53A
;
	LD	L,B
	LD	L,C
	LD	(HL),E
	JR	NZ,J$B52C
;
	JR	NZ,J.B530
;
	LD	L,A
	LD	L,(HL)
	LD	(HL),H
	LD	L,C
	LD	L,(HL)
J$B4D2:	LD	(HL),L
	LD	H,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$B549
;
J$B4DA:	LD	H,(HL)
	JR	NZ,J.B551
;
	LD	L,B
	LD	H,L
	JR	NZ,J.B551
;
	LD	(HL),D
	LD	H,L
	HALT	
;
;	-----------------
?.B4E4:	LD	L,C
	LD	L,A
	LD	(HL),L
J$B4E7:	LD	(HL),E
	JR	NZ,J$B550
;
	LD	L,C
	LD	L,H
	LD	H,L
	CCF	
J$B4EE:	JR	NZ,J$B518
;
	LD	E,C
J$B4F1:	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
J$B4F5:	DEC	DE
	LD	C,E
	LD	D,B
	LD	H,C
	LD	H,A
J.B4FA:	LD	H,L
	JR	NZ,J$B56B
;
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
	LD	(HL),D
	LD	L,C
	LD	L,(HL)
	LD	H,A
	CCF	
	JR	NZ,J.B530
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
J$B50D:	DEC	DE
	LD	C,E
	LD	D,E
	LD	(HL),H
	LD	H,C
	LD	(HL),D
	LD	(HL),H
	JR	NZ,J$B577
;
	LD	(HL),H
	JR	NZ,J.B589
J$B518	EQU	$-1
;
	LD	H,C
	LD	H,A
	LD	H,L
	JR	NZ,J$B58C
;
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
	LD	(HL),D
	CCF	
	NOP	
	DEC	DE
	LD	C,E
J$B527:	LD	C,(HL)
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
J$B52C:	LD	(HL),D
J$B52D:	LD	L,C
	LD	L,(HL)
	LD	H,A
J.B530:	JR	NZ,J$B593
;
	LD	(HL),H
	JR	NZ,J$B5A9
;
	LD	L,A
	LD	(HL),B
	JR	NZ,J$B5A8
;
	LD	(HL),D
J$B53A:	JR	NZ,J$B59E
;
	LD	L,A
	LD	(HL),H
	LD	(HL),H
	LD	L,A
	LD	L,L
	CCF	
	JR	NZ,J$B56C
;
	LD	D,H
	CPL	
	LD	B,D
	ADD	HL,HL
	NOP	
J$B549:	DEC	DE
	LD	C,E
	LD	D,B
	LD	H,C
	LD	(HL),L
	LD	(HL),E
	LD	H,L
J$B550:	JR	NZ,J$B5B4
J.B551	EQU	$-1
;
	LD	H,L
	LD	(HL),H
	LD	(HL),A
	LD	H,L
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$B5CA
;
	LD	H,C
	LD	H,A
	LD	H,L
	LD	(HL),E
	CCF	
	JR	NZ,J.B589
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	B,L
	LD	L,D
	LD	H,L
J$B56B:	LD	H,E
J$B56C:	LD	(HL),H
	JR	NZ,J$B5DB
;
	LD	H,C
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J$B5E4
;
	LD	H,C
	LD	H,A
	LD	H,L
J$B577:	CCF	
	JR	NZ,J$B5A2
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	D,B
	LD	(HL),D
	LD	L,C
	LD	L,(HL)
	LD	(HL),H
	JR	NZ,J$B5F8
;
	LD	H,C
J.B589:	LD	H,A
	LD	H,L
	JR	NZ,J$B5F5
J$B58C	EQU	$-1
;
	LD	H,L
	LD	H,C
	LD	H,H
	LD	L,C
	LD	L,(HL)
	LD	H,A
J$B593:	CCF	
	JR	NZ,J$B5BE
;
	LD	E,C
	CPL	
	LD	C,(HL)
	ADD	HL,HL
	NOP	
	DEC	DE
	LD	C,E
	LD	D,H
J$B59E:	LD	A,C
	LD	(HL),B
	LD	H,L
	JR	NZ,J$B60C
J$B5A2	EQU	$-1
;
	LD	L,(HL)
	JR	NZ,J$B616
;
	LD	H,C
	LD	H,A
J$B5A8:	LD	H,L
J$B5A9:	JR	NZ,J$B613
;
	LD	H,L
	LD	H,C
	LD	H,H
	LD	L,C
	LD	L,(HL)
	LD	H,A
	LD	A,(D.1B00)
J$B5B4:	LD	C,E
	LD	D,B
	LD	(HL),D
	LD	L,C
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$B627
;
J$B5BE:	LD	(HL),E
	JR	NZ,J$B633
;
	LD	H,L
	LD	H,C
	LD	H,H
	LD	A,C
	INC	L
	JR	NZ,J$B638
;
	LD	(HL),D
	LD	H,L
J$B5CA:	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$B5CF
;
	LD	D,D
J$B5CF:	LD	BC,I.0145
	LD	D,H
	LD	BC,I.0152
	LD	C,(HL)
	JR	NZ,J$B5F9
;
	NOP	
	DEC	DE
J$B5DB:	LD	C,E
	LD	B,H
	LD	L,A
	JR	NZ,J$B659
;
	LD	L,A
	LD	(HL),L
	JR	NZ,J$B65B
;
J$B5E4:	LD	H,C
	LD	L,(HL)
	LD	(HL),H
	JR	NZ,J$B65D
;
	LD	L,A
	JR	NZ,J$B65F
;
	LD	H,C
	HALT	
;
;	-----------------
?.B5EE:	LD	H,L
	JR	NZ,J$B665
;
	LD	L,B
	LD	H,L
	LD	(HL),E
	LD	H,L
J$B5F5:	JR	NZ,J$B65A
;
	LD	L,B
J$B5F8:	LD	H,C
J$B5F9:	LD	L,(HL)
	LD	H,A
	LD	H,L
	LD	H,H
	JR	NZ,J$B675
;
	LD	H,C
	LD	(HL),D
	LD	L,C
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	LD	(HL),E
	JR	NZ,J$B67D
;
	LD	L,A
	JR	NZ,J$B670
;
J$B60C:	LD	L,C
	LD	(HL),E
	LD	L,E
	CCF	
	JR	NZ,J$B63A
;
	LD	E,C
J$B613:	CPL	
	LD	C,(HL)
	ADD	HL,HL
J$B616:	DEFB	0,0
	LD	(D.D380),HL
	LD	(D.D382),DE
	LD	(D.D3C7),BC
	XOR	A
	LD	(D.D3E7),A
J$B627:	 CALL	C.00C3
;
	 CALL	C$B726
;
	JR	NZ,J$B642
;
	 CALL	C.B95A
;
	INC	BC
J$B633:	LD	B,41H	; "A"
	CP	D
	 CALL	C.B7A0
J$B638	EQU	$-1
;
J.B639:	XOR	A
J$B63A:	 CALL	C.00C3
;
	 CALL	C.0156
;
	JR	J$B661
;
;	-----------------
J$B642:	 CALL	C$B90A
;
	JR	C,J.B639
;
	 CALL	C.B6FB
;
	JR	C,J.B639
;
	JR	NZ,J$B669
;
J$B64E:	 CALL	C.B75F
;
	JR	NC,J$B658
;
	 CALL	C.B778
;
	JR	J$B64E
;
;	-----------------
J$B658:	 CALL	C.B6DD
J$B659	EQU	$-2
J$B65A	EQU	$-1
;
J$B65B:	 CALL	C$BCCA
J$B65D	EQU	$-1
;
	 CALL	C$BBCF
J$B65F	EQU	$-2
;
J$B661:	LD	DE,(D.D382)
J$B665:	LD	A,(D.D3E7)
	RET	
;
;	-----------------
J$B669:	PUSH	AF
	 CALL	C.B6DD
;
	 CALL	C.BDA9
;
J$B670:	 CALL	C$B78A
;
	JR	C,J$B6D6
;
J$B675:	LD	A,1BH
	 CALL	C.00A2
;
	LD	A,6CH	; "l"
	 CALL	C.00A2
J$B67D	EQU	$-2
;
	 CALL	C.B75F
;
	POP	AF
	INC	A
	JR	NZ,J$B6C1
;
	LD	DE,J.BAA9
	 CALL	C.B969
;
	LD	A,04H	; 4 
	LD	(D.D3E7),A
	 CALL	C.BDCC
;
	LD	HL,C.0000
J$B697:	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J$B697
;
	 CALL	C.B7D7
;
J.B69F:	PUSH	AF
	 CALL	C$BD9B
;
	 CALL	C.BDA9
;
	POP	AF
	JR	C,J$B6B4
;
	JR	Z,J$B6B9
;
	LD	DE,I$BB35
	 CALL	C.B969
;
J$B6B1:	 CALL	C$B79A
;
J$B6B4:	 CALL	C.B778
;
	JR	J$B6D7
;
;	-----------------
J$B6B9:	LD	DE,I$BB54
	 CALL	C.B969
;
	JR	J$B6B1
;
;	-----------------
J$B6C1:	 CALL	C.B75F
;
	LD	DE,I$BA89
	 CALL	C.B969
;
	 CALL	C.BDCC
;
	 CALL	C.B85D
;
	JR	C,J.B69F
;
	OR	0FFH
	JR	J.B69F
;
;	-----------------
J$B6D6:	POP	AF
J$B6D7:	 CALL	C$BC46
;
	JP	J.B639
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B6DD:	LD	HL,I$0101
	LD	(D.D3E2),HL
	LD	(D.D3E4),HL
	 CALL	C.00C6
;
	 CALL	C.BDA9
;
	XOR	A
	 CALL	C.00C3
;
	 CALL	C.BDCC
;
	XOR	A
	LD	(D.D3DE),A
	 CALL	C.00C3
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B6FB:	LD	A,(D.D3DF)
	OR	A
	RET	Z
;
	XOR	A
	 CALL	C.00C3
;
	 CALL	C.B95A
;
	INC	BC
	LD	B,0B7H
	CP	D
	LD	BC,I$3133
	 CALL	C.B7A9
;
	RET	C
;
	JR	Z,C.B6FB
;
	 CALL	C.00A2
;
	LD	D,A
	LD	BC,I.0D0D
	 CALL	C.B7A9
;
	RET	C
;
	JR	Z,C.B6FB
;
	LD	A,D
	SUB	33H	; "3"
	OR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B726:	LD	HL,I$D3CB
	PUSH	HL
	LD	B,06H	; 6 
J$B72C:	LD	(HL),00H
	INC	HL
	DJNZ	J$B72C
;
	POP	HL
	LD	A,(D$FB20)
	BIT	0,A
	JR	Z,J$B744
;
	PUSH	HL
	LD	B,83H
	LD	DE,I.0800
	 CALL	C$FFCA
;
	EI	
	POP	HL
J$B744:	LD	A,(HL)
	OR	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B747:	LD	B,83H
	LD	HL,I.D3CE
	LD	IY,(D.D3CA)
	LD	IX,(D.D3CC)
	INC	IX
	INC	IX
	INC	IX
	 CALL	C.001C
;
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B75F:	LD	IY,(D.D3CA)
	LD	IX,(D.D3CC)
	LD	BC,CPMADR
	ADD	IX,BC
	LD	HL,(D$F862)
	LD	E,04H	; 4 
	LD	C,78H	; "x"
	 CALL	C.001C
;
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B778:	LD	IY,(D.D3CA)
	LD	IX,(D.D3CC)
	LD	BC,I.0012
	ADD	IX,BC
	 CALL	C.001C
;
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B78A:	LD	DE,I$BB78
	 CALL	C.B969
;
J$B790:	LD	BC,I.0D0D
	 CALL	C.B7A9
;
	RET	C
;
	JR	Z,J$B790
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B79A:	LD	DE,I$BA65
	 CALL	C.B969
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B7A0:	LD	BC,I$3035
	 CALL	C.B7A9
;
	JR	NC,C.B7A0
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B7A9:	 CALL	C.BE07
;
	LD	E,01H	; 1 
	LD	HL,I.0F00
J$B7B1:	 CALL	C$BDF6
;
	 CALL	C.009C
;
	JR	Z,J$B7B1
;
	 CALL	C.009F
;
	CP	1BH
	JR	Z,J$B7D0
;
	CP	B
	JR	C,J.B7CB
;
	INC	C
	CP	C
	JR	NC,J.B7CB
;
	DEC	C
	OR	A
	JR	J.B7D1
;
;	-----------------
J.B7CB:	LD	E,A
	XOR	A
	LD	A,E
	JR	J.B7D1
;
;	-----------------
J$B7D0:	SCF	
J.B7D1:	PUSH	AF
	 CALL	C.BE02
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B7D7:	 CALL	C.BCF7
;
	LD	IY,(D.D3CA)
	LD	IX,(D.D3CC)
	LD	DE,I.000F
	ADD	IX,DE
	LD	HL,(D.D380)
	LD	DE,(D.D382)
	PUSH	DE
	PUSH	IX
	PUSH	IY
	 CALL	C.B82A
;
	POP	IY
	POP	IX
	POP	DE
	EX	DE,HL
	OR	A
	JR	Z,J$B823
;
	SBC	HL,DE
	INC	HL
	PUSH	HL
	POP	BC
	EX	DE,HL
J$B805:	PUSH	HL
	PUSH	BC
	PUSH	IX
	PUSH	IY
	 CALL	C.B82A
;
	 CALL	C.00A2
;
	 CALL	C.001C
;
	POP	IY
	POP	IX
	POP	BC
	POP	HL
	EI	
	RET	C
;
	RET	Z
;
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$B805
;
J$B823:	LD	A,1AH
	 CALL	C.001C
;
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B82A:	LD	A,H
	CP	0C0H
	JR	NC,J$B836
;
	LD	A,83H
	 CALL	C.000C
;
	EI	
	RET	
;
;	-----------------
J$B836:	LD	A,(HL)
	RET	
;
;	-----------------
?.B838:	 CALL	C$BE67
;
	 CALL	C.BDA9
;
	 CALL	C.B7D7
;
	 CALL	C.BCEA
;
	 CALL	C.BE5F
;
	LD	A,04H	; 4 
	LD	(D.D3E7),A
	RET	
;
;	-----------------
?.B84D:	 CALL	C$BE5A
;
	 CALL	C.BDCC
;
	 CALL	C.B85D
;
	 CALL	C.BCEA
;
	 CALL	C.BE52
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B85D:	 CALL	C.BCF7
;
	LD	DE,(D.D380)
	LD	HL,(D.D3C7)
	LD	A,(D.D3DF)
	OR	A
	JR	NZ,J.B879
;
	LD	A,(D.D3E7)
	CP	02H	; 2 
	JR	NZ,J.B879
;
	LD	DE,(D.D382)
	INC	DE
J.B879:	OR	A
	SBC	HL,DE
	PUSH	HL
	POP	BC
	LD	A,C
	OR	B
	JR	Z,J$B89E
;
	EX	DE,HL
	 CALL	C.B89F
;
	PUSH	AF
	PUSH	HL
	LD	DE,(D.D380)
	OR	A
	SBC	HL,DE
	POP	HL
	JR	Z,J$B89D
;
	LD	(HL),00H
	DEC	HL
	LD	(D.D382),HL
	LD	A,02H	; 2 
	LD	(D.D3E7),A
J$B89D:	POP	AF
J$B89E:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B89F:	PUSH	HL
	PUSH	BC
	 CALL	C.BE7E
;
	POP	BC
	POP	HL
	PUSH	AF
	POP	DE
	BIT	7,E
	JR	NZ,J$B8D3
;
	CP	1AH
	JR	Z,J.B8D1
;
	OR	A
	JR	Z,J.B8D1
;
J$B8B3:	 CALL	C$B8F6
;
	INC	HL
	CP	20H	; " "
	JR	NC,J.B8C5
;
	CP	0DH	; 13 
	JR	Z,J.B8C5
;
	CP	0AH	; 10 
	JR	Z,J.B8C5
;
	LD	A,20H	; " "
J.B8C5:	 CALL	C.00A2
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,C.B89F
;
	OR	0FFH
	JR	J.B8D2
;
;	-----------------
J.B8D1:	XOR	A
J.B8D2:	RET	
;
;	-----------------
J$B8D3:	PUSH	BC
	PUSH	HL
	LD	IX,(D.D3CC)
	LD	IY,(D.D3CA)
	LD	DE,I$0009
	ADD	IX,DE
	 CALL	C.001C
;
	EI	
	LD	A,H
	AND	38H	; "8"
	JR	Z,J$B8F1
;
	POP	HL
	POP	BC
	LD	A,20H	; " "
	JR	J$B8B3
;
;	-----------------
J$B8F1:	POP	HL
	POP	BC
	SCF	
	JR	J.B8D2
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B8F6:	PUSH	AF
	LD	E,A
	LD	A,H
	CP	0C0H
	JR	NC,J$B907
;
	PUSH	BC
	LD	A,83H
	 CALL	C.0014
;
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
J$B907:	LD	(HL),E
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B90A:	LD	A,0FFH
	LD	(D.D3DF),A
	LD	(D$D3E0),A
	 CALL	C$B974
;
J.B915:	XOR	A
	 CALL	C.00C3
;
	 CALL	C.B95A
;
	INC	BC
	LD	B,9AH
	CP	C
	 CALL	C.0156
;
	 CALL	C$BB9C
;
	JR	C,J.B951
;
	JR	Z,J.B915
;
	 CALL	C.00A2
;
	LD	D,A
	LD	BC,I.0D0D
	 CALL	C.B7A9
;
	JR	C,J.B951
;
	JR	Z,J.B915
;
	LD	A,D
	SUB	31H	; "1"
	LD	HL,I$B98E
	LD	D,00H
	ADD	A,A
	LD	E,A
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	LD	(D$D3D6),HL
	LD	(D$D3D8),HL
	 CALL	C$B747
;
	XOR	A
J.B951:	PUSH	AF
	 CALL	C.BE07
;
	POP	AF
	RET	
;
;	-----------------
?.B957:	SCF	
	JR	J.B951
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B95A:	POP	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	HL
	PUSH	BC
	POP	HL
	 CALL	C.00C6
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B969:	LD	A,(DE)
	INC	DE
	OR	A
	JR	Z,J$B973
;
	 CALL	C.00A2
;
	JR	C.B969
;
;	-----------------
J$B973:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B974:	LD	HL,I$B980
	LD	DE,I.D3CE
	LD	BC,I.000E
	LDIR	
	RET	
;
;	-----------------
I$B980:	JR	C,J$B9C7
;
	LD	SP,I$4858
	LD	C,(HL)
	LD	C,(HL)
	LD	C,(HL)
	INC	L
	LD	BC,I$012C
	INC	D
	NOP	
I$B98E:	LD	L,(HL)
	NOP	
	INC	L
	LD	BC,I$0258
	OR	B
	INC	B
	LD	H,B
	ADD	HL,BC
	RET	NZ
;
	LD	(DE),A
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	JR	NZ,J$B9BF
;
	JR	NZ,J$B9C1
;
	JR	NZ,J$B9F7
;
	LD	D,D
	LD	B,C
	LD	C,(HL)
	LD	D,E
	LD	B,(HL)
	LD	B,L
	LD	D,D
	JR	NZ,J.B9FE
;
	LD	B,C
	LD	D,H
	LD	B,L
	JR	NZ,J.B9FE
;
	LD	B,L
	LD	C,(HL)
	LD	D,L
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	SP,D.202E
J$B9BF:	JR	NZ,J$B9E1
;
J$B9C1:	LD	SP,I$3031
	JR	NZ,J$BA28
;
	LD	(HL),B
J$B9C7:	LD	(HL),E
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	(D.202E),A
	JR	NZ,J$B9F4
;
	INC	SP
	JR	NC,J.BA07
;
	JR	NZ,J$BA3B
;
	LD	(HL),B
	LD	(HL),E
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
J$B9E1:	ADD	HL,BC
	INC	SP
	LD	L,20H	; " "
	JR	NZ,J.BA07
;
	LD	(HL),30H	; "0"
	JR	NC,J$BA0B
;
	LD	H,D
	LD	(HL),B
	LD	(HL),E
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
J$B9F4:	ADD	HL,BC
	INC	(HL)
	LD	L,20H	; " "
J$B9F7	EQU	$-1
	JR	NZ,J$BA2B
;
	LD	(D$3030),A
	JR	NZ,J$BA61
J.B9FE	EQU	$-1
;
	LD	(HL),B
	LD	(HL),E
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
J.BA07:	ADD	HL,BC
	DEC	(HL)
	LD	L,20H	; " "
J$BA0B:	JR	NZ,J.BA3F
;
	INC	(HL)
	JR	NC,J$BA40
;
	JR	NZ,J$BA74
;
	LD	(HL),B
	LD	(HL),E
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	(HL),2EH	; "."
	JR	NZ,J.BA3F
;
	INC	(HL)
	JR	C,J$BA52
;
	JR	NC,J$BA44
;
	LD	H,D
	LD	(HL),B
	LD	(HL),E
	DEC	C
J$BA28:	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
J$BA2B:	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	B,L
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J.BAA9
;
	LD	L,B
	LD	H,L
	JR	NZ,J$BAA7
;
	LD	(HL),L
	LD	L,L
J$BA3B:	LD	H,D
	LD	H,L
	LD	(HL),D
	LD	A,(X.0020)
J.BA3F	EQU	$-2
J$BA40	EQU	$-1
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
J$BA44:	LD	C,(HL)
	LD	L,A
	JR	NZ,J$BA9A
;
	LD	D,E
	DEC	L
	LD	C,C
	LD	C,(HL)
	LD	D,H
	LD	B,L
	LD	D,D
	LD	B,(HL)
	LD	B,C
	LD	B,E
J$BA52:	LD	B,L
	JR	NZ,J$BABE
;
	LD	L,(HL)
	JR	NZ,J$BACC
;
	LD	L,B
	LD	L,C
	LD	(HL),E
	JR	NZ,J$BAD0
;
	LD	A,C
	LD	(HL),E
	LD	(HL),H
	LD	H,L
J$BA61:	LD	L,L
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
I$BA65:	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$BA71
;
	LD	B,L
J$BA71:	LD	BC,I.0153
J$BA74:	LD	B,E
	JR	NZ,J.BA77
;
J.BA77:	LD	C,H
	LD	C,C
	LD	D,E
	LD	D,H
	LD	B,L
	LD	C,(HL)
	LD	B,L
	LD	D,D
	DAA	
	LD	D,E
	JR	NZ,J$BAD6
;
	LD	B,E
	LD	D,D
	LD	B,L
	LD	B,L
	LD	C,(HL)
	NOP	
I$BA89:	DEC	C
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
I$BA8F:	LD	D,D
	LD	B,L
	LD	B,E
	LD	B,L
	LD	C,C
	LD	D,(HL)
	LD	C,C
	LD	C,(HL)
	LD	B,A
	NOP	
I$BA99:	LD	D,H
J$BA9A:	LD	B,C
	LD	C,H
	LD	C,E
	LD	B,L
	LD	D,D
	DAA	
	LD	D,E
	JR	NZ,J$BAF6
;
	LD	B,E
	LD	D,D
	LD	B,L
	LD	B,L
J$BAA7:	LD	C,(HL)
	NOP	
J.BAA9:	DEC	C
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
I$BAAF:	LD	D,E
	LD	B,L
	LD	C,(HL)
	LD	B,H
	LD	C,C
	LD	C,(HL)
	LD	B,A
	NOP	
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	JR	NZ,J$BADD
;
	LD	C,A
J$BABE:	LD	D,B
	LD	B,L
	LD	D,D
	LD	B,C
	LD	D,H
	LD	C,C
	LD	C,A
	LD	C,(HL)
	JR	NZ,J$BB15
;
	LD	B,L
	LD	C,(HL)
	LD	D,L
	DEC	C
J$BACC:	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
J$BAD0:	ADD	HL,BC
	ADD	HL,BC
	LD	SP,D.202E
	JR	NZ,J$BB29
J$BAD6	EQU	$-1
;
	LD	H,L
	LD	H,E
	LD	H,L
	LD	L,C
	HALT	
;
;	-----------------
?.BADC:	LD	L,C
J$BADD:	LD	L,(HL)
	LD	H,A
	JR	NZ,J$BB55
;
	LD	L,B
	LD	H,L
	JR	NZ,J$BB59
;
	LD	H,L
	LD	A,B
	LD	(HL),H
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	(D.202E),A
	JR	NZ,J$BB47
;
	LD	H,L
	LD	L,(HL)
J$BAF6:	LD	H,H
	LD	L,C
	LD	L,(HL)
	LD	H,A
	JR	NZ,J$BB70
;
	LD	L,B
	LD	H,L
	JR	NZ,J$BB74
;
	LD	H,L
	LD	A,B
	LD	(HL),H
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	INC	SP
	LD	L,20H	; " "
	JR	NZ,J$BB52
;
	LD	L,A
	LD	L,L
	LD	L,L
	LD	(HL),L
	LD	L,(HL)
	LD	L,C
J$BB15:	LD	H,E
	LD	H,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	B,L
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$BB9D
;
J$BB29:	LD	L,B
	LD	H,L
	JR	NZ,J$BB9B
;
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
	LD	(HL),D
	LD	A,(X.0020)
I$BB35:	DEC	C
	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	C,A
	LD	(HL),B
	LD	H,L
	LD	(HL),D
	LD	H,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$BBAF
;
	LD	(HL),E
J$BB47:	JR	NZ,J$BBAC
;
	LD	L,A
	LD	L,L
	LD	(HL),B
	LD	L,H
	LD	H,L
	LD	(HL),H
	LD	H,L
	LD	H,H
	DEC	C
J$BB52:	LD	A,(BC)
	NOP	
I$BB54:	DEC	C
J$BB55:	LD	A,(BC)
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
J$BB59:	ADD	HL,BC
	LD	B,E
	LD	H,C
	LD	L,(HL)
	DAA	
	LD	(HL),H
	JR	NZ,J$BBD4
;
	LD	H,L
	LD	L,(HL)
	LD	H,H
	DEC	SP
	JR	NZ,J$BBAA
;
	LD	D,H
	LD	D,E
	JR	NZ,J$BBD7
;
	LD	L,C
	LD	L,(HL)
	LD	H,L
	JR	NZ,J$BBD9
;
J$BB70:	LD	(HL),E
	JR	NZ,J$BBE2
;
	LD	H,(HL)
J$BB74:	LD	H,(HL)
	DEC	C
	LD	A,(BC)
	NOP	
I$BB78:	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	D,A
	LD	L,B
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$BBF4
;
	LD	H,L
	LD	H,C
	LD	H,H
	LD	A,C
	INC	L
	JR	NZ,J.BBF9
;
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$BB90
;
	LD	D,D
J$BB90:	LD	BC,I.0145
	LD	D,H
	LD	BC,I.0155
	LD	D,D
	LD	BC,I.204E
J$BB9B:	NOP	
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BB9C:	LD	BC,I$3136
J$BB9D	EQU	$-2
	 CALL	C.B7A9
;
	JR	C,J.BBAB
;
	JR	NZ,J.BBAB
;
	CP	1AH
	JR	Z,J$BBB1
;
J$BBAA:	XOR	A
J.BBAB:	PUSH	AF
J$BBAC:	 CALL	C.0156
;
J$BBAF:	POP	AF
	RET	
;
;	-----------------
J$BBB1:	LD	A,1BH
	 CALL	C.00A2
;
	LD	A,6CH	; "l"
	 CALL	C.00A2
;
	 CALL	C$00B4
;
	JR	C,J.BBAB
;
	INC	HL
	LD	DE,I.D3CE
	LD	BC,I$0008
	LDIR	
	XOR	A
	LD	(D.D3DF),A
	JR	J.BBAB
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BBCF:	 CALL	C.BE52
;
	 CALL	C.BE5F
J$BBD4	EQU	$-1
;
J.BBD5:	LD	A,(D.D3DF)
J$BBD7	EQU	$-1
	OR	A
J$BBD9:	JR	Z,J$BBDE
;
	 CALL	C.BDA9
;
J$BBDE:	 CALL	C$00B7
;
	JR	C,J$BC43
J$BBE2	EQU	$-1
;
	 CALL	C$BC82
;
	 CALL	C.009C
;
	JR	Z,J.BC2E
;
	 CALL	C.009F
;
	CP	0FEH
	JR	NZ,J.BBF9
;
	 CALL	C.009C
J$BBF4	EQU	$-1
;
	JR	NZ,J$BC56
;
	LD	A,0FEH
J.BBF9:	CP	80H
	JR	NC,J.BC2E
;
J$BBFD:	 CALL	C.BCA8
;
	JR	Z,J$BC25
;
	LD	HL,D.D3E6
	LD	(HL),00H
	LD	C,A
	LD	A,(D.D3DF)
	OR	A
	LD	A,C
	JR	Z,J$BC1A
;
	CP	0DH	; 13 
	JR	NZ,J$BC14
;
	LD	(HL),A
J$BC14:	 CALL	C.BDA9
;
	 CALL	C.00A2
;
J$BC1A:	 CALL	C$BE6C
;
	LD	A,(D.D3E6)
	OR	A
	LD	A,0AH	; 10 
	JR	NZ,J$BBFD
;
J$BC25:	LD	A,(D.D3DF)
	OR	A
	JR	NZ,J.BC2E
;
	 CALL	C.BDCC
;
J.BC2E:	 CALL	C$BE19
;
	JR	Z,J.BBD5
;
J$BC33:	 CALL	C.BDCC
;
	 CALL	C.BE7E
;
	JR	C,J.BBD5
;
	 CALL	C.BCA8
;
	 CALL	C.00A2
;
	JR	J.BBD5
;
;	-----------------
J$BC43:	 CALL	C.B778
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BC46:	LD	A,18H
	LD	(D.F3B1),A
	LD	HL,C.0000
	LD	(D.F922),HL
	XOR	A
	 CALL	C.00C3
;
	RET	
;
;	-----------------
J$BC56:	 CALL	C.009F
;
	OR	A
	JR	Z,J.BC72
;
	CP	06H	; 6 
	JR	NC,J.BC72
;
	DEC	A
	ADD	A,A
	LD	E,A
	LD	D,00H
	LD	HL,I$BC77
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,J.BC72
	PUSH	HL
	EX	DE,HL
	JP	(HL)
;
;	-----------------
J.BC72:	 CALL	C.0156
;
	JR	J.BC2E
;
;	-----------------
I$BC77:	LD	C,L
	CP	B
	JR	C,J$BC33
;
	ADD	A,C
	CP	H
	ADD	A,C
	CP	H
	ADD	A,C
	CP	H
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BC82:	LD	A,(D.D3DF)
	OR	A
	JR	NZ,J.BCA6
;
	LD	HL,I$FC9B
	DI	
	LD	A,(HL)
	LD	(HL),00H
	OR	A
	JR	Z,J.BCA6
;
	EI	
	LD	IY,(D.D3CA)
	LD	IX,(D.D3CC)
	LD	BC,I$0021
	ADD	IX,BC
	LD	DE,I$0064
	 CALL	C.001C
;
J.BCA6:	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BCA8:	LD	C,A
	CP	20H	; " "
	JR	NC,J.BCBE
;
	LD	A,(D.D3DF)
	OR	A
	JR	Z,J.BCBE
;
	LD	HL,I$BCC5
J$BCB6:	LD	A,(HL)
	INC	HL
	OR	A
	JR	Z,J$BCC1
;
	CP	C
	JR	NZ,J$BCB6
;
J.BCBE:	LD	A,C
	OR	A
	RET	
;
;	-----------------
J$BCC1:	LD	C,00H
	JR	J.BCBE
;
;	-----------------
I$BCC5:	RLCA	
	EX	AF,AF'
	LD	A,(BC)
	DEC	C
	NOP	
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BCCA:	LD	B,0A0H
	LD	HL,I$F87F
	PUSH	HL
J$BCD0:	LD	(HL),00H
	INC	HL
	DJNZ	J$BCD0
;
	LD	B,0AH	; 10 
	LD	A,01H	; 1 
	POP	HL
	LD	DE,I.000E
J$BCDD:	LD	(HL),0FEH
	INC	HL
	LD	(HL),A
	INC	A
	INC	HL
	ADD	HL,DE
	DJNZ	J$BCDD
;
	 CALL	C.BCEA
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BCEA:	LD	HL,I$BCFC
J$BCED:	LD	DE,I$073A
	LD	BC,I$0044
	 CALL	FCB1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BCF7:	LD	HL,I$BD22
	JR	J$BCED
;
;	-----------------
I$BCFC:	LD	B,(HL)
	LD	SP,I$6C3A
	LD	L,A
	LD	H,C
	LD	H,H
	DEC	L
	LD	(HL),H
	LD	H,L
	LD	A,B
	LD	(HL),H
	JR	NZ,J$BD2A
;
	JR	NZ,J$BD2C
;
	LD	B,(HL)
	LD	(D$733A),A
	LD	H,L
	LD	L,(HL)
	LD	H,H
	DEC	L
	LD	(HL),H
	LD	H,L
	LD	A,B
	LD	(HL),H
	JR	NZ,J$BD3A
;
	JR	NZ,J$BD3C
;
	JR	NZ,J$BD3E
;
	JR	NZ,J$BD40
;
	JR	NZ,J$BD42
;
I$BD22:	LD	D,H
	LD	L,A
	JR	NZ,J$BD87
;
	LD	H,D
	LD	L,A
	LD	(HL),D
	LD	(HL),H
J$BD2A:	INC	L
	JR	NZ,J$BD9D
J$BD2C	EQU	$-1
;
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$BD36
;
	INC	D
	LD	(DE),A
	INC	C
J$BD36:	JR	NZ,J$BD99
;
	LD	L,(HL)
	LD	H,H
J$BD3A:	JR	NZ,J$BD4F
;
J$BD3C:	INC	D
	RRCA	
J$BD3E:	DJNZ	J$BD60
;
J$BD40:	JR	NZ,J$BD62
;
J$BD42:	JR	NZ,J$BD64
;
	JR	NZ,J$BD66
;
	JR	NZ,J$BD68
;
	JR	NZ,J$BD6A
;
	JR	NZ,J$BD6C
;
	JR	NZ,J$BD6E
;
	JR	NZ,J$BD70
J$BD4F	EQU	$-1
;
	JR	NZ,J$BD72
;
	JR	NZ,J$BD74
;
	JR	NZ,J$BD76
;
	JR	NZ,J$BD78
;
	JR	NZ,J$BD7A
;
	JR	NZ,J$BD7C
;
	JR	NZ,J$BD7E
;
	JR	NZ,J$BD80
;
J$BD60:	JR	NZ,J$BD82
;
J$BD62:	JR	NZ,J$BD84
;
J$BD64:	JR	NZ,J$BD86
;
J$BD66:	JR	NZ,J$BD88
;
J$BD68:	JR	NZ,J$BD8A
;
J$BD6A:	JR	NZ,J$BD8C
;
J$BD6C:	JR	NZ,J$BD8E
;
J$BD6E:	JR	NZ,J$BD90
;
J$BD70:	JR	NZ,J$BD92
;
J$BD72:	JR	NZ,J$BD94
;
J$BD74:	JR	NZ,J$BD96
;
J$BD76:	JR	NZ,J$BD98
;
J$BD78:	JR	NZ,J$BD9A
;
J$BD7A:	JR	NZ,J$BD9C
;
J$BD7C:	JR	NZ,J$BD9E
;
J$BD7E:	JR	NZ,J.BDA0
;
J$BD80:	JR	NZ,J$BDA2
;
J$BD82:	JR	NZ,J$BDA4
;
J$BD84:	JR	NZ,J$BDA6
;
J$BD86:	JR	NZ,J$BDA8
J$BD87	EQU	$-1
;
J$BD88:	JR	NZ,J$BDAA
;
J$BD8A:	JR	NZ,J$BDAC
;
J$BD8C:	JR	NZ,J$BDAE
;
J$BD8E:	JR	NZ,J$BDB0
;
J$BD90:	JR	NZ,J$BDB2
;
J$BD92:	JR	NZ,J$BDB4
;
J$BD94:	JR	NZ,J$BDB6
;
J$BD96:	JR	NZ,J$BDB8
;
J$BD98:	JR	NZ,J$BDBA
J$BD99	EQU	$-1
;
J$BD9A:	JR	NZ,J$BDBD
C$BD9B	EQU	$-1
;
J$BD9C:	INC	SP
J$BD9D:	RLCA	
J$BD9E:	LD	B,4BH	; "K"
J.BDA0:	LD	A,20H	; " "
J$BDA2:	 CALL	C.004D
J$BDA4	EQU	$-1
;
	INC	HL
J$BDA6:	DJNZ	J.BDA0
;
J$BDA8:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BDA9:	PUSH	AF
J$BDAA:	LD	A,(D.D3DE)
J$BDAC	EQU	$-1
	OR	A
J$BDAE:	JR	NZ,J.BDF4
;
J$BDB0:	 CALL	C.BE02
J$BDB2	EQU	$-1
;
	LD	HL,(D.F3DC)
J$BDB4	EQU	$-2
J$BDB6:	LD	(D.D3E4),HL
J$BDB8	EQU	$-1
	LD	A,04H	; 4 
J$BDBA	EQU	$-1
	LD	(D.F3B1),A
J$BDBD	EQU	$-1
	LD	(D.D3DE),A
	LD	HL,I$05A0
	LD	(D.F922),HL
	LD	HL,(D.D3E2)
	JR	J$BDEE
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BDCC:	PUSH	AF
	LD	A,(D.D3DE)
	OR	A
	JR	Z,J.BDF4
;
	 CALL	C.BE02
;
	LD	HL,(D.F3DC)
	LD	(D.D3E2),HL
	LD	A,0FH	; 15 
	LD	(D.F3B1),A
	LD	HL,I$0050
	LD	(D.F922),HL
	LD	HL,(D.D3E4)
	XOR	A
	LD	(D.D3DE),A
J$BDEE:	 CALL	C.00C6
;
	 CALL	C.BE07
;
J.BDF4:	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BDF6:	DEC	HL
	LD	A,L
	OR	H
	RET	NZ
;
	LD	HL,I.0F00
	INC	E
	BIT	0,E
	JR	NZ,C.BE07
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE02:	LD	A,78H	; "x"
	PUSH	AF
	JR	J$BE0A
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE07:	LD	A,79H	; "y"
	PUSH	AF
J$BE0A:	LD	A,1BH
	 CALL	C.00A2
;
	POP	AF
	 CALL	C.00A2
;
	LD	A,35H	; "5"
	 CALL	C.00A2
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BE19:	LD	DE,I$0018
	 CALL	C.BE6F
;
	LD	A,L
	OR	H
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE22:	LD	B,50H	; "P"
J$BE24:	LD	A,3DH	; "="
	 CALL	C.004D
;
	INC	HL
	DJNZ	J$BE24
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE2D:	LD	A,(DE)
	OR	A
	RET	Z
;
	INC	DE
	 CALL	C.004D
;
	INC	HL
	JR	C.BE2D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BE37:	LD	HL,C.0000
	 CALL	C.BE22
;
	LD	HL,I$003D
J$BE40:	POP	BC
	POP	DE
	PUSH	BC
	 CALL	C.BE2D
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BE47:	LD	HL,I$0550
	 CALL	C.BE22
;
	LD	HL,I$058D
	JR	J$BE40
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE52:	LD	DE,J.BA77
J$BE55:	PUSH	DE
	 CALL	C$BE37
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BE5A:	LD	DE,I$BA8F
	JR	J$BE55
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE5F:	LD	DE,I$BA99
J$BE62:	PUSH	DE
	 CALL	C$BE47
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BE67:	LD	DE,I$BAAF
	JR	J$BE62
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BE6C:	LD	DE,I.000F
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE6F:	LD	IY,(D.D3CA)
	LD	IX,(D.D3CC)
	ADD	IX,DE
	 CALL	C.001C
;
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BE7E:	LD	DE,C.000C
	JR	C.BE6F
;
;	-----------------
?.BE83:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	END
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	3