;  
;   FS-SR021, segment 0 -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA
;
	.Z80
	ORG	4000H
;
I.0000	EQU	0000H	; ----I
I.0001	EQU	0001H	; ----I
I.0002	EQU	0002H	; ----I
C.0003	EQU	0003H	; -C--I
I$0004	EQU	0004H	; ----I
BDOS	EQU	0005H	; ----I
CPMADR	EQU	0006H	; ---LI
D.0007	EQU	0007H	; ---LI
I.0008	EQU	0008H	; ----I
C.0009	EQU	0009H	; -C--I
I.000A	EQU	000AH	; ----I
I$000B	EQU	000BH	; ----I
RDSLT	EQU	000CH	; -C--I
I$000D	EQU	000DH	; ----I
C.0010	EQU	0010H	; -C--I
I.0011	EQU	0011H	; ----I
WRSLT	EQU	0014H	; -C---
C$0015	EQU	0015H	; -C---
I.0016	EQU	0016H	; ----I
C.0018	EQU	0018H	; -C--I
I.0024	EQU	0024H	; ----I
C.0030	EQU	0030H	; -C--I
C.0038	EQU	0038H	; -C---
I$0040	EQU	0040H	; ----I
C$0041	EQU	0041H	; -C---
C$0044	EQU	0044H	; -C---
I$0048	EQU	0048H	; ----I
C$0050	EQU	0050H	; -C---
FCB1.1	EQU	005DH	; -C---
C$005F	EQU	005FH	; -C---
I.0063	EQU	0063H	; ----I
C$0069	EQU	0069H	; -C---
FCB2.1	EQU	006EH	; -C---
C.0074	EQU	0074H	; -C---
I.007E	EQU	007EH	; ----I
DBUF	EQU	0080H	; ----I
GICINI	EQU	0090H	; -C---
C$009B	EQU	009BH	; -C---
C$00D7	EQU	00D7H	; -C---
I$0101	EQU	0101H	; ----I
C.0110	EQU	0110H	; -C--I
C$0125	EQU	0125H	; -C---
J$0167	EQU	0167H	; J----
I$0200	EQU	0200H	; ----I
I$0300	EQU	0300H	; ----I
I$0600	EQU	0600H	; ----I
I$0801	EQU	0801H	; ----I
I$0B40	EQU	0B40H	; ----I
I$0B41	EQU	0B41H	; ----I
C$0E47	EQU	0E47H	; -C---
I$0EAA	EQU	0EAAH	; ----I
I.197E	EQU	197EH	; ----I
J$1E4F	EQU	1E4FH	; J----
I.2000	EQU	2000H	; ----I
D$2222	EQU	2222H	; --S--
I$2800	EQU	2800H	; ----I
I$3030	EQU	3030H	; ----I
D$3075	EQU	3075H	; ---L-
C$3290	EQU	3290H	; -C---
C$3846	EQU	3846H	; -C---
C$3A47	EQU	3A47H	; -C---
D$3A75	EQU	3A75H	; ---L-
D$3F41	EQU	3F41H	; ---L-
D$3F42	EQU	3F42H	; ---L-
D$3F43	EQU	3F43H	; ---L-
D$3F44	EQU	3F44H	; ---L-
D$3F45	EQU	3F45H	; ---L-
D$3F46	EQU	3F46H	; ---L-
D$3F47	EQU	3F47H	; ---L-
D.3F51	EQU	3F51H	; ---L-
D.3F57	EQU	3F57H	; --SL-
C.8000	EQU	8000H	; JC---
C.8003	EQU	8003H	; JC---
C.8006	EQU	8006H	; JC---
C.8009	EQU	8009H	; -C---
C.800C	EQU	800CH	; -C---
C.800F	EQU	800FH	; -C---
C.8012	EQU	8012H	; -C---
C$8015	EQU	8015H	; -C---
C.8018	EQU	8018H	; -C---
C.801B	EQU	801BH	; -C---
C.801E	EQU	801EH	; -C---
C.8021	EQU	8021H	; -C---
C$8024	EQU	8024H	; -C---
C.8027	EQU	8027H	; -C---
C.802A	EQU	802AH	; -C---
C$802D	EQU	802DH	; -C---
C.8030	EQU	8030H	; -C---
C.8033	EQU	8033H	; -C---
C.8036	EQU	8036H	; -C---
C.8039	EQU	8039H	; -C---
C.803C	EQU	803CH	; -C---
C.8045	EQU	8045H	; -C---
C$8048	EQU	8048H	; -C---
C$804B	EQU	804BH	; -C---
C.804E	EQU	804EH	; -C---
C$8051	EQU	8051H	; -C---
C$8054	EQU	8054H	; -C---
C$8057	EQU	8057H	; -C---
C$805A	EQU	805AH	; -C---
C$805D	EQU	805DH	; -C---
C$8060	EQU	8060H	; -C---
C$8063	EQU	8063H	; -C---
C$8066	EQU	8066H	; -C---
C$8069	EQU	8069H	; -C---
C$806C	EQU	806CH	; -C---
C$806F	EQU	806FH	; -C---
C.8072	EQU	8072H	; -C---
C$8075	EQU	8075H	; -C---
C$8078	EQU	8078H	; -C---
C$807B	EQU	807BH	; -C---
C$807E	EQU	807EH	; -C---
C$8081	EQU	8081H	; -C---
C$8084	EQU	8084H	; -C---
C$8087	EQU	8087H	; -C---
C$808A	EQU	808AH	; -C---
C$808D	EQU	808DH	; -C---
C$809F	EQU	809FH	; -C---
C$80A2	EQU	80A2H	; -C---
C$80A5	EQU	80A5H	; -C---
C$80A8	EQU	80A8H	; -C---
C$80AB	EQU	80ABH	; -C---
C$80AE	EQU	80AEH	; -C---
C$80B1	EQU	80B1H	; -C---
C$80B7	EQU	80B7H	; -C---
C$80BA	EQU	80BAH	; -C---
C$80BD	EQU	80BDH	; -C---
C$80C3	EQU	80C3H	; -C---
C$80C6	EQU	80C6H	; -C---
C$80C9	EQU	80C9H	; -C---
C$80CF	EQU	80CFH	; -C---
C$80D2	EQU	80D2H	; -C---
C$80D5	EQU	80D5H	; -C---
C$80D8	EQU	80D8H	; -C---
C$80DB	EQU	80DBH	; -C---
C$80EA	EQU	80EAH	; -C---
C$80F0	EQU	80F0H	; -C---
C$80F9	EQU	80F9H	; -C---
C$80FC	EQU	80FCH	; -C---
C$80FF	EQU	80FFH	; -C---
I$8101	EQU	8101H	; ----I
C$8102	EQU	8102H	; -C---
J$8105	EQU	8105H	; J----
J$8108	EQU	8108H	; J----
C$810B	EQU	810BH	; -C---
J$810E	EQU	810EH	; J----
C$8111	EQU	8111H	; -C---
C$8114	EQU	8114H	; -C---
C$8126	EQU	8126H	; -C---
J$812C	EQU	812CH	; J----
C$8146	EQU	8146H	; -C---
I$8202	EQU	8202H	; ----I
C$8FCD	EQU	8FCDH	; -C---
I$A000	EQU	0A000H	; ----I
C$A1C3	EQU	0A1C3H	; -C---
C$A1C6	EQU	0A1C6H	; -C---
C$A1C9	EQU	0A1C9H	; -C---
I.A400	EQU	0A400H	; ----I
I.B400	EQU	0B400H	; ----I
I$B401	EQU	0B401H	; ----I
D.BF58	EQU	0BF58H	; --S--
I$BFF0	EQU	0BFF0H	; ----I
I.C000	EQU	0C000H	; ----I
I$C010	EQU	0C010H	; ----I
I$C011	EQU	0C011H	; ----I
J.C200	EQU	0C200H	; J---I
I.C201	EQU	0C201H	; ----I
I.C27E	EQU	0C27EH	; ----I
D.C280	EQU	0C280H	; --SL-
D.C282	EQU	0C282H	; --SL-
D.C284	EQU	0C284H	; --SL-
D.C286	EQU	0C286H	; --SL-
D.C288	EQU	0C288H	; --SL-
D.C289	EQU	0C289H	; --SL-
D.C28A	EQU	0C28AH	; --SL-
D.C28B	EQU	0C28BH	; --SL-
D.C28C	EQU	0C28CH	; --SL-
D.C28E	EQU	0C28EH	; --SL-
D.C28F	EQU	0C28FH	; --SL-
D.C290	EQU	0C290H	; --SL-
D.C291	EQU	0C291H	; --SL-
D.C292	EQU	0C292H	; --SL-
D.C293	EQU	0C293H	; --SL-
I$C294	EQU	0C294H	; ----I
D.C2F9	EQU	0C2F9H	; --SL-
D.C31A	EQU	0C31AH	; ---L-
D.C31B	EQU	0C31BH	; ---L-
D.C31C	EQU	0C31CH	; ---L-
D$C31D	EQU	0C31DH	; ---L-
D.C31E	EQU	0C31EH	; ---L-
D$C31F	EQU	0C31FH	; ---L-
D.C320	EQU	0C320H	; ---L-
D.C325	EQU	0C325H	; --SL-
D.C326	EQU	0C326H	; --SLI
D.C328	EQU	0C328H	; --SL-
D$C329	EQU	0C329H	; ---L-
D$C32B	EQU	0C32BH	; --S--
D.C32C	EQU	0C32CH	; --S--
D.C32E	EQU	0C32EH	; --S-I
D.C332	EQU	0C332H	; --S-I
D$C333	EQU	0C333H	; ---L-
D.C337	EQU	0C337H	; --SL-
D.C339	EQU	0C339H	; --S--
D.C33D	EQU	0C33DH	; --SL-
I.C33E	EQU	0C33EH	; ----I
I.C33F	EQU	0C33FH	; ----I
I.C340	EQU	0C340H	; ----I
D.C354	EQU	0C354H	; --S--
D.C355	EQU	0C355H	; --S--
I.C389	EQU	0C389H	; ----I
D$C393	EQU	0C393H	; --S--
D$C395	EQU	0C395H	; --S--
D.C39D	EQU	0C39DH	; --S-I
D.C3A0	EQU	0C3A0H	; --SL-
D.C3B1	EQU	0C3B1H	; --S-I
D.C3B5	EQU	0C3B5H	; --SL-
D.C3BD	EQU	0C3BDH	; --SLI
D$C3BF	EQU	0C3BFH	; --S--
D.C3C0	EQU	0C3C0H	; --S-I
D.C3C5	EQU	0C3C5H	; --SLI
D.C3C7	EQU	0C3C7H	; --SL-
D.C3C8	EQU	0C3C8H	; --S--
D$C415	EQU	0C415H	; --S--
D.C419	EQU	0C419H	; --S--
D$C41B	EQU	0C41BH	; --S--
D.C4AE	EQU	0C4AEH	; --S--
D.C4B3	EQU	0C4B3H	; --S--
D$C4B4	EQU	0C4B4H	; --S--
D.C4B5	EQU	0C4B5H	; --S--
D$C4B6	EQU	0C4B6H	; --S--
D.C4BD	EQU	0C4BDH	; --S--
D$C4C2	EQU	0C4C2H	; --S--
I.C898	EQU	0C898H	; ----I
I.C899	EQU	0C899H	; ----I
D.C8FD	EQU	0C8FDH	; --SL-
D.C8FF	EQU	0C8FFH	; --SL-
D.C901	EQU	0C901H	; --SL-
I$C903	EQU	0C903H	; ----I
D.C904	EQU	0C904H	; --SL-
D.C906	EQU	0C906H	; --SL-
D.C907	EQU	0C907H	; --SL-
D.C908	EQU	0C908H	; --SL-
D.C909	EQU	0C909H	; --SL-
D.C90A	EQU	0C90AH	; --SL-
D.C90B	EQU	0C90BH	; --SL-
D.C90C	EQU	0C90CH	; --SL-
D.C90E	EQU	0C90EH	; --SL-
D.C90F	EQU	0C90FH	; --SL-
D.C910	EQU	0C910H	; --SL-
D.C913	EQU	0C913H	; --SL-
D.C917	EQU	0C917H	; --SLI
D$C918	EQU	0C918H	; --S--
D.C919	EQU	0C919H	; --SLI
I.C91B	EQU	0C91BH	; ----I
D$C942	EQU	0C942H	; --S--
D.C9C6	EQU	0C9C6H	; --SLI
D.C9CD	EQU	0C9CDH	; --SL-
I$C9E3	EQU	0C9E3H	; ----I
D$CB63	EQU	0CB63H	; ---L-
D$CB65	EQU	0CB65H	; ---L-
D$CB76	EQU	0CB76H	; --S--
D$CB78	EQU	0CB78H	; --S--
D$CB7A	EQU	0CB7AH	; --S--
I$CB7B	EQU	0CB7BH	; ----I
D$CBAF	EQU	0CBAFH	; --S--
I$CBB0	EQU	0CBB0H	; ----I
D.CBB1	EQU	0CBB1H	; --S--
D$CBB2	EQU	0CBB2H	; --S--
D.CBB8	EQU	0CBB8H	; --SL-
D.CBB9	EQU	0CBB9H	; --SL-
D$CBBA	EQU	0CBBAH	; --S--
D$CBBB	EQU	0CBBBH	; --S--
D.CC3D	EQU	0CC3DH	; ---L-
D.CC3F	EQU	0CC3FH	; ---LI
D.CC40	EQU	0CC40H	; ---L-
D.CC41	EQU	0CC41H	; ---L-
D.CC44	EQU	0CC44H	; ---L-
D.CC45	EQU	0CC45H	; ---L-
D.CC46	EQU	0CC46H	; ---L-
D.CC48	EQU	0CC48H	; ---L-
D$CC49	EQU	0CC49H	; ---L-
D$CC4A	EQU	0CC4AH	; ---L-
D.CC4B	EQU	0CC4BH	; ---L-
D.CC4C	EQU	0CC4CH	; ---L-
D.CC4D	EQU	0CC4DH	; ---L-
D$CCEE	EQU	0CCEEH	; --S--
D.CE6C	EQU	0CE6CH	; --SL-
D.CE73	EQU	0CE73H	; --S--
D.CF17	EQU	0CF17H	; --S--
D.CF1A	EQU	0CF1AH	; --SLI
D.CF1B	EQU	0CF1BH	; --SL-
D.CF1C	EQU	0CF1CH	; --SL-
D$CF1D	EQU	0CF1DH	; ---L-
D.CF1E	EQU	0CF1EH	; --SL-
D.CF1F	EQU	0CF1FH	; --S--
D.CF20	EQU	0CF20H	; --SL-
I.D14F	EQU	0D14FH	; ----I
D.D18E	EQU	0D18EH	; --SL-
D$D1A0	EQU	0D1A0H	; ---L-
I$D1B1	EQU	0D1B1H	; ----I
D$D1B4	EQU	0D1B4H	; --S--
D.D1BC	EQU	0D1BCH	; --S--
I.D1BD	EQU	0D1BDH	; ----I
I$D1E0	EQU	0D1E0H	; ----I
I$D1E1	EQU	0D1E1H	; ----I
I$D1F2	EQU	0D1F2H	; ----I
D$D448	EQU	0D448H	; --S--
D.D449	EQU	0D449H	; --SL-
D$D44B	EQU	0D44BH	; ---L-
D.D44E	EQU	0D44EH	; --S--
D$D44F	EQU	0D44FH	; ---L-
D$D450	EQU	0D450H	; --S--
D$D457	EQU	0D457H	; --S--
D.D464	EQU	0D464H	; --SLI
D.D466	EQU	0D466H	; --S--
D.D468	EQU	0D468H	; --SL-
D.D469	EQU	0D469H	; ---LI
D.D46B	EQU	0D46BH	; ---L-
D.D46E	EQU	0D46EH	; ---L-
D.D473	EQU	0D473H	; --SL-
D$D474	EQU	0D474H	; ---L-
D.D475	EQU	0D475H	; --SL-
D$D477	EQU	0D477H	; ---L-
D.D478	EQU	0D478H	; ---L-
D.D47B	EQU	0D47BH	; ---L-
D.D47C	EQU	0D47CH	; ---L-
D.D47D	EQU	0D47DH	; --SL-
D.D47F	EQU	0D47FH	; --SL-
D.D480	EQU	0D480H	; --SL-
D.D481	EQU	0D481H	; ---L-
D.D482	EQU	0D482H	; ---L-
D.D483	EQU	0D483H	; ---L-
D.D484	EQU	0D484H	; --SL-
D.D48A	EQU	0D48AH	; --SL-
D.D48B	EQU	0D48BH	; --SL-
D.D48F	EQU	0D48FH	; --SL-
D.D497	EQU	0D497H	; --SL-
D.D498	EQU	0D498H	; ---L-
D.D49B	EQU	0D49BH	; --SL-
D.D49C	EQU	0D49CH	; --SL-
D$D49D	EQU	0D49DH	; --S--
D.D49E	EQU	0D49EH	; --SLI
D.D49F	EQU	0D49FH	; --SL-
D.D4A0	EQU	0D4A0H	; --SL-
D.D4A6	EQU	0D4A6H	; --SL-
D.D4AD	EQU	0D4ADH	; ---L-
D$D4AF	EQU	0D4AFH	; ---L-
D$D4B8	EQU	0D4B8H	; --S--
D.D4C0	EQU	0D4C0H	; --SL-
D$D4C6	EQU	0D4C6H	; --S--
D.D4C7	EQU	0D4C7H	; --SL-
D.D4D2	EQU	0D4D2H	; ---L-
D.D4D4	EQU	0D4D4H	; ---L-
D.D4D5	EQU	0D4D5H	; ---L-
D.D4D7	EQU	0D4D7H	; ---L-
D.D4D8	EQU	0D4D8H	; --SLI
D.D4D9	EQU	0D4D9H	; --SL-
D.D4DA	EQU	0D4DAH	; --S--
D.D4DB	EQU	0D4DBH	; --SL-
D.D4E0	EQU	0D4E0H	; --SL-
D.D4E3	EQU	0D4E3H	; --SL-
D.D4E4	EQU	0D4E4H	; --SL-
D.D4E5	EQU	0D4E5H	; --SL-
D.D4E6	EQU	0D4E6H	; --SL-
I$D4F7	EQU	0D4F7H	; ----I
D.D524	EQU	0D524H	; --S--
I.D525	EQU	0D525H	; ----I
D$D54C	EQU	0D54CH	; ---L-
D.D552	EQU	0D552H	; ---L-
D.D553	EQU	0D553H	; --S--
I.D561	EQU	0D561H	; ----I
I.DA4F	EQU	0DA4FH	; ----I
I$DAA5	EQU	0DAA5H	; ----I
D.DACD	EQU	0DACDH	; ---L-
D.DAE4	EQU	0DAE4H	; --S--
D$DB15	EQU	0DB15H	; ---L-
D$DB17	EQU	0DB17H	; ---L-
D$DB27	EQU	0DB27H	; ---L-
D$DB29	EQU	0DB29H	; --S--
I$DB68	EQU	0DB68H	; ----I
I$DBE3	EQU	0DBE3H	; ----I
I.DE3D	EQU	0DE3DH	; ----I
D$DE3E	EQU	0DE3EH	; ---L-
C$F667	EQU	0F667H	; -C---

I$FACD	EQU	0FACDH	; ----I
I.FBC3	EQU	0FBC3H	; ----I
D$FC4A	EQU	0FC4AH	; ---L-
D$FCAF	EQU	0FCAFH	; --S--
D.FCC1	EQU	0FCC1H	; ---LI
D.FD9A	EQU	0FD9AH	; --SL-
H.TIMI	EQU	0FD9FH	; -C---
H.STKE	EQU	0FEDAH	; ----I
C$FF74	EQU	0FF74H	; -C---
H.PHYD	EQU	0FFA7H	; ---L-
EXTBIO	EQU	0FFCAH	; --S--
I.FFEA	EQU	0FFEAH	; ----I
I.FFFE	EQU	0FFFEH	; ----I
D.FFFF	EQU	0FFFFH	; --SLI
;
I$4000:	DEFB	"AB"
	DEFW	C.4106
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0

	JP	J$60EB

?.4013:	JP	J.7429

?.4016:	JP	J.7429

?.4019:	JP	C.76FA

?.401C:	JP	C.77D6

?.401F:	JP	J$754B

?.4022:	JP	J$7669

?.4025:	JP	J$5545

?.4028:	JP	C.5556

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$402B:	JP	C.555B

?.402E:	JP	C.560E

?.4031:	JP	C.5613

?.4034:	JP	J$553E

?.4037:	JP	J$77FF

?.403A:	JP	J$781B

?.403D:	JP	C.77F1

?.4040:	JP	J$5283

?.4043:	JP	J$41D5

?.4046:	JP	C.48EA

?.4049:	JP	J$7AE9

?.404C:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H

C.4100:	JP	J.4199
?.4103:	JP	J$480D

C.4106:	DI	
	LD	A,1
	LD	(D.6C00),A		; select segments page 1
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	0CH	; 12 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,C
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,B
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,0
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,18
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	JP	J$4F3F

;	  Subroutine select fimware on page 1 and 2, validate firmware environment
;	     Inputs  ________________________
;	     Outputs ________________________

C$414A:	DI	
	LD	A,1
	LD	(D.6C00),A		; select segments page 1 (6000H-7FFFH)
	IN	A,(0A8H)
	LD	B,A			; store primairy slot register
	AND	30H			; keep page 2
	LD	H,A			; firmware primairy slot page 2 OR mask
	LD	A,B
	AND	3FH			; clear page 3
	LD	D,A
	LD	A,B
	AND	0CH			; keep page 1
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A		; select firmware primairy slot on page 3
	LD	A,(D.FFFF)
	CPL	
	LD	C,A			; store secundairy slot
	AND	30H			; keep page 2
	LD	L,A			; firmware secundairy slot page 2 OR mask
	LD	A,C
	AND	0CFH			; clear page 2
	LD	E,A
	LD	A,C
	AND	0CH			; keep page 1
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A		; select firmware secundairy slot on page 2
	LD	A,B
	AND	0CFH			; clear page 2
	LD	D,A
	LD	A,B
	AND	0CH			; keep page 1
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,0
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,18
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	POP	DE
	PUSH	HL			; store firmware slot page 2 OR masks
	PUSH	DE
	JP	J$4F42			; validate firmware environment

J.4199:	DI	
	LD	SP,I.DE3D
	LD	A,(CPMADR)
	LD	(D.D49F),A		; VDP read I/O port
	LD	A,(D.0007)
	LD	(D.D4A0),A		; VDP write I/O port
	CALL	C.44B0
	LD	A,81H
	LD	(D.6400),A		; select SRAM page 0
	LD	A,(H.STKE+1)
	LD	(D.3F57),A		; slot id firmware (SRAM)
	LD	(D.D468),A		; slot id firmware
	LD	A,3
	LD	(D.6400),A		; select ROM page 0
	LD	HL,H.STKE
	LD	B,5
J$41C4:	LD	(HL),0C9H
	INC	HL
	DJNZ	J$41C4			; clear H.STKE
	LD	DE,I$DB68
	LD	HL,(D$FC4A)
	AND	A
	SBC	HL,DE			; enough free BASIC memory ?
	JP	C,J.4685		; nope, no disk system
J$41D5:	DI	
	LD	SP,I.DE3D
	LD	HL,(D.D49F)
	PUSH	HL
	LD	A,4
	OUT	(0C0H),A		; select MSX-AUDIO register 4
	NOP	
	LD	A,18H			; mask EOS, mask BUF RDY, disable timers
	OUT	(0C1H),A
	XOR	A
	LD	HL,J.C200
	LD	DE,I.C201
	LD	BC,I.197E
	LD	(HL),A
	LDIR				; initialize variables
	POP	HL
	LD	(D.D49F),HL
	LD	BC,I$D1B1
	LD	(D$D1A0),BC
	LD	HL,C.0110
	LD	(D$D1B4),HL
	CALL	C$486A
	CALL	C.44B0
	LD	A,81H
	LD	(D.6400),A		; select SRAM page 0 (2000H-3FFFH)
	LD	A,(D$3F41)
	CP	03H
	JR	C,J$4217
	XOR	A
J$4217:	LD	(D.D18E),A
	LD	A,(D$3F47)
	CP	06H	; 6 
	JR	C,J$4222
	XOR	A
J$4222:	LD	(D.D497),A
	LD	A,(D.3F57)		; slot id firmware (SRAM)
	LD	(D.D468),A		; slot id firmware
	LD	A,(D.3F51)		; slot id MOUF1 (SRAM)
	LD	(D.D44E),A
	LD	A,3
	LD	(D.6400),A		; select ROM page 0 (2000H-3FFFH)
	CALL	C.42DB			; check for Matsushita 12x12 JIS
	CALL	C$4336
	LD	HL,D.D469
	CALL	C.514E			; determine slot id RAM page 0-3
	DI	
	LD	HL,D.D469
	LD	B,4
J$4248:	LD	A,(HL)
	CP	83H			; RAM in slot 3-3 ?
	JR	NZ,J$4252		; nope, no turbo
	INC	HL
	DJNZ	J$4248
	JR	J$4257

J$4252:	LD	HL,D.D49E
	SET	7,(HL)			; set no turbo flag
J$4257:	CALL	C.47ED			; select turbo CPU
	EI	
	CALL	C$4ED7
	CALL	C$4916			; initialize SRAM if required
	CALL	C$4F7F
	DI	
	CALL	C$4EE4
	EI	
	CALL	C.4FF8			; select MAIN ROM in page 0
	CALL	GICINI			; initialize PSG
	CALL	C.50BA			; restore slot in page 0

I$4272:	LD	A,7
	LD	(D.D49C),A
J$4277:	LD	A,(D.D49C)
	AND	A
	JR	Z,J$4288
	DEC	A
	JR	NZ,J$4285
	PUSH	AF
	CALL	C$4403			; start music
	POP	AF
J$4285:	LD	(D.D49C),A
J$4288:	LD	A,0
	CALL	C.444F			; change pallete of color 5
	CALL	C.4475
	JR	C,J.429E
	LD	A,1
	CALL	C.444F			; change pallete of color 5
	CALL	C.4475
	JR	C,J.429E
	JR	J$4277			; again

J.429E:	PUSH	HL
	LD	A,0
	CALL	C.444F			; change pallete of color 5
	POP	HL
	PUSH	HL
	CALL	C.442F			; stop music
	POP	HL
	LD	A,(H.PHYD+0)
	CP	0F7H			; MSX-DISK ?
	JR	Z,J$42D6		; yep,
	EX	DE,HL
	LD	HL,I$46CC
	AND	A
	SBC	HL,DE
	JR	Z,J.42D5
	LD	HL,I$46D5
	AND	A
	SBC	HL,DE
	JR	Z,J.42D5
	LD	HL,I$46DE
	AND	A
	SBC	HL,DE
	JR	Z,J.42D5
	LD	HL,I$471A
	AND	A
	SBC	HL,DE
	JR	Z,J.42D5
	LD	DE,I$472E
J.42D5:	EX	DE,HL
J$42D6:	LD	DE,I$4272
	PUSH	DE
	JP	(HL)

;	  Subroutine check for Matsushita 12x12 JIS
;	     Inputs  ________________________
;	     Outputs ________________________

C.42DB:	LD	D,0			; no Matsushita 12x12 JIS support
	LD	A,0F7H
	OUT	(40H),A			; select Matsushita 12x12 JIS switchable I/O
	IN	A,(40H)
	CP	08H			; JIS1 selected ?
	JR	Z,J$430D		; yep,
	LD	A,1
	OUT	(42H),A			; select JIS1
	XOR	A
	OUT	(47H),A			; row = 0
	OUT	(48H),A			; col = 0
	IN	A,(49H)
	IN	A,(49H)
	LD	A,14
	OUT	(47H),A			; row = 14
	LD	A,5FH
	OUT	(48H),A			; col = 5FH
	LD	C,00H
	LD	B,8
J$4300:	IN	A,(49H)
	ADD	A,C
	LD	C,A
	DJNZ	J$4300
	LD	B,4CH	; "L"
	CP	B			; Matsushita 12x12 JIS1 ?
	JR	NZ,J$430F		; nope,
	SET	6,D			; Matsushita 12x12 JIS1 with select
J$430D:	SET	0,D			; Matsushita 12x12 JIS1
J$430F:	IN	A,(41H)
	CP	08H			; JIS2 selected ?
	JR	Z,J$432F		; yep, quit
	LD	A,2
	OUT	(42H),A			; JIS2
	LD	A,25H
	OUT	(47H),A			; row =
	LD	A,5EH
	OUT	(48H),A			; col =
	IN	A,(49H)
	CP	41H			; Matsushita 12x12 JIS2 ?
	JR	NZ,J.4331		; nope,
	IN	A,(49H)
	CP	42H			; Matsushita 12x12 JIS2 ?
	JR	NZ,J.4331		; nope,
	SET	7,D			; Matsushita 12x12 JIS2 with select
J$432F:	SET	1,D			; Matsushita 12x12 JIS2
J.4331:	LD	A,D
	LD	(D$D49D),A		; update flag
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$4336:	DI	
	XOR	A
	LD	(D.D49E),A		; clear flags
	CALL	C$43CA			; check if ? extension
	JP	C,J$43C9		; nope, quit
	LD	HL,D.D49E
	SET	6,(HL)			; set ? extension flag
	IN	A,(0AAH)
	AND	0F0H
	OR	07H
	OUT	(0AAH),A		; select keyboard row 7
	IN	A,(0A9H)
	AND	40H			; SELECT key pressed ?
	JR	NZ,J$4359		; nope, skip
	LD	HL,D.D49E
	SET	7,(HL)			; set no turbo flag
J$4359:	XOR	A
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,6
	LD	(D.6000),A
	LD	A,7
	LD	(D.6400),A		; select segments page 0
	CALL	C$4FF4			; check if panasonic firmware in slot 3-3
	LD	A,0
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,2
	LD	(D.6000),A
	LD	A,3
	LD	(D.6400),A		; select segments page 0
	LD	D,0			; assume type = 0
	JR	NC,J.43B8		; no panasonic firmware,
	IN	A,(0A8H)
	LD	B,A			; store primairy slot register
	AND	0FH
	OR	0F0H
	OUT	(0A8H),A		; select primairy slot 3 on page 2 and 3
	LD	D,A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A			; store secundairy slot register
	AND	0CFH
	OR	30H			; select secundairy slot 3 on page 2
	LD	(D.FFFF),A
	LD	A,D
	AND	3FH
	LD	D,A
	LD	A,B			; restore primairy slot register
	AND	0C0H			; keep page 3
	OR	D
	OUT	(0A8H),A
	PUSH	BC
	CALL	C$4949			; check for FS-A1FX
	LD	D,1
	POP	BC
	PUSH	AF			; store result
	LD	A,B			; restore primairy slot register
	AND	3FH
	OR	0C0H			; select primairy slot 3 on page 3
	OUT	(0A8H),A
	LD	A,C			; restore secundairy slot register
	LD	(D.FFFF),A
	LD	A,B			; restore primairy slot register
	OUT	(0A8H),A
	POP	AF			; restore result
	JR	NC,J.43B8		; not an FS-A1FX, type = 1
	LD	D,2			; type = 2
J.43B8:	LD	A,D
	CP	2			; FS-A1FX ?
	JR	NZ,J$43C2		; nope, skip
	LD	HL,D.D49E
	SET	7,(HL)			; set no turbo flag
J$43C2:	LD	A,(D.D49E)
	OR	D
	LD	(D.D49E),A
J$43C9:	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$43CA:	XOR	A
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,90H
	LD	(D.6000),A		; select ? page 0 (0000H-1FFFH)
	LD	DE,0
	LD	HL,0
	LD	BC,128
J$43DC:	PUSH	HL
	LD	A,(HL)
	LD	H,0
	LD	L,A
	ADD	HL,DE
	PUSH	HL
	POP	DE
	POP	HL
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$43DC
	LD	HL,I$0EAA
	AND	A
	SBC	HL,DE
	JR	NZ,J$43F6
	AND	A
	JR	J$43F7

J$43F6:	SCF	
J$43F7:	PUSH	AF
	XOR	A
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,2
	LD	(D.6000),A		; select ROM page 0
	POP	AF
	RET	

;	  Subroutine start music
;	     Inputs  ________________________
;	     Outputs ________________________

C$4403:	LD	A,(D.D49E)
	BIT	6,A			; ? extension found ?
	JR	NZ,J$442E		; yep, quit
	DI	
	LD	A,44
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	LD	A,(D.D468)
	LD	C,A			; slot id firmware
	CALL	C.489E			; select firmware in page 2
	LD	A,0FFH
	LD	(D.D49B),A
	EI	
	LD	HL,J.C200
	CALL	C$4FB3			; initialize MSX-MUSIC
	XOR	A
	LD	HL,I.A400
	CALL	C$4FC0			; start MSX-MUSIC song
J$442E:	RET	

;	  Subroutine stop music
;	     Inputs  ________________________
;	     Outputs ________________________

C.442F:	LD	A,(D.D49E)
	BIT	6,A			; ? extension found ?
	JR	NZ,J$444E		; yep. quit
	LD	A,(D.D49B)
	AND	A
	JR	Z,J$4445
	CALL	C$4FCD			; stop MSX-MUSIC song
	DI	
	XOR	A
	LD	(D.D49B),A
	EI	
J$4445:	CALL	C.4FF8			; select MAIN ROM in page 0
	CALL	GICINI			; initialize PSG
	CALL	C.50BA			; restore slot in page 0
J$444E:	RET	

;
;	  Subroutine change pallete of color 5
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.444F:	DI	
	PUSH	AF
	CALL	C.5254			; wait for VDP ready
	LD	E,5
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,E
	OUT	(C),A
	LD	A,90H
	OUT	(C),A
	POP	AF
	LD	HL,I$44AC
	ADD	A,A
	LD	D,0
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	INC	C
	OUT	(C),A
	INC	HL
	LD	A,(HL)
	OUT	(C),A
	EI	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4475:	LD	B,3
J$4477:	LD	A,0FFH
J$4479:	PUSH	AF
	PUSH	BC
	LD	IX,I$44ED
	CALL	C.4D51
	JP	C,J.44A8
	LD	B,A
	LD	HL,I$4725
	LD	A,(D$CB65)
	AND	01H	; 1 
	JR	NZ,J$4497
	LD	A,(D$CB63)
	AND	03H	; 3 
	JR	Z,J.44A8
J$4497:	LD	A,B
	AND	A
	JR	Z,J$449E
	CALL	C.442F			; stop music
J$449E:	POP	BC
	POP	AF
	SUB	01H	; 1 
	JR	NZ,J$4479
	DJNZ	J$4477			; next
	AND	A
	RET	

J.44A8:	POP	BC
	POP	AF
	SCF	
	RET	

I$44AC:	LD	H,D
	INC	B
	LD	B,A
	DEFB	6

C.44B0:	DI
	LD	A,0
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,2
	LD	(D.6000),A
	INC	A
	LD	(D.6400),A		; select segments page 0
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	0CH	; 12 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	E,A
	LD	A,C
	AND	0CH	; 12 
	RRCA	
	RRCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,B
	AND	0CH	; 12 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	RET	

I$44ED:	LD	(BC),A
	OR	44H	; "D"
	RST	38H
	RST	38H
	INC	SP
	LD	B,L
	RST	38H
	RST	38H
	LD	A,(BC)
	LD	C,34H	; "4"
	LD	A,E
	LD	C,E
	LD	D,D
	LD	B,L
	LD	C,4EH	; "N"
	LD	A,E
	LD	H,L
	CALL	PO,C$0E47
;
	LD	L,B
	LD	A,E
	LD	A,A
	LD	(HL),A
	LD	B,A
	LD	C,82H
	LD	A,E
	SBC	A,C
	ADC	A,A
	LD	B,(HL)
	LD	C,9CH
	LD	A,E
	OR	E
	AND	B
	LD	B,(HL)
	ADD	A,C
	INC	(HL)
	XOR	4BH	; "K"
	OR	C
	LD	B,(HL)
	ADD	A,C
	LD	C,(HL)
	XOR	65H	; "e"
	CALL	Z,C$8146
;
	LD	L,B
	XOR	7FH
	PUSH	DE
	LD	B,(HL)
	ADD	A,C
	ADD	A,D
	XOR	99H
	SBC	A,46H	; "F"
	ADD	A,C
	SBC	A,H
	XOR	0B3H
	LD	A,(DE)
	LD	B,A
	LD	A,(BC)
	LD	SP,I$4552
	LD	(D$47E4),A
	INC	SP
	LD	(HL),A
	LD	B,A
	INC	(HL)
	ADC	A,A
	LD	B,(HL)
	DEC	(HL)
	AND	B
	LD	B,(HL)
	LD	(HL),0B1H
	LD	B,(HL)
	SCF	
	CALL	Z,C$3846
;
	PUSH	DE
	LD	B,(HL)
	ADD	HL,SP
	SBC	A,46H	; "F"
	JR	NC,J$456B
;
	LD	B,A
I$4552:	LD	B,00H
	LD	C,00H
	LD	D,00H
	JP	J.455B

J.455B:	DI	
	LD	(D$DE3E),SP
	LD	SP,I.DE3D
	LD	A,0C9H
	LD	(EXTBIO+0),A
	PUSH	BC
	PUSH	DE
	LD	A,(D.D18E)
J$456B	EQU	$-2
	LD	H,A
	LD	A,(D.D497)
	LD	L,A
	PUSH	HL
	LD	A,(D.D468)		; slot id firmware
	PUSH	AF
	LD	HL,(D.D49F)
	PUSH	HL
	LD	A,(D.D49E)
	PUSH	AF			; store flags
	XOR	A
	LD	HL,J.C200
	LD	DE,I.C201
	LD	BC,I.197E
	LD	(HL),A
	LDIR				; initialize variables
	POP	AF			; restore flags
	LD	(D.D49E),A
	POP	HL
	LD	(D.D49F),HL
	POP	AF			; restore slot id
	LD	(D.D468),A		; slot id firmware
	POP	HL
	LD	A,L
	LD	(D.D497),A
	LD	A,H
	LD	(D.D18E),A
	POP	DE
	POP	BC
	LD	A,B
	LD	(D.CBB8),A
	LD	(D$D457),A
	LD	A,C
	LD	(D.CBB9),A
	LD	(D$DB29),A
	LD	A,D
	LD	(D$D450),A
	DI	
	CALL	C.42DB			; check for Matsushita 12x12 JIS
	LD	A,81H
	LD	(D.6400),A		; select SRAM page 0
	LD	A,(D.3F51)		; slot id MOUF1 (SRAM)
	LD	(D.D44E),A
	LD	A,3
	LD	(D.6400),A		; select ROM page 0
	LD	A,(D.CBB9)
	LD	B,A
	LD	A,(D.CBB8)
	OR	B
	JP	NZ,J$461D
	LD	A,81H
	LD	(D.6400),A		; select SRAM page 0
	LD	A,(D$3F42)
	AND	09H	; 9 
	LD	(D.DAE4),A
	LD	A,(D$3F43)
	AND	A
	JR	Z,J.45EC
	CP	0FFH
	JR	Z,J.45EC
	XOR	A
J.45EC:	LD	(D.CF17),A
	LD	A,(D$3F44)
	CP	02H	; 2 
	JR	C,J$45F7
	XOR	A
J$45F7:	LD	(D.D553),A
	LD	A,(D$3F45)
	AND	A
	JR	Z,J.4605
	CP	0FFH
	JR	Z,J.4605
	XOR	A
J.4605:	LD	(D.CBB1),A
	LD	A,(D$3F46)
	AND	A
	JR	Z,J.4613
	CP	0FFH
	JR	Z,J.4613
	XOR	A
J.4613:	LD	(D.D466),A
	LD	A,3
	LD	(D.6400),A		; select ROM page 0
	JR	J$4633

J$461D:	XOR	A
	LD	(D.D18E),A
	LD	(D.D497),A
	LD	(D.CF17),A
	LD	(D.D553),A
	LD	(D.CBB1),A
	LD	(D.D466),A
	LD	(D.DAE4),A
J$4633:	LD	A,(H.PHYD+0)
	CP	0F7H			; MSX-DISK ?
	JR	NZ,J.4685		; nope, no disk system
	CALL	C.4FF8			; select MAIN ROM in page 0
	CALL	C$48D4
	CALL	C.50BA			; restore slot in page 0
	LD	HL,D.D469
	CALL	C.514E			; determine slot id RAM page 0-3
	CALL	C.47ED			; select turbo CPU
	DI	
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46B)
	LD	H,A			; slot id RAM page 2
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A		; select RAM on page 2
	CALL	C$4EFE
	EI	
	CALL	C$5538
	RET	

J.4685:	CALL	C$4F4B
	JR	J.468D

?.468A:	CALL	C$4F58
J.468D:	JR	J.468D

?.468F:	LD	A,0C9H
	LD	(EXTBIO+0),A
	CALL	C.47ED			; select turbo CPU
	LD	A,22H
	CALL	C.5E42			; select firmware slot and segment on page 2
	EI	
	JP	C.8000

?.46A0:	LD	A,0C9H
	LD	(EXTBIO+0),A
	CALL	C.47ED			; select turbo CPU
	LD	A,22H	; """
	CALL	C.5E42			; select firmware slot and segment on page 2
	EI	
	JP	C.8003

?.46B1:	CALL	C$4F8C
	LD	A,(D$D44F)
	OR	A
	JR	Z,J$46CB
	LD	A,0C9H
	LD	(EXTBIO+0),A
	CALL	C.47ED			; select turbo CPU
	LD	A,22H	; """
	CALL	C.5E42			; select firmware slot and segment on page 2
	EI	
	JP	C.8006

J$46CB:	RET	

I$46CC:	LD	A,0FFH
	LD	(D.D1BC),A
	CALL	C$4F65
	RET	

I$46D5:	LD	A,0FFH
	LD	(D.D1BC),A
	CALL	C$4F72
	RET	

I$46DE:	CALL	C$4F0B
	CALL	C.4FF8			; select MAIN ROM in page 0
	LD	A,7
	LD	(D$FCAF),A		; screen mode = 7
	CALL	C$005F			; change screen mode
	CALL	C$0069
	CALL	C.50BA			; restore slot in page 0
	DI	
	XOR	A
	OUT	(0F5H),A		; disable internal hardware
	LD	A,(D.D49E)
	BIT	1,A			; FS-A1FX ?
	JR	NZ,J$4706		; yep, skip
	IN	A,(0F4H)
	DEFB	0,0,0
	AND	7FH
	OUT	(0F4H),A		; soft reset
J$4706:	LD	A,(D.D468)
	LD	C,A			; slot id firmware
	CALL	C.489E			; select firmware in page 2
	LD	A,18
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	EI	
	JP	J$4F45

I$471A:	LD	A,(D.D49E)
	BIT	6,A			; ? extension found ?
	JR	Z,J$4724		; nope, quit
	CALL	C$4FE7
J$4724:	RET	

I$4725:	LD	B,0FFH
	LD	C,00H
	LD	D,00H
	JP	J.455B

I$472E:	LD	HL,I$4752
	LD	DE,I.D14F
	LD	BC,I.0011
	LDIR	
	LD	IX,I.D14F
J$473B	EQU	$-2
	CALL	C.4EF1
	LD	A,70H	; "p"
	CALL	C.4F32
J$4745:	LD	IX,I$4763
	CALL	C.4D51
	JR	NC,J$4745
	CALL	C.4D6B
	RET	

I$4752:	DEC	BC
	INC	BC
	JR	Z,J$4759
J$4755	EQU	$-1
;
	INC	D
	LD	A,(BC)
	JR	NZ,J$46E9
J$4759	EQU	$-1
;
	ADC	A,B
	SUB	A
	SBC	A,L
	ADC	A,D
	LD	L,L
	SUB	H
	LD	B,(HL)
	JR	NZ,J$4762
J$4762	EQU	$-1
;
I$4763:	LD	(BC),A
	LD	L,H
	LD	B,A
	RST	38H
	RST	38H
	LD	(HL),E
	LD	B,A
	RST	38H
	RST	38H
	LD	BC,I$4BB4
	CALL	Z,FCB1.1
;
	NOP	
J$4773:	LD	BC,D.0007
	NOP	
	LD	HL,I$47A4
	LD	DE,I.D14F
	LD	BC,I.0011
	LDIR	
	LD	IX,I.D14F
	CALL	C.4EF1
;
	LD	A,60H	; "`"
	CALL	C.4F32
;
J$478E:	LD	IX,I$47B5
J$4791	EQU	$-1
	CALL	C.4D51
	JR	NC,J$478E
;
	PUSH	HL
	CALL	C.4D6B
;
	POP	HL
	LD	A,H
	OR	L
	JR	Z,J$47A3
	CALL	C$47DB
;
J$47A3:	RET	

I$47A4:	DEC	C
	LD	(BC),A
	INC	H
	INC	B
	LD	E,0AH	; 10 
	JR	NZ,J$473B
;
	ADC	A,B
	SUB	A
	SBC	A,L
	ADC	A,D
	LD	L,L
	SUB	H
	LD	B,(HL)
	JR	NZ,J$47B4
J$47B4	EQU	$-1
;
I$47B5:	LD	(BC),A
	CP	(HL)
	LD	B,A
	RST	38H
	RST	38H
	POP	DE
	LD	B,A
	RST	38H
	RST	38H
	INC	BC
	ADD	A,B
	JR	C,J$4755
;
	LD	C,D
	DEFB	0,0
	SUB	H
	JR	C,J$4773
;
	LD	C,D
	DEFB	0,0
	XOR	H
	JR	C,J$4791
;
	LD	C,D
	LD	BC,I$0300
	DEC	DE
	DEFB	0,0
	RLCA	
	DEFB	0,0
	DEC	BC
	LD	BC,I$0600
C$47DB	EQU	$-1
	NOP	
	LD	C,0FFH
	LD	D,00H
	JP	J.455B

D$47E4:	LD	B,00H
	LD	C,00H
	LD	D,01H	; 1 
	JP	J.455B

;	  Subroutine select turbo CPU
;	     Inputs  ________________________
;	     Outputs ________________________

C.47ED:	LD	A,(D.D49E)
	BIT	7,A			; no turbo flag ?
	JR	NZ,J.480C		; yep, quit
	LD	HL,D.D469
	LD	B,4
J$47F9:	LD	A,(HL)
	CP	83H			; RAM in slot 3-3 ?
	JR	NZ,J.480C		; nope, quit
	INC	HL
	DJNZ	J$47F9
	DI	
	LD	A,08H
	OUT	(40H),A			; Matsushita switchable I/O
	IN	A,(41H)
	AND	0FEH
	OUT	(41H),A			; select turbo CPU
J.480C:	RET	

J$480D:	CALL	C$414A			; select fimware on page 1 and 2, validate firmware environment
	POP	HL			; restore firmware slot page 2 OR masks
	JP	C,J$4827		; firmware enviroment should not start
	LD	(H.STKE+1),A
	LD	HL,I$C010
	LD	DE,I$C010+1
	LD	BC,6-1
	LD	(HL),0
	LDIR				; no environment
	JP	J.4199			; intialize firmware ROM

J$4827:	DI	
	IN	A,(0A8H)
	LD	B,A
	AND	3FH			; clear page 3
	LD	D,A			; store primairy slot register
	LD	A,H
	RLCA	
	RLCA	
	AND	0C0H			; firmware primairy slot page 3 OR mask
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	AND	0CFH			; clear page 2
	OR	L			; firmware secundairy slot page 2 OR mask
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH			; clear page 2
	OR	H			; firmware primairy slot page 2 OR mask
	OUT	(0A8H),A
	LD	HL,I$4854
	LD	DE,J.C200
	LD	BC,I.0016
	LDIR				; helper routine in page 3
	JP	J.C200			; start helper routine

I$4854:	LD	A,12
	LD	(D$6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	EI	
	CALL	C$402B
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$486A:	LD	A,0FFH
	LD	(D$CBAF),A
	LD	A,0CH	; 12 
	OUT	(0ABH),A
	XOR	A
	LD	(D$CB7A),A
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	OR	80H
	OUT	(0A1H),A
	LD	A,0FFH
	LD	(D$CBB2),A
	LD	HL,I$CB7B
	LD	(D$CB76),HL
	LD	(D$CB78),HL
	LD	HL,I$CBB0
	LD	(HL),A
	LD	A,0FFH
	LD	(D$CBBB),A
	LD	(D$CBBA),A
	RET	

;	  Subroutine select firmware in page 2
;	     Inputs  ________________________
;	     Outputs ________________________

C.489E:	IN	A,(0A8H)
	LD	B,A			; store primairy slot register
	AND	3FH
	LD	D,A
	LD	A,C			; slot id firmware
	LD	H,A
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	AND	0CFH			; clear page 2
	LD	E,A
	LD	A,H			; slot id firmware
	AND	0CH
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH			; clear page 2
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	RET	

J$48CC:	LD	A,(DE)
	CP	(HL)
	RET	NZ
	INC	DE
	INC	HL
	DJNZ	J$48CC
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$48D4:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,255
J$48DB:	PUSH	BC
	CALL	H.TIMI
	DI	
	POP	BC
	DEC	B
	JR	NZ,J$48DB
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	

;	  Subroutine calculate checksum
;	     Inputs  ________________________
;	     Outputs ________________________

C.48EA:	CALL	C.52BC			; select firmware on page 2
	EX	AF,AF'
	LD	A,80H			; segment = SRAM
	CALL	C.5E42			; select firmware slot and segment on page 2
	LD	IX,I.B400
	LD	BC,I$0B41
	LD	HL,I.0000
	LD	DE,I.0000
J$4900:	LD	E,(IX)
	ADD	HL,DE
	INC	IX
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$4900
	LD	DE,(D.BF58)
J$490F:	CALL	C.5EB9			; restore slot and segement on page 2
	CALL	C.531A			; restore slot on page 2
	RET	

;	  Subroutine initialize SRAM if required
;	     Inputs  ________________________
;	     Outputs ________________________

C$4916:	CALL	C.48EA			; calculate checksum
	AND	A
	SBC	HL,DE			; checksum correct ?
	JR	Z,J$4940		; yep, quit
	CALL	C.52BC			; select firmware on page 2
	EX	AF,AF'
	LD	A,80H			; segment = SRAM
	CALL	C.5E42			; select firmware slot and segment on page 2
	LD	HL,I.B400
	LD	DE,I.B400+1
	LD	BC,I$0B40
	LD	(HL),00H
	LDIR				; initialize SRAM
	LD	HL,0
	LD	(D.BF58),HL		; update checksum
	CALL	C.5EB9			; restore slot and segement on page 2
	CALL	C.531A			; restore slot on page 2
J$4940:	RET	

I$4941:	DEFB	"FS-A1FX "

;	  Subroutine check for FS-A1FX
;	     Inputs  ________________________
;	     Outputs ________________________

C$4949:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I$4941
	LD	DE,I$BFF0
	LD	BC,8
J$4955:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$4963
	INC	HL
	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$4955
	AND	A
	JR	J$4964

J$4963:	SCF	
J$4964:	POP	HL
	POP	DE
	POP	BC
	RET	

?.4968:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8063
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4975:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8069
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4982:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8003
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.498F:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$806C
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.499C:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$806F
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.49A9:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8006
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$49B6:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80FF
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.49C3:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8060
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.49D0:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800C
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.49DD:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800F
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.49EA:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8012
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$49F7:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8072
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A04:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$807B
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A11:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8075
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4A1E:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8018
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4A2B:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.801B
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A38:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8066
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A45:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8021
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4A52:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8078
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A5F:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8027
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A6C:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.802A
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4A79:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$807E
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4A86:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8030
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4A93:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8081
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4AA0:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8036
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4AAD:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8039
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4ABA:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8045
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4AC7:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8048
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4AD4:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.804E
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4AE1:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$805A
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4AEE:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$805D
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4AFB:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8084
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B08:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800F
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B15:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8012
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B22:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8009
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B2F:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8087
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B3C:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$808A
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4B49:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800F
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B56:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8003
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B63:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8006
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4B70:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8039
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4B7D:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.803C
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B8A:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8009
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4B97:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800C
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4BA4:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$808D
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4BB1:	EX	AF,AF'
	LD	A,28H	; "("
I$4BB4:	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.802A
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4BBE:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$802D
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4BCB:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8030
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4BD8:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8033
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4BE5:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8027
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4BF2:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$809F
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4BFF:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80A2
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4C0C:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.804E
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4C19:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8036
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4C26:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80A5
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4C33:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8012
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4C40:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8015
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4C4D:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8018
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4C5A:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.801B
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4C67:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.801E
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4C74:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8021
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4C81:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8024
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4C8E:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80C6
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4C9B:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80EA
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4CA8:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80C9
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4CB5:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80CF
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4CC2:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80D2
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4CCF:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80B1
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4CDC:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80AE
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4CE9:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80B7
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4CF6:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80BA
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4D03:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80BD
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4D10:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80D8
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4D1D:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80DB
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4D2A:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80F9
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4D37:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8039
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4D44:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.803C
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.4D51:	EX	AF,AF'
	LD	A,2AH	; "*"
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	FCB2.1
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4D5E:	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800F
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.4D6B:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.0018
	CALL	C.5DE9			; restore slot and segment on page 0
	RET

?.4D78:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80FC
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

?.4D85:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80D5
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$4D92:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8102
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

?.4D9F:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80A8
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

?.4DAC:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80AB
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

?.4DB9:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8126
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

?.4DC6:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80F0
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4DD3:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$80C3
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4DE0:	EX	AF,AF'
	LD	A,2AH	; "*"
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.0074
	CALL	C.5DE9			; restore slot and segment on page 0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4DED:	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$804B
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4DFA:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C$00D7
	CALL	C.5DE9			; restore slot and segment on page 0
;
	RET	

?.4E07:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8114
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4E14:	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8003
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4E21:	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8006
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

?.4E2E:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.801E
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4E3B:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	RDSLT
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4E48:	EX	AF,AF'
	LD	A,1EH
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8003
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4E55:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.0003
	CALL	C.5DE9			; restore slot and segment on page 0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4E62:	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8009
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4E6F:	EX	AF,AF'
	LD	A,1EH
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8006
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4E7C:	EX	AF,AF'
	LD	A,1EH
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8009
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4E89:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.0110
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4E96:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C$0041
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

?.4EA3:	EX	AF,AF'
	LD	A,18H
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8054
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4EB0:	EX	AF,AF'
	LD	A,18H
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.804E
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4EBD:	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8000
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4ECA:	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8009
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4ED7:	EX	AF,AF'
	LD	A,2
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.0009
	CALL	C.5DE9			; restore slot and segment on page 0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4EE4:	EX	AF,AF'
	LD	A,2
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.000C			; vdp register 1
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4EF1:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C$0015
	CALL	C.5DE9			; restore slot and segment on page 0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4EFE:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C$0050
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F0B:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C$009B
	CALL	C.5DE9			; restore slot and segment on page 0			; restore slot and segment on page 0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4F18:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C.0074
	CALL	C.5DE9			; restore slot and segment on page 0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F25:	EX	AF,AF'
	LD	A,1AH
	CALL	C.5D76			; select firmware slot and segment on page 0
	CALL	C$0044
	CALL	C.5DE9			; restore slot and segment on page 0
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4F32:	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800C
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

J$4F3F:	JP	J$8105

J$4F42:	JP	J$810E			; validate firmware environment

J$4F45:	JP	J$8108

?.4F48:	JP	J$812C

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$4F4B:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$810B
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F58:	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8111
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F65:	EX	AF,AF'
	LD	A,1EH
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8012
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F72:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8033
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F7F:	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8057
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F8C:	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8072
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F99:	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8039
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4FA6:	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$8051
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;	  Subroutine initialize MSX-MUSIC
;	     Inputs  ________________________
;	     Outputs ________________________

C$4FB3:	EX	AF,AF'
	LD	A,44
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$A1C3			; INIOPL
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;
;	  Subroutine start MSX-MUSIC song
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4FC0:	EX	AF,AF'
	LD	A,44
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$A1C6			; MSTART
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;
;	  Subroutine stop MSX-MUSIC song
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4FCD:	EX	AF,AF'
	LD	A,44
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C$A1C9			; MSTOP
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

?.4FDA:	EX	AF,AF'
	LD	A,18H
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.800F
	CALL	C.5EB9			; restore slot and segement on page 2
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4FE7:	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.5E42			; select firmware slot and segment on page 2
	CALL	C.8045
	CALL	C.5EB9			; restore slot and segement on page 2
;
	RET	

;	  Subroutine check if panasonic firmware
;	     Inputs  ________________________
;	     Outputs ________________________
;

C$4FF4:	CALL	C$0125
	RET	

;
;	  Subroutine select MAIN ROM in page 0
;	     Inputs  ________________________
;	     Outputs ________________________

C.4FF8:	DI	
	CALL	C.50A7			; disable H.KEYI handler
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	A,(D.FCC1)
	LD	E,A			; slot id MAIN ROM
	RRCA	
	RRCA	
	AND	0C0H
	LD	D,A
	LD	A,B
	AND	3FH	; "?"
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	D,A
	LD	A,E
	RRCA	
	RRCA	
	AND	03H	; 3 
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,E
	AND	03H	; 3 
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+11)
	LD	(IX+9),A
	LD	A,(IX+10)
	LD	(IX+8),A
	LD	(IX+11),B		; store primairy slot register
	LD	(IX+10),C		; store secundairy slot register
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	

;
;	  Subroutine select MAIN ROM in page 0
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5050:	DI	
	CALL	C.50A7			; disable H.KEYI handler
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	A,(D.FCC1)
	LD	E,A			; slot id MAIN ROM
	RRCA	
	RRCA	
	AND	0C0H
	LD	D,A
	LD	A,B
	AND	3FH	; "?"
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	D,A
	LD	A,E
	RRCA	
	RRCA	
	AND	03H	; 3 
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,E
	AND	03H
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+11)
	LD	(IX+9),A
	LD	A,(IX+10)
	LD	(IX+8),A
	LD	(IX+11),B		; store primairy slot register
	LD	(IX+10),C		; store secundairy slot register
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.50A7:	PUSH	AF
	PUSH	BC
	LD	A,(D.FD9A)
	LD	(D.CE6C),A
	LD	A,0C9H
	LD	(D.FD9A),A
	CALL	C.5254			; wait for VDP ready
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine restore slot in page 0
;	     Inputs  ________________________
;	     Outputs ________________________

C.50BA:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)		; restore primairy slot register
	LD	C,(IX+10)		; restore secundairy slot register
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.FCC1)		; slot id MAIN ROM
	RRCA	
	RRCA	
	AND	0C0H
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(D.CE6C)
	LD	(D.FD9A),A		; enable H.KEYI handler
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5108:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,I$D4F7
	LD	(IX+2),A
	LD	A,(D$D477)
	LD	L,A
	LD	BC,I.0000
	LD	A,(D.D482)
	SUB	L
	JR	C,J$5123
;
	LD	B,A
J$5123:	LD	A,(D.D483)
	SUB	L
	JR	C,J$512A
;
	LD	C,A
J$512A:	LD	A,(D.D47F)
	CP	B
	JR	NC,J$5131
;
	LD	A,B
J$5131:	LD	(IX),A
	LD	A,(D.D480)
	CP	C
	JR	C,J$513B
;
	LD	A,C
J$513B:	INC	A
	LD	(IX+1),A
	LD	A,11H	; 17 
	LD	(D$D4C6),A
	CALL	C$4DED
;
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;	  Subroutine determine slot id RAM page 0-3
;	     Inputs  ________________________
;	     Outputs ________________________

C.514E:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C$5050			; select MAIN ROM in page 0
	PUSH	HL
	POP	IX
	LD	BC,4000H		; page size = 16 KB
	IN	A,(0A8H)
	AND	0C0H
	RLCA	
	RLCA	
	LD	E,A			; primairy slot page 3
	CALL	C.51CF			; get slot info
	RLCA				; is slot expanded ?
	JR	C,J$5170		; yep,
	LD	A,E			; slot id
	JR	J$517D

J$5170:	LD	A,(D.FFFF)
	CPL	
	AND	0C0H
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	OR	E
	OR	80H			; slot id
J$517D:	LD	(IX+3),A		; store slot id RAM page 3
	LD	E,8FH			; slot id = 3-3
J$5182:	LD	HL,0			; page 0
J$5185:	CALL	C.51CF			; get slot info
	RLCA				; is slot expanded ?
	JR	C,J$5199		; yep,
	LD	A,73H
	AND	E
	LD	D,A			; slot id
	CALL	C.51F5			; test if page of slot is writeable
	JR	C,J.51B1		; nope,
	CALL	C.51E0			; update slot id RAM
	JR	J.51B1			; next page

J$5199:	LD	A,E
J$519A:	OR	80H
	LD	D,A
	CALL	C.51F5			; test if page of slot is writeable
	JR	C,J$51A5		; nope,
	CALL	C.51E0			; update slot id RAM
J$51A5:	LD	A,D
	AND	7FH
	LD	D,04H	; 4 
	SUB	D
	LD	D,A
	JP	M,J.51B1		; finished, next primairy slot
	JR	J$519A			; next secundairy slot

J.51B1:	AND	A
	ADD	HL,BC			; next page
	LD	A,0C0H
	CP	H			; page 3 ?
	JR	NZ,J$5185		; nope, next page
	LD	A,3
	AND	E
	DEC	E
	DEC	A
	JP	M,J$51C2		; finished,
	JR	J$5182			; next slot

J$51C2:	CALL	C.50BA			; restore slot in page 0
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	

;	  Subroutine get slot info
;	     Inputs  ________________________
;	     Outputs ________________________

C.51CF:	PUSH	HL
	PUSH	DE
	LD	HL,D.FCC1
	LD	A,03H
	AND	E
	LD	E,A
	LD	D,0
	AND	A
	ADD	HL,DE
	LD	A,(HL)
	POP	DE
	POP	HL
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.51E0:	PUSH	HL
	PUSH	DE
	PUSH	AF
	LD	A,H
	AND	0C0H
	RLCA	
	RLCA	
	LD	E,A
	LD	D,00H
	PUSH	IX
	POP	HL
	AND	A
	ADD	HL,DE
	POP	AF
	LD	(HL),A
	POP	DE
	POP	HL
	RET	

;	  Subroutine test if page of slot is writeable
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.51F5:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	E,55H	; "U"
	CALL	C.5218			; test if slot is writeable
	JR	C,J.5214		; nope, quit
	LD	E,0AAH
	CALL	C.5218			; test if slot is writeable
	JR	C,J.5214		; nope, quit
	LD	BC,I.2000
	ADD	HL,BC
	CALL	C.5218			; test if slot is writeable
	JR	C,J.5214		; nope, quit
	LD	E,55H	; "U"
	CALL	C.5218			; test if slot is writeable
J.5214:	POP	HL
	POP	DE
	POP	BC
	RET	

	  Subroutine test if slot is writeable
;	     Inputs  ________________________
;	     Outputs ________________________

C.5218:	CALL	C$5222			; read from slot and store
	CALL	C$522F			; write to slot and check if writeable
	CALL	C$5246			; restore and write to slot
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5222:	PUSH	AF
	PUSH	BC
	PUSH	DE
	CALL	RDSLT
	PUSH	AF
	POP	IY
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$522F:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	AF
	CALL	WRSLT
	POP	AF
	CALL	RDSLT
	POP	DE
	POP	BC
	CP	E
	JR	NZ,J$5243
	POP	AF
	AND	A
	JR	J$5245

J$5243:	POP	AF
	SCF	
J$5245:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5246:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IY
	POP	DE
	LD	E,D
	CALL	WRSLT
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.5254:	PUSH	AF
	PUSH	BC
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,02H	; 2 
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	CALL	C$5281
	LD	A,(D.D49F)
	INC	A
	LD	C,A
J$526B:	IN	A,(C)
	AND	01H	; 1 
	JR	NZ,J$526B
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,00H
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5281:	NOP	
	RET	

J$5283:	LD	A,03H	; 3 
	LD	HL,I.C000
	CALL	C.4F18
	CALL	C.52BC			; select firmware on page 2
	EX	AF,AF'
	LD	A,80H			; segment = SRAM
	CALL	C.5E42			; select firmware slot and segment on page 2
	LD	HL,I$A000
	LD	(HL),4DH	; "M"
	INC	HL
	LD	(HL),53H	; "S"
	INC	HL
	LD	(HL),58H	; "X"
	LD	HL,I.A400
	LD	(HL),4DH	; "M"
	INC	HL
	LD	(HL),53H	; "S"
	INC	HL
	LD	(HL),58H	; "X"
	CALL	C.5EB9			; restore slot and segement on page 2
	CALL	C.531A			; restore slot on page 2
	LD	A,02H	; 2 
	LD	HL,I.C000
	LD	DE,I$0200
	CALL	C.4F18
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.52BC:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$5313
	EI	
J$5313:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.531A:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$5361
;
	EI	
J$5361:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5368:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	XOR	A
	LD	(D.D4DA),A
	LD	A,(IX)
	CP	20H	; " "
	JR	NC,J$53AD
;
	LD	D,60H	; "`"
	LD	E,01H	; 1 
	LD	C,01H	; 1 
	CP	0CH	; 12 
	JP	Z,J.5418
;
	LD	D,70H	; "p"
	INC	C
	CP	0DH	; 13 
	JP	Z,J.5418
;
	LD	D,40H	; "@"
	LD	E,00H
	CP	1AH
	JP	Z,J.5418
;
	LD	D,30H	; "0"
	CP	1BH
	JP	Z,J.5418
;
	LD	D,20H	; " "
	CP	1CH
	JR	Z,J.5418
;
	LD	D,00H
	LD	E,02H	; 2 
	LD	A,01H	; 1 
	LD	(D.D4DA),A
	JR	J.5418

J$53AD:	CP	7FH
	JR	C,J$53B9
;
	CP	0A0H
	JR	C,J.53CF
;
	CP	0E0H
	JR	NC,J.53CF
;
J$53B9:	LD	A,(IX+1)
	LD	D,00H
	LD	E,01H	; 1 
	LD	C,03H	; 3 
	CP	02H	; 2 
	JR	Z,J.5418
;
	INC	C
	CP	03H	; 3 
	JR	Z,J.5418
;
	LD	C,01H	; 1 
	JR	J.5418

J.53CF:	LD	A,01H	; 1 
	LD	(D.D4DA),A
	LD	A,(IX+2)
	LD	D,00H
	LD	C,04H	; 4 
	CP	02H	; 2 
	JR	Z,J.53F5
;
	INC	C
	CP	03H	; 3 
	JR	Z,J.53F5
;
	LD	C,02H	; 2 
	LD	A,(D.D48A)
	OR	A
	JR	NZ,J.53F5
;
	LD	A,(D$CC49)
	OR	A
	JR	NZ,J.53F5
	CALL	C$5428
;
J.53F5:	LD	A,C
	LD	E,02H	; 2 
	CP	04H	; 4 
	JR	C,J.5418
;
	LD	A,(IX+3)
	AND	0F0H
	OR	A
	JR	Z,J.5418
;
	LD	E,0AH	; 10 
	CP	10H	; 16 
	JR	Z,J.5418
;
	LD	E,04H	; 4 
	CP	20H	; " "
	JR	Z,J.5418
;
	LD	E,0CH	; 12 
	CP	30H	; "0"
	JR	Z,J.5418
;
	LD	E,01H	; 1 
J.5418:	LD	A,D
	OR	E
	LD	(D.D4D8),A
	LD	A,C
	LD	(D.D4D9),A
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5428:	LD	A,(IX)
	CP	81H
	JR	NZ,J.544F
;
	LD	A,(IX+1)
	CP	41H	; "A"
	JR	C,J$543A
;
	CP	45H	; "E"
	JR	C,J$544C
;
J$543A:	CP	65H	; "e"
	JR	C,J.544F
;
	CP	7BH	; "{"
	JR	NC,J.544F
;
	AND	01H	; 1 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	SET	7,A
	LD	D,A
	RET	

J$544C:	LD	D,80H
	RET	

J.544F:	LD	D,00H
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5452:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.D48A)
	OR	A
	JR	NZ,J$5473
	CALL	C$5368
;
	LD	A,(D.D4D8)
	AND	07H	; 7 
	LD	H,00H
	LD	L,A
	LD	(D.D4DB),HL
	XOR	A
	LD	(D.D4DA),A
	JP	J.552A

J$5473:	LD	A,(IX)
	LD	B,61H	; "a"
	LD	D,01H	; 1 
	LD	E,01H	; 1 
	CP	0CH	; 12 
	JR	Z,J.549C
;
	LD	B,71H	; "q"
	LD	D,02H	; 2 
	CP	0DH	; 13 
	JR	Z,J.549C
;
	LD	B,40H	; "@"
	LD	E,00H
	CP	1AH
	JR	Z,J.549C
;
	LD	B,30H	; "0"
	CP	1BH
	JR	Z,J.549C
;
	LD	B,20H	; " "
	CP	1CH
	JR	NZ,J$54AB
;
J.549C:	LD	HL,D.D4D8
	XOR	A
	LD	(HL),B
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),A
	JR	J.552A

J$54AB:	LD	HL,I.0000
	LD	(D.D4D9),HL
	LD	(D.D4DB),HL
	LD	D,00H
J.54B6:	LD	A,(D$DB27)
	INC	A
	INC	A
	CP	D
	JR	Z,J.54F2
;
	INC	D
	LD	HL,I$5531
	LD	B,(HL)
	INC	HL
	LD	A,(IX)
J$54C7:	CP	(HL)
	JR	Z,J.54F2
;
	INC	HL
	DJNZ	J$54C7
;
	LD	HL,(D.D4D9)
	INC	HL
	LD	(D.D4D9),HL
	LD	HL,(D.D4DB)
	INC	HL
	LD	(D.D4DB),HL
	INC	IX
	LD	A,(IX)
	CP	02H	; 2 
	JR	NZ,J.54B6
;
	LD	HL,(D.D4D9)
	INC	HL
	INC	HL
	LD	(D.D4D9),HL
	INC	IX
	INC	IX
	JR	J.54B6

J.54F2:	LD	HL,(D.D4D9)
	LD	A,H
	OR	L
	JR	NZ,J$550E
;
	INC	HL
	LD	(D.D4D9),HL
	LD	(D.D4DB),HL
	LD	A,(IX+1)
	CP	02H	; 2 
	JR	NZ,J.5525
;
	INC	HL
	INC	HL
	LD	(D.D4D9),HL
	JR	J.5525

J$550E:	LD	A,(IX+1)
	CP	02H	; 2 
	JR	NZ,J.5525
;
	LD	HL,(D.D4D9)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.D4D9),HL
	LD	HL,(D.D4DB)
	INC	HL
	LD	(D.D4DB),HL
J.5525:	LD	A,01H	; 1 
	LD	(D.D4D8),A
J.552A:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

I$5531:	DEFB	06H,0DH,0CH,1AH,1BH,1CH,20H

C$5538	LD	A,21H
	CALL	C.4DFA
	RET	

J$553E:	EXX	
	LD	C,19H
	CALL	C.4E89
	RET	

J$5545:	PUSH	BC
	PUSH	AF
	EXX	
	LD	C,1CH
	CALL	C.4E89
	POP	AF
	CALL	C.5556
	POP	BC
	CALL	C.560E
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5556:	PUSH	BC
	LD	D,00H
	JR	J$5568

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.555B:	PUSH	BC
	PUSH	HL
	LD	HL,0
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L
	POP	HL
	LD	D,0FFH
J$5568:	LD	IX,I.FFEA
	ADD	IX,SP
	LD	SP,IX
	LD	(IX+11),A
	LD	A,01H	; 1 
	BIT	1,(IY+42)
J$5577	EQU	$-2
	JR	NZ,J$557C
	XOR	A
J$557C:	LD	(IX+10),A
	LD	(IX+12),D
	LD	(IX),C
	LD	(IX+1),B
	LD	A,(D.D48B)
	OR	A
	JR	Z,J$559C
	XOR	A
	LD	(D.D48B),A
	PUSH	IX
	CALL	C$4E48
	CALL	C$4E7C
	POP	IX
J$559C:	PUSH	IX
	LD	B,(IY+15)
	LD	C,(IY+17)
	EXX	
	LD	C,14H	; 20 
	CALL	C.4E89
	PUSH	IX
	POP	HL
	POP	IX
	LD	(IX+6),L
	LD	(IX+7),H
	LD	A,(HL)
	LD	(IX+8),A
	INC	HL
	LD	A,(HL)
	LD	(IX+9),A
	CALL	C$57A4
	LD	A,(D.D475)
	SUB	(IY+20)
	ADD	A,(IY+23)
	LD	C,A
	LD	A,(D.D482)
	ADD	A,(IY+29)
	CP	(IY+16)
	JR	NC,J$55DF
	LD	(IX+11),00H
	LD	B,(IY+27)
	JR	J$55EE

J$55DF:	LD	A,(D$D474)
	SUB	(IY+19)
	ADD	A,(IY+26)
	LD	B,(IY+27)
	LD	(D.D47F),A
J$55EE:	LD	L,(IX+8)
	LD	H,(IX+9)
	LD	A,(IX+11)
	BIT	0,(IX+12)
	CALL	Z,C.59CC
	CALL	NZ,C.5BF0
	LD	(IY+27),B
	LD	IX,I.0016
	ADD	IX,SP
	LD	SP,IX
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.560E:	PUSH	AF
	LD	D,00H
	JR	J$5620

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5613:	PUSH	AF
	PUSH	HL
	LD	HL,0
	OR	A
	SBC	HL,BC
	LD	B,H
	LD	C,L
	POP	HL
	LD	D,0FFH
J$5620:	LD	IX,I.FFEA
	ADD	IX,SP
	LD	SP,IX
	LD	(IX+10),00H
	LD	(IX+12),D
	LD	(IX),C
	LD	(IX+1),B
	LD	B,(IY+15)
	LD	C,(IY+17)
	PUSH	IX
	EXX	
	LD	C,14H	; 20 
	CALL	C.4E89
	PUSH	IX
	POP	DE
	POP	IX
	LD	(IX+6),E
	LD	(IX+7),D
	LD	A,(D.D475)
	ADD	A,A
	LD	B,00H
	LD	C,A
	LD	HL,J.C200
	ADD	HL,BC
	LD	(IX+2),L
	LD	(IX+3),H
	LD	B,(IY+18)
	LD	C,(IY+20)
	PUSH	IX
	EXX	
	LD	C,14H	; 20 
	CALL	C.4E89
	PUSH	IX
	POP	DE
	POP	IX
	LD	A,(D.D478)
	ADD	A,A
	LD	B,00H
	LD	C,A
	LD	HL,J.C200
	ADD	HL,BC
	EX	DE,HL
	CALL	C$5776
	LD	B,(IY+15)
	LD	C,(IY+17)
	DEC	C
	JP	P,J$568D
;
	LD	C,00H
J$568D:	LD	A,01H	; 1 
	CALL	C.4E3B
;
	LD	HL,(D.D484)
	LD	BC,(D.CE73)
	LD	A,B
	OR	C
	JR	Z,J$56A4
;
	DEC	BC
	DEC	BC
	SBC	HL,BC
	LD	(D.D484),HL
J$56A4:	LD	L,(IX)
	LD	H,(IX+1)
	LD	BC,(D.CE73)
	OR	A
	SBC	HL,BC
	LD	(IX),L
	LD	(IX+1),H
	PUSH	IX
	CALL	C$57E2
;
	LD	A,(D.D475)
	PUSH	AF
	BIT	1,(IY+42)
	JR	Z,J.56E3
;
	LD	B,(IY+15)
	LD	C,(IY+17)
	EXX	
	LD	C,14H	; 20 
	CALL	C.4E89
;
	LD	A,0FEH
	CP	(IX-2)
	JR	NZ,J$56E0
;
	LD	A,0FFH
	CP	(IX-1)
	JR	Z,J.56E3
;
J$56E0:	DEC	(IY+17)
J.56E3:	POP	AF
	POP	IX
	SUB	(IY+20)
	ADD	A,(IY+23)
	LD	C,A
	INC	C
	LD	A,02H	; 2 
	ADD	A,(IX+2)
	LD	(IX+2),A
	LD	A,00H
	ADC	A,(IX+3)
	LD	(IX+3),A
	LD	A,02H	; 2 
	ADD	A,(IX+6)
	LD	(IX+6),A
	LD	A,00H
	ADC	A,(IX+7)
	LD	(IX+7),A
	LD	(IX+10),00H
J$5712:	PUSH	BC
	LD	A,(D.D47D)
	CP	C
	JP	NC,J$5720
;
	BIT	0,(IX+10)
	JR	Z,J$576B
;
J$5720:	CALL	C$58A1
;
	JR	C,J$5746
;
	LD	B,A
	LD	A,(D.D480)
	SUB	(IY+27)
	CP	B
	JR	NC,J$5731
;
	LD	B,00H
J$5731:	LD	A,B
	LD	L,(IX+8)
	LD	H,(IX+9)
	BIT	0,(IX+12)
	CALL	Z,C.59CC
	CALL	NZ,C.5BF0
;
	LD	(IX+10),00H
J$5746:	POP	BC
	INC	C
	LD	A,02H	; 2 
	ADD	A,(IX+2)
	LD	(IX+2),A
	LD	A,00H
	ADC	A,(IX+3)
	LD	(IX+3),A
	LD	A,02H	; 2 
	ADD	A,(IX+6)
	LD	(IX+6),A
	LD	A,00H
	ADC	A,(IX+7)
	LD	(IX+7),A
	JP	J$5712

J$576B:	POP	BC
	LD	IX,I.0016
	ADD	IX,SP
	LD	SP,IX
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5776:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.D47B)
	LD	B,A
	LD	A,(D.D47D)
	SUB	B
	INC	A
	INC	A
	ADD	A,A
	LD	C,A
	LD	B,00H
	PUSH	BC
	LDIR	
	LD	B,00H
	LD	A,(D.D478)
	LD	C,A
	LD	HL,I.C27E
	ADD	HL,BC
	EX	DE,HL
	LD	HL,I.DA4F
	ADD	HL,BC
	POP	BC
	SRL	C
	LDIR	
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$57A4:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	BC
	LD	B,00H
	LD	HL,I.DA4F
	ADD	HL,BC
	LD	A,(HL)
	EX	DE,HL
	LD	HL,I.C27E
	ADD	HL,BC
	LD	(HL),A
	LD	(IX+17),A
	POP	BC
	LD	L,(IX+8)
	LD	H,(IX+9)
	EXX	
	LD	C,15H
	CALL	C.4E89
;
	EX	DE,HL
	LD	A,(D.D481)
	LD	(HL),A
	LD	(IX+16),A
	LD	A,(D$D54C)
	OR	A
	JR	Z,J$57DD
;
	LD	L,(IX+6)
	LD	H,(IX+7)
	INC	HL
	RES	7,(HL)
J$57DD:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$57E2:	LD	A,(D.D47C)
	ADD	A,(IY+20)
	SUB	(IY+23)
	LD	B,(IY+18)
	LD	C,A
	EXX	
	LD	C,14H	; 20 
	CALL	C.4E89
;
	ADD	A,A
	LD	D,00H
	LD	E,A
	LD	HL,J.C200
	ADD	HL,DE
J$57FD:	LD	A,(D.D475)
	CP	C
	JR	C,J$5869
;
	LD	A,(IX)
	CP	(HL)
	JR	NZ,J.581D
;
	INC	HL
	INC	IX
	LD	A,(IX)
	CP	(HL)
	JR	Z,J$5817
;
	DEC	HL
	DEC	IX
	JR	J.581D

J$5817:	INC	HL
	INC	IX
	INC	C
	JR	J$57FD

J.581D:	LD	A,(D.D478)
	CP	C
	JR	Z,J.584D
;
	DEC	IX
	DEC	IX
	DEC	C
	LD	A,0F0H
	CP	(IX)
	JR	NC,J.5838
;
	LD	A,0FFH
	CP	(IX+1)
	JR	NZ,J.5838
;
	JR	J.581D

J.5838:	LD	A,0FEH
	CP	(IX-2)
	JR	NZ,J.584D
;
	LD	A,0FFH
	CP	(IX-1)
	JR	NZ,J.584D
;
I$5846:	LD	A,C
	CP	(IY+20)
	JR	Z,J.584D
;
	DEC	C
J.584D:	LD	A,(D.D47B)
	SUB	(IY+20)
	LD	B,A
	ADD	A,C
	LD	C,A
	LD	A,B
	ADD	A,(IY+17)
	LD	E,A
	LD	B,(IY+27)
	LD	D,(IY+28)
	LD	A,01H	; 1 
	EXX	
	LD	C,13H	; 19 
	CALL	C.4E89
;
J$5869:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$586A:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.D481)
	LD	C,A
	LD	B,00H
J$5875:	PUSH	HL
	POP	IX
	EXX	
	LD	C,16H
	CALL	C.4E89
;
	LD	A,(D.D4D8)
	AND	07H	; 7 
	ADD	A,B
	LD	B,00H
	CP	C
	JR	NC,J$589A
;
	LD	B,A
	PUSH	BC
	LD	A,(D.D4D9)
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	POP	BC
	PUSH	HL
	OR	A
	SBC	HL,DE
	POP	HL
	JR	C,J$5875
;
J$589A:	LD	A,B
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$58A1:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.D478)
	ADD	A,C
	SUB	(IY+23)
	LD	C,A
	LD	B,(IY+18)
	CALL	C.4E62
;
	LD	(IX+14),C
	LD	(IX+15),B
	LD	L,(IX+2)
	LD	H,(IX+3)
	DEC	HL
	DEC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	(IX+20),C
	LD	(IX+21),B
	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	(IX+4),C
	LD	(IX+5),B
	LD	L,(IX+6)
	LD	H,(IX+7)
	DEC	HL
	DEC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	(IX+18),E
	LD	(IX+19),D
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	(IX+8),E
	LD	(IX+9),D
	LD	HL,C.0010
	ADD	HL,BC
	JR	C,J.58FC
;
	LD	HL,C.0010
	ADD	HL,DE
	JR	C,J.58FC
;
	JR	J$5925

J.58FC:	LD	HL,I.FFFE
	OR	A
	SBC	HL,DE
	JR	NZ,J.5913
;
	LD	HL,I.FFFE
	OR	A
	SBC	HL,BC
	JR	NZ,J.5913
;
	LD	(IX+10),01H	; 1 
	JP	J.59B3

J.5913:	LD	H,B
	LD	L,C
	OR	A
	SBC	HL,DE
	JR	NZ,J$5921
;
	LD	(IX+10),00H
	JP	J.59B3

J$5921:	XOR	A
	JP	J.59B7

J$5925:	PUSH	BC
	PUSH	DE
	LD	C,(IX+20)
	LD	B,(IX+21)
	LD	E,(IX+18)
	LD	D,(IX+19)
	PUSH	DE
	POP	HL
	OR	A
	SBC	HL,BC
	JR	Z,J.594E
;
	LD	HL,I.FFFE
	OR	A
	SBC	HL,DE
	JR	Z,J$594A
;
	LD	HL,I.FFFE
	OR	A
	SBC	HL,BC
	JR	NZ,J.594E
;
J$594A:	POP	DE
	POP	BC
	JR	J.59B6

J.594E:	POP	DE
	POP	BC
	LD	L,(IX)
	LD	H,(IX+1)
	ADD	HL,BC
	LD	(IX+4),L
	LD	(IX+5),H
	EX	DE,HL
	LD	B,(IX+15)
	LD	C,(IX+14)
	PUSH	HL
	EXX	
	LD	C,1DH
	CALL	C.4E89
;
	LD	A,(D.D481)
	LD	(IX+16),A
	LD	HL,I.C27E
	LD	B,00H
	ADD	HL,BC
	LD	A,(HL)
	LD	(IX+17),A
	POP	HL
	SET	7,H
	SET	7,D
	BIT	0,(IX+12)
	JR	Z,J$5992
;
	EX	DE,HL
	LD	BC,(D.D484)
	PUSH	HL
	XOR	A
	SBC	HL,BC
	POP	HL
	JR	C,J.59B7
;
J$5992:	PUSH	HL
	OR	A
	SBC	HL,DE
	POP	HL
	JR	Z,J$599E
;
	JR	C,J$59A4
;
	XOR	A
	JR	J.59B7

J$599E:	LD	(IX+10),00H
	JR	J.59B3

J$59A4:	LD	A,(IX+5)
	XOR	(IX+9)
	AND	80H
	JR	NZ,J.59B6
	CALL	C$586A
;
	JR	J.59B7

J.59B3:	SCF	
	JR	J$59B8

J.59B6:	XOR	A
J.59B7:	OR	A
J$59B8:	PUSH	AF
	RES	1,(IY+42)
	BIT	0,(IX+10)
	JR	Z,J$59C7
;
	SET	1,(IY+42)
J$59C7:	POP	AF
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.59CC:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	(IX+14),C
	OR	A
	JR	Z,J.59DA
;
	JR	J$5A02

J.59DA:	LD	C,(IX+14)
	LD	B,(IY+27)
	LD	E,C
	LD	A,(D.D47C)
	CP	C
	JR	Z,J.59F5
;
	BIT	0,(IX+10)
	JR	Z,J.59F5
;
	DEC	C
	LD	A,(D.D47D)
	CP	E
	JR	NC,J.59F5
;
	DEC	E
J.59F5:	LD	D,(IY+28)
	LD	A,01H	; 1 
	EXX	
	LD	C,13H	; 19 
	CALL	C.4E89
;
	JR	J.5A49

J$5A02:	CALL	C$5A50
;
	JR	C,J.59DA
;
	LD	A,L
	OR	A
	JR	Z,J.59DA
;
	LD	A,01H	; 1 
	EXX	
	LD	C,13H	; 19 
	CALL	C.4E89
;
	LD	A,H
	OR	A
	JR	Z,J.5A49
;
	LD	B,A
	LD	D,(IY+28)
	PUSH	BC
	PUSH	DE
	LD	B,(IY+15)
	LD	A,(D.D478)
	ADD	A,C
	SUB	(IY+23)
	LD	C,A
	CALL	C.4E62
;
	POP	DE
	POP	BC
	LD	A,(D.D482)
	ADD	A,(IX+17)
	JR	C,J.5A41
;
	ADD	A,(IY+26)
	JR	C,J.5A41
;
	SUB	(IY+19)
	CP	B
	JR	NC,J.5A41
;
	LD	B,A
J.5A41:	LD	A,01H	; 1 
	EXX	
	LD	C,13H	; 19 
	CALL	C.4E89
;
J.5A49:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5A50:	PUSH	AF
	LD	D,A
	ADD	A,(IX+17)
	JR	NC,J$5A59
;
	LD	A,0F0H
J$5A59:	LD	(IX+17),A
	PUSH	IX
	LD	IX,D.CF1A
	LD	A,(D.D482)
	SUB	(IY+19)
	JR	C,J.5A77
;
	CP	(IY+27)
	JR	C,J.5A77
;
	CP	(IY+28)
	JP	NC,J.5B64
;
	JR	J$5A7F

J.5A77:	LD	A,(D.D47F)
	LD	(D.CF1A),A
	JR	J$5A8B

J$5A7F:	LD	A,(D.D482)
	SUB	(IY+19)
	ADD	A,(IY+26)
	LD	(D.CF1A),A
J$5A8B:	ADD	A,D
	LD	(D.CF1E),A
	LD	B,(IY+15)
	LD	A,C
	LD	(D.CF1B),A
	LD	(IX+3),01H	; 1 
	PUSH	BC
	ADD	A,(IY+20)
	SUB	(IY+23)
	LD	C,A
	EXX	
	LD	C,15H
	CALL	C.4E89
;
	POP	BC
	BIT	1,(IY+42)
	JR	Z,J.5ABE
;
	LD	A,(D.D47B)
	CP	(IX+1)
	JR	NC,J.5ABE
;
	LD	(IX+3),02H	; 2 
	DEC	(IX+1)
J.5ABE:	LD	A,(D.D480)
	SUB	(IY+26)
	INC	A
	LD	B,A
	LD	A,(D.D482)
	ADD	A,(IY+29)
	SUB	(IY+19)
	JP	C,J.5B64
;
	JP	Z,J.5B64
;
	CP	B
	JR	NC,J$5ADA
;
	JR	J$5AF4

J$5ADA:	LD	H,00H
	LD	A,(D.D480)
	INC	A
	SUB	(IX+4)
	JR	NC,J$5AEE
;
	LD	A,(D.D480)
	INC	A
	LD	(IX+4),A
	LD	A,00H
J$5AEE:	LD	(IX+2),A
	LD	L,A
	JR	J$5B06

J$5AF4:	ADD	A,(IY+26)
	LD	H,A
	SUB	(IX+4)
	JR	NC,J$5B02
;
	LD	(IX+4),H
	LD	A,00H
J$5B02:	LD	(IX+2),A
	LD	L,A
J$5B06:	LD	A,(D.D46E)
	LD	(D.CF1F),A
	LD	A,(D.CF1A)
	LD	B,A
	LD	D,(IX+4)
	DEC	D
	LD	A,(D.CF1B)
	LD	C,A
	ADD	A,(IX+3)
	DEC	A
	LD	E,A
	LD	A,(D.D47D)
	CP	(IX+1)
	JR	NZ,J.5B30
;
	BIT	0,(IX+3)
	JR	NZ,J.5B30
;
	LD	(IX+3),01H	; 1 
	DEC	E
J.5B30:	LD	A,L
	OR	A
	JR	Z,J$5B5F
;
	PUSH	HL
	CALL	C.5B69
;
	LD	HL,(D.CF1A)
	PUSH	HL
	LD	HL,(D.CF1C)
	PUSH	HL
	LD	HL,(D.CF1E)
	PUSH	HL
	LD	HL,(D.CF20)
	PUSH	HL
	CALL	C.4E55
;
	POP	HL
	LD	(D.CF20),HL
	POP	HL
	LD	(D.CF1E),HL
	POP	HL
	LD	(D.CF1C),HL
	POP	HL
	LD	(D.CF1A),HL
	CALL	C.5B73
;
	POP	HL
J$5B5F:	POP	IX
	POP	AF
	OR	A
	RET	

J.5B64:	POP	IX
	POP	AF
	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5B69:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	AF
	LD	A,01H	; 1 
	JR	J$5B7A

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5B73:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	AF
	XOR	A
J$5B7A:	LD	HL,(D.CF1A)
	PUSH	HL
	LD	HL,(D.CF1C)
	PUSH	HL
	LD	HL,(D.CF1E)
	PUSH	HL
	LD	HL,(D.CF20)
	PUSH	HL
	LD	H,(IY+27)
	LD	L,(IY+24)
	PUSH	HL
	LD	H,(IY+28)
	LD	L,(IY+25)
	PUSH	HL
	LD	B,(IX)
	OR	A
	JR	NZ,J$5BA1
;
	LD	B,(IX+4)
J$5BA1:	LD	(IY+27),B
	LD	C,(IX+1)
	LD	(IY+24),C
	LD	A,(D.CF1C)
	ADD	A,B
	DEC	A
	LD	(D.D480),A
	LD	A,(D$CF1D)
	ADD	A,C
	DEC	A
	LD	(D.D47D),A
	CALL	C$4E6F
;
	POP	HL
	LD	(IY+28),H
	LD	(IY+25),L
	POP	HL
	LD	(IY+27),H
	LD	(IY+24),L
	POP	HL
	LD	(D.CF20),HL
	POP	HL
	LD	(D.CF1E),HL
	POP	HL
	LD	(D.CF1C),HL
	POP	HL
	LD	(D.CF1A),HL
	POP	AF
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

?.5BE2:	EXX	
	LD	C,19H
	CALL	C.4E89
;
	RET	

?.5BE9:	CALL	C.555B
	CALL	C.5613
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5BF0:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	(IX+14),C
	OR	A
	JR	NZ,J$5BFE
;
	JR	J.5C2F

J$5BFE:	PUSH	AF
	PUSH	BC
	LD	B,(IY+15)
	LD	A,(D.D478)
	ADD	A,C
	SUB	(IY+23)
	LD	C,A
	CALL	C.4E62
;
	POP	BC
	POP	AF
	CALL	C$5C5C
;
	JR	C,J.5C2F
;
	LD	A,(D.D482)
	ADD	A,(IX+16)
	ADD	A,(IY+26)
	SUB	(IY+19)
	CP	B
	JR	NC,J$5C25
;
	LD	B,A
J$5C25:	LD	A,01H	; 1 
	EXX	
	LD	C,13H	; 19 
	CALL	C.4E89
;
	JR	J$5C55

J.5C2F:	LD	C,(IX+14)
	LD	B,(IY+27)
	LD	E,C
	LD	A,(D.D47C)
	CP	C
	JR	Z,J.5C4A
;
	BIT	0,(IX+10)
	JR	Z,J.5C4A
;
	DEC	C
	LD	A,(D.D47D)
	CP	E
	JR	NC,J.5C4A
;
	DEC	E
J.5C4A:	LD	D,(IY+28)
	LD	A,01H	; 1 
	EXX	
	LD	C,13H	; 19 
	CALL	C.4E89
;
J$5C55:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5C5C:	PUSH	AF
	PUSH	IX
	LD	IX,D.CF1A
	LD	D,A
	LD	A,(D.D482)
	SUB	(IY+19)
	JR	C,J.5C79
;
	CP	(IY+27)
	JR	C,J.5C79
;
	CP	(IY+28)
	JP	NC,J.5D71
;
	JR	J$5C81

J.5C79:	LD	A,(D.D47F)
	LD	(D.CF1E),A
	JR	J$5C8D

J$5C81:	LD	A,(D.D482)
	SUB	(IY+19)
	ADD	A,(IY+26)
	LD	(D.CF1E),A
J$5C8D:	ADD	A,D
	LD	(D.CF1A),A
	LD	B,(IY+15)
	LD	A,C
	LD	(D.CF1B),A
	LD	(IX+3),01H	; 1 
	PUSH	BC
	ADD	A,(IY+20)
	SUB	(IY+23)
	LD	C,A
	EXX	
	LD	C,18H
	CALL	C.4E89
;
	POP	BC
	POP	IX
	BIT	0,(IX+10)
	PUSH	IX
	LD	IX,D.CF1A
	JR	Z,J.5CC8
;
	LD	A,(D.D47B)
	CP	(IX+1)
	JR	NC,J.5CC8
;
	LD	(IX+3),02H	; 2 
	DEC	(IX+1)
J.5CC8:	LD	A,(D.D480)
	SUB	(IY+26)
	INC	A
	LD	B,A
	LD	A,(D.D482)
	ADD	A,(IY+29)
	SUB	(IY+19)
	JP	C,J.5D71
;
	JP	Z,J.5D71
;
	CP	B
	JR	NC,J$5CE4
;
	JR	J$5CF4

J$5CE4:	LD	A,(D.D480)
	INC	A
	SUB	(IX)
	JR	NC,J$5CEE
;
	XOR	A
J$5CEE:	LD	(IX+2),A
	LD	L,A
	JR	J$5D01

J$5CF4:	ADD	A,(IY+26)
	SUB	(IX)
	JR	NC,J$5CFD
;
	XOR	A
J$5CFD:	LD	(IX+2),A
	LD	L,A
J$5D01:	LD	A,(D.D46E)
	LD	(D.CF1F),A
	LD	A,(D.CF1E)
	ADD	A,(IX+2)
	LD	B,A
	LD	A,(D.D480)
	LD	D,A
	SUB	B
	CP	03H	; 3 
	JR	NC,J.5D21
;
	BIT	1,(IY+10)
	JR	NZ,J.5D21
;
	SUB	03H	; 3 
	ADD	A,B
	LD	B,A
J.5D21:	LD	A,(D.CF1B)
	LD	C,A
	ADD	A,(IX+3)
	DEC	A
	LD	E,A
	LD	A,(D.D47D)
	CP	(IX+1)
	JR	NZ,J.5D3D
;
	BIT	0,(IX+3)
	JR	NZ,J.5D3D
;
	LD	(IX+3),01H	; 1 
	DEC	E
J.5D3D:	LD	A,L
	OR	A
	JR	Z,J$5D6C
;
	PUSH	HL
	CALL	C.5B69
;
	LD	HL,(D.CF1A)
	PUSH	HL
	LD	HL,(D.CF1C)
	PUSH	HL
	LD	HL,(D.CF1E)
	PUSH	HL
	LD	HL,(D.CF20)
	PUSH	HL
	CALL	C.4E55
;
	POP	HL
	LD	(D.CF20),HL
	POP	HL
	LD	(D.CF1E),HL
	POP	HL
	LD	(D.CF1C),HL
	POP	HL
	LD	(D.CF1A),HL
	CALL	C.5B73
;
	POP	HL
J$5D6C:	POP	IX
	POP	AF
	OR	A
	RET	

J.5D71:	POP	IX
	POP	AF
	SCF	
	RET	

;	  Subroutine select firmware slot and segment on page 0
;	     Inputs  ________________________
;	     Outputs ________________________

C.5D76:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	PUSH	AF
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RRCA	
	RRCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+15)
	LD	(IX+11),A
	LD	A,(IX+14)
	LD	(IX+10),A
	LD	(IX+15),B
	LD	(IX+14),C
	POP	AF
	LD	C,A
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D$7FF0)
	LD	B,A			; current segment page 0
	LD	A,C
	LD	(D.6000),A
	INC	A
	LD	(D.6400),A		; select segments page 0
	LD	(IX+13),B
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$5DE1
	EI	
J$5DE1:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5DE9:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	A,(IX+11)
	LD	(D.6000),A
	INC	A
	LD	(D.6400),A		; select segments page 0
	LD	B,(IX+13)
	LD	C,(IX+12)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
I.5E14:	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+13),A
	LD	A,(IX+8)
	LD	(IX+12),A
	LD	A,(IX+7)
	LD	(IX+11),A
	LD	A,(IX+6)
	LD	(IX+10),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$5E3A
;
	EI	
J$5E3A:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	POP	AF
	RET	

;	  Subroutine select firmware slot and segment on page 2
;	     Inputs  ________________________
;	     Outputs ________________________

C.5E42:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	PUSH	AF
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+15)
	LD	(IX+11),A
	LD	A,(IX+14)
	LD	(IX+10),A
	LD	(IX+15),B
	LD	(IX+14),C
	POP	AF
	LD	C,A
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D$7FF4)		; current segment page 2
	LD	B,A
	LD	A,C
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	LD	(IX+13),B
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$5EB1
;
	EI	
J$5EB1:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5EB9:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	A,(IX+11)
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	LD	B,(IX+13)
	LD	C,(IX+12)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+13),A
	LD	A,(IX+8)
	LD	(IX+12),A
	LD	A,(IX+7)
	LD	(IX+11),A
	LD	A,(IX+6)
	LD	(IX+10),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$5F0A
;
	EI	
J$5F0A:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	POP	AF
	RET	

?.5F12:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D469)
	LD	H,A			; slot id RAM page 0
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RRCA	
	RRCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

?.5F65:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D469)		; slot id RAM page 0
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5FAD:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46B)
	LD	H,A			; slot id RAM page 2
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	POP	IX
	POP	HL
D.6000:	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6005:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46B)
	AND	03H			; slot id RAM page 2
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	

?.604D:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46B)
	LD	H,A			; slot id RAM page 2
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

?.60A4:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46B)		; slot id RAM page 2
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	RET	

J$60EB:	PUSH	BC
	CALL	C$5FAD			; select RAM on page 2
	CALL	C$4A38
;
	JR	C,J.612C
;
	LD	A,18H
	LD	(D$C942),A
	LD	A,(D.CC3F)
	AND	A
	JR	NZ,J$6104
	CALL	C$4C9B
;
	JR	J$6107

J$6104:	CALL	C$4C8E
;
J$6107:	JR	C,J.612C
;
	LD	A,01H	; 1 
	CALL	C$4B49
	CALL	C$4C33
	CALL	C$6134
	CALL	C$618D
	CALL	C$61FE
	CALL	C$633D
;
	JR	C,J.612C
	CALL	C$6628
;
	JR	C,J.612C
	CALL	C$6350
;
	JR	C,J.612C
	CALL	C$66CE
;
J.612C:	CALL	C$4D92
	CALL	C$6005			; restore slot on page 2
;
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6134:	PUSH	AF
	PUSH	HL
	XOR	A
	LD	(D.D48A),A
	LD	(D.D449),A
	LD	(D$D448),A
	CALL	C$4A45
;
	XOR	A
	LD	L,A
	LD	H,A
	LD	(D.C33D),A
	LD	(D$C4C2),HL
	LD	(D.C9CD),HL
	LD	(D.C901),HL
	LD	(D.C3BD),A
	LD	(D.C332),A
	LD	(D$C415),HL
	LD	(D$C4B4),A
	LD	(D$C41B),HL
	LD	A,(D.CC4D)
	LD	(D$C4B6),A
	LD	L,00H
	LD	A,(D.CC3D)
	CP	03H	; 3 
	JR	NC,J.6186
;
	LD	A,(D.DACD)
	AND	A
	JR	Z,J$6178
;
	SET	2,L
J$6178:	LD	A,(D.CC4B)
	AND	A
	JR	Z,J.6186
;
	LD	A,(D.CC48)
	AND	A
	JR	Z,J.6186
;
	SET	0,L
J.6186:	LD	A,L
	LD	(D.C90F),A
	POP	HL
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$618D:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.C90F)
	AND	A
	JR	Z,J$61CE
;
	LD	A,(D.C31B)
	ADD	A,02H	; 2 
	LD	E,A
	LD	D,00H
	LD	A,(D.CC40)
	CALL	C.61D3
;
	LD	A,C
	LD	(D.C90B),A
	LD	A,L
	LD	(D.C90C),A
	LD	A,(D.C31A)
	LD	E,A
	LD	D,00H
	LD	A,(D.CC41)
	CALL	C.61D3
;
	LD	A,C
	LD	(D.C909),A
	LD	A,L
	LD	(D.C90A),A
	LD	A,(D.CC44)
	ADD	A,A
	LD	B,A
	LD	A,(D.C90B)
	ADD	A,B
	ADD	A,C
	LD	(D.C90E),A
J$61CE:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.61D3:	ADD	A,A
	ADD	A,A
	LD	C,A
	ADD	A,A
	ADD	A,C
	ADD	A,A
	LD	L,A
	LD	H,00H
	ADD	HL,DE
	LD	A,(D.CC46)
	ADD	A,18H
	LD	E,A
	XOR	A
	LD	D,A
	LD	C,A
J$61E6:	AND	A
	SBC	HL,DE
	JR	C,J$61EF
;
	INC	C
	INC	C
	JR	J$61E6

J$61EF:	ADD	HL,DE
	SRL	D
	RR	E
	AND	A
	SBC	HL,DE
	JR	NC,J$61FC
;
	ADD	HL,DE
	JR	J$61FD

J$61FC:	INC	C
J$61FD:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$61FE:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	XOR	A
	LD	(D.C917),A
	LD	(D$C918),A
	LD	(D.C919),A
	LD	A,(D.C90F)
	AND	A
	JP	Z,J.629F
;
	BIT	2,A
	JR	Z,J$6253
;
	LD	HL,I$DAA5
	LD	(D.C39D),HL
	CALL	C.62B0
;
	LD	(D.C917),A
	LD	HL,I.0000
	LD	A,(D.DACD)
	DEC	A
	JR	Z,J.623E
;
	LD	A,(D.C90E)
	LD	HL,D.C917
	SUB	(HL)
	LD	L,A
	LD	H,00H
	LD	A,(D.DACD)
	CP	03H	; 3 
	JR	NZ,J.623E
;
	ADD	HL,HL
J.623E:	LD	(D.C910),HL
	LD	A,(D.CC3D)
	ADD	A,A
	LD	E,A
	LD	D,00H
	LD	HL,I$62A4
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	(D.C3A0),HL
J$6253:	LD	A,(D.C90F)
	BIT	0,A
	JR	Z,J.629F
;
	LD	A,(D$CC4A)
	LD	HL,I.C389
	CALL	C$62C1
;
	LD	HL,I.C389
	LD	(D.C3B1),HL
	CALL	C.62B0
;
	LD	(D.C919),A
	LD	HL,I.0000
	LD	A,(D.CC4B)
	DEC	A
	JR	Z,J.628A
;
	LD	A,(D.C90E)
	LD	HL,D.C919
	SUB	(HL)
	LD	L,A
	LD	H,00H
	LD	A,(D.CC4B)
	CP	03H	; 3 
	JR	NZ,J.628A
;
	ADD	HL,HL
J.628A:	LD	(D.C913),HL
	LD	A,(D.CC3D)
	ADD	A,A
	LD	E,A
	LD	D,00H
	LD	HL,I$62AA
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	(D.C3B5),HL
J.629F:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

I$62A4:	LD	L,L
	DEC	B
	LD	(BC),A
	DEC	B
	CPL	
	INC	B
I$62AA:	LD	C,B
	NOP	
	DEC	E
	NOP	
	LD	A,(BC)
	NOP	
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.62B0:	PUSH	BC
	PUSH	HL
	LD	BC,I$2800
J$62B5:	LD	A,(HL)
	INC	HL
	AND	A
	JR	Z,J$62BD
;
	INC	C
	DJNZ	J$62B5
;
J$62BD:	LD	A,C
	POP	HL
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$62C1:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	DE,I$3030
	LD	C,0AH	; 10 
J$62CA:	SUB	C
	JR	C,J$62D0
;
	INC	D
	JR	J$62CA

J$62D0:	ADD	A,C
	ADD	A,E
	LD	E,A
	LD	A,(D.CC48)
	AND	A
	JR	Z,J.6314
;
	DEC	A
	JR	NZ,J$62E1
	CALL	C.631B
;
	JR	J.6314

J$62E1:	DEC	A
	JR	NZ,J$62EF
;
	LD	(HL),2DH	; "-"
	INC	HL
	CALL	C.631B
;
	LD	(HL),2DH	; "-"
	INC	HL
	JR	J.6314

J$62EF:	DEC	A
	JR	NZ,J$62FD
;
	LD	(HL),3CH	; "<"
	INC	HL
	CALL	C.631B
;
	LD	(HL),3EH	; ">"
	INC	HL
	JR	J.6314

J$62FD:	DEC	A
	JR	NZ,J$630B
;
	LD	(HL),82H
	INC	HL
	LD	(HL),6FH	; "o"
	INC	HL
	CALL	C.631B
;
	JR	J.6314

J$630B:	LD	(HL),28H	; "("
	INC	HL
	CALL	C.631B
;
	LD	(HL),29H	; ")"
	INC	HL
J.6314:	LD	(HL),00H
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.631B:	LD	A,(D.CC3F)
	AND	A
	JR	Z,J$6333
;
	LD	A,D
	CP	30H	; "0"
	JR	NZ,J$632D
;
	LD	(HL),0FFH
	INC	HL
	LD	(HL),E
	INC	HL
	JR	J.633C

J$632D:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	JR	J.633C

J$6333:	LD	A,D
	CP	30H	; "0"
	JR	Z,J$633A
;
	LD	(HL),D
	INC	HL
J$633A:	LD	(HL),E
	INC	HL
J.633C:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$633D:	PUSH	HL
	LD	A,(D.D497)
	CP	04H	; 4 
	JR	NZ,J$634D
;
	LD	HL,I$0040
	CALL	C$49B6
;
	JR	C,J$634E
;
J$634D:	AND	A
J$634E:	POP	HL
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6350:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.CC44)
	LD	B,A
J$6357:	CALL	C$4D2A
;
	JP	C,J.64E5
	CALL	C.64E9
;
	LD	DE,I.0001
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D.C31C)
	CALL	C.6746
;
	LD	DE,I.0002
	CALL	C.6DD5
;
	JP	C,J.64E5
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.6E49
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D$C31D)
	CALL	C.6746
;
	LD	HL,D.C332
	INC	(HL)
	LD	DE,C.0003
	CALL	C.6ECE
;
	JP	C,J.64E5
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.6F6C
;
	JP	C,J.64E5
;
	LD	A,16H
	LD	(D.C3C8),A
	CALL	C.4BE5
;
	LD	A,(D.C33D)
	LD	HL,I.C340
	OR	(HL)
	LD	(D.C33D),A
	LD	HL,C.0018
	LD	(D.C339),HL
	CALL	C.4B70
	CALL	C.4B7D
;
	LD	A,(D.C33D)
	LD	HL,I.C33E
	OR	(HL)
	LD	HL,I.C33F
	OR	(HL)
	LD	(D.C33D),A
	CALL	C.4CA8
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D.C31B)
	CALL	C.6746
;
	LD	DE,I$0004
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D.C31B)
	LD	L,A
D.6400:	LD	A,0CH	; 12 
	SUB	L
	CALL	C.6746
;
	LD	DE,BDOS
	CALL	C.676F
;
	JP	C,J.64E5
;
	LD	HL,D.C3BD
	INC	(HL)
	CALL	C.64E9
;
	LD	DE,CPMADR
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D.C31E)
	CALL	C.6746
;
	LD	DE,D.0007
	CALL	C.6DD5
;
	JP	C,J.64E5
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.6E49
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D$C31F)
	CALL	C.6746
;
	LD	DE,I.0008
	CALL	C.6ECE
;
	JP	C,J.64E5
	CALL	C.676F
;
	JP	C,J.64E5
	CALL	C.6F6C
;
	JP	C,J.64E5
	CALL	C.4CA8
;
	JP	C,J.64E5
	CALL	C.4CB5
;
	JP	C,J.64E5
;
	LD	A,(D.C31A)
	CALL	C.6746
;
	LD	DE,C.0009
	CALL	C.676F
;
	JR	C,J.64E5
	CALL	C.4CB5
;
	JR	C,J.64E5
;
	LD	A,(D.C320)
	LD	L,A
	LD	A,0AH	; 10 
	SUB	L
	CALL	C.6746
;
	LD	HL,D.C332
	INC	(HL)
	LD	DE,I.000A
	LD	A,(D.CC46)
	ADD	A,02H	; 2 
	LD	(D.C3C8),A
	CALL	C.4BE5
;
	LD	A,(D.C33D)
	LD	HL,I.C340
	OR	(HL)
	LD	(D.C33D),A
	LD	A,(D.CC46)
	ADD	A,02H	; 2 
	LD	L,A
	LD	H,00H
	LD	(D.C339),HL
	CALL	C.4B70
	CALL	C.4B7D
;
	LD	A,(D.C33D)
	LD	HL,I.C33E
	OR	(HL)
	LD	HL,I.C33F
	OR	(HL)
	LD	(D.C33D),A
	CALL	C.4CB5
;
	JR	C,J.64E5
;
	LD	A,(D.C31B)
	ADD	A,02H	; 2 
	CALL	C.6746
;
	LD	DE,I$000B
	CALL	C.676F
;
	JR	C,J.64E5
;
	LD	HL,D.C3BD
	INC	(HL)
	DEC	B
	JP	NZ,J$6357
	CALL	C.4CB5
;
J.64E5:	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.64E9:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IY
	LD	A,01H	; 1 
	LD	(D.C3C5),A
	LD	IY,I.7882
	LD	A,(D.CC45)
	LD	B,A
J$64FC:	CALL	C.4C40
;
	AND	A
	JR	NZ,J$655D
;
	LD	HL,I$793F
	CALL	C$4C5A
;
	AND	A
	JR	NZ,J$6556
;
	LD	HL,I.7804
	CALL	C.4C74
;
	LD	HL,D.FFFF
	AND	A
	SBC	HL,DE
	JR	NZ,J$6521
;
	LD	A,0FFH
	CALL	C.4C4D
;
	JP	J.65FE

J$6521:	LD	A,H
	AND	A
	JR	NZ,J.652E
;
	LD	A,L
	CP	06H	; 6 
	JR	NC,J.652E
;
	LD	A,0FEH
	JR	J.6550

J.652E:	PUSH	IY
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	POP	IY
	LD	A,(D.C328)
	LD	E,A
	LD	D,00H
	LD	HL,I.661A
	ADD	HL,DE
	LD	A,(HL)
	CP	0FDH
	JR	Z,J.6550
;
	LD	HL,D.C3BD
	BIT	0,(HL)
	JR	Z,J.6550
;
	OR	80H
J.6550:	CALL	C.4C4D
;
	JP	J.65F4

J$6556:	DEC	A
	CALL	C$4C67
;
	JP	J.65F4

J$655D:	CP	0FFH
	JP	Z,J.65FE
;
	LD	C,A
	AND	07H	; 7 
	JP	NZ,J.65F4
;
	LD	A,C
	BIT	3,A
	JR	Z,J$6572
;
	AND	0F7H
	JP	J.65F1

J$6572:	LD	HL,I.7804
	CALL	C.4C74
;
	PUSH	IY
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	POP	IY
	PUSH	HL
	LD	HL,(D$C333)
	LD	A,(D.C3C5)
	ADD	A,A
	LD	E,A
	LD	D,00H
	ADD	HL,DE
J$658E:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	HL
	LD	HL,D.FFFF
	AND	A
	SBC	HL,DE
	LD	A,H
	AND	A
	JR	NZ,J.65A8
;
	LD	A,L
	AND	A
	JR	Z,J.65A8
;
	CP	06H	; 6 
	JR	NC,J.65A8
;
	POP	HL
	JR	J$658E

J.65A8:	POP	HL
	EX	DE,HL
	POP	DE
	AND	A
	SBC	HL,DE
	JR	NZ,J$65B4
;
	LD	A,0FDH
	JR	J.65F1

J$65B4:	LD	HL,I.7804
	CALL	C.4C81
;
	PUSH	IY
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	POP	IY
	LD	A,(D.C328)
	LD	E,A
	LD	D,00H
	LD	HL,I.661A
	ADD	HL,DE
	LD	A,(HL)
	CP	0FDH
	JR	Z,J.65F1
;
	LD	D,A
	AND	07H	; 7 
	DEC	A
	LD	E,A
	LD	A,(D.C3BD)
	ADD	A,E
	LD	E,A
	CALL	C$6605
;
	CP	E
	JR	NC,J$65E7
;
	LD	A,0FDH
	JR	J.65F1

J$65E7:	LD	A,D
	LD	HL,D.C3BD
	BIT	0,(HL)
	JR	Z,J.65F1
;
	OR	80H
J.65F1:	CALL	C.4C4D
;
J.65F4:	LD	HL,D.C3C5
	INC	(HL)
	INC	IY
	DEC	B
	JP	NZ,J$64FC
;
J.65FE:	POP	IY
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6605:	PUSH	BC
	PUSH	DE
	LD	A,(D$DB15)
	DEC	A
	LD	B,A
	LD	A,(D.C3C5)
	DEC	A
	LD	C,A
	CALL	C.4E62
;
	LD	A,(D.D483)
	INC	A
	POP	DE
	POP	BC
I.661A:	RET	

?.661B:	LD	(D$2222),HL
	LD	C,E
	LD	L,L
	LD	C,E
	LD	L,L
	DEFB	0FDH		; << Illegal Op Code Byte >>
	DEFB	0FDH		; << Illegal Op Code Byte >>
	DEFB	0FDH		; << Illegal Op Code Byte >>
	DEFB	0FDH		; << Illegal Op Code Byte >>
	DEFB	0FDH		; << Illegal Op Code Byte >>
	DEFB	0FDH		; << Illegal Op Code Byte >>
;	-----------------
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6628:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.C90F)
	AND	A
	JR	NZ,J$6642
;
	LD	HL,(D.CC40)
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	ADD	HL,HL
	CALL	C.675C
;
	JR	J.669D

J$6642:	LD	A,(D.C90C)
	CALL	C.6746
;
	LD	A,(D.C90B)
	AND	A
	JR	Z,J.669D
;
	LD	B,A
J$664F:	BIT	0,B
	JR	Z,J$6658
;
	LD	A,(D.C31C)
	JR	J$665B

J$6658:	LD	A,(D.C31E)
J$665B:	CALL	C.6746
;
	LD	C,A
	CALL	C.6DD5
;
	JR	C,J.66CA
	CALL	C.6E49
;
	JR	C,J.66CA
	CALL	C.4CB5
;
	JR	C,J.66CA
;
	LD	A,(D.C31A)
	SUB	C
	CALL	C.6746
	CALL	C.6ECE
;
	JR	C,J.66CA
	CALL	C.6F6C
;
	JR	C,J.66CA
	CALL	C.4CA8
;
	JR	C,J.66CA
	CALL	C.4CB5
;
	JR	C,J.66CA
;
	DEC	B
	JR	Z,J$6693
;
	LD	A,0CH	; 12 
	CALL	C.6746
;
	JR	J$664F

J$6693:	LD	A,(D.C31A)
	LD	C,A
	LD	A,0AH	; 10 
	SUB	C
	CALL	C.6746
;
J.669D:	LD	A,(D.CC46)
	ADD	A,02H	; 2 
	LD	L,A
	LD	H,00H
	LD	(D.C339),HL
	CALL	C.4B70
	CALL	C.4B7D
;
	LD	A,(D.C33D)
	LD	HL,I.C33E
	OR	(HL)
	LD	HL,I.C33F
	OR	(HL)
	LD	(D.C33D),A
	CALL	C.4CB5
;
	JR	C,J.66CA
;
	LD	A,(D.C31B)
	ADD	A,02H	; 2 
	CALL	C.6746
;
	AND	A
J.66CA:	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$66CE:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.C90F)
	AND	A
	JR	NZ,J$66F3
;
	LD	HL,(D.CC41)
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	ADD	HL,HL
	LD	A,(D.C31A)
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	CALL	C.675C
;
	JR	J.6741

J$66F3:	LD	A,(D.C909)
	AND	A
	JR	Z,J.6741
;
	LD	B,A
J$66FA:	BIT	0,B
	JR	Z,J$6703
;
	LD	A,(D.C31C)
	JR	J$6706

J$6703:	LD	A,(D.C31E)
J$6706:	CALL	C.6746
;
	LD	C,A
	CALL	C.6DD5
;
	JR	C,J.6742
	CALL	C.6E49
;
	JR	C,J.6742
	CALL	C.4CB5
;
	JR	C,J.6742
;
	LD	A,(D.C31A)
	SUB	C
	CALL	C.6746
	CALL	C.6ECE
;
	JR	C,J.6742
	CALL	C.6F6C
;
	JR	C,J.6742
	CALL	C.4CA8
;
	JR	C,J.6742
	CALL	C.4CB5
;
	JR	C,J.6742
;
	LD	A,0CH	; 12 
	CALL	C.6746
;
	DJNZ	J$66FA
;
	LD	A,(D.C90A)
	CALL	C.6746
;
J.6741:	AND	A
J.6742:	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6746:	PUSH	DE
	PUSH	HL
	LD	E,A
	LD	D,00H
	LD	HL,(D.C901)
	ADD	HL,DE
	LD	(D.C901),HL
	LD	HL,(D.C9CD)
	ADD	HL,DE
	LD	(D.C9CD),HL
	POP	HL
	POP	DE
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.675C:	PUSH	DE
	EX	DE,HL
	LD	HL,(D.C901)
	ADD	HL,DE
	LD	(D.C901),HL
	LD	HL,(D.C9CD)
	ADD	HL,DE
	LD	(D.C9CD),HL
	EX	DE,HL
	POP	DE
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.676F:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IY
	LD	HL,I$67C6
	ADD	HL,DE
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	(D.C904),HL
	LD	A,01H	; 1 
	LD	(D.C3C5),A
	LD	IY,I.7882
	LD	A,(D.CC45)
	LD	B,A
J$678D:	PUSH	BC
	CALL	C.4C40
;
	LD	HL,(D.C904)
	LD	B,(HL)
	DEC	B
	JR	Z,J.67B8
;
	INC	HL
J$6799:	CP	(HL)
	INC	HL
	JR	Z,J$67A3
;
	INC	HL
	INC	HL
	DJNZ	J$6799
;
	JR	J.67B8

J$67A3:	LD	B,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,B
	LD	DE,I$67AC
	PUSH	DE
	JP	(HL)

I$67AC:	JR	NC,J$67B1
;
	POP	BC
	JR	J$67C2

J$67B1:	CALL	C.4C40
;
	DEC	A
	CALL	C.4C4D
;
J.67B8:	LD	HL,D.C3C5
	INC	(HL)
	INC	IY
	POP	BC
	DJNZ	J$678D
;
	AND	A
J$67C2:	POP	IY
	POP	HL
	POP	DE
I$67C6:	POP	BC
	RET	

?.67C8:	SBC	A,67H	; "g"
	RET	PE
;
	LD	H,A
	CALL	PE,C$F667
;
	LD	H,A
	JP	M,J$0167
;
	LD	L,B
	DEC	BC
	LD	L,B
	RRCA	
	LD	L,B
	ADD	HL,DE
	LD	L,B
	DEC	E
	LD	L,B
	LD	E,68H	; "h"
	INC	B
	LD	(D$6825),HL
	LD	C,E
	LD	E,B
	LD	L,C
	LD	L,L
	POP	BC
	LD	L,D
	LD	(BC),A
	LD	HL,I$683E
	INC	B
	LD	C,D
	LD	(HL),C
	LD	L,C
	LD	L,D
	DAA	
	LD	L,E
	EX	DE,HL
	EI	
	LD	L,D
	LD	(BC),A
	LD	L,H
	RET	C
;
	LD	L,D
	INC	BC
	LD	C,C
	XOR	B
	LD	L,D
	LD	L,C
	LD	D,A
D$6800:	LD	L,E
	INC	B
	AND	D
	DEC	H
	LD	L,B
	BIT	3,B
	LD	L,C
	DEFB	0EDH		; << Illegal Op Code Byte >>
;	-----------------
;
	POP	BC
	LD	L,D
	LD	(BC),A
	AND	C
	LD	A,68H	; "h"
	INC	B
	JP	Z,J$6971
;
	JP	PE,J$6B27
;
	LD	L,E
	EI	
	LD	L,D
	LD	(BC),A
	CALL	PE,C$6AD8
;
	LD	BC,I$C903
	XOR	B
	LD	L,D
	JP	(HL)

?.6823:	LD	D,A
	LD	L,E
D$6825:	PUSH	BC
	PUSH	HL
	RLA	
	LD	A,(D.C31A)
	JR	NC,J$6830
;
	LD	A,(D.C31B)
J$6830:	ADD	A,0BH	; 11 
	LD	L,A
	LD	H,00H
	LD	B,01H	; 1 
	CALL	C.6C6A
;
	AND	A
	POP	HL
	POP	BC
	RET	

I$683E:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,I.7804
	CALL	C.4C74
;
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	LD	B,(IY)
	LD	C,(IY+1)
	LD	A,(D.C328)
	CP	03H	; 3 
	JP	NZ,J$68DC
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.68A8
;
	LD	A,B
	CP	20H	; " "
	JP	Z,J$694F
;
	JR	C,J.68A8
;
	CP	80H
	JR	C,J$6879
;
	CP	0A0H
	JR	C,J.68A8
;
	CP	0F0H
	JR	NC,J.68A8
;
J$6879:	LD	A,(D.C326)
	AND	80H
	RLCA	
	LD	HL,D.CC3F
	XOR	(HL)
	JR	NZ,J$68A2
	CALL	C.49EA
;
	JP	C,J.6950
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.68A8
;
	LD	A,(D.CC3F)
	DEC	A
	JR	NZ,J.68C0
	CALL	C$4AA0
	CALL	C.49DD
	CALL	C.49DD
;
	JR	J.68C0

J$68A2:	CALL	C.4ECA
	CALL	C.4EBD
;
J.68A8:	CALL	C.49EA
;
	JP	C,J.6950
;
	LD	A,(D.CC3F)
	AND	A
	CALL	NZ,C.49DD
;
	LD	A,(D.C326)
	RLCA	
	CALL	C,C.49DD
;
	XOR	A
	CALL	C.4AEE
;
J.68C0:	LD	A,(D.C326)
	BIT	3,A
	CALL	NZ,C$4A6C
;
	BIT	2,A
	CALL	NZ,C$4AC7
	CALL	C.4975
;
	LD	HL,I.78C1
	CALL	C.4C74
;
	EX	DE,HL
	CALL	C.703E
;
	JR	J$694A

J$68DC:	CALL	C$4ABA
;
	JP	C,J.6950
;
	LD	A,(D.CC3F)
	AND	A
	JR	NZ,J$68EE
	CALL	C$4AD4
	CALL	C.4975
;
J$68EE:	LD	A,(D.C326)
	RLA	
	JR	NC,J$68FA
	CALL	C.49DD
	CALL	C$4A5F
;
J$68FA:	XOR	A
	LD	(D.C4B5),A
	LD	HL,C.000C
	LD	(D.C419),HL
	LD	HL,C.000C
	LD	(D.C337),HL
	LD	A,01H	; 1 
	LD	(D.C354),A
	LD	(D.C355),A
	LD	HL,D.C326
	XOR	A
	BIT	2,(HL)
	JR	Z,J$691B
;
	INC	A
J$691B:	LD	(D.C4B3),A
	XOR	A
	BIT	3,(HL)
	JR	Z,J$6924
;
	INC	A
J$6924:	LD	(D.C4BD),A
	LD	HL,I.78C1
	CALL	C.4C74
;
	LD	A,(D.C328)
	DEC	A
	JR	NZ,J$6938
;
	LD	HL,C.000C
	ADD	HL,DE
	EX	DE,HL
J$6938:	PUSH	DE
	POP	IX
	LD	A,(D.C328)
	CP	02H	; 2 
	JR	NZ,J$6947
;
	LD	A,01H	; 1 
	LD	(D.C328),A
J$6947:	CALL	C.4BB1
;
J$694A:	LD	A,01H	; 1 
	LD	(D.C33D),A
J$694F:	AND	A
J.6950:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

?.6958:	PUSH	BC
	PUSH	HL
	RLA	
	LD	A,(D.C31A)
	JR	NC,J$6963
;
	LD	A,(D.C31B)
J$6963:	ADD	A,0DH	; 13 
	LD	L,A
	LD	H,00H
	LD	B,00H
	CALL	C.6C6A
;
	AND	A
	POP	HL
	POP	BC
	RET	

J$6971:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,I.7804
	CALL	C.4C74
;
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	LD	B,(IY)
	LD	C,(IY+1)
	LD	A,(D.CC4C)
	LD	(D.C4B5),A
	CP	02H	; 2 
	JR	NZ,J$69E7
;
	LD	A,(D.CC3F)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	D,A
	LD	HL,I.D1BD
	LD	A,(D.C328)
	CP	04H	; 4 
	LD	A,D
	JR	NZ,J$69C4
;
	OR	01H	; 1 
	CALL	C.4BBE
;
	JR	C,J.69E3
;
	LD	A,(D.CC3F)
	AND	A
	CALL	Z,C.4975
;
	LD	A,(D.C326)
	BIT	7,A
	CALL	NZ,C.49DD
;
	XOR	A
	LD	(D.C4B5),A
	JP	J.6A52

J$69C4:	CALL	C.4BBE
;
	JR	C,J.69E3
;
	LD	A,(D.CC3F)
	AND	A
	CALL	Z,C.4BD8
;
	LD	A,(D.C326)
	BIT	7,A
	CALL	NZ,C.4BCB
;
	LD	HL,I.D1BD
	LD	C,02H	; 2 
	CALL	C.4C19
;
	JP	J.6A52

J.69E3:	XOR	A
	LD	(D.C4B5),A
J$69E7:	LD	A,(D.C328)
	CP	04H	; 4 
	JR	NZ,J$6A16
;
	LD	A,(D.C9C6)
	RLA	
	JR	NC,J.6A08
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6A08
	CALL	C.49EA
;
	JP	C,J.6AA0
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6A08
;
	JR	J.6A44

J.6A08:	LD	HL,I.78C1
	CALL	C.4C74
;
	EX	DE,HL
	XOR	A
	CALL	C.4D10
;
	JP	J.6A9F

J$6A16:	LD	A,(D.CC4D)
	AND	A
	JR	Z,J$6A22
;
	LD	A,(D.C9C6)
	RLA	
	JR	NC,J.6A36
;
J$6A22:	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6A36
	CALL	C.49EA
;
	JP	C,J.6AA0
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6A36
;
	JR	J.6A44

J.6A36:	LD	HL,I.78C1
	CALL	C.4C74
;
	EX	DE,HL
	LD	A,01H	; 1 
	CALL	C.4D10
;
	JR	J.6A9F

J.6A44:	LD	A,(D.CC3F)
	AND	A
	CALL	Z,C.4975
;
	LD	A,(D.C326)
	RLA	
	CALL	C,C.49DD
;
J.6A52:	LD	A,01H	; 1 
	LD	(D.C354),A
	LD	HL,C.0018
	LD	(D.C337),HL
	LD	A,(D.C328)
	CP	04H	; 4 
	JR	NZ,J$6A6E
;
	LD	HL,C.0018
	LD	(D.C419),HL
	LD	A,01H	; 1 
	JR	J$6A76

J$6A6E:	LD	HL,C.0030
	LD	(D.C419),HL
	LD	A,02H	; 2 
J$6A76:	LD	(D.C355),A
	LD	HL,D.C326
	XOR	A
	BIT	2,(HL)
	JR	Z,J$6A82
;
	INC	A
J$6A82:	LD	(D.C4B3),A
	XOR	A
	BIT	3,(HL)
	JR	Z,J$6A8B
;
	INC	A
J$6A8B:	LD	(D.C4BD),A
	LD	HL,I.78C1
	CALL	C.4C74
;
	PUSH	DE
	POP	IX
	CALL	C.4BB1
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
J.6A9F:	AND	A
J.6AA0:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

?.6AA8:	PUSH	BC
	PUSH	HL
	RLA	
	LD	A,(D.C31B)
	JR	NC,J$6AB3
;
	LD	A,(D.C31A)
J$6AB3:	ADD	A,0BH	; 11 
	LD	L,A
	LD	H,00H
	LD	B,01H	; 1 
	CALL	C.6C6A
;
	AND	A
	POP	HL
	POP	BC
	RET	

?.6AC1:	PUSH	BC
	PUSH	HL
	LD	A,(D.C320)
	AND	A
	JP	Z,J$6AD4
;
	ADD	A,01H	; 1 
	LD	L,A
	LD	H,00H
	LD	B,00H
	CALL	C.6C6A
;
J$6AD4:	AND	A
	POP	HL
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6AD8:	PUSH	BC
	PUSH	HL
	LD	A,0EH	; 14 
	LD	(D.C3C7),A
	LD	L,A
	LD	H,00H
	DEC	HL
	LD	B,00H
	CALL	C.6C6A
;
	LD	HL,C.0030
	LD	(D.C337),HL
	LD	A,01H	; 1 
	LD	(D.C4AE),A
	CALL	C.6B70
;
	JR	C,J$6AF8
;
J$6AF8:	POP	HL
	POP	BC
	RET	

?.6AFB:	PUSH	BC
	PUSH	HL
	RLA	
	LD	A,(D.C31B)
	JR	NC,J$6B06
;
	LD	A,(D.C31A)
J$6B06:	ADD	A,0EH	; 14 
	LD	(D.C3C7),A
	LD	L,A
	LD	H,00H
	DEC	HL
	LD	B,00H
	CALL	C.6C6A
;
	LD	HL,I.0024
	LD	(D.C337),HL
	LD	A,02H	; 2 
	LD	(D.C4AE),A
	CALL	C.6B70
;
	JR	C,J$6B24
;
J$6B24:	POP	HL
	POP	BC
	RET	

J$6B27:	PUSH	BC
	PUSH	HL
	RLA	
	LD	A,(D.C31B)
	JR	NC,J$6B32
;
	LD	A,(D.C31A)
J$6B32:	LD	L,A
	LD	A,18H
	SUB	L
	LD	(D.C3C7),A
	LD	HL,I$000D
	LD	B,00H
	CALL	C.6C6A
;
	LD	A,(D.C3C7)
	LD	L,A
	LD	H,00H
	LD	(D.C337),HL
	LD	A,02H	; 2 
	LD	(D.C4AE),A
	CALL	C.6B70
;
	JR	C,J$6B54
;
J$6B54:	POP	HL
	POP	BC
	RET	

?.6B57:	PUSH	BC
	PUSH	HL
	RLA	
	LD	A,(D.C31A)
	JR	NC,J$6B62
;
	LD	A,(D.C31B)
J$6B62:	ADD	A,0BH	; 11 
	LD	L,A
	LD	H,00H
	LD	B,01H	; 1 
	CALL	C.6C6A
;
	AND	A
	POP	HL
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6B70:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,I.7804
	CALL	C.4C74
;
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	LD	B,(IY)
	LD	C,(IY+1)
	LD	A,(D.CC4C)
	LD	(D.C4B5),A
	CP	02H	; 2 
	JP	NZ,J$6BC7
;
	LD	HL,I.D1BD
	LD	A,(D.CC3F)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	CALL	C.4BBE
;
	JR	C,J$6BC3
;
	LD	A,(D.CC3F)
	AND	A
	CALL	Z,C.4BD8
;
	LD	A,(D.C326)
	BIT	7,A
	CALL	NZ,C.4BCB
;
	LD	A,(D.C328)
	CP	05H	; 5 
	JR	NZ,J$6BC1
;
	LD	HL,I.D1BD
	LD	C,01H	; 1 
	CALL	C.4C19
;
J$6BC1:	JR	J.6C0D

J$6BC3:	XOR	A
	LD	(D.C4B5),A
J$6BC7:	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6BEA
	CALL	C.49EA
;
	JP	C,J$6C62
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6BEA
;
	LD	A,(D.CC3F)
	AND	A
	CALL	Z,C.4975
;
	LD	A,(D.C326)
	BIT	7,A
	CALL	NZ,C.49DD
;
	JR	J.6C0D

J.6BEA:	LD	HL,(D.C337)
	LD	DE,I.0024
	AND	A
	SBC	HL,DE
	JR	NZ,J.6C61
;
	LD	HL,I.78C1
	CALL	C.4C74
;
	EX	DE,HL
	LD	A,(D.C328)
	CP	07H	; 7 
D.6C00	EQU	$-1
	JR	NZ,J$6C07
;
	LD	A,01H	; 1 
	JR	J$6C08

J$6C07:	XOR	A
J$6C08:	CALL	C.4D10
;
	JR	J.6C61

J.6C0D:	LD	A,02H	; 2 
	LD	(D.C354),A
	LD	HL,C.0018
	LD	A,(D.C328)
	CP	07H	; 7 
	LD	A,01H	; 1 
	JR	NZ,J$6C20
;
	INC	A
	ADD	HL,HL
J$6C20:	LD	(D.C355),A
	LD	(D$C395),HL
	LD	(D.C419),HL
	LD	HL,D.C326
	XOR	A
	BIT	2,(HL)
	JR	Z,J$6C32
;
	INC	A
J$6C32:	LD	(D.C4B3),A
	XOR	A
	BIT	3,(HL)
	JR	Z,J$6C3B
;
	INC	A
J$6C3B:	LD	(D.C4BD),A
	LD	HL,I.78C1
	CALL	C.4C74
;
	PUSH	DE
	POP	IX
	CALL	C.4BB1
;
	LD	A,(D.C3C7)
	LD	HL,I.5E14
	PUSH	IX
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	ADD	HL,DE
	LD	(D$C393),HL
	CALL	C$4AE1
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
J.6C61:	AND	A
J$6C62:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6C6A:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	(D.C32E),HL
	LD	(D.C3C0),HL
	LD	HL,I.7804
	CALL	C.4C74
;
	PUSH	DE
	POP	IY
	CALL	C.7051
;
	PUSH	HL
	POP	IY
	LD	A,(D.C325)
	LD	HL,D.C326
	OR	(HL)
	AND	03H	; 3 
	JP	Z,J$6D45
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	DEC	A
	LD	(D$C32B),A
	LD	(D$C3BF),A
	LD	A,B
	AND	A
	JR	Z,J$6CF0
;
	LD	A,(D.C325)
	LD	(D.C906),A
	LD	A,(D.C326)
	LD	(D.C907),A
	LD	A,(D.C328)
	LD	(D.C908),A
	CALL	C.7051
;
	LD	A,(D.C907)
	AND	03H	; 3 
	LD	B,A
	LD	A,(D.C326)
	AND	03H	; 3 
	CP	B
	JR	NZ,J$6CCB
;
	LD	HL,D.C32E
	INC	(HL)
	INC	(HL)
J$6CCB:	LD	A,(D.C906)
	AND	03H	; 3 
	LD	B,A
	LD	A,(D.C325)
	AND	03H	; 3 
	CP	B
	JR	NZ,J$6CDE
;
	LD	HL,D.C3C0
	INC	(HL)
	INC	(HL)
J$6CDE:	LD	A,(D.C907)
	LD	(D.C326),A
	LD	A,(D.C906)
	LD	(D.C325),A
	LD	A,(D.C908)
	LD	(D.C328),A
J$6CF0:	LD	HL,I.78C1
	CALL	C.4C74
;
	LD	(D$C329),DE
	PUSH	DE
	POP	IX
	LD	A,(D.C328)
	LD	C,A
	LD	B,00H
	LD	HL,I$6D4D
	ADD	HL,BC
	LD	L,(HL)
	LD	H,00H
	ADD	HL,DE
	LD	(D.C32C),HL
	LD	A,(D.C3C5)
	DEC	A
	JR	Z,J$6D33
;
	LD	(D.C3C5),A
	LD	HL,I.7804
	CALL	C.4C74
J$6D1B	EQU	$-2
;
	LD	HL,I.FFFE
	AND	A
	SBC	HL,DE
	JR	NZ,J$6D2F
;
	PUSH	IX
	POP	HL
	LD	DE,C.0030
	ADD	HL,DE
	LD	(D.C32C),HL
J$6D2F:	LD	HL,D.C3C5
	INC	(HL)
J$6D33:	LD	B,01H	; 1 
	LD	A,(D.C325)
	AND	03H	; 3 
	CALL	NZ,C$6D8F
;
	LD	A,(D.C326)
	AND	03H	; 3 
	CALL	NZ,C$6D55
;
J$6D45:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
I$6D4D:	RET	

?.6D4E:	JR	J$6D68

?.6D50:	JR	J$6D6A

?.6D52:	JR	J.6D84

?.6D54:	JR	NC,J$6D1B
C$6D55	EQU	$-1
;
	PUSH	DE
	PUSH	HL
	LD	HL,I$79FC
	CALL	C.4C74
;
	LD	A,(D.C326)
	AND	03H	; 3 
	CP	D
	JR	Z,J$6D69
;
	LD	D,A
	LD	E,01H	; 1 
J$6D68	EQU	$-1
J$6D69:	LD	C,E
J$6D6A:	LD	A,B
	OR	A
	JR	Z,J.6D79
;
	LD	C,03H	; 3 
	DEC	E
	JR	Z,J.6D79
;
	LD	C,04H	; 4 
	DEC	E
	JR	Z,J.6D79
;
	LD	C,E
J.6D79:	LD	B,01H	; 1 
	LD	A,D
	DEC	A
	JR	NZ,J.6D84
	CALL	C$49F7
;
	JR	J$6D87

J.6D84:	CALL	C$4A11
;
J$6D87:	LD	E,A
	CALL	C.4C81
;
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6D8F:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	DEC	IX
	DEC	IX
	LD	HL,I$797E
	CALL	C.4C74
;
	LD	A,(D.C325)
	AND	03H	; 3 
	CP	03H	; 3 
	JR	Z,J$6DC1
;
	LD	E,A
	AND	A
	JR	Z,J$6DCC
;
	CP	01H	; 1 
	JR	NZ,J$6DB8
;
	LD	C,02H	; 2 
	CALL	C.4A52
;
	LD	A,01H	; 1 
	JR	J.6DCB

J$6DB8:	LD	C,04H	; 4 
	CALL	C.4A52
;
	LD	A,01H	; 1 
	JR	J.6DCB

J$6DC1:	LD	C,E
	CP	D
	JR	Z,J$6DC8
;
	LD	C,01H	; 1 
	LD	D,A
J$6DC8:	CALL	C$4A04
;
J.6DCB:	LD	E,A
J$6DCC:	CALL	C.4C81
;
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6DD5:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.C917)
	AND	A
	JR	Z,J.6E42
;
	LD	HL,(D.C910)
	LD	A,L
	OR	H
	JR	Z,J$6DED
;
	DEC	HL
	LD	(D.C910),HL
	JR	J.6E42

J$6DED:	LD	IX,D.C39D
	LD	L,(IX)
	LD	H,(IX+1)
	LD	B,(HL)
	INC	HL
	LD	A,B
	CP	20H	; " "
	JR	C,J.6E42
;
	CP	80H
	JR	C,J$6E0A
;
	CP	0A0H
	JR	C,J.6E42
;
	CP	0E0H
	JR	NC,J.6E42
;
J$6E0A:	LD	(IX),L
	LD	(IX+1),H
	CP	20H	; " "
	JR	Z,J$6E38
	CALL	C.4ECA
	CALL	C.4EBD
	CALL	C.49EA
;
	JR	C,J$6E43
;
	LD	A,(D.CC3F)
	AND	A
	CALL	NZ,C.49DD
;
	XOR	A
	CALL	C.4AEE
	CALL	C.4975
;
	LD	HL,(D.C3A0)
	CALL	C.703E
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
J$6E38:	LD	HL,D.C917
	DEC	(HL)
	LD	HL,I.0001
	LD	(D.C910),HL
J.6E42:	AND	A
J$6E43:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6E49:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.C919)
	AND	A
	JR	Z,J.6EC7
;
	LD	HL,(D.C913)
	LD	A,L
	OR	H
	JR	Z,J$6E61
;
	DEC	HL
	LD	(D.C913),HL
	JR	J.6EC7

J$6E61:	LD	IX,D.C3B1
	LD	L,(IX)
	LD	H,(IX+1)
	LD	B,(HL)
	INC	HL
	LD	A,B
	CP	20H	; " "
	JR	C,J.6EC7
;
	CP	30H	; "0"
	JR	C,J.6E93
;
	CP	3AH	; ":"
	JR	C,J$6E80
;
	CP	40H	; "@"
	JR	C,J.6E93
;
	JR	J.6EC7

J$6E80:	LD	A,(D.CC3F)
	AND	A
	JR	NZ,J.6EC7
;
	LD	(IX),L
	LD	(IX+1),H
	CALL	C.49EA
;
	JR	C,J.6EC8
;
	JR	J$6EAF

J.6E93:	LD	(IX),L
	LD	(IX+1),H
	CALL	C.4ECA
	CALL	C.4EBD
	CALL	C.49EA
;
	JR	C,J.6EC8
;
	LD	A,(D.CC3F)
	AND	A
	CALL	NZ,C.4975
;
	XOR	A
	CALL	C.4AEE
;
J$6EAF:	CALL	C.4975
;
	LD	HL,(D.C3B5)
	CALL	C.703E
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	LD	HL,D.C919
	DEC	(HL)
	LD	HL,I.0001
	LD	(D.C913),HL
J.6EC7:	AND	A
J.6EC8:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6ECE:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.C917)
	AND	A
	JP	Z,J.6F65
;
	LD	HL,(D.C910)
	LD	A,L
	OR	H
	JR	Z,J$6EE8
;
	DEC	HL
	LD	(D.C910),HL
	JP	J.6F65

J$6EE8:	LD	IX,D.C39D
	LD	L,(IX)
	LD	H,(IX+1)
	LD	B,(HL)
	INC	HL
	LD	A,B
	CP	20H	; " "
	JR	C,J.6F05
;
	CP	80H
	JR	C,J.6F65
;
	CP	0A0H
	JR	C,J.6F05
;
	CP	0E0H
	JR	C,J.6F65
;
J.6F05:	LD	C,(HL)
	INC	HL
	LD	(IX),L
	LD	(IX+1),H
	LD	A,(D.CC4C)
	CP	02H	; 2 
	JR	NZ,J$6F25
;
	LD	A,(D.CC3F)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	01H	; 1 
	LD	HL,I.D1BD
	CALL	C.4BBE
;
	JR	NC,J$6F3F
;
J$6F25:	CALL	C$7309
;
	LD	A,(D.C9C6)
	RLCA	
	JR	NC,J.6F53
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6F53
	CALL	C.49EA
;
	JR	C,J$6F66
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.6F53
;
J$6F3F:	LD	A,(D.CC3F)
	AND	A
	CALL	Z,C.4975
;
	LD	HL,(D.C3A0)
	CALL	C.703E
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	JR	J$6F5A

J.6F53:	LD	HL,(D.C3A0)
	XOR	A
	CALL	C.4D10
;
J$6F5A:	LD	HL,D.C917
	DEC	(HL)
	DEC	(HL)
	LD	HL,I.0002
	LD	(D.C910),HL
J.6F65:	AND	A
J$6F66:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6F6C:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.C919)
	AND	A
	JP	Z,J.7037
;
	LD	HL,(D.C913)
	LD	A,L
	OR	H
	JR	Z,J$6F86
;
	DEC	HL
	LD	(D.C913),HL
	JP	J.7037

J$6F86:	LD	IX,D.C3B1
	LD	L,(IX)
	LD	H,(IX+1)
	LD	B,(HL)
	INC	HL
	LD	A,B
	CP	0FFH
	JR	Z,J$6FE6
;
	CP	30H	; "0"
	JP	C,J.7037
;
	CP	3AH	; ":"
	JR	C,J$6FA8
;
	CP	82H
	JP	Z,J$7018
;
	JP	J.7037

J$6FA8:	LD	A,(D.CC3F)
	AND	A
	JP	Z,J.7037
;
	LD	(IX),L
	LD	(IX+1),H
	CALL	C.49EA
;
	JP	C,J.7038
;
	LD	HL,I.D1BD
	LD	DE,I.C91B
	LD	BC,I.0024
	LDIR	
	LD	L,(IX)
	LD	H,(IX+1)
	LD	B,(HL)
	INC	HL
	LD	(IX),L
	LD	(IX+1),H
	CALL	C.49EA
;
	JR	C,J.7038
;
	LD	HL,I.C91B
	LD	DE,I$D1E1
	LD	BC,I.0024
	LDIR	
	JR	J$700B

J$6FE6:	LD	A,(D.CC3F)
	AND	A
	JR	Z,J.7037
;
	LD	B,(HL)
	INC	HL
	LD	(IX),L
	LD	(IX+1),H
	CALL	C.49EA
;
	JR	C,J.7038
;
	LD	HL,I$D1E0
	LD	DE,I$D1F2
	LD	BC,I.0024
D.7000	EQU	$-2
	LDDR	
	XOR	A
	LD	B,12H	; 18 
J$7007:	LD	(DE),A
	DEC	DE
	DJNZ	J$7007
;
J$700B:	LD	HL,(D.C3B5)
	CALL	C.703E
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	JR	J$702C

J$7018:	LD	C,(HL)
	INC	HL
	LD	A,C
	CP	6FH	; "o"
	JR	NZ,J.7037
;
	LD	(IX),L
	LD	(IX+1),H
	LD	HL,(D.C3B5)
	XOR	A
	CALL	C.4D10
;
J$702C:	LD	HL,D.C919
	DEC	(HL)
	DEC	(HL)
	LD	HL,I.0002
	LD	(D.C913),HL
J.7037:	AND	A
J.7038:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.703E:	LD	BC,I$0048
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I.D1BD
	CALL	C$4A86
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7051:	PUSH	BC
	PUSH	DE
	PUSH	IX
	PUSH	IY
	POP	HL
	LD	A,04H	; 4 
	LD	(D.C328),A
	XOR	A
	LD	(D.C325),A
	LD	(D.C326),A
J$7064:	LD	A,(HL)
	CP	1FH
	JP	Z,J$70A8
;
	CP	1EH
	JP	Z,J$70BC
;
	CP	1DH
	JP	Z,J$70D0
;
	CP	0DH	; 13 
	JP	Z,J$70E4
;
	CP	0CH	; 12 
	JP	Z,J$70F8
;
	CP	1AH
	JP	Z,J$7104
;
	CP	1BH
	JP	Z,J$7090
;
	CP	1CH
	JP	Z,J$709B
;
	JP	J.7118

J$7090:	INC	HL
	LD	A,(HL)
	CP	1BH
	JP	NZ,J.7118
;
	DEC	HL
	JP	J.71A6

J$709B:	INC	HL
	LD	A,(HL)
	CP	1CH
	JR	NZ,J.7118
;
	INC	HL
	INC	IY
	INC	IY
	JR	J$7064

J$70A8:	INC	HL
	LD	A,(HL)
	DEC	HL
	CP	1FH
	JP	NZ,J.7118
;
	LD	BC,I.0002
	ADD	HL,BC
	LD	A,08H	; 8 
	LD	(D.C328),A
	JP	J.71A6

J$70BC:	INC	HL
	LD	A,(HL)
	DEC	HL
	CP	1EH
	JP	NZ,J.7118
;
	LD	BC,I.0002
	ADD	HL,BC
	LD	A,09H	; 9 
	LD	(D.C328),A
	JP	J.71A6

J$70D0:	INC	HL
	LD	A,(HL)
	DEC	HL
	CP	1DH
	JP	NZ,J.7118
;
	LD	BC,I.0002
	ADD	HL,BC
	LD	A,0AH	; 10 
	LD	(D.C328),A
	JP	J.71A6

J$70E4:	INC	HL
	LD	A,(HL)
	DEC	HL
	CP	0AH	; 10 
	JP	NZ,J.7118
;
	LD	BC,I.0001
	ADD	HL,BC
	LD	A,0BH	; 11 
	LD	(D.C328),A
	JP	J.71A6

J$70F8:	LD	BC,I.0001
	ADD	HL,BC
	LD	A,0CH	; 12 
	LD	(D.C328),A
	JP	J.71A6

J$7104:	INC	HL
	LD	A,(HL)
	DEC	HL
	CP	1AH
	JP	NZ,J.7118
;
	LD	BC,I.0002
	ADD	HL,BC
	LD	A,0DH	; 13 
	LD	(D.C328),A
	JP	J.71A6

J.7118:	CP	0E0H
	JP	NC,J.713B
;
	CP	20H	; " "
	JP	C,J.713B
;
	CP	0A0H
	JP	NC,J.712F
;
	CP	7FH
	JP	C,J.712F
;
	JP	J.713B

J.712F:	LD	BC,I.0001
	ADD	HL,BC
	LD	A,03H	; 3 
	LD	(D.C328),A
	JP	J$713F

J.713B:	LD	BC,I.0002
	ADD	HL,BC
J$713F:	LD	A,(HL)
	CP	08H	; 8 
	JP	NC,J.71A6
;
	PUSH	HL
	POP	DE
	LD	BC,I.0001
	ADD	HL,BC
	LD	A,(HL)
	LD	(D.C325),A
	AND	0F0H
	CP	80H
	JR	Z,J$716B
;
	CP	90H
	JR	Z,J$7172
;
	CP	40H	; "@"
	JR	Z,J$7179
;
	CP	20H	; " "
	JR	Z,J$7180
;
	CP	10H	; 16 
	JR	Z,J$7187
;
	CP	30H	; "0"
	JR	Z,J$718E
;
	JR	J.7195

J$716B:	LD	A,01H	; 1 
	LD	(D.C328),A
	JR	J.7195

J$7172:	LD	A,02H	; 2 
	LD	(D.C328),A
	JR	J.7195

J$7179:	LD	A,03H	; 3 
	LD	(D.C328),A
	JR	J.7195

J$7180:	LD	A,05H	; 5 
	LD	(D.C328),A
	JR	J.7195

J$7187:	LD	A,06H	; 6 
	LD	(D.C328),A
	JR	J.7195

J$718E:	LD	A,07H	; 7 
	LD	(D.C328),A
	JR	J.7195

J.7195:	LD	BC,I.0001
	ADD	HL,BC
	LD	A,(DE)
	CP	02H	; 2 
	JR	Z,J.71A6
;
	LD	A,(HL)
	LD	(D.C326),A
	LD	BC,I.0001
	ADD	HL,BC
J.71A6:	CALL	C$71AF
;
	XOR	A
	POP	IX
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$71AF:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,(IY)
	LD	C,(IY+1)
	LD	E,00H
	LD	A,B
	CP	81H
	JP	C,J.72A9
;
	JR	Z,J$71C8
;
	INC	E
	INC	E
	INC	E
	JR	J$723D

J$71C8:	LD	A,(D.CC3F)
	AND	A
	LD	A,C
	JR	NZ,J$71E4
;
	INC	E
	CP	9FH
	JP	C,J.72A9
;
	CP	0ADH
	JP	C,J.72AC
;
	INC	E
	INC	E
	CP	0FDH
	JP	C,J.72AC
;
	JP	J.72A9

J$71E4:	CP	43H	; "C"
	JP	C,J.72A9
;
	CP	45H	; "E"
	JP	C,J.72AC
;
	CP	4AH	; "J"
	JP	C,J.72A9
;
	CP	4CH	; "L"
	JP	C,J.72AC
;
	CP	65H	; "e"
	JP	C,J.72A9
;
	CP	69H	; "i"
	JP	C,J.72AC
;
	CP	7CH	; "|"
	JP	C,J.72A9
;
	CP	7DH	; "}"
	JP	C,J.72AC
;
	CP	82H
	JP	C,J.72A9
;
	CP	87H
	JP	C,J.72AC
;
	CP	8BH
	JP	C,J.72A9
;
	CP	8EH
	JP	C,J.72AC
;
	CP	9FH
	JP	C,J.72A9
;
	INC	E
	CP	0A8H
	JP	C,J.72AC
;
	INC	E
	CP	0ACH
	JR	C,J.72AC
;
	DEC	E
	CP	0ADH
	JR	C,J.72AC
;
	INC	E
	INC	E
	CP	0FDH
	JR	C,J.72AC
;
	JR	J.72A9

J$723D:	INC	E
	LD	A,B
	CP	98H
	JR	C,J.72A9
;
	JR	NZ,J$724C
;
	LD	A,C
	CP	9EH
	JR	C,J.72A9
;
	JR	J.72AC

J$724C:	LD	A,B
	CP	9FH
	JR	C,J.72AC
;
	JR	NZ,J$725A
;
	LD	A,C
	CP	0FDH
	JR	C,J.72AC
;
	JR	J.72A9

J$725A:	CP	0E0H
	JR	C,J.72A9
;
	JR	NZ,J$7267
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.72A9
;
	JR	J.72AC

J$7267:	CP	0EAH
	JR	C,J.72AC
;
	JR	NZ,J$7274
;
	LD	A,C
	CP	0A3H
	JR	C,J.72AC
;
	JR	J.72A9

J$7274:	INC	E
	CP	0F0H
	JR	C,J.72A9
;
	JR	NZ,J$7286
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.72A9
;
	CP	69H	; "i"
	JR	C,J.72AC
;
	JR	J.72A9

J$7286:	INC	E
	CP	0FBH
	JR	NZ,J$7296
;
	LD	A,C
	CP	0ADH
	JR	C,J.72A9
;
	CP	0E9H
	JR	C,J.72AC
;
	JR	J.72A9

J$7296:	INC	E
	CP	0FDH
	JR	NZ,J.72A9
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.72A9
;
	CP	9FH
	JR	C,J.72AC
;
	INC	E
	CP	0FDH
J$72A7:	JR	C,J.72AC
;
J.72A9:	XOR	A
	JR	J$72BD

J.72AC:	LD	D,00H
	LD	L,E
	LD	H,D
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	LD	A,(D.D497)
	LD	E,A
	ADD	HL,DE
	LD	DE,I.72DC
	ADD	HL,DE
	LD	A,(HL)
J$72BD:	LD	HL,D.C9C6
	LD	(HL),A
	LD	A,(D.C326)
	AND	0DCH
	JR	Z,J$72CA
;
	SET	7,(HL)
J$72CA:	LD	HL,I.FBC3
	AND	A
	SBC	HL,BC
	JR	NZ,J$72D7
;
	LD	HL,D.C9C6
	SET	7,(HL)
J$72D7:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

I.72DC:	NOP	
	ADD	A,B
	ADD	A,B
	ADD	A,B
	NOP	
	LD	BC,I$0801
	EX	AF,AF'
	LD	BC,I$8101
	ADC	A,B
	ADC	A,B
	LD	BC,I$0101
	ADD	A,C
	ADD	A,C
	LD	BC,I$8202
	ADD	A,D
	LD	(BC),A
	LD	(BC),A
	ADD	A,H
	ADD	A,H
	ADD	A,H
	ADD	A,H
	ADD	A,H
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
J$72FF:	DJNZ	J$7311
;
	SUB	B
	SUB	B
	DJNZ	J$7325
;
	JR	NZ,J$72A7
;
	AND	B
	JR	NZ,J$72FF
C$7309	EQU	$-1
;
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	E,00H
	LD	A,B
	CP	81H
J$7311	EQU	$-1
	JP	C,J.73FD
;
	JR	Z,J$731C
;
	INC	E
	INC	E
	INC	E
	JR	J$7391

J$731C:	LD	A,(D.CC3F)
	AND	A
	LD	A,C
	JR	NZ,J$7338
;
	INC	E
	CP	9FH
J$7325	EQU	$-1
	JP	C,J.73FD
;
	CP	0ADH
	JP	C,J.7400
;
	INC	E
	INC	E
	CP	0FDH
	JP	C,J.7400
;
	JP	J.73FD

J$7338:	CP	43H	; "C"
	JP	C,J.73FD
;
	CP	45H	; "E"
	JP	C,J.7400
;
	CP	4AH	; "J"
	JP	C,J.73FD
;
	CP	4CH	; "L"
	JP	C,J.7400
;
	CP	65H	; "e"
	JP	C,J.73FD
;
	CP	69H	; "i"
	JP	C,J.7400
;
	CP	7CH	; "|"
	JP	C,J.73FD
;
	CP	7DH	; "}"
	JP	C,J.7400
;
	CP	82H
	JP	C,J.73FD
;
	CP	87H
	JP	C,J.7400
;
	CP	8BH
	JP	C,J.73FD
;
	CP	8EH
	JP	C,J.7400
;
	CP	9FH
	JP	C,J.73FD
;
	INC	E
	CP	0A8H
	JP	C,J.7400
;
	INC	E
	CP	0ACH
	JR	C,J.7400
;
	DEC	E
	CP	0ADH
	JR	C,J.7400
;
	INC	E
	INC	E
	CP	0FDH
	JR	C,J.7400
;
	JR	J.73FD

J$7391:	INC	E
	LD	A,B
	CP	98H
	JR	C,J.73FD
;
	JR	NZ,J$73A0
;
	LD	A,C
	CP	9EH
	JR	C,J.73FD
;
	JR	J.7400

J$73A0:	LD	A,B
	CP	9FH
	JR	C,J.7400
;
	JR	NZ,J$73AE
;
	LD	A,C
	CP	0FDH
	JR	C,J.7400
;
	JR	J.73FD

J$73AE:	CP	0E0H
	JR	C,J.73FD
;
	JR	NZ,J$73BB
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.73FD
;
	JR	J.7400

J$73BB:	CP	0EAH
	JR	C,J.7400
;
	JR	NZ,J$73C8
;
	LD	A,C
	CP	0A3H
	JR	C,J.7400
;
	JR	J.73FD

J$73C8:	INC	E
	CP	0F0H
	JR	C,J.73FD
;
	JR	NZ,J$73DA
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.73FD
;
	CP	69H	; "i"
	JR	C,J.7400
;
	JR	J.73FD

J$73DA:	INC	E
	CP	0FBH
	JR	NZ,J$73EA
;
	LD	A,C
	CP	0ADH
	JR	C,J.73FD
;
	CP	0E9H
	JR	C,J.7400
;
	JR	J.73FD

J$73EA:	INC	E
	CP	0FDH
	JR	NZ,J.73FD
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.73FD
;
	CP	9FH
	JR	C,J.7400
;
	INC	E
	CP	0FDH
	JR	C,J.7400
;
J.73FD:	XOR	A
	JR	J$7411

J.7400:	LD	D,00H
	LD	L,E
	LD	H,D
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	LD	A,(D.D497)
	LD	E,A
	ADD	HL,DE
	LD	DE,I.72DC
	ADD	HL,DE
	LD	A,(HL)
J$7411:	LD	(D.C9C6),A
	LD	HL,I.FBC3
	AND	A
	SBC	HL,BC
	JR	NZ,J$7424
;
	LD	A,(D.C9C6)
	OR	80H
	LD	(D.C9C6),A
J$7424:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

J.7429:	XOR	A
	LD	(D.D464),A
	LD	(D$CCEE),A
	LD	A,0EH	; 14 
	LD	(D.D524),A
	LD	A,9FH
	CALL	C.4D5E
;
	LD	A,(D$DB17)
	AND	A
	JR	Z,J$7444
	CALL	C$778A
;
	RET	

J$7444:	CALL	C.4D6B
;
	LD	A,0A0H
	CALL	C.4D5E
;
	LD	IY,D.D464
	CALL	C.7A43
;
J.7453:	LD	IX,I$7484
	CALL	C.4D51
	JR	C,J$7461
	CALL	C$7AAF
;
	JR	J.7453

J$7461:	LD	BC,I$746A
	PUSH	BC
	LD	IY,D.D464
	JP	(HL)

I$746A:	LD	A,(D.D464)
	AND	A
	JR	Z,J$747B
;
	CP	80H
	RET	Z
;
	CP	0FFH
	RET	Z
;
	XOR	A
	LD	(D.D464),A
	RET	

J$747B:	LD	IY,D.D464
	CALL	C.7A43
;
	JR	J.7453

I$7484:	INC	BC
	ADC	A,L
	LD	(HL),H
	RST	38H
	RST	38H
	CALL	NZ,C$FF74
;
	RST	38H
	ADD	HL,BC
	LD	(BC),A
	LD	(DE),A
	DEFB	0FDH		; << Illegal Op Code Byte >>
;	-----------------
;
	XOR	E
	LD	A,(D$3075)
	NOP	
	LD	B,B
	RRCA	
	LD	H,A
	LD	A,D
	LD	B,C
	NOP	
	LD	D,H
	RRCA	
	LD	A,C
	LD	A,D
	LD	D,L
	NOP	
	LD	H,B
	RRCA	
	SUB	C
	LD	A,D
	LD	H,C
	NOP	
	LD	L,H
	RRCA	
	LD	A,A
	LD	A,D
	LD	L,L
	NOP	
	LD	A,B
	RRCA	
	ADD	A,L
	LD	A,D
	LD	A,C
	NOP	
	ADD	A,H
	RRCA	
	ADC	A,E
	LD	A,D
	ADD	A,L
	NOP	
	SBC	A,B
	RRCA	
	LD	(HL),E
	LD	A,D
	SBC	A,C
	NOP	
	XOR	E
	RRCA	
	LD	L,L
	LD	A,D
	DJNZ	J$74DD
;
	JP	C,J$1E4F
;
	LD	D,L
	LD	A,D
	RRA	
	LD	E,E
	LD	A,D
	INC	E
	LD	C,C
	LD	A,D
	DEC	E
	LD	C,A
	LD	A,D
	PUSH	AF
	LD	H,A
	LD	A,D
	RET	M
;
	LD	L,L
	LD	A,D
	OR	79H	; "y"
	LD	A,D
J$74DD:	RST	30H
;
	LD	(HL),E
	LD	A,D
	DEC	D
	SUB	C
	LD	A,D
	LD	D,8BH
	LD	A,D
	INC	DE
	ADD	A,L
	LD	A,D
	INC	D
	LD	A,A
	LD	A,D
	DEC	BC
	DEC	A
	LD	(HL),L
	DEC	DE
	LD	A,(BC)
	LD	(HL),L
	RLCA	
	LD	HL,(D$3A75)
	LD	A,B
	CALL	NC,C$3A47
;
	LD	(HL),L
	CALL	NC,C$3290
;
	RET	NZ
	CALL	NC,C$753A
	CALL	NC,C$8FCD
;
	LD	A,B
	CALL	C,C$7715
;
	RET	

?.750A:	LD	A,00H
	CALL	C.4D5E
;
	LD	A,03H	; 3 
	CALL	C.4D5E
	CALL	C.77D6
;
	LD	HL,I.C898
	LD	(HL),0FFH
	LD	DE,I.C899
	LD	BC,I.0063
	LDIR	
	LD	A,0FFH
	LD	(D.D464),A
	RET	

?.752A:	LD	A,9FH
	CALL	C.4D5E
;
	LD	A,03H	; 3 
	CALL	C.4D5E
;
	LD	A,80H
	LD	(D.D464),A
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$753A:	CALL	C$7A61
;
	LD	A,03H	; 3 
	CALL	C.4D5E
	CALL	C$7764
;
	LD	A,0A0H
	CALL	C.4D5E
;
	RET	

J$754B:	LD	A,(D.D478)
	LD	(D.D4C0),A
	LD	A,(D.D47B)
	LD	(D.C2F9),A
	CALL	C.7935
;
J$755A:	LD	A,(D.D4C0)
	CALL	C.764C
;
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	JR	Z,J$757A
;
	LD	A,(D.D4C0)
	CALL	C.788F
;
	JP	NC,J.75AB
;
	JP	J$75A5

J$757A:	LD	A,(D.D4C0)
	CALL	C.788F
;
	JR	NC,J.75AB
;
	LD	A,(D.C2F9)
	CALL	C.5108
;
	LD	A,(D.C2F9)
	INC	A
	LD	(D.C2F9),A
	LD	B,A
	LD	A,(D.D47D)
	CP	B
	JR	C,J$75C4
;
	LD	A,(D.D4C0)
	INC	A
	LD	(D.D4C0),A
	LD	A,(D.C2F9)
	CALL	C.5108
;
	JR	J.75AB

J$75A5:	LD	A,(D.C2F9)
	CALL	C.5108
;
J.75AB:	LD	A,(D.D4C0)
	INC	A
	LD	(D.D4C0),A
	LD	A,(D.C2F9)
	INC	A
	LD	(D.C2F9),A
	LD	A,(D.C2F9)
	LD	B,A
	LD	A,(D.D47D)
	CP	B
	JP	NC,J$755A
;
J$75C4:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.75C5:	LD	A,(D.D478)
	LD	(D.D4C0),A
	LD	A,(D.D47B)
	LD	(D.C2F9),A
	CALL	C.7935
;
J$75D4:	LD	A,(D.D473)
	LD	B,A
	LD	A,(D.D4C0)
	LD	C,A
	PUSH	DE
	CALL	C.4E62
;
	POP	DE
	LD	A,(D.D4C0)
	CALL	C.764C
;
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	JR	Z,J$7601
;
	LD	A,(D.D4C0)
	CALL	C.78F6
;
	JP	NC,J.7632
;
	JP	J$762C

J$7601:	LD	A,(D.D4C0)
	CALL	C.78F6
;
	JR	NC,J.7632
;
	LD	A,(D.C2F9)
	CALL	C.5108
;
	LD	A,(D.C2F9)
	INC	A
	LD	(D.C2F9),A
	LD	B,A
	LD	A,(D.D47D)
	CP	B
	JR	C,J$764B
;
	LD	A,(D.D4C0)
	INC	A
	LD	(D.D4C0),A
	LD	A,(D.C2F9)
	CALL	C.5108
;
	JR	J.7632

J$762C:	LD	A,(D.C2F9)
	CALL	C.5108
;
J.7632:	LD	A,(D.D4C0)
	INC	A
	LD	(D.D4C0),A
	LD	A,(D.C2F9)
	INC	A
	LD	(D.C2F9),A
	LD	A,(D.C2F9)
	LD	B,A
	LD	A,(D.D47D)
	CP	B
	JP	NC,J$75D4
;
J$764B:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.764C:	PUSH	DE
	PUSH	AF
	LD	DE,I.007E
	LD	HL,(D.D473)
	LD	H,00H
	CALL	C.4D37
;
	POP	AF
	SLA	A
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	DE,I.D561
	ADD	HL,DE
	PUSH	HL
	POP	IY
	POP	DE
	RET	

J$7669:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,(D.D48F)
	BIT	1,A
	JP	Z,J.76C7
;
	PUSH	DE
	PUSH	BC
	CALL	C.7935
;
	POP	BC
	POP	DE
	LD	A,(D$D44B)
	OR	A
	JR	Z,J$76A9
;
	LD	A,C
	PUSH	BC
	CALL	C.764C
;
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	POP	BC
	JR	NZ,J$769B
;
	INC	C
J$769B:	LD	A,(D$D4AF)
	CP	C
	JP	NZ,J.76C7
;
	LD	A,D
	LD	(D.D4C0),A
	JP	J$76BC

J$76A9:	LD	A,(D.C8FF)
	OR	A
	JR	Z,J.76C7
;
	LD	A,D
	LD	(D.D4C0),A
	LD	A,C
	PUSH	BC
	CALL	C.788F
;
	POP	BC
	JP	NC,J.76C7
;
J$76BC:	LD	A,0EH	; 14 
	LD	(D.D524),A
	LD	A,(D.D4C0)
	CALL	C.5108
;
J.76C7:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

?.76D0:	PUSH	BC
	PUSH	DE
	PUSH	AF
	LD	DE,I.007E
	LD	HL,(D.D473)
	LD	H,00H
	CALL	C.4D37
;
	POP	AF
	LD	D,00H
	LD	E,A
	INC	DE
	ADD	HL,DE
	LD	DE,I.D561
	ADD	HL,DE
	PUSH	HL
	POP	IY
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.76FA:	LD	A,(D.D473)
	LD	B,A
	LD	A,(D.D475)
	LD	C,A
	CALL	C.4E62
;
	LD	A,(D.D478)
	LD	B,A
	LD	A,(D.D475)
	SUB	B
	LD	B,A
	LD	A,(D.D47B)
	ADD	A,B
	LD	(D.D4C0),A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7715:	LD	A,0EH	; 14 
	LD	(D.D524),A
	CALL	C.773B
;
	JR	NZ,J.7734
;
	LD	A,(D.D4C0)
	AND	A
	JR	Z,J.7734
;
	LD	A,(D.D4C0)
	DEC	A
	CALL	C.5108
;
	LD	A,(D.D4C0)
	CALL	C.5108
;
	JR	J$773A

J.7734:	LD	A,(D.D4C0)
	CALL	C.5108
;
J$773A:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.773B:	LD	HL,I.007E
	LD	DE,(D.D473)
	LD	D,00H
	CALL	C.4D37
;
	LD	DE,I.D561
	ADD	HL,DE
	LD	DE,(D.D475)
	LD	D,00H
	SLA	E
	ADD	HL,DE
	PUSH	HL
	POP	IY
	LD	B,(IY-1)
	LD	C,(IY-2)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7764:	LD	A,(D.D478)
	LD	B,A
	LD	A,(D.D475)
	SUB	B
	LD	B,A
	LD	A,(D.D47B)
	ADD	A,B
	LD	(D.D4C0),A
	PUSH	BC
	CALL	C.7935
;
	POP	BC
	LD	A,(D.D475)
	CALL	C$78C8
;
	JR	NC,J$7786
	CALL	C$79CA
;
	JR	J$7789

J$7786:	CALL	C$7960
;
J$7789:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$778A:	CALL	C$7924
;
	JP	NC,J$7889
;
	LD	A,0AEH
	CALL	C.4D5E
;
J.7795:	LD	IX,I$7860
	CALL	C.4D51
	JR	C,J$77A0
;
	JR	J.7795

J$77A0:	LD	BC,I$77A5
	PUSH	BC
	JP	(HL)

I$77A5:	LD	A,(D.D464)
	AND	A
	JR	Z,J$77B6
;
	CP	0FFH
	RET	Z
;
	CP	80H
	RET	Z
;
	XOR	A
	LD	(D.D464),A
	RET	

J$77B6:	JR	NZ,J.7795
;
	LD	A,03H	; 3 
	CALL	C.4D5E
;
	LD	A,80H
	LD	(D.D464),A
	CALL	C.4D6B
	CALL	C.77D6
;
	LD	HL,I.C898
	LD	(HL),0FFH
	LD	DE,I.C899
	LD	BC,I.0063
	LDIR	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.77D6:	CALL	C.7935
;
	LD	A,(D.C8FF)
	AND	A
	JR	Z,J$77E2
	CALL	C.75C5
;
J$77E2:	XOR	A
	LD	(D.C8FF),A
	CALL	C.77F1
;
	LD	A,(D.D552)
	AND	A
	CALL	NZ,C.4EB0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.77F1:	LD	HL,I.C898
	LD	(HL),0FFH
	LD	DE,I.C899
	LD	BC,I.0063
	LDIR	
	RET	

J$77FF:	CALL	C.7935
D.7800	EQU	$-2
;
	LD	A,(D.C8FF)
I.7804	EQU	$-1
	AND	A
	JR	Z,J$780B
	CALL	C.75C5
;
J$780B:	LD	A,(D.D48F)
	RES	1,A
	LD	(D.D48F),A
	LD	A,(D.D552)
	AND	A
	CALL	NZ,C.4EB0
;
	RET	

J$781B:	CALL	C.7935
;
	LD	A,(D.C8FF)
	AND	A
	JR	Z,J$7827
	CALL	C.75C5
;
J$7827:	LD	A,(D.D48F)
	SET	1,A
	LD	(D.D48F),A
	LD	A,(D.D552)
	AND	A
	CALL	NZ,C.4EB0
;
	RET	

?.7837:	LD	A,03H	; 3 
	CALL	C.4D5E
J$783A	EQU	$-2
	CALL	C.4D6B
	CALL	C.77D6
;
	LD	HL,I.C898
	LD	(HL),0FFH
	LD	DE,I.C899
	LD	BC,I.0063
	LDIR	
	LD	A,0FFH
	LD	(D.D464),A
	RET	

?.7855:	LD	A,03H	; 3 
	CALL	C.4D5E
;
	LD	A,01H	; 1 
	LD	(D.D464),A
	RET	

I$7860:	INC	BC
	LD	L,C
	LD	A,B
	RST	38H
	RST	38H
	LD	A,H
	LD	A,B
	RST	38H
	RST	38H
	INC	BC
	LD	D,L
	LD	(HL),B
	OR	E
	ADD	A,D
	CP	B
	LD	(HL),A
	ADD	A,L
	LD	C,E
	SUB	A
	LD	E,H
	SCF	
	LD	A,B
	SBC	A,C
	LD	C,E
	XOR	A
	LD	E,H
	LD	D,L
	LD	A,B
	INC	B
	DEC	BC
	CP	B
	LD	(HL),A
	JR	NZ,J$783A
;
I.7882:	LD	(HL),A
	DEC	DE
	SCF	
	LD	A,B
	RLCA	
	LD	D,L
	LD	A,B
J$7889:	LD	A,0B1H
	CALL	C.79A5
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.788F:	PUSH	BC
	CALL	C.78B9
;
	POP	BC
	JR	C,J.78B7
;
	LD	A,C
	AND	A
	JR	Z,J.78B5
;
	PUSH	BC
	DEC	A
	CALL	C.764C
;
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	POP	BC
	JR	NZ,J.78B5
;
	LD	A,C
	DEC	A
	CALL	C.78B9
;
	JR	C,J.78B7
;
J.78B5:	AND	A
	RET	

J.78B7:	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.78B9:	LD	B,0AH	; 10 
	LD	HL,(D.C8FD)
J$78BE:	CP	(HL)
	JR	Z,J$78C6
;
I.78C1:	INC	HL
	DJNZ	J$78BE
;
	AND	A
	RET	

J$78C6:	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$78C8:	PUSH	BC
	CALL	C.78B9
;
	POP	BC
	JR	C,J.78F4
;
	LD	A,(D.D475)
	AND	A
	JR	Z,J.78F2
;
	PUSH	BC
	DEC	A
	CALL	C.764C
;
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	POP	BC
	JR	NZ,J.78F2
;
	LD	A,(D.D475)
	DEC	A
	CALL	C.78B9
;
	JR	C,J.78F4
;
J.78F2:	AND	A
	RET	

J.78F4:	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.78F6:	PUSH	BC
	CALL	C.78B9
;
	POP	BC
	JR	C,J.78F4
;
	LD	A,(D.D4C0)
	AND	A
	JR	Z,J.7920
;
	PUSH	BC
	DEC	A
	CALL	C.764C
;
	LD	C,(IY)
	LD	B,(IY+1)
	LD	HL,I.FFFE
	XOR	A
	SBC	HL,BC
	POP	BC
	JR	NZ,J.7920
;
	LD	A,(D.D4C0)
	DEC	A
	CALL	C.78B9
;
	JR	C,J$7922
;
J.7920:	AND	A
	RET	

J$7922:	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7924:	LD	HL,I.C898
	LD	B,64H	; "d"
J$7929:	LD	A,(HL)
	CP	0FFH
	JR	NZ,J$7933
;
	INC	HL
	DJNZ	J$7929
;
	AND	A
	RET	

J$7933:	SCF	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7935:	LD	HL,(D.D473)
	LD	H,00H
	LD	DE,I.000A
	CALL	C.4D37
I$793F	EQU	$-1
;
	LD	DE,I.C898
	ADD	HL,DE
	LD	(D.C8FD),HL
	XOR	A
	LD	(D.C8FF),A
	LD	B,0AH	; 10 
J$794D:	LD	A,(HL)
	CP	0FFH
	JR	Z,J$795C
;
	INC	HL
	LD	A,(D.C8FF)
	INC	A
	LD	(D.C8FF),A
	DJNZ	J$794D
;
J$795C:	LD	HL,(D.C8FD)
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7960:	LD	A,(D.C8FF)
	CP	0AH	; 10 
	JR	NC,J$798E
	CALL	C.76FA
	CALL	C.773B
;
	JR	NZ,J$7976
;
	LD	A,(D.D475)
	DEC	A
	LD	C,A
	JR	J$797A

J$7976:	LD	A,(D.D475)
	LD	C,A
J$797A:	LD	HL,(D.C8FD)
	LD	D,00H
I$797E	EQU	$-1
	LD	A,(D.C8FF)
	LD	E,A
	INC	A
	LD	(D.C8FF),A
	ADD	HL,DE
	LD	(HL),C
	CALL	C$7A05
;
	JR	J$7994

J$798E:	LD	A,0AFH
	CALL	C.79A5
;
	RET	

J$7994:	LD	A,(D.D473)
	LD	L,A
	LD	A,(D.D4AD)
	CP	L
	RET	NZ
;
	LD	A,(D.D552)
	AND	A
	CALL	NZ,C.4EB0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.79A5:	CALL	C.4D5E
;
	LD	IX,I$79B5
	CALL	C.4D51
	LD	A,03H	; 3 
	CALL	C.4D5E
;
	RET	

I$79B5:	NOP	
	CP	(HL)
	LD	A,C
	RST	38H
	RST	38H
	PUSH	BC
	LD	A,C
	RST	38H
	RST	38H
	LD	BC,I.0000
	RST	38H
	OUT	(0C9H),A
	LD	A,C
	LD	BC,I$C9E3
	LD	A,C
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$79CA:	LD	A,(D.C8FF)
	DEC	A
	LD	(D.C8FF),A
	CALL	C.76FA
	CALL	C.773B
;
	JR	NZ,J$79DF
;
	LD	A,(D.D475)
	DEC	A
	JR	J$79E2

J$79DF:	LD	A,(D.D475)
J$79E2:	LD	HL,(D.C8FD)
	LD	B,0AH	; 10 
J$79E7:	CP	(HL)
	JR	Z,J$79EF
;
	INC	HL
	DJNZ	J$79E7
;
	JR	J$79F1

J$79EF:	LD	(HL),0FFH
J$79F1:	CALL	C$7A24
;
	LD	A,(D.D473)
	LD	L,A
	LD	A,(D.D4AD)
	CP	L
I$79FC:	RET	NZ
;
	LD	A,(D.D552)
	AND	A
	CALL	NZ,C.4EB0
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7A05:	LD	HL,(D.C8FD)
	LD	A,(D.C8FF)
	LD	C,A
J$7A0C:	LD	B,C
	PUSH	HL
	POP	DE
J$7A0F:	INC	DE
	LD	A,(DE)
	CP	(HL)
	CALL	C,C$7A1E
;
	DJNZ	J$7A0F
;
	INC	HL
	DEC	C
	LD	A,C
	OR	A
	JR	NZ,J$7A0C
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7A1E:	PUSH	AF
	LD	A,(HL)
	LD	(DE),A
	POP	AF
	LD	(HL),A
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7A24:	LD	HL,(D.C8FD)
	LD	A,(D.C8FF)
	LD	B,A
J$7A2B:	LD	A,(HL)
	CP	0FFH
	JR	Z,J.7A35
;
	INC	HL
	DJNZ	J$7A2B
;
	JR	J.7A42

J.7A35:	PUSH	HL
	POP	DE
	INC	HL
	LD	A,(HL)
	CP	0FFH
	JR	Z,J.7A42
;
	LD	(DE),A
	DJNZ	J.7A35
;
	LD	(HL),0FFH
J.7A42:	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7A43:	LD	A,00H
	CALL	C.4DFA
;
	RET	

?.7A49:	LD	A,01H	; 1 
	CALL	C.4DFA
;
	RET	

?.7A4F:	LD	A,02H	; 2 
	CALL	C.4DFA
;
	RET	

?.7A55:	LD	A,03H	; 3 
	CALL	C.4DFA
;
	RET	

?.7A5B:	LD	A,04H	; 4 
	CALL	C.4DFA
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7A61:	LD	A,05H	; 5 
	CALL	C.4DFA
;
	RET	

?.7A67:	LD	A,06H	; 6 
	CALL	C.4DFA
;
	RET	

?.7A6D:	LD	A,07H	; 7 
	CALL	C.4DFA
;
	RET	

?.7A73:	LD	A,08H	; 8 
	CALL	C.4DFA
;
	RET	

?.7A79:	LD	A,09H	; 9 
	CALL	C.4DFA
;
	RET	

?.7A7F:	LD	A,0AH	; 10 
	CALL	C.4DFA
;
	RET	

?.7A85:	LD	A,0BH	; 11 
	CALL	C.4DFA
;
	RET	

?.7A8B:	LD	A,0CH	; 12 
	CALL	C.4DFA
;
	RET	

?.7A91:	LD	A,0DH	; 13 
	CALL	C.4DFA
;
	RET	

?.7A97:	LD	A,0EH	; 14 
	CALL	C.4DFA
;
	RET	

?.7A9D:	LD	A,0FH	; 15 
	CALL	C.4DFA
;
	RET	

?.7AA3:	LD	A,10H	; 16 
	CALL	C.4DFA
;
	RET	

?.7AA9:	LD	A,11H	; 17 
	CALL	C.4DFA
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7AAF:	LD	A,12H	; 18 
	CALL	C.4DFA
;
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7AB5:	DI	
	PUSH	AF
	PUSH	DE
	LD	A,00H
	LD	E,50H	; "P"
	CALL	C.7AE1
;
	LD	A,01H	; 1 
	LD	E,01H	; 1 
	CALL	C.7AE1
;
	LD	A,08H	; 8 
	LD	E,0FH	; 15 
	CALL	C.7AE1
;
	LD	DE,I.2000
J$7AD0:	DEC	DE
	LD	A,D
	OR	E
	JP	NZ,J$7AD0
;
	LD	A,08H	; 8 
	LD	E,00H
	CALL	C.7AE1
;
	POP	DE
	POP	AF
	EI	
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7AE1:	OUT	(0A0H),A
	PUSH	AF
	LD	A,E
	OUT	(0A1H),A
	POP	AF
	RET	

J$7AE9:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	IY,D.D464
	CALL	C.7A43
;
	LD	A,44H	; "D"
	CALL	C.4D5E
	CALL	C$4F25
;
	LD	A,(D.D4C7)
	AND	A
	JP	Z,J.7C29
;
	LD	A,(D.D4D2)
	LD	(D.D4E3),A
	LD	(D.D4E5),A
	LD	A,(D.D4D4)
	LD	(D.D4E4),A
	LD	(D.D4E6),A
	CALL	C$4F99
;
J$7B1C:	BIT	7,D
	JR	Z,J$7B41
;
	LD	A,(D.D4E3)
	LD	B,A
	LD	A,(D.D4D5)
	CP	B
	JR	NZ,J$7B35
;
	LD	A,(D.D4E4)
	LD	B,A
	LD	A,(D.D4D7)
	CP	B
	JP	Z,J.7C29
;
J$7B35:	PUSH	HL
	LD	HL,I.D525
	RES	4,(HL)
	POP	HL
	CALL	C.4FA6
;
	JR	J$7B1C

J$7B41:	LD	A,(D.D4E3)
	LD	(D.D4E5),A
	LD	A,(D.D4E4)
	LD	(D.D4E6),A
	LD	(D.C286),HL
	LD	(D.C280),DE
	LD	HL,I.0000
	LD	(D.C28C),HL
	XOR	A
	LD	(D.C293),A
J$7B5E:	LD	HL,(D.C280)
	LD	DE,(D.D4E0)
	AND	A
	SBC	HL,DE
	JP	Z,J.7C09
;
J$7B6B:	LD	A,(D.C293)
	CP	0FFH
	JP	Z,J.7C09
;
	LD	A,(D.D4E3)
	LD	B,A
	LD	A,(D.D4D5)
	CP	B
	JP	NZ,J$7B89
;
	LD	A,(D.D4E4)
	LD	B,A
	LD	A,(D.D4D7)
	CP	B
	JP	Z,J$7BA4
;
J$7B89:	LD	HL,I.D525
	RES	4,(HL)
	LD	HL,(D.C286)
	CALL	C.4FA6
;
	LD	(D.C286),HL
	LD	(D.C282),DE
	LD	A,D
	CP	0FFH
	JP	NZ,J$7BB0
;
	JP	J$7B6B

J$7BA4:	LD	HL,(D.D4E0)
	LD	(D.C282),HL
	LD	(D.C284),HL
	JP	J.7BF1

J$7BB0:	LD	DE,(D.C282)
	LD	HL,(D.C286)
J$7BB7:	BIT	7,D
	JP	Z,J$7BEA
;
	LD	A,(D.D4E3)
	LD	B,A
	LD	A,(D.D4D5)
	CP	B
	JP	NZ,J$7BD2
;
	LD	A,(D.D4E4)
	LD	B,A
	LD	A,(D.D4D7)
	CP	B
	JP	Z,J$7BDF
;
J$7BD2:	PUSH	HL
	LD	HL,I.D525
	RES	4,(HL)
	POP	HL
	CALL	C.4FA6
;
	JP	J$7BB7

J$7BDF:	LD	(D.C286),HL
	LD	HL,(D.D4E0)
	LD	(D.C284),HL
	JR	J.7BF1

J$7BEA:	LD	(D.C284),DE
	LD	(D.C286),HL
J.7BF1:	CALL	C$7C32
;
	LD	HL,(D.C284)
	LD	(D.C280),HL
	LD	A,(D.D4E3)
	LD	(D.D4E5),A
	LD	A,(D.D4E4)
	LD	(D.D4E6),A
	JP	J$7B5E

J.7C09:	LD	A,(D.C293)
	CP	0FFH
	JR	NZ,J$7C13
	CALL	C$7FA2
;
J$7C13:	LD	A,(D.D4D2)
	LD	B,A
	LD	A,(D.D4D4)
	LD	C,A
	XOR	A
	CALL	C.4E3B
;
	LD	IY,D.D464
	CALL	C$4E96
	CALL	C.4EB0
;
J.7C29:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7C32:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	XOR	A
	LD	(D.C288),A
	LD	(D.C289),A
	LD	(D.C28A),A
	LD	(D.C28B),A
	LD	(D.C28E),A
	LD	(D.C28F),A
	LD	(D.C290),A
	LD	(D.C291),A
	LD	HL,(D.C282)
	SET	7,H
	LD	(D.C282),HL
	LD	HL,(D.C280)
	SET	7,H
	LD	(D.C280),HL
	LD	IX,(D.C280)
	LD	DE,(D.C28C)
	ADD	IX,DE
	LD	A,01H	; 1 
	LD	(D.C292),A
	LD	A,(D.D4E5)
	LD	B,A
	LD	A,(D.D4E6)
	LD	C,A
	CALL	C.4E62
;
	JP	C,J.7DF4
;
	LD	A,01H	; 1 
	LD	(D.D48A),A
	CALL	C.5452
;
	LD	A,(D.D4D8)
	AND	0F0H
	CP	30H	; "0"
	JR	NZ,J.7C95
;
	INC	IX
	INC	IX
J.7C95:	CALL	C.5452
;
	LD	DE,(D.D4D9)
	ADD	IX,DE
	LD	A,(D.D4DB)
	LD	B,A
	LD	A,(D.C28E)
	ADD	A,B
	LD	(D.C28E),A
	LD	A,(D.D4D8)
	AND	0F0H
	JP	NZ,J.7CDD
;
	PUSH	IX
	POP	HL
	AND	A
	SBC	HL,DE
	LD	A,(HL)
	CP	20H	; " "
	JP	NZ,J.7CDD
;
	LD	HL,(D.D4D9)
	LD	DE,I.0001
	AND	A
	SBC	HL,DE
	JP	NZ,J.7CDD
;
	LD	DE,(D.C282)
	LD	HL,(D.C28C)
	ADD	HL,DE
	PUSH	IX
	POP	DE
	AND	A
	SBC	HL,DE
	JP	Z,J.7DF4
;
	JP	J.7C95

J.7CDD:	LD	DE,(D.D4D9)
	PUSH	IX
	POP	HL
	AND	A
	SBC	HL,DE
	PUSH	HL
	POP	IX
	LD	A,(D.D4DB)
	LD	B,A
	LD	A,(D.C28E)
	SUB	B
	LD	(D.C28E),A
J$7CF5:	CALL	C.5452
;
	LD	A,(D.D4D8)
	AND	0F0H
	JP	NZ,J.7DF4
;
	LD	HL,(D.D4DB)
	LD	A,(D.D482)
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(D.D483)
	LD	E,A
	LD	D,00H
	AND	A
	SBC	HL,DE
	JP	NC,J.7DF4
;
	LD	A,(IX)
	CP	20H	; " "
	JP	NZ,J.7D4D
;
	LD	DE,(D.D4D9)
	LD	HL,I.0001
	AND	A
	SBC	HL,DE
	JP	Z,J$7D37
;
	LD	HL,C.0003
	AND	A
	SBC	HL,DE
	JP	Z,J.7D4D
;
	JP	J.7DF4

J$7D37:	LD	A,(D.C28F)
	INC	A
	LD	(D.C28F),A
	LD	A,(D.C291)
	INC	A
	LD	(D.C291),A
	LD	A,01H	; 1 
	LD	(D.C292),A
	JP	J$7D89

J.7D4D:	LD	A,(D.C292)
	CP	01H	; 1 
	JP	NZ,J$7D7A
;
	LD	A,(D.C28E)
	LD	B,A
	LD	A,(D.C28F)
	ADD	A,B
	LD	(D.C28E),A
	XOR	A
	LD	(D.C28F),A
	LD	A,(D.C28B)
	INC	A
	LD	(D.C28B),A
	LD	A,(D.C290)
	LD	B,A
	LD	A,(D.C291)
	ADD	A,B
	LD	(D.C290),A
	XOR	A
	LD	(D.C291),A
J$7D7A:	LD	A,(D.D4DB)
	LD	B,A
	LD	A,(D.C28E)
	ADD	A,B
	LD	(D.C28E),A
	XOR	A
	LD	(D.C292),A
J$7D89:	LD	BC,(D.D4D9)
	ADD	IX,BC
	LD	DE,(D.C282)
	LD	HL,(D.C28C)
	ADD	HL,DE
	PUSH	IX
	POP	DE
	AND	A
	SBC	HL,DE
	JP	NZ,J$7CF5
;
	LD	A,(D.C28B)
	CP	02H	; 2 
	JP	C,J.7DF4
;
	LD	A,(D.C28E)
	LD	C,A
	LD	A,(D.D482)
	LD	B,A
	LD	A,(D.D483)
	INC	A
	SUB	B
	SUB	C
	LD	(D.C288),A
	LD	C,A
	LD	A,(D.C28B)
	DEC	A
	LD	B,A
	LD	D,00H
	LD	A,(D.C290)
	ADD	A,C
	DEC	A
J$7DC6:	SUB	B
	INC	D
	JR	C,J$7DCE
;
	JR	Z,J$7DD3
;
	JR	J$7DC6

J$7DCE:	ADD	A,B
	LD	(D.C28A),A
	DEC	D
J$7DD3:	LD	A,D
	LD	(D.C289),A
	LD	A,(D.C288)
	LD	B,A
	LD	A,(D.C291)
	CP	B
	JP	Z,J$7DE8
	CALL	C$7E01
;
	JP	C,J$7DED
;
J$7DE8:	CALL	C$7E6B
;
	JR	J.7DF4

J$7DED:	LD	A,0FFH
	LD	(D.C293),A
	JR	J.7DF4

J.7DF4:	XOR	A
	LD	(D.D4C7),A
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7E01:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,(D.D4A6)
	LD	A,(D.C288)
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	AND	A
	LD	A,(D.C291)
	LD	E,A
	LD	D,00H
	SBC	HL,DE
	PUSH	HL
	LD	DE,(D$D4B8)
	AND	A
	SBC	HL,DE
	JR	C,J.7E2C
;
	JR	Z,J.7E2C
;
	POP	HL
	SCF	
	JP	J$7E63

J.7E2C:	LD	HL,(D.D4A6)
	LD	DE,(D.C282)
	PUSH	HL
	AND	A
	SBC	HL,DE
	LD	DE,(D.C28C)
	AND	A
	SBC	HL,DE
	INC	HL
	INC	HL
	PUSH	HL
	POP	BC
	LD	A,(D.C288)
	LD	E,A
	LD	D,00H
	POP	HL
	PUSH	HL
	ADD	HL,DE
	INC	HL
	AND	A
	LD	A,(D.C291)
	LD	E,A
	LD	D,00H
	SBC	HL,DE
	PUSH	HL
	POP	DE
	POP	HL
	INC	HL
	POP	IY
	LD	(D.D4A6),IY
	LDDR	
	SCF	
	CCF	
J$7E63:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7E6B:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,(D.C280)
	LD	DE,(D.C28C)
	ADD	HL,DE
	PUSH	HL
	POP	IY
	LD	IX,I$C294
	LD	HL,(D.C282)
	LD	DE,(D.C280)
	AND	A
	SBC	HL,DE
	PUSH	HL
	POP	BC
	PUSH	IY
	POP	HL
	PUSH	IX
	POP	DE
	LDIR	
	LD	A,20H	; " "
	LD	(DE),A
	XOR	A
	INC	DE
	LD	(DE),A
	LD	HL,(D.C28C)
	LD	A,(D.C288)
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	AND	A
	LD	A,(D.C291)
	LD	E,A
	LD	D,00H
	SBC	HL,DE
	LD	(D.C28C),HL
	CALL	C.5452
;
	LD	A,(D.D4D8)
	AND	0F0H
	CP	30H	; "0"
	JR	NZ,J.7EC6
;
	INC	IX
	INC	IX
	INC	IY
	INC	IY
J.7EC6:	CALL	C.5452
;
	LD	DE,(D.D4D9)
	ADD	IX,DE
	ADD	IY,DE
	PUSH	IX
	POP	HL
	AND	A
	SBC	HL,DE
	LD	A,(HL)
	CP	20H	; " "
	JP	NZ,J.7EE9
;
	LD	HL,I.0001
	AND	A
	SBC	HL,DE
	JP	NZ,J.7EE9
;
	JP	J.7EC6

J.7EE9:	PUSH	IY
	POP	HL
	AND	A
	SBC	HL,DE
	PUSH	HL
	POP	IY
	PUSH	IX
	POP	HL
	AND	A
	SBC	HL,DE
	PUSH	HL
	POP	IX
J$7EFB:	LD	A,(IX)
	CP	20H	; " "
	JP	NZ,J$7F69
;
	LD	HL,(D.D4D9)
	LD	DE,I.0001
	AND	A
	SBC	HL,DE
	JP	NZ,J$7F5D
;
	LD	A,(D.C28A)
	AND	A
	JP	Z,J$7F2B
;
	DEC	A
	LD	(D.C28A),A
	LD	A,(D.C289)
	INC	A
J.7F1E:	LD	(IY),20H	; " "
	INC	IY
	DEC	A
	AND	A
	JR	NZ,J.7F1E
;
	JP	J.7F30

J$7F2B:	LD	A,(D.C289)
	JR	J.7F1E

J.7F30:	CALL	C.5452
;
	LD	DE,(D.D4D9)
	ADD	IX,DE
	PUSH	IX
	POP	HL
	AND	A
	SBC	HL,DE
	LD	A,(HL)
	CP	20H	; " "
	JP	NZ,J.7F51
;
	LD	HL,I.0001
	AND	A
	SBC	HL,DE
	JP	NZ,J.7F51
;
	JP	J.7F30

J.7F51:	PUSH	IX
	POP	HL
	AND	A
	SBC	HL,DE
	PUSH	HL
	POP	IX
	JP	J$7F7D

J$7F5D:	LD	HL,(D.D4D9)
	LD	DE,C.0003
	AND	A
	SBC	HL,DE
	JP	NZ,J.7F99
;
J$7F69:	PUSH	IX
	POP	HL
	PUSH	IY
	POP	DE
	LD	BC,(D.D4D9)
	LDIR	
	LD	DE,(D.D4D9)
	ADD	IX,DE
	ADD	IY,DE
J$7F7D:	CALL	C.5452
;
	LD	HL,(D.C282)
	LD	DE,(D.C28C)
	ADD	HL,DE
	DEC	HL
	PUSH	IY
	POP	DE
	AND	A
	SBC	HL,DE
	JP	NZ,J$7EFB
;
	LD	(IY),20H	; " "
	JP	J.7F99

J.7F99:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7FA2:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C$7AB5
;
	LD	A,4FH	; "O"
	CALL	C.4D5E
;
	LD	IX,I$7FC7
	CALL	C.4D51
	LD	BC,I$7FBE
	PUSH	BC
	JP	(HL)

I$7FBE:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

I$7FC7:	NOP	
	RET	NC
;
	LD	A,A
	RST	38H
	RST	38H
	RST	10H
;
	LD	A,A
	RST	38H
	RST	38H
	LD	BC,I.0000
	RST	38H
	RST	38H
	IN	A,(7FH)
	LD	BC,I$DBE3
	LD	A,A
	LD	A,95H
	CALL	C.4D5E
;
	RET	

?.7FE1:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
D$7FF0:	RST	38H
	RST	38H
	RST	38H
	RST	38H
D$7FF4:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
D.7FF9:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	END
