;  
;   FS-SR021, segment 2 -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA
;
	.Z80
	ORG	0000H
;
C$4027	EQU	4027H	; -C---
C$4028	EQU	4028H	; -C---
C$402B	EQU	402BH	; -C---
C$4042	EQU	4042H	; -C---
I$40FF	EQU	40FFH	; ----I
I$5000	EQU	5000H	; ----I
I$5050	EQU	5050H	; ----I
D.6400	EQU	6400H	; --S--
D.6800	EQU	6800H	; --S--
D.6C00	EQU	6C00H	; --S--
D.7000	EQU	7000H	; --S--
D.7800	EQU	7800H	; --S--
C$7CFC	EQU	7CFCH	; -C---
D$7FF0	EQU	7FF0H	; ---L-
D$7FF2	EQU	7FF2H	; ---L-
D.7FF4	EQU	7FF4H	; ---L-
D.7FF9	EQU	7FF9H	; --S--
C.8000	EQU	8000H	; -C---
I$8001	EQU	8001H	; ----I
C$8003	EQU	8003H	; -C---
C$8009	EQU	8009H	; -C---
C$801E	EQU	801EH	; -C---
C$8021	EQU	8021H	; -C---
C$8024	EQU	8024H	; -C---
C$8027	EQU	8027H	; -C---
C$802A	EQU	802AH	; -C---
C$8042	EQU	8042H	; -C---
I$8080	EQU	8080H	; ----I
I$849F	EQU	849FH	; ----I
C$A1CF	EQU	0A1CFH	; -C---
C$A1D5	EQU	0A1D5H	; -C---
J$A3B9	EQU	0A3B9H	; J----
I$A800	EQU	0A800H	; ----I
C$A9A7	EQU	0A9A7H	; -C---
I$AA00	EQU	0AA00H	; ----I
J$ACAD	EQU	0ACADH	; J----
I$B300	EQU	0B300H	; ----I
C$B3B1	EQU	0B3B1H	; -C---
C.B6CE	EQU	0B6CEH	; -C---
J.B8B7	EQU	0B8B7H	; J----
I$BA00	EQU	0BA00H	; ----I
I$BC00	EQU	0BC00H	; ----I
C$BDAF	EQU	0BDAFH	; -C---
C$BDC2	EQU	0BDC2H	; -C---
J$C1DB	EQU	0C1DBH	; J----
C.C5B6	EQU	0C5B6H	; -C---
I.C5F5	EQU	0C5F5H	; ----I
J$C7A6	EQU	0C7A6H	; J----
J$C9C0	EQU	0C9C0H	; J----
I$CB50	EQU	0CB50H	; ----I
I.CB51	EQU	0CB51H	; ----I
I$CB5C	EQU	0CB5CH	; ----I
D.CB5D	EQU	0CB5DH	; ---LI
D.CB63	EQU	0CB63H	; ---L-
D$CB67	EQU	0CB67H	; ---L-
D.CB68	EQU	0CB68H	; --SL-
I.CB69	EQU	0CB69H	; ----I
D$CB74	EQU	0CB74H	; --S--
D.CB75	EQU	0CB75H	; --S-I
D.CB76	EQU	0CB76H	; --SL-
D.CB78	EQU	0CB78H	; --SL-
D.CB7A	EQU	0CB7AH	; --SLI
I.CB7B	EQU	0CB7BH	; ----I
I.CBAD	EQU	0CBADH	; ----I
D.CBAF	EQU	0CBAFH	; --SLI
I$CBB0	EQU	0CBB0H	; ----I
D.CBB2	EQU	0CBB2H	; --SL-
D.CBB3	EQU	0CBB3H	; ---L-
D.CBB8	EQU	0CBB8H	; --SL-
D.CBB9	EQU	0CBB9H	; ---L-
D.CBBA	EQU	0CBBAH	; --SL-
D.CBBB	EQU	0CBBBH	; --SL-
I$CBBC	EQU	0CBBCH	; ----I
D.CF1A	EQU	0CF1AH	; --SLI
D.CF1C	EQU	0CF1CH	; --SL-
D.CF1E	EQU	0CF1EH	; --SL-
D.CF20	EQU	0CF20H	; --SL-
D.CF22	EQU	0CF22H	; --SL-
D$CF23	EQU	0CF23H	; --S--
D.CF24	EQU	0CF24H	; --SL-
D.CF26	EQU	0CF26H	; --SL-
I.CF29	EQU	0CF29H	; ----I
I.CF2D	EQU	0CF2DH	; ----I
I.CF31	EQU	0CF31H	; ----I
I.CF39	EQU	0CF39H	; ----I
I.CF49	EQU	0CF49H	; ----I
I$CF55	EQU	0CF55H	; ----I
I.CF61	EQU	0CF61H	; ----I
I$CF69	EQU	0CF69H	; ----I
I$CF6D	EQU	0CF6DH	; ----I
I.CF79	EQU	0CF79H	; ----I
I$CF7A	EQU	0CF7AH	; ----I
I.CFA9	EQU	0CFA9H	; ----I
I$CFAD	EQU	0CFADH	; ----I
I.CFB1	EQU	0CFB1H	; ----I
I.D029	EQU	0D029H	; ----I
I$D031	EQU	0D031H	; ----I
I$D039	EQU	0D039H	; ----I
I.D129	EQU	0D129H	; ----I
I.D12A	EQU	0D12AH	; ----I
I$D131	EQU	0D131H	; ----I
I.D139	EQU	0D139H	; ----I
D.D149	EQU	0D149H	; --SLI
D$D14B	EQU	0D14BH	; --S--
I.D16C	EQU	0D16CH	; ----I
D.D171	EQU	0D171H	; --SLI
D.D172	EQU	0D172H	; --SL-
D.D174	EQU	0D174H	; --SL-
D.D175	EQU	0D175H	; --SL-
D.D176	EQU	0D176H	; --SL-
D.D178	EQU	0D178H	; --SL-
D.D17A	EQU	0D17AH	; --SL-
D.D17B	EQU	0D17BH	; --SL-
D.D17C	EQU	0D17CH	; --SLI
D$D17D	EQU	0D17DH	; ---L-
D$D17E	EQU	0D17EH	; --S--
D$D17F	EQU	0D17FH	; --S--
D.D185	EQU	0D185H	; --SL-
D.D186	EQU	0D186H	; --S--
D.D187	EQU	0D187H	; --SL-
D.D188	EQU	0D188H	; --SL-
D.D189	EQU	0D189H	; --SL-
D.D18A	EQU	0D18AH	; --SL-
D.D18C	EQU	0D18CH	; --SL-
D.D18E	EQU	0D18EH	; ---L-
D.D18F	EQU	0D18FH	; --SL-
D.D190	EQU	0D190H	; --SL-
D.D191	EQU	0D191H	; --SL-
D.D196	EQU	0D196H	; --SL-
D.D197	EQU	0D197H	; --SL-
D.D198	EQU	0D198H	; --SL-
D.D199	EQU	0D199H	; --SL-
D.D19A	EQU	0D19AH	; --SL-
D.D19B	EQU	0D19BH	; --SL-
D.D19C	EQU	0D19CH	; --SLI
D.D19D	EQU	0D19DH	; --SL-
D.D19E	EQU	0D19EH	; --SL-
D.D19F	EQU	0D19FH	; --SL-
D.D1A0	EQU	0D1A0H	; --SL-
I$D1A1	EQU	0D1A1H	; ----I
I$D1B1	EQU	0D1B1H	; ----I
D.D1B2	EQU	0D1B2H	; --SL-
D.D1B4	EQU	0D1B4H	; --SL-
D$D1B6	EQU	0D1B6H	; --S--
D.D1B7	EQU	0D1B7H	; --SL-
J$D1B9	EQU	0D1B9H	; J----
I.D1BD	EQU	0D1BDH	; ----I
C.D1D0	EQU	0D1D0H	; -C---
J$D3A2	EQU	0D3A2H	; J----
J$D3DB	EQU	0D3DBH	; J----
D.D457	EQU	0D457H	; --SL-
D.D458	EQU	0D458H	; --SL-
D.D459	EQU	0D459H	; --SL-
D.D45A	EQU	0D45AH	; --SL-
I$D45C	EQU	0D45CH	; ----I
D$D466	EQU	0D466H	; ---L-
D.D468	EQU	0D468H	; ---L-
I$D469	EQU	0D469H	; ----I
D.D46D	EQU	0D46DH	; ---L-
D$D46E	EQU	0D46EH	; ---L-
D.D47B	EQU	0D47BH	; --SL-
D.D47C	EQU	0D47CH	; ---LI
D.D47D	EQU	0D47DH	; --SLI
D.D47E	EQU	0D47EH	; --SL-
I.D47F	EQU	0D47FH	; ----I
D.D480	EQU	0D480H	; --SLI
D.D48A	EQU	0D48AH	; ---L-
D$D48B	EQU	0D48BH	; --S--
D.D498	EQU	0D498H	; --SL-
D$D49B	EQU	0D49BH	; ---L-
D.D49D	EQU	0D49DH	; ---L-
D.D49E	EQU	0D49EH	; ---L-
D.D49F	EQU	0D49FH	; ---L-
D.D4A0	EQU	0D4A0H	; ---L-
J$D4D5	EQU	0D4D5H	; J----
C$D6D5	EQU	0D6D5H	; -C---
D$DB32	EQU	0DB32H	; --S--
J$DCC0	EQU	0DCC0H	; J----
J$E402	EQU	0E402H	; J----
J$E4E3	EQU	0E4E3H	; J----
D$F1F1	EQU	0F1F1H	; --S--
I.F7EF	EQU	0F7EFH	; ----I
I$F800	EQU	0F800H	; ----I
C.F8FC	EQU	0F8FCH	; -C---
I$FA00	EQU	0FA00H	; ----I
I$FA02	EQU	0FA02H	; ----I
C$FCFC	EQU	0FCFCH	; -C---
I$FD40	EQU	0FD40H	; ----I
D$FE72	EQU	0FE72H	; --S--
C.FEFC	EQU	0FEFCH	; -C---
C$FF00	EQU	0FF00H	; -C---
D$FF03	EQU	0FF03H	; ---L-
C$FFC0	EQU	0FFC0H	; -C---
C$FFFE	EQU	0FFFEH	; -C---
D.FFFF	EQU	0FFFFH	; --SL-
;
	JP	J$3E76
I.0001	EQU	$-2
I.0002	EQU	$-1
;
;	-----------------
?.0003:	JP	J$3E4D
I.0004	EQU	$-2
;
;	-----------------
CPMADR:	JP	C.09EF
C.0008	EQU	$-1
;
;	-----------------
J$0009:	JP	J$153F
I$000A	EQU	$-2
;
;	-----------------
I.000C:	JP	J$1604
;
;	-----------------
?.000F:	JP	J$1998
C.0010	EQU	$-2
I.0011	EQU	$-1
;
;	-----------------
I.0012:	JP	J$00DD
I$0013	EQU	$-2
;
;	-----------------
?.0015:	JP	J$0D64
;
;	-----------------
I.0018:	JP	J$1128
;
;	-----------------
?.001B:	JP	C.172A
;
;	-----------------
?.001E:	JP	J$194F
I$001F	EQU	$-2
I.0020	EQU	$-1
;
;	-----------------
?.0021:	JP	J$05F7
;
;	-----------------
?.0024:	JP	J$22DF
;
;	-----------------
?.0027:	JP	C.2FC8
;
;	-----------------
?.002A:	RST	38H
	RST	38H
	RST	38H
	JP	J$247E
;
;	-----------------
?.0030:	JP	J$316A
;
;	-----------------
?.0033:	JP	J$1BFC
;
;	-----------------
?.0036:	RST	38H
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0038:	JP	J$0150
;
;	-----------------
?.003B:	JP	C.1833
;
;	-----------------
?.003E:	JP	J$253D
;
;	-----------------
?.0041:	JP	J$0D5C
;
;	-----------------
?.0044:	JP	C.18D6
;
;	-----------------
?.0047:	JP	C.1C14
I$0048	EQU	$-2
;
;	-----------------
?.004A:	JP	J$1A7B
;
;	-----------------
?.004D:	JP	C.1917
;
;	-----------------
?.0050:	JP	J$0646
;
;	-----------------
?.0053:	JP	C.2EDA
;
;	-----------------
?.0056:	JP	C.16EB
;
;	-----------------
?.0059:	JP	C.275F
;
;	-----------------
FCB1:	JP	J$28F4
;
;	-----------------
?.005F:	JP	J$17F5
;
;	-----------------
?.0062:	JP	J$1BCA
;
;	-----------------
?.0065:	JP	J$1B4A
;
;	-----------------
?.0068:	JP	J$3E9F
;
;	-----------------
?.006B:	JP	J$1B88
;
;	-----------------
FCB2.1:	JP	J$1BB1
;
;	-----------------
?.0071:	JP	J$1BE4
;
;	-----------------
?.0074:	JP	J$0C6F
;
;	-----------------
?.0077:	JP	J$0C96
;
;	-----------------
?.007A:	JP	J$25E2
;
;	-----------------
?.007D:	JP	J$3218
;
;	-----------------
DBUF:	JP	J$1B1C
;
;	-----------------
?.0083:	JP	C.167B
;
;	-----------------
?.0086:	JP	J$1866
;
;	-----------------
?.0089:	JP	J$17A7
;
;	-----------------
?.008C:	JP	J$3297
;
;	-----------------
?.008F:	JP	C.258B
;
;	-----------------
?.0092:	JP	C.2659
;
;	-----------------
?.0095:	JP	C.14A5
;
;	-----------------
?.0098:	JP	J$31F6
;
;	-----------------
?.009B:	JP	J$14D2
;
;	-----------------
?.009E:	RST	38H
	RST	38H
	PUSH	HL
	PUSH	BC
	PUSH	AF
	LD	IX,D.D17C
	LD	(IX+5),00H
	LD	(IX+7),00H
I$00AE	EQU	$-1
	LD	B,(HL)
	INC	HL
J$00B1:	LD	A,B
	OR	A
	JR	Z,J$00D9
;
	LD	A,(HL)
	LD	(IX),A
	INC	HL
	LD	A,(HL)
	LD	(IX+1),A
	INC	HL
I$00BF:	LD	A,(HL)
	LD	(IX+2),A
	INC	HL
I$00C4:	LD	A,(HL)
	LD	(IX+3),A
	INC	HL
	LD	A,(HL)
	LD	(IX+4),A
	INC	HL
	LD	A,(HL)
	LD	(IX+6),A
	CALL	C.1C14
;
	INC	HL
	DEC	B
	JR	J$00B1
;
;	-----------------
J$00D9:	POP	AF
	POP	BC
	POP	HL
	RET	
;
;	-----------------
J$00DD:	PUSH	BC
	LD	C,00H
J$00E0:	CP	00H
	JR	Z,J.00EB
;
	SUB	03H	; 3 
	JR	C,J.00EB
;
	INC	C
	JR	J$00E0
;
;	-----------------
J.00EB:	LD	A,C
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.00EE:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	IX
	LD	IX,C.0000
	ADD	IX,SP
	LD	A,(IX+9)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.00FC:	LD	(D.7000),A
	INC	A
I.0100:	LD	(D.7800),A		; select segments page 2
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(IX+5)
	LD	(IX+7),A
	LD	A,(IX+4)
	LD	(IX+6),A
	POP	IX
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0122:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	IX
	LD	IX,C.0000
	ADD	IX,SP
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D.7FF4)
	LD	B,A
	LD	A,(IX+9)
	LD	(IX+7),A
	LD	A,(IX+8)
	LD	(IX+6),A
	LD	A,B
	LD	(IX+9),A
	POP	IX
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
?.014D:	RST	38H
	RST	38H
	RST	38H
J$0150:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	EXX	
	EX	AF,AF'
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	PUSH	IX
	PUSH	IY
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	XOR	A
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	DEFB	0,0,0,0,0
	LD	A,(D.D49F)
	INC	A
	LD	C,A
	IN	A,(C)
	SLA	A
	JR	NC,J.01AA
;
	LD	A,(D.CBB8)
	AND	A
	JR	Z,J$0185
;
	CALL	C$0691
;
	JR	J$01AD
;
;	-----------------
J$0185:	CALL	C$01D0
	JR	NZ,J.01AA
	LD	HL,D.CB75
	DEC	(HL)
	JR	NZ,J.01AA
	LD	(HL),3
	LD	HL,I$CBBC
	LD	(HL),0FFH
	LD	HL,I.CB51
	LD	D,H
	LD	E,L
	INC	DE
	LD	BC,11-1
J$01A0:	LD	(HL),0FFH
	LDI	
	JP	PE,J$01A0
	CALL	C.0244
J.01AA:	CALL	C.09EF
J$01AD:	LD	A,(D$D49B)
	AND	A
	JR	Z,J$01BF
	LD	A,0FFH			; leave interrupts disabled
	LD	(D.D498),A
	CALL	C$0D36
	XOR	A			; enable interrupts
	LD	(D.D498),A
J$01BF:	POP	IY
	POP	IX
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EX	AF,AF'
	EXX	
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RETI	
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$01D0:	IN	A,(0AAH)
	AND	0F0H
	LD	C,A
	LD	B,12
	LD	HL,D.CB5D
J$01DA:	LD	A,C
	OUT	(0AAH),A
	IN	A,(0A9H)
	LD	(HL),A
I.01E0:	INC	C
	INC	HL
	DJNZ	J$01DA
	DEFB	0,0
	LD	HL,I.CB69
	IN	A,(0AAH)
	AND	0F0H
I$01EC	EQU	$-1
	LD	C,A
	LD	B,0CH	; 12 
J.01F0:	LD	A,C
	OUT	(0AAH),A
	IN	A,(0A9H)
	LD	(HL),A
	INC	C
	INC	HL
	DJNZ	J.01F0
	LD	HL,D.CB5D
	LD	DE,I.CB69
I.0200:	LD	B,0CH	; 12 
J$0202:	LD	A,(HL)
	PUSH	AF
	LD	A,(DE)
	LD	C,A
	POP	AF
	CP	C
	RET	NZ
	INC	HL
	INC	DE
	DJNZ	J$0202
	LD	A,(D.CB68)
	LD	B,A
	LD	A,(D$CB67)
	CP	B
	JR	Z,J.0225
	LD	A,(D.CB5D)
	CP	B
	JR	Z,J.0225
	BIT	1,B
	JR	Z,J.022D
	BIT	3,B
	JR	Z,J.022D
J.0225:	LD	A,0FFH
	LD	(D.CB68),A
	LD	(D$CB74),A
J.022D:	LD	DE,I$CB5C
	LD	HL,I$CB50
	LD	B,0CH	; 12 
J$0235:	INC	DE
	INC	HL
	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$023F
	DJNZ	J$0235
	JR	C.0244

J$023F:	LD	A,37
	LD	(D.CB75),A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0244:	LD	B,12
	LD	HL,I.CB51
	LD	DE,D.CB5D
J$024C:	LD	A,(DE)
	LD	C,A
	XOR	(HL)
	AND	(HL)
	LD	(HL),C
	CALL	NZ,C$0260
	INC	DE
	INC	HL
	DJNZ	J$024C
	LD	HL,(D.CB78)
	LD	A,(D.CB76)
	SUB	L			; buffer empty ?
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0260:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	A,0CH	; 12 
	SUB	B
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	C,A
	LD	B,08H	; 8 
	POP	AF
J$026E:	RRA	
	PUSH	BC
	PUSH	AF
	CALL	C,C$027D
;
	POP	AF
	POP	BC
	INC	C
	DJNZ	J$026E
;
	POP	BC
	POP	DE
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$027D:	LD	A,C
	CP	0FFH
	RET	Z
;
	LD	HL,I$043F
	CP	30H	; "0"
	JR	NC,J.029E
;
	LD	A,(D.CB63)
	RRCA	
	RRCA	
	JR	NC,J.029D
;
	LD	A,(D.CBB2)
	CP	0FFH
	JR	Z,J.029D
;
	LD	A,(D.CBB3)
	AND	A
	JP	Z,J$03E7
;
J.029D:	LD	A,C
J.029E:	CP	(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	DE
	RET	C
;
	POP	DE
	JR	J.029E
;
;	-----------------
?.02A9:	ADD	A,30H	; "0"
	LD	B,A
	LD	A,(D.CB63)
	RRCA	
	LD	A,B
	JR	C,J$02BE
;
	LD	B,00H
	LD	HL,I$0457
	ADD	HL,BC
	LD	B,(HL)
	LD	A,B
	CP	0FFH
	RET	Z
;
J$02BE:	LD	A,(D.CB63)
	RRCA	
	RRCA	
	LD	A,B
	JR	C,J.02C9
;
	LD	A,C
	ADD	A,0E0H
J.02C9:	JP	C.03D7			; put in buffer
;
;	-----------------
?.02CC:	LD	A,(D.CB63)
	AND	03H	; 3 
	ADD	A,A
	LD	E,A
	LD	D,00H
	LD	HL,I$0461
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	INC	HL
	LD	L,A
	LD	A,C
	SUB	15H
	JP	(HL)
;
;	-----------------
?.02E2:	ADD	A,20H	; " "
	LD	B,A
	LD	A,(D.CBAF)
	CPL	
	AND	20H	; " "
	XOR	B
	ADD	A,40H	; "@"
	JR	J.02C9
;
;	-----------------
?.02F0:	LD	HL,I$0469
	DEC	A
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(HL)
	JR	J.02C9
;
;	-----------------
?.02FB:	LD	HL,I$0483
	LD	A,(D.CB63)
I$0300	EQU	$-1
I$0301:	AND	03H	; 3 
I.0302	EQU	$-1
	ADD	A,A
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	E,C
	ADD	HL,DE
	LD	A,(HL)
	CP	0FFH
	JP	NZ,C.03D7		; put in buffer
	RET	
;
;	-----------------
D$0315:	LD	A,C
	SUB	35H	; "5"
	LD	C,A
	LD	A,(D.CB63)
	RRCA	
	JR	C,J$0323
;
	LD	A,C
	ADD	A,05H	; 5 
	LD	C,A
J$0323:	LD	A,0F0H
	ADD	A,C
	CALL	C.03D7			; put in buffer
I$0327	EQU	$-2
;
	RET	
;
;	-----------------
?.032A:	LD	E,A
	CP	41H	; "A"
	JR	NZ,J$033D
;
	LD	A,(D.CB63)
	RRCA	
	JR	NC,J.0370
;
	RRCA	
	JR	C,J.0367
;
	LD	A,19H
	JP	C.03D7			; put in buffer
;
;	-----------------
J$033D:	CP	42H	; "B"
	JR	NZ,J$034F
;
	LD	A,(D.CB63)
	RRCA	
	JR	NC,J.0370
;
	RRCA	
	JR	C,J.0367
;
	LD	A,1AH
	JP	C.03D7			; put in buffer
;
;	-----------------
J$034F:	CP	44H	; "D"
	JR	C,J.0367
;
	CP	58H	; "X"
	JR	NC,J.0367
;
	LD	A,(D.CB63)
	RRCA	
	RRCA	
	JR	C,J$0363
;
	LD	HL,I$04D7
	JR	J.0373
;
;	-----------------
J$0363:	RLCA	
	RLCA	
	JR	NC,J.0370
;
J.0367:	LD	A,(D.CB63)
	RRCA	
	LD	HL,I$048B
	JR	C,J.0373
;
J.0370:	LD	HL,I$04BB
J.0373:	LD	D,00H
	ADD	HL,DE
	LD	A,(HL)
	AND	A
	RET	Z
;
	JR	C.03D7			; put in buffer
;
;	-----------------
?.037B:	LD	A,(D.CBBB)
	AND	A
	JR	NZ,J.03A6
;
	LD	HL,D.CB7A
	LD	A,(HL)
	CPL	
	LD	(HL),A
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	LD	B,A
	LD	A,(HL)
	CPL	
	AND	80H
	OR	B
	OUT	(0A1H),A
	AND	80H
	JR	NZ,J.03A6
;
	XOR	A
	LD	(D.CBAF),A
	LD	(D.CBB2),A
	LD	A,0DH	; 13 
	OUT	(0ABH),A
J.03A6:	RET	
;
;	-----------------
?.03A7:	LD	A,(D.CBBA)
	AND	A
	JR	NZ,J.03D6
;
	LD	HL,D.CBAF
	LD	A,(HL)
	CPL	
	LD	(HL),A
	CPL	
	PUSH	AF
	AND	A
	LD	A,0CH	; 12 
	JR	Z,J$03BB
;
	INC	A
J$03BB:	OUT	(0ABH),A
	POP	AF
	AND	A
	JR	NZ,J.03D6
;
	XOR	A
	LD	(D.CB7A),A
	LD	A,0FFH
	LD	(D.CBB2),A
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	OR	80H
	OUT	(0A1H),A
J.03D6:	RET	


;	  Subroutine put in buffer
;	     Inputs  ________________________
;	     Outputs ________________________

C.03D7:	LD	HL,(D.CB76)
	LD	(HL),A
	CALL	C.0434
	LD	A,(D.CB78)
	CP	L
	RET	Z
	LD	(D.CB76),HL
	RET	
;
;	-----------------
J$03E7:	LD	A,0EH	; 14 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	40H	; "@"
	JR	NZ,J$03FF
	LD	A,(D.CB63)
	RRCA	
	LD	HL,I$0537
	JR	C,J.040B
	LD	HL,I$0567
	JR	J.040B
;
;	-----------------
J$03FF:	LD	A,(D.CB63)
I$0400	EQU	$-2
	RRCA	
	LD	HL,I$0597
	JR	C,J.040B
;
	LD	HL,I$05C7
J.040B:	LD	B,00H
	ADD	HL,BC
	LD	BC,C.03D7
	PUSH	BC
	LD	A,(D.CB7A)
J$0413	EQU	$-2
	AND	A
	LD	A,(HL)
	RET	Z
;
	CP	0DEH
	RET	Z
;
	CP	0DFH
	RET	Z
;
	CP	0B0H
	RET	Z
;
	CP	0A1H
	JR	C,J$0428
;
	CP	0A6H
	RET	C
;
J$0428:	POP	BC
	LD	B,A
	LD	A,0FFH
	CALL	C.03D7			; put in buffer
	LD	A,B
	CALL	C.03D7			; put in buffer
;
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0434:	INC	HL
	LD	DE,I.CBAD
	LD	A,E
	CP	L
	RET	NZ
	LD	HL,I.CB7B
	RET	

I$043F:	LD	A,(BC)
	XOR	C
	LD	(BC),A
	LD	D,0FBH
	LD	(BC),A
	JR	NC,J$0413
;
	LD	(BC),A
	INC	SP
	LD	HL,(X.3403)
	AND	A
	INC	BC
	DEC	(HL)
	LD	A,E
	INC	BC
	LD	A,(D$0315)
	RST	38H
	LD	HL,(D$FF03)
I$0457	EQU	$-1
	LD	HL,I$2322
	INC	H
	DEC	H
	LD	H,27H	; "'"
	JR	Z,J$048A
;
I$0461:	RET	P
;
	LD	(BC),A
	RET	P
;
	LD	(BC),A
	JP	PO,J$E402
;
	LD	(BC),A
I$0469:	ADD	A,C
	ADD	A,D
	ADD	A,E
	ADD	A,H
	ADD	A,L
	ADD	A,(HL)
	ADD	A,A
	ADC	A,B
	ADC	A,C
	ADC	A,D
	ADC	A,E
	ADC	A,H
	ADC	A,L
	ADC	A,(HL)
	ADC	A,A
	SUB	B
	SUB	C
	SUB	D
	SUB	E
	SUB	H
	SUB	L
	SUB	(HL)
	SUB	A
	SBC	A,B
	SBC	A,C
	SBC	A,D
I$0483:	AND	L
	INC	B
	SBC	A,C
	INC	B
	ADC	A,L
	INC	B
	ADD	A,C
J$048A:	INC	B
I$048B:	DEC	L
	LD	E,(HL)
	LD	E,H
	LD	B,B
	LD	E,E
	DEC	SP
	LD	A,(D$2C5D)
	LD	L,2FH	; "/"
	RST	38H
	DEC	A
	LD	A,(HL)
	LD	A,H
	LD	H,B
	LD	A,E
	DEC	HL
	LD	HL,(D$3C7D)
	LD	A,3FH	; "?"
	LD	E,A
	DEC	L
	SBC	A,(HL)
	SBC	A,H
	ADD	A,B
	SBC	A,E
	DEC	SP
	LD	A,(D$2C9D)
	LD	L,2FH	; "/"
	RST	38H
	NOP	
	SBC	A,(HL)
	SBC	A,H
	ADD	A,B
	SBC	A,E
	DEC	HL
	LD	HL,(D$3C9D)
	LD	A,3FH	; "?"
	SBC	A,A
I$04BB:	LD	B,01H	; 1 
	LD	(BC),A
	DEFB	0,0,0,0,0,0,0
	DEC	DE
	ADD	HL,BC
	ADD	HL,DE
	EX	AF,AF'
	JR	J$04D8
;
;	-----------------
?.04CB:	JR	NZ,J$04E7
;
	LD	(DE),A
	LD	A,A
	DEC	E
	LD	E,1FH
	INC	E
	LD	HL,(D.2F2B)
	JR	NC,J$0509
I$04D7	EQU	$-1
;
J$04D8:	LD	(D.3433),A
	DEC	(HL)
	LD	(HL),37H	; "7"
	JR	C,J$0519
;
	DEC	L
	INC	L
	LD	L,00H
	DEC	BC
	NOP	
	RLCA	
J$04E7:	DEFB	0,0,0,0
	LD	B,00H
	DEFB	0,0,0,0,0,0,0,0
	DEC	DE
	DEFB	0,0
	EX	AF,AF'
	RLA	
	INC	C
	INC	BC
	NOP	
	INC	B
	DEC	B
	INC	D
	DEC	D
	LD	D,13H	; 19 
	LD	HL,(D.2F2B)
	JR	NC,J$0539
;
	LD	(D.3433),A
J$0509	EQU	$-2
	DEC	(HL)
	LD	(HL),37H	; "7"
	JR	C,J$0549
;
	DEC	L
	INC	L
	LD	L,00H
	DEFB	0,0,0,0,0
J$0519:	DEFB	0,0
	RRCA	
	DJNZ	J$052F
;
	LD	C,2AH	; "*"
	DEC	HL
	CPL	
	RET	PO
;
	POP	HL
	JP	PO,J$E4E3
;
	PUSH	HL
	AND	0E7H
	RET	PE
;
	JP	(HL)
;
;	-----------------
?.052C:	DEC	L
	INC	L
	LD	L,00H
J$052F	EQU	$-1
	DEFB	0,0,0,0,0,0,0
I$0537:	RET	
;
;	-----------------
?.0538:	OR	C
J$0539:	OR	D
	OR	E
	OR	H
	OR	L
	PUSH	BC
	ADD	A,0C7H
I$0540:	RET	Z
;
	RST	10H
;
	RET	C
;
	EXX	
	JP	C,J$D3DB
;
	SBC	A,0DFH
J$0549:	SUB	0DCH
	AND	(HL)
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	CP	E
	CALL	NZ,C$BDC2
;
	CP	B
	CP	(HL)
	CP	A
	RST	08H
;
	CALL	Z,C.D1D0
;
	JP	NC,J$D4D5
;
	CALL	C.B6CE
;
	CP	C
	CP	H
	CP	D
	SET	0,E
	OR	A
	POP	BC
	JP	Z,J$C9C0
I$0567	EQU	$-1
;
	AND	A
	XOR	B
	XOR	C
	XOR	D
	XOR	E
	PUSH	BC
	ADD	A,0C7H
	RET	Z
;
	RST	10H
;
	RET	C
;
	EXX	
	JP	C,J$D3A2
;
	OR	B
	AND	E
	XOR	(HL)
	AND	H
	AND	C
	AND	L
	CP	E
	CALL	NZ,C$BDAF
;
	CP	B
	CP	(HL)
	CP	A
	RST	08H
;
	CALL	Z,C.D1D0
;
	JP	NC,J$ACAD
;
	CALL	C.B6CE
;
	CP	C
	CP	H
	CP	D
	SET	0,E
	OR	A
	POP	BC
	JP	Z,J$DCC0
I$0597	EQU	$-1
;
	RST	00H
;
	CALL	Z,C$B3B1
;
	OR	H
	OR	L
	CALL	NC,C$D6D5
;
	ADC	A,0CDH
	OR	B
	SBC	A,0DFH
	JP	C,J$D1B9
;
	RET	Z
;
	EXX	
	JP	NC,J$C1DB
;
	CP	D
	CP	A
	CP	H
	OR	D
	JP	Z,J.B8B7
;
	ADD	A,0CFH
	RET	
;
;	-----------------
?.05B8:	RET	C
;
	OUT	(0D0H),A
	RST	10H
;
	CP	(HL)
	RET	NZ
;
	CP	L
	CALL	NZ,C.C5B6
;
	SET	0,E
	CP	E
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	JP	NZ,J$C7A6
I$05C7	EQU	$-2
;
	CALL	Z,C$A9A7
;
	XOR	D
	XOR	E
	XOR	H
	XOR	L
	XOR	(HL)
	ADC	A,0CDH
	OR	B
	SBC	A,0A2H
	JP	C,J$A3B9
;
	AND	H
	AND	C
	AND	L
	IN	A,(0C1H)
	CP	D
	CP	A
	CP	H
	XOR	B
	JP	Z,J.B8B7
;
	ADD	A,0CFH
	RET	
;
;	-----------------
?.05E8:	RET	C
;
	OUT	(0D0H),A
	RST	10H
;
	CP	(HL)
	RET	NZ
;
	CP	L
	CALL	NZ,C.C5B6
;
	SET	0,E
	CP	E
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	XOR	A

J$05F7:	DI	
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,(D.CB78)
	LD	DE,(D.CB76)
	LD	A,L
	CP	E			; buffer empty ?
	JR	NZ,J.0612		; nope,
	LD	A,H
	CP	D			; buffer empty ?
	JR	NZ,J.0612		; nope,
	LD	C,0
	JR	J$061C

J.0612:	LD	HL,(D.CB78)
	LD	C,(HL)
	CALL	C.0434
	LD	(D.CB78),HL		; update buffer get pointer
J$061C:	EI	
	LD	A,(D.D49E)
	AND	03H			; panasonic firmware ?
	JR	Z,J.0633		; nope,
	LD	A,C
	CP	19H
I$0627:	LD	A,07H	; 7 
	JR	Z,J$0632
	LD	A,C
	CP	1AH
	JR	NZ,J.0633
	LD	A,0BH	; 11 
J$0632:	LD	C,A
J.0633:	LD	A,(D.CBB9)
	AND	A
	JR	Z,J$063C
	CALL	C$0D1C
J$063C:	LD	A,C
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	EI	
	RET	
;
;	-----------------
J$0646:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	OUT	(0A1H),A
	LD	A,00H
	LD	(D.CBB2),A
	LD	A,0DH	; 13 
	OUT	(0ABH),A
	LD	HL,I.CB7B
	LD	(D.CB76),HL
	LD	(D.CB78),HL		; clear buffer
	LD	HL,D.CB7A
	LD	A,0FFH
	LD	(HL),A
	XOR	A
	LD	HL,D.CBAF
	LD	(HL),A
	LD	HL,I$CBB0
	LD	(HL),A
	LD	A,(D.CBB9)
	AND	A
	JR	Z,J$0688
	LD	A,0FFH
	LD	(D.CBBB),A
	LD	(D.CBBA),A
J$0688:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0691:	LD	A,(D.D457)
	AND	A
	JP	NZ,J.0718
	LD	HL,(D.CB76)
	LD	DE,(D.CB78)
	AND	A
	SBC	HL,DE			; buffer empty ?
	JR	NZ,J.0718		; nope,
	LD	A,(D.D459)
	AND	A
	JR	Z,J$06B0
	DEC	A
	LD	(D.D459),A
	JR	J.0718

J$06B0:	LD	A,(D.D458)
	AND	A
	JR	Z,J$06BC
	DEC	A
	LD	(D.D458),A
	JR	J.0718

J$06BC:	LD	A,0FFH			; leave interrupts disabled
	LD	(D.D498),A
	CALL	C.1252			; select firmware on page 1
	LD	A,81H			; segment = SRAM
	LD	(D.6400),A		; select segement page 0 (2000H-3FFFH)
	LD	HL,(D.D45A)
	LD	A,(HL)
	INC	HL
	LD	(D.D45A),HL
	LD	DE,I$0705
	PUSH	DE
	CP	57H	; "W"
	JP	Z,J$0719
	CP	4BH	; "K"
	JP	Z,J$0728
	CP	4DH	; "M"
	JP	Z,J$07FA
	CP	43H	; "C"
	JP	Z,J$081C
	CP	4CH	; "L"
	JP	Z,J$082B
	CP	53H	; "S"
	JP	Z,J$0845
	CP	4EH	; "N"
	JP	Z,J$084F
	CP	45H	; "E"
	JP	Z,J.0861
	CP	1AH
	JP	Z,J.0861
	JP	J$0873

I$0705:	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D$7FF0)		; current segment page 0 (0000H-1FFFH)
	INC	A
	LD	(D.6400),A		; select segment page 0 (2000H-3FFFH)
	CALL	C.12AC			; restore slot on page 1
	XOR	A			; enable interrupts
	LD	(D.D498),A
J.0718:	RET	

J$0719:	LD	B,(HL)
	INC	HL
	LD	C,(HL)
	INC	HL
	INC	HL
	LD	(D.D45A),HL
	CALL	C.0874
	LD	(D.D458),A
	RET	
;
;	-----------------
J$0728:	LD	B,(HL)
	INC	HL
	LD	C,(HL)
	INC	HL
	INC	HL
	LD	(D.D45A),HL
	CALL	C.0874
	LD	HL,I$0744
	PUSH	HL
	CP	19H
	JP	Z,J$074A
	CP	1AH
	JP	Z,J$0774
	JP	J$079A
;
;	-----------------
I$0744:	LD	A,10H	; 16 
	LD	(D.D459),A
	RET	
;
;	-----------------
J$074A:	LD	HL,D.CBAF
	LD	A,(HL)
	CPL	
	LD	(HL),A
	CPL	
	PUSH	AF
	AND	A
	LD	A,0CH	; 12 
	JR	Z,J$0758
;
	INC	A
J$0758:	OUT	(0ABH),A
	POP	AF
	AND	A
	JR	NZ,J$0773
;
	XOR	A
	LD	(D.CB7A),A
	LD	A,0FFH
	LD	(D.CBB2),A
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	OR	80H
	OUT	(0A1H),A
J$0773:	RET	
;
;	-----------------
J$0774:	LD	HL,D.CB7A
	LD	A,(HL)
	CPL	
	LD	(HL),A
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	LD	B,A
	LD	A,(HL)
	CPL	
	AND	80H
	OR	B
	OUT	(0A1H),A
	AND	80H
	JR	NZ,J$0799
;
	XOR	A
	LD	(D.CBAF),A
	LD	(D.CBB2),A
	LD	A,0DH	; 13 
	OUT	(0ABH),A
J$0799:	RET	
;
;	-----------------
J$079A:	LD	HL,(D.CB76)
	LD	B,A
	CP	41H	; "A"
	JR	C,J.07E6
;
	CP	0A0H
	JR	C,J.07CF
;
	CP	0E0H
	JR	NC,J.07CF
;
	LD	A,(D.CBB2)
	CP	0FFH
	JR	Z,J.07CF
;
	LD	A,(D.CBB3)
	AND	A
	JR	NZ,J.07CF
;
	LD	A,(D.CB7A)
	AND	A
	JR	Z,J.07E6
;
	LD	(HL),0FFH
	INC	HL
	LD	DE,I.CBAD
	AND	A
	PUSH	HL
	SBC	HL,DE
	POP	HL
	JR	NZ,J.07E6
;
	LD	HL,I.CB7B
	JR	J.07E6
;
;	-----------------
J.07CF:	LD	A,B
	CP	7BH	; "{"
	JR	NC,J.07E6
;
	CP	5BH	; "["
	JR	C,J$07DC
;
	CP	61H	; "a"
	JR	C,J.07E6
;
J$07DC:	LD	A,(D.CBAF)
	AND	A
	JR	NZ,J.07E6
;
	LD	A,20H	; " "
	ADD	A,B
	LD	B,A
J.07E6:	LD	A,B
	LD	(HL),A
	INC	HL
	LD	DE,I.CBAD
	AND	A
	PUSH	HL
	SBC	HL,DE
	POP	HL
	JR	NZ,J$07F6
;
	LD	HL,I.CB7B
J$07F6:	LD	(D.CB76),HL
	RET	
;
;	-----------------
J$07FA:	LD	B,(HL)
	INC	HL
	LD	C,(HL)
	INC	HL
	INC	HL
	PUSH	HL
	CALL	C.0874
;
	POP	HL
	PUSH	AF
	LD	B,(HL)
	INC	HL
	LD	C,(HL)
I$0808:	INC	HL
	INC	HL
	LD	(D.D45A),HL
	CALL	C.0874
;
	LD	B,A
	POP	AF
	LD	C,A
	CALL	C.0ABA
;
	LD	A,03H	; 3 
	LD	(D.D459),A
C$0819	EQU	$-2
	RET	
;
;	-----------------
J$081C:	INC	HL
	LD	(D.D45A),HL
	LD	A,0FFH
	LD	(D$D14B),A
	LD	A,10H	; 16 
	LD	(D.D459),A
	RET	
;
;	-----------------
J$082B:	LD	HL,I.3400
	LD	(D.D45A),HL
	LD	HL,I.CB7B
	LD	(D.CB78),HL
	LD	(D.CB76),HL		; clear buffer
	XOR	A
	LD	(D.D457),A
	LD	(D.D458),A
	LD	(D.D459),A
	RET	
;
;	-----------------
J$0845:	INC	HL
	LD	(D.D45A),HL
	LD	A,0FFH
	LD	(D$DB32),A
	RET	
;
;	-----------------
J$084F:	LD	A,0FFH
	LD	(D.D457),A
	LD	DE,I$D45C
	LD	BC,C.0008
	LDIR	
	INC	HL
	LD	(D.D45A),HL
	RET	
;
;	-----------------
J.0861:	XOR	A
	LD	(D.CBB8),A
	LD	HL,I.3400
	LD	DE,I$3401
	LD	BC,I$0BFF
	LD	(HL),00H
	LDIR	
	RET	
;
;	-----------------
J$0873:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0874:	XOR	A
	LD	HL,I$08A9
	LD	A,B
	AND	0F0H
	CP	30H	; "0"
	JR	Z,J$0886
;
	CP	40H	; "@"
	JR	NZ,J.08A8
;
	LD	HL,I$08B8
J$0886:	LD	A,B
	AND	0FH	; 15 
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	B,(HL)
	LD	HL,I$08C7
	LD	A,C
	AND	0F0H
	CP	30H	; "0"
	JR	Z,J$089F
;
	CP	40H	; "@"
	JR	NZ,J.08A8
;
	LD	HL,I$08D6
J$089F:	LD	A,C
	AND	0FH	; 15 
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(HL)
	ADD	A,B
J.08A8:	RET	
;
;	-----------------
I$08A9:	NOP	
	DJNZ	J$08CC
;
	JR	NC,J$08EE
;
	LD	D,B
	LD	H,B
	LD	(HL),B
	ADD	A,B
	SUB	B
	DEFB	0,0,0,0,0
I$08B8:	DEFB	0
	AND	B
	OR	B
	RET	NZ
;
	RET	NC
;
	RET	PO
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0
I$08C7:	DEFB	0
	LD	BC,I.0302
	INC	B
J$08CC:	DEC	B
	LD	B,07H	; 7 
	EX	AF,AF'
	ADD	HL,BC
	DEFB	0,0,0,0,0
I$08D6:	DEFB	0
	LD	A,(BC)
	DEC	BC
	INC	C
	DEC	C
	LD	C,0FH	; 15 
	DEFB	0,0,0,0,0,0,0,0

;	  Subroutine select firmware slot and segments in page 1
;	     Inputs  ________________________
;	     Outputs ________________________

C.08E5:	DI	
	PUSH	AF			; +12
	PUSH	AF			; +10, bogus
	PUSH	AF			; +8
	PUSH	BC			; +6
	PUSH	DE			; +4
	PUSH	HL			; +2
	PUSH	IX			; +0
J$08EE:	LD	IX,0
	ADD	IX,SP
	PUSH	AF			; store segment
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+15)
	LD	(IX+11),A
	LD	A,(IX+14)
	LD	(IX+10),A		; return address
	LD	(IX+15),B		; store primairy slot register
	LD	(IX+14),C		; store secundairy slot register
	POP	AF			; restore segment
	LD	C,A
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D$7FF2)		; current segment page 1 (4000H-5FFFH)
	LD	B,A
	LD	A,C
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	LD	(IX+13),B
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$0950
	EI	
J$0950:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	RET	

;	  Subroutine restore slot and segments page 1
;	     Inputs  ________________________
;	     Outputs ________________________

C.0958:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	A,(IX+11)
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	LD	B,(IX+13)
	LD	C,(IX+12)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+13),A
	LD	A,(IX+8)
	LD	(IX+12),A
	LD	A,(IX+7)
	LD	(IX+11),A
	LD	A,(IX+6)
	LD	(IX+10),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$09A9
	EI	
J$09A9:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	POP	AF
	RET	
;
;	-----------------
I$09B1:	INC	B
	DEFB	0,0
	EX	DE,HL
	CP	A
	JP	Z,J$0009
;
	RET	NZ
;
	EX	DE,HL
	OUT	(0CDH),A
	ADD	HL,BC
	CALL	PE,C$FF00
;
	CP	A
J$09C2:	RET	NC
;
	ADD	HL,BC
	CALL	PE,C$FFC0
;
	OUT	(0D3H),A
	ADD	HL,BC
	DEFB	0,0
	LD	E,00H
	POP	AF
	JR	NZ,J$09C2
;
	NOP	
	LD	(D$F1F1),HL
	INC	H
I$09D6:	DEFB	0,0,0
	RST	38H
	LD	BC,I.01FF
	NOP	
	LD	BC,I.0001
	LD	BC,I.01FF
	RST	38H
	NOP	
	RST	38H
	RST	38H
	LD	HL,I$5050
	LD	(D.D149),HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.09EF:	LD	A,(D.D18E)
	OR	A
	RET	Z
;
	CP	01H	; 1 
	JR	Z,J$0A1B
;
	CP	02H	; 2 
	JR	Z,J$09FE
;
J$09FC:	JR	J$09FC
;
;	-----------------
J$09FE:	LD	A,01H	; 1 
	CALL	C$0AF4
;
	ADD	A,A
	LD	IX,I$09D6
	LD	B,00H
	LD	C,A
	ADD	IX,BC
	LD	A,(IX)
	LD	(D.D196),A
	LD	A,(IX+1)
	LD	(D.D197),A
	JR	J.0A66
;
;	-----------------
J$0A1B:	LD	A,(D.D49E)
	BIT	7,A			; no turbo flag ?
	JR	NZ,J$0A30		; yep, skip CPU
	IN	A,(40H)
	CPL	
	PUSH	AF
	LD	A,08H			; Matsushita switchable I/O
	OUT	(40H),A
	IN	A,(41H)
	OR	01H	; 1 
	OUT	(41H),A			; select normal CPU
J$0A30:	LD	A,0CH	; 12 
	CALL	C.0B48
	LD	A,0DH	; 13 
	CALL	C.0B48
	LD	(D.D196),A
	LD	A,0EH	; 14 
	CALL	C.0B48
	LD	(D.D197),A
	LD	A,(D.D49E)
	BIT	7,A			; no turbo flag ?
	JR	NZ,J.0A66		; yep, skip CPU
	PUSH	HL
	PUSH	BC
	LD	HL,I$D469
	LD	B,04H	; 4 
J$0A53:	LD	A,(HL)
	CP	83H
	JR	NZ,J$0A61
	INC	HL
	DJNZ	J$0A53
	IN	A,(41H)
	AND	0FEH
	OUT	(41H),A			; select turbo CPU
J$0A61:	POP	BC
	POP	HL
	POP	AF
	OUT	(40H),A
J.0A66:	LD	BC,(D.D149)
	LD	A,(D.D196)
	OR	A
	JP	P,J$0A77
	ADD	A,C
	JR	C,J$0A75
	XOR	A
J$0A75:	JR	J.0A7C
;
;	-----------------
J$0A77:	ADD	A,C
	JR	NC,J.0A7C
;
	LD	A,0FFH
J.0A7C:	LD	C,A
	LD	A,(D.D197)
	OR	A
	JP	P,J$0A8A
;
	ADD	A,B
	JR	C,J$0A88
;
	XOR	A
J$0A88:	JR	J.0A91
;
;	-----------------
J$0A8A:	ADD	A,B
	CP	0D4H
	JR	C,J.0A91
;
	LD	A,0D3H
J.0A91:	LD	B,A
	CALL	C.0ABA
;
	LD	IX,D.D149
	LD	A,01H	; 1 
	CALL	C.0B32
;
	CP	(IX+4)
	JR	Z,J$0AA9
;
	LD	(IX+2),A
	LD	(IX+4),A
J$0AA9:	LD	A,03H	; 3 
	CALL	C.0B32
;
	CP	(IX+5)
	JR	Z,J$0AB9
;
	LD	(IX+3),A
	LD	(IX+5),A
J$0AB9:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0ABA:	LD	(D.D149),BC
	LD	A,B
	LD	B,C
	LD	C,A
	LD	IX,I$09B1
	CALL	C$0D29
;
J$0AC8:	JR	NC,J$0AC8
;
	LD	BC,(D.D149)
	LD	A,C
	ADD	A,(HL)
	LD	D,A
	LD	A,B
	INC	HL
	ADD	A,(HL)
	DEC	A
	LD	E,A
	LD	A,06H	; 6 
	PUSH	HL
	PUSH	DE
	CALL	C.18D6
;
	POP	DE
	LD	A,07H	; 7 
	CALL	C.18D6
;
	POP	HL
	INC	HL
	LD	B,(HL)
	LD	A,06H	; 6 
	PUSH	BC
	CALL	C.1917
;
	POP	BC
	INC	B
	LD	A,07H	; 7 
	CALL	C.1917
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0AF4:	DEC	A
	CALL	C.0B03
;
	LD	HL,I$0B22
	AND	0FH	; 15 
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,(HL)
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0B03:	LD	B,A
	LD	A,0FH	; 15 
	CALL	C$0B1D
;
	DJNZ	J$0B11
;
	AND	0DFH
	OR	4CH	; "L"
	JR	J$0B15
;
;	-----------------
J$0B11:	AND	0AFH
	OR	03H	; 3 
J$0B15:	OUT	(0A1H),A
	CALL	C$0B1B
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0B1B:	LD	A,0EH	; 14 
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0B1D:	OUT	(0A0H),A
	IN	A,(0A2H)
	RET	
;
;	-----------------
I$0B22:	NOP	
	DEC	B
	LD	BC,I$0300
	INC	B
	LD	(BC),A
	INC	BC
	RLCA	
	LD	B,08H	; 8 
	RLCA	
	NOP	
	DEC	B
	LD	BC,I$3D00
C.0B32	EQU	$-1
	PUSH	AF
	AND	01H	; 1 
	CALL	C.0B03
;
	POP	BC
	DEC	B
	DEC	B
	LD	B,10H	; 16 
	JP	M,J$0B43
;
	LD	B,20H	; " "
J$0B43:	AND	B
	SUB	01H	; 1 
	SBC	A,A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0B48:	LD	E,0FH	; 15 
	LD	BC,I$00BF
	LD	HL,I$10EF
	CP	0CH	; 12 
	JR	Z,J.0B6C
;
	LD	BC,I$40FF
	LD	HL,I$20DF
	CP	10H	; 16 
	JR	Z,J.0B6C
;
	AND	03H	; 3 
	SUB	02H	; 2 
	LD	A,(D.D198)
	RET	M
;
	LD	A,(D.D199)
	RET	Z
;
	XOR	A
	RET	
;
;	-----------------
J.0B6C:	CALL	C.0BE0
;
	CALL	C$0BFB
;
	PUSH	AF
	CALL	C.0BE6
;
	CALL	C.0BF2
;
	PUSH	AF
	CALL	C.0BE0
;
	CALL	C.0BF8
;
	PUSH	AF
	CALL	C.0BE6
;
	CALL	C.0BF8
;
	PUSH	AF
	CALL	C.0BE0
;
	CALL	C.0BF8
;
	PUSH	AF
	CALL	C.0BE6
;
	CALL	C.0BF2
;
	PUSH	AF
	CALL	C.0BE0
;
	CALL	C.0C0B
;
	CALL	C.0BE6
;
	CALL	C.0C0B
;
	CALL	C.0BE0
;
	POP	AF
	POP	HL
	POP	DE
	POP	BC
	XOR	08H	; 8 
	SUB	02H	; 2 
	CP	0DH	; 13 
	JR	C,J$0BBE
;
	POP	AF
	CALL	C.0BD8
;
	LD	(D.D199),A
	POP	AF
	CALL	C.0BD8
;
	JR	J$0BD2
;
;	-----------------
J$0BBE:	LD	A,D
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	H
	NEG	
	LD	(D.D199),A
	POP	AF
	POP	DE
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	B
	NEG	
J$0BD2:	LD	(D.D198),A
	LD	A,0FFH
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0BD8:	XOR	08H	; 8 
	BIT	3,A
	RET	Z
;
	OR	0F0H
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0BE0:	CALL	C.0C03
;
	AND	L
	JR	J$0BEA
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0BE6:	CALL	C.0C03
;
	OR	H
J$0BEA:	PUSH	AF
	LD	A,E
	OUT	(0A0H),A
	POP	AF
	OUT	(0A1H),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0BF2:	CALL	C.0C0B
;
	CALL	C.0C0B
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0BF8:	CALL	C.0C0B
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0BFB:	LD	A,0EH	; 14 
	CALL	C$0C04
I$0BFF	EQU	$-1
;
	AND	0FH	; 15 
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0C03:	LD	A,E
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0C04:	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	C
	OR	B
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0C0B:	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0C10:	CALL	C.1252			; select firmware on page 1
	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.12FA			; select firmware slot and segments in page 2
	CALL	C$8003
	CALL	C.1371			; restore slot and segments on page 2
	CALL	C.12AC			; restore slot on page 1
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0C23:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C.8000
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0C36:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,0AH	; 10 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$8009
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0C49:	CALL	C.1252			; select firmware on page 1
	EX	AF,AF'
	LD	A,12H	; 18 
	CALL	C.12FA			; select firmware slot and segments in page 2
	CALL	C$8042
	CALL	C.1371			; restore slot and segments on page 2
	CALL	C.12AC			; restore slot on page 1
	RET	
;
;	-----------------
?.0C5C:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,24H	; "$"
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C.8000
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
J$0C6F:	CALL	C.13CA			; select firmware slot in page 2
	CALL	C.0122
	EX	AF,AF'
	LD	A,0CH	; 12 
	CALL	C.08E5			; select firmware slot and segments in page 1
	DI	
	PUSH	AF
	LD	A,0EH	; 14 
	LD	(D.7000),A		; select segment page 2 (8000H-9FFFH)
	LD	A,80H			; segment = SRAM
	LD	(D.7800),A		; select segment page 2 (A000H-BFFFH)
	POP	AF
	CALL	C$4028
	EI	
	CALL	C.0958			; restore slot and segments page 1
	CALL	C.00EE
	CALL	C.1428			; restore slot in page 2
	RET	
;
;	-----------------
J$0C96:	CALL	C.13CA			; select firmware slot in page 2
;
	CALL	C.0122
;
	EX	AF,AF'
	LD	A,0CH	; 12 
	CALL	C.08E5			; select firmware slot and segments in page 1
;
	DI	
	PUSH	AF
	LD	A,0EH	; 14 
	LD	(D.7000),A		; select segment page 2 (8000H-9FFFH)
	LD	A,80H			; segment = SRAM
	LD	(D.7800),A		; select segment page 2 (A000H-BFFFH)
	POP	AF
	CALL	C$402B
;
	EI	
	CALL	C.0958			; restore slot and segments page 1
;
	CALL	C.00EE
;
	CALL	C.1428			; restore slot in page 2
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0CBD:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$801E
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0CD0:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$8021
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0CE3:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$8024
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0CF6:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$8027
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0D09:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$802A
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0D1C:	EX	AF,AF'
	LD	A,26H	; "&"
	CALL	C.08E5			; select firmware slot and segments in page 1
	CALL	C$4027
	CALL	C.0958			; restore slot and segments page 1
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0D29:	EX	AF,AF'
	LD	A,08H	; 8 
	CALL	C.08E5			; select firmware slot and segments in page 1
;
	CALL	C$4042
;
	CALL	C.0958			; restore slot and segments page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0D36:	CALL	C.1252			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,2CH	; ","
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	CALL	C$A1CF
;
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.0D49:	CALL	C.1252			; select firmware on page 1
	EX	AF,AF'
	LD	A,2CH	; ","
	CALL	C.12FA			; select firmware slot and segments in page 2
	CALL	C$A1D5
	CALL	C.1371			; restore slot and segments on page 2
	CALL	C.12AC			; restore slot on page 1
	RET	
;
;	-----------------
J$0D5C:	PUSH	AF
	LD	A,01H	; 1 
	LD	(D.D19B),A
	JR	J$0D6E
;
;	-----------------
J$0D64:	PUSH	AF
	LD	A,0FFH
	LD	(D$D48B),A
	XOR	A
	LD	(D.D19B),A
J$0D6E:	LD	A,(D.D47E)
	PUSH	AF
	LD	A,(D.D480)
	PUSH	AF
	LD	A,(D.D47B)
	PUSH	AF
	LD	A,(D.D47D)
	PUSH	AF
	XOR	A
	LD	(D.D47E),A
	LD	(D.D47B),A
	LD	A,08H	; 8 
	LD	(D.D47D),A
	LD	A,3DH	; "="
	LD	(D.D480),A
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IY
	PUSH	IX
	LD	A,(IX)
	LD	(D$D1B6),A
	ADD	A,A
	ADD	A,A
	ADD	A,04H	; 4 
	LD	(D.D19C),A
	LD	A,(IX+1)
	LD	(D.D1B7),A
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	ADD	A,A
	ADD	A,B
	ADD	A,12H	; 18 
	LD	(D.D19D),A
	LD	A,(IX+2)
	ADD	A,A
	ADD	A,A
	LD	(D.D19E),A
	SUB	04H	; 4 
	LD	HL,D.D19C
	ADD	A,(HL)
	LD	(D.D19A),A
	LD	A,(IX+3)
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	ADD	A,A
	ADD	A,B
	LD	(D.D19F),A
	LD	A,(D.D19B)
	OR	A
	JR	NZ,J$0E3C
;
	LD	HL,(D.D1A0)
	LD	BC,I$D1A1
	SBC	HL,BC
	JP	Z,J.0FBC
;
	LD	HL,(D.D1A0)
	LD	BC,(D.D19E)
	LD	(HL),B
	DEC	HL
	LD	(HL),C
	DEC	HL
	LD	BC,(D.D19C)
	LD	(HL),B
	DEC	HL
	LD	(HL),C
	DEC	HL
	LD	(D.D1A0),HL
	LD	HL,(D.D19C)
	LD	H,00H
	DEC	HL
	ADD	HL,HL
	LD	(D.CF1A),HL
	LD	(D.CF1E),HL
	LD	A,(D.D19E)
	ADD	A,03H	; 3 
	LD	L,A
	LD	H,00H
	ADD	HL,HL
	LD	(D.CF22),HL
	LD	A,(D.D19D)
	DEC	A
	DEC	A
	LD	B,00H
	LD	C,A
	LD	(D.CF1C),BC
	LD	B,01H	; 1 
	LD	(D.CF20),BC
	LD	A,(D.D19F)
	ADD	A,03H	; 3 
	LD	B,00H
	LD	C,A
	LD	(D.CF24),BC
	LD	A,00H
	LD	(D.CF26),A
	LD	HL,D.CF1A
	CALL	C$0FD5
;
J$0E3C:	LD	HL,(D.D19C)
	LD	H,00H
	ADD	HL,HL
	LD	(D.CF1A),HL
	LD	HL,(D.D19E)
	LD	A,L
	LD	L,A
	LD	H,00H
	INC	HL
	ADD	HL,HL
	LD	(D.CF1E),HL
	LD	A,(D.D19D)
	DEC	A
	LD	B,00H
	LD	C,A
	LD	(D.CF1C),BC
	LD	A,(D.D19F)
	DEC	A
	LD	B,00H
	LD	C,A
	INC	BC
	INC	BC
	LD	(D.CF20),BC
	LD	A,00H
	LD	(D.CF22),A
	LD	HL,D.CF1A
	CALL	C.172A
;
	LD	BC,(D.CF1A)
	INC	BC
	INC	BC
	LD	(D.CF1A),BC
	LD	BC,(D.CF1C)
	INC	BC
	LD	(D.CF1C),BC
	LD	BC,(D.CF20)
	DEC	BC
	LD	(D.CF20),BC
	CALL	C.172A
;
	LD	BC,(D.CF1A)
	DEC	BC
	DEC	BC
	LD	(D.CF1A),BC
	LD	BC,(D.CF1C)
	DEC	BC
	DEC	BC
	LD	(D.CF1C),BC
	LD	BC,(D.CF1E)
	DEC	BC
	DEC	BC
	LD	(D.CF1E),BC
	LD	A,99H
	LD	(D.CF22),A
	CALL	C.172A
;
	LD	IX,D.D19C
	LD	IY,D.D17C
	LD	A,(IX)
	LD	(IY),A
	LD	A,(IX+1)
	DEC	A
	DEC	A
	LD	(IY+1),A
	LD	A,(IX+2)
	ADD	A,(IX)
	LD	(IY+2),A
	LD	A,(IX+3)
	ADD	A,(IY+1)
	LD	(IY+3),A
	LD	(IY+4),00H
	LD	(IY+5),00H
	XOR	A
	LD	(IY+6),A
	LD	(IY+7),A
	LD	IX,D.D17C
	CALL	C.1C14
;
	EX	(SP),IX
	LD	A,1FH
	AND	(IX+4)
	EX	(SP),IX
	JP	Z,J.0FBC
;
I$0F03:	LD	A,(D$D17D)
	ADD	A,13H	; 19 
	LD	(D$D17F),A
	LD	(IX+4),0AH	; 10 
	LD	(IX+6),01H	; 1 
	CALL	C.1C14
;
	LD	(IX+4),00H
	LD	(IX+6),00H
	CALL	C.1C14
;
	POP	IY
	PUSH	IY
	BIT	4,(IY+4)
	JR	Z,J$0F86
;
	LD	A,(D.D17C)
	ADD	A,04H	; 4 
	LD	(D.D17C),A
	ADD	A,(IY+5)
	ADD	A,(IY+5)
	ADD	A,(IY+5)
	ADD	A,(IY+5)
	LD	(D$D17E),A
	LD	(IX+4),01H	; 1 
	LD	(IX+6),01H	; 1 
	CALL	C.1C14
;
	LD	IX,I.D16C
	LD	A,(IY+5)
	LD	(IX),A
	LD	A,(IY)
	INC	A
	LD	(IX+1),A
	LD	A,(IY+1)
	LD	(IX+2),A
	LD	(IX+3),00H
	LD	A,01H	; 1 
	LD	(D.D18F),A
	PUSH	IY
	POP	HL
	LD	BC,CPMADR
	ADD	HL,BC
	CALL	C.2FC8
;
	LD	IX,D.D17C
	LD	(IX+4),00H
	LD	(IX+6),00H
	CALL	C.1C14
;
J$0F86:	LD	A,(D.D18E)
	OR	A
	JR	Z,J.0FBC
;
	BIT	0,(IY+4)
	JR	Z,J$0F9B
;
	XOR	A
	CALL	C.1082
;
	LD	A,01H	; 1 
	CALL	C.1082
;
J$0F9B:	BIT	1,(IY+4)
	JR	Z,J$0FA6
;
	LD	A,02H	; 2 
	CALL	C.1082
;
J$0FA6:	BIT	2,(IY+4)
	JR	Z,J$0FB1
;
	LD	A,03H	; 3 
	CALL	C.1082
;
J$0FB1:	BIT	3,(IY+4)
	JR	Z,J.0FBC
;
	LD	A,04H	; 4 
	CALL	C.1082
;
J.0FBC:	POP	IX
	POP	IY
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	LD	(D.D47D),A
	POP	AF
	LD	(D.D47B),A
	POP	AF
	LD	(D.D480),A
	POP	AF
	LD	(D.D47E),A
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$0FD5:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.D1B2)
	LD	(D.CF1E),HL
	LD	HL,(D.D1B4)
	LD	(D.CF20),HL
	LD	BC,(D.CF22)
	LD	DE,(D.CF24)
	LD	HL,I.0001
	LD	(D.CF24),HL
J$0FF3:	LD	A,E
	OR	D
	JR	Z,J$1004
;
	CALL	C$1015
;
	LD	HL,(D.CF1C)
	INC	HL
	LD	(D.CF1C),HL
	DEC	DE
	JR	J$0FF3
;
;	-----------------
J$1004:	LD	HL,(D.CF1E)
	LD	(D.D1B2),HL
	LD	HL,(D.CF20)
	LD	(D.D1B4),HL
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1015:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.CF1A)
	PUSH	HL
	LD	(D.CF22),BC
	LD	HL,I.0200
	LD	DE,(D.CF1E)
	OR	A
	SBC	HL,DE
	LD	D,B
	LD	E,C
	EX	DE,HL
	OR	A
	SBC	HL,DE
	JR	Z,J.1058
;
	JR	C,J.1058
;
	LD	(D.CF22),DE
	PUSH	HL
	LD	HL,D.CF1A
	CALL	C.16EB
;
	POP	HL
	LD	(D.CF22),HL
	LD	HL,(D.CF1A)
	ADD	HL,DE
	LD	(D.CF1A),HL
	LD	HL,(D.CF20)
	INC	HL
	LD	(D.CF20),HL
	LD	DE,C.0000
	LD	(D.CF1E),DE
J.1058:	LD	HL,D.CF1A
	CALL	C.16EB
;
	LD	HL,(D.CF1E)
	LD	DE,(D.CF22)
	ADD	HL,DE
	LD	A,H
	CP	02H	; 2 
	JR	C,J$1077
;
	AND	01H	; 1 
	LD	H,A
	LD	DE,(D.CF20)
	INC	DE
	LD	(D.CF20),DE
J$1077:	LD	(D.CF1E),HL
	POP	HL
	LD	(D.CF1A),HL
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.1082:	ADD	A,A
	LD	C,A
	LD	B,00H
	LD	HL,I$10FB
J$1089:	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	POP	HL
J$108F:	LD	IX,D.D17C
	LD	A,(D.D19A)
	LD	(IX+2),A
	SUB	(HL)
	SUB	(HL)
	SUB	(HL)
	SUB	(HL)
	LD	(D.D19A),A
	LD	(IX),A
	LD	A,(D.D19D)
	DEC	A
	DEC	A
	LD	(IX+1),A
	ADD	A,13H	; 19 
	LD	(IX+3),A
	LD	A,01H	; 1 
	LD	(IX+4),A
	LD	(IX+5),00H
	LD	(IX+6),01H	; 1 
	LD	(IX+7),00H
	CALL	C.1C14
;
	LD	IX,I.D16C
	LD	A,(HL)
	LD	(IX),A
	LD	A,(D.D19A)
	SUB	04H	; 4 
	SRL	A
	SRL	A
	LD	(IX+1),A
	LD	A,(D.D1B7)
	LD	(IX+2),A
	LD	(IX+3),00H
	LD	A,01H	; 1 
	LD	(D.D18F),A
	INC	HL
	CALL	C.2FC8
;
	LD	IX,D.D17C
I$10EF:	LD	(IX+4),00H
	LD	(IX+6),00H
	CALL	C.1C14
;
	RET	
;
;	-----------------
I$10FB:	DEC	B
	LD	DE,I$110B
	LD	DE,I$1911
	LD	DE,I$1121
	INC	B
	JR	NZ,J$1089
;
	AND	L
	JR	NZ,J$110A
J$110A	EQU	$-1
;
I$110B:	INC	B
	JR	NZ,J$108F
;
	AND	E
	JR	NZ,J$1110
J$1110	EQU	$-1
;
	LD	B,20H	; " "
	ADC	A,(HL)
	RET	NZ
;
	ADC	A,L
	LD	(HL),E
	JR	NZ,J$1118
J$1118	EQU	$-1
;
	LD	B,20H	; " "
	ADC	A,(HL)
	AND	8FH
	POP	BC
	JR	NZ,J$1120
J$1120	EQU	$-1
;
I$1121:	DEC	B
	JR	NZ,J$1169
;
	LD	D,E
	LD	B,E
	JR	NZ,J$1127
J$1127	EQU	$-1
;
J$1128:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	DE,(D.D1A0)
	LD	HL,I$D1B1
	OR	A
	SBC	HL,DE
	EX	DE,HL
	JR	Z,J$117B
;
	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	(D.D1A0),HL
	LD	H,00H
	LD	L,C
	DEC	HL
	ADD	HL,HL
	LD	(D.CF1A),HL
	LD	(D.CF1E),HL
	LD	A,E
	ADD	A,03H	; 3 
	LD	L,A
	LD	H,00H
	ADD	HL,HL
	LD	(D.CF22),HL
	LD	A,B
	DEC	A
	DEC	A
	LD	H,01H	; 1 
	LD	L,A
	LD	(D.CF1C),HL
	LD	H,00H
	LD	(D.CF20),HL
	LD	A,D
	ADD	A,03H	; 3 
J$1169	EQU	$-1
	LD	H,00H
	LD	L,A
	LD	(D.CF24),HL
	LD	A,00H
	LD	(D.CF26),A
	LD	HL,D.CF1A
	CALL	C$1180
;
J$117B:	POP	AF
	POP	BC
	POP	DE
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1180:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.D1B2)
	LD	(D.CF1A),HL
	LD	HL,(D.D1B4)
	LD	(D.CF1C),HL
	LD	HL,(D.CF1E)
	LD	BC,(D.CF22)
	ADD	HL,BC
	LD	(D.CF1E),HL
	LD	HL,(D.CF20)
	LD	BC,(D.CF24)
	DEC	HL
	ADD	HL,BC
	LD	(D.CF20),HL
	LD	BC,(D.CF22)
	LD	DE,(D.CF24)
	LD	HL,I.0001
	LD	(D.CF24),HL
J$11B5:	LD	A,E
	OR	D
	JR	Z,J$11C6
;
	CALL	C$11D7
;
	LD	HL,(D.CF20)
	DEC	HL
	LD	(D.CF20),HL
	DEC	DE
	JR	J$11B5
;
;	-----------------
J$11C6:	LD	HL,(D.CF1A)
	LD	(D.D1B2),HL
	LD	HL,(D.CF1C)
	LD	(D.D1B4),HL
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$11D7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.CF1E)
	PUSH	HL
	LD	(D.CF22),BC
	LD	H,B
	LD	L,C
	LD	DE,(D.CF1A)
	OR	A
	SBC	HL,DE
	JR	Z,J.1232
;
	JR	C,J.1232
;
	PUSH	HL
	LD	A,D
	OR	E
	JR	Z,J$120C
;
	LD	(D.CF22),DE
	LD	HL,(D.CF1E)
	SBC	HL,DE
	LD	(D.CF1E),HL
	LD	HL,C.0000
	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.16EB
;
J$120C:	POP	DE
	LD	(D.CF22),DE
	LD	HL,(D.CF1E)
	OR	A
	SBC	HL,DE
	LD	(D.CF1E),HL
	LD	HL,I.0200
	OR	A
	SBC	HL,DE
	LD	(D.CF1A),HL
	LD	HL,(D.CF1C)
	DEC	HL
	LD	(D.CF1C),HL
	LD	HL,D.CF1A
	CALL	C.16EB
;
	JR	J$124A
;
;	-----------------
J.1232:	OR	A
	LD	HL,(D.CF1E)
	SBC	HL,BC
	LD	(D.CF1E),HL
	OR	A
	LD	HL,(D.CF1A)
	SBC	HL,BC
	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.16EB
;
J$124A:	POP	HL
	LD	(D.CF1E),HL
	POP	HL
	POP	DE
	POP	BC
	RET	

;	  Subroutine select firmware on page 1
;	     Inputs  ________________________
;	     Outputs ________________________

C.1252:	DI	
	PUSH	AF			; bogus
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$12A5
	EI	
J$12A5:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;	  Subroutine restore slot on page 1
;	     Inputs  ________________________
;	     Outputs ________________________

C.12AC:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$12F3
	EI	
J$12F3:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	RET	

;	  Subroutine select firmware slot and segments in page 2
;	     Inputs  ________________________
;	     Outputs ________________________

C.12FA:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	PUSH	AF
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+15)
	LD	(IX+11),A
	LD	A,(IX+14)
	LD	(IX+10),A
	LD	(IX+15),B
	LD	(IX+14),C
	POP	AF
	LD	C,A
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D.7FF4)
	LD	B,A
	LD	A,C
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	LD	(IX+13),B
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$1369
;
	EI	
J$1369:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	RET	

;	  Subroutine restore slot and segments on page 2
;	     Inputs  ________________________
;	     Outputs ________________________

C.1371:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,C.0000
	ADD	IX,SP
	LD	A,(IX+11)
	LD	(D.7000),A
	INC	A
	LD	(D.7800),A		; select segments page 2
	LD	B,(IX+13)
	LD	C,(IX+12)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+13),A
	LD	A,(IX+8)
	LD	(IX+12),A
	LD	A,(IX+7)
	LD	(IX+11),A
	LD	A,(IX+6)
	LD	(IX+10),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$13C2
;
	EI	
J$13C2:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	POP	AF
	RET	

;	  Subroutine select firmware slot in page 2
;	     Inputs  ________________________
;	     Outputs ________________________

C.13CA:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0CFH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RLCA	
	RLCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0CFH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$1421
	EI	
J$1421:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;	  Subroutine restore slot in page 2
;	     Inputs  ________________________
;	     Outputs ________________________

C.1428:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,C.0000
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$146F
	EI	
J$146F:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1476:	PUSH	AF
	PUSH	BC
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,02H	; 2 
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	CALL	C.14A3
	LD	A,(D.D49F)
	INC	A
	LD	C,A
J$148D:	IN	A,(C)
	AND	01H	; 1 
	JR	NZ,J$148D
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,00H
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.14A3:	NOP	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.14A5:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.1476			; wait for VDP ready
	LD	E,00H
	LD	HL,I$14FF
	LD	B,10H	; 16 
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
J$14B8:	PUSH	BC
	LD	A,E
	OUT	(C),A
	LD	A,90H
	OUT	(C),A
	INC	C
	LD	A,(HL)
	OUT	(C),A
	INC	HL
	LD	A,(HL)
	OUT	(C),A
	INC	HL
	INC	E
	POP	BC
	DJNZ	J$14B8
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$14D2:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.1476			; wait for VDP ready
;
	LD	E,00H
	LD	HL,I$151F
	LD	B,10H	; 16 
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
J$14E5:	PUSH	BC
	LD	A,E
	OUT	(C),A
	LD	A,90H
	OUT	(C),A
	INC	C
	LD	A,(HL)
	OUT	(C),A
	INC	HL
	LD	A,(HL)
	OUT	(C),A
	INC	HL
	INC	E
	POP	BC
	DJNZ	J$14E5
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$14FF:	DEFB	0,0
	LD	(HL),A
	RLCA	
	LD	H,A
	LD	B,65H	; "e"
	LD	B,02H	; 2 
	DEC	B
	LD	H,H
	LD	(BC),A
	LD	B,A
	INC	B
	LD	H,(HL)
	LD	B,34H	; "4"
	INC	BC
	LD	D,A
	LD	B,44H	; "D"
	LD	B,47H	; "G"
	LD	B,62H	; "b"
	LD	B,04H	; 4 
	INC	B
	DEFB	0,0,0,0
I$151F:	DEFB	0,0,0,0
	LD	DE,I$3306
	RLCA	
	RLA	
	LD	BC,I$0327
	LD	D,C
	LD	BC,I$0627
	LD	(HL),C
	LD	BC,J.0373
	LD	H,C
	LD	B,63H	; "c"
	LD	B,11H	; 17 
	INC	B
	LD	H,H
	LD	(BC),A
	LD	D,L
	DEC	B
	LD	(HL),A
	RLCA	

J$153F:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C$1618
	DI	
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,03H	; 3 
	OUT	(C),A
	LD	A,8EH
	OUT	(C),A
	LD	A,00H
	OUT	(C),A
	LD	A,70H	; "p"
	OUT	(C),A
	LD	HL,I$1D9F
	LD	BC,I$0540
J$1562:	PUSH	BC
	LD	A,(D.D4A0)
	LD	C,A
	LD	A,(HL)
	OUT	(C),A
	INC	HL
	POP	BC
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$1562
	LD	B,58H	; "X"
J$1573:	PUSH	BC
	LD	B,08H	; 8 
	LD	A,(D.D4A0)
	LD	C,A
J$157A:	XOR	A
	OUT	(C),A
	DJNZ	J$157A
	POP	BC
	DJNZ	J$1573
	LD	A,(D.D4A0)
	LD	C,A
	LD	B,10H	; 16 
J$1588:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$1588
	LD	B,10H	; 16 
J$1590:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$1590
	LD	B,10H	; 16 
J$1598:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$1598
	LD	B,10H	; 16 
J$15A0:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$15A0
	LD	B,10H	; 16 
J$15A8:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$15A8
	LD	B,10H	; 16 
J$15B0:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$15B0
	LD	B,10H	; 16 
J$15B8:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$15B8
	LD	B,10H	; 16 
J$15C0:	LD	A,00H
	OUT	(C),A
	DJNZ	J$15C0
	LD	B,10H	; 16 
J$15C8:	LD	A,05H	; 5 
	OUT	(C),A
	DJNZ	J$15C8
	LD	B,17H
J$15D0:	PUSH	BC
	LD	B,10H	; 16 
J$15D3:	XOR	A
	OUT	(C),A
	DJNZ	J$15D3
	POP	BC
	DJNZ	J$15D0
	LD	HL,I$15FB
	LD	B,09H	; 9 
J$15E0:	LD	A,0F0H
	OUT	(C),A
	LD	A,0FFH
	OUT	(C),A
	LD	A,(HL)
	OUT	(C),A
	INC	HL
	XOR	A
	OUT	(C),A
	DJNZ	J$15E0
	LD	A,0D8H
	OUT	(C),A
	EI	
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$15FB:	NOP	
	LD	C,B
	LD	C,H
	SBC	A,B
	SBC	A,B
	SBC	A,B
	LD	A,B
	ADC	A,B
	SBC	A,H

J$1604:	DI	
	PUSH	AF
	PUSH	BC
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,62H	; "b"
	OUT	(C),A
	LD	A,81H
	OUT	(C),A
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1618:	DI	
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,00H
	OUT	(C),A
	LD	A,0AEH
	OUT	(C),A
	LD	A,0AH	; 10 
	OUT	(C),A
	LD	A,80H
	OUT	(C),A
	LD	A,22H	; """
	OUT	(C),A
	LD	A,81H
	OUT	(C),A
	LD	A,28H	; "("
	OUT	(C),A
	LD	A,88H
	OUT	(C),A
	LD	A,80H
	OUT	(C),A
	LD	A,89H
	OUT	(C),A
	LD	A,1FH
	OUT	(C),A
	LD	A,82H
	OUT	(C),A
	LD	A,0F7H
	OUT	(C),A
	LD	A,85H
	OUT	(C),A
	LD	A,01H	; 1 
	OUT	(C),A
	LD	A,8BH
	OUT	(C),A
	LD	A,1EH
	OUT	(C),A
	LD	A,86H
	OUT	(C),A
	LD	A,06H	; 6 
	OUT	(C),A
	LD	A,87H
	OUT	(C),A
	CALL	C.14A5
	LD	A,00H
	OUT	(C),A
	LD	A,0ADH
	OUT	(C),A
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.167B:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$16C9
;
	LD	A,(D.D4A0)
	INC	A
	INC	A
	INC	A
	LD	C,A
	LD	A,0F0H
	OUT	(C),A
	DEC	C
	DEC	C
	LD	A,02H	; 2 
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	CALL	C.14A3
;
	LD	A,(D.D49F)
	INC	A
	LD	C,A
J.16A3:	IN	A,(C)
	BIT	0,A
	JR	Z,J$16BC
;
	BIT	7,A
	JR	Z,J.16A3
;
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	INC	HL
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ACH
	OUT	(C),A
	JR	J.16A3
;
;	-----------------
J$16BC:	XOR	A
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$16C9:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,24H	; "$"
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,08H	; 8 
J$16DA:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$16DA
;
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	LD	A,(HL)
	OUT	(C),A
	XOR	A
	OUT	(C),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.16EB:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$1709
;
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,0D0H
	OUT	(C),A
	LD	A,0AEH
	OUT	(C),A
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1709:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,20H	; " "
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,0CH	; 12 
J$171A:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$171A
;
	DEC	C
	DEC	C
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ADH
	OUT	(C),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.172A:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$1746
;
	LD	A,(D.D4A0)
	INC	A
	INC	A
	INC	A
	LD	C,A
	LD	A,0C0H
	OUT	(C),A
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1746:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,24H	; "$"
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,09H	; 9 
J$1757:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$1757
;
	XOR	A
	OUT	(C),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.1761:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$177F
;
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,50H	; "P"
	OUT	(C),A
	LD	A,0AEH
	OUT	(C),A
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$177F:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,24H	; "$"
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,04H	; 4 
J$1790:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$1790
;
	DEC	C
	DEC	C
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ACH
	OUT	(C),A
	XOR	A
	OUT	(C),A
	LD	A,0ADH
	OUT	(C),A
	RET	
;
;	-----------------
J$17A7:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$17C5
;
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,0E0H
	OUT	(C),A
	LD	A,0AEH
	OUT	(C),A
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$17C5:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,22H	; """
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,06H	; 6 
J$17D6:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$17D6
;
	DEC	C
	DEC	C
	LD	A,(HL)
	OUT	(C),A
	LD	A,0AAH
	OUT	(C),A
	INC	HL
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ABH
	OUT	(C),A
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ADH
	OUT	(C),A
	RET	
;
;	-----------------
J$17F5:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$1806
;
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1806:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,20H	; " "
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,0CH	; 12 
J$1817:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$1817
;
	DEC	C
	DEC	C
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ADH
	OUT	(C),A
	INC	HL
	LD	A,(HL)
	AND	0FH	; 15 
	OR	90H
	OUT	(C),A
	LD	A,0AEH
	OUT	(C),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.1833:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$1844
;
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1844:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,24H	; "$"
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,09H	; 9 
J$1855:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$1855
;
	XOR	A
	OUT	(C),A
	LD	A,(HL)
	AND	0FH	; 15 
	OR	80H
	OUT	(C),A
	RET	
;
;	-----------------
J$1866:	DI	
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	CALL	C.1476			; wait for VDP ready
;
	CALL	C$18AC
;
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,02H	; 2 
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	CALL	C.14A3
;
	LD	A,(D.D49F)
	INC	A
	LD	C,A
J.1886:	IN	A,(C)
	BIT	0,A
	JR	Z,J$189F
;
	BIT	7,A
	JR	Z,J.1886
;
	INC	HL
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,(HL)
	OUT	(C),A
	LD	A,0ACH
	OUT	(C),A
	JR	J.1886
;
;	-----------------
J$189F:	XOR	A
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$18AC:	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,24H	; "$"
	OUT	(C),A
	LD	A,91H
	OUT	(C),A
	INC	C
	INC	C
	LD	B,08H	; 8 
J$18BD:	LD	A,(HL)
	OUT	(C),A
	INC	HL
	DJNZ	J$18BD
;
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	LD	A,(HL)
	OUT	(C),A
	XOR	A
	OUT	(C),A
	INC	DE
	LD	A,(DE)
	AND	0FH	; 15 
	OR	0B0H
	OUT	(C),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.18D6:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.1476			; wait for VDP ready
;
	LD	HL,I$FA00
	SLA	A
	SLA	A
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,03H	; 3 
	OUT	(C),A
	LD	A,8EH
	OUT	(C),A
	LD	A,L
	OUT	(C),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(C),A
	DEFB	0,0,0,0,0
	DEC	C
	LD	A,E
	OUT	(C),A
	DEFB	0,0,0,0,0
	LD	A,D
	OUT	(C),A
I$1911:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.1917:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.1476			; wait for VDP ready
;
	LD	HL,I$FA02
	SLA	A
	SLA	A
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	SLA	B
	SLA	B
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,03H	; 3 
	OUT	(C),A
	LD	A,8EH
	OUT	(C),A
	LD	A,L
	OUT	(C),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(C),A
	DEC	C
	LD	A,B
	OUT	(C),A
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
J$194F:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.1476			; wait for VDP ready
;
	LD	HL,I$F800
	LD	E,A
	LD	D,00H
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	ADD	HL,DE
	PUSH	BC
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,03H	; 3 
	OUT	(C),A
	LD	A,8EH
	OUT	(C),A
	LD	A,L
	OUT	(C),A
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	OUT	(C),A
	POP	BC
	LD	B,10H	; 16 
	LD	D,C
	LD	A,(D.D4A0)
	LD	C,A
J$198E:	OUT	(C),D
	DJNZ	J$198E
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
J$1998:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.1A2E
;
	PUSH	AF
	AND	0FH	; 15 
	SLA	A
	LD	C,A
	LD	B,00H
	POP	AF
	LD	HL,I$19DA
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	AND	0F0H
	RRCA	
	RRCA	
	RRCA	
	LD	L,A
	LD	H,00H
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	A,(D$D466)
	AND	01H	; 1 
	LD	L,A
	LD	H,00H
	ADD	HL,BC
	LD	B,(HL)
	XOR	A
	CALL	C.1917
;
	XOR	A
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$19DA:	RET	PO
;
	ADD	HL,DE
	CALL	P,C$0819
;
	LD	A,(DE)
	INC	E
	LD	A,(DE)
	INC	E
	LD	A,(DE)
	LD	E,1AH
	LD	E,1AH
	JR	NZ,J$1A04
;
	JR	NZ,J$1A06
;
	JR	NZ,J$1A08
;
	JR	NZ,J$1A0A
;
	JR	NZ,J$1A0C
;
	JR	NZ,J$1A0E
;
	LD	(D$221A),HL
	LD	A,(DE)
	INC	H
	LD	A,(DE)
	INC	H
	LD	A,(DE)
	LD	H,1AH
	LD	H,1AH
	LD	H,1AH
	LD	H,1AH
J$1A04:	LD	H,1AH
J$1A06:	LD	H,1AH
J$1A08:	JR	Z,J$1A24
;
J$1A0A:	JR	Z,J$1A26
;
J$1A0C:	LD	HL,(D$2A1A)
J$1A0E	EQU	$-1
	LD	A,(DE)
	INC	L
	LD	A,(DE)
	INC	L
	LD	A,(DE)
	INC	L
	LD	A,(DE)
	INC	L
	LD	A,(DE)
	INC	L
	LD	A,(DE)
	INC	L
	LD	A,(DE)
	NOP	
	LD	BC,I.0302
	INC	B
	DEC	B
	LD	B,07H	; 7 
J$1A24:	EX	AF,AF'
	ADD	HL,BC
J$1A26:	LD	A,(BC)
	DEC	BC
	INC	C
	DEC	C
	LD	C,0FH	; 15 
	DJNZ	J$1A3F
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.1A2E:	PUSH	AF
	AND	0FH	; 15 
	SLA	A
	LD	E,A
	LD	D,00H
	LD	HL,I$1A69
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	PUSH	DE
	POP	IX
J$1A3F	EQU	$-1
	LD	E,B
	LD	B,(IX)
	LD	D,00H
	LD	HL,C.0000
J$1A49:	ADD	HL,DE
	DJNZ	J$1A49
;
	LD	E,(IX+1)
	ADD	HL,DE
	PUSH	HL
	LD	E,C
	LD	B,(IX+2)
	LD	D,00H
	LD	HL,C.0000
J$1A5A:	ADD	HL,DE
	DJNZ	J$1A5A
;
	LD	E,(IX+3)
	ADD	HL,DE
	SRL	H
	RR	L
	POP	DE
	LD	D,L
	POP	AF
	RET	
;
;	-----------------
I$1A69:	LD	L,A
	LD	A,(DE)
	LD	(HL),E
	LD	A,(DE)
	LD	(HL),A
	LD	A,(DE)
	LD	C,14H	; 20 
	LD	B,04H	; 4 
	INC	DE
	INC	DE
	EX	AF,AF'
	EX	AF,AF'
	LD	(BC),A
	RRA	
	LD	(BC),A
	LD	C,B
J$1A7B:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	PUSH	DE
	CALL	C$1AC5
;
	PUSH	AF
	AND	0FH	; 15 
	SLA	A
	LD	C,A
	LD	B,00H
	POP	AF
	LD	HL,I$1AB3
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	AND	0F0H
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	LD	L,A
	LD	H,00H
	ADD	HL,BC
	LD	B,(HL)
	POP	AF
	INC	A
	CALL	C.1917
;
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$1AB3:	CP	C
	LD	A,(DE)
	CP	L
	LD	A,(DE)
	POP	BC
	LD	A,(DE)
	LD	(DE),A
	INC	DE
	INC	D
	DEC	D
	LD	D,17H
	JR	J$1ADA
;
;	-----------------
?.1AC1:	LD	A,(DE)
	DEC	DE
	INC	E
	DEC	E
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1AC5:	PUSH	AF
	AND	0FH	; 15 
	SLA	A
	LD	E,A
	LD	D,00H
	LD	HL,I$1B0A
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	PUSH	DE
	POP	IX
	LD	E,B
	LD	B,(IX)
J$1ADA	EQU	$-1
	LD	D,00H
	LD	HL,C.0000
J$1AE0:	ADD	HL,DE
	DJNZ	J$1AE0
;
	LD	E,(IX+1)
	ADD	HL,DE
	PUSH	HL
	LD	E,C
	LD	B,(IX+2)
	LD	D,00H
	LD	HL,C.0000
J$1AF1:	ADD	HL,DE
	DJNZ	J$1AF1
;
	LD	E,(IX+3)
	ADD	HL,DE
	SRL	H
	RR	L
	POP	DE
	LD	D,L
	POP	AF
	CP	21H	; "!"
	JR	Z,J$1B07
;
	CP	31H	; "1"
	JR	NZ,J$1B09
;
J$1B07:	INC	E
	INC	E
J$1B09:	RET	
;
;	-----------------
I$1B0A:	DJNZ	J$1B27
;
	INC	D
	DEC	DE
	JR	J$1B2B
;
;	-----------------
?.1B10:	LD	C,12H	; 18 
	LD	B,04H	; 4 
	INC	DE
	LD	DE,I$0808
	LD	(BC),A
	LD	E,02H	; 2 
	LD	C,B
J$1B1C:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	PUSH	BC
	LD	B,06H	; 6 
J$1B27:	XOR	A
	CALL	C.1917
;
J$1B2B:	POP	BC
	LD	B,C
	LD	HL,DBUF
	LD	DE,C.0008
J$1B33:	ADD	HL,DE
	DJNZ	J$1B33
;
	SRL	H
	RR	L
	LD	D,L
	LD	E,0AFH
	XOR	A
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$1B4A:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C$1B64
;
	INC	A
	INC	A
	INC	A
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1B64:	PUSH	AF
	XOR	A
	LD	H,B
	LD	B,03H	; 3 
J$1B69:	ADD	A,H
	DJNZ	J$1B69
;
	ADD	A,2CH	; ","
	LD	E,A
	XOR	A
	LD	B,03H	; 3 
J$1B72:	ADD	A,C
	DJNZ	J$1B72
;
	ADD	A,0DH	; 13 
	LD	D,A
	LD	A,H
	CP	18H
	JP	C,J$1B86
;
	LD	A,D
	ADD	A,9CH
	LD	D,A
	LD	A,E
	SUB	48H	; "H"
	LD	E,A
J$1B86:	POP	AF
	RET	
;
;	-----------------
J$1B88:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C$1BA7
;
	ADD	A,27H	; "'"
	LD	B,A
	LD	A,08H	; 8 
	CALL	C.1917
;
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1BA7:	CALL	C.1A2E
;
	CP	02H	; 2 
	JR	Z,J$1BB0
;
	DEC	E
	DEC	E
J$1BB0:	RET	
;
;	-----------------
J$1BB1:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,08H	; 8 
	LD	DE,I.F7EF
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$1BCA:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	INC	A
	INC	A
	INC	A
	LD	DE,I.F7EF
	CALL	C.18D6
;
	POP	IX
	POP	IY
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$1BE4:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	INC	A
	LD	DE,I.F7EF
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$1BFC:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	XOR	A
	LD	DE,I.F7EF
	CALL	C.18D6
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.1C14:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	B,(IX)
	LD	C,(IX+1)
	LD	D,(IX+2)
	LD	E,(IX+3)
	LD	L,B
	LD	H,00H
	SLA	L
	RL	H
	DEC	HL
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1C37
;
	DEC	HL
J$1C37:	LD	(D.CF1A),HL
	LD	L,C
	LD	H,00H
	LD	A,(D.D46D)
	AND	A
	JR	Z,J$1C49
;
	PUSH	DE
	LD	DE,I.0100
	ADD	HL,DE
	POP	DE
J$1C49:	LD	(D.CF1C),HL
	LD	A,(IX+4)
	LD	(D.CF22),A
	LD	A,(IX+5)
	LD	(D$CF23),A
	LD	A,(IX+6)
	AND	A
	JP	NZ,J$1D6C
;
	LD	A,B
	CP	D
	JR	Z,J.1CB6
;
	LD	A,(IX+7)
	AND	A
	JR	Z,J.1C78
;
	LD	A,B
	INC	A
	CP	D
	JR	Z,J.1CB6
;
	LD	A,B
	DEC	A
	CP	D
	JR	NZ,J.1C78
;
	LD	A,D
	CP	0FFH
	JR	NZ,J.1CB6
;
J.1C78:	LD	A,C
	CP	E
	JR	Z,J.1C8C
;
	LD	A,(IX+7)
	AND	A
	JR	Z,J.1CD7
;
	LD	A,C
	INC	A
	CP	E
	JR	Z,J.1C8C
;
	LD	A,C
	DEC	A
	CP	E
	JR	NZ,J.1CD7
;
J.1C8C:	LD	L,D
	LD	H,00H
	SLA	L
	RL	H
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1C9A
;
	INC	HL
J$1C9A:	LD	DE,(D.CF1A)
	AND	A
	SBC	HL,DE
	INC	HL
	LD	(D.CF1E),HL
	LD	H,00H
	LD	L,01H	; 1 
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1CB1
;
	LD	L,02H	; 2 
J$1CB1:	LD	(D.CF20),HL
	JR	J$1CCE
;
;	-----------------
J.1CB6:	LD	H,00H
	LD	L,02H	; 2 
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1CC2
;
	LD	L,04H	; 4 
J$1CC2:	LD	(D.CF1E),HL
	LD	A,E
	SUB	C
	LD	L,A
	LD	H,00H
	INC	HL
	LD	(D.CF20),HL
J$1CCE:	LD	HL,D.CF1A
	CALL	C.1833
;
	JP	J.1D96
;
;	-----------------
J.1CD7:	LD	HL,I.0002
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1CE3
;
	LD	HL,I.0004
J$1CE3:	LD	(D.CF1E),HL
	LD	A,E
	SUB	C
	LD	L,A
	LD	H,00H
	INC	HL
	LD	(D.CF20),HL
	LD	HL,D.CF1A
	CALL	C.1833
;
	LD	L,D
	LD	H,00H
	SLA	L
	RL	H
	DEC	HL
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1D04
;
	DEC	HL
J$1D04:	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.1833
;
	LD	L,B
	LD	H,00H
	SLA	L
	RL	H
	INC	HL
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1D1C
;
	INC	HL
J$1D1C:	LD	(D.CF1A),HL
	PUSH	DE
	LD	E,D
	LD	D,00H
	SLA	E
	RL	D
	DEC	DE
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1D2F
;
	DEC	DE
J$1D2F:	EX	DE,HL
	AND	A
	SBC	HL,DE
	POP	DE
	LD	(D.CF1E),HL
	LD	H,00H
	LD	L,01H	; 1 
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1D43
;
	LD	L,02H	; 2 
J$1D43:	LD	(D.CF20),HL
	LD	HL,D.CF1A
	CALL	C.1833
;
	LD	L,E
	LD	H,00H
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1D56
;
	DEC	HL
J$1D56:	LD	A,(D.D46D)
	AND	A
	JR	Z,J$1D60
;
	LD	DE,I.0100
	ADD	HL,DE
J$1D60:	LD	(D.CF1C),HL
	LD	HL,D.CF1A
	CALL	C.1833
;
	JP	J.1D96
;
;	-----------------
J$1D6C:	LD	L,D
	LD	H,00H
	SLA	L
	RL	H
	LD	A,(IX+7)
	AND	A
	JR	Z,J$1D7A
;
	DEC	HL
J$1D7A:	PUSH	DE
	LD	DE,(D.CF1A)
	AND	A
	SBC	HL,DE
	POP	DE
	INC	HL
	LD	(D.CF1E),HL
	LD	A,E
	SUB	C
	LD	L,A
	LD	H,00H
	INC	HL
	LD	(D.CF20),HL
	LD	HL,D.CF1A
	CALL	C.1833
;
J.1D96:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$1D9F:	DEFB	0,0,0,0,0,0,0,0,0,0
	CALL	M,C.00FC
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0
	CALL	M,C$FCFC
;
	CALL	M,C.0000
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RET	P
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RET	PO
;
	RET	PO
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$1EDE:	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RET	P
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RET	NZ
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0
	RET	NZ
;
	RET	NZ
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0,0
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0
	RET	P
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0,0
	ADD	A,B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0
	ADD	A,B
	ADD	A,B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0
	CALL	M,C.F8FC
;
	RET	M
;
	RET	P
;
	RET	P
;
	RET	PO
;
	RET	PO
;
	RET	NZ
;
	RET	NZ
;
	ADD	A,B
	ADD	A,B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	CALL	M,C$7CFC
;
	LD	A,H
	INC	A
	INC	A
	INC	E
	INC	E
	INC	C
	INC	C
	INC	B
	INC	B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0
	ADD	A,B
	ADD	A,B
	RET	NZ
;
	RET	NZ
;
	RET	PO
;
	RET	PO
;
	RET	P
;
	RET	P
;
	RET	M
;
	RET	M
;
	CALL	M,C.00FC
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	INC	B
	INC	B
	INC	C
	INC	C
	INC	E
	INC	E
	INC	A
	INC	A
	LD	A,H
	LD	A,H
	CALL	M,C.00FC
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	CP	0FEH
	CALL	M,C.F8FC
;
	RET	M
;
	RET	P
;
	RET	P
;
	RET	PO
;
	RET	PO
;
	RET	NZ
;
	RET	NZ
;
	ADD	A,B
	ADD	A,B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	LD	A,A
	LD	A,A
	CCF	
	CCF	
	RRA	
	RRA	
	RRCA	
	RRCA	
	RLCA	
	RLCA	
	INC	BC
	INC	BC
	LD	BC,I.0001
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	ADD	A,B
	ADD	A,B
	RET	NZ
;
	RET	NZ
;
	RET	PO
;
	RET	PO
;
	RET	P
;
	RET	P
;
	RET	M
;
	RET	M
;
	CALL	M,C.FEFC
;
	CP	0FFH
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	LD	BC,I$0301
	INC	BC
	RLCA	
	RLCA	
	RRCA	
	RRCA	
	RRA	
	RRA	
	CCF	
	CCF	
	LD	A,A
	LD	A,A
	RST	38H
	RST	38H
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
I$20DF:	RET	PO
;
	RET	NZ
;
	ADD	A,B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0
	RET	PO
;
	LD	H,B
	JR	NZ,J$2103
;
J$2103:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0
	ADD	A,B
	RET	NZ
;
	RET	PO
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0
	JR	NZ,J$21A1
;
	RET	PO
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0,0
	LD	B,B
	LD	H,B
	LD	(HL),B
	LD	A,B
	LD	A,H
	LD	A,B
	LD	A,B
	LD	E,B
	INC	C
	INC	C
	LD	B,04H	; 4 
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RET	NZ
;
	RET	PO
;
	RET	P
;
	RET	M
;
	CALL	M,C$FFFE
;
	CP	0FCH
	CALL	M,C$1EDE
;
	RRCA	
	LD	C,04H	; 4 
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J$21A1:	INC	B
	LD	B,0CH	; 12 
	INC	C
	LD	E,B
	LD	A,B
	LD	A,B
	LD	A,H
	LD	A,B
	LD	(HL),B
	LD	H,B
	LD	B,B
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	INC	B
	LD	C,0FH	; 15 
	LD	E,0DEH
	CALL	M,C.FEFC
;
	EI	
	CP	0FCH
	RET	M
;
	RET	P
;
	RET	PO
;
	RET	NZ
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	INC	BC
	LD	BC,I$0F03
	INC	A
	DJNZ	J$21E7
;
J$21E7:	DEFB	0,0,0,0,0,0,0,0,0
	CP	0FCH
	RET	M
;
	RET	P
;
	RET	PO
;
	LD	B,B
	DEFB	0,0,0,0,0,0,0,0,0
	RLCA	
	RLCA	
	INC	BC
	RRCA	
	CCF	
	LD	A,A
	INC	A
	DJNZ	J$2208
;
J$2208:	DEFB	0,0,0,0,0,0,0
	RST	38H
	RST	38H
	CP	0FCH
	RET	M
;
	RET	P
;
	RET	PO
;
	LD	B,B
	DEFB	0,0,0
D$221A:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0
	JR	NZ,J$2293
;
	JR	NC,J$2265
;
	LD	A,(DE)
	LD	E,1EH
	LD	A,1EH
	LD	C,06H	; 6 
	LD	(BC),A
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	JR	NZ,J$22C2
;
	RET	P
;
	LD	A,B
	LD	A,E
	CCF	
	CCF	
	LD	A,A
	RST	38H
	LD	A,A
	CCF	
	RRA	
	RRCA	
	RLCA	
	INC	BC
	RET	M
;
	ADC	A,B
	ADC	A,B
	RET	M
;
	DEFB	0,0
J$2265:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	RET	PO
;
	DEFB	0,0,0,0,0,0,0,0,0,0
J$2293:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	RET	P
;
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	ADD	A,B
	ADD	A,B
	DEFB	0
J$22C2:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0
J$22DF:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	(D.D172),HL
	LD	A,(IX)
	LD	(D.D174),A
	LD	A,(IX+1)
	LD	(D.D175),A
	LD	A,00H
	LD	C,(IX+1)
	LD	B,(IX+2)
	CALL	C.2EDA
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
J$2308:	XOR	A
	LD	(D.D185),A
	LD	(D.D186),A
	LD	(D.D187),A
	LD	(D.D188),A
	LD	(D.D189),A
	LD	HL,(D.D172)
	LD	A,(HL)
	CALL	C.258B
;
	LD	A,(HL)
	INC	HL
	BIT	7,B
I$2322	EQU	$-1
	JR	Z,J$2327
;
	LD	A,20H	; " "
J$2327:	LD	(D.D187),A
	BIT	0,B
	JR	NZ,J$233F
;
	BIT	5,B
	JR	Z,J$2336
;
	CP	0DH	; 13 
	JR	NZ,J.235B
;
J$2336:	BIT	7,B
	JR	NZ,J.235B
;
	LD	A,(HL)
	INC	HL
	LD	(D.D186),A
J$233F:	LD	A,(HL)
	CP	02H	; 2 
	JR	Z,J$2355
;
	CP	03H	; 3 
	JR	NZ,J.235B
;
	INC	HL
	LD	A,(HL)
	LD	(D.D188),A
	INC	HL
	LD	A,(HL)
	LD	(D.D189),A
	INC	HL
	JR	J.235B
;
;	-----------------
J$2355:	INC	HL
	LD	A,(HL)
	LD	(D.D188),A
	INC	HL
J.235B:	LD	(D.D172),HL
	BIT	0,B
	JR	Z,J$236A
;
	LD	A,(D.D188)
	AND	0FH	; 15 
	LD	(D.D188),A
J$236A:	BIT	0,B
	JR	NZ,J.23D6
;
	BIT	5,B
	JR	NZ,J.23D6
;
	BIT	7,B
	JR	NZ,J.23D6
;
	LD	A,(D.D188)
	AND	0F0H
	LD	E,A
	CP	40H	; "@"
	JR	NC,J.23D6
;
	LD	C,00H
	AND	A
	JR	Z,J.23A4
;
	CP	20H	; " "
	JR	Z,J.23A4
;
	LD	A,(IX+2)
	LD	C,0C0H
	LD	HL,D.D47C
	CP	(HL)
	JR	Z,J.239C
;
	LD	HL,D.D47D
	CP	(HL)
	JR	Z,J.239C
;
	LD	C,00H
J.239C:	LD	A,(IX+3)
	AND	C
	LD	(D.D185),A
	LD	C,A
J.23A4:	LD	A,(D.D175)
	LD	HL,I.D47F
	CP	(HL)
	JR	NZ,J$23B8
;
	LD	A,(IX+3)
	RRCA	
	RRCA	
	RRCA	
	AND	07H	; 7 
	OR	C
	JR	J$23D3
;
;	-----------------
J$23B8:	LD	HL,D.D480
	LD	B,(HL)
	PUSH	AF
	LD	A,E
	AND	A
	JR	Z,J.23C7
;
	CP	10H	; 16 
	JR	Z,J.23C7
;
	DEC	B
	DEC	B
J.23C7:	POP	AF
	CP	B
	JR	C,J.23D6
;
	LD	A,(IX+3)
	AND	07H	; 7 
	OR	08H	; 8 
	OR	C
J$23D3:	LD	(D.D185),A
J.23D6:	LD	A,(IX+2)
	LD	HL,D.D47D
	CP	(HL)
	JR	C,J.23F5
;
	LD	A,(IX+3)
	AND	40H	; "@"
	JR	Z,J.23F5
;
	LD	A,(D.D188)
	AND	0F0H
	CP	10H	; 16 
	JR	Z,J.23F5
;
	CP	30H	; "0"
	JR	Z,J.23F5
;
	JR	J$23F8
;
;	-----------------
J.23F5:	CALL	C.2659
;
J$23F8:	LD	A,(D.D174)
	LD	B,A
	LD	A,(D.D175)
	LD	C,A
	LD	DE,CPMADR
	LD	A,(D.D188)
	AND	0F0H
	DEC	B
	INC	C
	CP	40H	; "@"
	JR	NC,J.2458
;
	LD	HL,D.D171
	BIT	0,(HL)
	JR	NZ,J.2458
;
	BIT	5,(HL)
	JR	NZ,J.2458
;
	DEC	B
	INC	C
	LD	DE,I.000C
	AND	A
	JR	Z,J$2425
;
	CP	10H	; 16 
	JR	NZ,J$2433
;
J$2425:	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J.2458
;
	INC	B
	DEC	C
	LD	DE,CPMADR
	JR	J.2458
;
;	-----------------
J$2433:	DEC	B
	DEC	B
	INC	C
	INC	C
	LD	DE,I.0018
	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J.2458
;
	INC	B
	DEC	C
	LD	DE,I.0012
	CP	01H	; 1 
	JR	Z,J.2458
;
	INC	B
	DEC	C
	LD	DE,I.000C
	CP	02H	; 2 
	JR	Z,J.2458
;
	INC	B
	DEC	C
	LD	DE,CPMADR
J.2458:	LD	A,B
	AND	A
	JR	Z,J.2475
;
	LD	(D.D174),A
	LD	A,C
	LD	HL,D.D480
	CP	(HL)
	JR	Z,J$2468
;
	JR	NC,J.2475
;
J$2468:	LD	(D.D175),A
	LD	HL,(D.D18A)
	ADD	HL,DE
	LD	(D.D18A),HL
	JP	J$2308
;
;	-----------------
J.2475:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$247E:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(HL)
	LD	(D.D174),A
	INC	HL
	PUSH	HL
	CALL	C$250F
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
	POP	HL
	INC	HL
	LD	A,(HL)
	LD	(D.D18F),A
	INC	HL
	LD	(D.D172),HL
J$249C:	XOR	A
	LD	(D.D185),A
	LD	(D.D186),A
	LD	(D.D188),A
	LD	(D.D189),A
	LD	HL,(D.D172)
	LD	A,(HL)
	CALL	C.258B
;
	LD	A,(HL)
	INC	HL
	BIT	7,B
	JR	Z,J$24B8
;
	LD	A,20H	; " "
J$24B8:	LD	(D.D187),A
	BIT	0,B
	JR	NZ,J.24DB
;
	BIT	5,B
	JR	Z,J$24C7
;
	CP	0DH	; 13 
	JR	NZ,J.24DB
;
J$24C7:	BIT	7,B
	JR	NZ,J.24DB
;
	LD	A,(HL)
	INC	HL
	LD	(D.D186),A
	LD	A,(HL)
	CP	02H	; 2 
	JR	NZ,J.24DB
;
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	(D.D188),A
J.24DB:	LD	(D.D172),HL
	CALL	C.32E5
;
	LD	A,(D.D174)
	LD	B,A
	DEC	B
	LD	DE,C.0008
	LD	HL,D.D171
	BIT	0,(HL)
	JR	NZ,J.24FA
;
	LD	A,(D.D188)
	OR	A
	JR	NZ,J.24FA
;
	DEC	B
	LD	DE,C.0010
J.24FA:	LD	A,B
	OR	A
	JR	Z,J$250A
;
	LD	(D.D174),A
	LD	HL,(D.D18A)
	ADD	HL,DE
	LD	(D.D18A),HL
	JR	J$249C
;
;	-----------------
J$250A:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$250F:	LD	A,(HL)
	LD	C,A
J$2511:	SUB	40H	; "@"
	JR	NC,J$2511
;
	ADD	A,40H	; "@"
	LD	H,00H
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	PUSH	HL
	LD	A,C
	LD	HL,C.0000
	CP	40H	; "@"
	JR	C,J.2530
;
	LD	HL,I$00AE
	CP	80H
	JR	C,J.2530
;
	LD	HL,I$00C4
J.2530:	LD	A,(D.D46D)
	OR	A
	JR	Z,J$253A
;
	LD	DE,I.0100
	ADD	HL,DE
J$253A:	EX	DE,HL
	POP	HL
	RET	
;
;	-----------------
J$253D:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	(D.D185),A
	LD	(D.D188),HL
	PUSH	DE
	LD	A,03H	; 3 
	CALL	C.2EDA
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
	POP	DE
	XOR	A
	LD	(D.D186),A
	LD	A,D
	CALL	C.258B
;
	LD	A,D
	BIT	7,B
	JR	Z,J$2568
;
	LD	A,20H	; " "
J$2568:	LD	(D.D187),A
	BIT	0,B
	JR	NZ,J.257F
;
	BIT	5,B
	JR	Z,J$2577
;
	CP	0DH	; 13 
	JR	NZ,J.257F
;
J$2577:	BIT	7,B
	JR	NZ,J.257F
;
	LD	A,E
	LD	(D.D186),A
J.257F:	CALL	C.2659
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.258B:	LD	B,20H	; " "
	CP	0DH	; 13 
	JR	Z,J.25DD
;
	CP	0CH	; 12 
	JR	Z,J.25DD
;
	CP	1AH
	JR	Z,J.25DD
;
	CP	1BH
	JR	Z,J.25DD
;
	CP	1CH
	JR	Z,J.25DD
;
	CP	1DH
	JR	Z,J.25DD
;
	CP	1EH
	JR	Z,J.25DD
;
	CP	1FH
	JR	Z,J.25DD
;
	CP	20H	; " "
	JR	C,J$25DB
;
	LD	B,01H	; 1 
	CP	7FH
	JR	C,J.25DD
;
	LD	B,02H	; 2 
	CP	0A0H
	JR	C,J.25DD
;
	LD	B,01H	; 1 
	CP	0E0H
	JR	C,J.25DD
;
	LD	B,02H	; 2 
	CP	0EBH
	JR	C,J.25DD
;
	LD	B,04H	; 4 
	CP	0F0H
	JR	Z,J.25DD
;
	LD	B,08H	; 8 
	CP	0FDH
	JR	Z,J.25DD
;
	LD	B,10H	; 16 
	CP	0FBH
	JR	Z,J.25DD
;
J$25DB:	LD	B,80H
J.25DD:	LD	A,B
	LD	(D.D171),A
	RET	
;
;	-----------------
J$25E2:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	B,(IX+2)
	LD	C,(IX+1)
	XOR	A
	CALL	C.2EDA
;
	LD	A,(D.D46D)
	AND	A
	JR	Z,J$2600
;
	EX	DE,HL
	LD	BC,I.0100
	ADD	HL,BC
	EX	DE,HL
J$2600:	PUSH	HL
	PUSH	DE
	LD	A,00H
	LD	(D.D191),A
	LD	A,07H	; 7 
	LD	(D.D190),A
	LD	DE,I$2650
	LD	B,09H	; 9 
	LD	HL,I.CF29
J$2614:	LD	A,(DE)
	CALL	C.29BE
;
	INC	DE
	DJNZ	J$2614
;
	POP	DE
	LD	(D.CF1C),DE
	LD	HL,CPMADR
	LD	(D.CF1E),HL
	LD	HL,I.000C
	LD	(D.CF20),HL
	LD	HL,I.CF29
	LD	(D.CF22),HL
	LD	B,(IX)
	POP	HL
J$2636:	LD	(D.CF1A),HL
	PUSH	HL
	LD	HL,D.CF1A
	CALL	C.167B
;
	POP	HL
	LD	DE,CPMADR
	ADD	HL,DE
	DJNZ	J$2636
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$2650:	CP	1BH
	LD	L,L
	OR	(HL)
	IN	A,(6DH)
	OR	(HL)
	RET	C
;
	LD	A,A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.2659:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	BC,(D.D186)
	CALL	C.275F
;
	LD	A,(D.D18F)
	AND	0FH	; 15 
	LD	B,A
	LD	A,(D.D171)
	BIT	5,A
	JR	Z,J$2679
;
	LD	B,01H	; 1 
	JR	J.2693
;
;	-----------------
J$2679:	BIT	7,A
	JR	Z,J$2684
;
	LD	A,01H	; 1 
	LD	(D.D171),A
	JR	J.2693
;
;	-----------------
J$2684:	LD	A,(D.D188)
	AND	0CH	; 12 
	JR	NZ,J$2691
;
	LD	A,(D.D189)
	AND	A
	JR	Z,J.2693
;
J$2691:	LD	B,06H	; 6 
J.2693:	LD	A,B
	LD	(D.D190),A
	LD	A,(D.D18F)
	LD	B,A
	LD	A,(D.D171)
	BIT	5,A
	JR	Z,J$26A9
;
	LD	B,0F0H
	LD	A,01H	; 1 
	LD	(D.D171),A
J$26A9:	LD	A,B
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	AND	0FH	; 15 
	LD	(D.D191),A
	LD	B,00H
	CALL	C.26D5
;
	CALL	C$2D48
;
	LD	A,(D.D188)
	AND	03H	; 3 
	JR	Z,J.26CC
;
	LD	A,(D.D185)
	AND	40H	; "@"
	JR	NZ,J.26CC
;
	CALL	C$2DC4
;
J.26CC:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.26D5:	LD	A,(D.D188)
	AND	0F0H
	JR	NZ,J$26F8
;
	LD	A,B
	AND	A
	JR	Z,J$26F3
;
	LD	A,(D.D171)
	BIT	0,A
	JR	Z,J$26EE
;
	LD	A,(D.D189)
	AND	0FCH
	JR	NZ,J$2736
;
J$26EE:	CALL	C$3886
;
	JR	J.275E
;
;	-----------------
J$26F3:	CALL	C$2C49
;
	JR	J.275E
;
;	-----------------
J$26F8:	CP	10H	; 16 
	JR	NZ,J$270A
;
	LD	A,B
	AND	A
	JR	Z,J$2705
;
	CALL	C$3672
;
	JR	J.275E
;
;	-----------------
J$2705:	CALL	C$29ED
;
	JR	J.275E
;
;	-----------------
J$270A:	CP	20H	; " "
	JR	NZ,J$271C
;
	LD	A,B
	AND	A
	JR	Z,J$2717
;
	CALL	C$36D0
;
	JR	J.275E
;
;	-----------------
J$2717:	CALL	C$2A39
;
	JR	J.275E
;
;	-----------------
J$271C:	CP	30H	; "0"
	JR	NZ,J$272E
;
	LD	A,B
	AND	A
	JR	Z,J$2729
;
	CALL	C$3749
;
	JR	J.275E
;
;	-----------------
J$2729:	CALL	C$2A9B
;
	JR	J.275E
;
;	-----------------
J$272E:	CP	40H	; "@"
	JR	NZ,J$2740
;
	LD	A,B
	AND	A
	JR	Z,J$273B
;
J$2736:	CALL	C$3864
;
	JR	J.275E
;
;	-----------------
J$273B:	CALL	C$2C27
;
	JR	J.275E
;
;	-----------------
J$2740:	CP	80H
	JR	NZ,J$2752
;
	LD	A,B
	AND	A
	JR	Z,J$274D
;
	CALL	C$37F2
;
	JR	J.275E
;
;	-----------------
J$274D:	CALL	C$2BB5
;
	JR	J.275E
;
;	-----------------
J$2752:	LD	A,B
	AND	A
	JR	Z,J$275B
;
	CALL	C$382B
;
	JR	J.275E
;
;	-----------------
J$275B:	CALL	C$2BEE
;
J.275E:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.275F:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	PUSH	BC
	LD	HL,I.D129
	LD	DE,I.D12A
	LD	BC,I.0011
	LD	(HL),00H
	LDIR	
	POP	BC
	LD	A,(D.D171)
	BIT	2,A
	JR	NZ,J$279A
;
	BIT	5,A
	JP	NZ,J$27AA
;
	CALL	C$27CD
;
	JR	NC,J.27C4
;
	CALL	C.335A
;
	LD	HL,I.D129
	LD	DE,I.CF29
	LD	BC,I.0020
	LDIR	
	CALL	C$281A
;
	JR	J.27C4
;
;	-----------------
J$279A:	LD	HL,I.D1BD
	CALL	C.0C49
;
	JR	C,J$27A8
;
	LD	BC,I.D1BD
	CALL	C$2F43
;
J$27A8:	JR	J.27C4
;
;	-----------------
J$27AA:	LD	A,B
	LD	HL,I$2FA4
	CP	0CH	; 12 
	JR	Z,J.27BC
;
	LD	HL,I$2F92
	CP	0DH	; 13 
	JR	Z,J.27BC
;
	LD	HL,I$2FB6
J.27BC:	LD	DE,I.D129
	LD	BC,I.0012
	LDIR	
J.27C4:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$27CD:	PUSH	BC
	LD	A,(D.D49D)
	AND	03H			; 12x12 JIS ROM ?
	JR	Z,J.2817		; nope, quit with error
	LD	A,(D.D171)
	BIT	0,A
	JP	NZ,J.27FE
	BIT	1,A
	JP	NZ,J$27EC
	BIT	3,A
	JR	NZ,J.27FE
	BIT	4,A
	JR	NZ,J.27FE
	JR	J.2817			; quit with error

J$27EC:	LD	A,B
	CP	0E0H
	JR	NC,J.280A
	CP	99H
	JR	NC,J.280A
	CP	98H
	JR	C,J.27FE
	LD	A,C
	CP	9FH
	JR	NC,J.280A
J.27FE:	LD	A,(D.D49D)
	AND	01H			; 12x12 JIS1 ROM ?
	JR	Z,J.2817		; nope, quit with error
	CALL	C.0D49
	JR	J$2814
;
;	-----------------
J.280A:	LD	A,(D.D49D)
	AND	02H			; 12x12 JIS2 ROM ?
	JR	Z,J.2817		; nope, quit with error
	CALL	C.0D49
J$2814:	POP	BC
	AND	A
	RET	
;
;	-----------------
J.2817:	POP	BC
	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$281A:	LD	HL,I.CF31
	LD	DE,I.CF49
	LD	BC,C.0008
	LDIR	
	LD	HL,I.CF39
	LD	DE,I.CF31
	LD	BC,C.0008
	LDIR	
	LD	HL,I.CF49
	LD	DE,I.CF39
	LD	BC,C.0008
	LDIR	
	LD	HL,I.CF29
	LD	DE,I.CF49
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	LD	B,08H	; 8 
J$2847:	LD	A,(HL)
	INC	HL
	OR	(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DJNZ	J$2847
;
	LD	HL,I.CF49
	LD	IX,I$CF55
	LD	DE,I.CF61
	LD	B,0CH	; 12 
J$2863:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	LD	A,(IX)
	LD	(DE),A
	INC	DE
	INC	IX
	DJNZ	J$2863
;
	LD	HL,I.CF79
	LD	DE,I$CF7A
	LD	(HL),00H
	LD	BC,I.0011
	LDIR	
	LD	IX,I.28D4
	LD	HL,I.CF61
	LD	DE,I.CF79
	LD	B,06H	; 6 
J$2889:	PUSH	BC
	LD	C,(HL)
	LD	B,08H	; 8 
	CALL	C.28C6
;
	INC	HL
	LD	C,(HL)
	LD	B,03H	; 3 
	CALL	C.28C6
;
	INC	DE
	LD	B,05H	; 5 
	CALL	C.28C6
;
	INC	HL
	LD	C,(HL)
	LD	B,05H	; 5 
	CALL	C.28C6
;
	INC	DE
	LD	B,03H	; 3 
	CALL	C.28C6
;
	INC	HL
	LD	C,(HL)
	LD	B,08H	; 8 
	CALL	C.28C6
;
	INC	DE
	INC	HL
	LD	IX,I.28D4
	POP	BC
	DJNZ	J$2889
;
	LD	HL,I.CF79
	LD	DE,I.D129
	LD	BC,I.0012
	LDIR	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.28C6:	RLC	C
	JR	NC,J$28CF
;
	LD	A,(DE)
	OR	(IX)
	LD	(DE),A
J$28CF:	INC	IX
	DJNZ	C.28C6
;
	RET	
;
;	-----------------
I.28D4:	ADD	A,B
	LD	B,B
	LD	B,B
	JR	NZ,J$28E9
;
	EX	AF,AF'
	EX	AF,AF'
	INC	B
	LD	(BC),A
	LD	BC,I$8001
	LD	B,B
	JR	NZ,J$2903
;
	DJNZ	J$28ED
;
	INC	B
	INC	B
	LD	(BC),A
	LD	BC,I$8080
J$28E9	EQU	$-2
	LD	B,B
	JR	NZ,J$28FE
J$28ED	EQU	$-1
;
	DJNZ	J$28F8
;
	INC	B
	LD	(BC),A
	LD	(BC),A
	LD	BC,I.C5F5
J$28F4	EQU	$-2
	PUSH	DE
	PUSH	HL
J$28F8:	PUSH	IX
	PUSH	IY
	CALL	C.335A
J$28FE	EQU	$-1
;
	LD	HL,I.D129
	LD	DE,I.CF29
J$2903	EQU	$-2
	LD	BC,I.0020
	LDIR	
	CALL	C$2916
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2916:	LD	HL,I.CF39
	LD	DE,I.CF31
	LD	BC,C.0008
	LDIR	
	LD	HL,I.CF29
	LD	DE,I.CF49
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	LD	B,04H	; 4 
J$292D:	LD	A,(HL)
	INC	HL
	OR	(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DJNZ	J$292D
;
	LD	HL,I.CF49
	LD	DE,I.D129
	LD	B,06H	; 6 
J$2945:	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	LD	A,(HL)
	PUSH	AF
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	AND	0FH	; 15 
	LD	(DE),A
	INC	DE
	POP	AF
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0F0H
	LD	(DE),A
	INC	DE
	INC	HL
	DJNZ	J$2945
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.2960:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	C,A
	LD	B,02H	; 2 
J$2966:	AND	A
	RLC	C
	JR	C,J$2970
;
	LD	A,(D.D190)
	JR	J$2973
;
;	-----------------
J$2970:	LD	A,(D.D191)
J$2973:	AND	A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	D,A
	AND	A
	RLC	C
	JR	C,J$2983
;
	LD	A,(D.D190)
	JR	J$2986
;
;	-----------------
J$2983:	LD	A,(D.D191)
J$2986:	OR	D
	LD	(HL),A
	INC	HL
	DJNZ	J$2966
;
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.298F:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	C,A
	LD	B,03H	; 3 
J$2995:	AND	A
	RLC	C
	JR	C,J$299F
;
	LD	A,(D.D190)
	JR	J$29A2
;
;	-----------------
J$299F:	LD	A,(D.D191)
J$29A2:	AND	A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	D,A
	AND	A
	RLC	C
	JR	C,J$29B2
;
	LD	A,(D.D190)
	JR	J$29B5
;
;	-----------------
J$29B2:	LD	A,(D.D191)
J$29B5:	OR	D
	LD	(HL),A
	INC	HL
	DJNZ	J$2995
;
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.29BE:	PUSH	AF
	PUSH	BC
	PUSH	DE
	LD	C,A
	LD	B,04H	; 4 
J$29C4:	AND	A
	RLC	C
	JR	C,J$29CE
;
	LD	A,(D.D190)
	JR	J$29D1
;
;	-----------------
J$29CE:	LD	A,(D.D191)
J$29D1:	AND	A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	LD	D,A
	AND	A
	RLC	C
	JR	C,J$29E1
;
	LD	A,(D.D190)
	JR	J$29E4
;
;	-----------------
J$29E1:	LD	A,(D.D191)
J$29E4:	OR	D
	LD	(HL),A
	INC	HL
	DJNZ	J$29C4
;
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$29ED:	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,06H	; 6 
J$29F6:	PUSH	BC
	LD	A,(IX)
	CALL	C.29BE
;
	LD	A,(IX+1)
	CALL	C.2960
;
	LD	A,(IX)
	CALL	C.29BE
;
	LD	A,(IX+1)
	CALL	C.2960
;
	LD	A,(IX+1)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	CALL	C.2960
;
	LD	A,(IX+2)
D$2A1A	EQU	$-2
	CALL	C.29BE
;
	LD	A,(IX+1)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	CALL	C.2960
;
	LD	A,(IX+2)
	CALL	C.29BE
;
	INC	IX
	INC	IX
	INC	IX
	POP	BC
	DJNZ	J$29F6
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2A39:	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,12H	; 18 
J$2A42:	PUSH	BC
	LD	A,(IX)
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	LD	A,(IX)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	INC	IX
	POP	BC
	DJNZ	J$2A42
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2A9B:	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,06H	; 6 
J$2AA4:	PUSH	BC
	LD	B,02H	; 2 
J$2AA7:	PUSH	BC
	LD	A,(IX)
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	LD	A,(IX)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	LD	A,(IX+1)
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	POP	BC
	DJNZ	J$2AA7
;
	LD	B,02H	; 2 
J$2B26:	PUSH	BC
	LD	A,(IX+1)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	LD	A,(IX+2)
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	LD	A,(IX+2)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	POP	BC
	DEC	B
	JP	NZ,J$2B26
;
	INC	IX
	INC	IX
	INC	IX
	POP	BC
	DEC	B
	JP	NZ,J$2AA4
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2BB5:	CALL	C.2CC7
;
	LD	HL,I.CF29
	LD	DE,I.D129
	LD	B,06H	; 6 
J$2BC0:	LD	A,(HL)
	INC	HL
	LD	C,(HL)
	OR	C
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$2BC0
;
	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,06H	; 6 
J$2BD2:	LD	A,(IX)
	CALL	C.298F
;
	INC	IX
	DJNZ	J$2BD2
;
	LD	A,(D.D190)
	LD	B,A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0F0H
	OR	B
	LD	B,12H	; 18 
J$2BE9:	LD	(HL),A
	INC	HL
	DJNZ	J$2BE9
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2BEE:	CALL	C.2CC7
;
	LD	HL,I.CF29
	LD	DE,I.D129
	LD	B,06H	; 6 
J$2BF9:	LD	A,(HL)
	INC	HL
	LD	C,(HL)
	OR	C
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$2BF9
;
	LD	IX,I.D129
	LD	HL,I.CF29
	LD	A,(D.D190)
	LD	B,A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0F0H
	OR	B
	LD	B,12H	; 18 
J$2C16:	LD	(HL),A
	INC	HL
	DJNZ	J$2C16
;
	LD	B,06H	; 6 
J$2C1C:	LD	A,(IX)
	CALL	C.298F
;
	INC	IX
	DJNZ	J$2C1C
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2C27:	CALL	C.2CC7
;
	LD	HL,I.CF29
	LD	DE,I.D129
	LD	BC,I.000C
	LDIR	
	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,0CH	; 12 
J$2C3E:	LD	A,(IX)
	CALL	C.298F
;
	INC	IX
	DJNZ	J$2C3E
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2C49:	LD	A,(D.D171)
	AND	01H	; 1 
	JR	Z,J$2CB3
;
	LD	A,(D.D48A)
	AND	A
	JR	Z,J.2C6D
	LD	A,(D.D49D)
	AND	01H			; 12x12 JIS1 ROM ?
	JR	Z,J.2C6D		; nope,
D$2C5D:	LD	A,(D.D187)
	CP	0A0H
	JR	C,J.2C6D
	CP	0E0H
	JR	NC,J.2C6D
	CALL	C.2CC7
	JR	J$2C93
;
;	-----------------
J.2C6D:	LD	HL,I.D129
	LD	DE,I.CF29
	LD	B,06H	; 6 
J$2C75:	PUSH	BC
	LD	A,(HL)
	AND	0FCH
	LD	(DE),A
	INC	HL
	INC	DE
	LD	A,(HL)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0F0H
	LD	B,A
	INC	HL
	LD	A,(HL)
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	AND	0CH	; 12 
	OR	B
	LD	(DE),A
	INC	HL
	INC	DE
	POP	BC
	DJNZ	J$2C75
;
J$2C93:	LD	HL,I.CF29
	LD	DE,I.D129
	LD	BC,I.000C
	LDIR	
D$2C9D	EQU	$-1
	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,0CH	; 12 
J$2CA7:	LD	A,(IX)
	CALL	C.298F
;
	INC	IX
	DJNZ	J$2CA7
;
	JR	J$2CC6
;
;	-----------------
J$2CB3:	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,12H	; 18 
J$2CBC:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	DJNZ	J$2CBC
;
J$2CC6:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.2CC7:	LD	IX,I.D129
	LD	IY,I.CF29
	LD	B,06H	; 6 
J$2CD1:	LD	A,(IX)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,(IX+1)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,E
	OR	C
	SLA	A
	SLA	A
	LD	(IY),A
	LD	A,(IX+1)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,(IX+2)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,E
	OR	C
	SLA	A
	SLA	A
	LD	(IY+1),A
	INC	IX
	INC	IX
	INC	IX
	INC	IY
	INC	IY
	DJNZ	J$2CD1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2D48:	LD	HL,(D.D18C)
	LD	A,(D.D188)
	AND	0F0H
	CP	10H	; 16 
	JR	Z,J$2D58
;
	CP	30H	; "0"
	JR	NZ,J$2D5E
;
J$2D58:	LD	DE,I.000C
	AND	A
	SBC	HL,DE
J$2D5E:	LD	DE,(D.D18A)
	LD	A,(D.D185)
	AND	0C7H
	JR	Z,J$2D6F
;
	LD	DE,C.0000
	LD	HL,I.01E0
J$2D6F:	LD	(D.CF1A),DE
	LD	(D.CF1C),HL
	LD	A,(D.D171)
	AND	01H	; 1 
	JR	NZ,J$2D90
;
	LD	HL,I.000C
	LD	A,(D.D188)
	AND	0F0H
	CP	20H	; " "
	JR	C,J.2D93
;
	LD	HL,I.0018
	CP	40H	; "@"
	JR	C,J.2D93
;
J$2D90:	LD	HL,CPMADR
J.2D93:	LD	(D.CF1E),HL
	LD	HL,I.0018
	CP	10H	; 16 
	JR	Z,J.2DA4
;
	CP	30H	; "0"
	JR	Z,J.2DA4
;
	LD	HL,I.000C
J.2DA4:	LD	(D.CF20),HL
	LD	HL,I.CF29
	LD	(D.CF22),HL
	LD	HL,D.CF1A
	CALL	C.167B
;
	LD	A,(D.D185)
	AND	0C7H
	JR	Z,J$2DC3
;
	CALL	C$2E21
;
	LD	HL,D.CF1A
	CALL	C.16EB
;
J$2DC3:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2DC4:	LD	HL,(D.D18A)
	LD	(D.CF1A),HL
	LD	HL,(D.D18C)
	LD	DE,I.000C
	ADD	HL,DE
	LD	(D.CF1C),HL
	LD	HL,I.000C
	LD	A,(D.D171)
	BIT	0,A
	JR	NZ,J$2DEE
;
	LD	A,(D.D188)
	AND	0F0H
	CP	20H	; " "
	JR	C,J.2DF1
;
	LD	HL,I.0018
	CP	40H	; "@"
	JR	C,J.2DF1
;
J$2DEE:	LD	HL,CPMADR
J.2DF1:	LD	(D.CF1E),HL
	LD	HL,I.0001
	LD	(D.CF20),HL
	LD	A,00H
	LD	(D.CF22),A
	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J$2E1A
;
	LD	HL,I.0012
	CP	01H	; 1 
	JR	Z,J.2E17
;
	LD	HL,I.000C
	CP	02H	; 2 
	JR	Z,J.2E17
;
	LD	HL,CPMADR
J.2E17:	LD	(D.CF1E),HL
J$2E1A:	LD	HL,D.CF1A
	CALL	C.172A
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$2E21:	LD	HL,C.0000
	LD	(D.CF1A),HL
	LD	HL,I.01E0
	LD	(D.CF1C),HL
	LD	HL,(D.D18A)
	LD	(D.CF1E),HL
	LD	A,(D.D188)
	AND	0F0H
	LD	HL,(D.D18C)
	CP	10H	; 16 
	JR	Z,J$2E43
;
	CP	30H	; "0"
	JR	NZ,J$2E49
;
J$2E43:	LD	DE,I.000C
	AND	A
	SBC	HL,DE
J$2E49:	LD	(D.CF20),HL
	LD	HL,I.000C
	LD	DE,I.000C
	AND	0F0H
	JR	Z,J.2E6A
;
	LD	DE,I.0018
	CP	10H	; 16 
	JR	Z,J.2E6A
;
	LD	HL,I.0018
	LD	DE,I.000C
	CP	20H	; " "
	JR	Z,J.2E6A
;
	LD	DE,I.0018
J.2E6A:	LD	(D.CF22),HL
	LD	(D.CF24),DE
	XOR	A
	LD	(D.CF26),A
	LD	A,(D.D185)
	AND	0C0H
	JR	Z,J$2E98
;
	LD	DE,(D.D18C)
	AND	40H	; "@"
	JR	NZ,J$2E8C
;
	LD	HL,I$01EC
	LD	(D.CF1C),HL
	JR	J$2E8E
;
;	-----------------
J$2E8C:	INC	DE
	INC	DE
J$2E8E:	LD	HL,I.000C
	LD	(D.CF24),HL
	LD	(D.CF20),DE
J$2E98:	LD	A,(D.D185)
	LD	B,A
	AND	07H	; 7 
	JR	Z,J.2ED9
;
	LD	HL,CPMADR
	LD	DE,I.0012
	CP	01H	; 1 
	JR	Z,J.2EC8
;
	LD	HL,I.000C
	LD	DE,I.000C
	CP	02H	; 2 
	JR	Z,J.2EC8
;
	LD	HL,CPMADR
	LD	A,(D.D188)
	AND	0F0H
	JR	Z,J.2EC5
;
	CP	10H	; 16 
	JR	Z,J.2EC5
;
	LD	HL,I.0012
J.2EC5:	LD	DE,CPMADR
J.2EC8:	BIT	3,B
	JR	Z,J$2ED2
;
	EX	DE,HL
	LD	(D.CF22),HL
	JR	J.2ED9
;
;	-----------------
J$2ED2:	LD	(D.CF1A),HL
	LD	(D.CF22),DE
J.2ED9:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.2EDA:	PUSH	AF
	PUSH	BC
	PUSH	IX
	AND	0FH	; 15 
	SLA	A
	LD	E,A
	LD	D,00H
	LD	HL,I$2F19
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	PUSH	DE
	POP	IX
	LD	E,B
	LD	B,(IX)
	LD	D,00H
	LD	HL,C.0000
J$2EF8:	ADD	HL,DE
	DJNZ	J$2EF8
;
	LD	E,(IX+1)
	ADD	HL,DE
	PUSH	HL
	LD	E,C
	LD	B,(IX+2)
	LD	D,00H
	LD	HL,C.0000
J$2F09:	ADD	HL,DE
	DJNZ	J$2F09
;
	LD	E,(IX+3)
	LD	D,(IX+4)
	ADD	HL,DE
	POP	DE
	POP	IX
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$2F19:	DEC	H
	CPL	
	LD	HL,(D$2F2F)
	CPL	
	INC	(HL)
	CPL	
	ADD	HL,SP
	CPL	
	LD	A,2FH	; "/"
	LD	C,13H	; 19 
	LD	B,04H	; 4 
	NOP	
	INC	DE
D.2F2B:	LD	(DE),A
	EX	AF,AF'
	EX	AF,AF'
	NOP	
D$2F2F:	LD	(BC),A
	JR	NZ,J$2F34
;
	LD	C,B
	NOP	
J$2F34:	LD	C,0EH	; 14 
	LD	B,04H	; 4 
	NOP	
	LD	A,(DE)
	JR	C,J$2F44
;
	LD	A,B
	NOP	
	LD	A,(DE)
	JR	C,J$2F49
;
	LD	E,(HL)
	LD	BC,I.C5F5
C$2F43	EQU	$-2
J$2F44	EQU	$-1
	PUSH	DE
	PUSH	HL
	PUSH	IX
J$2F49:	PUSH	BC
	POP	IX
	LD	HL,I.D129
	LD	D,03H	; 3 
	LD	E,01H	; 1 
	LD	B,03H	; 3 
J$2F55:	PUSH	BC
	LD	B,04H	; 4 
J$2F58:	PUSH	BC
	PUSH	IX
	LD	B,0CH	; 12 
J$2F5D:	LD	A,(IX)
	OR	(IX+3)
	AND	D
	JR	Z,J$2F67
;
	SCF	
J$2F67:	RL	E
	JR	NC,J$2F6F
;
	LD	(HL),E
	LD	E,01H	; 1 
	INC	HL
J$2F6F:	INC	IX
	INC	IX
	INC	IX
	INC	IX
	INC	IX
	INC	IX
	DJNZ	J$2F5D
;
	RLC	D
	RLC	D
	POP	IX
	POP	BC
	DJNZ	J$2F58
;
	INC	IX
	POP	BC
	DJNZ	J$2F55
;
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$2F92:	DEFB	0,0
	ADD	A,B
	EX	AF,AF'
	NOP	
	ADD	A,B
	EX	AF,AF'
	NOP	
	ADD	A,B
	EX	AF,AF'
	NOP	
	ADD	A,B
	JR	Z,J$2FA6
;
	ADD	A,B
	RET	M
;
	DEFB	0,0
I$2FA4:	DEFB	0
	RRCA	
J$2FA6:	RET	NZ
;
	JR	NC,J$2FAC
;
	NOP	
	JR	NC,J$2FAF
;
J$2FAC:	NOP	
	JR	NC,J$2FB2
;
J$2FAF:	NOP	
	OR	H
	RLCA	
J$2FB2:	ADD	A,B
	JR	NC,J$2FB5
;
J$2FB5:	DEFB	0
I$2FB6:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.2FC8:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	(D.D172),HL
	LD	A,(IX)
	LD	(D.D174),A
	LD	A,(IX+1)
	LD	(D.D175),A
	LD	A,01H	; 1 
	LD	C,(IX+1)
	LD	B,(IX+2)
	CALL	C.2EDA
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
J$2FF1:	XOR	A
	LD	(D.D185),A
	LD	(D.D186),A
	LD	(D.D187),A
	LD	(D.D188),A
	LD	(D.D189),A
	LD	HL,(D.D172)
	LD	A,(HL)
	CALL	C.258B
;
	LD	A,(HL)
	INC	HL
	BIT	7,B
	JR	Z,J$3010
;
	LD	A,20H	; " "
J$3010:	LD	(D.D187),A
	BIT	0,B
	JR	NZ,J$3028
;
	BIT	5,B
	JR	Z,J$301F
;
	CP	0DH	; 13 
	JR	NZ,J.3044
;
J$301F:	BIT	7,B
	JR	NZ,J.3044
;
	LD	A,(HL)
	INC	HL
	LD	(D.D186),A
J$3028:	LD	A,(HL)
	CP	02H	; 2 
	JR	Z,J$303E
;
	CP	03H	; 3 
	JR	NZ,J.3044
;
	INC	HL
	LD	A,(HL)
	LD	(D.D188),A
	INC	HL
	LD	A,(HL)
	LD	(D.D189),A
	INC	HL
	JR	J.3044
;
;	-----------------
J$303E:	INC	HL
	LD	A,(HL)
	LD	(D.D188),A
	INC	HL
J.3044:	LD	(D.D172),HL
	BIT	0,B
	JR	Z,J$3053
;
	LD	A,(D.D188)
	AND	0FH	; 15 
	LD	(D.D188),A
J$3053:	BIT	0,B
	JR	NZ,J.30BF
;
	BIT	5,B
	JR	NZ,J.30BF
;
	BIT	7,B
	JR	NZ,J.30BF
;
	LD	A,(D.D188)
	AND	0F0H
	LD	E,A
	CP	40H	; "@"
	JR	NC,J.30BF
;
	LD	C,00H
	AND	A
	JR	Z,J.308D
;
	CP	20H	; " "
	JR	Z,J.308D
;
	LD	A,(IX+2)
	LD	C,0C0H
	LD	HL,D.D47C
	CP	(HL)
	JR	Z,J.3085
;
	LD	HL,D.D47D
	CP	(HL)
	JR	Z,J.3085
;
	LD	C,00H
J.3085:	LD	A,(IX+3)
	AND	C
	LD	(D.D185),A
	LD	C,A
J.308D:	LD	A,(D.D175)
	LD	HL,I.D47F
	CP	(HL)
	JR	NZ,J$30A1
;
	LD	A,(IX+3)
	RRCA	
	RRCA	
	RRCA	
	AND	07H	; 7 
	OR	C
	JR	J$30BC
;
;	-----------------
J$30A1:	LD	HL,D.D480
	LD	B,(HL)
	PUSH	AF
	LD	A,E
	AND	A
	JR	Z,J.30B0
;
	CP	10H	; 16 
	JR	Z,J.30B0
;
	DEC	B
	DEC	B
J.30B0:	POP	AF
	CP	B
	JR	C,J.30BF
;
	LD	A,(IX+3)
	AND	07H	; 7 
	OR	08H	; 8 
	OR	C
J$30BC:	LD	(D.D185),A
J.30BF:	LD	A,(IX+2)
	LD	HL,D.D47D
	CP	(HL)
	JR	NZ,J.30DE
;
	LD	A,(IX+3)
	AND	40H	; "@"
	JR	Z,J.30DE
;
	LD	A,(D.D188)
	AND	0F0H
	CP	10H	; 16 
	JR	Z,J.30DE
;
	CP	30H	; "0"
	JR	Z,J.30DE
;
	JR	J$30E1
;
;	-----------------
J.30DE:	CALL	C.32E5
;
J$30E1:	CALL	C$3AD1
;
	LD	A,(D.D174)
	LD	B,A
	LD	A,(D.D175)
	LD	C,A
	LD	DE,C.0008
	LD	A,(D.D188)
	AND	0F0H
	DEC	B
	INC	C
	CP	40H	; "@"
	JR	NC,J.3144
;
	LD	HL,D.D171
	BIT	0,(HL)
	JR	NZ,J.3144
;
	BIT	5,(HL)
	JR	NZ,J.3144
;
	DEC	B
	INC	C
	LD	DE,C.0010
	AND	A
	JR	Z,J$3111
;
	CP	10H	; 16 
	JR	NZ,J$311F
;
J$3111:	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J.3144
;
	INC	B
	DEC	C
	LD	DE,C.0008
	JR	J.3144
;
;	-----------------
J$311F:	DEC	B
	DEC	B
	INC	C
	INC	C
	LD	DE,I.0020
	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J.3144
;
	INC	B
	DEC	C
	LD	DE,I.0018
	CP	01H	; 1 
	JR	Z,J.3144
;
	INC	B
	DEC	C
	LD	DE,C.0010
	CP	02H	; 2 
	JR	Z,J.3144
;
	INC	B
	DEC	C
	LD	DE,C.0008
J.3144:	LD	A,B
	AND	A
	JR	Z,J.3161
;
	LD	(D.D174),A
	LD	A,C
	LD	HL,D.D480
	CP	(HL)
	JR	Z,J$3154
;
	JR	NC,J.3161
;
J$3154:	LD	(D.D175),A
	LD	HL,(D.D18A)
	ADD	HL,DE
	LD	(D.D18A),HL
	JP	J$2FF1
;
;	-----------------
J.3161:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$316A:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,(HL)
	INC	HL
	LD	(D.D174),A
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	PUSH	HL
	LD	A,01H	; 1 
	CALL	C.2EDA
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
	POP	HL
J$3189:	LD	A,(HL)
	LD	(D.D18F),A
	INC	HL
	LD	(D.D172),HL
J$3191:	XOR	A
	LD	(D.D185),A
	LD	(D.D186),A
	LD	(D.D188),A
	LD	(D.D189),A
	LD	HL,(D.D172)
	LD	A,(HL)
	CALL	C.258B
;
	LD	A,(HL)
	INC	HL
	BIT	7,B
	JR	Z,J$31AD
;
	LD	A,20H	; " "
J$31AD:	LD	(D.D187),A
	BIT	0,B
	JR	NZ,J.31C5
;
	BIT	5,B
	JR	Z,J$31BC
;
	CP	0DH	; 13 
	JR	NZ,J.31C5
;
J$31BC:	BIT	7,B
	JR	NZ,J.31C5
;
	LD	A,(HL)
	INC	HL
	LD	(D.D186),A
J.31C5:	LD	(D.D172),HL
	CALL	C.32E5
;
	LD	A,(D.D174)
	DEC	A
	LD	DE,C.0008
	LD	HL,D.D171
	BIT	0,(HL)
	JR	NZ,J$31DD
;
	DEC	A
	LD	DE,C.0010
J$31DD:	AND	A
	JR	Z,J$31ED
;
	LD	(D.D174),A
	LD	HL,(D.D18A)
	ADD	HL,DE
	LD	(D.D18A),HL
	JP	J$3191
;
;	-----------------
J$31ED:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$31F6:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	PUSH	AF
	LD	A,(HL)
	INC	HL
	LD	(D.D174),A
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	POP	AF
	PUSH	HL
	CALL	C.2EDA
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
	POP	HL
	JP	J$3189
;
;	-----------------
J$3218:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	B,(IX+2)
	LD	C,(IX+1)
	LD	A,01H	; 1 
	CALL	C.2EDA
;
	LD	A,(D.D46D)
	AND	A
	JR	Z,J$3237
;
	EX	DE,HL
	LD	BC,I.0100
	ADD	HL,BC
	EX	DE,HL
J$3237:	PUSH	HL
	PUSH	DE
	LD	A,00H
	LD	(D.D191),A
	LD	A,07H	; 7 
	LD	(D.D190),A
	LD	DE,I$3287
	LD	B,10H	; 16 
	LD	HL,I.CF29
J$324B:	LD	A,(DE)
	CALL	C.29BE
;
	INC	DE
	DJNZ	J$324B
;
	POP	DE
	LD	(D.CF1C),DE
	LD	HL,C.0008
	LD	(D.CF1E),HL
	LD	HL,C.0010
	LD	(D.CF20),HL
	LD	HL,I.CF29
	LD	(D.CF22),HL
	LD	B,(IX)
	POP	HL
J$326D:	LD	(D.CF1A),HL
	PUSH	HL
	LD	HL,D.CF1A
	CALL	C.167B
;
	POP	HL
	LD	DE,C.0008
	ADD	HL,DE
	DJNZ	J$326D
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$3287:	RST	38H
	ADD	A,C
	ADD	A,C
	CP	L
	SBC	A,C
	SBC	A,C
	SBC	A,C
	SBC	A,C
	SBC	A,C
	SBC	A,C
	SBC	A,C
	SBC	A,C
	CP	L
	ADD	A,C
	ADD	A,C
	RST	38H
J$3297:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	(D.D185),A
	LD	(D.D188),HL
	PUSH	DE
	LD	A,01H	; 1 
	CALL	C.2EDA
;
	LD	(D.D18A),HL
	LD	(D.D18C),DE
	POP	DE
	XOR	A
	LD	(D.D186),A
	LD	A,D
	CALL	C.258B
;
	LD	A,D
	BIT	7,B
	JR	Z,J$32C2
;
	LD	A,20H	; " "
J$32C2:	LD	(D.D187),A
	BIT	0,B
	JR	NZ,J.32D9
;
	BIT	5,B
	JR	Z,J$32D1
;
	CP	0DH	; 13 
	JR	NZ,J.32D9
;
J$32D1:	BIT	7,B
	JR	NZ,J.32D9
;
	LD	A,E
	LD	(D.D186),A
J.32D9:	CALL	C.32E5
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.32E5:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	BC,(D.D186)
	CALL	C.335A
;
	LD	A,(D.D189)
	AND	0FCH
	JR	Z,J$32FE
;
	CALL	C$3CF8
;
J$32FE:	LD	A,(D.D18F)
	AND	0FH	; 15 
	LD	B,A
	LD	A,(D.D171)
I$3306	EQU	$-1
	BIT	5,A
	JR	Z,J$330F
;
	LD	B,01H	; 1 
	JR	J.3318
;
;	-----------------
J$330F:	BIT	7,A
	JR	Z,J.3318
;
	LD	A,01H	; 1 
	LD	(D.D171),A
J.3318:	LD	A,B
	LD	(D.D190),A
	LD	A,(D.D18F)
	LD	B,A
	LD	A,(D.D171)
	BIT	5,A
	JR	Z,J$332E
;
	LD	B,0F0H
	LD	A,01H	; 1 
	LD	(D.D171),A
J$332E:	LD	A,B
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	AND	0FH	; 15 
	LD	(D.D191),A
	LD	B,01H	; 1 
	CALL	C.26D5
;
	CALL	C$396E
;
	LD	A,(D.D188)
	AND	03H	; 3 
	JR	Z,J.3351
;
	LD	A,(D.D185)
	AND	40H	; "@"
	JR	NZ,J.3351
;
	CALL	C$39EA
;
J.3351:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.335A:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	PUSH	BC
	LD	HL,I.D129
	LD	DE,I.D12A
	LD	BC,I$001F
	LD	(HL),00H
	LDIR	
	POP	BC
	LD	A,(D.D171)
	BIT	0,A
	JP	NZ,J.3393
;
	BIT	1,A
	JP	NZ,J.33F0
;
	BIT	2,A
	JP	NZ,J$34E3
;
	BIT	3,A
	JP	NZ,J$34F6
;
	BIT	4,A
	JR	NZ,J$33EB
;
	BIT	5,A
	JP	NZ,J$3512
;
	JR	J.3393
;
;	-----------------
J.3393:	LD	A,(D.D48A)
	AND	A
	JR	Z,J$33C3
;
	LD	A,B
	LD	HL,I$BA00
	SUB	20H	; " "
	PUSH	AF
	CP	80H
	JR	C,J$33A9
;
	SUB	80H
	LD	HL,I$BC00
J$33A9:	LD	B,A
	AND	A
	JR	Z,J$33B3
;
	LD	DE,C.0010
J$33B0:	ADD	HL,DE
	DJNZ	J$33B0
;
J$33B3:	POP	AF
	CP	80H
	JR	NC,J$33BD
;
	CALL	C$3626
;
	JR	J$33C0

J$33BD:	CALL	C$364C
J$33C0:	JP	J.3556			; quit
;
;	-----------------
J$33C3:	LD	A,(D.D189)
	AND	0FCH
	JR	Z,J.33D8
;
	LD	A,(D$D46E)
	AND	A
	JR	Z,J.33D8
;
	CALL	C$0C36
;
	CALL	C$0C23
;
	JR	J.33F0
;
;	-----------------
J.33D8:	LD	A,B
	CP	80H
	JR	NC,J$33E4
;
	SUB	20H	; " "
	LD	L,A
	LD	H,00H
	JR	J.3458
;
;	-----------------
J$33E4:	SUB	40H	; "@"
	LD	L,A
	LD	H,03H	; 3 
	JR	J.3458
;
;	-----------------
J$33EB:	LD	B,81H
	JP	J.3420

J.33F0:	LD	A,B
	CP	0E0H
	JR	NC,J.3474
	CP	99H
	JR	NC,J.3474
	CP	98H
	JR	C,X.3403
	LD	A,C
	CP	9FH
I.3400:	JR	NC,J.3474
	LD	A,B
X.3403:	CP	81H
	JR	NZ,J.3411
	LD	A,C
	CP	0B8H
	JR	C,J.3411
	CP	0FDH
	JP	C,J$34B9
J.3411:	LD	A,B
	CP	84H
	JR	NZ,J.3420
	LD	A,C
	CP	9FH
	JR	C,J.3420
	CP	0BFH
	JP	C,J$34CE
J.3420:	CALL	C.0C10
	LD	A,B
	SUB	20H	; " "
	CP	10H	; 16 
	JR	NC,J$343F
	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	PUSH	HL
D.3433:	ADD	HL,HL
	POP	DE
	ADD	HL,DE
	LD	A,C
	SUB	20H	; " "
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	JR	J.3458

J$343F:	SUB	10H	; 16 
	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	PUSH	HL
	ADD	HL,HL
	POP	DE
	ADD	HL,DE
	LD	A,C
	SUB	20H	; " "
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	LD	BC,I$0400
	ADD	HL,BC
J.3458:	LD	A,L
	AND	3FH	; "?"
	DI	
	OUT	(0D8H),A
	ADD	HL,HL
	ADD	HL,HL
	LD	A,H
	AND	3FH	; "?"
	OUT	(0D9H),A
	EI	
	LD	B,32
	LD	HL,I.D129
J$346B:	IN	A,(0D9H)
	LD	(HL),A
	INC	HL
	DJNZ	J$346B
	JP	J.3556			; quit
;
;	-----------------
J.3474:	CALL	C.0C10
;
J.3477:	PUSH	BC
	POP	HL
	LD	DE,I$5000
	AND	A
	SBC	HL,DE
	LD	B,60H	; "`"
	LD	C,L
	LD	DE,C.0000
	LD	L,H
	LD	H,00H
	EX	DE,HL
J$3489:	ADD	HL,DE
	DJNZ	J$3489
;
	LD	A,C
	SUB	20H	; " "
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	A,3FH	; "?"
	AND	L
	LD	E,A
	SLA	L
	RL	H
	SLA	L
	RL	H
	LD	A,3FH	; "?"
	AND	H
	LD	D,A
	DI	
	LD	A,E
	OUT	(0DAH),A
	LD	A,D
	OUT	(0DBH),A
	EI	
	LD	B,20H	; " "
	LD	HL,I.D129
J$34B0:	IN	A,(0DBH)
	LD	(HL),A
	INC	HL
	DJNZ	J$34B0
;
	JP	J.3556			; quit
;
;	-----------------
J$34B9:	LD	A,(D.D49E)
	BIT	6,A			; ? extension found ?
	JR	Z,J$34C6		; nope,
	CALL	C$355F
	JP	J.3556			; quit

J$34C6:	CALL	C.0C10
	LD	B,75H	; "u"
	JP	J.3477

J$34CE:	LD	A,(D.D49E)
	BIT	6,A			; ? extension found ?
	JR	Z,J$34DB		; nope,
	CALL	C$359E
	JP	J.3556			; quit

J$34DB:	CALL	C.0C10
	LD	B,76H	; "v"
	JP	J.3477
;
;	-----------------
J$34E3:	LD	HL,I.D1BD
	CALL	C.0C49
	JR	C,J.3556		; quit
	LD	HL,I.D1BD
	LD	DE,I.D129
	CALL	C$0CBD
	JR	J.3556			; quit
;
;	-----------------
J$34F6:	LD	A,(D.D49E)
	BIT	6,A			; ? extension found ?
	JR	Z,J$3503		; nope,
	CALL	C$35C5
	JP	J.3556			; quit

J$3503:	CALL	C.0C10
	LD	A,B
	LD	B,77H	; "w"
	CP	99H
	JR	Z,J$350F
	LD	B,78H	; "x"
J$350F:	JP	J.3477
;
;	-----------------
J$3512:	LD	A,B
	LD	HL,I$3D4D
	CP	0CH	; 12 
	JR	Z,J.354E
;
	LD	HL,I$3D2D
	CP	0DH	; 13 
	JR	Z,J.354E
;
	LD	HL,I$3DED
	CP	1AH
	JR	Z,J.354E
;
	LD	HL,I$3E0D
	CP	1BH
	JR	Z,J.354E
;
	LD	HL,I$3D6D
	CP	1CH
	JR	Z,J.354E
;
	LD	HL,I$3D8D
	CP	1DH
	JR	Z,J.354E
;
	LD	HL,I$3DAD
	CP	1EH
	JR	Z,J.354E
;
	LD	HL,I$3DCD
	CP	1FH
	JR	Z,J.354E
;
	LD	HL,I$3E2D
J.354E:	LD	DE,I.D129
	LD	BC,32
	LDIR	
J.3556:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$355F:	LD	A,C
	SUB	0B8H
	LD	IX,I$3594
J$3566:	CP	(IX)
	JR	C,J$3571
	INC	IX
	INC	IX
	JR	J$3566

J$3571:	LD	B,(IX+1)
	SUB	B
	LD	HL,I$B300
	LD	E,A
	LD	D,00H
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	ADD	HL,DE
	CALL	C$35EC
	RET	
;
;	-----------------
I$3594:	DJNZ	J$3596
;
J$3596:	LD	(D$3808),HL
	INC	DE
	LD	B,H
	LD	A,(DE)
	LD	B,L
	LD	E,0C5H
C$359E	EQU	$-1
	POP	HL
	LD	DE,I$849F
	AND	A
	SBC	HL,DE
	LD	E,L
	LD	D,00H
	LD	HL,I$AA00
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	ADD	HL,DE
	CALL	C$35FA
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$35C5:	PUSH	BC
	POP	HL
	LD	DE,I$FD40
	AND	A
	SBC	HL,DE
	LD	E,L
	LD	D,00H
	LD	HL,I$A800
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	SLA	E
	RL	D
	ADD	HL,DE
	CALL	C$3608
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$35EC:	CALL	C.1252			; select firmware on page 1
	CALL	C.13CA			; select firmware slot in page 2
	EX	AF,AF'
	LD	A,6
	CALL	C.12FA			; select firmware slot and segments in page 2
	JR	J.3614
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$35FA:	CALL	C.1252			; select firmware on page 1
;
	CALL	C.13CA			; select firmware slot in page 2
;
	EX	AF,AF'
	LD	A,2AH	; "*"
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	JR	J.3614
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3608:	CALL	C.1252			; select firmware on page 1
;
	CALL	C.13CA			; select firmware slot in page 2
;
	EX	AF,AF'
	LD	A,2CH	; ","
	CALL	C.12FA			; select firmware slot and segments in page 2
;
J.3614:	LD	DE,I.D129
	LD	BC,I.0020
	LDIR	
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.1428			; restore slot in page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3626:	CALL	C.1252			; select firmware on page 1
;
	CALL	C.13CA			; select firmware slot in page 2
;
	EX	AF,AF'
	LD	A,28H	; "("
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	LD	DE,I.D129
	LD	BC,C.0008
	LDIR	
	LD	DE,I.D139
	LD	BC,C.0008
	LDIR	
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.1428			; restore slot in page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$364C:	CALL	C.1252			; select firmware on page 1
;
	CALL	C.13CA			; select firmware slot in page 2
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	LD	DE,I.D129
	LD	BC,C.0008
	LDIR	
	LD	DE,I.D139
	LD	BC,C.0008
	LDIR	
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.1428			; restore slot in page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3672:	LD	IX,I.D129
	LD	HL,I.CF29
	CALL	C.36BF
;
	LD	HL,I.CF2D
	CALL	C.36BF
;
	LD	HL,I.CF29
	LD	DE,I.CF31
	LD	B,08H	; 8 
J$368A:	PUSH	BC
	LD	BC,C.0008
	LDIR	
	LD	BC,C.0008
	ADD	HL,BC
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	DJNZ	J$368A
;
	LD	HL,I.CFA9
	CALL	C.36BF
;
	LD	HL,I$CFAD
	CALL	C.36BF
;
	LD	HL,I.CFA9
	LD	DE,I.CFB1
	LD	B,08H	; 8 
J$36AE:	PUSH	BC
	LD	BC,C.0008
	LDIR	
	LD	BC,C.0008
	ADD	HL,BC
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	DJNZ	J$36AE
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.36BF:	LD	B,08H	; 8 
J$36C1:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	LD	DE,I.000C
	ADD	HL,DE
	DJNZ	J$36C1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$36D0:	LD	IX,I.D129
	LD	HL,I.CF29
	CALL	C.36ED
;
	LD	HL,I.CF31
	CALL	C.36ED
;
	LD	HL,I.CFA9
	CALL	C.36ED
;
	LD	HL,I.CFB1
	CALL	C.36ED
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.36ED:	LD	B,08H	; 8 
J$36EF:	LD	A,(IX)
	PUSH	AF
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	POP	AF
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	INC	IX
	LD	DE,C.0008
	ADD	HL,DE
	DJNZ	J$36EF
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3749:	LD	IX,I.D129
	LD	HL,I.CF29
	CALL	C.3796
;
	LD	HL,I.CF31
	CALL	C.3796
;
	LD	HL,I.CF29
	LD	DE,I.CF39
	LD	B,08H	; 8 
J$3761:	PUSH	BC
	LD	BC,C.0010
	LDIR	
	LD	BC,C.0010
	ADD	HL,BC
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	DJNZ	J$3761
;
	LD	HL,I.D029
	CALL	C.3796
;
	LD	HL,I$D031
	CALL	C.3796
;
	LD	HL,I.D029
	LD	DE,I$D039
	LD	B,08H	; 8 
J$3785:	PUSH	BC
	LD	BC,C.0010
	LDIR	
	LD	BC,C.0010
	ADD	HL,BC
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	DJNZ	J$3785
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.3796:	LD	B,08H	; 8 
J$3798:	LD	A,(IX)
	PUSH	AF
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	POP	AF
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	SRA	A
	RLA	
	RL	D
	RLA	
	RL	D
	LD	A,D
	CALL	C.29BE
;
	INC	IX
	LD	DE,I.0018
	ADD	HL,DE
	DJNZ	J$3798
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$37F2:	CALL	C.38DB
;
	LD	HL,I.CF29
	LD	DE,I.D129
	LD	B,08H	; 8 
J$37FD:	LD	A,(HL)
	INC	HL
	LD	C,(HL)
	OR	C
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$37FD
;
	LD	IX,I.D129
D$3808	EQU	$-2
	LD	HL,I.CF29
	LD	B,08H	; 8 
J$380F:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	DJNZ	J$380F
;
	LD	A,(D.D190)
	LD	B,A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0F0H
	OR	B
	LD	B,20H	; " "
J$3826:	LD	(HL),A
	INC	HL
	DJNZ	J$3826
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$382B:	CALL	C.38DB
;
	LD	HL,I.CF29
	LD	DE,I.D129
	LD	B,08H	; 8 
J$3836:	LD	A,(HL)
	INC	HL
	LD	C,(HL)
	OR	C
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$3836
;
	LD	IX,I.D129
	LD	HL,I.CF29
	LD	A,(D.D190)
	LD	B,A
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	AND	0F0H
	OR	B
	LD	B,20H	; " "
J$3853:	LD	(HL),A
	INC	HL
	DJNZ	J$3853
;
	LD	B,08H	; 8 
J$3859:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	DJNZ	J$3859
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3864:	CALL	C.38DB
;
	LD	HL,I.CF29
	LD	DE,I.D129
	LD	BC,C.0010
	LDIR	
	LD	IX,I.D129
	LD	HL,I.CF29
	LD	B,10H	; 16 
J$387B:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	DJNZ	J$387B
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3886:	LD	A,(D.D171)
	AND	01H	; 1 
	JR	Z,J$38AD
;
	LD	HL,I.D139
	LD	DE,I$D131
	LD	BC,C.0008
	LDIR	
	LD	B,10H	; 16 
	LD	IX,I.D129
	LD	HL,I.CF29
J$38A1:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	DJNZ	J$38A1
;
	JR	J$38C9
;
;	-----------------
J$38AD:	LD	IX,I.D129
	LD	HL,I.CF29
	CALL	C.38CA
;
	LD	HL,I.CF2D
	CALL	C.38CA
;
	LD	HL,I$CF69
	CALL	C.38CA
;
	LD	HL,I$CF6D
	CALL	C.38CA
;
J$38C9:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.38CA:	LD	B,08H	; 8 
J$38CC:	LD	A,(IX)
	CALL	C.29BE
;
	INC	IX
	LD	DE,I.0004
	ADD	HL,DE
	DJNZ	J$38CC
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.38DB:	LD	IX,I.D129
	LD	IY,I.CF29
	LD	B,08H	; 8 
J$38E5:	LD	A,(IX)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,(IX+8)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,E
	OR	C
	LD	(IY),A
	INC	IX
	INC	IY
	DJNZ	J$38E5
;
	LD	IX,I.D139
	LD	B,08H	; 8 
J$392C:	LD	A,(IX)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,(IX+8)
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	RLCA	
	RL	C
	RLCA	
	RL	E
	LD	A,E
	OR	C
	LD	(IY),A
	INC	IX
	INC	IY
	DJNZ	J$392C
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$396E:	LD	HL,(D.D18C)
	LD	A,(D.D188)
	AND	0F0H
	CP	10H	; 16 
	JR	Z,J$397E
;
	CP	30H	; "0"
	JR	NZ,J$3984
;
J$397E:	LD	DE,C.0010
	AND	A
	SBC	HL,DE
J$3984:	LD	DE,(D.D18A)
	LD	A,(D.D185)
	AND	0C7H
	JR	Z,J$3995
;
	LD	DE,C.0000
	LD	HL,I.01E0
J$3995:	LD	(D.CF1A),DE
	LD	(D.CF1C),HL
	LD	A,(D.D171)
	AND	01H	; 1 
	JR	NZ,J$39B6
;
	LD	HL,C.0010
	LD	A,(D.D188)
	AND	0F0H
	CP	20H	; " "
	JR	C,J.39B9
;
	LD	HL,I.0020
	CP	40H	; "@"
	JR	C,J.39B9
;
J$39B6:	LD	HL,C.0008
J.39B9:	LD	(D.CF1E),HL
	LD	HL,I.0020
	CP	10H	; 16 
	JR	Z,J.39CA
;
	CP	30H	; "0"
	JR	Z,J.39CA
;
	LD	HL,C.0010
J.39CA:	LD	(D.CF20),HL
	LD	HL,I.CF29
	LD	(D.CF22),HL
	LD	HL,D.CF1A
	CALL	C.167B
;
	LD	A,(D.D185)
	AND	0C7H
	JR	Z,J$39E9
;
	CALL	C$3C3E
;
	LD	HL,D.CF1A
	CALL	C.16EB
;
J$39E9:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$39EA:	LD	A,(D.D188)
	AND	03H	; 3 
	LD	HL,I.0001
	CP	01H	; 1 
	JR	Z,J$39F9
;
	LD	HL,I.0002
J$39F9:	LD	(D.CF20),HL
	LD	HL,(D.D18A)
	LD	(D.CF1A),HL
	LD	HL,(D.D18C)
	LD	DE,C.0010
	ADD	HL,DE
	LD	(D.CF1C),HL
	LD	HL,C.0010
	LD	A,(D.D171)
	AND	01H	; 1 
	JR	NZ,J$3A26
;
	LD	A,(D.D188)
	AND	0F0H
	CP	20H	; " "
	JR	C,J.3A29
;
	LD	HL,I.0020
	CP	40H	; "@"
	JR	C,J.3A29
;
J$3A26:	LD	HL,C.0008
J.3A29:	LD	(D.CF1E),HL
	LD	A,00H
	LD	(D.CF22),A
	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J$3A4C
;
	LD	HL,I.0018
	CP	01H	; 1 
	JR	Z,J.3A49
;
	LD	HL,C.0010
	CP	02H	; 2 
	JR	Z,J.3A49
;
	LD	HL,C.0008
J.3A49:	LD	(D.CF1E),HL
J$3A4C:	LD	A,(D.D188)
	AND	03H	; 3 
	CP	03H	; 3 
	JR	Z,J$3A5D
;
	LD	HL,D.CF1A
	CALL	C.172A
;
	JR	J$3A77
;
;	-----------------
J$3A5D:	LD	A,(D.CF1E)
	RRCA	
	RRCA	
	RRCA	
	AND	07H	; 7 
	LD	B,A
	LD	HL,I.0002
	LD	(D.CF1E),HL
	LD	HL,I.0001
	LD	(D.CF20),HL
J$3A72:	CALL	C$3A78
;
	DJNZ	J$3A72
;
J$3A77:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3A78:	LD	HL,D.CF1A
	CALL	C.172A
;
	LD	HL,(D.CF1A)
	LD	DE,I.0004
	ADD	HL,DE
	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.172A
;
	LD	HL,(D.CF1A)
	LD	DE,I.0002
	AND	A
	SBC	HL,DE
	LD	(D.CF1A),HL
	LD	HL,(D.CF1C)
	LD	DE,I.0001
	ADD	HL,DE
	LD	(D.CF1C),HL
	LD	HL,D.CF1A
	CALL	C.172A
;
	LD	HL,(D.CF1A)
	LD	DE,I.0004
	ADD	HL,DE
	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.172A
;
	LD	HL,(D.CF1A)
	LD	DE,I.0002
	ADD	HL,DE
	LD	(D.CF1A),HL
	LD	HL,(D.CF1C)
	LD	DE,I.0001
	AND	A
	SBC	HL,DE
	LD	(D.CF1C),HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3AD1:	PUSH	IX
	LD	A,(D.D189)
	AND	03H	; 3 
	JP	Z,J.3C06
;
	LD	HL,(D.D18C)
	LD	A,(D.D188)
	AND	0F0H
	LD	E,A
	CP	10H	; 16 
	JR	Z,J$3AEC
;
	CP	30H	; "0"
	JR	NZ,J$3B08
;
J$3AEC:	LD	A,(D.D185)
	AND	0C0H
	JR	NZ,J$3AFD
;
	LD	BC,C.0010
	AND	A
	SBC	HL,BC
	LD	B,10H	; 16 
	JR	J.3B2E
;
;	-----------------
J$3AFD:	LD	B,08H	; 8 
	AND	40H	; "@"
	JR	Z,J.3B2E
;
	INC	HL
	INC	HL
	INC	HL
	JR	J.3B2E
;
;	-----------------
J$3B08:	LD	B,08H	; 8 
	LD	A,(IX+4)
	AND	A
	JR	Z,J.3B2E
;
	LD	A,(IX+3)
	AND	40H	; "@"
	JR	Z,J$3B1C
;
	INC	HL
	INC	HL
	INC	HL
	JR	J.3B2E
;
;	-----------------
J$3B1C:	LD	A,(IX+2)
	LD	C,A
	LD	A,(D.D47C)
	CP	C
	JR	Z,J.3B2E
;
	LD	BC,C.0010
	AND	A
	SBC	HL,BC
	LD	B,10H	; 16 
J.3B2E:	LD	A,B
	LD	(D.D17A),A
	LD	(D.D178),HL
	LD	B,02H	; 2 
	LD	A,(D.D171)
	AND	01H	; 1 
	JR	NZ,J$3B49
;
	LD	A,E
	CP	20H	; " "
	JR	C,J.3B4B
;
	LD	B,04H	; 4 
	CP	40H	; "@"
	JR	C,J.3B4B
;
J$3B49:	LD	B,01H	; 1 
J.3B4B:	LD	A,B
	LD	(D.D17B),A
	LD	A,(D.D185)
	AND	07H	; 7 
	JR	Z,J$3B68
;
	LD	B,03H	; 3 
	CP	01H	; 1 
	JR	Z,J.3B64
;
	LD	B,02H	; 2 
	CP	02H	; 2 
	JR	Z,J.3B64
;
	LD	B,01H	; 1 
J.3B64:	LD	A,B
	LD	(D.D17B),A
J$3B68:	LD	A,00H
	LD	(D.CF1E),A
	LD	A,(D.D189)
	AND	03H	; 3 
	CP	01H	; 1 
	JR	Z,J$3BC0
;
	LD	HL,(D.D18A)
	LD	(D.D176),HL
	LD	A,(D.D17B)
	LD	B,A
J$3B80:	PUSH	BC
	LD	A,(D.D17A)
	LD	B,A
	LD	HL,(D.D178)
	LD	(D.CF1C),HL
J$3B8B:	PUSH	BC
	LD	HL,(D.D176)
	LD	(D.CF1A),HL
	CALL	C.3C09
;
	LD	HL,(D.D176)
	INC	HL
	INC	HL
	LD	(D.CF1A),HL
	LD	HL,(D.CF1C)
	INC	HL
	LD	(D.CF1C),HL
	CALL	C.3C09
;
	LD	HL,(D.CF1C)
	INC	HL
	LD	(D.CF1C),HL
	POP	BC
	DJNZ	J$3B8B
;
	LD	HL,(D.D176)
	LD	DE,C.0008
	ADD	HL,DE
	LD	(D.D176),HL
	POP	BC
	DJNZ	J$3B80
;
	JR	J.3C06
;
;	-----------------
J$3BC0:	LD	HL,(D.D18A)
	LD	(D.D176),HL
	LD	A,(D.D17B)
	LD	B,A
J$3BCA:	PUSH	BC
	LD	A,(D.D17A)
	LD	B,A
	LD	HL,(D.D178)
	LD	(D.CF1C),HL
J$3BD5:	PUSH	BC
	LD	HL,(D.D176)
	LD	(D.CF1A),HL
	CALL	C$3C1E
;
	LD	HL,(D.D176)
	LD	(D.CF1A),HL
	LD	HL,(D.CF1C)
	INC	HL
	LD	(D.CF1C),HL
	CALL	C$3C2C
;
	LD	HL,(D.CF1C)
	INC	HL
	LD	(D.CF1C),HL
	POP	BC
	DJNZ	J$3BD5
;
	LD	HL,(D.D176)
	LD	DE,C.0008
	ADD	HL,DE
	LD	(D.D176),HL
	POP	BC
	DJNZ	J$3BCA
;
J.3C06:	POP	IX
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.3C09:	LD	B,02H	; 2 
J$3C0B:	LD	HL,D.CF1A
	CALL	C.1761
;
	LD	HL,(D.CF1A)
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(D.CF1A),HL
	DJNZ	J$3C0B
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3C1E:	LD	HL,(D.CF1A)
	INC	HL
	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.1761
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3C2C:	LD	HL,(D.CF1A)
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(D.CF1A),HL
	LD	HL,D.CF1A
	CALL	C.1761
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3C3E:	LD	HL,C.0000
	LD	(D.CF1A),HL
	LD	HL,I.01E0
	LD	(D.CF1C),HL
	LD	HL,(D.D18A)
	LD	(D.CF1E),HL
	LD	A,(D.D188)
	AND	0F0H
	LD	HL,(D.D18C)
	CP	10H	; 16 
	JR	Z,J$3C60
;
	CP	30H	; "0"
	JR	NZ,J$3C66
;
J$3C60:	LD	DE,C.0010
	AND	A
	SBC	HL,DE
J$3C66:	LD	(D.CF20),HL
	LD	HL,C.0010
	LD	DE,C.0010
	AND	0F0H
	JR	Z,J.3C87
;
	LD	DE,I.0020
	CP	10H	; 16 
	JR	Z,J.3C87
;
	LD	HL,I.0020
D$3C7D:	LD	DE,C.0010
	CP	20H	; " "
	JR	Z,J.3C87
;
	LD	DE,I.0020
J.3C87:	LD	(D.CF22),HL
	LD	(D.CF24),DE
	XOR	A
	LD	(D.CF26),A
	LD	A,(D.D185)
	AND	0C0H
	JR	Z,J$3CB6
;
	LD	DE,(D.D18C)
D$3C9D:	AND	40H	; "@"
	JR	NZ,J$3CA9
;
	LD	HL,J.01F0
	LD	(D.CF1C),HL
	JR	J$3CAC
;
;	-----------------
J$3CA9:	INC	DE
	INC	DE
	INC	DE
J$3CAC:	LD	HL,C.0010
	LD	(D.CF24),HL
	LD	(D.CF20),DE
J$3CB6:	LD	A,(D.D185)
	LD	B,A
	AND	07H	; 7 
	JR	Z,J.3CF7
;
	LD	HL,C.0008
	LD	DE,I.0018
	CP	01H	; 1 
	JR	Z,J.3CE6
;
	LD	HL,C.0010
	LD	DE,C.0010
	CP	02H	; 2 
	JR	Z,J.3CE6
;
	LD	HL,C.0008
	LD	A,(D.D188)
	AND	0F0H
	JR	Z,J.3CE3
;
	CP	10H	; 16 
	JR	Z,J.3CE3
;
	LD	HL,I.0018
J.3CE3:	LD	DE,C.0008
J.3CE6:	BIT	3,B
	JR	Z,J$3CF0
;
	EX	DE,HL
	LD	(D.CF22),HL
	JR	J.3CF7
;
;	-----------------
J$3CF0:	LD	(D.CF1A),HL
	LD	(D.CF22),DE
J.3CF7:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$3CF8:	BIT	3,A
	JR	Z,J$3CFF
;
	CALL	C$0CD0
;
J$3CFF:	BIT	2,A
I$3D00	EQU	$-1
	JR	Z,J$3D06
;
	CALL	C$0CF6
;
J$3D06:	BIT	7,A
	JR	Z,J$3D0D
;
	CALL	C$0D09
;
J$3D0D:	BIT	5,A
	JR	Z,J$3D14
;
	CALL	C$0CE3
;
J$3D14:	RET	
;
;	-----------------
?.3D15:	CALL	C.1252			; select firmware on page 1
;
	CALL	C.13CA			; select firmware slot in page 2
;
	EX	AF,AF'
	LD	A,04H	; 4 
	CALL	C.12FA			; select firmware slot and segments in page 2
;
	LDIR	
	CALL	C.1371			; restore slot and segments on page 2
;
	CALL	C.1428			; restore slot in page 2
;
	CALL	C.12AC			; restore slot on page 1
;
	RET	
;
;	-----------------
I$3D2D:	NOP	
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	DEFB	0,0,0,0,0,0,0,0
	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	LD	(DE),A
	LD	(D$FE72),A
	DEFB	0,0,0,0,0,0,0,0,0
I$3D4D:	DEFB	0
	RST	38H
	RST	38H
	JR	J$3D6A
;
;	-----------------
?.3D52:	JR	J$3D6C
;
;	-----------------
?.3D54:	JR	J$3D56
;
;	-----------------
J$3D56:	DEFB	0,0,0,0,0,0,0
	JR	J$3D77
;
;	-----------------
?.3D5F:	JR	J$3D60
J$3D60	EQU	$-1
;
;	-----------------
?.3D61:	LD	A,(HL)
	INC	A
	JR	J$3D65
;
;	-----------------
J$3D65:	DEFB	0,0,0,0,0
J$3D6A:	DEFB	0,0
J$3D6C:	DEFB	0
I$3D6D:	DEFB	0,0
	EX	AF,AF'
	JR	J$3D7A
;
;	-----------------
?.3D72:	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	DEFB	0,0
J$3D77:	DEFB	0,0,0
J$3D7A:	DEFB	0,0,0
	ADD	HL,BC
	LD	(BC),A
	INC	B
	EX	AF,AF'
	DJNZ	J$3DA3
;
	DEFB	0,0,0,0,0,0,0,0,0,0
I$3D8D:	DEFB	0,0
	INC	A
	LD	B,D
	LD	(BC),A
	INC	B
	EX	AF,AF'
	DJNZ	J$3D96
;
J$3D96:	DEFB	0,0,0,0,0,0,0
	LD	A,A
	LD	(BC),A
	INC	B
	EX	AF,AF'
	DJNZ	J$3DC3
;
J$3DA3:	DEFB	0,0,0,0,0,0,0,0,0,0
I$3DAD:	DEFB	0,0
	INC	A
	LD	B,D
	LD	(BC),A
	INC	A
	LD	(BC),A
	LD	B,D
	DEFB	0,0,0,0,0,0,0,0
	DEC	A
	LD	(BC),A
	INC	B
	EX	AF,AF'
	DJNZ	J$3DE3
;
J$3DC3:	DEFB	0,0,0,0,0,0,0,0,0,0
I$3DCD:	DEFB	0,0
	INC	B
	EX	AF,AF'
	DJNZ	J$3DF3
;
	LD	B,B
	CP	H
	DEFB	0,0,0,0,0,0,0,0
	LD	B,D
	LD	(BC),A
	INC	A
	LD	(BC),A
	LD	B,D
	INC	A
J$3DE3:	DEFB	0,0,0,0,0,0,0,0,0,0
I$3DED:	DEFB	0,0
	INC	B
	EX	AF,AF'
	DJNZ	J$3E13
;
J$3DF3:	LD	B,B
	ADC	A,B
	DEFB	0,0,0,0,0,0,0,0
	JR	J$3E07
;
;	-----------------
?.3DFF:	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	DEFB	0,0,0,0
J$3E07:	DEFB	0,0,0,0,0,0
I$3E0D:	DEFB	0,0
	INC	B
	EX	AF,AF'
	DJNZ	J$3E33
;
J$3E13:	LD	B,B
	CP	H
	DEFB	0,0,0,0,0,0,0,0
	LD	B,D
	LD	(BC),A
	INC	B
	EX	AF,AF'
	DJNZ	J$3EA1
;
	DEFB	0,0,0,0,0,0,0,0,0,0
I$3E2D:	DEFB	0,0,0,0,0,0
J$3E33:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0
J$3E4D:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	D,(IX+2)
	LD	E,(IX+3)
	PUSH	DE
	LD	H,(IX)
	LD	L,(IX+1)
	LD	A,H
	SUB	(IX+4)
	LD	B,A
	LD	C,00H
	LD	A,00H
	JR	NC,J$3E6C
;
	LD	A,0CH	; 12 
	ADD	HL,DE
J$3E6C:	PUSH	HL
	LD	(D.CF26),A
	AND	A
	LD	A,(IX+5)
	JR	J.3ECD
;
;	-----------------
J$3E76:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	D,(IX+2)
	LD	E,(IX+3)
	PUSH	DE
	LD	H,(IX)
	LD	L,(IX+1)
	LD	A,L
	SUB	(IX+4)
	LD	B,00H
	LD	C,A
	LD	A,00H
	JR	NC,J$3E95
;
	LD	A,0CH	; 12 
	ADD	HL,DE
J$3E95:	PUSH	HL
	LD	(D.CF26),A
	AND	A
	LD	A,(IX+5)
	JR	J.3ECD
;
;	-----------------
J$3E9F:	PUSH	AF
	PUSH	BC
J$3EA1:	PUSH	DE
	PUSH	HL
	LD	D,(IX+2)
	LD	E,01H	; 1 
	LD	H,(IX)
	LD	L,(IX+1)
	BIT	4,(IX+4)
	JR	Z,J$3EB6
;
	INC	E
	DEC	L
J$3EB6:	PUSH	DE
	LD	A,H
	SUB	(IX+3)
	LD	B,A
	LD	C,00H
	LD	A,00H
	JR	NC,J$3EC5
;
	LD	A,0CH	; 12 
	ADD	HL,DE
J$3EC5:	PUSH	HL
	LD	(D.CF26),A
	AND	A
	LD	A,(IX+4)
J.3ECD:	PUSH	AF
	LD	A,H
	SUB	B
	LD	D,A
	LD	A,L
	SUB	C
	LD	E,A
	POP	AF
	LD	C,00H
	JR	Z,J$3EDB
;
	LD	C,0F0H
J$3EDB:	AND	0FH	; 15 
	OR	C
	LD	C,00H
	LD	B,D
	CALL	C.3F66
;
	LD	(D.CF1E),HL
	LD	B,E
	CALL	C.3F9B
;
	LD	(D.CF20),HL
	POP	DE
	LD	B,D
	CALL	C.3F66
;
	LD	(D.CF1A),HL
	LD	B,E
	CALL	C.3F9B
;
	LD	(D.CF1C),HL
	POP	DE
	LD	C,0FFH
	LD	B,D
	CALL	C.3F66
;
	LD	(D.CF22),HL
	LD	B,E
	CALL	C.3F9B
;
	LD	(D.CF24),HL
	LD	A,(D.D46D)
	AND	A
	JR	Z,J.3F5B
;
	LD	DE,I.0100
	LD	HL,(D.CF1C)
	ADD	HL,DE
	LD	(D.CF1C),HL
	LD	HL,(D.CF20)
	ADD	HL,DE
	LD	(D.CF20),HL
	LD	HL,(D.CF22)
	INC	HL
	INC	HL
	LD	(D.CF22),HL
	LD	HL,(D.CF24)
	INC	HL
	INC	HL
	LD	(D.CF24),HL
	LD	A,(D.CF26)
	AND	A
	JR	NZ,J.3F5B
;
	LD	HL,(D.CF1A)
	DEC	HL
	DEC	HL
	LD	(D.CF1A),HL
	LD	HL,(D.CF1C)
	DEC	HL
	DEC	HL
	LD	(D.CF1C),HL
	LD	HL,(D.CF1E)
	DEC	HL
	DEC	HL
	LD	(D.CF1E),HL
	LD	HL,(D.CF20)
	DEC	HL
	DEC	HL
	LD	(D.CF20),HL
J.3F5B:	LD	HL,D.CF1A
	CALL	C.16EB
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.3F66:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	AF
	AND	0FH	; 15 
	JR	NZ,J$3F75
;
	LD	E,06H	; 6 
	LD	HL,I.0004
	JR	J.3F84
;
;	-----------------
J$3F75:	DEC	A
	JR	NZ,J$3F7F
;
	LD	E,08H	; 8 
	LD	HL,C.0008
	JR	J.3F84
;
;	-----------------
J$3F7F:	LD	E,02H	; 2 
	LD	HL,I$0048
J.3F84:	LD	A,B
	BIT	0,C
	POP	BC
	JR	NZ,J$3F94
;
	CALL	C.3FD3
;
	BIT	4,B
	JR	Z,J.3F97
;
	DEC	HL
	JR	J.3F97
;
;	-----------------
J$3F94:	CALL	C.3FD0
;
J.3F97:	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.3F9B:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	AF
	AND	0FH	; 15 
	JR	NZ,J$3FAA
;
	LD	E,0EH	; 14 
	LD	HL,I$0013
	JR	J.3FB9
;
;	-----------------
J$3FAA:	DEC	A
	JR	NZ,J$3FB4
;
	LD	E,13H	; 19 
	LD	HL,I.0012
	JR	J.3FB9
;
;	-----------------
J$3FB4:	LD	E,02H	; 2 
	LD	HL,I.0020
J.3FB9:	LD	A,B
	BIT	0,C
	POP	BC
	JR	NZ,J$3FC9
;
	CALL	C.3FD3
;
	BIT	4,B
	JR	Z,J.3FCC
;
	DEC	HL
	JR	J.3FCC
;
;	-----------------
J$3FC9:	CALL	C.3FD0
;
J.3FCC:	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.3FD0:	LD	HL,C.0000
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.3FD3:	LD	D,00H
	PUSH	BC
	LD	B,08H	; 8 
J$3FD8:	SRL	A
	JR	NC,J$3FDD
;
	ADD	HL,DE
J$3FDD:	SLA	E
	RL	D
	DJNZ	J$3FD8
;
	POP	BC
	RET	
;
;	-----------------
?.3FE5:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	END
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	