;  
;   FS-SR021, segment 18 -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA
;
	.Z80
	ORG	8000H
;
X.0000	EQU	0000H	; JCS-I
I.0003	EQU	0003H	; ----I
I.0004	EQU	0004H	; ----I
BDOS	EQU	0005H	; ----I
CPMADR	EQU	0006H	; -C-LI
D.0007	EQU	0007H	; ---LI
C.0008	EQU	0008H	; -C--I
C.000C	EQU	000CH	; -C--I
I.000D	EQU	000DH	; ----I
I$000E	EQU	000EH	; ----I
I.000F	EQU	000FH	; ----I
I$0012	EQU	0012H	; ----I
C.0018	EQU	0018H	; -C--I
I.001A	EQU	001AH	; ----I
C.001B	EQU	001BH	; -C--I
C$001C	EQU	001CH	; -C---
I.0024	EQU	0024H	; ----I
I$002E	EQU	002EH	; ----I
I$0030	EQU	0030H	; ----I
C.0038	EQU	0038H	; -C---
C$003B	EQU	003BH	; -C---
C$003E	EQU	003EH	; -C---
C$0041	EQU	0041H	; -C---
C$0044	EQU	0044H	; -C---
I.0045	EQU	0045H	; ----I
C$0047	EQU	0047H	; -C---
I.0048	EQU	0048H	; ----I
C.004A	EQU	004AH	; -C---
C$004D	EQU	004DH	; -C---
C$0050	EQU	0050H	; -C---
C.0053	EQU	0053H	; -C--I
C$0056	EQU	0056H	; -C---
I$0057	EQU	0057H	; ----I
C.0059	EQU	0059H	; -C---
FCB1	EQU	005CH	; -C---
C.005F	EQU	005FH	; -C---
C$0062	EQU	0062H	; -C---
I.0063	EQU	0063H	; ----I
I$0064	EQU	0064H	; ----I
C$0065	EQU	0065H	; -C---
DBUF	EQU	0080H	; ----I
C$0083	EQU	0083H	; -C---
C$0098	EQU	0098H	; -C---
C$009B	EQU	009BH	; -C---
C$009E	EQU	009EH	; -C---
C$00A2	EQU	00A2H	; -C---
C$00AA	EQU	00AAH	; -C---
C$00B6	EQU	00B6H	; -C---
CLS	EQU	00C3H	; -C---
POSIT	EQU	00C6H	; -C---
TOTEXT	EQU	00D2H	; -C---
I$0101	EQU	0101H	; ----I
I$010B	EQU	010BH	; ----I
I$010D	EQU	010DH	; ----I
I$0120	EQU	0120H	; ----I
SNSMAT	EQU	0141H	; -C---
EXTROM	EQU	015FH	; -C---
D$0164	EQU	0164H	; --S--
D$0174	EQU	0174H	; --S--
CHGMDP	EQU	01B5H	; ----I
WRTCLK	EQU	01F9H	; ----I
I$01FF	EQU	01FFH	; ----I
I$0200	EQU	0200H	; ----I
I.0201	EQU	0201H	; ----I
I$0304	EQU	0304H	; ----I
I$030B	EQU	030BH	; ----I
I$0402	EQU	0402H	; ----I
I$05A0	EQU	05A0H	; ----I
I.0703	EQU	0703H	; ----I
I$073A	EQU	073AH	; ----I
I.0801	EQU	0801H	; ----I
I$0808	EQU	0808H	; ----I
I$09FF	EQU	09FFH	; ----I
I$0B40	EQU	0B40H	; ----I
I$0EAA	EQU	0EAAH	; ----I
I$1001	EQU	1001H	; ----I
I$10DF	EQU	10DFH	; ----I
I.10E0	EQU	10E0H	; ----I
C$1393	EQU	1393H	; -C---
I$1400	EQU	1400H	; ----I
C$1493	EQU	1493H	; -C---
I$2020	EQU	2020H	; ----I
C$2193	EQU	2193H	; -C---
I.3030	EQU	3030H	; ----I
J$3191	EQU	3191H	; J----
I$3401	EQU	3401H	; ----I
I$3434	EQU	3434H	; ----I
J$3493	EQU	3493H	; J----
D.4000	EQU	4000H	; --S-I
I.4010	EQU	4010H	; ----I
C$4018	EQU	4018H	; -C---
I$4023	EQU	4023H	; ----I
C$4024	EQU	4024H	; -C---
C$402B	EQU	402BH	; -C---
C$4039	EQU	4039H	; -C---
J$4043	EQU	4043H	; J----
C$405A	EQU	405AH	; -C---
C$405D	EQU	405DH	; -C---
I$4100	EQU	4100H	; ----I
C$5291	EQU	5291H	; -C---
I.5E14	EQU	5E14H	; ----I
I$5E15	EQU	5E15H	; ----I
D.6000	EQU	6000H	; --S--
J$6291	EQU	6291H	; J----
D.6400	EQU	6400H	; --S--
D.6800	EQU	6800H	; --S--
D.6C00	EQU	6C00H	; --S--
I.6EF4	EQU	6EF4H	; ----I
D.7800	EQU	7800H	; --S--
I.7804	EQU	7804H	; ----I
I.7836	EQU	7836H	; ----I
D$7FF0	EQU	7FF0H	; ---L-
D$7FF2	EQU	7FF2H	; ---L-
D.7FF9	EQU	7FF9H	; --S--
D.C010	EQU	0C010H	; --S-I
D$C31A	EQU	0C31AH	; ---L-
D$C31B	EQU	0C31BH	; --S--
D$C325	EQU	0C325H	; --S--
D$C326	EQU	0C326H	; ---L-
D.C327	EQU	0C327H	; ---LI
D.C329	EQU	0C329H	; --SLI
D.C32B	EQU	0C32BH	; ---L-
D.C32C	EQU	0C32CH	; ---LI
D.C32E	EQU	0C32EH	; ---L-
D$C332	EQU	0C332H	; ---L-
D.C337	EQU	0C337H	; --SL-
D.C339	EQU	0C339H	; ---L-
D.C33D	EQU	0C33DH	; --SL-
D.C341	EQU	0C341H	; --S--
D.C344	EQU	0C344H	; --S-I
D$C345	EQU	0C345H	; --S--
D.C346	EQU	0C346H	; --S--
D$C34E	EQU	0C34EH	; ---L-
D$C34F	EQU	0C34FH	; ---L-
D.C352	EQU	0C352H	; --SL-
D$C354	EQU	0C354H	; ---L-
D$C355	EQU	0C355H	; ---L-
I$C389	EQU	0C389H	; ----I
D.C393	EQU	0C393H	; --SL-
D.C395	EQU	0C395H	; --S--
D.C3BF	EQU	0C3BFH	; ---L-
D.C3C0	EQU	0C3C0H	; ---L-
I.C3C1	EQU	0C3C1H	; ----I
D.C3CA	EQU	0C3CAH	; --SL-
D.C3CC	EQU	0C3CCH	; --SL-
D$C3CF	EQU	0C3CFH	; ---L-
J$C3D1	EQU	0C3D1H	; J----
D$C3D8	EQU	0C3D8H	; ---L-
D$C3DA	EQU	0C3DAH	; ---L-
D.C3DB	EQU	0C3DBH	; --SL-
D.C3DC	EQU	0C3DCH	; --SL-
D.C3DD	EQU	0C3DDH	; --SL-
D.C3E1	EQU	0C3E1H	; --SL-
D.C3E2	EQU	0C3E2H	; --SL-
D$C3E3	EQU	0C3E3H	; ---L-
D.C3EC	EQU	0C3ECH	; --SL-
D.C3ED	EQU	0C3EDH	; --S--
D.C3EE	EQU	0C3EEH	; --S--
D.C3EF	EQU	0C3EFH	; --SL-
D.C403	EQU	0C403H	; --SL-
D$C407	EQU	0C407H	; --S--
D.C4C2	EQU	0C4C2H	; --SLI
C$C500	EQU	0C500H	; -C---
I$C5FF	EQU	0C5FFH	; ----I
I$C88E	EQU	0C88EH	; ----I
D.C901	EQU	0C901H	; --SL-
I.C91B	EQU	0C91BH	; ----I
D.C996	EQU	0C996H	; --SL-
D.C997	EQU	0C997H	; --SL-
D$C998	EQU	0C998H	; ---L-
D.C999	EQU	0C999H	; --SLI
D$C99B	EQU	0C99BH	; ---L-
D.C9B0	EQU	0C9B0H	; ---L-
D.C9C6	EQU	0C9C6H	; --SL-
D.C9C7	EQU	0C9C7H	; --SL-
D.C9D0	EQU	0C9D0H	; --SL-
C$CAC4	EQU	0CAC4H	; -C---
I$CC01	EQU	0CC01H	; ----I
D.CC3D	EQU	0CC3DH	; ---L-
D.CC3F	EQU	0CC3FH	; ---L-
D$CC40	EQU	0CC40H	; ---L-
D$CC48	EQU	0CC48H	; ---L-
D$CC4A	EQU	0CC4AH	; ---L-
X.CC4B	EQU	0CC4BH	; J--L-
D$CC4C	EQU	0CC4CH	; ---L-
C$CCB0	EQU	0CCB0H	; -C---
D.CE6C	EQU	0CE6CH	; --SL-
D$CF00	EQU	0CF00H	; --S--
I.D129	EQU	0D129H	; ----I
D.D171	EQU	0D171H	; --S--
I$D185	EQU	0D185H	; ----I
I$D189	EQU	0D189H	; ----I
D$D18E	EQU	0D18EH	; ---L-
I.D1BD	EQU	0D1BDH	; ----I
I.D1BE	EQU	0D1BEH	; ----I
I.D1BF	EQU	0D1BFH	; ----I
I.D1C0	EQU	0D1C0H	; ----I
I$D1CF	EQU	0D1CFH	; ----I
I$D1D2	EQU	0D1D2H	; ----I
I$D1D3	EQU	0D1D3H	; ----I
I$D1D4	EQU	0D1D4H	; ----I
I.D1D5	EQU	0D1D5H	; ----I
I.D1D6	EQU	0D1D6H	; ----I
I.D1D7	EQU	0D1D7H	; ----I
I$D1E0	EQU	0D1E0H	; ----I
I.D1E1	EQU	0D1E1H	; ----I
I$D1EA	EQU	0D1EAH	; ----I
I$D1EB	EQU	0D1EBH	; ----I
I$D1EC	EQU	0D1ECH	; ----I
I.D1ED	EQU	0D1EDH	; ----I
I.D1EE	EQU	0D1EEH	; ----I
I.D1EF	EQU	0D1EFH	; ----I
I$D1F2	EQU	0D1F2H	; ----I
D$D200	EQU	0D200H	; --S--
I.D201	EQU	0D201H	; ----I
I.D202	EQU	0D202H	; ----I
I$D203	EQU	0D203H	; ----I
I.D204	EQU	0D204H	; ----I
I$D205	EQU	0D205H	; ----I
I$D206	EQU	0D206H	; ----I
I$D207	EQU	0D207H	; ----I
I$D21D	EQU	0D21DH	; ----I
I$D21E	EQU	0D21EH	; ----I
I$D21F	EQU	0D21FH	; ----I
I.D2DD	EQU	0D2DDH	; ----I
I.D2DE	EQU	0D2DEH	; ----I
I.D2DF	EQU	0D2DFH	; ----I
I$D2E0	EQU	0D2E0H	; ----I
I.D2E5	EQU	0D2E5H	; ----I
I.D2ED	EQU	0D2EDH	; ----I
I.D2EF	EQU	0D2EFH	; ----I
I$D2F4	EQU	0D2F4H	; ----I
I.D2F5	EQU	0D2F5H	; ----I
I.D2F6	EQU	0D2F6H	; ----I
I.D2F7	EQU	0D2F7H	; ----I
I.D2FD	EQU	0D2FDH	; ----I
I.D305	EQU	0D305H	; ----I
I$D30C	EQU	0D30CH	; ----I
I.D30D	EQU	0D30DH	; ----I
I.D30E	EQU	0D30EH	; ----I
I.D30F	EQU	0D30FH	; ----I
I.D315	EQU	0D315H	; ----I
I.D31D	EQU	0D31DH	; ----I
I$D321	EQU	0D321H	; ----I
I.D324	EQU	0D324H	; ----I
I.D325	EQU	0D325H	; ----I
I$D328	EQU	0D328H	; ----I
I.D32D	EQU	0D32DH	; ----I
I$D335	EQU	0D335H	; ----I
I$D33D	EQU	0D33DH	; ----I
I$D345	EQU	0D345H	; ----I
I$D34D	EQU	0D34DH	; ----I
I$D354	EQU	0D354H	; ----I
I.D3FD	EQU	0D3FDH	; ----I
I.D3FE	EQU	0D3FEH	; ----I
I$D3FF	EQU	0D3FFH	; ----I
I$D415	EQU	0D415H	; ----I
I$D416	EQU	0D416H	; ----I
D.D417	EQU	0D417H	; --SLI
D.D418	EQU	0D418H	; --SL-
D.D419	EQU	0D419H	; --SLI
I$D42D	EQU	0D42DH	; ----I
I$D42E	EQU	0D42EH	; ----I
I$D42F	EQU	0D42FH	; ----I
D.D445	EQU	0D445H	; --SL-
D.D446	EQU	0D446H	; --SL-
D.D447	EQU	0D447H	; --SL-
D$D448	EQU	0D448H	; ---L-
D.D449	EQU	0D449H	; ---L-
D.D44A	EQU	0D44AH	; --S--
D.D456	EQU	0D456H	; --S--
D.D464	EQU	0D464H	; --S--
D.D468	EQU	0D468H	; ---L-
D.D469	EQU	0D469H	; ---L-
D.D46A	EQU	0D46AH	; ---L-
D.D48A	EQU	0D48AH	; ---L-
D.D497	EQU	0D497H	; ---L-
D.D498	EQU	0D498H	; --SL-
D.D499	EQU	0D499H	; --SL-
D.D49D	EQU	0D49DH	; ---L-
D.D49E	EQU	0D49EH	; ---L-
D.D49F	EQU	0D49FH	; --SL-
D.D4A0	EQU	0D4A0H	; --SL-
C$D6C4	EQU	0D6C4H	; -C---
X.DACD	EQU	0DACDH	; J--L-
D$DB15	EQU	0DB15H	; ---L-
D$DB16	EQU	0DB16H	; ---L-
C$DBDF	EQU	0DBDFH	; -C---
D.F3EB	EQU	0F3EBH	; --S--
D.FAF8	EQU	0FAF8H	; ---L-
D.FAFC	EQU	0FAFCH	; ---L-
I$FBC3	EQU	0FBC3H	; ----I
D.FCC1	EQU	0FCC1H	; ---LI
H.KEYI	EQU	0FD9AH	; --SL-
H.TIMI	EQU	0FD9FH	; -C---
H.STKE	EQU	0FEDAH	; --SL-
J$FF93	EQU	0FF93H	; J----
I$FFF8	EQU	0FFF8H	; ----I
D.FFFF	EQU	0FFFFH	; --SL-
;
I$8000:	JP	C.9495
;
;	-----------------
?.8003:	JP	C.A845
;
;	-----------------
?.8006:	JP	C.9BFE
;
;	-----------------
?.8009:	JP	J$9C27
;
;	-----------------
?.800C:	JP	C.9C0D
;
;	-----------------
?.800F:	JP	C.876D
;
;	-----------------
?.8012:	JP	C.A197
;
;	-----------------
?.8015:	JP	C.93DE
;
;	-----------------
?.8018:	JP	C.A66C
;
;	-----------------
?.801B:	JP	C.A12D
;
;	-----------------
?.801E:	JP	J.9A77
;
;	-----------------
?.8021:	JP	C.A652
;
;	-----------------
?.8024:	JP	J$AAEF
;
;	-----------------
?.8027:	JP	J$88DE
;
;	-----------------
?.802A:	JP	J$8636
;
;	-----------------
?.802D:	JP	J$8834
;
;	-----------------
?.8030:	JP	C.A171
;
;	-----------------
?.8033:	JP	J$A681
;
;	-----------------
?.8036:	JP	C.8905
;
;	-----------------
?.8039:	JP	J$8693
;
;	-----------------
?.803C:	JP	J$A6A6
;
;	-----------------
?.803F:	JP	C.878B
;
;	-----------------
?.8042:	JP	C.A6A7
;
;	-----------------
?.8045:	JP	J$A3F3
;
;	-----------------
?.8048:	JP	J$86AA
;
;	-----------------
?.804B:	JP	C.A93D
;
;	-----------------
?.804E:	JP	C.88BB
;
;	-----------------
?.8051:	JP	J$8FC2
;
;	-----------------
?.8054:	JP	J$8852
;
;	-----------------
?.8057:	JP	J$891D
;
;	-----------------
?.805A:	JP	C.AB39
;
;	-----------------
?.805D:	JP	C.8C92
;
;	-----------------
?.8060:	JP	J$9CA6
;
;	-----------------
?.8063:	JP	C.AB23
;
;	-----------------
?.8066:	JP	J.9A77
;
;	-----------------
?.8069:	JP	C.877C
;
;	-----------------
?.806C:	JP	J.91E4
;
;	-----------------
?.806F:	JP	C.96A0
;
;	-----------------
?.8072:	JP	J$9578
;
;	-----------------
?.8075:	JP	J$9616
;
;	-----------------
?.8078:	JP	J$9751
;
;	-----------------
?.807B:	JP	J$97B3
;
;	-----------------
?.807E:	JP	J$852C
;
;	-----------------
?.8081:	JP	C.987E
;
;	-----------------
?.8084:	JP	J$A861
;
;	-----------------
?.8087:	JP	C.8941
;
;	-----------------
?.808A:	JP	C.8AC7
;
;	-----------------
?.808D:	JP	J$99CC
;
;	-----------------
?.8090:	JP	C.98F4
;
;	-----------------
?.8093:	JP	J$AC3D
;
;	-----------------
?.8096:	JP	J$AC53
;
;	-----------------
J$8099:	JP	J$8099
;
;	-----------------
J$809C:	JP	J$809C
;
;	-----------------
?.809F:	JP	J$86C5
;
;	-----------------
?.80A2:	JP	J$86E0
;
;	-----------------
?.80A5:	JP	J$887F
;
;	-----------------
?.80A8:	JP	J$9D9F
;
;	-----------------
?.80AB:	JP	J$9DA4
;
;	-----------------
?.80AE:	JP	J$9DBE
;
;	-----------------
?.80B1:	JP	J$9DC3
;
;	-----------------
?.80B4:	JP	J$9CA7
;
;	-----------------
?.80B7:	JP	C.9F3D
;
;	-----------------
?.80BA:	JP	C.A118
;
;	-----------------
?.80BD:	JP	C.A00C
;
;	-----------------
?.80C0:	JP	J$9FD9
;
;	-----------------
?.80C3:	JP	C.9FE7
;
;	-----------------
?.80C6:	JP	J$9DB4
;
;	-----------------
?.80C9:	JP	J$9AF4
;
;	-----------------
?.80CC:	JP	J$9B19
;
;	-----------------
?.80CF:	JP	J$9AD1
;
;	-----------------
?.80D2:	JP	C.9B3E
;
;	-----------------
?.80D5:	JP	C.9DFC
;
;	-----------------
?.80D8:	JP	J$9F23
;
;	-----------------
?.80DB:	JP	J.A3C2
;
;	-----------------
?.80DE:	JP	C.A984
;
;	-----------------
?.80E1:	JP	J$8E37
;
;	-----------------
?.80E4:	JP	J$8ED7
;
;	-----------------
?.80E7:	JP	J$8F76
;
;	-----------------
?.80EA:	JP	J$9DB9
;
;	-----------------
?.80ED:	JP	J$ABA0
;
;	-----------------
?.80F0:	JP	J$9FA7
;
;	-----------------
?.80F3:	JP	C.A737
;
;	-----------------
?.80F6:	JP	J$9E96
;
;	-----------------
?.80F9:	JP	J$9ECB
;
;	-----------------
?.80FC:	JP	C.9DD3
;
;	-----------------
?.80FF:	JP	J$9BA3
I$8101	EQU	$-1
;
;	-----------------
?.8102:	JP	J$9B81
;
;	-----------------
?.8105:	JP	J$8160
;
;	-----------------
?.8108:	JP	J$82A0
;
;	-----------------
?.810B:	JP	C.B554
;
;	-----------------
?.810E:	JP	J$8216
;
;	-----------------
?.8111:	JP	C.B56D
;
;	-----------------
?.8114:	JP	C.863E
;
;	-----------------
J$8117:	JP	J$8117
;
;	-----------------
?.811A:	JP	J$A9E7
;
;	-----------------
?.811D:	JP	J$9A61
;
;	-----------------
?.8120:	JP	J$B3D5
;
;	-----------------
?.8123:	JP	J$B428
;
;	-----------------
?.8126:	JP	J$9D32
;
;	-----------------
?.8129:	JP	C.9E6A
;
;	-----------------
?.812C:	JP	J$B703
;
;	-----------------
?.812F:	JP	C.9E04
;
;	-----------------
?.8132:	JP	C.AFE5
;
;	-----------------
?.8135:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	LD	C,L
	LD	D,E
	LD	E,B
	LD	D,A
	LD	D,B
	LD	C,C
	LD	B,H

I$8157:	LD	C,L
	LD	D,E
	LD	E,B

I.815A:	LD	C,D
	LD	D,A
	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	H,L

J$8160:	CALL	C$BD90
	NOP	
	DI	
	CALL	C$8267			; check for panasonic JIS2 ROM
	JR	C,J$8187		; yep,
	LD	A,81H
	LD	(D.7800),A		; select SRAM page 2
	LD	A,(D.BF48)		; software firmware switch
	CP	2			; valid value ?
	JR	C,J$817A		; yep,
	XOR	A
	LD	(D.BF48),A		; software firmware switch = off
J$817A:	LD	B,A
	LD	A,13H	; 19 
	LD	(D.7800),A		; select ROM page 2
	LD	A,B
	OR	A			; software firmware switch = off ?
	JP	Z,C.82CC		; yep, do not start firmware
	JR	J$8191			; firmware enabled

J$8187:	LD	A,08H
	OUT	(40H),A			; Matsushita switchable I/O
	IN	A,(41H)
	RLCA				; firmware switch enabled ?
	JP	C,C.82CC		; nope, do not start firmware
J$8191:	LD	A,08H
	CALL	SNSMAT
	AND	08H			; DEL pressed ?
	JP	Z,C.82CC		; yep, do not start firmware
	LD	A,(D.FAF8)
	OR	A			; MSX1 ?
	JP	Z,J.8256		; yep, show message and halt
	LD	A,(D.FAFC)
	AND	04H			; VRAM size 128 KB ?
	JP	Z,J.8245		; nope, show message and halt
	LD	HL,D.C010
	LD	DE,I$8157		; MSX
	LD	B,3
J$81B2:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$81BD		; environment not found,
	INC	HL
	INC	DE
	DJNZ	J$81B2
	JP	J.820F			; end environment and quit

J$81BD:	LD	HL,D.C010
	LD	DE,I.815A		; JWrite
	LD	B,6
J$81C5:	LD	A,(DE)
	CP	(HL)
	JP	NZ,J$81D1		; environment not found,
	INC	HL
	INC	DE
	DJNZ	J$81C5
	JP	J.820F			; end enviromwnt and quit

J$81D1:	CALL	C.82E0			; BASIC ROM ?
	JP	C,C.82CC		; yep, do not start firmware
	DI	
	LD	A,(H.STKE+0)
	CP	0C9H			; H.STKE hooked ?
	JP	NZ,C.82CC		; yep, do not start firmware
	LD	A,0F7H
	LD	(H.STKE+0),A
	CALL	C.84E1			; get slot id page 2
	LD	(H.STKE+1),A
	LD	HL,I$4100
	LD	(H.STKE+2),HL		; hook H.STKE
	LD	A,07H	; 7 
	LD	(D.F3EB),A
	LD	A,7			; keyboard row = 7
	CALL	SNSMAT
	AND	04H			; ESC key pressed ?
	JP	NZ,J$8203		; nope,
	CALL	C$8434
J$8203:	DI	
	LD	A,0
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	EI	
	RET	

J.820F:	XOR	A
	LD	(D.C010),A		; environment = none
	JP	C.82CC			; do not start firmware

J$8216:	NOP
	NOP
	NOP
	NOP
	DI	
	LD	A,(D.FAF8)
	OR	A			; MSX1 ?
	JP	Z,J.8256		; yep, show message and halt
	LD	A,(D.FAFC)
	AND	04H			; VRAM size 128 KB ?
	JP	Z,J.8245		; nope, show message and halt
	CALL	C.82E0			; BASIC ROM ?
	JP	C,J.8243		; yep, quit
	DI	
	LD	A,(H.STKE+0)
	CP	0C9H			; H.STKE hooked ?
	JP	NZ,J.8243		; yep, quit
	LD	A,07H	; 7 
	LD	(D.F3EB),A
	CALL	C.84E1			; get slot id page 2
	AND	A
	RET	

J.8243:	SCF	
	RET	
;
;	-----------------
J.8245:	LD	A,(CPMADR)
	LD	(D.D49F),A
	LD	A,(D.0007)
	LD	(D.D4A0),A
	CALL	C.B554			; show ? message
	JR	J.8265
;
;	-----------------
J.8256:	LD	A,(CPMADR)
	LD	(D.D49F),A
	LD	A,(D.0007)
	LD	(D.D4A0),A
	CALL	C.B56D			; show ? message
J.8265:	JR	J.8265			; halt

;	  Subroutine check for panasonic JIS2 ROM
;	     Inputs  ________________________
;	     Outputs ________________________

C$8267:	XOR	A
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,90H
	LD	(D.7800),A		; select panasonic JIS2 ROM on page 2 (A000H-BFFFH)
	LD	DE,0
	LD	HL,I.A000
	LD	BC,128
J$8279:	PUSH	HL
	LD	A,(HL)
	LD	H,0
	LD	L,A
	ADD	HL,DE
	PUSH	HL
	POP	DE
	POP	HL
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$8279
	LD	HL,I$0EAA
	AND	A
	SBC	HL,DE			; checksum match for panasonic JIS2 ROM ?
	JR	NZ,J$8293		; nope,
	AND	A
	JR	J$8294

J$8293:	SCF	
J$8294:	PUSH	AF
	XOR	A
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,13H
	LD	(D.7800),A		; select ROM page 2
	POP	AF
	RET	
;
;	-----------------
J$82A0:	CALL	C.82CC			; do not start firmware
	LD	HL,I.815A		; JWrite
	LD	DE,D.C010
	LD	BC,6
	LDIR				; environment = JWrite
	CALL	C$B61C			; select ROM BIOS on page 0
	LD	A,(D.CE6C)
	LD	(H.KEYI+0),A
	LD	A,(D.D49E)
	BIT	7,A			; no turbo flag ?
	JR	NZ,J$82C8		; yep, skip CPU
	LD	A,08H
	OUT	(40H),A			; Matsushita switchable I/O
	IN	A,(41H)
	OR	01H
	OUT	(41H),A			; select normal CPU
J$82C8:	EI	
	JP	0			; reboot
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.82CC:	DI	
	LD	A,0
	LD	(D.7FF9),A		; segments registers not readable
	LD	A,12
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	EI	
	CALL	C$402B
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.82E0:	DI	
	LD	A,81H
	LD	(D.7800),A		; select SRAM page 2
	EI	
	LD	A,0FFH
	LD	(D.BF51),A		; no MOUF1
	LD	(D.BF52),A		; no JWrite EXTEND
J$82EF:	PUSH	DE
	LD	L,D
	LD	H,0
	LD	BC,D.FCC1
	ADD	HL,BC
	LD	A,(HL)
	AND	80H			; slot expanded ?
	JR	NZ,J$830C		; yep,
	LD	A,D			; slot id
	LD	B,3			; page = 2
J$82FF:	CALL	C.8348
	JR	NC,J$8307		; not found,
	POP	DE
	JR	J.8340			; quit

J$8307:	DEC	B
	JR	NZ,J$82FF		; next page
	JR	J$8339			; next slot

J$830C:	LD	C,4
J$830E:	PUSH	BC
	DEC	C
	JR	NZ,J$8316
	LD	A,80H			; secundairy slot 0
	JR	J.8326

J$8316:	DEC	C
	JR	NZ,J$831D
	LD	A,84H			; secundairy slot 1
	JR	J.8326

J$831D:	DEC	C
	JR	NZ,J$8324
	LD	A,88H			; secundairy slot 2
	JR	J.8326

J$8324:	LD	A,8CH			; secundairy slot 3
J.8326:	OR	D
	LD	B,3			; page = 2
J$8329:	CALL	C.8348
	JR	NC,J$8332		; not found,
	POP	BC
	POP	DE
	JR	J.8340			; quit

J$8332:	DEC	B
	JR	NZ,J$8329		; next page
	POP	BC
	DEC	C
	JR	NZ,J$830E		; next secundairy slot
J$8339:	POP	DE
	DEC	D
	JP	NZ,J$82EF		; next slot
	LD	A,1
J.8340:	DI	
	LD	A,11
	LD	(D.7800),A		; select ROM page 2
	EI	
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.8348:	PUSH	DE
	PUSH	BC
	DEC	B
	JR	NZ,J$8352
	LD	HL,0
	JR	J.835D

J$8352:	DEC	B
	JR	NZ,J$835A
	LD	HL,D.4000
	JR	J.835D

J$835A:	LD	HL,I$8000
J.835D:	PUSH	AF
	CALL	RDSLT
	CP	"A"			; ROM extension ?
	JR	NZ,J.8386		; nope,
	POP	AF
	INC	HL
	PUSH	AF
	CALL	RDSLT
	CP	"B"			; ROM extension ?
	JR	NZ,J.8386		; nope,
	POP	AF
	LD	BC,8-1
	ADD	HL,BC
	PUSH	AF
	CALL	RDSLT
	OR	A			; ROM extension with BASIC program ?
	JP	NZ,J.8417		; yep, quit
	POP	AF
	INC	HL
	PUSH	AF
	CALL	RDSLT
	OR	A			; ROM extension with BASIC program ?
	JP	NZ,J.8417		; yep, quit
J.8386:	POP	AF
	LD	IX,I$841C		; MOUF1
	LD	BC,7
	PUSH	AF
J$838F:	POP	AF
	PUSH	IX
	POP	IY
	ADD	IY,BC
	LD	HL,I.4010
	ADD	HL,BC
	PUSH	AF
	PUSH	BC
	CALL	RDSLT
	POP	BC
	LD	D,A
	POP	AF
	PUSH	AF
	PUSH	IY
	POP	HL
	LD	A,(HL)
	CP	D
	JR	NZ,J$83AF		; not found,
	DEC	C
	JR	NZ,J$838F
	JR	J$83D8			; MOUF1 found
;
;	-----------------
J$83AF:	POP	AF
	LD	IX,I$8424		; JWrite EXTEND
	LD	BC,15
	PUSH	AF
J$83B8:	POP	AF
	PUSH	IX
	POP	IY
	ADD	IY,BC
	LD	HL,I.4010
	ADD	HL,BC
	PUSH	AF
	PUSH	BC
	CALL	RDSLT
	POP	BC
	LD	D,A
	POP	AF
	PUSH	AF
	PUSH	IY
	POP	HL
	LD	A,(HL)
	CP	D
	JR	NZ,J$8413		; quit (not found)
	DEC	C
	JR	NZ,J$83B8
	JR	J$83DE			; JWrite EXTEND found
;
;	-----------------
J$83D8:	POP	AF
	LD	(D.BF51),A		; store slot id MOUF1
	JR	J.8414
;
;	-----------------
J$83DE:	POP	AF
	LD	(D.BF52),A		; store slot id JWrite EXTEND
	LD	HL,I$4023
	PUSH	AF
	PUSH	HL
	CALL	RDSLT
	LD	(D$BF53+0),A
	POP	HL
	POP	AF
	INC	HL
	PUSH	AF
	PUSH	HL
	CALL	RDSLT
	LD	(D$BF53+1),A		; address ? entry
	POP	HL
	POP	AF
	INC	HL
	INC	HL
	PUSH	AF
	PUSH	HL
	CALL	RDSLT
	LD	(D$BF55+0),A
	POP	HL
	POP	AF
	INC	HL
	PUSH	AF
	PUSH	HL
	CALL	RDSLT
	LD	(D$BF55+1),A		; address ? entry
	POP	HL
	POP	AF
	JR	J.8414
;
;	-----------------
J$8413:	POP	AF
J.8414:	POP	BC
	POP	DE
	RET	
;
;	-----------------
J.8417:	POP	AF
	POP	BC
	POP	DE
	SCF	
	RET	
;
;	-----------------
I$841C:	LD	C,L
	LD	C,A
	LD	D,L
	LD	B,(HL)
	LD	SP,I$2020
	JR	NZ,J$846F
I$8424	EQU	$-1
;
	LD	D,A
	LD	(HL),D
	LD	L,C
J$8428:	LD	(HL),H
	LD	H,L
	JR	NZ,J$8471
;
	LD	E,B
	LD	D,H
	LD	B,L
	LD	C,(HL)
	LD	B,H
	JR	NZ,J$8453
;
	JR	NZ,J$8428
C$8434	EQU	$-1
;
	LD	A,81H
	LD	(D.7800),A		; select SRAM page 2
	LD	HL,I.A000
	LD	(HL),4DH	; "M"
	INC	HL
	LD	(HL),53H	; "S"
	INC	HL
	LD	(HL),58H	; "X"
	LD	HL,I$A400
	LD	(HL),4DH	; "M"
	INC	HL
	LD	(HL),53H	; "S"
	INC	HL
	LD	(HL),58H	; "X"
	LD	HL,I$B400
J$8453:	LD	DE,I$B401
	LD	BC,I$0B40
	LD	(HL),00H
	LDIR	
	LD	HL,I.A800
	LD	DE,I$A801
	LD	BC,I$01FF
	LD	(HL),0FFH
	LDIR	
	LD	IX,I.A800
	LD	A,01H	; 1 
J$846F	EQU	$-1
	LD	(IX),A
J$8471	EQU	$-2
	LD	A,14H	; 20 
	LD	(IX+6),A
	LD	A,29H	; ")"
	LD	(IX+12),A
	LD	A,3DH	; "="
	LD	(IX+18),A
	LD	A,49H	; "I"
	LD	(IX+24),A
	LD	HL,I$AA00
	LD	DE,I$AA01
	LD	BC,I$09FF
	LD	(HL),00H
	LDIR	
	LD	HL,I$BF41
	LD	DE,I$BF42
	LD	BC,I.000F
	LD	(HL),00H
	LDIR	
	LD	A,11
	LD	(D.7800),A		; select ROM page 2
	LD	HL,I$84C7
	LD	B,02H	; 2 
	LD	C,20H	; " "
J$84AD:	PUSH	BC
	LD	B,13
J$84B0:	LD	A,(HL)
	LD	IX,WRTCLK
	PUSH	BC
	PUSH	HL
	CALL	EXTROM
	POP	HL
	POP	BC
	INC	HL
	INC	C
	DJNZ	J$84B0
	POP	BC
	LD	C,30H	; "0"
	DJNZ	J$84AD
	EI	
	RET	
;
;	-----------------
I$84C7:	LD	A,(BC)
	DEFB	0,0
	LD	BC,I$010D
	RRCA	
	INC	B
	RLCA	
	INC	BC
	LD	(BC),A
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.84E1:	DI	
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,D.FCC1
	IN	A,(0A8H)
	AND	30H			; keep page 2
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	LD	C,A
	LD	B,00H
	AND	A
	ADD	HL,BC
	LD	A,(HL)
	RLCA				; slot expanded ?
	JR	C,J$8503		; yep
	IN	A,(0A8H)
	AND	30H	; "0"
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	JR	J$8527

J$8503:	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	30H	; "0"
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	30H			; keep page 2
	RRCA	
	RRCA	
	LD	E,A
	LD	A,B
	OUT	(0A8H),A
	AND	30H	; "0"
	RRCA	
	RRCA	
	RRCA	
	RRCA	
	OR	E
	OR	80H
J$8527:	POP	HL
	POP	DE
	POP	BC
	EI	
	RET	
;
;	-----------------
J$852C:	PUSH	AF
	LD	A,(D$C354)
	CP	02H	; 2 
	JR	NZ,J$8537
;
	CALL	C$8543
;
J$8537:	LD	A,(D$C355)
	CP	02H	; 2 
	JR	NZ,J$8541
;
	CALL	C$8602
;
J$8541:	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8543:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	HL,(D.C337)
	LD	A,L
	SUB	18H
	JR	NC,J$8552
;
	XOR	A
J$8552:	LD	(D.C3EC),A
	LD	HL,I.D2DD
	LD	DE,I.D3FD
	LD	B,48H	; "H"
	XOR	A
J$855E:	LD	(HL),A
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$855E
;
	CALL	C.8AC7
;
	LD	A,(D.C3EC)
	LD	B,A
	LD	HL,(D.C337)
	LD	A,L
	SUB	B
	LD	(D.C3EF),A
	LD	HL,(D.C337)
	LD	A,L
	CP	31H	; "1"
	JR	C,J$8592
;
	XOR	A
	LD	(D.C3ED),A
	LD	HL,(D.C337)
	LD	BC,I$0030
	AND	A
	SBC	HL,BC
	LD	A,L
	DEC	A
	LD	B,A
	ADD	A,B
	ADD	A,B
	LD	(D.C3EE),A
	JR	J$85AD
;
;	-----------------
J$8592:	XOR	A
	LD	(D.C3EE),A
	LD	HL,(D.C337)
	LD	A,L
	LD	B,00H
J$859C:	SUB	02H	; 2 
	JR	Z,J$85A4
;
	INC	B
	JR	NC,J$859C
;
	DEC	B
J$85A4:	LD	A,17H
	SUB	B
	LD	B,A
	ADD	A,B
	ADD	A,B
	LD	(D.C3ED),A
J$85AD:	LD	HL,I.D2DD
	LD	BC,(D.C3ED)
	LD	B,00H
	ADD	HL,BC
	LD	IX,I.D3FD
	LD	BC,(D.C3EE)
	LD	B,00H
	ADD	IX,BC
	PUSH	IX
	POP	DE
	LD	BC,(D.C337)
	LD	A,C
	RRA	
	JR	NC,J.85DF
;
	LD	B,03H	; 3 
J$85D0:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$85D0
;
	LD	A,(D.C3EF)
	DEC	A
	LD	(D.C3EF),A
	JR	Z,J.85F8
;
J.85DF:	LD	B,03H	; 3 
J$85E1:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$85E1
;
	LD	A,(D.C3EF)
	DEC	A
	LD	(D.C3EF),A
	JR	Z,J.85F8
;
	RRA	
	JR	NC,J.85DF
;
	DEC	HL
	DEC	HL
	DEC	HL
	JR	J.85DF
;
;	-----------------
J.85F8:	CALL	C$8A75
;
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8602:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	HL,I.D1BD
	LD	DE,I.D2DD
	LD	BC,I.0048
	LDIR	
	LD	HL,I.D2DD
	LD	DE,I.D1BD
	LD	C,30H	; "0"
J.861B:	LD	B,03H	; 3 
J$861D:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$861D
;
	DEC	C
	JR	Z,J$862F
;
	LD	A,C
	RRA	
	JR	NC,J.861B
;
	DEC	HL
	DEC	HL
	DEC	HL
	JR	J.861B
;
;	-----------------
J$862F:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$8636:	PUSH	AF
	LD	A,04H	; 4 
	CALL	C.863E
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.863E:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,A
	AND	03H	; 3 
	LD	A,B
	JR	Z,J$866E
;
	CALL	C.8AC7
;
	RRCA	
	JR	NC,J$865A
;
	LD	HL,I$D2E0
	LD	DE,I.D2DD
	LD	BC,I.0045
	CALL	C.A171
;
J$865A:	RRCA	
	JR	NC,J$8669
;
	LD	HL,I$D321
	LD	DE,I.D324
	LD	BC,I.0045
	CALL	C.A184
J$8669:	CALL	C.8941
	JR	J$8670
;
;	-----------------
J$866E:	RRCA	
	RRCA	
J$8670:	RRCA	
	JR	NC,J$867F
;
	LD	HL,I.D1C0
	LD	DE,I.D1BD
	LD	BC,I.0045
	CALL	C.A171
;
J$867F:	RRCA	
	JR	NC,J$868E
;
	LD	HL,I.D201
	LD	DE,I.D204
	LD	BC,I.0045
	CALL	C.A184
;
J$868E:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$8693:	PUSH	BC
	PUSH	IX
	LD	B,16H
	LD	C,00H
	LD	IX,I$86A5
	CALL	C.86FB
;
	POP	IX
	POP	BC
	RET	
;
;	-----------------
I$86A5:	JR	J$86A6
J$86A6	EQU	$-1
;
;	-----------------
?.86A7:	RST	38H
	RST	38H
	NOP	
J$86AA:	PUSH	BC
	PUSH	IX
	LD	B,0AH	; 10 
	LD	C,00H
	LD	IX,I$86BC
	CALL	C.86FB
;
	POP	IX
	POP	BC
	RET	
;
;	-----------------
I$86BC:	INC	C
	RST	38H
	RST	38H
	RST	38H
	INC	C
	DEFB	0,0,0,0
J$86C5:	PUSH	BC
	PUSH	IX
	LD	B,0AH	; 10 
	LD	C,08H	; 8 
	LD	IX,I$86D7
	CALL	C.86FB
;
	POP	IX
	POP	BC
	RET	
;
;	-----------------
I$86D7:	INC	C
	RST	38H
	RRCA	
	RST	38H
	INC	C
	DEFB	0,0,0,0
J$86E0:	PUSH	BC
	PUSH	IX
	LD	B,04H	; 4 
	LD	C,08H	; 8 
	LD	IX,I$86F2
	CALL	C.86FB
;
	POP	IX
	POP	BC
	RET	
;
;	-----------------
I$86F2:	LD	B,0FFH
	RRCA	
	NOP	
	LD	(DE),A
	DEFB	0,0,0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.86FB:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	BC
	LD	HL,I.D1BD
	LD	DE,I.D325
	LD	BC,I.0048
	LDIR	
	LD	A,0FH	; 15 
	CALL	C.863E
;
	LD	HL,I.D1BD
J$8715:	LD	A,(IX)
	AND	A
	JR	Z,J$873A
;
	LD	B,A
J$871C:	LD	A,(HL)
	AND	(IX+1)
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	AND	(IX+2)
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	AND	(IX+3)
	LD	(HL),A
	INC	HL
	DJNZ	J$871C
;
	INC	IX
	INC	IX
	INC	IX
	INC	IX
	JR	J$8715
;
;	-----------------
J$873A:	LD	HL,I$D328
	LD	DE,I.D1C0
	POP	BC
J$8741:	LD	A,(DE)
	XOR	(HL)
	LD	(DE),A
	EX	DE,HL
	LD	A,(DE)
	AND	01H	; 1 
	OR	(HL)
	LD	(HL),A
	EX	DE,HL
	INC	HL
	INC	DE
	LD	A,(DE)
	XOR	(HL)
	LD	(DE),A
	EX	DE,HL
	LD	A,(DE)
	AND	C
	OR	(HL)
	LD	(HL),A
	EX	DE,HL
	INC	HL
	INC	DE
	LD	A,(DE)
	XOR	(HL)
	LD	(DE),A
	EX	DE,HL
	LD	A,(DE)
	AND	80H
	OR	(HL)
	LD	(HL),A
	EX	DE,HL
	INC	HL
	INC	DE
	DJNZ	J$8741
;
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.876D:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.8B21
;
	CALL	C$8B73
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.877C:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.8B21
;
	CALL	C$8BC5
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.878B:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.8B21
;
	LD	HL,I$D354
	LD	B,10H	; 16 
	XOR	A
J$8798:	LD	(HL),A
	DEC	HL
	DJNZ	J$8798
;
	EX	DE,HL
	LD	HL,I.D324
	LD	BC,C.0018
	LDDR	
	EX	DE,HL
	LD	B,08H	; 8 
J$87A8:	LD	(HL),A
	DEC	HL
	DJNZ	J$87A8
;
	EX	DE,HL
	LD	HL,I$D30C
	LD	BC,C.0018
	LDDR	
	EX	DE,HL
	LD	B,10H	; 16 
J$87B8:	LD	(HL),A
	DEC	HL
	DJNZ	J$87B8
;
	EX	DE,HL
	LD	HL,I$D2F4
	LD	BC,C.0018
	LDDR	
	EX	DE,HL
	LD	B,08H	; 8 
J$87C8:	LD	(HL),A
	DEC	HL
	DJNZ	J$87C8
;
	LD	HL,I.D2E5
	CALL	C.87E6
;
	LD	HL,I.D31D
	CALL	C$880B
;
	LD	HL,I.D32D
	CALL	C.87E6
;
	CALL	C$89ED
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.87E6:	LD	B,03H	; 3 
	LD	DE,C.0008
J$87EB:	LD	C,02H	; 2 
J$87ED:	PUSH	BC
J$87EE:	PUSH	HL
	SRL	(HL)
	RLA	
	ADD	HL,DE
	RRA	
	RR	(HL)
	RLA	
	ADD	HL,DE
	RRA	
	RR	(HL)
	RLA	
	ADD	HL,DE
	RRA	
	RR	(HL)
	POP	HL
	DJNZ	J$87EE
;
	POP	BC
	INC	HL
	DEC	C
	JR	NZ,J$87ED
;
	DJNZ	J$87EB
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$880B:	LD	B,01H	; 1 
	LD	DE,I$FFF8
J$8810:	LD	C,02H	; 2 
J$8812:	PUSH	BC
J$8813:	PUSH	HL
	SLA	(HL)
	RLA	
	ADD	HL,DE
	RRA	
	RL	(HL)
	RLA	
	ADD	HL,DE
	RRA	
	RL	(HL)
	RLA	
	ADD	HL,DE
	RRA	
	RL	(HL)
	POP	HL
	DJNZ	J$8813
;
	POP	BC
	INC	HL
	DEC	C
	JR	NZ,J$8812
;
	INC	B
	LD	A,B
	CP	05H	; 5 
	JR	NZ,J$8810
;
	RET	
;
;	-----------------
J$8834:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.878B
;
	LD	HL,I$D1CF
	LD	DE,I.D1BD
	LD	BC,I$0057
	LDIR	
	XOR	A
	LD	B,15H
J$8849:	LD	(DE),A
	INC	DE
	DJNZ	J$8849
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$8852:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I.D1BD
	LD	DE,I.D2DD
	CALL	C.8C2F
;
	LD	HL,I.D2DD
	SRL	(HL)
	SRL	(HL)
	INC	HL
	SRL	(HL)
	SRL	(HL)
	INC	HL
	SRL	(HL)
	INC	HL
	SRL	(HL)
	LD	HL,I.D2DD
	LD	DE,I.D1BD
	CALL	C.8C5D
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$887F:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I.D1BD
	LD	DE,I.D2DD
	LD	BC,I$0012
	LDIR	
	LD	HL,I.D2DD
	LD	DE,I.D2EF
	LD	B,06H	; 6 
J$8896:	XOR	A
	PUSH	HL
	LD	B,06H	; 6 
J$889A:	RRC	(HL)
	RLA	
	INC	HL
	INC	HL
	INC	HL
	DJNZ	J$889A
;
	LD	(DE),A
	INC	DE
	POP	HL
	DJNZ	J$8896
;
	LD	HL,I.D2EF
	LD	DE,I.D1BD
	LD	BC,CPMADR
J$88B0:	LDI	
	INC	DE
	INC	DE
	JR	NZ,J$88B0
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.88BB:	PUSH	AF
	LD	HL,I.D1BD
	XOR	A
	LD	B,11H	; 17 
J$88C2:	LD	D,(HL)
	LD	(HL),A
	INC	HL
	LD	E,(HL)
	SLA	D
	RL	E
	SLA	D
	RL	E
	SLA	D
	RL	E
	SLA	D
	RL	E
	LD	(HL),D
	INC	HL
	LD	(HL),E
	INC	HL
	DJNZ	J$88C2
;
	POP	AF
	RET	
;
;	-----------------
J$88DE:	PUSH	AF
	LD	HL,I.D1BD
	XOR	A
	LD	B,0CH	; 12 
J$88E5:	INC	HL
	LD	D,(HL)
	INC	HL
	LD	E,(HL)
	LD	(HL),A
	DEC	HL
	SRL	E
	RR	D
	SRL	E
	RR	D
	SRL	E
	RR	D
	SRL	E
	RR	D
	LD	(HL),E
	DEC	HL
	LD	(HL),D
	INC	HL
	INC	HL
	INC	HL
	DJNZ	J$88E5
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8905:	PUSH	AF
	LD	HL,I.D1BD
	LD	DE,I.D1E1
	LD	BC,I.0024
	LDIR	
	LD	HL,I.D1BD
	XOR	A
	LD	B,24H	; "$"
J$8917:	LD	(HL),A
	INC	HL
	DJNZ	J$8917
;
	POP	AF
	RET	
;
;	-----------------
J$891D:	PUSH	AF
	LD	HL,I.D1BD
	LD	B,08H	; 8 
J$8923:	XOR	A
	LD	D,(HL)
	SLA	D
	SLA	D
	SLA	D
	RL	A
	SLA	D
	RL	A
	SLA	D
	RL	A
	SLA	D
	RL	A
	LD	(HL),D
	INC	HL
	LD	(HL),A
	INC	HL
	DJNZ	J$8923
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8941:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I.D2DD
	LD	DE,I.D1BD
	CALL	C.8C45
	LD	HL,I.D2DE
	LD	DE,I.D1D5
	CALL	C.8C45
	LD	HL,I.D2DF
	LD	DE,I.D1ED
	CALL	C.8C45
	LD	HL,I.D2F5
	LD	DE,I.D1BE
	CALL	C.8C45
	LD	HL,I.D2F6
	LD	DE,I.D1D6
	CALL	C.8C45
	LD	HL,I.D2F7
	LD	DE,I.D1EE
	CALL	C.8C45
	LD	HL,I.D30D
	LD	DE,I.D1BF
	CALL	C.8C45
	LD	HL,I.D30E
	LD	DE,I.D1D7
	CALL	C.8C45
	LD	HL,I.D30F
	LD	DE,I.D1EF
	CALL	C.8C45
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.899B:	LD	HL,I.D2DD
	LD	DE,I.D1BD
	CALL	C.8C5D
;
	LD	HL,I.D2E5
	LD	DE,I.D1D5
	CALL	C.8C5D
;
	LD	HL,I.D2ED
	LD	DE,I.D1ED
	CALL	C.8C5D
;
	LD	HL,I.D2F5
	LD	DE,I.D1BE
	CALL	C.8C5D
;
	LD	HL,I.D2FD
	LD	DE,I.D1D6
	CALL	C.8C5D
;
	LD	HL,I.D305
	LD	DE,I.D1EE
	CALL	C.8C5D
;
	LD	HL,I.D30D
	LD	DE,I.D1BF
	CALL	C.8C5D
;
	LD	HL,I.D315
	LD	DE,I.D1D7
	CALL	C.8C5D
;
	LD	HL,I.D31D
	LD	DE,I.D1EF
	CALL	C.8C5D
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$89ED:	LD	HL,I.D2DD
	LD	DE,I.D1BD
	CALL	C.8C5D
;
	LD	HL,I.D2E5
	LD	DE,I.D1D5
	CALL	C.8C5D
;
	LD	HL,I.D2ED
	LD	DE,I.D1ED
	CALL	C.8C5D
;
	LD	HL,I.D2F5
	LD	DE,I$D205
	CALL	C.8C5D
;
	LD	HL,I.D2FD
	LD	DE,I$D21D
	CALL	C.8C5D
;
	LD	HL,I.D305
	LD	DE,I.D1BE
	CALL	C.8C5D
;
	LD	HL,I.D30D
	LD	DE,I.D1D6
	CALL	C.8C5D
;
	LD	HL,I.D315
	LD	DE,I.D1EE
	CALL	C.8C5D
;
	LD	HL,I.D31D
	LD	DE,I$D206
	CALL	C.8C5D
;
	LD	HL,I.D325
	LD	DE,I$D21E
	CALL	C.8C5D
;
	LD	HL,I.D32D
	LD	DE,I.D1BF
	CALL	C.8C5D
;
	LD	HL,I$D335
	LD	DE,I.D1D7
	CALL	C.8C5D
;
	LD	HL,I$D33D
	LD	DE,I.D1EF
	CALL	C.8C5D
;
	LD	HL,I$D345
	LD	DE,I$D207
	CALL	C.8C5D
;
	LD	HL,I$D34D
	LD	DE,I$D21F
	CALL	C.8C5D
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8A75:	LD	HL,I.D3FD
	LD	DE,I.D1BD
	CALL	C.8C45
	LD	HL,I.D3FE
	LD	DE,I.D1D5
	CALL	C.8C45
;
	LD	HL,I$D3FF
	LD	DE,I.D1ED
	CALL	C.8C45
;
	LD	HL,I$D415
	LD	DE,I.D1BE
	CALL	C.8C45
;
	LD	HL,I$D416
	LD	DE,I.D1D6
	CALL	C.8C45
;
	LD	HL,D.D417
	LD	DE,I.D1EE
	CALL	C.8C45
;
	LD	HL,I$D42D
	LD	DE,I.D1BF
	CALL	C.8C45
;
	LD	HL,I$D42E
	LD	DE,I.D1D7
	CALL	C.8C45
;
	LD	HL,I$D42F
	LD	DE,I.D1EF
	CALL	C.8C45
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8AC7:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	DE,I.D2DD
	LD	HL,I.D1BD
	CALL	C.8C17
;
	LD	DE,I.D2DE
	LD	HL,I.D1D5
	CALL	C.8C17
;
	LD	DE,I.D2DF
	LD	HL,I.D1ED
	CALL	C.8C17
;
	LD	DE,I.D2F5
	LD	HL,I.D1BE
	CALL	C.8C17
;
	LD	DE,I.D2F6
	LD	HL,I.D1D6
	CALL	C.8C17
;
	LD	DE,I.D2F7
	LD	HL,I.D1EE
	CALL	C.8C17
;
	LD	DE,I.D30D
	LD	HL,I.D1BF
	CALL	C.8C17
;
	LD	DE,I.D30E
	LD	HL,I.D1D7
	CALL	C.8C17
;
	LD	DE,I.D30F
	LD	HL,I.D1EF
	CALL	C.8C17
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8B21:	LD	DE,I.D2DD
	LD	HL,I.D1BD
	CALL	C.8C2F
;
	LD	DE,I.D2E5
	LD	HL,I.D1D5
	CALL	C.8C2F
;
	LD	DE,I.D2ED
	LD	HL,I.D1ED
	CALL	C.8C2F
;
	LD	DE,I.D2F5
	LD	HL,I.D1BE
	CALL	C.8C2F
;
	LD	DE,I.D2FD
	LD	HL,I.D1D6
	CALL	C.8C2F
;
	LD	DE,I.D305
	LD	HL,I.D1EE
	CALL	C.8C2F
;
	LD	DE,I.D30D
	LD	HL,I.D1BF
	CALL	C.8C2F
;
	LD	DE,I.D315
	LD	HL,I.D1D7
	CALL	C.8C2F
;
	LD	DE,I.D31D
	LD	HL,I.D1EF
	CALL	C.8C2F
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8B73:	LD	HL,I.D2DD
	LD	DE,I.D1BF
	CALL	C.8C73
;
	LD	HL,I.D2E5
	LD	DE,I.D1BE
	CALL	C.8C73
;
	LD	HL,I.D2ED
	LD	DE,I.D1BD
	CALL	C.8C73
;
	LD	HL,I.D2F5
	LD	DE,I.D1D7
	CALL	C.8C73
;
	LD	HL,I.D2FD
	LD	DE,I.D1D6
	CALL	C.8C73
;
	LD	HL,I.D305
	LD	DE,I.D1D5
	CALL	C.8C73
;
	LD	HL,I.D30D
	LD	DE,I.D1EF
	CALL	C.8C73
;
	LD	HL,I.D315
	LD	DE,I.D1EE
	CALL	C.8C73
;
	LD	HL,I.D31D
	LD	DE,I.D1ED
	CALL	C.8C73
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8BC5:	LD	HL,I.D2DD
	LD	DE,I.D202
	CALL	C.8C7E
;
	LD	HL,I.D2E5
	LD	DE,I$D203
	CALL	C.8C7E
;
	LD	HL,I.D2ED
	LD	DE,I.D204
	CALL	C.8C7E
;
	LD	HL,I.D2F5
	LD	DE,I$D1EA
	CALL	C.8C7E
;
	LD	HL,I.D2FD
	LD	DE,I$D1EB
	CALL	C.8C7E
;
	LD	HL,I.D305
	LD	DE,I$D1EC
	CALL	C.8C7E
;
	LD	HL,I.D30D
	LD	DE,I$D1D2
	CALL	C.8C7E
;
	LD	HL,I.D315
	LD	DE,I$D1D3
	CALL	C.8C7E
;
	LD	HL,I.D31D
	LD	DE,I$D1D4
	CALL	C.8C7E
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8C17:	PUSH	HL
	LD	C,08H	; 8 
J$8C1A:	LD	B,08H	; 8 
	POP	HL
	PUSH	HL
J$8C1E:	RRC	(HL)
	INC	HL
	INC	HL
	INC	HL
	RLA	
	DJNZ	J$8C1E
;
	LD	(DE),A
	INC	DE
	INC	DE
	INC	DE
	DEC	C
	JR	NZ,J$8C1A
;
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8C2F:	PUSH	HL
	LD	C,08H	; 8 
J$8C32:	LD	B,08H	; 8 
	POP	HL
	PUSH	HL
J$8C36:	RRC	(HL)
	INC	HL
	INC	HL
	INC	HL
	RLA	
	DJNZ	J$8C36
;
	LD	(DE),A
	INC	DE
	DEC	C
	JR	NZ,J$8C32
;
	POP	HL
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.8C45:	PUSH	HL
	LD	C,08H	; 8 
J$8C48:	LD	B,08H	; 8 
	POP	HL
	PUSH	HL
J$8C4C:	RLC	(HL)
	INC	HL
	INC	HL
	INC	HL
	RRA	
	DJNZ	J$8C4C
	LD	(DE),A
	INC	DE
	INC	DE
	INC	DE
	DEC	C
	JR	NZ,J$8C48
	POP	HL
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8C5D:	PUSH	HL
	LD	C,08H	; 8 
J$8C60:	LD	B,08H	; 8 
	POP	HL
	PUSH	HL
J$8C64:	RLC	(HL)
	INC	HL
	RRA	
	DJNZ	J$8C64
;
	LD	(DE),A
	INC	DE
	INC	DE
	INC	DE
	DEC	C
	JR	NZ,J$8C60
;
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8C73:	LD	B,08H	; 8 
J$8C75:	LD	A,(HL)
	INC	HL
	LD	(DE),A
	INC	DE
	INC	DE
	INC	DE
	DJNZ	J$8C75
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8C7E:	LD	BC,I$0808
J$8C81:	PUSH	BC
	LD	C,(HL)
	INC	HL
J$8C84:	RLC	C
	RRA	
	DJNZ	J$8C84
;
	LD	(DE),A
	DEC	DE
	DEC	DE
	DEC	DE
	POP	BC
	DEC	C
	JR	NZ,J$8C81
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8C92:	CALL	C.8CAB
;
	CALL	C.8D75
;
	AND	A
	JR	Z,J$8CAA
;
	CALL	C$8DEE
;
	CALL	C.8CAB
;
	CALL	C.8D75
;
	CALL	C$8E2B
;
	CALL	C$8DB1
;
J$8CAA:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8CAB:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,I.D3FD
	LD	A,06H	; 6 
	LD	B,1AH
J$8CBA:	LD	(HL),A
	INC	HL
	DJNZ	J$8CBA
;
	LD	IX,I.D1BD
	LD	B,18H
J$8CC4:	PUSH	BC
	LD	IY,I.D3FE
	LD	B,03H	; 3 
J$8CCB:	PUSH	BC
	LD	B,08H	; 8 
J$8CCE:	RRC	(IX)
	LD	HL,I$8D6E
	JR	C,J$8CDA
;
	LD	HL,I$8D67
J$8CDA:	LD	E,(IY)
	LD	D,00H
	ADD	HL,DE
	LD	A,(HL)
	LD	(IY),A
	INC	IY
	DJNZ	J$8CCE
;
	INC	IX
	POP	BC
	DJNZ	J$8CCB
;
	LD	A,0FFH
	LD	(D.D417),A
	LD	(D.D418),A
	LD	(D.D419),A
	LD	IY,I.D3FE
	LD	B,18H
J$8CFE:	LD	A,(IY)
	AND	A
	JR	NZ,J.8D27
;
	LD	A,(IY-1)
	CP	01H	; 1 
	JR	NZ,J$8D18
;
	LD	A,(IY+1)
	CP	03H	; 3 
	JR	Z,J$8D16
;
	CP	01H	; 1 
	JR	NZ,J.8D2A
;
J$8D16:	JR	J.8D27
;
;	-----------------
J$8D18:	CP	03H	; 3 
	JR	NZ,J$8D25
;
	LD	A,(IY+1)
	CP	01H	; 1 
	JR	Z,J.8D27
;
	JR	J.8D2A
;
;	-----------------
J$8D25:	JR	J.8D2A
;
;	-----------------
J.8D27:	SCF	
	JR	J$8D2F
;
;	-----------------
J.8D2A:	AND	A
	LD	(IY),02H	; 2 
J$8D2F:	LD	HL,D.D419
	RR	(HL)
	DEC	HL
	RR	(HL)
	DEC	HL
	RR	(HL)
	INC	IY
	DJNZ	J$8CFE
;
	LD	A,(D.D417)
	AND	(IX-6)
	LD	(IX-6),A
	LD	A,(D.D418)
	AND	(IX-5)
	LD	(IX-5),A
	LD	A,(D.D419)
	AND	(IX-4)
	LD	(IX-4),A
	POP	BC
	DEC	B
	JP	NZ,J$8CC4
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$8D67:	LD	(BC),A
	LD	(BC),A
	INC	BC
	INC	BC
	LD	BC,I$0200
I$8D6E:	INC	B
	INC	B
	INC	B
	INC	B
	DEC	B
	DEC	B
	INC	B
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.8D75:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	HL,I.D1BD
	LD	IX,I.D1BD
	LD	B,0CH	; 12 
J$8D84:	LD	A,(IX)
	OR	(IX+3)
	LD	(HL),A
	INC	HL
	LD	A,(IX+1)
	OR	(IX+4)
	LD	(HL),A
	INC	HL
	LD	A,(IX+2)
	OR	(IX+5)
	LD	(HL),A
	INC	HL
	LD	DE,CPMADR
	ADD	IX,DE
	DJNZ	J$8D84
;
	XOR	A
	LD	B,24H	; "$"
J$8DA6:	LD	(HL),A
	INC	HL
	DJNZ	J$8DA6
;
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8DB1:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I.D2DD
	LD	DE,I.D202
	LD	B,03H	; 3 
J$8DBC:	PUSH	BC
	PUSH	DE
	LD	B,08H	; 8 
J$8DC0:	PUSH	BC
	PUSH	DE
	LD	B,03H	; 3 
J$8DC4:	PUSH	BC
	LD	B,08H	; 8 
J$8DC7:	EX	DE,HL
	RRC	(HL)
	EX	DE,HL
	RR	(HL)
	DEC	DE
	DEC	DE
	DEC	DE
	DJNZ	J$8DC7
;
	INC	HL
	POP	BC
	DJNZ	J$8DC4
;
	POP	DE
	POP	BC
	DJNZ	J$8DC0
;
	POP	DE
	INC	DE
	POP	BC
	DJNZ	J$8DBC
;
	LD	HL,I.D2DD
	LD	DE,I.D1BD
	LD	BC,I.0048
	LDIR	
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8DEE:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I.D2DD
	LD	DE,I.D1BF
	LD	B,03H	; 3 
J$8DF9:	PUSH	BC
	PUSH	DE
	LD	B,08H	; 8 
J$8DFD:	PUSH	BC
	PUSH	DE
	LD	B,03H	; 3 
J$8E01:	PUSH	BC
	LD	B,08H	; 8 
J$8E04:	EX	DE,HL
	RLC	(HL)
	EX	DE,HL
	RR	(HL)
	INC	DE
	INC	DE
	INC	DE
	DJNZ	J$8E04
;
	INC	HL
	POP	BC
	DJNZ	J$8E01
;
	POP	DE
	POP	BC
	DJNZ	J$8DFD
;
	POP	DE
	DEC	DE
	POP	BC
	DJNZ	J$8DF9
;
	LD	HL,I.D2DD
	LD	DE,I.D1BD
	LD	BC,I.0048
	LDIR	
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8E2B:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.8905
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$8E37:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,(D.C9B0)
	LD	DE,(D.C352)
	AND	A
	SBC	HL,DE
	JP	Z,J.8EC2
;
	LD	A,(D.C327)
	LD	C,A
	LD	B,00H
	LD	HL,(D.C339)
	XOR	A
	SBC	HL,BC
	JR	NC,J$8E5D
;
	LD	A,02H	; 2 
	JR	J$8E60
;
;	-----------------
J$8E5D:	LD	A,02H	; 2 
	ADD	A,L
J$8E60:	LD	(D.C3E2),A
	LD	IX,(D.C9B0)
J$8E67:	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,(IX)
	CALL	C.BD49			; restore slot on page 1
;
	AND	A
	JP	Z,J.8EC2
;
	CALL	C.BCF6			; select RAM on page 1
;
	INC	IX
	LD	L,(IX)
	LD	H,(IX+1)
	LD	(D.C3CA),HL
	LD	L,(IX+2)
	LD	H,(IX+3)
	LD	(D.C3CC),HL
	CALL	C.BD49			; restore slot on page 1
;
	CP	01H	; 1 
	JP	NZ,J$8E98
;
	LD	C,03H	; 3 
	JP	J$8E9F
;
;	-----------------
J$8E98:	CP	02H	; 2 
	JP	NZ,J$8EA5
;
	LD	C,0FH	; 15 
J$8E9F:	CALL	C.93DE
;
	JP	J$8EAF
;
;	-----------------
J$8EA5:	CP	03H	; 3 
	JP	NZ,J.8ECA
;
	LD	C,01H	; 1 
	CALL	C.9495
;
J$8EAF:	LD	BC,I.0004
	ADD	IX,BC
	LD	HL,(D.C352)
	PUSH	IX
	POP	BC
	SBC	HL,BC
	JP	NZ,J$8E67
;
	JP	J.8ECA
;
;	-----------------
J.8EC2:	NOP	
	XOR	A
	LD	(D.C341),A
	JP	J$8ECF
;
;	-----------------
J.8ECA:	LD	A,01H	; 1 
	LD	(D.C341),A
J$8ECF:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$8ED7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,(D.C9B0)
	LD	DE,(D.C352)
	AND	A
	SBC	HL,DE
	JP	Z,J.8F61
;
	LD	A,(D.C327)
	LD	C,A
	LD	B,00H
	LD	HL,(D.C339)
	SBC	HL,BC
	JR	NC,J$8EFC
;
	LD	A,01H	; 1 
	JR	J$8EFF
;
;	-----------------
J$8EFC:	LD	A,01H	; 1 
	ADD	A,L
J$8EFF:	LD	(D.C3E2),A
	LD	IX,(D.C9B0)
J$8F06:	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,(IX)
	CALL	C.BD49			; restore slot on page 1
;
	AND	A
	JP	Z,J.8F61
;
	CALL	C.BCF6			; select RAM on page 1
;
	INC	IX
	LD	L,(IX)
	LD	H,(IX+1)
	LD	(D.C3CA),HL
	LD	L,(IX+2)
	LD	H,(IX+3)
	LD	(D.C3CC),HL
	CALL	C.BD49			; restore slot on page 1
;
	CP	01H	; 1 
	JP	NZ,J$8F37
;
	LD	C,01H	; 1 
	JP	J$8F3E
;
;	-----------------
J$8F37:	CP	02H	; 2 
	JP	NZ,J$8F44
;
	LD	C,03H	; 3 
J$8F3E:	CALL	C.93DE
;
	JP	J$8F4E
;
;	-----------------
J$8F44:	CP	03H	; 3 
	JP	NZ,J.8F69
;
	LD	C,01H	; 1 
	CALL	C.98F4
;
J$8F4E:	LD	BC,I.0004
	ADD	IX,BC
	LD	HL,(D.C352)
	PUSH	IX
	POP	BC
	SBC	HL,BC
	JP	NZ,J$8F06
;
	JP	J.8F69
;
;	-----------------
J.8F61:	NOP	
	XOR	A
	LD	(D.C341),A
	JP	J$8F6E
;
;	-----------------
J.8F69:	LD	A,01H	; 1 
	LD	(D.C341),A
J$8F6E:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$8F76:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	PUSH	DE
	POP	IX
	PUSH	HL
	POP	IY
	LD	A,(D.C3E1)
	AND	A
	JR	Z,J.8F9C
;
	CP	B
	JR	NZ,J.8F9C
;
	LD	HL,(D.C352)
	PUSH	IY
	POP	DE
	DEC	HL
	LD	(HL),D
	DEC	HL
	LD	(HL),E
	JR	J$8FB2
;
;	-----------------
J.8F9C:	LD	HL,(D.C352)
	LD	(HL),B
	PUSH	IX
	POP	DE
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	PUSH	IY
	POP	DE
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(D.C352),HL
J$8FB2:	LD	A,B
	LD	(D.C3E1),A
	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$8FC2:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,(D.C329)
	LD	DE,I.0004
J$8FCF:	AND	A
	SBC	HL,DE
	JR	NC,J$8FCF
;
	ADD	HL,DE
	LD	C,L
	INC	C
	LD	A,(D$C326)
	AND	03H	; 3 
	JR	Z,J.8FF2
;
	CP	01H	; 1 
	JR	Z,J$8FEB
;
	LD	A,(D$C34F)
	LD	B,A
	CALL	C$91ED
;
	JR	J.8FF2
;
;	-----------------
J$8FEB:	LD	A,(D$C34E)
	LD	B,A
	CALL	C$8FFE
;
J.8FF2:	CALL	C.BD49			; restore slot on page 1
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.8FFA:	LD	BC,I$0304
	LD	(BC),A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$8FFE:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,B
	AND	0FH	; 15 
	RLC	A
	RLC	A
	RLC	A
	RLC	A
	LD	B,A
	LD	A,C
	AND	0FH	; 15 
	ADD	A,B
	LD	B,A
	LD	IX,I.5E14
	LD	HL,I$9163
J$901E:	LD	C,02H	; 2 
J$9020:	LD	A,(HL)
	INC	A
	JP	Z,J.915A
;
	DEC	A
	CP	B
	JP	Z,J$9035
;
	INC	HL
	DEC	C
	JP	NZ,J$9020
;
	INC	HL
	INC	HL
	INC	HL
	JP	J$901E
;
;	-----------------
J$9035:	LD	B,00H
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	LD	HL,D.C329
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	PUSH	BC
	DEC	C
	JP	NZ,J$9054
;
	LD	B,00H
	LD	C,03H	; 3 
	ADD	HL,BC
J$9054:	EX	DE,HL
	ADD	IX,DE
	POP	BC
	LD	HL,D.C329
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,D.C32C
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	SBC	HL,DE
	INC	HL
	EX	DE,HL
	POP	HL
	DEC	C
	JR	NZ,J$9073
;
	DEC	DE
	LD	A,D
	OR	E
	JP	Z,J.915A
;
J$9073:	LD	B,00H
J.9075:	PUSH	BC
	LD	IY,I.C3C1
	LD	A,(HL)
	LD	(IY),A
	INC	HL
	LD	A,(HL)
	LD	(IY+1),A
	INC	HL
	LD	A,(HL)
	LD	(IY+2),A
	LD	A,(D.C32B)
	LD	B,A
	INC	B
J$908D:	DEC	B
	JP	Z,J$90BA
;
	SLA	(IY)
	JP	NC,J$90A2
;
	SLA	(IY+1)
	INC	(IY+1)
	JP	J$90A6
;
;	-----------------
J$90A2:	SLA	(IY+1)
J$90A6:	JP	NC,J$90B3
;
	SLA	(IY+2)
	INC	(IY+2)
	JP	J$90B7
;
;	-----------------
J$90B3:	SLA	(IY+2)
J$90B7:	JP	J$908D
;
;	-----------------
J$90BA:	LD	A,(D.C32E)
	INC	A
	CP	08H	; 8 
	JP	NC,J$90DD
;
	PUSH	HL
	LD	HL,J.91E4
	LD	B,00H
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	AND	(IY)
	LD	(IY),A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	POP	HL
	JP	J.910D
;
;	-----------------
J$90DD:	SBC	A,08H	; 8 
	CP	08H	; 8 
	JP	NC,J$90FB
;
	PUSH	HL
	LD	HL,J.91E4
	LD	B,00H
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	AND	(IY+1)
	LD	(IY+1),A
	XOR	A
	LD	(IY+2),A
	POP	HL
	JP	J.910D
;
;	-----------------
J$90FB:	SBC	A,08H	; 8 
	PUSH	HL
	LD	HL,J.91E4
	LD	B,00H
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	AND	(IY+2)
	LD	(IY+2),A
	POP	HL
J.910D:	PUSH	HL
	PUSH	IX
	POP	HL
	LD	BC,I.6EF4
	AND	A
	SBC	HL,BC
	POP	HL
	JR	NC,J.9159
;
	LD	A,(IY)
	OR	(IX)
	LD	(IX),A
	LD	A,(IY+1)
	OR	(IX+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	OR	(IX+2)
	LD	(IX+2),A
	LD	BC,CPMADR
	ADD	IX,BC
	DEC	DE
	LD	A,D
	OR	E
	JR	Z,J.9159
;
	DEC	DE
	LD	A,D
	OR	E
	JR	Z,J.9159
;
	POP	BC
	DEC	B
	JP	Z,J$914F
;
	LD	B,01H	; 1 
	INC	HL
	JP	J.9075
;
;	-----------------
J$914F:	LD	B,00H
	DEC	HL
	DEC	HL
	DEC	HL
	DEC	HL
	DEC	HL
	JP	J.9075
;
;	-----------------
J.9159:	POP	BC
J.915A:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$9163:	LD	DE,C.0053
	OR	H
	SUB	C
	LD	(DE),A
	LD	D,H
	LD	BC,I$91CC
	LD	HL,I.0063
	CP	D
	SUB	C
	LD	(D$0164),HL
	JP	NC,J$3191
;
	LD	(HL),E
	NOP	
	RET	NZ
;
	SUB	C
	LD	(D$0174),A
	RET	C
;
	SUB	C
	LD	B,C
	ADD	A,E
	NOP	
	ADD	A,91H
	LD	B,D
	ADD	A,H
	LD	BC,I$91DE
	LD	D,C
	INC	DE
	NOP	
	CALL	Z,C$5291
;
	INC	D
	LD	BC,I$91B4
	LD	H,C
	INC	HL
	NOP	
	JP	NC,J$6291
;
	INC	H
	LD	BC,I$91BA
	LD	(HL),C
	INC	SP
	NOP	
	RET	C
;
	SUB	C
	LD	(HL),D
	INC	(HL)
	LD	BC,I$91C0
	ADD	A,C
	LD	B,E
	NOP	
	SBC	A,91H
	ADD	A,D
	LD	B,H
	LD	BC,I$91C6
	RST	38H
I$91B4:	LD	(BC),A
	LD	(BC),A
	LD	(BC),A
	JR	NZ,J$91D9
;
	JR	NZ,J$91BC
I$91BA	EQU	$-1
;
	LD	BC,I$1001
J$91BC	EQU	$-2
	DJNZ	J$91D0
;
I$91C0:	ADD	A,B
	ADD	A,B
	ADD	A,B
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
I$91C6:	LD	B,B
	LD	B,B
	LD	B,B
	INC	B
	INC	B
	INC	B
I$91CC:	JR	NZ,J$91EE
;
	JR	NZ,J$91D2
;
J$91D0:	LD	(BC),A
	LD	(BC),A
J$91D2:	DJNZ	J.91E4
;
	DJNZ	J$91D7
;
	LD	BC,I.0801
J$91D7	EQU	$-2
J$91D9:	EX	AF,AF'
	EX	AF,AF'
	ADD	A,B
	ADD	A,B
	ADD	A,B
I$91DE:	INC	B
	INC	B
	INC	B
	LD	B,B
	LD	B,B
	LD	B,B
J.91E4:	NOP	
	LD	BC,I.0703
	RRCA	
	RRA	
	CCF	
	LD	A,A
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$91ED:	PUSH	AF
J$91EE:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,B
	AND	0FH	; 15 
	RLC	A
	RLC	A
	RLC	A
	RLC	A
	LD	B,A
	LD	A,C
	AND	0FH	; 15 
	ADD	A,B
	LD	B,A
	LD	IX,I.5E14
	LD	HL,I$939B
J$920D:	LD	C,01H	; 1 
J$920F:	LD	A,(HL)
	INC	A
	JP	Z,J.9392
;
	DEC	A
	CP	B
	JP	Z,J$9224
;
	INC	HL
	DEC	C
	JP	NZ,J$920F
;
	INC	HL
	INC	HL
	INC	HL
	JP	J$920D
;
;	-----------------
J$9224:	LD	B,00H
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	LD	HL,D.C329
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	A,C
	PUSH	AF
	CP	00H
	JP	Z,J.925C
;
	CP	01H	; 1 
	JP	NZ,J$924D
;
	LD	B,00H
	LD	C,03H	; 3 
	ADD	HL,BC
	JP	J.925C
;
;	-----------------
J$924D:	CP	02H	; 2 
	JP	NZ,J$9257
;
	LD	B,01H	; 1 
	JP	J$925E
;
;	-----------------
J$9257:	LD	B,00H
	LD	C,06H	; 6 
	ADD	HL,BC
J.925C:	LD	B,02H	; 2 
J$925E:	EX	DE,HL
	ADD	IX,DE
	POP	AF
	LD	C,A
	LD	HL,D.C329
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,D.C32C
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	AND	A
	SBC	HL,DE
	INC	HL
	EX	DE,HL
	POP	HL
	LD	A,C
	OR	A
	JR	Z,J.928D
;
	CP	02H	; 2 
	JR	Z,J.928D
;
	DEC	DE
	LD	A,D
	OR	E
	JP	Z,J.9392
;
	DEC	C
	JR	Z,J.928D
;
	DEC	DE
	LD	A,D
	OR	E
	JP	Z,J.9392
;
J.928D:	PUSH	BC
	LD	IY,I.C3C1
	LD	A,(HL)
	LD	(IY),A
	INC	HL
	LD	A,(HL)
	LD	(IY+1),A
	INC	HL
	LD	A,(HL)
	LD	(IY+2),A
	LD	A,(D.C32B)
	LD	B,A
	INC	B
J$92A5:	DEC	B
	JP	Z,J$92D2
;
	SLA	(IY)
	JP	NC,J$92BA
;
	SLA	(IY+1)
	INC	(IY+1)
	JP	J$92BE
;
;	-----------------
J$92BA:	SLA	(IY+1)
J$92BE:	JP	NC,J$92CB
;
	SLA	(IY+2)
	INC	(IY+2)
	JP	J$92CF
;
;	-----------------
J$92CB:	SLA	(IY+2)
J$92CF:	JP	J$92A5
;
;	-----------------
J$92D2:	LD	A,(D.C32E)
	INC	A
	CP	08H	; 8 
	JP	NC,J$92F5
;
	PUSH	HL
	LD	HL,I.93D5
	LD	B,00H
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	AND	(IY)
	LD	(IY),A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	POP	HL
	JP	J.9325
;
;	-----------------
J$92F5:	SBC	A,08H	; 8 
	CP	08H	; 8 
	JP	NC,J$9313
;
	PUSH	HL
	LD	HL,I.93D5
	LD	B,00H
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	AND	(IY+1)
	LD	(IY+1),A
	XOR	A
	LD	(IY+2),A
	POP	HL
	JP	J.9325
;
;	-----------------
J$9313:	SBC	A,08H	; 8 
	PUSH	HL
	LD	HL,I.93D5
	LD	B,00H
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	AND	(IY+2)
	LD	(IY+2),A
	POP	HL
J.9325:	PUSH	HL
	PUSH	IX
	POP	HL
	LD	BC,I.6EF4
	AND	A
	SBC	HL,BC
	POP	HL
	JR	NC,J.9391
;
	LD	A,(IY)
	OR	(IX)
	LD	(IX),A
	LD	A,(IY+1)
	OR	(IX+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	OR	(IX+2)
	LD	(IX+2),A
	LD	BC,I.0003
	ADD	IX,BC
	DEC	DE
	LD	A,D
	AND	D
	JP	NZ,J$935D
;
	LD	A,E
	AND	E
	JP	Z,J.9391
;
J$935D:	POP	BC
	DEC	B
	JP	Z,J$9367
;
	DEC	HL
	DEC	HL
	JP	J.928D
;
;	-----------------
J$9367:	LD	BC,CPMADR
	ADD	IX,BC
	PUSH	HL
	PUSH	IX
	POP	HL
	LD	BC,I.6EF4
	AND	A
	SBC	HL,BC
	POP	HL
	JR	NC,J.9392
;
	DEC	DE
	LD	A,D
	OR	E
	JP	Z,J.9392
;
	DEC	DE
	LD	A,D
	AND	D
	JP	NZ,J$938A
;
	LD	A,E
	AND	E
	JP	Z,J.9392
;
J$938A:	DEC	HL
	DEC	HL
	LD	B,02H	; 2 
	JP	J.928D
;
;	-----------------
J.9391:	POP	BC
J.9392:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$939B:	LD	DE,I$CC01
	SUB	E
	LD	(DE),A
	NOP	
	CALL	Z,C$1393
;
	LD	(BC),A
	CALL	Z,C$1493
;
	INC	BC
	CALL	Z,C$2193
;
	LD	BC,I$93CF
	LD	(D$CF00),HL
	SUB	E
	INC	HL
	LD	(BC),A
	RST	08H
;
	SUB	E
	INC	H
	INC	BC
	RST	08H
;
	SUB	E
	LD	SP,I.D201
	SUB	E
	LD	(D$D200),A
	SUB	E
	INC	SP
	LD	(BC),A
	JP	NC,J$3493
;
	INC	BC
	JP	NC,J$FF93
;
	SUB	D
	INC	H
	LD	C,C
I$93CF:	LD	C,C
	SUB	D
	INC	H
	INC	H
	LD	C,C
	SUB	D
I.93D5:	NOP	
	LD	BC,I.0703
	RRCA	
	RRA	
	CCF	
	LD	A,A
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.93DE:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,(D.C3CA)
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	LD	DE,(D.C3CA)
	LD	HL,(D.C3CC)
	SBC	HL,DE
	EX	DE,HL
	INC	DE
	POP	HL
	LD	IY,I.C3C1
	LD	A,(D.C3E2)
	CP	08H	; 8 
	JP	NC,J$941B
;
	LD	B,A
	LD	A,C
	LD	(IY),A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	JP	J.943F
;
;	-----------------
J$941B:	SUB	08H	; 8 
	CP	08H	; 8 
	JP	NC,J$9431
;
	LD	B,A
	LD	A,C
	LD	(IY+1),A
	XOR	A
	LD	(IY),A
	LD	(IY+2),A
	JP	J.943F
;
;	-----------------
J$9431:	SUB	08H	; 8 
	LD	B,A
	LD	A,C
	LD	(IY+2),A
	XOR	A
	LD	(IY),A
	LD	(IY+1),A
J.943F:	INC	B
J.9440:	DEC	B
	JP	Z,J.946D
;
	SLA	(IY)
	JP	NC,J$9455
;
	SLA	(IY+1)
	INC	(IY+1)
	JP	J$9459
;
;	-----------------
J$9455:	SLA	(IY+1)
J$9459:	JP	NC,J$9466
;
	SLA	(IY+2)
	INC	(IY+2)
	JP	J.9440
;
;	-----------------
J$9466:	SLA	(IY+2)
	JP	J.9440
;
;	-----------------
J.946D:	LD	A,(IY)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(IY+1)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(IY+2)
	OR	(HL)
	LD	(HL),A
	INC	HL
	DEC	DE
	LD	A,D
	AND	D
	JP	NZ,J.946D
;
	LD	A,E
	AND	E
	JP	NZ,J.946D
;
	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9495:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,(D.C3CA)
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	LD	DE,(D.C3CA)
	LD	HL,(D.C3CC)
	SBC	HL,DE
	EX	DE,HL
	INC	DE
J.94B6:	LD	HL,I$9569
J$94B9:	LD	A,(HL)
	INC	A
	JP	Z,J$955D
;
	DEC	A
	CP	C
	JP	Z,J$94C8
;
	INC	HL
	INC	HL
	JP	J$94B9
;
;	-----------------
J$94C8:	INC	HL
	LD	B,(HL)
	POP	HL
	LD	IY,I.C3C1
	LD	A,(D.C3E2)
	CP	08H	; 8 
	JP	NC,J$94E5
;
	LD	(IY),B
	LD	B,A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	JP	J.9507
;
;	-----------------
J$94E5:	SUB	08H	; 8 
	CP	08H	; 8 
	JP	NC,J$94FA
;
	LD	(IY+1),B
	LD	B,A
	XOR	A
	LD	(IY),A
	LD	(IY+2),A
	JP	J.9507
;
;	-----------------
J$94FA:	SUB	08H	; 8 
	LD	(IY+2),B
	LD	B,A
	XOR	A
	LD	(IY),A
	LD	(IY+1),A
J.9507:	INC	B
J.9508:	DEC	B
	JP	Z,J$9535
;
	SLA	(IY)
	JP	NC,J$951D
;
	SLA	(IY+1)
	INC	(IY+1)
	JP	J$9521
;
;	-----------------
J$951D:	SLA	(IY+1)
J$9521:	JP	NC,J$952E
;
	SLA	(IY+2)
	INC	(IY+2)
	JP	J.9508
;
;	-----------------
J$952E:	SLA	(IY+2)
	JP	J.9508
;
;	-----------------
J$9535:	LD	A,(IY)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(IY+1)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(IY+2)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,C
	INC	A
	CP	07H	; 7 
	JP	C,J$9550
;
	LD	A,01H	; 1 
J$9550:	LD	C,A
	PUSH	HL
	DEC	DE
	LD	A,D
	AND	D
	JP	NZ,J.94B6
;
	LD	A,E
	AND	E
	JP	NZ,J.94B6
;
J$955D:	POP	HL
	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$9569:	LD	BC,I.0201
	LD	(BC),A
	INC	BC
	INC	B
	INC	B
	EX	AF,AF'
	DEC	B
	INC	B
	LD	B,02H	; 2 
	RLCA	
	LD	BC,I$C5FF
J$9578	EQU	$-1
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,C
	AND	A
	JR	Z,J$95EB
;
	LD	HL,I$95F6
	LD	DE,C.0008
J$958C:	DEC	A
	JR	Z,J$9592
;
	ADD	HL,DE
	JR	J$958C
;
;	-----------------
J$9592:	PUSH	BC
	DEC	B
	LD	C,B
	LD	B,00H
	ADD	HL,BC
	PUSH	HL
	LD	HL,(D.C32C)
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	POP	IX
	LD	HL,(D.C32C)
	LD	DE,(D.C329)
	XOR	A
	SBC	HL,DE
	EX	DE,HL
	INC	E
	POP	HL
	POP	BC
	LD	IY,I.C3C1
J$95B9:	LD	A,(HL)
	CALL	C.96A0
;
	INC	B
	LD	A,B
	CP	09H	; 9 
	JR	NZ,J$95CD
;
	XOR	A
	PUSH	DE
	LD	DE,C.0008
	SBC	HL,DE
	POP	DE
	LD	B,01H	; 1 
J$95CD:	DEC	E
	JR	Z,J$95D9
;
	INC	HL
	DEC	IX
	DEC	IX
	DEC	IX
	JR	J$95B9
;
;	-----------------
J$95D9:	LD	A,(D.C32B)
	LD	B,A
	LD	A,(D.C32E)
	SUB	B
	INC	A
	ADD	A,C
J$95E3:	SUB	04H	; 4 
	JR	Z,J$95E9
;
	JR	NC,J$95E3
;
J$95E9:	ADD	A,04H	; 4 
J$95EB:	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$95F6:	NOP	
	LD	DE,X.0000
	NOP	
	LD	B,H
	DEFB	0,0,0
	ADC	A,B
	DEFB	0,0,0
	LD	(X.0000),HL
	NOP	
	LD	B,H
	DEFB	0,0,0
	LD	DE,X.0000
	NOP	
	LD	(X.0000),HL
	NOP	
	ADC	A,B
	DEFB	0,0
J$9616:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,C
	AND	A
	JR	Z,J$9689
;
	LD	HL,I$9694
	LD	DE,I.0003
J$962A:	DEC	A
	JR	Z,J$9630
;
	ADD	HL,DE
	JR	J$962A
;
;	-----------------
J$9630:	PUSH	BC
	DEC	B
	LD	C,B
	LD	B,00H
	ADD	HL,BC
	PUSH	HL
	LD	HL,(D.C32C)
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	POP	IX
	LD	HL,(D.C32C)
	LD	DE,(D.C329)
	XOR	A
	SBC	HL,DE
	EX	DE,HL
	INC	E
	POP	HL
	POP	BC
	LD	IY,I.C3C1
J$9657:	LD	A,(HL)
	CALL	C.96A0
;
	INC	B
	LD	A,B
	CP	04H	; 4 
	JR	NZ,J$966B
;
	XOR	A
	PUSH	DE
	LD	DE,I.0003
	SBC	HL,DE
	POP	DE
	LD	B,01H	; 1 
J$966B:	DEC	E
	JR	Z,J$9677
;
	INC	HL
	DEC	IX
	DEC	IX
	DEC	IX
	JR	J$9657
;
;	-----------------
J$9677:	LD	A,(D.C32B)
	LD	B,A
	LD	A,(D.C32E)
	SUB	B
	INC	A
	ADD	A,C
J$9681:	SUB	04H	; 4 
	JR	Z,J$9687
;
	JR	NC,J$9681
;
J$9687:	ADD	A,04H	; 4 
J$9689:	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$9694:	NOP	
	LD	H,(HL)
	DEFB	0,0
	INC	SP
	DEFB	0,0
	SBC	A,C
	DEFB	0,0
	CALL	Z,C$C500
C.96A0	EQU	$-1
;
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	(IY),A
	LD	(IY+1),A
	LD	(IY+2),A
	LD	A,(D.C32B)
	LD	B,A
	INC	B
J.96B5:	DEC	B
	JR	Z,J$96DC
;
	SLA	(IY)
	JR	NC,J$96C7
;
	SLA	(IY+1)
	INC	(IY+1)
	JR	J$96CB
;
;	-----------------
J$96C7:	SLA	(IY+1)
J$96CB:	JR	NC,J$96D6
;
	SLA	(IY+2)
	INC	(IY+2)
	JR	J.96B5
;
;	-----------------
J$96D6:	SLA	(IY+2)
	JR	J.96B5
;
;	-----------------
J$96DC:	LD	A,(D.C32E)
	INC	A
	CP	08H	; 8 
	JR	NC,J$96FC
;
	LD	HL,J.91E4
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	AND	(IY)
	LD	(IY),A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	JP	J.9726
;
;	-----------------
J$96FC:	SUB	08H	; 8 
	CP	08H	; 8 
	JR	NC,J$9716
;
	LD	HL,J.91E4
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	AND	(IY+1)
	LD	(IY+1),A
	XOR	A
	LD	(IY+2),A
	JR	J.9726
;
;	-----------------
J$9716:	SUB	08H	; 8 
	LD	HL,J.91E4
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	AND	(IY+2)
	LD	(IY+2),A
J.9726:	LD	A,(IY)
	OR	(IX)
	LD	(IX),A
	LD	A,(IY+1)
	OR	(IX+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	OR	(IX+2)
	LD	(IX+2),A
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
?.9749:	LD	BC,I$0402
	EX	AF,AF'
	DJNZ	J$976F
;
	LD	B,B
	ADD	A,B
J$9751:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BBBF			; select RAM on page 0
;
	PUSH	IX
	PUSH	IX
	POP	DE
	POP	HL
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	POP	IX
	LD	IY,I.C3C1
	LD	A,0FFH
J$976F	EQU	$-1
	LD	(IY),A
	LD	(IY+1),A
	LD	(IY+2),A
	CALL	C.987E
;
	LD	B,C
J$977D:	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,(IY)
	OR	(IX)
	LD	(IX),A
	LD	A,(IY+1)
	OR	(IX+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	OR	(IX+2)
	LD	(IX+2),A
	CALL	C.BD49			; restore slot on page 1
;
	DEC	IX
	DEC	IX
	DEC	IX
	DJNZ	J$977D
;
	LD	A,01H	; 1 
	CALL	C.BC12			; restore slot on page 0
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$97B3:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BBBF			; select RAM on page 0
;
	PUSH	IX
	PUSH	IX
	POP	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	POP	IX
	LD	A,B
	AND	A
	JR	Z,J$97DA
;
	LD	A,C
	SUB	02H	; 2 
	JR	Z,J$97D7
;
	JR	NC,J$97D9
;
J$97D7:	ADD	A,06H	; 6 
J$97D9:	LD	C,A
J$97DA:	LD	D,04H	; 4 
J$97DC:	PUSH	BC
	PUSH	DE
	LD	HL,I$9866
	LD	A,04H	; 4 
	SUB	D
	JR	Z,J$97F0
;
	LD	B,A
	XOR	A
J$97E8:	ADD	A,06H	; 6 
	DJNZ	J$97E8
;
	LD	E,A
	LD	D,00H
	ADD	HL,DE
J$97F0:	LD	D,00H
	DEC	C
	LD	E,C
	ADD	HL,DE
	LD	B,03H	; 3 
	LD	DE,I.C3C1
J$97FA:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	HL
	INC	C
	INC	C
	LD	A,C
	CP	06H	; 6 
	JR	C,J$9811
;
	PUSH	DE
	LD	DE,CPMADR
	XOR	A
	SBC	HL,DE
	POP	DE
	LD	A,C
	SUB	06H	; 6 
	LD	C,A
J$9811:	INC	DE
	DEC	B
	JR	NZ,J$97FA
;
	LD	IY,I.C3C1
	CALL	C.987E
;
	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,(IY)
	OR	(IX)
	LD	(IX),A
	LD	A,(IY+1)
	OR	(IX+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	OR	(IX+2)
	LD	(IX+2),A
	CALL	C.BD49			; restore slot on page 1
;
	DEC	IX
	DEC	IX
	DEC	IX
	POP	DE
	POP	BC
	DEC	D
	JP	NZ,J$97DC
;
	LD	A,(D.C3BF)
	LD	B,A
	LD	A,(D.C3C0)
	SUB	B
	INC	A
	ADD	A,C
J$9853:	SUB	06H	; 6 
	JR	Z,J$9859
;
	JR	NC,J$9853
;
J$9859:	ADD	A,06H	; 6 
	CALL	C.BC12			; restore slot on page 0
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$9866:	LD	B,C
	JR	NZ,J$9879
;
	EX	AF,AF'
	INC	B
	ADD	A,D
	AND	D
	LD	D,C
	JR	Z,J$9884
;
	ADC	A,D
	LD	B,L
	INC	D
	ADC	A,D
	LD	B,L
	AND	D
	LD	D,C
	JR	Z,J$9881
;
J$9879:	INC	B
	ADD	A,D
	LD	B,C
	JR	NZ,J$988E
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.987E:	LD	A,(D.C3BF)
J$9881:	LD	B,A
	INC	B
J.9883:	DEC	B
J$9884:	JR	Z,J$98AA
;
	SLA	(IY)
	JR	NC,J$9895
;
	SLA	(IY+1)
J$988E	EQU	$-2
	INC	(IY+1)
	JR	J$9899
;
;	-----------------
J$9895:	SLA	(IY+1)
J$9899:	JR	NC,J$98A4
;
	SLA	(IY+2)
	INC	(IY+2)
	JR	J.9883
;
;	-----------------
J$98A4:	SLA	(IY+2)
	JR	J.9883
;
;	-----------------
J$98AA:	LD	A,(D.C3C0)
	INC	A
	CP	08H	; 8 
	JR	NC,J$98C9
;
	LD	HL,J.91E4
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	AND	(IY)
	LD	(IY),A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	JR	J.98F3
;
;	-----------------
J$98C9:	SUB	08H	; 8 
	CP	08H	; 8 
	JR	NC,J$98E3
;
	LD	HL,J.91E4
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	AND	(IY+1)
	LD	(IY+1),A
	XOR	A
	LD	(IY+2),A
	JR	J.98F3
;
;	-----------------
J$98E3:	SUB	08H	; 8 
	LD	HL,J.91E4
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	LD	A,(HL)
	AND	(IY+2)
	LD	(IY+2),A
J.98F3:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.98F4:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,(D.C3CA)
	PUSH	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	LD	DE,(D.C3CA)
	LD	HL,(D.C3CC)
	SBC	HL,DE
	EX	DE,HL
J.9914:	LD	HL,I$99C7
J$9917:	LD	A,(HL)
	INC	A
	JP	Z,J$99BB
;
	DEC	A
	CP	C
	JP	Z,J$9926
;
	INC	HL
	INC	HL
	JP	J$9917
;
;	-----------------
J$9926:	INC	HL
	LD	B,(HL)
	POP	HL
	LD	IY,I.C3C1
	LD	A,(D.C3E2)
	CP	08H	; 8 
	JP	NC,J$9943
;
	LD	(IY),B
	LD	B,A
	XOR	A
	LD	(IY+1),A
	LD	(IY+2),A
	JP	J.9965
;
;	-----------------
J$9943:	SUB	08H	; 8 
	CP	08H	; 8 
	JP	NC,J$9958
;
	LD	(IY+1),B
	LD	B,A
	XOR	A
	LD	(IY),A
	LD	(IY+2),A
	JP	J.9965
;
;	-----------------
J$9958:	SUB	08H	; 8 
	LD	(IY+2),B
	LD	B,A
	XOR	A
	LD	(IY),A
	LD	(IY+1),A
J.9965:	INC	B
J.9966:	DEC	B
	JP	Z,J$9993
;
	SLA	(IY)
	JP	NC,J$997B
;
	SLA	(IY+1)
	INC	(IY+1)
	JP	J$997F
;
;	-----------------
J$997B:	SLA	(IY+1)
J$997F:	JP	NC,J$998C
;
	SLA	(IY+2)
	INC	(IY+2)
	JP	J.9966
;
;	-----------------
J$998C:	SLA	(IY+2)
	JP	J.9966
;
;	-----------------
J$9993:	LD	A,(IY)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(IY+1)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(IY+2)
	OR	(HL)
	LD	(HL),A
	INC	HL
	LD	A,C
	INC	A
	CP	03H	; 3 
	JP	C,J$99AE
;
	LD	A,01H	; 1 
J$99AE:	LD	C,A
	PUSH	HL
	DEC	DE
	LD	A,D
	AND	D
	JP	NZ,J.9914
;
	LD	A,E
	AND	E
	JP	NZ,J.9914
;
J$99BB:	POP	HL
	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$99C7:	LD	BC,I.0201
	LD	(BC),A
	RST	38H
J$99CC:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BBBF			; select RAM on page 0
;
	PUSH	IX
	PUSH	IX
	POP	HL
	POP	DE
	ADD	HL,DE
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	PUSH	HL
	POP	IX
	LD	D,02H	; 2 
	LD	E,C
J$99E8:	PUSH	BC
	PUSH	DE
	LD	HL,I$9A5F
	LD	D,00H
	LD	E,C
	ADD	HL,DE
	DEC	HL
	LD	IY,I.C3C1
	LD	A,(HL)
	LD	(IY),A
	LD	(IY+1),A
	LD	(IY+2),A
	CALL	C.987E
;
	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,(IY)
	OR	(IX)
	LD	(IX),A
	LD	A,(IY+1)
	OR	(IX+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	OR	(IX+2)
	LD	(IX+2),A
	CALL	C.BD49			; restore slot on page 1
;
	XOR	A
	LD	DE,I.0003
	PUSH	IX
	POP	HL
	SBC	HL,DE
	PUSH	HL
	POP	IX
	POP	DE
	POP	BC
	LD	A,C
	CP	01H	; 1 
	JR	Z,J$9A3B
;
	LD	C,01H	; 1 
	JR	J$9A3D
;
;	-----------------
J$9A3B:	LD	C,02H	; 2 
J$9A3D:	DEC	D
	JP	NZ,J$99E8
;
	LD	C,E
	LD	A,(D.C3BF)
	LD	B,A
	LD	A,(D.C3C0)
	SUB	B
	INC	A
	ADD	A,C
J$9A4C:	SUB	02H	; 2 
	JR	Z,J$9A52
;
	JR	NC,J$9A4C
;
J$9A52:	ADD	A,02H	; 2 
	CALL	C.BC12			; restore slot on page 0
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$9A5F:	LD	D,L
	XOR	D
J$9A61:	XOR	A
	LD	(D.C3E1),A
	LD	(D$C325),A
	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,(D.C9B0)
	LD	(D.C352),HL
	LD	(HL),00H
	CALL	C.BD49			; restore slot on page 1
;
	RET	
;
;	-----------------
J.9A77:	LD	HL,I$9ABC
	CALL	C.9AAB
;
	JR	C,J.9AAA
;
	LD	A,(D.D497)
	CP	05H	; 5 
	JR	Z,J$9A8E
;
	LD	HL,I$9ABF
	CALL	C.9AAB
;
	JR	C,J.9AAA
;
J$9A8E:	LD	B,00H
	LD	A,(D.D497)
	CP	02H	; 2 
	JR	Z,J.9AA5
;
	CP	03H	; 3 
	JR	Z,J.9AA5
;
	LD	HL,I$9AC8
	CALL	C.9AAB
;
	JR	C,J.9AAA
;
	LD	B,01H	; 1 
J.9AA5:	LD	A,B
	LD	(D.C9C7),A
	AND	A
J.9AAA:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9AAB:	LD	B,(HL)
	INC	HL
	LD	A,(D$DB16)
	AND	A
	JR	NZ,J$9AB8
	CALL	C.9DD3
	JR	J$9ABB

J$9AB8:	CALL	C.9DDD
J$9ABB:	RET	
;
;	-----------------
I$9ABC:	LD	(BC),A
	JR	J$9ACE
;
;	-----------------
I$9ABF:	EX	AF,AF'
	DEC	DE
	LD	H,(HL)
	LD	A,(DE)
	LD	B,A
	LD	A,(DE)
	LD	D,C
	LD	A,(DE)
	LD	D,A
I$9AC8:	EX	AF,AF'
	DEC	DE
	LD	B,B
	DEC	DE
	LD	B,E
	LD	L,D
J$9ACE:	DEC	DE
	LD	B,E
	LD	H,C
J$9AD1:	LD	A,(D.C33D)
	AND	A
	JR	Z,J$9AF2
;
	LD	A,48H	; "H"
	CALL	C.B8A8
;
	CALL	C.9B3E
;
	JR	C,J.9AF3
;
	CALL	C$9C73
;
	JR	C,J.9AF3
;
	CALL	C.A652
;
	XOR	A
	LD	(D.C33D),A
	LD	A,47H	; "G"
	CALL	C.B8A8
;
J$9AF2:	AND	A
J.9AF3:	RET	
;
;	-----------------
J$9AF4:	PUSH	HL
	LD	HL,(D.C4C2)
	LD	A,L
	OR	H
	JR	Z,J$9B16
;
	LD	A,48H	; "H"
	CALL	C.B8A8
;
	CALL	C.9B3E
;
	JR	C,J.9B17
;
	CALL	C$9D09
;
	JR	C,J.9B17
;
	LD	HL,X.0000
	LD	(D.C4C2),HL
	LD	A,47H	; "G"
	CALL	C.B8A8
;
J$9B16:	AND	A
J.9B17:	POP	HL
	RET	
;
;	-----------------
J$9B19:	PUSH	HL
	LD	HL,(D.C4C2)
	LD	A,L
	OR	H
	JR	Z,J$9B3B
;
	LD	A,48H	; "H"
	CALL	C.B8A8
;
	CALL	C.9B3E
;
	JR	C,J.9B3C
;
	CALL	C$9CE1
;
	JR	C,J.9B3C
;
	LD	HL,X.0000
	LD	(D.C4C2),HL
	LD	A,47H	; "G"
	CALL	C.B8A8
;
J$9B3B:	AND	A
J.9B3C:	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9B3E:	PUSH	DE
	PUSH	HL
	LD	HL,(D.C901)
	LD	A,L
	OR	H
	JR	Z,J$9B7D
;
	AND	A
	LD	DE,I.0063
	SBC	HL,DE
	JR	C,J.9B71
;
	EX	DE,HL
	CALL	C.9C0D
;
	JR	C,J.9B7E
;
	LD	HL,(D.C901)
J$9B58:	AND	A
	LD	DE,I.0063
	SBC	HL,DE
	JR	C,J.9B71
;
	LD	D,0AH	; 10 
	CALL	C.9DFC
;
	JR	C,J.9B7E
;
	CALL	C.9ED2
;
	CALL	C.9EFE
;
	JR	C,J.9B7E
;
	JR	J$9B58
;
;	-----------------
J.9B71:	ADD	HL,DE
	CALL	C.9BFE
;
	JR	C,J.9B7E
;
	LD	HL,X.0000
	LD	(D.C901),HL
J$9B7D:	AND	A
J.9B7E:	POP	HL
	POP	DE
	RET	
;
;	-----------------
J$9B81:	JR	NC,J$9B94
;
	LD	A,(D.C999)
	AND	A
	JR	NZ,J$9B91
;
	LD	HL,C.0018
	CALL	C.9BFE
;
	JR	C,J.9B9D
;
J$9B91:	SCF	
	JR	J.9B9D
;
;	-----------------
J$9B94:	LD	HL,C.0018
	CALL	C.9BFE
;
	JR	C,J.9B9D
;
	AND	A
J.9B9D:	LD	A,00H
	LD	(D.C999),A
	RET	
;
;	-----------------
J$9BA3:	PUSH	DE
	PUSH	HL
	LD	A,(D.D497)
	CP	05H	; 5 
	JR	Z,J.9BCF
;
	LD	D,1BH
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	LD	D,72H	; "r"
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	CALL	C.9BFE
;
	JR	C,J.9BFB
;
	LD	D,1BH
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	LD	D,66H	; "f"
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	JR	J.9BFA
;
;	-----------------
J.9BCF:	LD	D,1BH
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	LD	D,43H	; "C"
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	LD	D,79H	; "y"
	CALL	C.9DFC
;
	JR	C,J.9BFB
;
	LD	DE,I$002E
	AND	A
	SBC	HL,DE
	JR	Z,J.9BFA
;
	JR	NC,J.9BCF
;
	EX	DE,HL
	LD	HL,X.0000
	AND	A
	SBC	HL,DE
	CALL	C.9BFE
;
	JR	C,J.9BFB
;
J.9BFA:	AND	A
J.9BFB:	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9BFE:	PUSH	DE
	PUSH	HL
	CALL	C.9C0D
;
	JR	C,J$9C0A
;
	LD	D,0AH	; 10 
	CALL	C.9DFC
;
J$9C0A:	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9C0D:	PUSH	BC
	PUSH	HL
	CALL	C.A12D
;
	LD	A,1BH
	LD	(D.C344),A
	LD	A,54H	; "T"
	LD	(D$C345),A
	LD	HL,D.C344
	LD	B,04H	; 4 
	CALL	C.9DD3
	POP	HL
	POP	BC
	RET	
;
;	-----------------
J$9C27:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.BCF6			; select RAM on page 1
;
	LD	A,48H	; "H"
	CALL	C.B8A8
;
	CALL	C.9D67
;
	JR	C,J.9C65
;
	LD	HL,I.9C6C
J$9C39	EQU	$-1
	LD	B,(HL)
	INC	HL
	CALL	C.9DD3
;
	JR	C,J.9C65
;
	LD	HL,I.5E14
	LD	BC,I.10E0
J$9C47:	LD	D,(HL)
	INC	HL
	CALL	C.9DFC
;
	JR	C,J.9C65
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9C47
;
	CALL	C.9DE9
;
	JR	C,J.9C65
;
	LD	D,0AH	; 10 
	CALL	C.9DFC
;
	JR	C,J.9C65
;
	LD	A,47H	; "G"
	CALL	C.B8A8
;
	AND	A
J.9C65:	CALL	C.BD49			; restore slot on page 1
;
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I.9C6C:	LD	B,1BH
	LD	C,D
	LD	SP,I$3434
	JR	NC,J$9C39
C$9C73	EQU	$-1
;
	PUSH	DE
	PUSH	HL
	CALL	C.BCF6			; select RAM on page 1
;
	CALL	C.9D67
;
	JR	C,J.9C9F
;
	LD	HL,I.9C6C
	LD	B,(HL)
	INC	HL
	CALL	C.9DD3
;
	JR	C,J.9C9F
;
	LD	HL,I.5E14
	LD	BC,I.10E0
J$9C8E:	LD	D,(HL)
	INC	HL
	CALL	C.9DFC
;
	JR	C,J.9C9F
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9C8E
;
	CALL	C.9DE9
;
	JR	C,J.9C9F
;
J.9C9F:	CALL	C.BD49			; restore slot on page 1
;
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$9CA6:	RET	
;
;	-----------------
J$9CA7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,48H	; "H"
	CALL	C.B8A8
;
	CALL	C.9D67
;
	JR	C,J.9CDD
;
	LD	HL,D.C4C2
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	A,C
	OR	B
	JR	Z,J$9CCB
;
J$9CBF:	LD	D,(HL)
	INC	HL
	CALL	C.9DFC
;
	JR	C,J.9CDD
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9CBF
;
J$9CCB:	CALL	C.9DE9
;
	JR	C,J.9CDD
;
	LD	D,0AH	; 10 
	CALL	C.9DFC
;
	JR	C,J.9CDD
;
	LD	A,47H	; "G"
	CALL	C.B8A8
;
	AND	A
J.9CDD:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9CE1:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.9D67
;
	JR	C,J.9D05
;
	LD	HL,D.C4C2
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	A,C
	OR	B
	JR	Z,J$9D00
;
J$9CF4:	LD	D,(HL)
	INC	HL
	CALL	C.9DFC
;
	JR	C,J.9D05
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9CF4
;
J$9D00:	CALL	C.9DE9
;
	JR	C,J.9D05
;
J.9D05:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9D09:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.9D67
;
	JR	C,J.9D2E
;
	LD	HL,D.C4C2
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	A,C
	OR	B
	JR	Z,J$9D28
;
	ADD	HL,BC
J$9D1C:	LD	D,(HL)
	DEC	HL
	CALL	C.9DFC
;
	JR	C,J.9D2E
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9D1C
;
J$9D28:	CALL	C.9DE9
;
	JR	C,J.9D2E
;
	AND	A
J.9D2E:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$9D32:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,48H	; "H"
	CALL	C.B8A8
;
	LD	HL,D.C4C2
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	A,C
	OR	B
	JR	Z,J$9D51
;
J$9D45:	LD	D,(HL)
	INC	HL
	CALL	C.9DFC
;
	JR	C,J.9D63
;
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9D45
;
J$9D51:	CALL	C.9DE9
;
	JR	C,J.9D63
;
	LD	D,0AH	; 10 
	CALL	C.9DFC
;
	JR	C,J.9D63
;
	LD	A,47H	; "G"
	CALL	C.B8A8
;
	AND	A
J.9D63:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9D67:	LD	A,(D.C9C7)
	AND	A
	JR	Z,J.9D7D
;
	LD	A,(D.CC3D)
	AND	A
	JR	NZ,J.9D7D
;
	LD	HL,I$9D7F
	LD	B,(HL)
	INC	HL
	CALL	C.9DD3
;
	JR	C,J$9D7E
;
J.9D7D:	AND	A
J$9D7E:	RET	
;
;	-----------------
I$9D7F:	INC	BC
	DEC	DE
	LD	B,E
	LD	H,D
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9D83:	LD	A,(D.C9C7)
	AND	A
	JR	Z,J.9D99
;
	LD	A,(D.CC3D)
	AND	A
	JR	NZ,J.9D99
;
	LD	HL,I$9D9B
	LD	B,(HL)
	INC	HL
	CALL	C.9DD3
;
	JR	C,J$9D9A
;
J.9D99:	AND	A
J$9D9A:	RET	
;
;	-----------------
I$9D9B:	INC	BC
	DEC	DE
	LD	B,E
	LD	H,C
J$9D9F:	PUSH	DE
	LD	E,56H	; "V"
	JR	J.9DA7
;
;	-----------------
J$9DA4:	PUSH	DE
	LD	E,57H	; "W"
J.9DA7:	LD	D,1AH
	CALL	C.9DFC
;
	JR	C,J$9DB2
;
	LD	D,E
	CALL	C.9DFC
;
J$9DB2:	POP	DE
	RET	
;
;	-----------------
J$9DB4:	PUSH	DE
	LD	E,6BH	; "k"
	JR	J.9DA7
;
;	-----------------
J$9DB9:	PUSH	DE
	LD	E,74H	; "t"
	JR	J.9DA7
;
;	-----------------
J$9DBE:	PUSH	DE
	LD	E,74H	; "t"
	JR	J$9DC6
;
;	-----------------
J$9DC3:	PUSH	DE
	LD	E,4BH	; "K"
J$9DC6:	LD	D,1BH
	CALL	C.9DFC
;
	JR	C,J$9DD1
;
	LD	D,E
	CALL	C.9DFC
;
J$9DD1:	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9DD3:	LD	D,(HL)
	CALL	C.9DFC
	RET	C
	INC	HL
	DJNZ	C.9DD3
	AND	A
	RET	
;
;	-----------------
;
;	  Subroutine send 
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9DDD:	LD	D,(HL)
	LD	E,9EH
	CALL	C.9E04
	RET	C
	INC	HL
	DJNZ	C.9DDD
	AND	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9DE9:	LD	D,0DH	; 13 
	CALL	C.9DFC
;
	JR	C,J.9DFB
;
	CALL	C$9D83
;
	JR	C,J.9DFB
;
	CALL	C.9ED2
;
	CALL	C.9EFE
;
J.9DFB:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9DFC:	PUSH	DE
	LD	E,4CH	; "L"
	CALL	C.9E04
	POP	DE
	RET	

;	  Subroutine send byte to printer
;	     Inputs  ________________________
;	     Outputs ________________________

C.9E04:	PUSH	BC
	PUSH	HL
J$9E06:	LD	A,(D.D49E)
	BIT	7,A			; no turbo flag ?
	LD	C,0
	JR	Z,J$9E11		; nope,
	LD	C,6
J$9E11:	LD	A,(D.D497)
	CP	04H
	LD	A,0
	JR	Z,J$9E1C
	LD	A,3
J$9E1C:	ADD	A,C
	LD	C,A
	LD	A,(D$D18E)
	ADD	A,C
	LD	C,A
	LD	B,00H
	LD	HL,I$9E5E
	ADD	HL,BC
	LD	L,(HL)
	LD	H,0
J$9E2C:	LD	BC,0
J$9E2F:	IN	A,(90H)
	BIT	1,A			; printer ready ?
	JR	Z,J$9E49		; yep, send data
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$9E2F
	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J$9E2C
	CALL	C.9E6A
	LD	(D.C999),A
	JR	NC,J$9E06		; retry
	JR	J$9E5B			; quit

J$9E49:	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	NOP
	LD	A,D
	OUT	(91H),A
	XOR	A
	OUT	(90H),A
	DEC	A
	OUT	(90H),A
	AND	A
J$9E5B:	POP	HL
	POP	BC
	RET	
;
;	-----------------
I$9E5E:	LD	E,14H	; 20 
	DEC	D
	LD	E,14H	; 20 
	DEC	D
	INC	D
	DEC	BC
	DEC	C
	INC	D
	DEC	BC
	DEC	C
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9E6A:	LD	A,03H	; 3 
	CALL	C.B8A8
;
	LD	A,5BH	; "["
	CALL	C.B935
;
	LD	A,H
	AND	A
	JR	Z,J$9E90
;
	CP	01H	; 1 
	JR	Z,J$9E86
;
	LD	A,01H	; 1 
	LD	(D.D464),A
	LD	A,80H
	SCF	
	JR	J.9E95
;
;	-----------------
J$9E86:	LD	A,01H	; 1 
	LD	(D.D44A),A
	SCF	
	LD	A,80H
	JR	J.9E95
;
;	-----------------
J$9E90:	LD	A,E
	CALL	C.B8A8
;
	XOR	A
J.9E95:	RET	
;
;	-----------------
J$9E96:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D$DB15)
	ADD	A,A
	LD	E,A
	ADD	A,A
	ADD	A,A
	ADD	A,E
	LD	E,A
	LD	D,00H
	LD	HL,I$C88E
	ADD	HL,DE
	LD	A,(D$C99B)
	LD	C,A
	LD	B,0AH	; 10 
J$9EAE:	LD	A,(HL)
	INC	HL
	CP	C
	JR	Z,J$9EBA
;
	INC	A
	JR	Z,J.9EC1
;
	DJNZ	J$9EAE
;
	JR	J.9EC1
;
;	-----------------
J$9EBA:	LD	HL,D.C999
	SET	0,(HL)
	JR	J$9EC4
;
;	-----------------
J.9EC1:	CALL	C.9ED2
;
J$9EC4:	CALL	C.9EFE
;
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$9ECB:	CALL	C.9ED2
;
	CALL	C.9EFE
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9ED2:	PUSH	AF
	PUSH	BC
	LD	C,00H
J.9ED6:	CALL	C$B895
;
	AND	A
	JR	Z,J$9EF4
;
	CP	1BH
	JR	NZ,J$9EE4
;
	SET	2,C
	JR	J.9ED6
;
;	-----------------
J$9EE4:	CP	07H	; 7 
	JR	NZ,J$9EEC
;
	SET	1,C
	JR	J.9ED6
;
;	-----------------
J$9EEC:	CP	20H	; " "
	JR	NZ,J.9ED6
;
	SET	0,C
	JR	J.9ED6
;
;	-----------------
J$9EF4:	LD	A,(D.C999)
	OR	C
	LD	(D.C999),A
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9EFE:	LD	A,(D.C999)
	RRA	
	JR	NC,J$9F09
;
	CALL	C$B8DB
;
	JR	J.9F1D
;
;	-----------------
J$9F09:	RRA	
	JR	NC,J$9F14
;
	LD	A,01H	; 1 
	LD	(D.D44A),A
	SCF	
	JR	J.9F1D
;
;	-----------------
J$9F14:	RRA	
	JR	NC,J.9F1D
;
	LD	A,01H	; 1 
	LD	(D.D464),A
	SCF	
J.9F1D:	LD	A,00H
	LD	(D.C999),A
	RET	
;
;	-----------------
J$9F23:	PUSH	AF
	AND	A
	PUSH	AF
	JR	Z,J$9F2D
;
	LD	A,0FH	; 15 
	CALL	C.A118
;
J$9F2D:	CALL	C$A022
;
	CALL	C$9F72
;
	POP	AF
	JR	Z,J$9F3B
;
	LD	A,0EH	; 14 
	CALL	C.A118
;
J$9F3B:	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9F3D:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	LD	HL,(D.C9D0)
	AND	A
	SBC	HL,DE
	EX	DE,HL
	JR	NC,J$9F6E
;
	CALL	C.A12D
;
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),1BH
	INC	HL
	LD	(HL),46H	; "F"
	INC	HL
	EX	DE,HL
	LD	HL,D.C344
	LD	BC,I.0004
	LDIR	
	LD	HL,(D.C4C2)
	LD	DE,CPMADR
	ADD	HL,DE
	LD	(D.C4C2),HL
J$9F6E:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$9F72:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,L
	OR	H
	JR	Z,J$9FA3
;
	CALL	C.A12D
;
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	BC,(D.C346)
	LD	(HL),B
	INC	HL
	LD	(HL),C
	INC	HL
	LD	BC,(D.C344)
	LD	(HL),B
	INC	HL
	LD	(HL),C
	INC	HL
	LD	(HL),46H	; "F"
	INC	HL
	LD	(HL),1BH
	LD	HL,(D.C4C2)
	LD	DE,CPMADR
	ADD	HL,DE
	LD	(D.C4C2),HL
J$9FA3:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$9FA7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,H
	OR	L
	JR	Z,J$9FD5
;
	CALL	C.A12D
;
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),1BH
	INC	HL
	LD	(HL),56H	; "V"
	INC	HL
	EX	DE,HL
	LD	HL,D.C344
	LD	BC,I.0004
	LDIR	
	EX	DE,HL
	LD	(HL),00H
	LD	HL,(D.C4C2)
	LD	DE,D.0007
	ADD	HL,DE
	LD	(D.C4C2),HL
J$9FD5:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$9FD9:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,H
	LD	C,L
	JR	J.9FF5
;
;	-----------------
?.9FE0:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,L
	LD	C,H
	JR	J.9FF5
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.9FE7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	C,A
	LD	B,00H
	JR	J.9FF5
;
;	-----------------
?.9FEF:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	C,00H
	LD	B,A
J.9FF5:	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),B
	INC	HL
	LD	(HL),C
I.A000:	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A00C:	LD	A,(D.C9C6)
	BIT	0,A
	JR	NZ,J$A018
;
	CALL	C.A038
;
	JR	J$A021
;
;	-----------------
J$A018:	CALL	C$A0DC
;
	CALL	C.A038
;
	CALL	C$A0A0
;
J$A021:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A022:	LD	A,(D.C9C6)
	BIT	0,A
	JR	NZ,J$A02E
;
	CALL	C.A06C
;
	JR	J$A037
;
;	-----------------
J$A02E:	CALL	C$A0BE
;
	CALL	C.A06C
;
	CALL	C$A0FA
;
J$A037:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A038:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.B76B
;
	LD	A,(D.C9C6)
	BIT	4,A
	JR	Z,J$A049
;
	LD	B,2DH	; "-"
	JR	J.A04F
;
;	-----------------
J$A049:	BIT	5,A
	JR	Z,J.A04F
;
	LD	B,2EH	; "."
J.A04F:	BIT	3,A
	JR	Z,J$A055
;
	LD	B,22H	; """
J$A055:	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),B
	INC	HL
	LD	(HL),C
	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A06C:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.B76B
;
	LD	A,(D.C9C6)
	BIT	4,A
	JR	Z,J$A07D
;
	LD	B,2DH	; "-"
	JR	J.A083
;
;	-----------------
J$A07D:	BIT	5,A
	JR	Z,J.A083
;
	LD	B,2EH	; "."
J.A083:	BIT	3,A
	JR	Z,J$A089
;
	LD	B,22H	; """
J$A089:	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),C
	INC	HL
	LD	(HL),B
	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0A0:	PUSH	DE
	PUSH	HL
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),1BH
	INC	HL
	LD	(HL),43H	; "C"
	INC	HL
	LD	(HL),6AH	; "j"
	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0BE:	PUSH	DE
	PUSH	HL
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),6AH	; "j"
	INC	HL
	LD	(HL),43H	; "C"
	INC	HL
	LD	(HL),1BH
	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0DC:	PUSH	DE
	PUSH	HL
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),1BH
	INC	HL
	LD	(HL),43H	; "C"
	INC	HL
	LD	(HL),4AH	; "J"
	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A0FA:	PUSH	DE
	PUSH	HL
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),4AH	; "J"
	INC	HL
	LD	(HL),43H	; "C"
	INC	HL
	LD	(HL),1BH
	LD	HL,(D.C4C2)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A118:	PUSH	DE
	PUSH	HL
	LD	HL,D.C4C2
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	ADD	HL,DE
	LD	(HL),A
	LD	HL,(D.C4C2)
	INC	HL
	LD	(D.C4C2),HL
	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A12D:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	DE,I$0064
	LD	B,00H
J$A136:	AND	A
	SBC	HL,DE
	JR	C,J$A13E
;
	INC	B
	JR	J$A136
;
;	-----------------
J$A13E:	ADD	HL,DE
	LD	A,L
	CALL	C.A152
;
	LD	(D.C346),HL
	LD	A,B
	CALL	C.A152
;
	LD	(D.C344),HL
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A152:	LD	HL,I.3030
J$A155:	SUB	0AH	; 10 
	JR	C,J$A15C
;
	INC	L
	JR	J$A155
;
;	-----------------
J$A15C:	ADD	A,0AH	; 10 
	ADD	A,H
	LD	H,A
	RET	
;
;	-----------------
?.A161:	PUSH	IX
	POP	HL
	LD	D,00H
	ADD	HL,DE
	LD	D,H
	LD	E,L
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A171:	PUSH	AF
	CALL	C.BCF6			; select RAM on page 1
;
J$A175:	LD	A,(DE)
	OR	(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$A175
;
	CALL	C.BD49			; restore slot on page 1
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A184:	PUSH	AF
	CALL	C.BCF6			; select RAM on page 1
;
J$A188:	LD	A,(DE)
	OR	(HL)
	LD	(DE),A
	DEC	HL
	DEC	DE
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$A188
;
	CALL	C.BD49			; restore slot on page 1
;
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A197:	CALL	C.A66C
;
	LD	A,B
	CP	20H	; " "
	JP	C,J.A3B5
;
	LD	D,02H	; 2 
	CP	80H
	JR	C,J.A1D0
;
	CP	0A0H
	JR	C,J$A1D3
;
	CP	0E0H
	JR	C,J.A1D0
;
	CP	0F0H
	JP	C,J.A33E
;
	JP	Z,J.A33E
;
	LD	D,10H	; 16 
	CP	0FBH
	JP	Z,J.A33E
;
	LD	D,08H	; 8 
	CP	0FDH
	JP	Z,J.A33E
;
	LD	D,04H	; 4 
	CP	0F0H
	JP	Z,J.A33E
;
	LD	D,02H	; 2 
	JP	J.A33E
;
;	-----------------
J.A1D0:	JP	J.A3C2
;
;	-----------------
J$A1D3:	LD	A,(D.CC3F)
	CP	01H	; 1 
	JP	NZ,J.A33E
;
	LD	A,B
	CP	81H
	JR	Z,J$A1ED
;
	CP	82H
	JP	Z,J$A282
;
	CP	83H
	JP	Z,J$A2B8
;
	JP	J.A33E
;
;	-----------------
J$A1ED:	LD	A,C
	CP	41H	; "A"
	JP	C,J.A33E
;
	CP	45H	; "E"
	JP	C,J.A380
;
	CP	4AH	; "J"
	JP	C,J.A33E
;
	CP	4CH	; "L"
	JP	C,J.A380
;
	CP	50H	; "P"
	JP	C,J.A33E
;
	CP	52H	; "R"
	JP	C,J.A2F8
;
	CP	5BH	; "["
	JP	C,J.A33E
;
	CP	5CH	; "\"
	JP	C,J.A380
;
	CP	5EH	; "^"
	JP	C,J.A2F8
;
	CP	60H	; "`"
	JP	C,J.A33E
;
	CP	65H	; "e"
	JP	C,J.A2F8
;
	CP	69H	; "i"
	JP	C,J.A380
;
	CP	7DH	; "}"
	JP	C,J.A2F8
;
	CP	81H
	JP	C,J.A33E
;
	CP	87H
	JP	C,J.A2F8
;
	CP	8BH
	JP	C,J.A33E
;
	CP	8EH
	JP	C,J.A380
;
	CP	0A8H
	JP	C,J.A33E
;
	CP	0ACH
	JP	C,J.A2F8
;
	CP	0B8H
	JP	C,J.A33E
;
	CP	0C0H
	JP	C,J.A2F8
;
	CP	0C8H
	JP	C,J.A33E
;
	CP	0CDH
	JP	C,J.A2F8
;
	CP	0DFH
	JP	C,J.A33E
;
	CP	0E3H
	JP	C,J.A2F8
;
	CP	0E4H
	JP	C,J.A33E
;
	CP	0E6H
	JP	C,J.A2F8
;
	CP	0E7H
	JP	C,J.A33E
;
	CP	0E9H
	JP	C,J.A2F8
;
	JP	J.A33E
;
;	-----------------
J$A282:	LD	A,C
	CP	9FH
	JP	Z,J.A380
;
	CP	0A1H
	JP	Z,J.A380
;
	CP	0A3H
	JP	Z,J.A380
;
	CP	0A5H
	JP	Z,J.A380
;
	CP	0A7H
	JP	Z,J.A380
;
	CP	0C1H
	JP	Z,J.A380
;
	CP	0E1H
	JP	Z,J.A380
;
	CP	0E3H
	JP	Z,J.A380
;
	CP	0E5H
	JP	Z,J.A380
;
	CP	0ECH
	JP	Z,J.A380
;
	JP	J.A33E
;
;	-----------------
J$A2B8:	LD	A,C
	CP	40H	; "@"
	JP	Z,J.A380
;
	CP	42H	; "B"
	JP	Z,J.A380
;
	CP	44H	; "D"
	JP	Z,J.A380
;
	CP	46H	; "F"
	JP	Z,J.A380
;
	CP	48H	; "H"
	JP	Z,J.A380
;
	CP	62H	; "b"
	JP	Z,J.A380
;
	CP	83H
	JP	Z,J.A380
;
	CP	85H
	JP	Z,J.A380
;
	CP	87H
	JP	Z,J.A380
;
	CP	8EH
	JP	Z,J.A380
;
	CP	95H
	JP	Z,J.A380
;
	CP	96H
	JP	Z,J.A380
;
	JP	J.A33E
;
;	-----------------
J.A2F8:	PUSH	HL
	LD	A,B
	CP	0F0H
	JR	Z,J.A306
;
	CP	0FBH
	JR	Z,J.A306
;
	CP	0FDH
	JR	Z,J.A306
;
J.A306:	LD	HL,I.D1BD
	CALL	C.A6A7
;
	JR	NC,J$A338
;
	LD	A,03H	; 3 
	CALL	C.B8A8
;
	LD	A,66H	; "f"
	PUSH	IX
	PUSH	IY
	CALL	C.B935
;
	POP	IY
	POP	IX
	LD	A,H
	AND	A
	JR	NZ,J$A32B
;
	LD	A,4CH	; "L"
	CALL	C.B8A8
;
	JR	J.A306
;
;	-----------------
J$A32B:	CP	02H	; 2 
	JP	NZ,J.A3BA
;
	LD	A,0FFH
	LD	(D.D464),A
	JP	J.A3B7
;
;	-----------------
J$A338:	POP	HL
	CALL	C.877C
;
	JR	J.A3B5
;
;	-----------------
J.A33E:	PUSH	HL
	LD	A,B
	CP	0F0H
	JR	Z,J.A34C
;
	CP	0FBH
	JR	Z,J.A34C
;
	CP	0FDH
	JR	Z,J.A34C
;
J.A34C:	LD	HL,I.D1BD
	CALL	C.A6A7
;
	JR	NC,J$A37D
;
	LD	A,03H	; 3 
	CALL	C.B8A8
;
	LD	A,66H	; "f"
	PUSH	IX
	PUSH	IY
	CALL	C.B935
;
	POP	IY
	POP	IX
	LD	A,H
	AND	A
	JR	NZ,J$A371
;
	LD	A,4CH	; "L"
	CALL	C.B8A8
;
	JR	J.A34C
;
;	-----------------
J$A371:	CP	02H	; 2 
	JP	NZ,J.A3BA
;
	LD	A,0FFH
	LD	(D.D464),A
	JR	J.A3B7
;
;	-----------------
J$A37D:	POP	HL
	JR	J.A3B5
;
;	-----------------
J.A380:	PUSH	HL
J$A381:	LD	HL,I.D1BD
	CALL	C.A93D
;
	JR	NC,J$A3AE
;
	LD	A,03H	; 3 
	CALL	C.B8A8
;
	LD	A,66H	; "f"
	PUSH	IX
	CALL	C.B935
;
	POP	IX
	LD	A,H
	AND	A
	JR	NZ,J$A3A2
;
	LD	A,4CH	; "L"
	CALL	C.B8A8
;
	JR	J$A381
;
;	-----------------
J$A3A2:	CP	02H	; 2 
	JP	NZ,J.A3BA
;
	LD	A,0FFH
	LD	(D.D464),A
	JR	J.A3B7
;
;	-----------------
J$A3AE:	CALL	C.B751
;
	POP	HL
	CALL	C.877C
;
J.A3B5:	AND	A
	RET	
;
;	-----------------
J.A3B7:	POP	HL
	SCF	
	RET	
;
;	-----------------
J.A3BA:	LD	A,01H	; 1 
	LD	(D.D44A),A
	POP	HL
	SCF	
	RET	
;
;	-----------------
J.A3C2:	PUSH	HL
J$A3C3:	LD	HL,I.D1BD
	CALL	C.A6A7
;
	JR	NC,J$A3F1
;
	LD	A,03H	; 3 
	CALL	C.B8A8
;
	LD	A,66H	; "f"
	PUSH	IX
	CALL	C.B935
;
	POP	IX
	LD	A,H
	AND	A
	JR	NZ,J$A3E4
;
	LD	A,4CH	; "L"
	CALL	C.B8A8
;
	JR	J$A3C3
;
;	-----------------
J$A3E4:	CP	02H	; 2 
	JP	NZ,J.A3BA
;
	LD	A,0FFH
	LD	(D.D464),A
	JP	J.A3B7
;
;	-----------------
J$A3F1:	POP	HL
	RET	
;
;	-----------------
J$A3F3:	CALL	C.A66C
;
	LD	A,B
	CP	20H	; " "
	JP	C,J.A56F
;
	LD	D,02H	; 2 
	CP	80H
I$A400:	JP	C,J.A550
;
	CP	0A0H
	JR	C,J$A42B
;
	CP	0E0H
	JP	C,J.A550
;
	CP	0F0H
	JP	C,J.A556
;
	LD	D,10H	; 16 
	CP	0FBH
	JP	Z,J.A556
;
	LD	D,08H	; 8 
	CP	0FDH
	JP	Z,J.A556
;
	LD	D,04H	; 4 
	CP	0F0H
	JP	Z,J.A556
;
	LD	D,02H	; 2 
	JP	J.A556
;
;	-----------------
J$A42B:	LD	A,(D.CC3F)
	CP	01H	; 1 
	JP	NZ,J.A556
;
	LD	A,B
	CP	81H
	JR	Z,J$A445
;
	CP	82H
	JP	Z,J$A4DA
;
	CP	83H
	JP	Z,J$A510
;
	JP	J.A556
;
;	-----------------
J$A445:	LD	A,C
	CP	41H	; "A"
	JP	C,J.A556
;
	CP	45H	; "E"
	JP	C,J.A55D
;
	CP	4AH	; "J"
	JP	C,J.A556
;
	CP	4CH	; "L"
	JP	C,J.A55D
;
	CP	50H	; "P"
	JP	C,J.A556
;
	CP	52H	; "R"
	JP	C,J.A564
;
	CP	5BH	; "["
	JP	C,J.A556
;
	CP	5CH	; "\"
	JP	C,J.A55D
;
	CP	5EH	; "^"
	JP	C,J.A564
;
	CP	60H	; "`"
	JP	C,J.A556
;
	CP	65H	; "e"
	JP	C,J.A564
;
	CP	69H	; "i"
	JP	C,J.A55D
;
	CP	7DH	; "}"
	JP	C,J.A564
;
	CP	81H
	JP	C,J.A556
;
	CP	87H
	JP	C,J.A564
;
	CP	8BH
	JP	C,J.A556
;
	CP	8EH
	JP	C,J.A55D
;
	CP	0A8H
	JP	C,J.A556
;
	CP	0ACH
	JP	C,J.A564
;
	CP	0B8H
	JP	C,J.A556
;
	CP	0C0H
	JP	C,J.A564
;
	CP	0C8H
	JP	C,J.A556
;
	CP	0CDH
	JP	C,J.A564
;
	CP	0DFH
	JP	C,J.A556
;
	CP	0E3H
	JP	C,J.A564
;
	CP	0E4H
	JP	C,J.A556
;
	CP	0E6H
	JP	C,J.A564
;
	CP	0E7H
	JP	C,J.A556
;
	CP	0E9H
	JP	C,J.A564
;
	JP	J.A556
;
;	-----------------
J$A4DA:	LD	A,C
	CP	9FH
	JP	Z,J.A55D
;
	CP	0A1H
	JP	Z,J.A55D
;
	CP	0A3H
	JP	Z,J.A55D
;
	CP	0A5H
	JP	Z,J.A55D
;
	CP	0A7H
	JP	Z,J.A55D
;
	CP	0C1H
	JP	Z,J.A55D
;
	CP	0E1H
	JP	Z,J.A55D
;
	CP	0E3H
	JP	Z,J.A55D
;
	CP	0E5H
	JP	Z,J.A55D
;
	CP	0ECH
	JP	Z,J.A55D
;
	JP	J.A556
;
;	-----------------
J$A510:	LD	A,C
	CP	40H	; "@"
	JP	Z,J.A55D
;
	CP	42H	; "B"
	JP	Z,J.A55D
;
	CP	44H	; "D"
	JP	Z,J.A55D
;
	CP	46H	; "F"
	JP	Z,J.A55D
;
	CP	48H	; "H"
	JP	Z,J.A55D
;
	CP	62H	; "b"
	JP	Z,J.A55D
;
	CP	83H
	JP	Z,J.A55D
;
	CP	85H
	JP	Z,J.A55D
;
	CP	87H
	JP	Z,J.A55D
;
	CP	8EH
	JP	Z,J.A55D
;
	CP	95H
	JP	Z,J.A55D
;
	CP	96H
	JP	Z,J.A55D
;
	JP	J.A556
;
;	-----------------
J.A550:	CALL	C.B75E
;
	CALL	C.B751
;
J.A556:	CALL	C.A571
;
	JR	C,J.A570
;
	JR	J.A56F
;
;	-----------------
J.A55D:	CALL	C$A606
;
	JR	C,J.A570
;
	JR	J$A569
;
;	-----------------
J.A564:	CALL	C.A571
;
	JR	C,J.A570
;
J$A569:	CALL	C.88BB
;
	CALL	C.877C
;
J.A56F:	AND	A
J.A570:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A571:	PUSH	HL
	LD	A,D
	AND	04H	; 4 
	JR	NZ,J.A5C7
;
	LD	A,D
	AND	19H
	JR	NZ,J.A5BB
;
	LD	A,B
	CP	98H
	JR	C,J.A5BB
;
	JR	NZ,J$A58A
;
	LD	A,C
	CP	9EH
	JR	C,J.A5BB
;
	JR	J.A5B2
;
;	-----------------
J$A58A:	LD	A,B
	CP	9FH
	JR	C,J.A5B2
;
	JR	NZ,J$A598
;
	LD	A,C
	CP	0FDH
	JR	C,J.A5B2
;
	JR	J.A5BB
;
;	-----------------
J$A598:	CP	0E0H
	JR	C,J.A5BB
;
	JR	NZ,J$A5A5
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.A5BB
;
	JR	J.A5B2
;
;	-----------------
J$A5A5:	CP	0EAH
	JR	C,J.A5B2
	JR	NZ,J.A5BB
	LD	A,C
	CP	9FH
	JR	C,J.A5B2
	JR	J.A5BB

J.A5B2:	LD	A,(D.D49D)
	BIT	1,A			; 12x12 JIS2 ROM ?
	JR	Z,J.A5C7		; nope,
	JR	J$A5C2

J.A5BB:	LD	A,(D.D49D)
	BIT	0,A			; 12x12 JIS1 ROM ?
	JR	Z,J.A5C7		; nope,
J$A5C2:	CALL	C.A984
	JR	J$A603

J.A5C7:	LD	HL,I.D1BD
	CALL	C.A6A7
	JR	NC,J$A5FE
	LD	A,03H	; 3 
	CALL	C.B8A8
	LD	A,66H	; "f"
	PUSH	IX
	PUSH	IY
	CALL	C.B935
	POP	IY
	POP	IX
	LD	A,H
	AND	A
	JR	NZ,J$A5EC
	LD	A,4CH	; "L"
	CALL	C.B8A8
	JR	J.A5C7

J$A5EC:	CP	02H	; 2 
	LD	A,01H	; 1 
	JR	NZ,J$A5F8
	LD	(D.D464),A
	SCF	
	JR	J.A604

J$A5F8:	LD	(D.D44A),A
	SCF	
	JR	J.A604

J$A5FE:	LD	A,01H	; 1 
	CALL	C.8C92
J$A603:	AND	A
J.A604:	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A606:	PUSH	HL
	LD	A,(D.D49D)
	BIT	0,A			; 12x12 JIS1 ?
	JR	Z,J.A613		; nope,
	CALL	C$A971
	JR	J$A64F

J.A613:	LD	HL,I.D1BD
	CALL	C.A93D
	JR	NC,J$A64A
	LD	A,03H	; 3 
	CALL	C.B8A8
	LD	A,66H	; "f"
	PUSH	IX
	PUSH	IY
	CALL	C.B935
	POP	IY
	POP	IX
	LD	A,H
	AND	A
	JR	NZ,J$A638
	LD	A,4CH	; "L"
	CALL	C.B8A8
	JR	J.A613

J$A638:	CP	02H	; 2 
	LD	A,01H	; 1 
	JR	NZ,J$A644
	LD	(D.D464),A
	SCF	
	JR	J.A650

J$A644:	LD	(D.D44A),A
	SCF	
	JR	J.A650

J$A64A:	LD	A,01H	; 1 
	CALL	C.8C92
J$A64F:	AND	A
J.A650:	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A652:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,I.5E14
	LD	DE,I$5E15
	LD	BC,I$10DF
	LD	(HL),00H
	LDIR	
	CALL	C.BD49			; restore slot on page 1
;
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A66C:	PUSH	AF
	PUSH	BC
	PUSH	HL
	LD	HL,I.D1BD
	LD	BC,I$0120
J$A675:	LD	(HL),00H
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$A675
;
	POP	HL
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$A681:	LD	A,B
	CP	80H
	JR	C,J.A690
;
	CP	0A0H
	JR	C,J.A695
;
	CP	0E0H
	JR	C,J.A690
;
	JR	J.A695
;
;	-----------------
J.A690:	CALL	C.B75E
;
	JR	J.A6A5
;
;	-----------------
J.A695:	LD	A,B
	CP	0F0H
	JR	Z,J.A6A5
;
	CP	0FBH
	JR	Z,J.A6A5
;
	CP	0FDH
	JR	Z,J.A6A5
;
	CALL	C.B76B
;
J.A6A5:	RET	
;
;	-----------------
J$A6A6:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A6A7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IY
	LD	A,B
	CP	20H	; " "
	JR	NC,J$A6B9
	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	JP	J.A731

J$A6B9:	CP	7FH
	JR	NC,J$A6CA
	CALL	C.A845
	JR	NC,J$A6C8
	LD	B,24H	; "$"
	CALL	C.A967			; clear buffer
	SCF	
J$A6C8:	JR	J.A731

J$A6CA:	CP	80H
	JR	NC,J$A6D6
	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	SCF	
	JR	J.A731

J$A6D6:	CP	0A0H
	JR	NC,J$A6E7
	CALL	C.A869
	JR	NC,J$A6E5
	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	SCF	
J$A6E5:	JR	J.A731

J$A6E7:	CP	0E0H
	JR	NC,J$A6F8
	CALL	C.A845
	JR	NC,J$A6F6
	LD	B,24H	; "$"
	CALL	C.A967			; clear buffer
	SCF	
J$A6F6:	JR	J.A731

J$A6F8:	CP	0F0H
	JR	NC,J$A709
	CALL	C.A869
	JR	NC,J$A707
	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	SCF	
J$A707:	JR	J.A731

J$A709:	JR	NZ,J$A711
	CALL	C.A737
	OR	A
	JR	J.A731

J$A711:	CP	0FBH
	JR	NZ,J$A722
	CALL	C$A884
	JR	NC,J$A720
	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	SCF	
J$A720:	JR	J.A731

J$A722:	CP	0FDH
	JR	NZ,J$A72B
	CALL	C$A8A1
	JR	NC,J.A731
J$A72B:	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	SCF	
J.A731:	POP	IY
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A737:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	HL
	LD	A,C
	LD	C,40H	; "@"
	SUB	C
	INC	A
	LD	DE,I.0048
	LD	HL,X.0000
	LD	B,A
J$A747:	ADD	HL,DE
	DJNZ	J$A747
	AND	A
	SBC	HL,DE
	LD	DE,I$3401
	ADD	HL,DE
	POP	DE
	LD	BC,I.0048
	LD	A,1
	LD	(D.D498),A
	CALL	C.BB17			; select firmware on page 1
	EX	AF,AF'
	LD	A,80H			; segment = SRAM
	CALL	C.B97F			; select firmware slot and segment in page 0
	LDIR	
	CALL	C.B9F2			; restore slot and segment in page 0
	CALL	C.BB71			; restore slot in page 1
	XOR	A
	LD	(D.D498),A
	AND	A
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A774:	DI	
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	D,1BH
	CALL	C.9DFC
;
	JP	NC,J$A786
;
	CALL	C.A843
;
	JP	J.A83E
;
;	-----------------
J$A786:	LD	A,(D.CC3D)
	AND	0FH	; 15 
	CP	02H	; 2 
	JR	Z,J.A797
;
	CP	04H	; 4 
	JR	Z,J.A797
;
	LD	D,79H	; "y"
	JR	J$A799
;
;	-----------------
J.A797:	LD	D,78H	; "x"
J$A799:	CALL	C.9DFC
;
	JP	NC,J$A7A5
;
	CALL	C.A843
;
	JP	J.A83E
;
;	-----------------
J$A7A5:	LD	A,(D.D445)
	LD	D,A
	CALL	C.9DFC
;
	JP	NC,J$A7B5
;
	CALL	C.A843
;
	JP	J.A83E
;
;	-----------------
J$A7B5:	LD	A,(D.D446)
	LD	D,A
	CALL	C.9DFC
	JP	NC,J$A7C5
	CALL	C.A843
	JP	J.A83E

J$A7C5:	IN	A,(41H)
	LD	E,00H
	LD	B,48H	; "H"
	LD	HL,I.D3FD
J$A7CE:	PUSH	BC
	LD	D,00H
	LD	B,00H
J$A7D3:	PUSH	BC
	LD	B,00H
J$A7D6:	PUSH	BC
	IN	A,(46H)
	AND	01H	; 1 
	JR	Z,J$A7E7
	LD	D,01H	; 1 
	POP	BC
	LD	B,01H	; 1 
	POP	BC
	LD	B,01H	; 1 
	PUSH	BC
	PUSH	BC
J$A7E7:	POP	BC
	DJNZ	J$A7D6
	POP	BC
	DJNZ	J$A7D3
	LD	A,D
	OR	A
	JR	NZ,J$A7F7
	POP	BC
	LD	B,01H	; 1 
	PUSH	BC
	JR	J$A7FD

J$A7F7:	IN	A,(45H)
	LD	(HL),A
	INC	HL
	ADD	A,E
	LD	E,A
J$A7FD:	POP	BC
	DJNZ	J$A7CE
;
I.A800:	LD	A,D
I$A801:	OR	A
	JR	NZ,J$A80A
	CALL	C.A843
	JP	J.A83E

J$A80A:	LD	D,00H
	LD	B,00H
J$A80E:	PUSH	BC
	LD	B,00H
J$A811:	PUSH	BC
	IN	A,(46H)
	AND	01H	; 1 
	JR	Z,J$A822
	LD	D,01H	; 1 
	POP	BC
	LD	B,01H	; 1 
	POP	BC
	LD	B,01H	; 1 
	PUSH	BC
	PUSH	BC
J$A822:	POP	BC
	DJNZ	J$A811
	POP	BC
	DJNZ	J$A80E
	LD	A,D
	OR	A
	JR	NZ,J$A831
	CALL	C.A843
	JR	J.A83E

J$A831:	IN	A,(45H)
	ADD	A,E
	CP	0FFH
	JR	Z,J$A83D
	CALL	C.A843
	JR	J.A83E

J$A83D:	XOR	A
J.A83E:	POP	HL
	POP	DE
	POP	BC
	EI	
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.A843:	SCF	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A845:	PUSH	HL
	LD	A,04H	; 4 
	LD	(D.D456),A
	LD	A,B
	LD	B,00H
	LD	C,A
	LD	(D.D446),A
	XOR	A
	LD	(D.D445),A
	CALL	C.AA11
	JR	C,J$A85E
	AND	A
	POP	HL
	RET	

J$A85E:	SCF	
	POP	HL
	RET	
;
;	-----------------
J$A861:	LD	C,00H
	LD	D,01H	; 1 
	CALL	C.A984
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A869:	PUSH	HL
	CALL	C.B76B
;
	XOR	A
	LD	(D.D456),A
	LD	A,B
	LD	(D.D445),A
	LD	A,C
	LD	(D.D446),A
	CALL	C.AA11
;
	JR	C,J$A881
;
	AND	A
	POP	HL
	RET	
;
;	-----------------
J$A881:	SCF	
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A884:	PUSH	HL
	CALL	C.B76B
;
	LD	A,01H	; 1 
	LD	(D.D456),A
	LD	A,0FH	; 15 
	LD	(D.D445),A
	LD	A,C
	LD	(D.D446),A
	CALL	C.AA11
;
	JR	C,J$A89E
;
	AND	A
	POP	HL
	RET	
;
;	-----------------
J$A89E:	SCF	
	POP	HL
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A8A1:	PUSH	HL
	LD	A,03H	; 3 
	LD	(D.D456),A
	LD	A,C
	CP	9FH
	JR	NC,J$A8B6
;
	CALL	C.B76B
;
	LD	A,0DH	; 13 
	LD	(D.D445),A
	JR	J$A8BE
;
;	-----------------
J$A8B6:	CALL	C.B76B
;
	LD	A,0EH	; 14 
	LD	(D.D445),A
J$A8BE:	LD	A,C
	LD	(D.D446),A
	CALL	C.AA11
;
	JR	C,J$A8CA
;
	AND	A
	POP	HL
	RET	
;
;	-----------------
J$A8CA:	SCF	
	POP	HL
	RET	
;
;	-----------------
?.A8CD:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	HL
	LD	A,B
	CP	20H	; " "
	JR	C,J.A8F3
;
	LD	A,01H	; 1 
	LD	(D.D445),A
	LD	A,B
	LD	(D.D446),A
	CALL	C.AA11
;
	JR	C,J.A8F3
;
	POP	HL
	LD	DE,I.D3FD
	LD	BC,C.001B
	EX	DE,HL
	LDIR	
	AND	A
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J.A8F3:	POP	HL
	LD	B,1BH
	CALL	C.A967			; clear buffer
	SCF	
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
?.A8FE:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	HL
	LD	A,B
	CP	20H	; " "
	JR	C,J.A932
;
	LD	A,02H	; 2 
	LD	(D.D445),A
	LD	A,B
	LD	(D.D446),A
	LD	D,1BH
	CALL	C.9DFC
;
	JR	C,J.A932
;
	LD	D,50H	; "P"
	CALL	C.9DFC
;
	JR	C,J.A932
;
	CALL	C$A774
;
	JR	C,J.A932
;
	POP	HL
	LD	DE,I.D3FD
	LD	BC,C.001B
	EX	DE,HL
	LDIR	
	AND	A
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J.A932:	POP	HL
	LD	B,1BH
	CALL	C.A967			; clear buffer
	SCF	
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A93D:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	HL
	CALL	C.B76B
;
	LD	A,02H	; 2 
	LD	(D.D456),A
	LD	A,B
	LD	(D.D445),A
	LD	A,C
	LD	(D.D446),A
	CALL	C.AA11
;
	JR	C,J$A95C
;
	POP	HL
	AND	A
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J$A95C:	POP	HL
	LD	B,48H	; "H"
	CALL	C.A967			; clear buffer
	SCF	
	POP	HL
	POP	DE
	POP	BC
	RET	

;	  Subroutine clear buffer
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.A967:	PUSH	BC
	PUSH	HL
	XOR	A
J$A96A:	LD	(HL),A
	INC	HL
	DJNZ	J$A96A
	POP	HL
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$A971:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,B
	AND	3FH	; "?"
	ADD	A,12H	; 18 
	LD	B,A
	LD	A,C
	SUB	40H	; "@"
	LD	C,A
	CALL	C$B972
	JR	J$A9AA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.A984:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,D
	LD	(D.D171),A
	XOR	A
	LD	HL,I$D189
	LD	(HL),A
	LD	A,(D.D48A)
	CP	01H	; 1 
	JR	NZ,J$A99B
	XOR	A
	JR	J.A9A5

J$A99B:	CP	02H	; 2 
	JR	NZ,J$A9A3
	LD	A,04H	; 4 
	JR	J.A9A5
;
;	-----------------
J$A9A3:	LD	A,08H	; 8 
J.A9A5:	DEC	HL
	LD	(HL),A
	CALL	C$B778
J$A9AA:	XOR	A
	LD	B,48H	; "H"
	LD	HL,I.D2DD
J$A9B0:	LD	(HL),A
	INC	HL
	DJNZ	J$A9B0
	LD	DE,I.D129
	LD	HL,I.D2DD
	LD	B,06H	; 6 
J$A9BC:	LD	A,(DE)
	INC	DE
	LD	(HL),A
	INC	HL
	LD	A,(DE)
	AND	0F0H
	LD	(HL),A
	INC	HL
	INC	HL
	LD	A,(DE)
	INC	DE
	EX	DE,HL
	SLA	(HL)
	RLA	
	SLA	(HL)
	RLA	
	SLA	(HL)
	RLA	
	SLA	(HL)
	RLA	
	EX	DE,HL
	LD	(HL),A
	INC	HL
	LD	A,(DE)
	INC	DE
	LD	(HL),A
	INC	HL
	INC	HL
	DJNZ	J$A9BC
	CALL	C.8941
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$A9E7:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	D,00H
	LD	HL,I.7804
	LD	BC,I$073A
J$A9FA:	LD	(HL),D
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$A9FA
I$AA00	EQU	$-1
;
I$AA01:	XOR	A
	LD	(D.D447),A
	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.AA11:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	A,(D.D499)
	AND	A
	JR	NZ,J$AA22
	CALL	C$B942
	JP	C,J.AAC5
J$AA22:	LD	A,01H	; 1 
	LD	(D.D499),A
	XOR	A
	LD	(D.D44A),A
	LD	(D.D464),A
	LD	A,(D$D448)
	AND	A
	JR	NZ,J$AA3D
	CALL	C.B8CE
	JP	C,J.AAC5
	JP	J.AABE
;
;	-----------------
J$AA3D:	PUSH	HL
	LD	IX,I.7804
	LD	D,19H
J$AA44:	CALL	C.BCF6			; select RAM on page 1
;
	LD	L,(IX)
	LD	H,(IX+1)
	CALL	C.BD49			; restore slot on page 1
;
	XOR	A
	SBC	HL,BC
	JR	Z,J$AAA2
;
	INC	IX
	INC	IX
	DEC	D
	JR	NZ,J$AA44
;
	POP	HL
	PUSH	HL
	CALL	C.B8CE
;
	POP	HL
	JR	C,J.AAC5
;
	PUSH	HL
	LD	IX,I.7836
	LD	HL,I.7804
	LD	A,(D.D447)
	AND	A
	JR	Z,J$AA7C
;
J$AA72:	INC	HL
	INC	HL
	LD	DE,I.0048
	ADD	IX,DE
	DEC	A
	JR	NZ,J$AA72
;
J$AA7C:	CALL	C.BCF6			; select RAM on page 1
;
	LD	(HL),C
	INC	HL
	LD	(HL),B
	CALL	C.BD49			; restore slot on page 1
;
	POP	HL
	PUSH	IX
	POP	DE
	LD	BC,I.0048
	CALL	C.BCF6			; select RAM on page 1
;
	LDIR	
	CALL	C.BD49			; restore slot on page 1
;
	LD	A,(D.D447)
	INC	A
	CP	19H
	JR	C,J$AA9D
;
	XOR	A
J$AA9D:	LD	(D.D447),A
	JR	J.AABE
;
;	-----------------
J$AAA2:	LD	B,D
	POP	DE
	LD	HL,I.7836
	LD	A,19H
	SUB	B
	JR	Z,J$AAB3
;
J$AAAC:	LD	BC,I.0048
	ADD	HL,BC
	DEC	A
	JR	NZ,J$AAAC
;
J$AAB3:	LD	BC,I.0048
	CALL	C.BCF6			; select RAM on page 1
;
	LDIR	
	CALL	C.BD49			; restore slot on page 1
;
J.AABE:	XOR	A
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
J.AAC5:	CALL	C.B5C4			; select ROM BIOS on page 0
	CALL	C$AAD9
	CALL	C.B686			; restore slot on page 0
	XOR	A
	LD	(D.D499),A
	SCF	
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$AAD9:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,255
J$AAE0:	PUSH	BC
	CALL	H.TIMI
	DI	
	POP	BC
	DEC	B
	JR	NZ,J$AAE0
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
J$AAEF:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.C339)
	CP	18H
	JR	Z,J.AB1B
;
	LD	HL,D.C327
	CP	(HL)
	JR	NC,J$AB04
;
	INC	A
	INC	A
	JR	J.AB1B
;
;	-----------------
J$AB04:	LD	A,(HL)
	JR	NZ,J$AB0B
;
	INC	A
	INC	A
	JR	J$AB0F
;
;	-----------------
J$AB0B:	INC	A
	INC	A
	INC	A
	INC	A
J$AB0F:	CP	19H
	JR	NZ,J$AB17
;
	LD	A,17H
	JR	J.AB1B
;
;	-----------------
J$AB17:	JR	C,J.AB1B
;
	LD	A,18H
J.AB1B:	CALL	C.AB23
;
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.AB23:	CALL	C.BCF6			; select RAM on page 1
;
	LD	HL,I.5E14
	LD	(D.C393),HL
	LD	HL,I$05A0
	LD	(D.C395),HL
	CALL	C.AB39
;
	CALL	C.BD49			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.AB39:	CALL	C.BCF6			; select RAM on page 1
;
	LD	E,00H
	CP	18H
	JR	NC,J$AB59
;
	CP	08H	; 8 
	JR	C,J.AB50
;
	SUB	08H	; 8 
	INC	E
	CP	08H	; 8 
	JR	C,J.AB50
;
	SUB	08H	; 8 
	INC	E
J.AB50:	CALL	C$AB5D
;
	CALL	C.AB86
;
	CALL	C.AB86
;
J$AB59:	CALL	C.BD49			; restore slot on page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$AB5D:	LD	C,A
	LD	B,00H
	LD	HL,I$AB7D
	ADD	HL,BC
	LD	A,(HL)
	LD	D,00H
	LD	HL,(D.C393)
	ADD	HL,DE
	LD	BC,(D.C395)
	LD	D,A
J$AB70:	LD	A,(HL)
	AND	D
	LD	(HL),A
	INC	HL
	INC	HL
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$AB70
;
	INC	E
	RET	
;
;	-----------------
I$AB7D:	NOP	
	LD	BC,I.0703
	RRCA	
	RRA	
	CCF	
	LD	A,A
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.AB86:	LD	A,E
	CP	03H	; 3 
	RET	Z
;
	LD	D,00H
	LD	HL,(D.C393)
	ADD	HL,DE
	LD	BC,(D.C395)
J$AB94:	LD	(HL),00H
	INC	HL
	INC	HL
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$AB94
;
	INC	E
	RET	
;
;	-----------------
J$ABA0:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IY
	LD	A,01H	; 1 
	LD	(D.D171),A
	XOR	A
	LD	IY,I$D185
	LD	(IY+4),A
	LD	A,(D.D48A)
	CP	01H	; 1 
	JR	NZ,J$ABBD
;
	XOR	A
	JR	J.ABC7
;
;	-----------------
J$ABBD:	CP	02H	; 2 
	JR	NZ,J$ABC5
;
	LD	A,04H	; 4 
	JR	J.ABC7
;
;	-----------------
J$ABC5:	LD	A,08H	; 8 
J.ABC7:	LD	(IY+3),A
	CALL	C.B785
;
	XOR	A
	LD	B,48H	; "H"
	LD	HL,I.D2DD
J$ABD3:	LD	(HL),A
	INC	HL
	DJNZ	J$ABD3
	LD	DE,I.D129
	LD	HL,I.D2DD
	LD	B,06H	; 6 
J$ABDF:	LD	A,(DE)
	INC	DE
	LD	(HL),A
	INC	HL
	LD	A,(DE)
	AND	0F0H
	LD	(HL),A
	INC	HL
	INC	HL
	LD	A,(DE)
	INC	DE
	EX	DE,HL
	SLA	(HL)
	RLA	
	SLA	(HL)
	RLA	
	SLA	(HL)
	RLA	
	SLA	(HL)
	RLA	
	EX	DE,HL
	LD	(HL),A
	INC	HL
	LD	A,(DE)
	INC	DE
	LD	(HL),A
	INC	HL
	INC	HL
	DJNZ	J$ABDF
	CALL	C.8941
	POP	IY
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.AC0C:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,C
	CP	0A0H
	JR	C,J.AC20
;
	CP	0E0H
	JR	NC,J.AC20
;
	SUB	20H	; " "
	LD	C,A
J.AC20:	LD	A,(D.D48A)
	LD	B,02H	; 2 
	CP	01H	; 1 
	JR	Z,J.AC31
;
	LD	B,04H	; 4 
	CP	02H	; 2 
	JR	Z,J.AC31
;
	LD	B,06H	; 6 
J.AC31:	CALL	C.B785
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
J$AC3D:	PUSH	IX
	LD	A,(X.DACD)
	AND	A
	JR	Z,J$AC4C
;
	LD	IX,I$AC4F
	CALL	C$AC74
;
J$AC4C:	POP	IX
	RET	
;
;	-----------------
I$AC4F:	AND	L
	JP	C,X.DACD
;
J$AC53:	PUSH	HL
	PUSH	IX
	LD	A,(X.CC4B)
	AND	A
	JR	Z,J$AC6C
;
	LD	A,(D$CC4A)
	LD	HL,I$C389
	CALL	C.AFE5
;
	LD	IX,I$AC70
	CALL	C$ADB7
;
J$AC6C:	POP	IX
	POP	HL
	RET	
;
;	-----------------
I$AC70:	ADC	A,C
	JP	X.CC4B
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$AC74:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,X.0000
	LD	(D.C9D0),HL
	CALL	C.AF74
;
	LD	E,(IX)
	LD	D,(IX+1)
	PUSH	DE
	POP	IY
	LD	B,28H	; "("
J$AC8F:	LD	A,(IY)
	AND	A
	JP	Z,J.ADAE
;
	PUSH	BC
	PUSH	HL
	CP	20H	; " "
	JP	C,J$ADA1
;
	JP	Z,J$AD97
;
	CP	80H
	JP	C,J.AD29
;
	CP	0A0H
	JR	C,J$ACAD
;
	CP	0E0H
	JR	C,J.AD29
;
J$ACAD:	LD	A,(D$CC4C)
	CP	02H	; 2 
	JR	NZ,J$ACCB
;
	LD	A,(D.CC3F)
	RLCA	
	RLCA	
	RLCA	
	RLCA	
	OR	01H	; 1 
	LD	HL,I.D1BD
	LD	B,(IY)
	LD	C,(IY+1)
	CALL	C$B95C
;
	JR	NC,J$ACF0
;
J$ACCB:	CALL	C.B07A
;
	LD	A,(D.C9C6)
	RLCA	
	JR	NC,J.AD08
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.AD08
;
	LD	B,(IY)
	LD	C,(IY+1)
	PUSH	IY
	CALL	C.A197
;
	POP	IY
	JP	C,J.ADA9
;
	LD	A,(D.D449)
	AND	A
	JR	NZ,J.AD08
;
J$ACF0:	LD	A,(D.CC3F)
	AND	A
	CALL	NZ,C.876D
;
	POP	HL
	INC	HL
	INC	HL
	CALL	C$B061
;
	LD	DE,I.001A
	ADD	HL,DE
	LD	A,01H	; 1 
	LD	(D.C33D),A
	JR	J$AD20
;
;	-----------------
J.AD08:	POP	HL
	INC	HL
	INC	HL
	CALL	C.9F3D
;
	LD	DE,C.0018
	ADD	HL,DE
	LD	(D.C9D0),HL
	INC	HL
	INC	HL
	LD	B,(IY)
	LD	C,(IY+1)
	CALL	C.A00C
;
J$AD20:	INC	IY
	INC	IY
	POP	BC
	DEC	B
	JP	J.ADA3
;
;	-----------------
J.AD29:	LD	A,(D.CC3F)
	AND	A
	JR	NZ,J$AD5E
;
	LD	B,(IY)
	CALL	C.B07A
;
	LD	A,(D.C9C6)
	RLCA	
	JR	C,J$AD52
;
	POP	HL
	INC	HL
	CALL	C.9F3D
;
	LD	DE,C.000C
	ADD	HL,DE
	LD	(D.C9D0),HL
	INC	HL
	LD	A,(IY)
	INC	IY
	CALL	C.9FE7
;
	JR	J$AD94
;
;	-----------------
J$AD52:	LD	B,(IY)
	INC	IY
	CALL	C.A197
;
	JR	C,J.ADA9
;
	JR	J$AD75
;
;	-----------------
J$AD5E:	LD	B,(IY)
	INC	IY
	CALL	C.B75E
;
	CALL	C.B751
;
	CALL	C.A197
;
	JR	C,J.ADA9
;
	CALL	C.876D
;
	XOR	A
	CALL	C.8C92
;
J$AD75:	POP	HL
	INC	HL
	PUSH	HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I.D1BD
	LD	BC,I.0024
	CALL	C.A171
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	POP	HL
	LD	DE,I.000D
	ADD	HL,DE
J$AD94:	POP	BC
	JR	J.ADA3
;
;	-----------------
J$AD97:	INC	IY
	POP	HL
	LD	DE,I$000E
	ADD	HL,DE
	POP	BC
	JR	J.ADA3
;
;	-----------------
J$ADA1:	POP	HL
	POP	BC
J.ADA3:	DEC	B
	JP	NZ,J$AC8F
;
	JR	J.ADAE
;
;	-----------------
J.ADA9:	POP	HL
	POP	BC
	SCF	
	JR	J$ADAF
;
;	-----------------
J.ADAE:	AND	A
J$ADAF:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$ADB7:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	HL,X.0000
	LD	(D.C9D0),HL
	CALL	C.AF74
;
	LD	E,(IX)
	LD	D,(IX+1)
	PUSH	DE
	POP	IY
	LD	B,28H	; "("
J$ADD2:	LD	A,(IY)
	AND	A
	JP	Z,J.AF47
;
	PUSH	BC
	PUSH	HL
	CP	20H	; " "
	JP	C,J.AF3B
;
	CP	2DH	; "-"
	JP	Z,J$ADF6
;
	CP	30H	; "0"
	JP	C,J.AF3B
;
	CP	3AH	; ":"
	JR	C,J$AE1B
;
	CP	0FFH
	JP	Z,J$AEF0
;
	JP	J.AF3B
;
;	-----------------
J$ADF6:	INC	IY
	POP	HL
	INC	HL
	PUSH	HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I$AF50
	LD	BC,I.0024
	CALL	C.A171
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	POP	HL
	LD	DE,I.000D
	ADD	HL,DE
	POP	BC
	JP	J.AF3D
;
;	-----------------
J$AE1B:	LD	A,(D.CC3F)
	AND	A
	JR	NZ,J$AE74
;
	LD	B,(IY)
	CALL	C.B07A
;
	LD	A,(D.C9C6)
	RLCA	
	JR	C,J$AE46
;
	POP	HL
	INC	HL
	CALL	C.9F3D
;
	LD	DE,C.000C
	ADD	HL,DE
	LD	(D.C9D0),HL
	INC	HL
	LD	A,(IY)
	INC	IY
	CALL	C.9FE7
;
	POP	BC
	JP	J.AF3D
;
;	-----------------
J$AE46:	LD	B,(IY)
	INC	IY
	CALL	C.A197
;
	JP	C,J.AF43
;
	POP	HL
	INC	HL
	PUSH	HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I.D1BD
	LD	BC,I.0024
	CALL	C.A171
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	POP	HL
	LD	DE,I.000D
	ADD	HL,DE
	POP	BC
	JP	J.AF3D
;
;	-----------------
J$AE74:	LD	B,(IY)
	INC	IY
	CALL	C.A197
;
	JP	C,J.AF43
;
	LD	HL,I.D1BD
	LD	DE,I.C91B
	LD	BC,I.0024
	LDIR	
	LD	B,(IY)
	INC	IY
	CALL	C.A197
;
	JP	C,J.AF43
;
	LD	HL,I.C91B
	LD	DE,I.D1E1
	LD	BC,I.0024
	LDIR	
	JR	J.AF14
;
;	-----------------
?.AEA2:	LD	A,(IY+1)
	CP	6FH	; "o"
	JP	NZ,J.AF3B
;
	LD	B,(IY)
	LD	C,(IY+1)
	CALL	C.B07A
;
	LD	A,(D.C9C6)
	RLCA	
	JR	C,J$AED9
;
	POP	HL
	INC	HL
	INC	HL
	CALL	C.9F3D
;
	LD	DE,C.0018
	ADD	HL,DE
	LD	(D.C9D0),HL
	INC	HL
	INC	HL
	LD	B,(IY)
	LD	C,(IY+1)
	INC	IY
	INC	IY
	CALL	C.A00C
;
	POP	BC
	DEC	B
	JR	J.AF3D
;
;	-----------------
J$AED9:	LD	B,(IY)
	LD	C,(IY+1)
	INC	IY
	INC	IY
	CALL	C.A197
;
	JR	C,J.AF43
;
	LD	A,(D.CC3F)
	AND	A
	JR	Z,J$AF17
;
	JR	J.AF14
;
;	-----------------
J$AEF0:	LD	A,(D.CC3F)
	AND	A
	JR	Z,J.AF3B
;
	INC	IY
	LD	B,(IY)
	INC	IY
	CALL	C.A197
;
	JR	C,J.AF43
;
	LD	HL,I$D1E0
	LD	DE,I$D1F2
	LD	BC,I.0024
	LDDR	
	XOR	A
	LD	B,12H	; 18 
J$AF10:	LD	(DE),A
	DEC	DE
	DJNZ	J$AF10
;
J.AF14:	CALL	C.876D
;
J$AF17:	POP	HL
	INC	HL
	INC	HL
	PUSH	HL
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I.D1BD
	LD	BC,I.0048
	CALL	C.A171
;
	LD	A,01H	; 1 
	LD	(D.C33D),A
	POP	HL
	LD	DE,I.001A
	ADD	HL,DE
	POP	BC
	DEC	B
	JR	J.AF3D
;
;	-----------------
J.AF3B:	POP	HL
	POP	BC
J.AF3D:	DEC	B
	JP	NZ,J$ADD2
;
	JR	J.AF47
;
;	-----------------
J.AF43:	POP	HL
	POP	BC
	JR	J$AF48
;
;	-----------------
J.AF47:	AND	A
J$AF48:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$AF50:	DEFB	0,0,0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0
	EX	AF,AF'
	DEFB	0,0,0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.AF74:	LD	L,(IX+2)
	LD	H,(IX+3)
	LD	A,(HL)
	LD	HL,X.0000
	DEC	A
	JR	Z,J.AFC1
;
	LD	HL,I$AFDF
	LD	A,(D.CC3D)
	ADD	A,A
	LD	E,A
	LD	D,00H
	ADD	HL,DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	L,(IX)
	LD	H,(IX+1)
	LD	C,00H
	LD	B,28H	; "("
J$AF99:	LD	A,(HL)
	INC	HL
	AND	A
	JR	Z,J$AFA1
;
	INC	C
	DJNZ	J$AF99
;
J$AFA1:	LD	B,00H
	LD	L,C
	LD	H,B
	ADD	HL,HL
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	AND	A
	SBC	HL,BC
	EX	DE,HL
	AND	A
	SBC	HL,DE
	LD	E,(IX+2)
	LD	D,(IX+3)
	LD	A,(DE)
	CP	02H	; 2 
	JR	NZ,J.AFC1
;
	SRL	H
	RR	L
J.AFC1:	PUSH	HL
	LD	HL,(D$C3D8)
	LD	DE,C.0018
	LD	A,(D$CC40)
	AND	A
	JR	Z,J$AFD3
;
	LD	B,A
J$AFCF:	SBC	HL,DE
	DJNZ	J$AFCF
;
J$AFD3:	LD	DE,(D$C31B)
	LD	D,00H
	AND	A
	SBC	HL,DE
	POP	DE
	ADD	HL,DE
	RET	
;
;	-----------------
I$AFDF:	LD	(HL),H
	DEC	B
	LD	B,(HL)
	DEC	B
	ADD	A,(HL)
	INC	B
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.AFE5:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	DE,I.3030
	LD	C,0AH	; 10 
J$AFEE:	SUB	C
	JR	C,J$AFF4
;
	INC	D
	JR	J$AFEE
;
;	-----------------
J$AFF4:	ADD	A,C
	ADD	A,E
	LD	E,A
	LD	A,(D$CC48)
	AND	A
	JR	Z,J.B038
;
	DEC	A
	JR	NZ,J$B005
;
	CALL	C.B03F
;
	JR	J.B038
;
;	-----------------
J$B005:	DEC	A
	JR	NZ,J$B013
;
	LD	(HL),2DH	; "-"
	INC	HL
	CALL	C.B03F
;
	LD	(HL),2DH	; "-"
	INC	HL
	JR	J.B038
;
;	-----------------
J$B013:	DEC	A
	JR	NZ,J$B021
;
	LD	(HL),3CH	; "<"
	INC	HL
	CALL	C.B03F
;
	LD	(HL),3EH	; ">"
	INC	HL
	JR	J.B038
;
;	-----------------
J$B021:	DEC	A
	JR	NZ,J$B02F
;
	LD	(HL),82H
	INC	HL
	LD	(HL),6FH	; "o"
	INC	HL
	CALL	C.B03F
;
	JR	J.B038
;
;	-----------------
J$B02F:	LD	(HL),28H	; "("
	INC	HL
	CALL	C.B03F
;
	LD	(HL),29H	; ")"
	INC	HL
J.B038:	LD	(HL),00H
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B03F:	LD	A,(D.CC3F)
	AND	A
	JR	Z,J$B057
;
	LD	A,D
	CP	30H	; "0"
	JR	NZ,J$B051
;
	LD	(HL),0FFH
	INC	HL
	LD	(HL),E
	INC	HL
	JR	J.B060
;
;	-----------------
J$B051:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	JR	J.B060
;
;	-----------------
J$B057:	LD	A,D
	CP	30H	; "0"
	JR	Z,J$B05E
;
	LD	(HL),D
	INC	HL
J$B05E:	LD	(HL),E
	INC	HL
J.B060:	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B061:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	BC,I.0048
	LD	E,L
	LD	D,H
	ADD	HL,HL
	ADD	HL,DE
	LD	DE,I.5E14
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I.D1BD
	CALL	C.A171
;
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B07A:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	B,(IY)
	LD	C,(IY+1)
	LD	E,00H
	LD	A,B
	CP	81H
	JP	C,J.B174
;
	JR	Z,J$B093
;
	INC	E
	INC	E
	INC	E
	JR	J$B108
;
;	-----------------
J$B093:	LD	A,(D.CC3F)
	AND	A
	LD	A,C
	JR	NZ,J$B0AF
;
	INC	E
	CP	9FH
	JP	C,J.B174
;
	CP	0ADH
	JP	C,J.B177
;
	INC	E
	INC	E
	CP	0FDH
	JP	C,J.B177
;
	JP	J.B174
;
;	-----------------
J$B0AF:	CP	43H	; "C"
	JP	C,J.B174
;
	CP	45H	; "E"
	JP	C,J.B177
;
	CP	4AH	; "J"
	JP	C,J.B174
;
	CP	4CH	; "L"
	JP	C,J.B177
;
	CP	65H	; "e"
	JP	C,J.B174
;
	CP	69H	; "i"
	JP	C,J.B177
;
	CP	7CH	; "|"
	JP	C,J.B174
;
	CP	7DH	; "}"
	JP	C,J.B177
;
	CP	82H
	JP	C,J.B174
;
I$B0DC:	CP	87H
	JP	C,J.B177
;
	CP	8BH
	JP	C,J.B174
;
	CP	8EH
	JP	C,J.B177
;
	CP	9FH
	JP	C,J.B174
;
	INC	E
	CP	0A8H
	JP	C,J.B177
;
	INC	E
	CP	0ACH
	JR	C,J.B177
;
	DEC	E
	CP	0ADH
	JR	C,J.B177
;
	INC	E
	INC	E
	CP	0FDH
	JR	C,J.B177
;
	JR	J.B174
;
;	-----------------
J$B108:	INC	E
	LD	A,B
	CP	98H
	JR	C,J.B174
;
	JR	NZ,J$B117
;
	LD	A,C
	CP	9EH
	JR	C,J.B174
;
	JR	J.B177
;
;	-----------------
J$B117:	LD	A,B
	CP	9FH
	JR	C,J.B177
;
	JR	NZ,J$B125
;
	LD	A,C
	CP	0FDH
	JR	C,J.B177
;
	JR	J.B174
;
;	-----------------
J$B125:	CP	0E0H
	JR	C,J.B174
;
	JR	NZ,J$B132
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.B174
;
	JR	J.B177
;
;	-----------------
J$B132:	CP	0EAH
	JR	C,J.B177
;
	JR	NZ,J$B13F
;
	LD	A,C
	CP	0A3H
	JR	C,J.B177
;
	JR	J.B174
;
;	-----------------
J$B13F:	INC	E
	CP	0F0H
	JR	C,J.B174
;
	JR	NZ,J$B151
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.B174
;
	CP	69H	; "i"
	JR	C,J.B177
;
	JR	J.B174
;
;	-----------------
J$B151:	INC	E
	CP	0FBH
	JR	NZ,J$B161
;
	LD	A,C
	CP	0ADH
	JR	C,J.B174
;
	CP	0E9H
	JR	C,J.B177
;
	JR	J.B174
;
;	-----------------
J$B161:	INC	E
	CP	0FDH
	JR	NZ,J.B174
;
	LD	A,C
	CP	40H	; "@"
	JR	C,J.B174
;
	CP	9FH
	JR	C,J.B177
;
	INC	E
	CP	0FDH
	JR	C,J.B177
;
J.B174:	XOR	A
	JR	J$B188
;
;	-----------------
J.B177:	LD	D,00H
	LD	L,E
J$B17A:	LD	H,D
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	LD	A,(D.D497)
	LD	E,A
	ADD	HL,DE
	LD	DE,I$B1AF
	ADD	HL,DE
	LD	A,(HL)
J$B188:	LD	(D.C9C6),A
	LD	A,(D.D497)
	CP	05H	; 5 
	JR	NZ,J$B19A
;
	LD	A,(D.C9C6)
	OR	80H
	LD	(D.C9C6),A
J$B19A:	LD	HL,I$FBC3
	AND	A
	SBC	HL,BC
	JR	NZ,J$B1AA
;
	LD	A,(D.C9C6)
	OR	80H
	LD	(D.C9C6),A
J$B1AA:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
I$B1AF:	NOP	
	ADD	A,B
	ADD	A,B
	ADD	A,B
	NOP	
	LD	BC,I.0801
	EX	AF,AF'
	LD	BC,I$8101
	ADC	A,B
	ADC	A,B
	LD	BC,I$0101
	ADD	A,C
	ADD	A,C
J$B1C2:	LD	BC,I$8202
	ADD	A,D
	LD	(BC),A
	LD	(BC),A
	ADD	A,H
	ADD	A,H
	ADD	A,H
	ADD	A,H
	ADD	A,H
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	EX	AF,AF'
	DJNZ	J$B1E4
;
	SUB	B
	SUB	B
	DJNZ	J$B1F8
;
	JR	NZ,J$B17A
;
	AND	B
	JR	NZ,J$B1C2
;
	PUSH	HL
J$B1DE:	LD	A,B
	OR	C
	JP	Z,J.B1F4
;
	LD	H,00H
J$B1E4	EQU	$-1
	LD	L,0AH	; 10 
	CALL	C$B21F
;
	LD	A,30H	; "0"
	OR	L
	POP	HL
	LD	(HL),A
	DEC	HL
	PUSH	HL
	JP	J$B1DE
;
;	-----------------
J.B1F4:	LD	A,D
	CP	00H
	JP	NZ,J$B200
J$B1F8	EQU	$-2
;
	LD	A,E
	CP	0AH	; 10 
	JP	C,J$B210
;
J$B200:	EX	DE,HL
	LD	A,0AH	; 10 
	CALL	C$B29C
;
	LD	A,30H	; "0"
	OR	L
	POP	HL
	LD	(HL),A
	DEC	HL
	PUSH	HL
	JP	J.B1F4
;
;	-----------------
J$B210:	OR	30H	; "0"
	POP	HL
	LD	(HL),A
	EX	DE,HL
	POP	HL
	LD	A,L
	SUB	E
	LD	L,A
	LD	A,H
	SBC	A,D
	LD	H,A
	LD	A,L
	INC	A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B21F:	LD	A,H
	OR	L
	RET	Z
;
	PUSH	DE
	LD	D,01H	; 1 
J$B225:	LD	A,H
	RLCA	
	JP	C,J$B22F
;
	INC	D
	ADD	HL,HL
	JP	J$B225
;
;	-----------------
J$B22F:	LD	A,D
	POP	DE
	PUSH	AF
	ADD	A,10H	; 16 
J$B234:	PUSH	AF
	LD	A,B
	RLCA	
	JP	NC,J$B252
;
	LD	A,B
	CP	H
	JP	C,J.B25F
;
	JP	NZ,J.B247
;
	LD	A,C
	CP	L
	JP	C,J.B25F
;
J.B247:	LD	A,C
	SUB	L
	LD	C,A
	LD	A,B
	SBC	A,H
	LD	B,A
	RLCA	
	JP	C,J$B260
;
	SCF	
J$B252:	CALL	C.B28F
;
	POP	AF
	DEC	A
	JP	NZ,J$B234
;
	POP	AF
	OR	A
	JP	J$B26C
;
;	-----------------
J.B25F:	OR	A
J$B260:	CALL	C.B28F
;
	POP	AF
	DEC	A
	PUSH	AF
	JP	NZ,J.B247
;
	POP	AF
	POP	AF
	SCF	
J$B26C:	LD	H,B
	LD	L,C
	PUSH	DE
	LD	D,A
	LD	E,A
J$B271:	LD	A,H
	RRA	
	LD	H,A
	LD	A,L
	RRA	
	LD	L,A
	OR	A
	DEC	D
	JP	NZ,J$B271
;
	PUSH	HL
	LD	HL,X.0000
J$B280:	ADD	HL,HL
	INC	HL
	DEC	E
	JP	NZ,J$B280
;
	LD	A,B
	AND	H
	LD	B,A
	LD	A,C
	AND	L
	LD	C,A
	POP	HL
	POP	DE
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B28F:	LD	A,E
	RLA	
	LD	E,A
	LD	A,D
	RLA	
	LD	D,A
	LD	A,C
	RLA	
	LD	C,A
	LD	A,B
	RLA	
	LD	B,A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B29C:	PUSH	AF
	PUSH	BC
	OR	A
	JP	Z,J$B2D3
;
	LD	C,09H	; 9 
J$B2A4:	RLCA	
	JP	C,J$B2AC
;
	INC	C
	JP	J$B2A4
;
;	-----------------
J$B2AC:	RRCA	
	LD	B,A
	LD	A,C
	LD	C,00H
	LD	DE,X.0000
J$B2B4:	PUSH	AF
	LD	A,L
	SUB	C
	LD	L,A
	LD	A,H
	SBC	A,B
	LD	H,A
	JP	C,J$B2C4
;
	EX	DE,HL
	ADD	HL,HL
	INC	HL
	JP	J$B2C7
;
;	-----------------
J$B2C4:	ADD	HL,BC
	EX	DE,HL
	ADD	HL,HL
J$B2C7:	EX	DE,HL
	LD	A,B
	RRA	
	LD	B,A
	LD	A,C
	RRA	
	LD	C,A
	POP	AF
	DEC	A
	JP	NZ,J$B2B4
;
J$B2D3:	POP	BC
	POP	AF
	RET	
;
;	-----------------
?.B2D6:	LD	BC,X.0000
	LD	DE,X.0000
J$B2DC:	PUSH	AF
	PUSH	HL
	LD	H,B
	LD	L,C
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,BC
	ADD	HL,HL
	LD	B,H
	LD	C,L
	LD	H,D
	LD	L,E
	LD	A,09H	; 9 
J$B2EA:	ADD	HL,DE
	JP	NC,J$B2EF
;
	INC	BC
J$B2EF:	DEC	A
	JP	NZ,J$B2EA
;
	EX	DE,HL
	POP	HL
	LD	A,(HL)
	AND	0FH	; 15 
	INC	HL
	PUSH	HL
	LD	L,A
	LD	H,00H
	ADD	HL,DE
	JP	NC,J$B302
;
	INC	BC
J$B302:	EX	DE,HL
	POP	HL
	POP	AF
	DEC	A
	JP	NZ,J$B2DC
;
	RET	
;
;	-----------------
?.B30A:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,C.0008
	ADD	HL,BC
	LD	E,04H	; 4 
	LD	A,00H
J$B315:	CP	(HL)
	JP	NZ,J$B322
;
	INC	HL
	DEC	E
	JP	NZ,J$B315
;
	LD	A,01H	; 1 
	JR	J$B38A
;
;	-----------------
J$B322:	LD	HL,I.0004
	ADD	HL,BC
	LD	E,04H	; 4 
	LD	A,00H
J$B32A:	LD	(HL),A
	INC	HL
	DEC	E
	JP	NZ,J$B32A
;
	LD	HL,C.000C
	ADD	HL,BC
	LD	(HL),20H	; " "
J$B336:	LD	A,00H
	ADD	A,A
	LD	H,B
	LD	L,C
	LD	D,08H	; 8 
J$B33D:	LD	A,(HL)
	RLA	
	LD	(HL),A
	INC	HL
	DEC	D
	JP	NZ,J$B33D
;
	PUSH	BC
	LD	HL,I.0004
	ADD	HL,BC
	EX	DE,HL
	LD	HL,C.0008
	ADD	HL,BC
	LD	A,(DE)
	SUB	(HL)
	LD	(DE),A
	LD	C,03H	; 3 
J$B354:	INC	DE
	INC	HL
	LD	A,(DE)
	SBC	A,(HL)
	LD	(DE),A
	DEC	C
	JP	NZ,J$B354
;
	POP	BC
	JP	NC,J$B37D
;
	LD	HL,I.0004
	ADD	HL,BC
	EX	DE,HL
	LD	HL,C.0008
	ADD	HL,BC
	PUSH	BC
	LD	A,(DE)
	ADD	A,(HL)
	LD	(DE),A
	LD	C,03H	; 3 
J$B370:	INC	DE
	INC	HL
	LD	A,(DE)
	ADC	A,(HL)
	LD	(DE),A
	DEC	C
	JP	NZ,J$B370
;
	POP	BC
	JP	J$B380
;
;	-----------------
J$B37D:	LD	A,(BC)
	INC	A
	LD	(BC),A
J$B380:	LD	HL,C.000C
	ADD	HL,BC
	DEC	(HL)
	JP	NZ,J$B336
;
	LD	A,00H
J$B38A:	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
?.B38E:	LD	A,D
	CP	H
	JR	C,J$B393
;
	EX	DE,HL
J$B393:	XOR	A
	OR	D
	SCF	
	RET	NZ
;
	PUSH	BC
	LD	A,E
	LD	B,H
	LD	C,L
	LD	HL,X.0000
	LD	DE,C.0008
J$B3A1:	ADD	HL,HL
	RLCA	
	JR	NC,J$B3A6
;
	ADD	HL,BC
J$B3A6:	ADC	A,D
	DEC	E
	JR	NZ,J$B3A1
;
	POP	BC
	OR	A
	RET	Z
;
	SCF	
	RET	
;
;	-----------------
?.B3AF:	LD	A,D
	OR	E
	SCF	
	RET	Z
;
	PUSH	BC
	LD	A,D
	CPL	
	LD	B,A
	LD	A,E
	CPL	
	LD	C,A
	INC	BC
	EX	DE,HL
	LD	HL,X.0000
	LD	A,10H	; 16 
J$B3C1:	ADD	HL,HL
	EX	DE,HL
	ADD	HL,HL
	EX	DE,HL
	JR	NC,J$B3C8
;
	INC	HL
J$B3C8:	PUSH	HL
	ADD	HL,BC
	JR	NC,J$B3CE
;
	EX	(SP),HL
	INC	DE
J$B3CE:	POP	HL
	DEC	A
	JR	NZ,J$B3C1
;
	POP	BC
	OR	A
	RET	
;
;	-----------------
J$B3D5:	PUSH	DE
	PUSH	HL
	PUSH	IY
	LD	A,(D$C3DA)
	AND	A
	JR	Z,J.B423
;
	LD	A,(D.C996)
	AND	A
	JR	Z,J$B3EF
;
	DEC	A
	LD	(D.C996),A
	LD	A,(D.C997)
	LD	D,A
	JR	J$B3F4
;
;	-----------------
J$B3EF:	LD	A,(D.C997)
	INC	A
	LD	D,A
J$B3F4:	LD	A,(D.C3DC)
	LD	B,A
	LD	A,(D.C3DD)
	ADD	A,B
	AND	A
	JR	Z,J.B423
;
	LD	A,D
I$B400:	AND	A
I$B401:	JR	Z,J.B423
;
	LD	B,A
	LD	A,C
	AND	A
	JR	Z,J$B40A
;
	SLA	B
J$B40A:	LD	A,(D.C3DC)
	LD	C,A
	LD	A,(D.C3DD)
	ADD	A,C
J$B412:	DEC	A
	JR	Z,J$B417
;
	DJNZ	J$B412
;
J$B417:	LD	C,A
	SRL	A
	LD	(D.C3DD),A
	LD	B,A
	LD	A,C
	SUB	B
	LD	(D.C3DC),A
J.B423:	POP	IY
	POP	HL
	POP	DE
	RET	
;
;	-----------------
J$B428:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C$B94F
;
	AND	A
	JR	Z,J.B461
;
	LD	A,(D.C3DB)
	AND	A
	JR	NZ,J.B461
;
	LD	A,(D.CC3D)
	CP	05H	; 5 
	JR	Z,J$B45D
;
	LD	A,C
	CP	03H	; 3 
	JR	NZ,J$B454
;
	CALL	C.B46E
;
	AND	A
	JR	Z,J$B45A
;
	LD	A,01H	; 1 
	LD	(D.C3DB),A
	JR	J.B465
;
;	-----------------
J$B454:	CALL	C.B46E
;
	AND	A
	JR	NZ,J.B465
;
J$B45A:	CALL	C$B4D8
;
J$B45D:	LD	A,01H	; 1 
	JR	J$B466
;
;	-----------------
J.B461:	XOR	A
	LD	(D.C3DB),A
J.B465:	XOR	A
J$B466:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B46E:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.BCF6			; select RAM on page 1
;
	LD	B,C
	LD	A,C
	CP	03H	; 3 
	LD	A,(D$C332)
	JR	NZ,J$B482
;
	DEC	A
J$B482:	LD	C,A
	LD	IX,(D$C3CF)
J$B487:	LD	DE,(D.C403)
	PUSH	IX
	POP	HL
	XOR	A
	SBC	HL,DE
	JR	Z,J.B4A0
;
	LD	A,C
	CP	(IX+2)
	JR	Z,J.B4CB
;
	LD	DE,BDOS
	ADD	IX,DE
	JR	J$B487
;
;	-----------------
J.B4A0:	LD	IX,(D.C403)
J$B4A4:	LD	DE,(D$C407)
	PUSH	IX
	POP	HL
	XOR	A
	SBC	HL,DE
	JR	Z,J$B4C4
;
	LD	A,C
	CP	(IX+2)
	JR	C,J$B4BD
;
	CP	(IX+4)
	JR	Z,J.B4CB
;
	JR	C,J.B4CB
;
J$B4BD:	LD	DE,BDOS
	ADD	IX,DE
	JR	J$B4A4
;
;	-----------------
J$B4C4:	INC	C
	DEC	B
	JR	NZ,J.B4A0
;
	XOR	A
	JR	J$B4CD
;
;	-----------------
J.B4CB:	LD	A,01H	; 1 
J$B4CD:	CALL	C.BD49			; restore slot on page 1
;
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B4D8:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	XOR	A
	LD	(D.C997),A
	LD	(D.C996),A
	LD	A,(D$C31A)
	LD	B,A
	LD	A,(D$C3E3)
	ADD	A,B
	LD	B,A
	LD	A,(D$C998)
	CP	B
	JR	C,J$B4FF
;
	SUB	B
	LD	(D.C996),A
	XOR	A
	LD	(D.C997),A
	JR	J$B516
;
;	-----------------
J$B4FF:	LD	C,A
	LD	A,B
J$B501:	SUB	C
	JR	C,J$B50F
;
	PUSH	AF
	LD	A,(D.C997)
	INC	A
	LD	(D.C997),A
	POP	AF
	JR	J$B501
;
;	-----------------
J$B50F:	ADD	A,C
	LD	B,A
	LD	A,C
	SUB	B
	LD	(D.C996),A
J$B516:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET	
;
;	-----------------
I$B51E:	CALL	C,C$CCB0
;
	RST	18H
;
	IN	A,(0BFH)
	CALL	Z,C$D6C4
;
	OR	E
	RET	
;
;	-----------------
?.B529:	CALL	C,C$B8B0
;
	OR	H
	RET	C
;
	OR	C
	OR	(HL)
	SBC	A,0C0H
	RET	C
;
	RST	08H
;
	CP	(HL)
	LD	IX,I$B0DC
I.B537	EQU	$-2
	CALL	Z,C$DBDF
;
	CP	A
	CALL	Z,C$CAC4
;
	LD	C,L
	LD	D,E
	LD	E,B
	LD	(D$BDBC),A
	JP	J$C3D1
;
;	-----------------
?.B549:	SBC	A,0BAH
	SBC	A,0BCH
	SUB	0B3H
	CP	B
	RET	NZ
;
	SBC	A,0BBH
	OR	D
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B554:	CALL	C.B5C4			; select ROM BIOS on page 0
	CALL	C.B586			; select screen mode 1
	LD	HL,3*256+11
	CALL	POSIT
	LD	HL,I$B51E
	LD	DE,I.B537
	CALL	C.B5A6			; text to screen
	CALL	C.B686			; restore slot on page 0
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B56D:	CALL	C.B5C4			; select ROM BIOS on page 0
	CALL	C.B586			; select screen mode 1
	LD	HL,1*256+11
	CALL	POSIT
	LD	HL,I.B537
	LD	DE,C.B554
	CALL	C.B5A6			; text to screen
	CALL	C.B686			; restore slot on page 0
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.B586:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	LD	A,1			; screen mode = 1
	LD	IX,CHGMDP
	CALL	EXTROM			; change screen mode
	CALL	CLS
	CALL	TOTEXT
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.B5A6:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
J$B5AE:	LD	A,(HL)
	CALL	C$00A2
;
	INC	HL
	AND	A
	SBC	HL,DE
	JR	NC,J$B5BB
	ADD	HL,DE
	JR	J$B5AE

J$B5BB:	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B5C4:	DI	
	CALL	C.B673			; disable H.KEYI handler
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	A,(D.FCC1)
	LD	E,A
	RRCA	
	RRCA	
	AND	0C0H
	LD	D,A
	LD	A,B
	AND	3FH	; "?"
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	D,A
	LD	A,E
	RRCA	
	RRCA	
	AND	03H	; 3 
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,E
	AND	03H	; 3 
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+11)
	LD	(IX+9),A
	LD	A,(IX+10)
	LD	(IX+8),A
	LD	(IX+11),B
	LD	(IX+10),C
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B61C:	DI	
	CALL	C.B673			; disable H.KEYI handler
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	A,(D.FCC1)
	LD	E,A
	RRCA	
	RRCA	
	AND	0C0H
	LD	D,A
	LD	A,B
	AND	3FH	; "?"
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	D,A
	LD	A,E
	RRCA	
	RRCA	
	AND	03H	; 3 
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,E
	AND	03H	; 3 
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+11)
	LD	(IX+9),A
	LD	A,(IX+10)
	LD	(IX+8),A
	LD	(IX+11),B
	LD	(IX+10),C
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.B673:	PUSH	AF
	PUSH	BC
	LD	A,(H.KEYI+0)
	LD	(D.CE6C),A
	LD	A,0C9H
	LD	(H.KEYI+0),A
	CALL	C$B6D4
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B686:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.FCC1)
	RRCA	
	RRCA	
	AND	0C0H
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(D.CE6C)
	LD	(H.KEYI+0),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B6D4:	PUSH	AF
	PUSH	BC
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,02H	; 2 
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	CALL	C$B701
;
	LD	A,(D.D49F)
	INC	A
	LD	C,A
J$B6EB:	IN	A,(C)
	AND	01H	; 1 
	JR	NZ,J$B6EB
;
	LD	A,(D.D4A0)
	INC	A
	LD	C,A
	LD	A,00H
	OUT	(C),A
	LD	A,8FH
	OUT	(C),A
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B701:	NOP	
	RET	
;
;	-----------------
J$B703:	PUSH	IX
	PUSH	IY
	CALL	C.82CC			; quit
	POP	IY
	POP	IX
	CALL	C.B5C4			; select ROM BIOS on page 0
	CALL	C$001C
	DI	
	CALL	C$B724
	LD	A,0
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	JP	J$B96F
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B724:	DI	
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	30H	; "0"
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,C
	AND	30H	; "0"
	RRCA	
	RRCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,B
	AND	30H	; "0"
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B751:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	X.0000
	CALL	C.B9F2			; restore slot and segment in page 0
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B75E:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	C.004A
	CALL	C.B9F2			; restore slot and segment in page 0
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B76B:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	CPMADR
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$B778:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	C.0059
	CALL	C.B9F2			; restore slot and segment in page 0
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B785:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	FCB1
	CALL	C.B9F2			; restore slot and segment in page 0
	RET	
;
;	-----------------
?.B792:	CALL	C.BB17			; select firmware on page 1
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	C$0044
	CALL	C.B9F2			; restore slot and segment in page 0
	CALL	C.BB71			; restore slot in page 1
	RET	
;
;	-----------------
?.B7A5:	CALL	C.BB17			; select firmware on page 1
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	C$0047
	CALL	C.B9F2			; restore slot and segment in page 0
	CALL	C.BB71			; restore slot in page 1
	RET	
;
;	-----------------
?.B7B8:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.004A
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B7CB:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
	CALL	C.BC5A			; select RAM on page 1
	CALL	C$004D
	CALL	C.BCAE			; restore slot on page 1
	CALL	C.B9F2			; restore slot and segment in page 0
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B7E4:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.BC5A			; select RAM on page 1
;
	CALL	C$0050
;
	CALL	C.BCAE			; restore slot on page 1
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B7FD:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.0053
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B810:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$0056
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B823:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.0059
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B836:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	FCB1
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B849:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.005F
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B85C:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$0062
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B86F:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$0065
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B882:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$003B
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B895:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$003E
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B8A8:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
C$B8B0	EQU	$-1
;
	CALL	C$0041
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B8BB:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$009B
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B8CE:	EX	AF,AF'
	LD	A,1CH
	CALL	C.BA4B			; select firmware slot and segment in page 1
	CALL	C$4039
	CALL	C.BABE			; restore slot and segment in page 1
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B8DB:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$009E
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
?.B8EE:	EX	AF,AF'
	LD	A,06H	; 6 
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$00B6
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	RET	
;
;	-----------------
?.B8FB:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$0083
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	RET	
;
;	-----------------
?.B908:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.001B
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	RET	
;
;	-----------------
?.B915:	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C.005F
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	RET	
;
;	-----------------
?.B922:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,02H	; 2 
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$0098
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.B935:	EX	AF,AF'
	LD	A,08H	; 8 
	CALL	C.BA4B			; select firmware slot and segment in page 1
;
	CALL	C$405A
;
	CALL	C.BABE			; restore slot and segment in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B942:	EX	AF,AF'
	LD	A,1CH
	CALL	C.BA4B			; select firmware slot and segment in page 1
;
	CALL	C$405D
;
	CALL	C.BABE			; restore slot and segment in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B94F:	EX	AF,AF'
	LD	A,14H	; 20 
	CALL	C.BA4B			; select firmware slot and segment in page 1
;
	CALL	C$4018
;
	CALL	C.BABE			; restore slot and segment in page 1
;
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B95C:	CALL	C.BB17			; select firmware on page 1
;
	EX	AF,AF'
	LD	A,16H
	CALL	C.B97F			; select firmware slot and segment in page 0
;
	CALL	C$00AA
;
	CALL	C.B9F2			; restore slot and segment in page 0
;
	CALL	C.BB71			; restore slot in page 1
;
	RET	
;
;	-----------------
J$B96F:	JP	J$4043
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$B972:	EX	AF,AF'
	LD	A,20
	CALL	C.BA4B			; select firmware slot and segment in page 1
	CALL	C$4024
	CALL	C.BABE			; restore slot and segment in page 1
	RET	

;	  Subroutine select firmware slot and segment in page 0
;	     Inputs  ________________________
;	     Outputs ________________________

C.B97F:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	PUSH	AF			; store segment
	IN	A,(0A8H)
	LD	B,A
	AND	3FH
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	E,A
	LD	A,H
	AND	0CH
	RRCA	
	RRCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,H
	AND	03H
	OR	D
	OUT	(0A8H),A		; select slot in page 0
	LD	A,(IX+15)
	LD	(IX+11),A
	LD	A,(IX+14)
	LD	(IX+10),A
	LD	(IX+15),B
	LD	(IX+14),C
	POP	AF			; restore segment
	LD	C,A
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D$7FF0)
	LD	B,A			; store segment page 0
	LD	A,C
	LD	(D.6000),A
	INC	A
	LD	(D.6400),A		; select segment page 0
	LD	(IX+13),B
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$B9EA
	EI	
J$B9EA:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.B9F2:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	A,(IX+11)
	LD	(D.6000),A
	INC	A
	LD	(D.6400),A		; select segment page 0
	LD	B,(IX+13)
	LD	C,(IX+12)
	IN	A,(0A8H)
	AND	3FH
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A		; select slot
	LD	A,(IX+9)
	LD	(IX+13),A
	LD	A,(IX+8)
	LD	(IX+12),A
	LD	A,(IX+7)
	LD	(IX+11),A
	LD	A,(IX+6)
	LD	(IX+10),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$BA43
	EI	
J$BA43:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	POP	AF
	RET	

;	  Subroutine select firmware slot and segment in page 1
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BA4B:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	PUSH	AF
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A		; select slot in page 1
	LD	A,(IX+15)
	LD	(IX+11),A
	LD	A,(IX+14)
	LD	(IX+10),A
	LD	(IX+15),B
	LD	(IX+14),C
	POP	AF
	LD	C,A
	LD	A,4
	LD	(D.7FF9),A		; segments registers readable
	LD	A,(D$7FF2)
	LD	B,A			; store segment page 1
	LD	A,C
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	LD	(IX+13),B
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$BAB6
	EI	
J$BAB6:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BABE:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	A,(IX+11)
	LD	(D.6800),A
	INC	A
	LD	(D.6C00),A		; select segments page 1
	LD	B,(IX+13)
	LD	C,(IX+12)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A		; select slot
	LD	A,(IX+9)
	LD	(IX+13),A
	LD	A,(IX+8)
	LD	(IX+12),A
	LD	A,(IX+7)
	LD	(IX+11),A
	LD	A,(IX+6)
	LD	(IX+10),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$BB0F
;
	EI	
J$BB0F:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	POP	AF
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.BB17:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)
	LD	H,A			; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A		; select slot in page 1
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$BB6A
	EI	
J$BB6A:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.BB71:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D468)		; slot id firmware
	AND	03H
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A		; select slot
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	LD	A,(D.D498)
	OR	A
	JR	NZ,J$BBB8
	EI	
J$BBB8:	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BBBF:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D469)
	LD	H,A			; slot id RAM page 0
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0FCH
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	RRCA	
	RRCA	
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0FCH
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BC12:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D469)		; slot id RAM page 0
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine select RAM on page 1
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BC5A:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46A)
	LD	H,A			; slot id RAM page 1
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BCAE:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46A)		; slot id RAM page 1
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	EI	
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BCF6:	DI	
	PUSH	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46A)
	LD	H,A			; slot id RAM page 1
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL	
	LD	C,A
	AND	0F3H
	LD	E,A
	LD	A,H
	AND	0CH	; 12 
	OR	E
	LD	(D.FFFF),A
	LD	A,B
	AND	0F3H
	LD	D,A
	LD	A,H
	AND	03H	; 3 
	RLCA	
	RLCA	
	OR	D
	OUT	(0A8H),A
	LD	A,(IX+13)
	LD	(IX+11),A
	LD	A,(IX+12)
	LD	(IX+10),A
	LD	(IX+13),B
	LD	(IX+12),C
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.BD49:	DI	
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	IX
	LD	IX,0
	ADD	IX,SP
	LD	B,(IX+11)
	LD	C,(IX+10)
	IN	A,(0A8H)
	AND	3FH	; "?"
	LD	D,A
	LD	A,(D.D46A)		; slot id RAM page 1
	AND	03H	; 3 
	RRCA	
	RRCA	
	OR	D
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,(IX+9)
	LD	(IX+11),A
	LD	A,(IX+8)
	LD	(IX+10),A
	LD	A,(IX+7)
	LD	(IX+9),A
	LD	A,(IX+6)
	LD	(IX+8),A
	POP	IX
	POP	DE
	POP	BC
	POP	AF
	POP	AF
	RET	
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$BD90:	PUSH	AF
	PUSH	BC
	PUSH	HL
	LD	A,81H
	LD	(D.6800),A		; select SRAM in page 1
	LD	HL,D.4000
	LD	BC,I$1400
J$BD9E:	LD	A,(HL)
	OR	A
	JR	Z,J.BDA8
	CP	0FFH
	JR	Z,J.BDA8
	JR	J$BDB3
;
;	-----------------
J.BDA8:	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$BD9E
	LD	A,3FH
	LD	(D.4000),A
J$BDB3:	LD	A,00H
	LD	(D.6800),A		; select segment in page 1
	POP	HL
	POP	BC
	POP	AF
	RET	
;
;	-----------------
D$BDBC:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
I$BF41:	RST	38H
I$BF42:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
D.BF48:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
D.BF51:	RST	38H
D.BF52:	RST	38H
D$BF53:	RST	38H
D$BF54:	RST	38H
D$BF55:	RST	38H
D$BF56:	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	END
