; Diskdriver NOVAXIS for HSH/MAK SCSI controller
; HDC	WD33C93A

; Source re-created by Z80DIS 2.2
; Z80DIS was written by Kenneth Gielow, Palo Alto, CA

; Code Copyrighted by ? and maybe others
; Source comments by Arjen Zeilemaker

; Sourcecode supplied for STUDY ONLY
; Recreation NOT permitted without authorisation of the copyrightholders

	.Z80
	ORG	4000H
I.0000	EQU	0000H	; ----I
I$0002	EQU	0002H	; ----I
I$0003	EQU	0003H	; ----I
I.0004	EQU	0004H	; ----I
CPMADR	EQU	0006H	; ----I
D.0007	EQU	0007H	; ---LI
C.0008	EQU	0008H	; -C--I
I$0009	EQU	0009H	; ----I
I.000C	EQU	000CH	; ----I
I$000D	EQU	000DH	; ----I
C.0010	EQU	0010H	; -C--I
I.0013	EQU	0013H	; ----I
I$0014	EQU	0014H	; ----I
I$0015	EQU	0015H	; ----I
C.0018	EQU	0018H	; JC---
I$0019	EQU	0019H	; ----I
CALSLT	EQU	001CH
X.0020	EQU	0020H	; -C-L-
ENASLT	EQU	0024H
D.002D	EQU	002DH	; ---L-
I$002F	EQU	002FH	; ----I
I.0030	EQU	0030H	; ----I
I$0034	EQU	0034H	; ----I
C.0038	EQU	0038H	; -C--I
I.0040	EQU	0040H	; ----I
C.0047	EQU	0047H	; -C---
C$005F	EQU	005FH	; -C---
DBUF	EQU	0080H	; ----I
C.009F	EQU	009FH	; -C---
C$00A2	EQU	00A2H	; -C---
C.00C6	EQU	00C6H	; -C---
I$00FE	EQU	00FEH	; ----I
I.0100	EQU	0100H	; ----I
I$0102	EQU	0102H	; ----I
I$0116	EQU	0116H	; ----I
C.0141	EQU	0141H	; -C---
C.0159	EQU	0159H	; -C---
C.0171	EQU	0171H	; -C---
X.0180	EQU	0180H	; -C-LI
I$0183	EQU	0183H	; ----I
I$01E7	EQU	01E7H	; ----I
I.0200	EQU	0200H	; ----I
I.0206	EQU	0206H	; ----I
I$021E	EQU	021EH	; ----I
I$0230	EQU	0230H	; ----I
I$0280	EQU	0280H	; ----I
I.0302	EQU	0302H	; ----I
D$03FF	EQU	03FFH	; ---L-
I$0400	EQU	0400H	; ----I
I.0402	EQU	0402H	; ----I
I.0403	EQU	0403H	; ----I
I$0502	EQU	0502H	; ----I
I$0503	EQU	0503H	; ----I
I$051E	EQU	051EH	; ----I
I$0700	EQU	0700H	; ----I
I$0800	EQU	0800H	; ----I
I$08B2	EQU	08B2H	; ----I
D$0A0D	EQU	0A0DH	; ---L-
I$0C35	EQU	0C35H	; ----I
I$0D18	EQU	0D18H	; ----I
I$0D1E	EQU	0D1EH	; ----I
I.1000	EQU	1000H	; ----I
I.10FE	EQU	10FEH	; ----I
I$1266	EQU	1266H	; ----I
I$1300	EQU	1300H	; ----I
I$140E	EQU	140EH	; ----I
I$1F00	EQU	1F00H	; ----I
I.2009	EQU	2009H	; ----I
I$200A	EQU	200AH	; ----I
I$200B	EQU	200BH	; ----I
D.2020	EQU	2020H	; --SL-
D.2BFF	EQU	2BFFH	; ---L-
D.2D20	EQU	2D20H	; --S-I
D$3020	EQU	3020H	; ---L-
I.3939	EQU	3939H	; ----I
I.3FFC	EQU	3FFCH	; ----I
D.8000	EQU	8000H	; --SLI
D.8002	EQU	8002H	; --SL-
I$8004	EQU	8004H	; ----I
D.81FC	EQU	81FCH	; --SL-
D.81FD	EQU	81FDH	; --SL-
I.8200	EQU	8200H	; ----I
I$8201	EQU	8201H	; ----I
D.8207	EQU	8207H	; --SL-
D.8209	EQU	8209H	; --S--
D.83F0	EQU	83F0H	; --SL-
D.83F1	EQU	83F1H	; --SL-
I.83F2	EQU	83F2H	; ----I
D.83FA	EQU	83FAH	; --SL-
D.83FB	EQU	83FBH	; --SL-
D.83FD	EQU	83FDH	; --SL-
D.83FE	EQU	83FEH	; --SL-
D.83FF	EQU	83FFH	; --SL-
I.8400	EQU	8400H	; ----I
I.859E	EQU	859EH	; ----I
D$85A0	EQU	85A0H	; ---L-
D$85A2	EQU	85A2H	; ---L-
I.85BE	EQU	85BEH	; ----I
D.85D2	EQU	85D2H	; ---L-
D$85F3	EQU	85F3H	; ---L-
D$85F4	EQU	85F4H	; ---L-
I$85F6	EQU	85F6H	; ----I
D.85FE	EQU	85FEH	; ---LI
I$8600	EQU	8600H	; ----I
I.8700	EQU	8700H	; ----I
I$8708	EQU	8708H	; ----I
I.8800	EQU	8800H	; ----I
I$A40C	EQU	0A40CH	; ----I
I$AA55	EQU	0AA55H	; ----I
I$B059	EQU	0B059H	; ----I
I$B7FB	EQU	0B7FBH	; ----I
I.C000	EQU	0C000H	; ----I
I$C001	EQU	0C001H	; ----I
I$C9A8	EQU	0C9A8H	; ----I
J$CD4F	EQU	0CD4FH	; J----
I$F00D	EQU	0F00DH	; ----I
I$F1C9	EQU	0F1C9H	; ----I
I$F24F	EQU	0F24FH	; ----I
D$F30D	EQU	0F30DH	; ---L-
D.F33F	EQU	0F33FH	; --SL-
D$F342	EQU	0F342H	; ---L-
D.F34D	EQU	0F34DH	; --SL-
I$F355	EQU	0F355H	; ----I
D$F365	EQU	0F365H	; --S--
D$F366	EQU	0F366H	; --S--
C$F368	EQU	0F368H	; -C---
C$F398	EQU	0F398H	; -C---
D$F3AE	EQU	0F3AEH	; --S--
D.F3DC	EQU	0F3DCH	; --SL-
D.F3DD	EQU	0F3DDH	; --S--
I.F55E	EQU	0F55EH	; ----I
D.F663	EQU	0F663H	; --SLI
D.F672	EQU	0F672H	; --SL-
D.F674	EQU	0F674H	; --SL-
I$F698	EQU	0F698H	; ----I
D$F699	EQU	0F699H	; --S--
D.F6A0	EQU	0F6A0H	; --SL-
D.F6AB	EQU	0F6ABH	; --SL-
D$F6B1	EQU	0F6B1H	; --S--
I$F7F6	EQU	0F7F6H	; ----I
D.F7F8	EQU	0F7F8H	; --S-I
D.F7F9	EQU	0F7F9H	; --S--
D$F860	EQU	0F860H	; --S--
D.F862	EQU	0F862H	; --SL-
D.F92C	EQU	0F92CH	; --SL-
I$FB20	EQU	0FB20H	; ----I
I.FB21	EQU	0FB21H	; ----I
D.FBEB	EQU	0FBEBH	; ---L-
D.FBED	EQU	0FBEDH	; ---L-
D.FC48	EQU	0FC48H	; --SL-
D.FC4A	EQU	0FC4AH	; --SL-
D.FCC0	EQU	0FCC0H	; ---L-
I$FCC1	EQU	0FCC1H	; ----I
I$FD09	EQU	0FD09H	; ----I
I$FD89	EQU	0FD89H	; ----I
D.FD99	EQU	0FD99H	; ---LI
I$FDEA	EQU	0FDEAH	; ----I
I.FE00	EQU	0FE00H	; ----I
I$FE49	EQU	0FE49H	; ----I
I$FFCA	EQU	0FFCAH	; ----I
I.FFFF	EQU	0FFFFH	; ----I
I.4000:	DEFB    "AB"
        DEFW    C.456E
        DEFW    C.5BBD
        DEFW    0
        DEFW    0
        DEFS    6,0

	JP	J$4D3B			; DSKIO entrypoint
?.4013:	JP	J$4E4F                  ; DSKCHG entrypoint
?.4016:	JP	C.4E7E                  ; GETDPB entrypoint
?.4019:	JP	J$4F5B                  ; CHOICE entrypoint
?.401C:	JP	J$4F9D                  ; DSKFMT entrypoint
?.401F:	JP	J.4FDA                  ; MTOFF entrypoint
?.4022:	JP	J.46BE
?.4025:	NOP
	JP	J.46BE
?.4029:	JP	J.46BE
?.402C:	NOP
	JP	C.4030			; GETSLT entrypoint

;	  Subroutine GETSLT
;	     Inputs  ________________________
;	     Outputs ________________________

C.4030:	CALL	C.4064
	OR	(HL)
	RET	P
	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	0CH
	OR	C
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.403F:	CALL	C.404A
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.404A:	CALL	C.4064
	ADD	A,A
	ADD	A,A
	ADD	A,A
	SCF
	ADC	A,A
	LD	C,A
	LD	A,(HL)
	ADD	A,A
	SBC	A,A
	AND	0CH	; 12 
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	AND	(HL)
	OR	C
	ADD	A,A
	LD	HL,I$FD09
	JR	J$4070

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4064:	IN	A,(0A8H)
	NOP
	RRCA
	RRCA
	AND	03H	; 3 
	LD	HL,I$FCC1
	LD	B,00H
I$406F	EQU	$-1
J$4070:	LD	C,A
	ADD	HL,BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4073:	LD	A,(HL)
	EX	(SP),HL
	CP	(HL)
	INC	HL
	EX	(SP),HL
	JR	NZ,J.408C
	LD	IX,I$4666
	CALL	C.0159
	EI
	RET

?.4083:	LD	E,13H	; 19 
	LD	BC,I$0D1E
J.4086	EQU	$-2
	LD	BC,I$051E
J.4089	EQU	$-2
	LD	BC,I$021E
J.408C	EQU	$-2
J$408E:	LD	IX,I$406F
	JR	J.40B6

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4094:	LD	IX,I$6627
	JR	J.40B6

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.409A:	LD	IX,I$5EA4
	JR	J.40B6

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$40A0:	LD	IX,I$517A
	JR	J.40B6

?.40A6:	LD	IX,I$4C64
	JR	J.40B6

?.40AC:	LD	IX,I$67D0
	JR	J.40B6

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.40B2:	LD	IX,I$521C
J.40B6:	CALL	C.0159
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.40BB:	PUSH	HL
	LD	HL,D.F663
	LD	A,(HL)
	LD	C,A
	LD	(HL),02H	; 2 
	LD	HL,D.F7F8
	CP	02H	; 2 
	JR	Z,J$40DB
	CP	04H	; 4 
	JR	Z,J$40D3
	CP	08H	; 8 
	JP	NZ,J.4086
J$40D3:	PUSH	BC
	CALL	C$40A0
	POP	BC
	LD	HL,I$F7F6
J$40DB:	LD	B,00H
	POP	DE
	LDIR
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.40E1:	PUSH	HL
	PUSH	AF
	CALL	C$4094
	LD	DE,(D$F699)
	LD	HL,I.F55E
	POP	AF
	AND	A
	JR	Z,J$40F6
	LD	C,A
	LD	B,00H
	LDIR
J$40F6:	POP	DE
	LD	HL,I$F698
	LD	BC,I$0003
	LDIR
	RET

;	  Subroutine CALL SLOW
;	     Inputs  ________________________
;	     Outputs ________________________

J.4100:	LD	A,80H
	JR	J.410A

;	  Subroutine CALL MEDIUM
;	     Inputs  ________________________
;	     Outputs ________________________

J.4104:	LD	A,81H
	JR	J.410A

;	  Subroutine CALL FAST
;	     Inputs  ________________________
;	     Outputs ________________________

J.4108:	LD	A,82H
J.410A:	PUSH	AF
	LD	A,(X.0180)
	CP	0C3H
	JR	Z,J$4115
	POP	AF
	AND	A
	RET

J$4115:	POP	AF
	PUSH	IX
	PUSH	IY
	CALL	X.0180
	POP	IY
	POP	IX
	AND	A
	RET

;	  Subroutine CALL MAP
;	     Inputs  ________________________
;	     Outputs ________________________

?.4123:	DI
	PUSH	HL
	LD	HL,I.C000
	LD	BC,I.3FFC
J.412B:	LD	A,3AH	; ":"
	CPIR
	JR	NZ,J.414E
	INC	HL
	LD	A,(HL)
	CP	0F2H
	JR	NZ,J.412B
	DEC	HL
	LD	A,(HL)
	CP	0C8H
	JR	C,J.412B
	CP	0CBH
	JR	NC,J.412B
	DEC	HL
	LD	(HL),0DBH
	INC	HL
	LD	A,(HL)
	ADD	A,35H	; "5"
	LD	(HL),A
	INC	HL
	LD	(HL),00H
	JR	J.412B

J.414E:	AND	A
	POP	HL
	EI
	RET

;	  Subroutine CALL MAP2
;	     Inputs  ________________________
;	     Outputs ________________________

J.4152:	DI
	PUSH	HL
	LD	HL,I.C000
	LD	BC,I.3FFC
J.415A:	LD	A,3AH	; ":"
	CPIR
	JR	NZ,J.414E
	INC	HL
	LD	A,(HL)
	CP	0F2H
	JR	NZ,J.415A
	DEC	HL
	LD	A,(HL)
	CP	0C7H
	JR	C,J.415A
	CP	0CBH
	JR	NC,J.415A
	DEC	HL
	LD	(HL),0DBH
	INC	HL
	LD	A,(HL)
	ADD	A,35H	; "5"
	LD	(HL),A
	INC	HL
	LD	(HL),00H
	JR	J.415A

;	  Subroutine CALL INFO
;	     Inputs  ________________________
;	     Outputs ________________________

J.417D:	PUSH	HL
	CALL	C.46BF
	LD	B,C
	HALT

?.4183:	LD	H,C
	LD	L,C
	LD	L,H
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	JR	NZ,J$41EF
	LD	H,C
	LD	L,H
	LD	L,H
	JR	NZ,J$4204
	LD	(HL),H
	LD	H,C
	LD	(HL),H
	LD	H,L
	LD	L,L
	LD	H,L
	LD	L,(HL)
	LD	(HL),H
	LD	(HL),E
	LD	A,(D$0A0D)
	DEC	C
	LD	A,(BC)
	LD	H,E
	LD	H,C
	LD	L,H
	LD	L,H
	JR	NZ,J$41EE
	LD	C,(HL)
	LD	B,(HL)
	LD	C,A
	JR	NZ,J$41CA
	JR	NZ,J$41CC
	JR	NZ,J$41CE
	JR	NZ,J$41D0
	JR	NZ,J$41D2
	JR	NZ,J$41D4
	JR	NZ,J$41D6
	JR	NZ,J$41D8
	JR	NZ,J$41DA
	JR	NZ,J$41DC
	JR	NZ,J$4211
	LD	L,B
	LD	L,A
	LD	(HL),A
	LD	(HL),E
	JR	NZ,J$4238
	LD	L,B
	LD	L,C
	LD	(HL),E
	JR	NZ,J$423D
	LD	H,L
J$41CA:	LD	A,B
	LD	(HL),H
J$41CC:	DEC	C
	LD	A,(BC)
J$41CE:	LD	H,E
	LD	H,C
J$41D0:	LD	L,H
	LD	L,H
J$41D2:	JR	NZ,J$4227
J$41D4:	LD	C,H
	LD	C,A
J$41D6:	LD	D,A
	JR	NZ,J$41F9
J$41D8	EQU	$-1
	JR	NZ,J$41FB
J$41DA	EQU	$-1
	JR	NZ,J$41FD
J$41DC	EQU	$-1
	JR	NZ,J$41FF
	JR	NZ,J$4201
	JR	NZ,J$4203
	JR	NZ,J$4205
	JR	NZ,J$4207
	JR	NZ,J$4209
	JR	NZ,J$420B
	JR	NZ,J$4247
	JR	C,J$421F
J$41EE	EQU	$-1
J$41EF:	JR	NZ,J.425E
	LD	L,A
	LD	H,H
	LD	H,L
	LD	L,0DH	; 13 
	LD	A,(BC)
	LD	H,E
	LD	H,C
J$41F9:	LD	L,H
	LD	L,H
J$41FB:	JR	NZ,J$424A
J$41FD:	LD	B,L
	LD	B,H
J$41FF:	LD	C,C
	LD	D,L
J$4201:	LD	C,L
	JR	NZ,J$4224
J$4203	EQU	$-1
J$4204:	JR	NZ,J$4226
J$4205	EQU	$-1
	JR	NZ,J$4228
J$4207	EQU	$-1
	JR	NZ,J$422A
J$4209	EQU	$-1
	JR	NZ,J$422C
J$420B	EQU	$-1
	JR	NZ,J$422E
	JR	NZ,J$4230
	JR	NZ,J$4232
J$4211	EQU	$-1
	JR	NZ,J$4234
	JR	NZ,J.4268
	JR	C,J$4248
	JR	NC,J$423A
	LD	D,D
	LD	C,A
	LD	C,L
	JR	NZ,J$428C
J$421F:	LD	L,A
	LD	H,H
	LD	H,L
	LD	L,0DH	; 13 
J$4224:	LD	A,(BC)
	LD	H,E
J$4226:	LD	H,C
J$4227:	LD	L,H
J$4228:	LD	L,H
	JR	NZ,J$4271
J$422A	EQU	$-1
	LD	B,C
J$422C:	LD	D,E
	LD	D,H
J$422E:	JR	NZ,J$4250
J$4230:	JR	NZ,J$4252
J$4232:	JR	NZ,J$4254
J$4234:	JR	NZ,J$4256
	JR	NZ,J$4258
J$4238:	JR	NZ,J$425A
J$423A:	JR	NZ,J$425C
	JR	NZ,J.425E
J$423D	EQU	$-1
	JR	NZ,J$4260
	JR	NZ,J$4262
	JR	NZ,J$4296
	JR	C,J$4276
	JR	NC,J.4268
J$4247	EQU	$-1
J$4248:	LD	D,D
	LD	B,C
J$424A:	LD	C,L
	JR	NZ,J.42BA
	LD	L,A
	LD	H,H
	LD	H,L
J$4250:	LD	L,0DH	; 13 
J$4252:	LD	A,(BC)
	LD	H,E
J$4254:	LD	H,C
	LD	L,H
J$4256:	LD	L,H
	JR	NZ,J$42A6
J$4258	EQU	$-1
	LD	B,C
J$425A:	LD	D,B
	JR	NZ,J$427D
J$425C	EQU	$-1
	JR	NZ,J$427F
J.425E	EQU	$-1
	JR	NZ,J$4281
J$4260	EQU	$-1
	JR	NZ,J$4283
J$4262	EQU	$-1
	JR	NZ,J$4285
	JR	NZ,J$4287
	JR	NZ,J$4289
J.4268	EQU	$-1
	JR	NZ,J$428B
	JR	NZ,J$428D
	JR	NZ,J$428F
	JR	NZ,J$4291
J$4271:	LD	B,(HL)
	LD	L,C
	LD	A,B
	JR	NZ,J.42BA
J$4276:	LD	C,A
	LD	D,E
	LD	(D$6D20),A
	LD	H,C
	LD	(HL),B
J$427D:	LD	(HL),B
	LD	H,L
J$427F:	LD	(HL),D
	JR	NZ,J.42F4
J$4281	EQU	$-1
	LD	L,A
J$4283:	LD	(HL),L
	LD	(HL),H
J$4285:	LD	L,C
	LD	L,(HL)
J$4287:	LD	H,L
	DEC	C
J$4289:	LD	A,(BC)
	LD	H,E
J$428B:	LD	H,C
J$428C:	LD	L,H
J$428D:	LD	L,H
	JR	NZ,J$42DD
J$428F	EQU	$-1
	LD	B,C
J$4291:	LD	D,B
	LD	(D.2020),A
	JR	NZ,J$42B7
J$4296	EQU	$-1
	JR	NZ,J$42B9
	JR	NZ,J$42BB
	JR	NZ,J$42BD
	JR	NZ,J$42BF
	JR	NZ,J$42C1
	JR	NZ,J$42C3
	JR	NZ,J$42C5
	JR	NZ,J$42C7
J$42A6	EQU	$-1
	JR	NZ,J$430D
	LD	L,C
	LD	(HL),H
	LD	(HL),H
	LD	L,A
	JR	NZ,J$42DC
	JR	NZ,J.4327
	LD	H,L
	LD	(HL),D
	LD	(HL),E
	LD	L,C
	LD	L,A
	LD	L,(HL)
J$42B7:	JR	NZ,J$42EB
J$42B9:	DEC	C
J.42BA:	LD	A,(BC)
J$42BB:	LD	H,E
	LD	H,C
J$42BD:	LD	L,H
	LD	L,H
J$42BF:	JR	NZ,J$4309
J$42C1:	LD	C,A
	LD	D,E
J$42C3:	LD	D,H
	LD	C,C
J$42C5:	LD	B,H
	JR	Z,J$433E
J$42C7	EQU	$-1
	LD	H,C
	LD	(HL),D
	LD	L,C
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	ADD	HL,HL
	JR	NZ,J$42F2
	JR	NZ,J.42F4
	JR	NZ,J$42F6
	JR	NZ,J$42F8
	JR	NZ,J.4321
	LD	H,L
	LD	(HL),H
J$42DC:	JR	NZ,J.4331
J$42DD	EQU	$-1
	LD	B,E
	LD	D,E
	LD	C,C
	JR	NZ,J$432B
	LD	L,A
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J.4331
	LD	B,H
	DEC	C
	LD	A,(BC)
J$42EB:	LD	H,E
	LD	H,C
	LD	L,H
	LD	L,H
	JR	NZ,J$4344
	LD	B,L
J$42F2:	LD	D,H
	LD	C,B
J.42F4:	LD	C,A
	LD	D,E
J$42F6:	LD	D,H
	LD	C,C
J$42F8:	LD	B,H
	JR	Z,J$4371
	LD	H,C
	LD	(HL),D
	LD	L,29H	; ")"
	JR	NZ,J.4321
	JR	NZ,J$4323
	JR	NZ,J$4325
	JR	NZ,J.4327
	JR	NZ,J$4329
J$4309:	LD	D,E
	LD	H,L
	LD	(HL),H
	JR	NZ,J.4361
J$430D	EQU	$-1
	LD	B,E
	LD	D,E
	LD	C,C
	JR	NZ,J$435B
	LD	L,A
I$4314:	LD	(HL),E
	LD	(HL),H
	JR	NZ,J.4361
	LD	B,H
	DEC	C
	LD	A,(BC)
	LD	H,E
	LD	H,C
	LD	L,H
	LD	L,H
	JR	NZ,J$4375
J.4321:	LD	B,C
	LD	D,D
J$4323:	LD	B,A
	LD	B,L
J$4325:	LD	D,H
	LD	C,C
J.4327:	LD	B,H
	JR	Z,J$43A0
J$4329	EQU	$-1
	LD	H,C
J$432B:	LD	(HL),D
	LD	L,C
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
J.4331:	ADD	HL,HL
	JR	NZ,J$4354
	JR	NZ,J$4356
	JR	NZ,J$4358
	JR	NZ,J$4381
	LD	H,L
	LD	(HL),H
	JR	NZ,J$4391
J$433E:	LD	B,E
	LD	D,E
	LD	C,C
	JR	NZ,J$4397
	LD	H,C
J$4344:	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	(HL),H
	JR	NZ,J$4393
	LD	B,H
	DEC	C
	LD	A,(BC)
	LD	H,E
	LD	H,C
	LD	L,H
	LD	L,H
	JR	NZ,J$43A6
	LD	B,L
J$4354:	LD	D,H
	LD	D,H
J$4356:	LD	B,C
	LD	D,D
J$4358:	LD	B,A
	LD	B,L
	LD	D,H
J$435B:	LD	C,C
	LD	B,H
	JR	Z,J$43D5
	LD	H,C
	LD	(HL),D
J.4361:	LD	L,29H	; ")"
	JR	NZ,J$4385
	JR	NZ,J$4387
	JR	NZ,J$4389
	JR	NZ,J$438B
	LD	D,E
	LD	H,L
	LD	(HL),H
	JR	NZ,J$43C3
	LD	B,E
J$4371:	LD	D,E
	LD	C,C
	JR	NZ,J$43C9
J$4375:	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	(HL),H
	JR	NZ,J$43C5
	LD	B,H
	DEC	C
	LD	A,(BC)
	LD	H,E
	LD	H,C
J$4381:	LD	L,H
	LD	L,H
	JR	NZ,J$43CE
J$4385:	LD	C,(HL)
	LD	D,C
J$4387:	LD	D,L
	LD	C,C
J$4389:	LD	D,D
	LD	E,C
J$438B:	JR	Z,J$4403
	LD	H,C
	LD	(HL),D
	INC	L
	LD	(HL),E
J$4391:	LD	(HL),H
	LD	(HL),D
J$4393:	INC	L
	LD	(HL),E
	LD	(HL),H
J$4396:	LD	(HL),D
J$4397:	INC	L
	LD	(HL),E
	LD	(HL),H
	LD	(HL),D
	ADD	HL,HL
	JR	NZ,J$43E5
	LD	H,L
	LD	(HL),H
J$43A0:	JR	NZ,J$43EB
	LD	C,(HL)
	LD	D,C
	LD	D,L
	LD	C,C
J$43A6:	LD	D,D
	LD	E,C
	JR	NZ,J$4419
	LD	H,(HL)
	JR	NZ,J$4420
	LD	(HL),B
	LD	H,L
	LD	H,E
	LD	L,C
	LD	H,(HL)
	LD	L,C
	LD	H,L
	LD	H,H
	JR	NZ,J$440B
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	(HL),H
	DEC	C
	LD	A,(BC)
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	AND	A
J$43C3:	RET

;	  Subroutine CALL HOSTID
;	     Inputs  ________________________
;	     Outputs ________________________

J.43C4:	CALL	C.4073
J$43C5	EQU	$-2
	JR	Z,J$4396
J$43C9:	SBC	A,D
	LD	B,B
	PUSH	DE
J$43CC:	LD	A,(D.F663)
J$43CE	EQU	$-1
	PUSH	AF
	CALL	C.5935
	LD	(D.F7F8),A
J$43D5	EQU	$-1
	XOR	A
	LD	(D.F7F9),A
	POP	AF
	LD	(D.F663),A
	EX	(SP),HL
	CALL	C.40BB
	POP	HL
	CALL	C.4073
J$43E5	EQU	$-1
	ADD	HL,HL
	RET

;	  Subroutine CALL SETHOSTID
;	     Inputs  ________________________
;	     Outputs ________________________

C$43E8:	CALL	C.40B2
J$43EB:	CP	04H	; 4 
	JP	C,J.4089
	CP	08H	; 8 
	JP	NC,J.4089
	CALL	C$50F0
	AND	A
	RET

;	  Subroutine CALL TARGETID
;	     Inputs  ________________________
;	     Outputs ________________________

C$43FA:	CALL	C.4073
	JR	Z,J$43CC
	SBC	A,D
	LD	B,B
	PUSH	DE
	LD	A,(D.F663)
J$4403	EQU	$-2
	PUSH	AF
	CALL	C.5A19
	LD	(D.F7F8),A
J$440B	EQU	$-1
	XOR	A
	LD	(D.F7F9),A
	POP	AF
	LD	(D.F663),A
	EX	(SP),HL
	CALL	C.40BB
	POP	HL
J$4419:	CALL	C.4073
	ADD	HL,HL
	RET

;	  Subroutine CALL SETTARGETID
;	     Inputs  ________________________
;	     Outputs ________________________

C$441E:	CALL	C.40B2
J$4420	EQU	$-1
	CP	07H	; 7 
	CCF
	JP	C,J.4089
	CALL	C.5A3F
	AND	A
	RET

;	  Subroutine CALL INQUIRY
;	     Inputs  ________________________
;	     Outputs ________________________

J.442C:	LD	A,(HL)
	CP	28H	; "("
	JP	NZ,J.408C
	INC	HL
	CALL	C.40B2
	AND	A
	JP	M,J.4089
	CP	08H	; 8 
	JP	NC,J.4089
	LD	IX,(D.F34D)
	LD	(IX+112),A
	LD	A,(HL)
	CP	2CH	; ","
	JP	NZ,J.408C
	INC	HL
	PUSH	IX
	CALL	C.409A
	POP	IX
	LD	A,(D.F663)
	CP	03H	; 3 
	JP	NZ,J.4086
	LD	(IX+113),D
	LD	(IX+114),E
	LD	A,(HL)
	CP	2CH	; ","
	JP	NZ,J.408C
	INC	HL
	PUSH	IX
	CALL	C.409A
	POP	IX
	LD	A,(D.F663)
	CP	03H	; 3 
	JP	NZ,J.4086
	LD	(IX+115),D
	LD	(IX+116),E
	LD	A,(HL)
	CP	2CH	; ","
	JP	NZ,J.408C
	INC	HL
	PUSH	IX
	CALL	C.409A
	POP	IX
	LD	A,(D.F663)
	CP	03H	; 3 
	JP	NZ,J.4086
	LD	(IX+117),D
	LD	(IX+118),E
	LD	A,(HL)
	CP	29H	; ")"
	JP	NZ,J.408C
	PUSH	HL
	LD	A,(IX+112)
	CALL	C$58BF
	JP	C,J$408E
	LD	HL,(D.F34D)
	LD	BC,C.0008
	ADD	HL,BC
	LD	DE,I.F55E
	LD	BC,C.0008
	LD	A,C
	LDIR
	PUSH	HL
	LD	H,(IX+113)
	LD	L,(IX+114)
	PUSH	IX
	CALL	C.40E1
	POP	IX
	POP	HL
	LD	DE,I.F55E
	LD	BC,C.0010
	LD	A,C
	LDIR
	PUSH	HL
	LD	H,(IX+115)
	LD	L,(IX+116)
	PUSH	IX
	CALL	C.40E1
	POP	IX
	POP	HL
	LD	DE,I.F55E
	LD	BC,I.0004
	LD	A,C
	LDIR
	LD	H,(IX+117)
	LD	L,(IX+118)
	CALL	C.40E1
	POP	HL
	INC	HL
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.44F7:	LD	A,L
	OR	H
	RET	Z
	XOR	A
	SUB	L
	LD	L,A
	LD	A,00H
	SBC	A,H
	LD	H,A
	LD	C,L
	LD	B,H
	ADD	HL,SP
	CCF
	RET	C
	LD	DE,(D.FC48)
	SBC	HL,DE
	RET	C
	LD	A,H
	CP	03H	; 3 
	RET	C
	PUSH	BC
	LD	HL,I.0000
	ADD	HL,SP
I.4516:	LD	E,L
	LD	D,H
I.4518:	ADD	HL,BC
	PUSH	HL
	LD	HL,(D.F674)
	AND	A
	SBC	HL,DE
	LD	C,L
	LD	B,H
	INC	BC
	POP	HL
	LD	SP,HL
	EX	DE,HL
	LDIR
	POP	BC
	LD	HL,(D.FC4A)
	ADD	HL,BC
	LD	(D.FC4A),HL
	LD	DE,I$FDEA
	ADD	HL,DE
	LD	(D$F860),HL
	EX	DE,HL
	LD	HL,(D.F672)
	ADD	HL,BC
	LD	(D.F672),HL
	LD	HL,(D.F862)
	ADD	HL,BC
	LD	(D.F862),HL
	LD	HL,(D.F674)
	ADD	HL,BC
	LD	(D.F674),HL
	DEC	HL
	DEC	HL
	LD	(D$F6B1),HL
	LD	L,E
	LD	H,D
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,02H	; 2 
J$455A:	EX	DE,HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	EX	DE,HL
	LD	BC,D.0007
	LD	(HL),B
	ADD	HL,BC
	LD	(HL),B
	LD	BC,I$0102
	ADD	HL,BC
	DEC	A
	JR	NZ,J$455A
	RET

;	  Subroutine CARTRIDGE INIT
;	     Inputs  ________________________
;	     Outputs ________________________

?.456E:	CALL	C$4710
	RET	C
	LD	A,(D.FD99)
	OR	A
	RET	M
	JR	NZ,J$457F
	CALL	C$4587
	RET	C
	JR	J$4583

J$457F:	CALL	C$45FB
	RET	C
J$4583:	CALL	C$5FCC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4587:	LD	HL,I$FB20
	BIT	0,(HL)
	JR	NZ,J$459A
	SET	0,(HL)
	LD	HL,I$FFCA
	LD	B,0FH	; 15 
J$4595:	LD	(HL),0C9H
	INC	HL
	DJNZ	J$4595
J$459A:	LD	HL,(D.FC48)
	LD	DE,I$C001
	RST	20H
	CCF
	RET	C
	LD	A,06H	; 6 
	CALL	C.0141
	RRCA
	CCF
	RET	C
	CALL	C$57F3
	CALL	C.44F7
	RET	C
	PUSH	HL
	LD	HL,I$FE49
	LD	BC,I$F1C9
J$45B9:	XOR	A
	LD	(BC),A
	INC	BC
	INC	HL
	LD	A,L
	OR	H
	JR	NZ,J$45B9
	LD	HL,I.0200
	LD	(D.F6AB),HL
	LD	B,14H	; 20 
	LD	HL,I.FB21
J$45CC:	LD	(HL),A
	INC	HL
	DJNZ	J$45CC
	LD	HL,I$F24F
	LD	B,69H	; "i"
J$45D5:	LD	(HL),0C9H
	INC	HL
	DJNZ	J$45D5
	LD	A,0DBH
	LD	HL,I$C9A8
	LD	(D$F365),A
	LD	(D$F366),HL
	LD	A,06H	; 6 
	CALL	C.0141
	AND	02H	; 2 
	LD	(D.F33F),A
	LD	A,07H	; 7 
	RST	18H
	LD	C,00H
	LD	DE,I.FB21
	EXX
	POP	DE
	JR	J$4632

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$45FB:	LD	HL,I.FB21
	LD	B,04H	; 4 
	XOR	A
J$4601:	ADD	A,(HL)
	RET	C
	INC	HL
	INC	HL
	DJNZ	J$4601
	CP	08H	; 8 
	CCF
	RET	C
	LD	HL,(D.F6AB)
	LD	DE,I.0200
	RST	20H
	JR	NC,J$4618
	LD	(D.F6AB),DE
J$4618:	LD	DE,I.FB21
	LD	BC,I$0400
J$461E:	LD	A,(DE)
	AND	A
	JR	Z,J$4629
	ADD	A,C
	LD	C,A
	INC	DE
	INC	DE
	DJNZ	J$461E
	RET

J$4629:	EXX
	CALL	C$57F8
	CALL	C.44F7
	RET	C
	EX	DE,HL
J$4632:	CALL	C.404A
	LD	(HL),E
	INC	HL
	LD	(HL),D
	EXX
	LD	A,(D.F33F)
	AND	A
	LD	A,C
	CALL	C.4828
	ADD	A,L
	CP	09H	; 9 
	LD	A,L
	JR	C,J$464A
	LD	A,08H	; 8 
	SUB	C
J$464A:	PUSH	BC
	LD	(DE),A
	INC	DE
	CALL	C.4030			; GETSLT
	LD	(DE),A
	POP	BC
	LD	B,00H
	LD	HL,I$F355
	ADD	HL,BC
	ADD	HL,BC
	PUSH	HL
	DEC	DE
	LD	A,(DE)
	PUSH	AF
	PUSH	DE
	LD	L,A
	LD	H,00H
	LD	D,H
	LD	E,L
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
I$4666:	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	CALL	C.44F7
	POP	DE
	JR	C,J$46B6
	PUSH	HL
	CALL	C.4CE1
	POP	DE
	POP	BC
	POP	HL
	LD	C,00H
J$4678:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,I.FE00
	ADD	HL,SP
	LD	SP,HL
	LD	(D.F34D),HL
	LD	A,C
	LD	BC,(D$46FE)
	LD	B,00H
	EX	DE,HL
	CALL	C.4E7E
	LD	HL,I.0200
	EX	AF,AF'
	ADD	HL,SP
	EX	AF,AF'
	LD	SP,HL
	POP	HL
	POP	DE
	LD	BC,I$0015
	JR	C,J$46A5
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	JR	J$46AC

J$46A5:	PUSH	HL
	LD	HL,I$46FD
	LDIR
	POP	HL
J$46AC:	POP	BC
	INC	C
	DJNZ	J$4678
	LD	HL,D.FD99
	INC	(HL)
	AND	A
	RET

J$46B6:	POP	AF
	POP	AF
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	SCF
	RET

J.46BE:	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.46BF:	POP	HL
	LD	A,(HL)
	INC	HL
	PUSH	HL
	OR	A
	RET	Z
	RST	18H
	JR	C.46BF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.46C8:	PUSH	AF
	PUSH	IX
	PUSH	IY
	LD	A,(D.F92C)
	JR	J$46ED

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.46D2:	PUSH	AF
	PUSH	IX
	PUSH	IY
	LD	IX,I$0183
	LD	IY,(D.FCC0)
	CALL	CALSLT
	LD	(D.F92C),A
	CALL	C.5923
	CPL
	RLCA
	RLCA
	AND	01H	; 1 
J$46ED:	LD	IX,X.0180
	LD	IY,(D.FCC0)
	CALL	CALSLT
	POP	IY
	POP	IX
	POP	AF
I$46FD:	RET

D$46FE:	RET	P
	NOP
	LD	(BC),A
	RRCA
	INC	B
	RRA
	LD	B,01H	; 1 
	NOP
	LD	(BC),A
	CP	29H	; ")"
	NOP
	INC	D
	DEC	B
	INC	C
	ADD	HL,DE
	NOP
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4710:	EI
	LD	A,(D.002D)
	CP	1
	RET	C
	LD	A,06H	; 6 
	CALL	C$7E00
	BIT	2,A
	JR	NZ,J.4722
	SCF
	RET

J.4722:	LD	A,50H	; "P"
	LD	(D$F3AE),A
	XOR	A
	CALL	C$005F
J$472B:	LD	A,(D.002D)
	CP	3
	PUSH	AF
	CALL	NC,C.46D2
	CALL	C.5AB8
	LD	BC,DBUF
	LD	HL,I$7F80
	LD	DE,(D$6B25)
	CALL	C$4FFA
	JR	C,J$479A
	POP	AF
	CALL	C$511A
	RET	C
	CALL	C$5158
	RET	C
	CALL	C.578A
	CALL	C$597E
	CALL	C.46BF
	LD	D,B
	LD	L,H
	LD	H,L
	LD	H,C
	LD	(HL),E
	LD	H,L
	JR	NZ,J$47D7
	LD	H,C
	LD	L,C
	LD	(HL),H
	JR	NZ,J$4792
	DEC	L
	NOP
	LD	B,1EH
J$4769:	CALL	C$58A4
	CALL	C.5A19
	PUSH	BC
	CALL	C.5186
	POP	BC
	INC	D
	DEC	D
	JP	Z,J$5972
	CP	42H	; "B"
	CALL	NZ,C.481D
	DJNZ	J$4769
	CALL	C.46BF
	DEC	C
	LD	C,B
	LD	H,C
	LD	(HL),D
	LD	H,H
	JR	NZ,J$47EE
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$47FE
	LD	H,(HL)
	LD	H,(HL)
	LD	L,H
J$4792:	LD	L,C
	LD	L,(HL)
	LD	H,L
	DEC	C
	LD	A,(BC)
	NOP
	SCF
	RET

J$479A:	POP	AF
	CALL	C.46BF
	LD	D,D
	LD	C,A
	LD	C,L
	JR	NZ,J$4806
	LD	L,B
	LD	H,L
	LD	H,E
	LD	L,E
	LD	(HL),E
	LD	(HL),L
	LD	L,L
	JR	NZ,J.4811
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
	DEC	C
	LD	A,(BC)
	NOP
	JR	J.47E9

J$47B5:	CALL	C.46BF
	LD	D,E
	LD	B,E
	LD	D,E
	LD	C,C
	JR	NZ,J.4820
	LD	(HL),L
	LD	(HL),E
	JR	NZ,J$482B
	LD	(HL),E
	JR	NZ,J$4829
	LD	L,A
	LD	(HL),A
	LD	L,(HL)
	DEC	C
	LD	A,(BC)
	NOP
	JR	J.47E9

J$47CD:	CALL	C.46BF
	LD	B,E
	LD	L,A
	LD	L,(HL)
	LD	(HL),H
	LD	(HL),D
	LD	L,A
	LD	L,H
J$47D7:	LD	L,H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$4850
	LD	H,L
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J$4847
	LD	H,C
	LD	L,C
	LD	L,H
	LD	H,L
	LD	H,H
	DEC	C
	LD	A,(BC)
	NOP
J.47E9:	CALL	C.46BF
	RLCA
	LD	C,B
J$47EE:	LD	L,A
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J$485C
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	LD	H,(HL)
	LD	H,C
	LD	H,E
	LD	H,L
	JR	NZ,J$4870
	LD	H,L
J$47FE:	LD	L,H
	LD	H,(HL)
	JR	NZ,J$4876
	LD	H,L
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J$486D
J$4806	EQU	$-1
	LD	H,C
	LD	L,C
I.4809:	LD	L,H
I$480A:	LD	H,L
	LD	H,H
	DEC	C
	LD	A,(BC)
	NOP
	LD	B,05H	; 5 
J.4811:	CALL	C.481D
	DJNZ	J.4811
	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4818:	LD	HL,I$1266
	JR	J.4820

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.481D:	LD	HL,I$B7FB
J.4820:	LD	A,H
	OR	L
	RET	Z
	EX	(SP),HL
	EX	(SP),HL
	DEC	HL
	JR	J.4820

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4828:	PUSH	AF
J$4829:	PUSH	BC
	PUSH	DE
J$482B:	CALL	C.403F
	LD	(HL),00H
	LD	D,H
	LD	E,L
	INC	DE
	CALL	C$57D5
	LDIR
	LD	A,(D.002D)
	CP	3
	LD	A,01H	; 1 
	JR	Z,J$4842
	DEC	A
J$4842:	PUSH	AF
	LD	A,02H	; 2 
	CALL	C.5A72
J$4847	EQU	$-1
	LD	B,0BH	; 11 
	CALL	C.5A83
	AND	0CH	; 12 
	SRL	A
J$4850	EQU	$-1
	LD	D,A
	POP	AF
	OR	D
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
J$485C:	CALL	C.5A83
	AND	04H	; 4 
	SLA	A
	OR	D
	LD	(IX+7),A
	LD	HL,J.64EC
	CALL	C.5BD0
J$486D:	LD	HL,I$140E
J$4870:	LD	(D.81FD),HL
	LD	H,01H	; 1 
	CALL	C.00C6
J$4876	EQU	$-2
	LD	HL,I.FE00
	ADD	HL,SP
	LD	SP,HL
	CALL	C$48C4
	LD	A,(IY)
	LD	C,00H
J.4885:	PUSH	AF
	PUSH	IY
	CALL	C$4904
	POP	IY
	POP	AF
	INC	D
	DEC	D
	JR	NZ,J$4896
	ADD	A,20H	; " "
	JR	NC,J.4885
J$4896:	INC	IY
	LD	A,(IY)
	BIT	7,A
	JR	Z,J.4885
	LD	A,C
	OR	A
	JR	NZ,J$48A6
	INC	C
	LD	A,0F1H
J$48A6:	LD	L,C
	LD	IX,I.0200
	ADD	IX,SP
	LD	SP,IX
J$48AF:	LD	A,03H	; 3 
	CALL	C.0141
	BIT	5,A
	JR	Z,J$48AF
	POP	DE
	POP	BC
	POP	AF
	EI
	HALT

?.48BD:	HALT

?.48BE:	HALT

?.48BF:	HALT

?.48C0:	HALT

?.48C1:	HALT

?.48C2:	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$48C4:	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0BH	; 11 
	CALL	C.5A83
	BIT	2,A
	JR	NZ,J$48E4
	CALL	C.5A19
	LD	IY,I$6B15
	AND	A
	RET	Z
	LD	DE,I$0002
J$48DE:	ADD	IY,DE
	DEC	A
	JR	NZ,J$48DE
	RET

J$48E4:	CALL	C.5923
	AND	07H	; 7 
	LD	IY,I$6A05
	LD	DE,C.0038
	INC	A
	LD	B,A
J$48F2:	ADD	IY,DE
	DJNZ	J$48F2
	CALL	C.5A19
	AND	A
	RET	Z
	LD	B,A
	LD	DE,C.0008
J$48FF:	ADD	IY,DE
	DJNZ	J$48FF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4904:	LD	HL,I.0004
	ADD	HL,SP
	LD	(D.F34D),HL
	PUSH	BC
	PUSH	IX
	PUSH	AF
	LD	E,A
	CALL	C.5923
	INC	A
	ADD	A,E
	AND	07H	; 7 
I$4916	EQU	$-1
	JR	NZ,J$4921
	POP	AF
	POP	IX
	POP	BC
	LD	D,02H	; 2 
	POP	BC
	RET

J$4921:	POP	AF
	PUSH	AF
	CALL	C$5ADF
	POP	AF
	POP	IX
	POP	BC
	INC	D
	DEC	D
	RET	NZ
	LD	(D.83FD),A
	LD	A,C
	LD	(D.83FA),A
	LD	(D.83F1),A
	LD	(D.83FB),IX
	CP	06H	; 6 
	JP	NC,J.4A5C
	CALL	C$4B41
	JP	C,J$4AF7
	LD	A,(D.83FF)
	CP	01H	; 1 
	JP	Z,J$49E5
	CP	02H	; 2 
	JP	Z,J$495C
	AND	A
	JP	Z,J$4A6F
	LD	A,4EH	; "N"
	JP	J.4AF9

J$495C:	LD	IX,(D.83FB)
	LD	IY,I.8800
	LD	A,(D.83FE)
	LD	B,A
	LD	A,(D.83FA)
	LD	C,A
	LD	DE,C.0008
	PUSH	BC
	PUSH	IX
	PUSH	IY
	LD	IX,I.859E
J$4978:	LD	A,(IX)
	RRCA
	XOR	0C0H
	LD	(IY+7),A
	ADD	IX,DE
	ADD	IX,DE
	ADD	IY,DE
	DJNZ	J$4978
	CALL	C.4B0B
	POP	IY
	POP	IX
	POP	BC
	DEC	(IY)
	JR	NZ,J$49D0
	LD	A,(D.83FD)
	LD	(IX),A
	LD	A,(IY+7)
	LD	(IX+6),A
	CALL	C.580F
	BIT	1,A
	JR	Z,J$49B1
	LD	A,(IY+7)
	CALL	C.4B30
	LD	A,H
	LD	(DE),A
J$49B1:	LD	A,(IY+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	LD	(IX+2),A
	LD	A,(IY+3)
	LD	(IX+3),A
	LD	A,(IY+4)
	LD	(IX+4),A
	LD	A,(IY+5)
	LD	(IX+5),A
	INC	C
J$49D0:	PUSH	DE
	LD	DE,C.0008
	ADD	IX,DE
	ADD	IY,DE
	POP	DE
	INC	DE
	LD	A,C
	CP	06H	; 6 
	JP	NC,J.4A5C
	DJNZ	J.4A12
	JP	J.4A5C

J$49E5:	LD	IX,(D.83FB)
	LD	IY,I.8800
	LD	A,(D.83FE)
	LD	B,A
	LD	A,(D.83FA)
	LD	C,A
	LD	DE,C.0008
	CALL	C.5923
	ADD	A,10H	; 16 
	PUSH	BC
	PUSH	IY
	PUSH	AF
	CALL	C.4B30
	POP	AF
J$4A05:	LD	(IY+7),A
	ADD	IY,DE
	DJNZ	J$4A05
	CALL	C.4B0B
	POP	IY
	POP	BC
J.4A12:	DEC	(IY)
	JR	NZ,J$4A4B
	LD	A,(D.83FD)
	LD	(IX),A
	LD	A,(IY+7)
	LD	(IX+6),A
	CALL	C.580F
	BIT	1,A
	JR	Z,J$4A2C
	LD	A,H
	LD	(DE),A
J$4A2C:	LD	A,(IY+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	LD	(IX+2),A
	LD	A,(IY+3)
	LD	(IX+3),A
	LD	A,(IY+4)
	LD	(IX+4),A
	LD	A,(IY+5)
	LD	(IX+5),A
	INC	C
J$4A4B:	PUSH	DE
	LD	DE,C.0008
	ADD	IX,DE
	ADD	IY,DE
	POP	DE
	INC	DE
	LD	A,C
	CP	06H	; 6 
	JR	NC,J.4A5C
	DJNZ	J.4A12
J.4A5C:	LD	(D.83FA),A
	LD	(D.83FB),IX
	PUSH	AF
	LD	A,(D.83F1)
	LD	B,A
	POP	AF
	SUB	B
	ADD	A,30H	; "0"
	JP	J.4AF9

J$4A6F:	CALL	C.580F
	BIT	1,A
	LD	A,30H	; "0"
	JP	Z,J.4AF9
	CALL	C.403F
	LD	DE,I.0030
	ADD	IX,DE
	SET	7,(IX+1)
	LD	DE,I.0040
	ADD	HL,DE
	LD	A,(D.83FA)
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	EX	DE,HL
	LD	IX,(D.83FB)
	LD	IY,I.8800
	CALL	C.5935
	LD	H,01H	; 1 
	AND	A
	JR	Z,J$4AA6
	LD	B,A
J$4AA2:	SLA	H
	DJNZ	J$4AA2
J$4AA6:	LD	A,(D.83FE)
	LD	B,A
	LD	A,(D.83FA)
	LD	C,A
J$4AAE:	DEC	(IY)
	JR	NZ,J.4AE2
	LD	A,(IY+6)
	AND	H
	JR	Z,J.4AE2
	LD	A,(D.83FD)
	LD	(IX),A
	LD	A,(IY+7)
	LD	(DE),A
	LD	A,(IY+1)
	LD	(IX+1),A
	LD	A,(IY+2)
	LD	(IX+2),A
	LD	A,(IY+3)
	LD	(IX+3),A
	LD	A,(IY+4)
	LD	(IX+4),A
	LD	A,(IY+5)
	LD	(IX+5),A
	INC	C
J.4AE2:	PUSH	DE
	LD	DE,C.0008
	ADD	IX,DE
	ADD	IY,DE
	POP	DE
	INC	DE
	LD	A,C
	CP	06H	; 6 
	JP	NC,J.4A5C
	DJNZ	J$4AAE
	JP	J.4A5C

J$4AF7:	LD	A,45H	; "E"
J.4AF9:	RST	18H
	LD	HL,J.64EC
	CALL	C.5BD0
	LD	IX,(D.83FB)
	LD	A,(D.83FA)
	LD	C,A
	LD	D,00H
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4B0B:	CALL	C.580F
	BIT	1,A
	RET	Z
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.403F
	LD	DE,I.0030
	ADD	IX,DE
	LD	DE,I.0040
	ADD	HL,DE
	LD	A,(D.83FA)
	LD	D,00H
	LD	E,A
	ADD	HL,DE
	EX	DE,HL
	POP	IY
	POP	IX
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4B30:	XOR	0FFH
	AND	07H	; 7 
	PUSH	BC
	LD	H,01H	; 1 
	LD	B,A
	AND	A
	JR	Z,J$4B3F
J$4B3B:	SLA	H
	DJNZ	J$4B3B
J$4B3F:	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4B41:	LD	A,(D.83FD)
	LD	B,02H	; 2 
	LD	DE,I.0000
	LD	C,E
	LD	HL,I.8400
	CALL	C.4C9D
	LD	A,D
	OR	A
	JP	NZ,J$4C9B
	LD	HL,(D.85FE)
	LD	DE,I$AA55
	RST	20H
	JR	NZ,J$4B8C
	LD	A,(D.85D2)
	SUB	05H	; 5 
	JR	Z,J$4B95
	LD	HL,(D$85A0)
	LD	DE,I.0000
	RST	20H
	JR	NZ,J.4B7E
	LD	HL,(D$85A2)
	LD	E,01H	; 1 
	RST	20H
	JR	NZ,J.4B7E
	LD	A,02H	; 2 
	LD	IX,I.859E
	JR	J$4B84

J.4B7E:	LD	A,01H	; 1 
	LD	IX,I.85BE
J$4B84:	LD	(D.83FF),A
J.4B87:	CALL	C$4C8C
	JR	J$4BBB

J$4B8C:	LD	A,0FFH
	LD	(D.83FF),A
	INC	A
	JP	J$4C49

J$4B95:	LD	IX,I.85BE
	LD	(D.83FF),A
	LD	A,(D$85F3)
	CP	44H	; "D"
	JR	NZ,J.4B87
	LD	HL,(D$85F4)
	LD	DE,I$7672
	RST	20H
	JR	NZ,J.4B87
	LD	HL,I$85F6
	LD	DE,I.83F2
	LD	BC,C.0008
	LDIR
	LD	IX,I.85BE
J$4BBB:	LD	HL,I.8800
	LD	DE,I.0000
	XOR	A
	LD	B,A
J$4BC3:	PUSH	BC
	PUSH	AF
	PUSH	DE
	EX	AF,AF'
	LD	A,(IX+4)
	OR	A
	JP	Z,J$4C4E
	LD	(HL),A
	INC	HL
	LD	C,(IX+8)
	LD	B,(IX+9)
	EX	AF,AF'
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	ADC	A,(IX+10)
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),A
	INC	HL
	EX	DE,HL
	PUSH	IX
	POP	HL
	LD	BC,I.000C
	ADD	HL,BC
	LDI
	LDI
	LD	A,(D.83FF)
	CP	02H	; 2 
	JR	NC,J$4C14
	DEC	A
	JR	Z,J$4C27
	PUSH	IX
	POP	HL
	PUSH	DE
	LD	B,08H	; 8 
J$4BFF:	DEC	HL
	LD	A,(HL)
	CP	04H	; 4 
	JR	NC,J$4C26
	CPL
	RRCA
	RL	D
	RRCA
	RL	E
	DJNZ	J$4BFF
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	JR	J.4C2D

J$4C14:	EX	DE,HL
	LD	(HL),0FFH
	INC	HL
	LD	B,(IX)
	SRL	B
	INC	B
	LD	A,01H	; 1 
J$4C20:	RRCA
	DJNZ	J$4C20
	LD	(HL),A
	JR	J.4C2D

J$4C26:	POP	DE
J$4C27:	EX	DE,HL
	LD	(HL),0FFH
	INC	HL
	LD	(HL),0FFH
J.4C2D:	INC	HL
	LD	A,(D.83FF)
	OR	A
	JR	Z,J$4C57
	LD	BC,C.0010
	ADD	IX,BC
	PUSH	HL
	PUSH	IX
	POP	HL
	LD	DE,D.85FE
	RST	20H
	POP	HL
	JR	C,J$4C85
J$4C44:	POP	DE
	POP	AF
	POP	BC
	INC	B
	LD	A,B
J$4C49:	LD	(D.83FE),A
	AND	A
	RET

J$4C4E:	POP	DE
	POP	AF
	POP	BC
	LD	A,B
	LD	(D.83FE),A
	AND	A
	RET

J$4C57:	LD	A,(D.85D2)
	CP	05H	; 5 
	JR	NZ,J$4C44
	POP	DE
	POP	AF
	LD	C,(IX+24)
	LD	B,(IX+25)
I$4C64	EQU	$-2
	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	ADC	A,(IX+26)
	LD	C,A
	PUSH	AF
	PUSH	DE
	PUSH	HL
	LD	B,01H	; 1 
	LD	HL,I.8400
	LD	A,(D.83FD)
	CALL	C.4C9D
	LD	A,D
	OR	A
	JP	NZ,J$4C97
	LD	IX,I.85BE
	POP	HL
J$4C85:	POP	DE
	POP	AF
	POP	BC
	INC	B
	JP	J$4BC3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4C8C:	LD	HL,I.83F2
	LD	B,08H	; 8 
J$4C91:	LD	(HL),0FFH
	INC	HL
	DJNZ	J$4C91
	RET

J$4C97:	POP	HL
	POP	DE
	POP	AF
	POP	BC
J$4C9B:	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4C9D:	LD	A,03H	; 3 
	LD	(D.83F0),A
J$4CA2:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.83FD)
	CALL	C.5209
	LD	A,D
	AND	A
	JR	Z,J.4CDB
	CP	02H	; 2 
	JR	NZ,J.4CDB
	LD	A,(D.83FD)
	CALL	C.59EF
	INC	D
	DEC	D
	JR	NZ,J.4CDB
	AND	A
	JR	Z,J.4CDB
	CP	06H	; 6 
	JR	NZ,J.4CDB
	LD	A,B
	CP	29H	; ")"
	JR	Z,J$4CCD
	CP	30H	; "0"
	JR	NZ,J.4CDB
J$4CCD:	LD	A,(D.83F0)
	DEC	A
	LD	(D.83F0),A
	JR	Z,J.4CDB
	POP	HL
	POP	DE
	POP	BC
	JR	J$4CA2

J.4CDB:	LD	HL,CPMADR
	ADD	HL,SP
	LD	SP,HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4CE1:	CALL	C.46BF
	DEC	C
	DEC	DE
	LD	C,E
	NOP
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4CE9:	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	E,A
	LD	D,00H
	CALL	C.403F
	ADD	IX,DE
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4CF5:	LD	A,02H	; 2 
	OUT	(34H),A
	LD	A,0CH	; 12 
	OUT	(35H),A
	CALL	C.5935
	LD	D,A
	LD	BC,I$0700
	LD	A,C
	LD	E,A
J$4D06:	CP	D
	JR	Z,J.4D1B
	PUSH	BC
	PUSH	DE
	CALL	C.5186
	POP	DE
	POP	BC
	CP	85H
	JR	NZ,J.4D1B
	LD	A,C
	SET	0,A
	RRCA
I.4D18:	LD	C,A
	JR	J$4D20

J.4D1B:	LD	A,C
	RES	0,A
	RRCA
	LD	C,A
J$4D20:	INC	E
	LD	A,E
	DJNZ	J$4D06
	LD	A,02H	; 2 
	OUT	(34H),A
	LD	A,7DH	; "}"
	OUT	(35H),A
	LD	A,C
	RRCA
	LD	C,A
	LD	B,08H	; 8 
	LD	E,00H
J$4D33:	RRA
	JR	NC,J$4D37
	INC	E
J$4D37:	DJNZ	J$4D33
	LD	A,E
	RET

J$4D3B:	EI
	PUSH	AF
	CP	06H	; 6 
	JP	NC,J.4E4A
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C$5833
	POP	HL
	POP	DE
	POP	BC
	POP	AF
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4D4C:	BIT	4,(IX)
	JP	NZ,J$4E90
	PUSH	AF
	LD	A,C
	CP	0F0H
	JR	Z,J$4D5E
	CP	0F8H
	JP	NZ,J.4E4A
J$4D5E:	LD	C,00H
	PUSH	DE
	LD	A,B
	DEC	A
	ADD	A,E
	LD	E,A
	LD	A,C
	ADC	A,D
	LD	D,A
	LD	A,C
	ADC	A,C
	LD	C,A
	LD	A,(IX+4)
	SUB	E
	LD	A,(IX+5)
	SBC	A,D
	LD	A,00H
	SBC	A,C
	POP	DE
	JP	C,J$4E23
	LD	A,E
	ADD	A,(IX+1)
	LD	E,A
	LD	A,D
	ADC	A,(IX+2)
	LD	D,A
	LD	A,00H
	ADC	A,(IX+3)
	LD	C,A
	POP	AF
	PUSH	DE
	PUSH	BC
	PUSH	IX
	JR	C,J$4D99
	LD	A,(IX)
	CALL	C.5209
	JR	J.4DCB

J$4D99:	CALL	C$5856
	JP	C,J$4E1C
	LD	A,(IX)
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.534B
	LD	B,A
	LD	A,(D$F30D)
	OR	A
	JP	Z,J.4DC5
	LD	A,D
	OR	A
	JR	NZ,J.4DC5
	CALL	C.5923
	BIT	4,A
	JR	NZ,J.4DC5
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	CALL	C.530C
	JR	J.4DCB

J.4DC5:	LD	A,B
	LD	HL,C.0008
	ADD	HL,SP
	LD	SP,HL
J.4DCB:	POP	IX
	POP	BC
	POP	HL
	CP	42H	; "B"
	LD	A,02H	; 2 
	SCF
	RET	Z
	LD	A,D
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4DD6:	OR	A
	RET	Z
	PUSH	HL
	PUSH	BC
	LD	A,(IX)
	PUSH	IX
	CALL	C.5443
	POP	HL
	PUSH	AF
	INC	D
	DEC	D
	JR	NZ,J$4E07
	LD	A,(IX+2)
	CP	06H	; 6 
	JR	NZ,J$4E0B
	PUSH	HL
	CALL	C.403F
	POP	IX
	LD	A,(IX)
	OR	08H	; 8 
	LD	DE,C.0008
	LD	B,06H	; 6 
J$4DFF:	CP	(HL)
	JR	NZ,J$4E04
	RES	3,(HL)
J$4E04:	ADD	HL,DE
	DJNZ	J$4DFF
J$4E07:	POP	AF
	POP	BC
	POP	DE
	RET

J$4E0B:	POP	AF
	POP	BC
	POP	DE
	BIT	7,(IX)
	RET	Z
	PUSH	AF
	LD	A,B
	SUB	(IX+6)
I.4E18:	ADD	A,E
	LD	B,A
	POP	AF
	RET

J$4E1C:	POP	AF
	POP	BC
	POP	AF
	LD	A,00H
	SCF
	RET

J$4E23:	LD	A,(IX+4)
	SUB	E
	LD	C,A
	INC	C
	LD	A,(IX+5)
	SBC	A,D
	JR	C,J$4E3E
	LD	A,B
	SUB	C
	LD	B,A
	POP	AF
	PUSH	BC
	LD	B,C
	LD	C,0F0H
	CALL	C$4D4C
	JR	C,J$4E43
	POP	BC
	LD	A,0F1H
J$4E3E	EQU	$-1
	LD	A,08H	; 8 
	SCF
	RET

J$4E43:	POP	DE
	PUSH	AF
	LD	A,B
	ADD	A,D
	LD	B,A
	POP	AF
	RET

J.4E4A:	POP	AF
J.4E4B:	LD	A,0CH	; 12 
	SCF
	RET

J$4E4F:	EI
	CP	06H	; 6 
	JR	NC,J.4E4B
	OR	A
	PUSH	AF
	PUSH	HL
	CALL	C.4CE9
	POP	HL
	CALL	C.5923
	XOR	(IX+6)
	AND	07H	; 7 
	JR	NZ,J$4E77
	POP	AF
	LD	B,01H	; 1 
	BIT	3,(IX)
	RET	NZ
	SET	3,(IX)
	CALL	C.4E7E
	LD	B,0FFH
	RET

J$4E77:	POP	AF
	CALL	C.4E7E
	LD	B,00H
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.4E7E:	EI
	CP	06H	; 6 
	JR	NC,J.4E4B
	PUSH	AF
	PUSH	HL
	CALL	C.4CE9
	POP	HL
	POP	AF
	BIT	4,(IX)
	JR	Z,J$4E94
J$4E90:	LD	A,16H
	SCF
	RET

J$4E94:	PUSH	HL
	LD	HL,(D.F34D)
	PUSH	HL
	LD	A,(IX)
	LD	B,01H	; 1 
	LD	C,(IX+3)
	LD	D,(IX+2)
	LD	E,(IX+1)
	CALL	C.5209
	POP	IY
	POP	IX
	LD	A,D
	CALL	C$4DD6
	RET	C
	LD	A,(IY+21)
	LD	(IX+1),A
	CP	0F0H
	JR	Z,J.4EC5
	CP	0F8H
	JR	Z,J.4EC5
	LD	A,12H	; 18 
	SCF
	RET

J.4EC5:	LD	L,(IY+14)
	LD	H,(IY+15)
	LD	(IX+8),L
	LD	(IX+9),H
	LD	A,(IY+16)
	LD	(IX+10),A
	LD	E,(IY+22)
	LD	D,(IY+23)
	LD	(IX+16),E
	LD	B,A
J$4EE1:	ADD	HL,DE
	DJNZ	J$4EE1
	LD	(IX+17),L
	LD	(IX+18),H
	LD	E,(IY+17)
	LD	D,(IY+18)
	LD	(IX+11),E
	LD	C,(IY+11)
	LD	B,(IY+12)
	LD	(IX+2),C
	LD	(IX+3),B
	SRL	B
	RR	C
	SRL	B
	RR	C
	SRL	B
	RR	C
	SRL	B
	RR	C
	SRL	B
	RR	C
	DEC	C
	LD	(IX+4),C
	ADD	A,E
	LD	E,A
	RL	D
J$4F1B:	INC	B
	RR	C
	JR	C,J$4F1B
	DEC	B
	LD	(IX+5),B
J$4F24:	SRL	D
	RR	E
	DJNZ	J$4F24
	ADD	HL,DE
	LD	(IX+12),L
	LD	(IX+13),H
	EX	DE,HL
	LD	L,(IY+19)
	LD	H,(IY+20)
	OR	A
	SBC	HL,DE
	LD	A,(IY+13)
	DEC	A
	LD	(IX+6),A
J$4F42:	INC	B
	RRCA
	JR	C,J$4F42
	LD	(IX+7),B
	DEC	B
	JR	Z,J$4F52
J$4F4C:	SRL	H
	RR	L
	DJNZ	J$4F4C
J$4F52:	INC	HL
	LD	(IX+14),L
	LD	(IX+15),H
	OR	A
	RET

J$4F5B:	LD	HL,I$4F5F
	RET

I$4F5F:	DEC	C
	LD	A,(BC)
	LD	SP,D.2D20
	JR	NZ,J$4FBD
	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	H,L
	JR	NZ,J$4FDC
	LD	(HL),D
	LD	L,A
	LD	(HL),H
	LD	H,L
	LD	H,E
	LD	(HL),H
	JR	NZ,J$4FE4
	LD	H,C
	LD	(HL),D
	LD	(HL),H
	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	DEC	C
	LD	A,(BC)
	LD	(D.2D20),A
	JR	NZ,J.4FDA
	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	H,L
	JR	NZ,J$4FEE
	LD	L,(HL)
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	JR	NZ,J$5000
	LD	H,C
	LD	(HL),D
	LD	(HL),H
	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	DEC	C
	LD	A,(BC)
	DEC	C
	LD	A,(BC)
	NOP
J$4F9D:	LD	E,A
	CP	03H	; 3 
	JR	NC,J$4FA5
	LD	A,D
	CP	06H	; 6 
J$4FA5:	LD	A,0CH	; 12 
	CCF
	RET	C
	DEC	E
	SCF
	RET	M
	PUSH	DE
	LD	A,D
	CALL	C.4CE9
	POP	DE
	LD	D,00H
	LD	HL,I$4FBE
	ADD	HL,DE
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
J$4FBD:	JP	(HL)

I$4FBE:	PUSH	DE
	LD	C,A
	JP	NZ,J$CD4F
	INC	HL
	LD	E,C
	XOR	(IX+6)
	AND	07H	; 7 
	JR	Z,J$4FD0
	LD	A,00H
	SCF
	RET

J$4FD0:	SET	7,(IX+6)
	RET

?.4FD5:	RES	7,(IX+6)
	RET

J.4FDA:	CALL	C.403F
J$4FDC	EQU	$-1
	LD	BC,CPMADR
	OR	C
J$4FE1:	LD	A,(HL)
	PUSH	HL
	PUSH	BC
J$4FE4:	PUSH	AF
	CALL	NZ,C.51A0
	POP	AF
	POP	BC
	POP	HL
J$4FEB:	DEC	C
	RET	Z
	LD	DE,C.0008
J$4FEE	EQU	$-2
	ADD	HL,DE
	BIT	4,(HL)
	JR	NZ,J$4FEB
	XOR	(HL)
	AND	0E7H
	JR	J$4FE1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$4FFA:	PUSH	DE
	PUSH	HL
	LD	HL,I.0000
	LD	(D.8000),HL
J$5000	EQU	$-2
	POP	HL
	CALL	C.500E
	POP	DE
	LD	HL,(D.8000)
	RST	20H
	RET	Z
	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.500E:	LD	A,(HL)
	PUSH	HL
	PUSH	BC
	CALL	C$501D
	POP	BC
	POP	HL
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	JR	C.500E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$501D:	LD	BC,(D.8000)
	LD	E,A
	XOR	C
	LD	C,B
	LD	D,A
	JP	PE,J$502A
	XOR	02H	; 2 
J$502A:	XOR	D
	LD	E,A
	RRA
	RRA
	LD	A,D
	RRA
	LD	D,A
	LD	A,E
	RRA
	LD	E,A
	LD	A,D
	RRA
	LD	B,A
	LD	A,E
	RRA
	XOR	E
	XOR	C
	LD	C,A
	LD	A,D
	XOR	B
	LD	B,A
	LD	(D.8000),BC
	RET

?.5044:	CALL	C$50C5
	CALL	C$507B
	LD	HL,I$8004
	PUSH	HL
	POP	DE
	INC	DE
	LD	(HL),00H
	LD	BC,I.4000
	LDIR
	LD	HL,I.FFFF
	PUSH	HL
	LD	DE,(D.8002)
	AND	A
	SBC	HL,DE
	CALL	C.50CF
	POP	HL
	LD	DE,(D.8000)
	AND	A
	SBC	HL,DE
	CALL	C.50CF
J$5070:	LD	A,03H	; 3 
	CALL	C.0141
	BIT	5,A
	JR	NZ,J$5070
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$507B:	LD	BC,I.4000
	LD	HL,I.4000
J$5081:	LD	A,(HL)
	PUSH	HL
	PUSH	BC
	PUSH	AF
	CALL	C$5092
	POP	AF
	POP	BC
	POP	HL
	INC	HL
	DEC	BC
	LD	A,B
	OR	C
	RET	Z
	JR	J$5081

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5092:	LD	HL,(D.8000)
	LD	DE,(D.8002)
	LD	C,A
	LD	B,08H	; 8 
J$509C:	LD	A,L
	XOR	C
	SRL	C
	SRL	D
	RR	E
	RR	H
	RR	L
	RRA
	JR	NC,J$50BB
	LD	A,D
	XOR	0EDH
	LD	D,A
	LD	A,E
	XOR	0B8H
	LD	E,A
	LD	A,H
	XOR	83H
	LD	H,A
	LD	A,L
	XOR	20H	; " "
	LD	L,A
J$50BB:	DJNZ	J$509C
	LD	(D.8000),HL
	LD	(D.8002),DE
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$50C5:	LD	HL,I.FFFF
	LD	(D.8000),HL
	LD	(D.8002),HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.50CF:	LD	A,H
	CALL	C$50D4
	LD	A,L
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$50D4:	PUSH	AF
	RLCA
	RLCA
	RLCA
	RLCA
	CALL	C$50DD
	POP	AF
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$50DD:	AND	0FH	; 15 
	ADD	A,30H	; "0"
	CP	3AH	; ":"
	JR	C,J$50E7
	ADD	A,07H	; 7 
J$50E7:	JP	C.0018

J$50EA:	CP	04H	; 4 
	RET	C
	CP	08H	; 8 
	RET	NC
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$50F0:	AND	03H	; 3 
	LD	D,A
	PUSH	BC
	PUSH	DE
	PUSH	HL
	XOR	A
	OUT	(34H),A
	OUT	(35H),A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A83
	AND	0CH	; 12 
	OR	D
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A8E
	CALL	C.578A
	POP	HL
	POP	DE
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$511A:	PUSH	AF
	OUT	(36H),A
	IN	A,(34H)
	CP	30H	; "0"
	JR	NZ,J$513C
	LD	DE,D.8000
J$5126:	IN	A,(34H)
	AND	80H
	JR	NZ,J$5134
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J$5126
	POP	AF
	SCF
	RET

J$5134:	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
J$513C:	POP	AF
	CALL	NC,C.46C8
	LD	BC,J.640C
	IN	A,(34H)
	AND	C
	CP	0CH	; 12 
	SCF
	RET	Z
	LD	C,20H	; " "
J$514C:	IN	A,(34H)
	AND	C
	RET	Z
	CALL	C$4818
	DJNZ	J$514C
	JP	J$47B5

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5158:	LD	D,02H	; 2 
	LD	BC,I$0034
J.515D:	OUT	(C),D
	LD	A,B
	OUT	(35H),A
	OUT	(C),D
	IN	A,(35H)
	CP	B
	JP	NZ,J$47CD
	DJNZ	J.515D
	INC	D
	LD	A,D
	CP	0FH	; 15 
	JR	NZ,J.515D
	AND	A
	RET

J$5174:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,1DH
I$517A	EQU	$-1
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OR	04H	; 4 
	JR	J$5193

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5186:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
J$5193:	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(35H),A
	JR	J.51B9

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.51A0:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,1BH
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(C),B
J.51B9:	OUT	(35H),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(35H),A
	POP	AF
	AND	07H	; 7 
	OUT	(35H),A
J.51D5:	IN	A,(34H)
	OR	A
	JP	P,J$51E9
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OR	A
	CALL	Z,C.578A
	JR	J.51D5

J$51E9:	AND	30H	; "0"
	JR	NZ,J.51D5
	LD	IX,C.5757
J$51F1:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$51F1
	LD	A,10H	; 16 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	JP	J.5651

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5209:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OR	C
	OUT	(35H),A
	LD	C,35H	; "5"
I$521C:	OUT	(C),D
	OUT	(C),E
	XOR	A
	OUT	(C),B
	OUT	(C),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(C),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(C),A
	SLA	B
	OUT	(C),B
	OUT	(35H),A
	POP	AF
	AND	07H	; 7 
	OUT	(C),A
J.5241:	IN	A,(34H)
	OR	A
	JP	P,J$5255
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OR	A
	CALL	Z,C.578A
	JR	J.5241

J$5255:	AND	30H	; "0"
	JR	NZ,J.5241
	LD	IX,I.56C7
J$525D:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$525D
	LD	A,10H	; 16 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	CALL	C.53D4
J.5279:	IN	A,(34H)
	RRCA
	JR	NC,J$5286
	LD	B,40H	; "@"
	INIR
	JR	J.5279

?.5284:	DEFB	0,0
J$5286:	AND	40H	; "@"
	JR	NZ,J$528C
	JR	J.5279

J$528C:	CALL	C.593C
	JP	J.5651

J$5292:	EI
	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,15H
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(C),B
	OUT	(35H),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(C),B
	JP	J.5580

J$52C6:	EI
	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,04H	; 4 
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OR	B
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(35H),A
	OUT	(C),D
	OUT	(C),E
	OUT	(35H),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	D,A
	LD	E,A
	BIT	4,B
	JR	Z,J$5305
	PUSH	HL
	INC	HL
	INC	HL
	LD	D,(HL)
	INC	HL
	LD	E,(HL)
	POP	HL
	INC	DE
	INC	DE
	INC	DE
	INC	DE
J$5305:	OUT	(C),D
	OUT	(C),E
	JP	J.5580

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.530C:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,2FH	; "/"
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	XOR	A
	OUT	(35H),A
	LD	A,C
	OUT	(35H),A
	LD	C,35H	; "5"
	OUT	(C),D
	OUT	(C),E
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(C),B
	OUT	(35H),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	SLA	B
	OUT	(C),B
	OUT	(35H),A
	JP	J.5580

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.534B:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,0AH	; 10 
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OR	C
	OUT	(35H),A
	LD	C,35H	; "5"
	OUT	(C),D
	OUT	(C),E
	XOR	A
	OUT	(C),B
	OUT	(35H),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	SLA	B
	OUT	(C),B
	OUT	(35H),A
	POP	AF
	AND	07H	; 7 
	OUT	(35H),A
J.5383:	IN	A,(34H)
	OR	A
	JP	P,J$5397
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OR	A
	CALL	Z,C.578A
	JR	J.5383

J$5397:	AND	30H	; "0"
	JR	NZ,J.5383
	LD	IX,I.56BD
J$539F:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$539F
	LD	A,10H	; 16 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	CALL	C.53D4
J.53BB:	IN	A,(34H)
	RRCA
	JR	NC,J$53C8
	LD	B,04H	; 4 
	OTIR
	DEFB	0,0
	JR	J.53BB

J$53C8:	AND	40H	; "@"
	JR	NZ,J$53CE
	JR	J.53BB

J$53CE:	CALL	C.593C
	JP	J.5651

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.53D4:	CALL	C$5957
	BIT	7,H
	JR	Z,J$53FA
	LD	DE,(D.F34D)
	LD	A,E
	SUB	L
	JR	NZ,J$53E8
	LD	A,D
	SUB	H
	AND	3FH	; "?"
	RET	Z
J$53E8:	EX	(SP),HL
	PUSH	BC
	LD	BC,I.0013
	LDIR
	LD	A,0C9H
	LD	(DE),A
	POP	BC
	EX	(SP),HL
	LD	IY,(D.F34D)
	JP	(IY)

J$53FA:	EX	(SP),HL
	PUSH	BC
	PUSH	HL
	LD	BC,CPMADR
	LD	DE,(D.F34D)
	LD	HL,I$542D
	LDIR
	EX	(SP),HL
	LD	BC,I.0013
	LDIR
	EX	(SP),HL
	LD	BC,C.0010
	LDIR
	CALL	C.4030			; GETSLT
	POP	HL
	POP	BC
	EX	(SP),HL
	LD	IY,(D.F34D)
	LD	(IY+26),A
	LD	A,(D$F342)
	PUSH	IX
	PUSH	BC
	PUSH	HL
	LD	H,40H	; "@"
	JP	(IY)

I$542D:	CALL	ENASLT
D$542F	EQU	$-1
	POP	HL
	POP	BC
	EI
	PUSH	HL
	CALL	C$F368
	LD	A,00H
	LD	H,40H	; "@"
	CALL	ENASLT
	POP	HL
	POP	IX
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5443:	CALL	C.5486
	LD	HL,(D.F34D)
	PUSH	HL
	CALL	C.552F
	POP	IX
	CP	42H	; "B"
	LD	A,02H	; 2 
	SCF
	RET	Z
	BIT	3,D
	LD	A,18H
	SCF
	RET	NZ
	INC	D
	DEC	D
	LD	A,0CH	; 12 
	SCF
	RET	NZ
	LD	A,(IX)
	AND	7FH
	CP	70H	; "p"
	LD	A,0CH	; 12 
	SCF
	RET	NZ
	LD	A,(IX+12)
	CP	2BH	; "+"
	LD	E,A
	JR	NC,J$5482
	LD	HL,I$625A
	ADD	HL,DE
	LD	A,(HL)
	OR	A
	SCF
	RET	P
	CALL	C.5923
	AND	20H	; " "
	RET	NZ
J$5482:	LD	A,0CH	; 12 
	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5486:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	LD	B,12H	; 18 
	OUT	(C),B
	OUT	(35H),A
	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(C),B
	POP	AF
	AND	07H	; 7 
	OUT	(35H),A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.54BC:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,12H	; 18 
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	LD	B,24H	; "$"
	OUT	(C),B
	OUT	(35H),A
	JR	J.5515

J$54DB:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,1AH
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	OUT	(C),B
	XOR	A
	OUT	(35H),A
	LD	B,80H
	OUT	(C),B
	OUT	(35H),A
	JR	J.5515

J$54FA:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,25H	; "%"
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	LD	B,08H	; 8 
J$550F:	OUT	(35H),A
	DJNZ	J$550F
I$5512	EQU	$-1
	LD	B,08H	; 8 
J.5515:	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	OUT	(35H),A
	OUT	(C),B
	POP	AF
	AND	07H	; 7 
	OUT	(35H),A
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.552F:	IN	A,(34H)
	OR	A
	JP	P,J$5543
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OR	A
	CALL	Z,C.578A
	JR	C.552F

J$5543:	AND	30H	; "0"
	JR	NZ,C.552F
	LD	IX,I.56C7
J$554B:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$554B
	LD	A,10H	; 16 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	CALL	C.53D4
J.5567:	IN	A,(34H)
	RRCA
	JR	NC,J$5574
	INI
	JR	J.5567

?.5570:	DEFB	0,0,0,0
J$5574:	AND	40H	; "@"
	JR	NZ,J$557A
	JR	J.5567

J$557A:	CALL	C.593C
	JP	J.5651

J.5580:	POP	AF
	AND	07H	; 7 
	OUT	(35H),A
J.5585:	IN	A,(34H)
	OR	A
	JP	P,J$5599
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OR	A
	CALL	Z,C.578A
	JR	J.5585

J$5599:	AND	30H	; "0"
	JR	NZ,J.5585
	LD	IX,I.56BD
J$55A1:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$55A1
	LD	A,10H	; 16 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	CALL	C.53D4
J.55BD:	IN	A,(34H)
	RRCA
	JR	NC,J$55CA
	OUTI
	JR	J.55BD

?.55C6:	DEFB	0,0,0,0
J$55CA:	AND	40H	; "@"
	JR	NZ,J$55D0
	JR	J.55BD

J$55D0:	CALL	C.593C
	JP	J.5651

J$55D6:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,37H	; "7"
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	OUT	(C),B
	XOR	A
	OUT	(C),A
	OUT	(C),A
	OUT	(C),A
	OUT	(C),A
	OUT	(C),D
	OUT	(C),E
	OUT	(C),A
J$55F9:	LD	A,0FH	; 15 
	OUT	(34H),A
	POP	AF
	RLCA
	RLCA
	RLCA
	OUT	(C),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(C),A
	OUT	(C),D
	OUT	(C),E
	POP	AF
	AND	07H	; 7 
	OUT	(C),A
	JP	C.552F

J$5616:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,18H
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(C),A
	OUT	(C),D
	OUT	(C),E
	OUT	(C),A
	JR	J$55F9

J$5633:	PUSH	AF
	LD	A,03H	; 3 
	OUT	(34H),A
	LD	A,1EH
	OUT	(35H),A
	POP	AF
	PUSH	AF
	AND	0E0H
	PUSH	AF
	OUT	(35H),A
	LD	C,35H	; "5"
	XOR	A
	OUT	(C),A
	OUT	(C),A
	OUT	(C),B
	OUT	(C),A
	JP	J.51B9

J.5651:	LD	DE,C.0008
	LD	C,35H	; "5"
J.5656:	IN	A,(34H)
	BIT	0,A
	JP	NZ,J$5751
	BIT	5,A
	JR	NZ,J.5656
	LD	A,17H
	OUT	(34H),A
	DEFB	0,0
	IN	A,(35H)
	CP	04H	; 4 
	JR	NZ,J$566F
	RES	2,A
J$566F:	BIT	3,A
	JR	NZ,J$56A6
	CP	16H
	JP	Z,J$5748
	BIT	4,A
	RET	NZ
	OR	A
	JP	Z,C.578A
	CP	21H	; "!"
	JR	NZ,J$5687
	PUSH	HL
	POP	IY
	DEC	A
J$5687:	CP	20H	; " "
	JP	Z,J$5730
	CP	85H
	JR	NZ,J$5695
	BIT	7,D
	RET	Z
	JR	J.5656

J$5695:	CP	80H
	JR	NZ,J$569D
	RES	7,D
	JR	J.5656

J$569D:	BIT	6,A
	JR	NZ,J$56A3
	OUT	(36H),A
J$56A3:	LD	D,02H	; 2 
	RET

J$56A6:	AND	07H	; 7 
	LD	B,A
	LD	A,18H
	OUT	(34H),A
	LD	A,0A0H
	OUT	(35H),A
J$56B1:	IN	A,(34H)
	RRCA
	JR	NC,J$56B1
	LD	A,19H
	OUT	(34H),A
	INC	B
	DJNZ	J$56C5
I.56BD:	OUTI
	CALL	C.5757
	JP	J.5656

J$56C5:	DJNZ	J$56CF
I.56C7:	INI
	CALL	C.5757
	JP	J.5656

J$56CF:	DJNZ	J$56D7
J$56D1:	XOR	A
	OUT	(35H),A
	JP	J.5656

J$56D7:	DJNZ	J$56DE
	IN	D,(C)
	JP	J.5656

J$56DE:	DJNZ	J$56E3
	JP	J$56D1

J$56E3:	DJNZ	J$56EA
	IN	A,(35H)
	JP	J.5656

J$56EA:	DJNZ	J$56F3
	OUT	(C),E
	LD	E,08H	; 8 
	JP	J.5656

J$56F3:	IN	A,(C)
	JP	Z,J.5656
	JP	M,J.5656
	CP	02H	; 2 
	JR	Z,J$5724
	CP	03H	; 3 
	JR	Z,J$572A
	CP	04H	; 4 
	JR	Z,J$5719
	CP	07H	; 7 
	JR	Z,J.571E
	CP	08H	; 8 
	JP	Z,J.5656
	CP	09H	; 9 
	JR	Z,J.571E
	LD	E,07H	; 7 
	JP	J.5656

J$5719:	SET	7,D
	JP	J.5656

J.571E:	LD	DE,I.0206
	JP	J.5656

J$5724:	PUSH	HL
	POP	IX
	JP	J.5656

J$572A:	PUSH	IX
	POP	HL
	JP	J.5656

J$5730:	LD	A,E
	CP	08H	; 8 
	JR	Z,J$573D
	LD	A,18H
	OUT	(34H),A
	LD	A,02H	; 2 
	OUT	(35H),A
J$573D:	LD	A,18H
	OUT	(34H),A
	LD	A,03H	; 3 
	OUT	(35H),A
	JP	J.5656

J$5748:	LD	A,0FH	; 15 
	OUT	(34H),A
	IN	D,(C)
	JP	J.5656

J$5751:	CALL	C$F398
	JP	J.5656

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5757:	IN	A,(34H)
	OR	A
	JP	P,J$5767
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	JR	C.5757

J$5767:	IN	A,(34H)
	RRCA
	JR	NC,J$5778
	LD	A,19H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OUT	(35H),A
	JR	C.5757

J$5778:	LD	DE,I.0206
J$577B:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$577B
	LD	A,18H
	OUT	(34H),A
	LD	A,02H	; 2 
	OUT	(35H),A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.578A:	XOR	A
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	OR	A
	JR	NZ,J$57B8
	OUT	(34H),A
	CALL	C.5935
J.5799:	OUT	(35H),A
J$579B:	IN	A,(34H)
	AND	10H	; 16 
	JR	NZ,J$579B
	LD	A,18H
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
J$57A8:	EX	(SP),HL
	EX	(SP),HL
	IN	A,(34H)
	AND	20H	; " "
	JR	NZ,J$57A8
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
J$57B8:	LD	A,01H	; 1 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,7DH	; "}"
	OUT	(35H),A
	LD	A,11H	; 17 
	OUT	(34H),A
	LD	A,30H	; "0"
	OUT	(35H),A
	LD	A,16H
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	D,02H	; 2 
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$57D5:	CALL	C.580F
	LD	BC,I$002F
	RET	Z
	PUSH	HL
	LD	H,B
	LD	L,C
	LD	BC,I.0100
	BIT	1,A
	JR	Z,J$57E7
	ADD	HL,BC
J$57E7:	LD	BC,I.0100
	BIT	0,A
	JR	Z,J$57EF
	ADD	HL,BC
J$57EF:	PUSH	HL
	POP	BC
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$57F3:	LD	HL,I$01E7
	JR	J$57FB

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$57F8:	LD	HL,I.0030
J$57FB:	CALL	C.580F
	RET	Z
	LD	DE,I.0100
	BIT	1,A
	JR	Z,J$5807
	ADD	HL,DE
J$5807:	BIT	0,A
	RET	Z
	LD	DE,I.0100
	ADD	HL,DE
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.580F:	PUSH	BC
	PUSH	DE
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0BH	; 11 
	CALL	C.5A83
	RRA
	RRA
	RRA
	AND	01H	; 1 
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A83
	RRA
	AND	02H	; 2 
	OR	D
	POP	DE
	POP	BC
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5833:	PUSH	AF
	CALL	C.403F
	BIT	3,(IX+7)
	JR	NZ,J$5847
	POP	AF
J$583E:	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	E,A
	LD	D,00H
	ADD	IX,DE
	RET

J$5847:	POP	AF
	PUSH	IX
	LD	DE,I.0030
	ADD	IX,DE
	LD	(IX),A
	POP	IX
	JR	J$583E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5856:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	CALL	C.403F
	BIT	3,(IX+7)
	JR	Z,J$586A
	BIT	7,(IX+49)
	JR	NZ,J$587D
J$586A:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	CALL	C.5923
	OR	80H
	XOR	(IX+6)
	AND	8FH
	SCF
	RET	NZ
	CCF
	RET

J$587D:	LD	DE,I.0030
	ADD	IX,DE
	LD	A,(IX)
	LD	E,A
	LD	D,00H
	ADD	IX,DE
	CALL	C.5935
	LD	C,01H	; 1 
	AND	A
	JR	Z,J$5897
	LD	B,A
J$5893:	RLC	C
	DJNZ	J$5893
J$5897:	LD	A,C
	AND	(IX+16)
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	SCF
	RET	Z
	CCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$58A4:	PUSH	AF
	PUSH	HL
	LD	A,(D.F6A0)
	INC	A
	AND	01H	; 1 
	LD	(D.F6A0),A
	LD	HL,I$6258
	ADD	A,L
	LD	L,A
	JR	NC,J$58B7
	INC	H
J$58B7:	LD	A,(HL)
	RST	18H
	LD	A,08H	; 8 
	RST	18H
	POP	HL
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$58BF:	LD	B,A
	CALL	C.5935
	CP	B
	JR	Z,J$58FA
	LD	A,B
	PUSH	IX
	CALL	C.5186
	POP	IX
	INC	D
	DEC	D
	JR	Z,J$590C
	LD	A,D
	CP	02H	; 2 
	JR	Z,J.58DB
J.58D7:	LD	E,46H	; "F"
	SCF
	RET

J.58DB:	LD	A,(IX+112)
	CALL	C.5443
	INC	D
	DEC	D
	JR	NZ,J.58D7
	LD	A,(IX)
	AND	0FFH
	CP	70H	; "p"
	LD	E,45H	; "E"
	SCF
	RET	NZ
	LD	A,(IX+2)
	AND	0FH	; 15 
	CP	02H	; 2 
	JR	Z,J.58D7
	RET

J$58FA:	LD	HL,(D.F34D)
	LD	DE,C.0008
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I$6921
	LD	BC,C.001C
	LDIR
	AND	A
	RET

J$590C:	LD	A,(IX+112)
	LD	HL,(D.F34D)
	PUSH	IX
	CALL	C.54BC
	POP	IX
	INC	D
	DEC	D
	RET	Z
	LD	A,D
	CP	02H	; 2 
	JR	Z,J.58DB
	JR	J.58D7

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5923:	PUSH	BC
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A83
	POP	BC
	AND	03H	; 3 
	CPL
	SUB	4CH	; "L"
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5935:	CALL	C.5923
	CPL
	AND	07H	; 7 
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.593C:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.403F
	BIT	0,(IX+7)
	CALL	NZ,C.46C8
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5957:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	PUSH	IY
	CALL	C.403F
	BIT	0,(IX+7)
	CALL	NZ,C.46D2
	POP	IY
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET

J$5972:	CALL	C.4CE1
	CALL	C$5999
	CALL	C$59BB
	JP	J$59CD

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$597E:	LD	HL,I$63A5
	CALL	C$7F00
	LD	HL,I$7D00
J$5987:	LD	A,08H	; 8 
	CALL	C.0141
	BIT	3,A
	JP	Z,J$5BD7
	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J$5987
	JP	C.4CE1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5999:	CALL	C.580F
	BIT	0,A
	JR	Z,J$59B5
	LD	HL,I$63BE
	CALL	C.5BD0
	LD	A,(D.7FFA)
	CALL	C.5A98
	LD	A,2EH	; "."
	RST	18H
	LD	A,(D$7FFB)
	CALL	C.5AAC
J$59B5:	LD	HL,J.6389
	JP	C.5BD0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$59BB:	CALL	C.5935
	CP	04H	; 4 
	RET	NC
	LD	A,(D$7FF7)
	CPL
	AND	07H	; 7 
	PUSH	AF
	CALL	C.59FE
	POP	AF
	RET

J$59CD:	PUSH	AF
	LD	HL,I$638D
	CALL	C.5BD0
	POP	AF
	ADD	A,30H	; "0"
	RST	18H
	LD	HL,I$6397
	CALL	C.5BD0
	CALL	C.5A19
	ADD	A,30H	; "0"
	RST	18H
	XOR	A
	OUT	(34H),A
	OUT	(35H),A
	CALL	C.578A
	JP	C.481D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.59EF:	CALL	C.5443
	LD	A,(IX+2)
	AND	0FH	; 15 
	LD	B,(IX+12)
	LD	C,(IX+13)
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.59FE:	AND	03H	; 3 
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A83
	AND	0CH	; 12 
	OR	D
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	JP	C.5A8E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A19:	PUSH	BC
	CALL	C.5A2D
	RRA
	RRA
	AND	03H	; 3 
	PUSH	AF
	CALL	C.5A36
	AND	08H	; 8 
	RRA
	LD	B,A
	POP	AF
	OR	B
	POP	BC
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A2D:	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,03H	; 3 
	JR	C.5A83

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A36:	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	JR	C.5A83

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A3F:	CP	07H	; 7 
	CCF
	RET	C
	PUSH	AF
	AND	04H	; 4 
	SLA	A
	LD	D,A
	CALL	C.5A36
	AND	07H	; 7 
	OR	D
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A8E
	POP	AF
	SLA	A
	SLA	A
	LD	D,A
	CALL	C.5A2D
	AND	03H	; 3 
	OR	D
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,03H	; 3 
	CALL	C.5A8E
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A72:	PUSH	BC
	PUSH	AF
	LD	B,0DH	; 13 
	CALL	C.5A83
	DI
	AND	0CH	; 12 
	POP	BC
	OR	B
	OUT	(0B5H),A
	POP	BC
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A83:	DI
	LD	A,B
	OUT	(0B4H),A
	INC	B
	IN	A,(0B5H)
	AND	0FH	; 15 
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A8E:	DI
	LD	A,B
	OUT	(0B4H),A
	LD	A,D
	INC	B
	OUT	(0B5H),A
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5A98:	LD	B,A
	AND	0F0H
	RLCA
	RLCA
	RLCA
	RLCA
	AND	A
	JR	Z,J.5AA5
	ADD	A,30H	; "0"
	RST	18H
J.5AA5:	LD	A,B
	AND	0FH	; 15 
	ADD	A,30H	; "0"
	RST	18H
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5AAC:	LD	B,A
	AND	0F0H
	RLCA
	RLCA
	RLCA
	RLCA
	ADD	A,30H	; "0"
	RST	18H
	JR	J.5AA5

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5AB8:	LD	HL,I$62DE
	CALL	C.5BD0
	INC	HL
	LD	DE,I$7FF5
	LD	A,(DE)
	CALL	C.5A98
	LD	A,2EH	; "."
	RST	18H
	INC	DE
	LD	A,(DE)
	CALL	C.5AAC
	LD	A,(D$7FF9)
	AND	A
	JR	Z,J$5ADC
	PUSH	AF
	LD	A,2EH	; "."
	RST	18H
	POP	AF
	CALL	C.5AAC
J$5ADC:	JP	C.5BD0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5ADF:	LD	HL,I.8400
	LD	IY,I.8200
	CALL	C$5B7B
	INC	D
	DEC	D
	JR	Z,J$5AFB
	LD	A,02H	; 2 
	LD	(D.81FC),A
	LD	D,A
	RET

J$5AF4:	INC	HL
	CALL	C.5BD0
	LD	D,02H	; 2 
	RET

J$5AFB:	LD	HL,J.63D4
	CALL	C.5BD0
	LD	A,(IY)
	ADD	A,30H	; "0"
	RST	18H
	LD	A,(IY+1)
	AND	A
	JR	Z,J$5B0F
	LD	A,02H	; 2 
J$5B0F:	LD	(D.81FC),A
	LD	HL,I$64EF
	CALL	C.5BD0
	PUSH	IY
	POP	HL
	LD	DE,I$0009
	ADD	HL,DE
	CALL	C.5BD0
	PUSH	HL
	LD	HL,(D.81FD)
	CALL	C.00C6
	POP	HL
	INC	HL
	CALL	C.5BD0
	PUSH	HL
	LD	HL,(D.81FD)
	LD	DE,I$1300
	ADD	HL,DE
	CALL	C.00C6
	LD	HL,I$64F7
	CALL	C.5BD0
	POP	HL
	INC	HL
	CALL	C.5BD0
	BIT	7,(IY+2)
	JR	Z,J$5B50
	LD	HL,J.6502
	CALL	C.5BD0
J$5B50:	LD	HL,(D.81FD)
	PUSH	HL
	LD	H,4AH	; "J"
	CALL	C.00C6
	POP	HL
	INC	L
	LD	(D.81FD),HL
	CALL	C$5B6D
	LD	A,(D.81FC)
	LD	D,A
	AND	A
	RET	Z
	LD	HL,I$64F2
	JP	J$5AF4

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5B6D:	LD	HL,I.8200
	LD	DE,I$8201
	LD	BC,I$0230
	LD	(HL),00H
	LDIR
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5B7B:	PUSH	HL
	PUSH	IY
	LD	(IY),A
	CALL	C.54BC
	POP	IY
	POP	HL
	LD	A,D
	AND	A
	JR	Z,J$5B90
	LD	A,0FFH
	LD	D,02H	; 2 
	RET

J$5B90:	LD	A,(HL)
	AND	1FH
	LD	(IY+1),A
	INC	HL
	PUSH	IY
	POP	DE
	INC	DE
	INC	DE
	LD	BC,D.0007
	LDIR
	XOR	A
	LD	BC,C.0008
	LDIR
	LD	(DE),A
	INC	DE
	LD	BC,C.0010
	LDIR
	LD	(DE),A
	INC	DE
	LD	BC,I.0004
	LDIR
	LD	(DE),A
	INC	DE
	LD	D,00H
	LD	A,(IY)
	RET

;	  Subroutine CARTRIDGE CALL statement
;	     Inputs  ________________________
;	     Outputs ________________________

?.5BBD:	LD	DE,I$6285
	LD	A,(D.002D)
	CP	3
	JR	NC,J$5BCA
	LD	DE,I$6299
J$5BCA:	CALL	C.5F7F
	RET	C
	PUSH	DE
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5BD0:	LD	A,(HL)
	AND	A
	RET	Z
	INC	HL
	RST	18H
	JR	C.5BD0

J$5BD7:	CALL	C.4CE1
	LD	HL,I$6509
	CALL	C.5BD0
	CALL	C$5EB4
	LD	IX,I.8200
	CALL	C.5935
	LD	(IX),A
	CALL	C.5A19
	LD	(IX+1),A
	PUSH	IX
	CALL	C.578A
	CALL	C.4CF5
	POP	IX
	LD	(IX+2),A
	LD	(IX+12),C
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0BH	; 11 
	CALL	C.5A83
	LD	D,00H
	BIT	2,A
	JR	Z,J$5C14
	INC	D
J$5C14:	LD	(IX+5),D
	LD	D,00H
	BIT	3,A
	JR	Z,J$5C1E
	INC	D
J$5C1E:	LD	(IX+6),D
	XOR	A
	LD	(IX+4),A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A83
	LD	(IX+13),00H
	BIT	2,A
	JR	Z,J$5C3A
	INC	(IX+13)
J$5C3A:	CALL	C$5EF0
	LD	HL,I$6511
	CALL	C.5F5F
J.5C43:	PUSH	IX
	LD	A,(IX+1)
	CALL	C.5186
	POP	IX
	LD	(IX+3),A
	LD	HL,I.2009
	CALL	C.00C6
	LD	A,(IX)
	ADD	A,30H	; "0"
	RST	18H
	LD	HL,I.4809
	CALL	C.00C6
	LD	A,(IX+1)
	ADD	A,30H	; "0"
	RST	18H
	LD	HL,I$200A
	CALL	C.00C6
	BIT	0,(IX+5)
	LD	HL,J.66D2
	JR	Z,J$5C7A
	LD	HL,I.66DB
J$5C7A:	CALL	C.5BD0
	LD	HL,I$480A
	CALL	C.00C6
	BIT	0,(IX+6)
	LD	HL,J.66D2
	JR	Z,J$5C8F
	LD	HL,I.66DB
J$5C8F:	CALL	C.5BD0
	LD	HL,I$200B
	CALL	C.00C6
	BIT	0,(IX+13)
	LD	HL,J.66D2
	JR	Z,J$5CA4
	LD	HL,I.66DB
J$5CA4:	CALL	C.5BD0
	LD	HL,I$665D
	CALL	C.5F5F
	LD	A,(IX+2)
	ADD	A,30H	; "0"
	RST	18H
	CALL	C$5F25
	LD	HL,J.666F
	CALL	C.5F5F
	LD	A,(IX+3)
	CP	85H
	LD	HL,J.66A5
	LD	A,0AH	; 10 
	LD	(IX+11),A
	JR	NZ,J.5D20
	LD	A,(IX+1)
	PUSH	HL
	LD	HL,I.8700
	PUSH	IX
	CALL	C.54BC
	POP	IX
	INC	D
	DEC	D
	JR	NZ,J$5D10
	POP	HL
	LD	HL,I.8700
	LD	A,(HL)
	AND	1FH
	LD	(IX+11),A
	XOR	A
	LD	HL,I$8708
	LD	DE,I.8800
	LD	BC,C.0008
	LDIR
	LD	(DE),A
	PUSH	HL
	LD	HL,I.8800
	CALL	C.5BD0
	POP	HL
	LD	DE,I.8800
	LD	BC,C.0010
	LDIR
	LD	(DE),A
	LD	HL,I$668E
	CALL	C.5F5F
	LD	HL,I.8800
	JR	J.5D20

J$5D10:	LD	A,D
	CP	02H	; 2 
	JR	NZ,J$5D1F
	LD	A,(IX+1)
	PUSH	IX
	CALL	C.5443
	POP	IX
J$5D1F:	POP	HL
J.5D20:	CALL	C.5BD0
	LD	HL,J.66C1
	CALL	C.5F5F
	LD	A,(IX+11)
	CP	0BH	; 11 
	JR	C,J$5D32
	LD	A,0AH	; 10 
J$5D32:	LD	HL,I$63D9
	AND	A
	JR	Z,J$5D3F
	LD	B,A
	LD	DE,I$0019
J$5D3C:	ADD	HL,DE
	DJNZ	J$5D3C
J$5D3F:	LD	DE,I.0004
	ADD	HL,DE
	CALL	C.5BD0
J$5D46:	LD	HL,I$6720
	CALL	C.5F5F
	CALL	C.009F
	CP	1BH
	JR	Z,J.5D7D
	SET	5,A
	CP	71H	; "q"
	JR	Z,J.5D7D
	CP	73H	; "s"
	JR	Z,J$5D89
	CP	68H	; "h"
	JP	Z,J.5DE7
	CP	74H	; "t"
	JP	Z,J.5E24
	CP	61H	; "a"
	JP	Z,J$5E70
	CP	6DH	; "m"
	JP	Z,J$5E55
	CP	65H	; "e"
	JP	Z,J$5E87
	CP	72H	; "r"
	JP	Z,J$5E9E
	JR	J$5D46

J.5D7D:	CALL	C$5EDD
	CALL	C$5F18
	LD	A,0CH	; 12 
	RST	18H
	JP	C.5AB8

J$5D89:	DEC	(IX+4)
	JR	NZ,J.5D7D
	LD	A,(IX)
	CALL	C.59FE
	LD	A,(IX+1)
	CALL	C.5A3F
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A83
	AND	0BH	; 11 
	LD	D,A
	LD	A,(IX+13)
	SLA	A
	SLA	A
	OR	D
	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0CH	; 12 
	CALL	C.5A8E
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0BH	; 11 
	CALL	C.5A83
	LD	D,(IX+5)
	SET	2,A
	BIT	0,D
	JR	NZ,J$5DCF
	RES	2,A
J$5DCF:	LD	D,(IX+6)
	SET	3,A
	BIT	0,D
	JR	NZ,J$5DDA
	RES	3,A
J$5DDA:	LD	D,A
	LD	A,02H	; 2 
	CALL	C.5A72
	LD	B,0BH	; 11 
	CALL	C.5A8E
	JR	J.5D7D

J.5DE7:	LD	HL,I.6912
	CALL	C.5F5F
	LD	HL,J.66E4
	CALL	C.5F5F
	LD	HL,I.2009
	CALL	C.00C6
	CALL	C.009F
	CP	1BH
	JR	Z,J.5E18
	SUB	30H	; "0"
	CP	08H	; 8 
	JR	NC,J.5DE7
	CP	04H	; 4 
	JR	C,J.5DE7
	LD	B,(IX+1)
	CP	B
	JR	Z,J.5DE7
	LD	(IX),A
	LD	A,01H	; 1 
	LD	(IX+4),A
J.5E18:	LD	HL,I$0116
	CALL	C.00C6
	CALL	C.4CE1
	JP	J.5C43

J.5E24:	LD	HL,I.6912
	CALL	C.5F5F
	LD	HL,I$6701
	CALL	C.5F5F
	LD	HL,I.4809
	CALL	C.00C6
	CALL	C.009F
	CP	1BH
	JR	Z,J$5E53
	SUB	30H	; "0"
	JR	C,J.5E24
	CP	07H	; 7 
	JR	NC,J.5E24
	LD	B,(IX)
	CP	B
	JR	Z,J.5E24
	LD	(IX+1),A
	LD	A,01H	; 1 
	LD	(IX+4),A
J$5E53:	JR	J.5E18

J$5E55:	LD	A,01H	; 1 
	LD	(IX+4),A
	LD	A,(IX+5)
	XOR	01H	; 1 
	LD	(IX+5),A
	LD	HL,I$67CE
	JR	NZ,J.5E6A
	LD	HL,I$681F
J.5E6A:	CALL	C.5F5F
	JP	J.5C43

J$5E70:	LD	A,01H	; 1 
	LD	(IX+4),A
	LD	A,(IX+6)
	XOR	01H	; 1 
	LD	(IX+6),A
	LD	HL,J.672C
	JR	NZ,J.5E6A
	LD	HL,I$677D
	JR	J.5E6A

J$5E87:	LD	A,01H	; 1 
	LD	(IX+4),A
	LD	A,(IX+13)
	XOR	01H	; 1 
	LD	(IX+13),A
	LD	HL,I$6870
	JR	NZ,J.5E6A
	LD	HL,I$68C1
	JR	J.5E6A

J$5E9E:	LD	HL,I.6912
	CALL	C.5F5F
I$5EA4:	PUSH	IX
	CALL	C.4CF5
	POP	IX
	LD	(IX+2),A
	LD	(IX+12),C
	JP	J.5C43

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5EB4:	LD	DE,(D.F34D)
	LD	(D.8207),DE
	LD	DE,I.8400
	LD	(D.F34D),DE
	CALL	C.403F
	LD	(D.8209),HL
	CALL	C.404A
	LD	DE,I$8600
	LD	(HL),E
	INC	HL
	LD	(HL),D
	PUSH	DE
	POP	HL
	INC	DE
	LD	(HL),00H
	LD	BC,C.0008
	LDIR
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5EDD:	LD	DE,(D.8207)
	LD	(D.F34D),DE
	CALL	C.404A
	LD	DE,(D.8209)
	LD	(HL),E
	INC	HL
	LD	(HL),D
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5EF0:	LD	HL,I$0800
	CALL	C.0171
	LD	A,(D.0007)
	LD	C,A
	LD	B,00H
	LD	HL,I$693D
	DI
	OTIR
	LD	B,0EH	; 14 
	OTIR
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	LD	BC,I$A40C
	CALL	C.0047
	LD	BC,I$F00D
	CALL	C.0047
	EI
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5F18:	LD	BC,I.000C
	CALL	C.0047
	LD	BC,I$000D
	CALL	C.0047
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5F25:	LD	HL,I$08B2
	CALL	C.0171
	LD	A,(IX+12)
	LD	HL,I$6A2D
	LD	C,A
	LD	DE,I.0000
	AND	A
	JR	Z,J.5F4E
	LD	B,08H	; 8 
J.5F3A:	RRC	C
	JR	NC,J$5F4A
	LD	A,(HL)
	ADD	A,D
	LD	D,A
	INC	HL
	LD	A,(HL)
	ADD	A,E
	LD	E,A
	INC	HL
	DJNZ	J.5F3A
	JR	J.5F4E

J$5F4A:	INC	HL
	INC	HL
	DJNZ	J.5F3A
J.5F4E:	LD	A,(D.0007)
	LD	C,A
	OUT	(C),D
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	OUT	(C),E
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5F5F:	PUSH	IX
	CALL	C.5F67
	POP	IX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5F67:	LD	A,(HL)
	AND	A
	RET	Z
	CP	0FFH
	JR	NZ,J$5F7B
	INC	HL
	LD	A,(HL)
	INC	HL
	PUSH	HL
	LD	L,(HL)
	LD	H,A
	CALL	C.00C6
	POP	HL
	INC	HL
	JR	C.5F67

J$5F7B:	RST	18H
	INC	HL
	JR	C.5F67

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5F7F:	LD	A,(DE)
	OR	A
	SCF
	RET	Z
	LD	IX,I$FD89
J$5F87:	BIT	7,A
	INC	DE
	JR	NZ,J$5F9E
	CP	(IX+0)
	INC	IX
	LD	A,(DE)
	JR	Z,J$5F87
J$5F94:	AND	80H
	INC	DE
	LD	A,(DE)
	JR	Z,J$5F94
J.5F9A:	INC	DE
	INC	DE
	JR	C.5F7F

J$5F9E:	AND	7FH
	CP	(IX)
	JR	NZ,J.5F9A
	LD	A,(IX+1)
	OR	A
	JR	NZ,J.5F9A
	LD	A,(DE)
	LD	C,A
	INC	DE
	LD	A,(DE)
	LD	D,A
	LD	E,C
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.5FB2:	CALL	C.403F
	LD	DE,I.0030
	ADD	IX,DE
	CALL	C.580F
	SCF
	BIT	0,A
	RET	Z
	CCF
	BIT	1,A
	RET	Z
	LD	DE,I.0100
	ADD	IX,DE
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$5FCC:	CALL	C.5FB2
	RET	C
	PUSH	IX
	POP	DE
	LD	HL,I$7FF0
	LD	BC,I.0004
	LDIR
	LD	BC,(D.7FFA)
	LD	(IX+4),C
	LD	(IX+5),B
	RET

J$5FE6:	CALL	C.5FB2
	RET	C
	LD	DE,C.0010
	ADD	IX,DE
	PUSH	IX
	CALL	C.614E
	POP	HL
	CALL	C$603A
	XOR	A
	LD	(IX+24),A
	LD	A,(IX+20)
	AND	A
	RET	Z
	SET	7,(IX+24)
	BIT	0,(IX-10)
	RET	Z
	CP	02H	; 2 
	RET	NZ
	CALL	C.601D
	AND	A
	SET	6,(IX+24)
	DEC	D
	INC	D
	RET	Z
	SET	5,(IX+24)
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.601D:	LD	A,(IX+1)
	AND	0E0H
	LD	B,A
	LD	A,(IX+12)
	OR	B
	LD	L,(IX+22)
	LD	H,(IX+23)
	CALL	C.5486
	PUSH	HL
	PUSH	IX
	CALL	C.552F
	POP	IX
	POP	HL
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$603A:	LD	A,03H	; 3 
	OUT	(34H),A
	LD	BC,I$0C35
	OTIR
	LD	A,0FH	; 15 
	OUT	(34H),A
	LD	A,(IX+1)
	RLCA
	RLCA
	RLCA
	AND	07H	; 7 
	OUT	(35H),A
	LD	A,12H	; 18 
	OUT	(34H),A
	XOR	A
	OUT	(35H),A
	LD	A,(IX+14)
	OUT	(35H),A
	LD	A,(IX+13)
	OUT	(35H),A
	LD	A,(IX+12)
	OUT	(35H),A
	XOR	A
	OUT	(34H),A
	LD	A,(IX+15)
	OUT	(35H),A
	LD	L,(IX+16)
	LD	H,(IX+17)
	CALL	C.6084
	LD	(IX+19),A
	LD	(IX+20),D
	LD	(IX+21),E
	JP	J$6159

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.6084:	IN	A,(34H)
	OR	A
	JP	P,J$6098
	LD	A,17H
	OUT	(34H),A
	DEFB	0,0
	IN	A,(35H)
	OR	A
	CALL	Z,C.614E
	JR	C.6084

J$6098:	AND	30H	; "0"
	JR	NZ,C.6084
	BIT	7,(IX+18)
	JP	NZ,J$6130
	LD	A,(IX+18)
	AND	03H	; 3 
	JR	Z,J$60B2
	DEC	A
	JR	Z,J$60D0
	DEC	A
	JR	Z,J$60F0
	JR	J$6110

J$60B2:	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	DI
J.60BF:	IN	A,(34H)
	RRCA
	JR	NC,J$60C9
	INI
	JP	J.60BF

J$60C9:	AND	40H	; "@"
	JR	Z,J.60BF
	JP	J.6162

J$60D0:	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	DI
J.60DD:	IN	A,(34H)
	RRCA
	JR	NC,J$60E9
	LD	B,10H	; 16 
	INIR
	JP	J.60DD

J$60E9:	AND	40H	; "@"
	JR	Z,J.60DD
	JP	J.6162

J$60F0:	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	DI
J.60FD:	IN	A,(34H)
	RRCA
	JR	NC,J$6109
	LD	B,20H	; " "
	INIR
	JP	J.60FD

J$6109:	AND	40H	; "@"
	JR	Z,J.60FD
	JP	J.6162

J$6110:	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	DI
J.611D:	IN	A,(34H)
	RRCA
	JR	NC,J$6129
	LD	B,40H	; "@"
	INIR
	JP	J.611D

J$6129:	AND	40H	; "@"
	JR	Z,J.611D
	JP	J.6162

J$6130:	LD	A,18H
	OUT	(34H),A
	LD	A,08H	; 8 
	OUT	(35H),A
	LD	A,19H
	OUT	(34H),A
	DI
J.613D:	IN	A,(34H)
	RRCA
	JR	NC,J$6147
	OUTI
	JP	J.613D

J$6147:	AND	40H	; "@"
	JR	Z,J.613D
	JP	J.6162

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.614E:	XOR	A
	OUT	(34H),A
	CALL	C.5935
	OR	08H	; 8 
	JP	J.5799

J$6159:	XOR	A
	OUT	(34H),A
	CALL	C.5935
	JP	J.5799

J.6162:	LD	DE,C.0008
	LD	C,35H	; "5"
J.6167:	IN	A,(34H)
	BIT	0,A
	JP	NZ,J$624C
	BIT	5,A
	JR	NZ,J.6167
	LD	A,17H
	OUT	(34H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(35H)
	BIT	3,A
	JR	NZ,J$61B1
	CP	16H
	JP	Z,J$624F
	BIT	4,A
	RET	NZ
	OR	A
	JP	Z,C.614E
	CP	21H	; "!"
	JR	NZ,J$6192
	PUSH	HL
	POP	IY
	DEC	A
J$6192:	CP	20H	; " "
	JP	Z,J$6234
	CP	85H
	JR	NZ,J$61A0
	BIT	7,D
	RET	Z
	JR	J.6167

J$61A0:	CP	80H
	JR	NZ,J$61A8
	RES	7,D
	JR	J.6167

J$61A8:	BIT	6,A
	JR	NZ,J$61AE
	OUT	(36H),A
J$61AE:	LD	D,02H	; 2 
	RET

J$61B1:	AND	07H	; 7 
	LD	B,A
	LD	A,18H
	OUT	(34H),A
	LD	A,0A0H
	OUT	(35H),A
J$61BC:	IN	A,(34H)
	RRCA
	JR	NC,J$61BC
	LD	A,19H
	OUT	(34H),A
	INC	B
	DJNZ	J$61CC
	OUTI
	JR	J.6167

J$61CC:	DJNZ	J$61D3
	INI
	JP	J.6167

J$61D3:	DJNZ	J$61DB
J$61D5:	XOR	A
	OUT	(35H),A
	JP	J.6167

J$61DB:	DJNZ	J$61E2
	IN	D,(C)
	JP	J.6167

J$61E2:	DJNZ	J$61E7
	JP	J$61D5

J$61E7:	DJNZ	J$61EE
	IN	A,(35H)
	JP	J.6167

J$61EE:	DJNZ	J$61F7
	OUT	(C),E
	LD	E,08H	; 8 
	JP	J.6167

J$61F7:	IN	A,(C)
	JP	Z,J.6167
	JP	M,J.6167
	CP	02H	; 2 
	JR	Z,J$6228
	CP	03H	; 3 
	JR	Z,J$622E
	CP	04H	; 4 
	JR	Z,J$621D
	CP	07H	; 7 
	JR	Z,J.6222
	CP	08H	; 8 
	JP	Z,J.6167
	CP	09H	; 9 
	JR	Z,J.6222
	LD	E,07H	; 7 
	JP	J.6167

J$621D:	SET	7,D
	JP	J.6167

J.6222:	LD	DE,I.0206
	JP	J.6167

J$6228:	PUSH	HL
	POP	IY
	JP	J.6167

J$622E:	PUSH	IY
	POP	HL
	JP	J.6167

J$6234:	LD	A,E
	CP	08H	; 8 
	JR	Z,J$6241
	LD	A,18H
	OUT	(34H),A
	LD	A,02H	; 2 
	OUT	(35H),A
J$6241:	LD	A,18H
	OUT	(34H),A
	LD	A,03H	; 3 
	OUT	(35H),A
	JP	J.6167

J$624C:	JP	J.6167

J$624F:	LD	A,0FH	; 15 
	OUT	(34H),A
	IN	D,(C)
	JP	J.6167

I$6258:	DEC	L
	DAA
I$625A:	JR	J$6268

?.625C:	LD	B,0AH	; 10 
	LD	(BC),A
	INC	C
	INC	C
	INC	C
	INC	C
	INC	C
	INC	C
	INC	C
	INC	C
	INC	C
J$6268:	INC	C
	INC	C
	EX	AF,AF'
	INC	B
	INC	C
	INC	C
	EX	AF,AF'
	LD	B,0CH	; 12 
	RST	38H
	RST	38H
	INC	C
	INC	C
	EX	AF,AF'
	LD	D,0CH	; 12 
	RST	38H
	INC	C
	INC	C
	EX	AF,AF'
	INC	C
	INC	C
	EX	AF,AF'
	LD	(BC),A
	INC	C
	INC	C
	INC	C
	JR	J$629D

I$6285:	DEFB	"SLO"
	DEFB	"W"+128
	DEFW	J.4100

	DEFB	"MEDIU"
	DEFB	"M"+128
	DEFW	J.4104

	DEFB	"FAS"
	DEFB	"T"+128
	DEFW	J.4108

I$6299:	DEFB	"INF"
	DEFB	"O"+128
	DEFW	J.417D

	DEFB	"MAP"
	DEFB	"2"+128
	DEFW	J.4152

	DEFB	"MA"
	DEFB	"P"+128
	DEFW	J.4123

	DEFB	"HOSTI"
	DEFB	"D"+128
	DEFW	J.43C4

	DEFB	"SETHOSTI"
	DEFB	"D"+128
	DEFW	J.43E8

	DEFB	"TARGETI"
	DEFB	"D"+128
	DEFW	J.43FA

	DEFB	"SETTARGETI"
	DEFB	"D"+128
	DEFW	J.441E

	DEFB	"INQUIR"
	DEFB	"Y"+128
	DEFW	J.442C

	DEFB	0

J$6306:	DEC	C
	LD	A,(BC)
	LD	B,E
	LD	L,A
	LD	(HL),B
	LD	A,C
	LD	(HL),D
	LD	L,C
	LD	H,A
	LD	L,B
	LD	(HL),H
	JR	NZ,J$6344
	ADD	HL,SP
	ADD	HL,SP
	INC	(HL)
	DEC	L
	LD	SP,I.3939
	LD	(HL),20H	; " "
	LD	C,E
	LD	C,L
	LD	H,E
	LD	(HL),E
	JR	NZ,J$6351
	JR	NZ,J$6371
	LD	D,E
	LD	E,B
	JR	NZ,J$636B
	LD	L,H
	LD	(HL),L
	LD	H,D
	JR	NZ,J.6374
	LD	L,A
	LD	(HL),L
	LD	H,H
	LD	H,C
	DEC	C
	LD	A,(BC)
	LD	D,A
J$6334:	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	(HL),H
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$639E
J$633B	EQU	$-1
	LD	A,C
	JR	NZ,J.6389
	LD	(HL),L
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	L,(HL)
J$6344:	JR	NZ,J$6391
	LD	(HL),D
J$6347:	LD	H,C
	LD	L,L
	LD	H,L
	LD	(HL),D
	JR	NZ,J$637A
	JR	NZ,J$6390
	LD	(HL),L
	LD	H,A
J$6351:	LD	(HL),L
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J$6388
	DEC	(HL)
	LD	(HL),H
	LD	L,B
	LD	L,20H	; " "
	LD	SP,I.3939
	LD	(HL),20H	; " "
	DEC	L
	DEC	C
	LD	A,(BC)
	DEC	C
	LD	A,(BC)
	LD	C,B
	LD	H,C
	LD	(HL),D
	LD	H,H
	LD	(HL),A
	LD	H,C
J$636B:	LD	(HL),D
	LD	H,L
	JR	NZ,J$63D1
	LD	A,C
	JR	NZ,J$63BA
J$6371	EQU	$-1
	LD	L,47H	; "G"
J.6374:	LD	L,20H	; " "
	LD	SP,I.3939
	INC	SP
J$637A:	LD	L,20H	; " "
	HALT

?.637D:	LD	H,L
	LD	(HL),D
	LD	(HL),E
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$63B6
	LD	L,31H	; "1"
	DEC	C
J$6388:	LD	A,(BC)
J.6389:	DEC	C
	LD	A,(BC)
	LD	A,(BC)
	NOP
I$638D:	LD	C,B
	LD	L,A
	LD	(HL),E
J$6390:	LD	(HL),H
J$6391:	JR	NZ,J$63DC
	LD	B,H
	LD	A,(X.0020)
I$6397:	INC	L
	JR	NZ,J$63EE
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	H,L
J$639E:	LD	(HL),H
	JR	NZ,J$63EA
	LD	B,H
	LD	A,(X.0020)
I$63A5:	DEC	C
	LD	A,(BC)
	LD	C,B
	LD	L,C
	LD	(HL),H
	JR	NZ,J$63E8
	LD	B,H
	LD	B,L
	LD	C,H
	LD	A,20H	; " "
	LD	(HL),H
	LD	L,A
	JR	NZ,J.6427
	LD	(HL),L
J$63B6:	LD	L,(HL)
	JR	NZ,J.640C
	LD	B,L
J$63BA:	LD	D,H
	LD	D,L
	LD	D,B
	NOP
I$63BE:	LD	C,(HL)
	LD	C,A
	LD	D,(HL)
	LD	B,C
	LD	E,B
	LD	C,C
	LD	D,E
	JR	NZ,J$6408
	LD	D,E
	LD	D,B
	LD	C,C
	JR	NZ,J$6442
	LD	H,L
	LD	(HL),D
	LD	(HL),E
	LD	L,C
	LD	L,A
J$63D1:	LD	L,(HL)
	JR	NZ,J.63D4
J.63D4:	LD	C,C
	LD	B,H
	JR	NZ,J.63FB
	NOP
I$63D9:	JR	NZ,J.63FB
	DEC	L
J$63DC:	JR	NZ,J$6422
	LD	L,C
	LD	(HL),D
	LD	H,L
	LD	H,E
	LD	(HL),H
	JR	NZ,J$6426
	LD	H,E
	LD	H,E
	LD	H,L
J$63E8:	LD	(HL),E
	LD	(HL),E
J$63EA:	JR	NZ,J$6430
	LD	H,L
	HALT

J$63EE:	LD	L,C
	LD	H,E
	LD	H,L
	NOP
	JR	NZ,J$6414
	DEC	L
	JR	NZ,J$644B
	LD	H,C
	LD	(HL),B
	LD	H,L
	JR	NZ,J.646F
J.63FB	EQU	$-1
	LD	(HL),H
	LD	(HL),D
	LD	H,L
	LD	H,C
	LD	L,L
	LD	H,L
	LD	(HL),D
	JR	NZ,J$6425
	JR	NZ,J.6427
	JR	NZ,J$6429
J$6408	EQU	$-1
	JR	NZ,J$640B
J$640B:	JR	NZ,J$642D
J.640C	EQU	$-1
	DEC	L
	JR	NZ,J$6460
	LD	(HL),D
	LD	L,C
	LD	L,(HL)
	LD	(HL),H
J$6414:	LD	H,L
	LD	(HL),D
	JR	NZ,J$647C
	LD	H,L
	HALT

?.641A:	LD	L,C
	LD	H,E
	LD	H,L
	JR	NZ,J$643F
	JR	NZ,J$6441
	JR	NZ,J$6443
J$6422	EQU	$-1
	NOP
	JR	NZ,J$6446
J$6425	EQU	$-1
J$6426:	DEC	L
J.6427:	JR	NZ,J$6479
J$6429:	LD	(HL),D
	LD	L,A
	LD	H,E
	LD	H,L
J$642D:	LD	(HL),E
	LD	(HL),E
	LD	L,A
J$6430:	LD	(HL),D
	JR	NZ,J$6497
	LD	H,L
	HALT

?.6435:	LD	L,C
	LD	H,E
	LD	H,L
	JR	NZ,J$645A
	JR	NZ,J$645C
	NOP
	JR	NZ,J$645F
J$643F:	DEC	L
	JR	NZ,J$6499
J$6441	EQU	$-1
J$6442:	LD	C,A
J$6443:	LD	D,D
	LD	C,L
	JR	NZ,J$6467
J$6446	EQU	$-1
	JR	NZ,J$6469
	JR	NZ,J$646B
J$644B:	JR	NZ,J$646D
	JR	NZ,J.646F
	JR	NZ,J$6471
	JR	NZ,J$6473
	JR	NZ,J$6475
	NOP
	JR	NZ,J$6478
	DEC	L
	JR	NZ,J.649E
J$645A	EQU	$-1
	LD	B,H
J$645C:	DEC	L
	LD	D,D
	LD	C,A
J$645F:	LD	C,L
J$6460:	JR	NZ,J$6482
	JR	NZ,J$6484
	JR	NZ,J$6486
	JR	NZ,J.6488
J$6467	EQU	$-1
	JR	NZ,J$648A
J$6469	EQU	$-1
	JR	NZ,J$648C
J$646B	EQU	$-1
	JR	NZ,J$648E
J$646D	EQU	$-1
	NOP
J.646F:	JR	NZ,J$6491
J$6471:	DEC	L
	JR	NZ,J$64C7
J$6473	EQU	$-1
	LD	H,E
J$6475:	LD	H,C
	LD	L,(HL)
	LD	L,(HL)
J$6478:	LD	H,L
J$6479:	LD	(HL),D
	JR	NZ,J$649C
J$647C:	JR	NZ,J.649E
	JR	NZ,J$64A0
	JR	NZ,J$64A2
J$6482:	JR	NZ,J$64A4
J$6484:	JR	NZ,J$64A6
J$6486:	JR	NZ,J.6488
J.6488:	JR	NZ,J$64AA
J$648A:	DEC	L
	JR	NZ,J.64DC
J$648C	EQU	$-1
	LD	(HL),B
J$648E:	LD	(HL),H
	LD	L,C
	LD	H,E
J$6491:	LD	H,C
	LD	L,H
	JR	NZ,J$64F9
	LD	H,L
	HALT

J$6497:	LD	L,C
	LD	H,E
J$6499:	LD	H,L
	JR	NZ,J$64BC
J$649C:	JR	NZ,J$64BE
J.649E:	JR	NZ,J$64C0
J$64A0:	NOP
	JR	NZ,J$64C3
J$64A2	EQU	$-1
	DEC	L
J$64A4:	JR	NZ,J.64F3
J$64A6:	LD	H,L
	LD	H,H
	LD	L,C
	LD	(HL),L
J$64AA:	LD	L,L
	JR	NZ,J$6510
	LD	L,B
	LD	H,C
	LD	L,(HL)
	LD	H,A
	LD	H,L
	LD	(HL),D
	JR	NZ,J$64D5
	JR	NZ,J$64D7
	JR	NZ,J$64D9
	NOP
	JR	NZ,J.64DC
J$64BC:	DEC	L
	JR	NZ,J.6502
J$64BE	EQU	$-1
	LD	L,A
J$64C0:	LD	L,L
	LD	L,L
	LD	(HL),L
J$64C3:	LD	L,(HL)
	LD	L,C
	LD	H,E
	LD	H,C
J$64C7:	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J.6531
	LD	H,L
	HALT

?.64CF:	LD	L,C
	LD	H,E
	LD	H,L
	NOP
	JR	NZ,J$64F5
J$64D5:	DEC	L
	JR	NZ,J$652D
J$64D7	EQU	$-1
	LD	L,(HL)
J$64D9:	LD	L,E
	LD	L,(HL)
	LD	L,A
J.64DC:	LD	(HL),A
	LD	L,(HL)
	JR	NZ,J$6544
	LD	H,L
	HALT

?.64E2:	LD	L,C
	LD	H,E
	LD	H,L
	JR	NZ,J$655B
	LD	A,C
	LD	(HL),B
	LD	H,L
	JR	NZ,J.64EC
J.64EC:	DEC	C
	LD	A,(BC)
	NOP
I$64EF:	JR	NZ,J$651E
	JR	NZ,J.64F3
I$64F2	EQU	$-1
J.64F3:	DEC	L
	DEC	C
J$64F5:	LD	A,(BC)
	NOP
I$64F7:	LD	D,D
	LD	H,L
J$64F9:	HALT

?.64FA:	LD	L,C
	LD	(HL),E
	LD	L,C
	LD	L,A
	LD	L,(HL)
	LD	A,(X.0020)
J.6502:	JR	NZ,J.6531
	JR	NZ,J$6558
	LD	C,L
	LD	B,D
	NOP
I$6509:	LD	D,A
	LD	H,C
	LD	L,C
	LD	(HL),H
	LD	L,2EH	; "."
	LD	L,00H
J$6510	EQU	$-1
I$6511:	INC	C
	RST	38H
	DJNZ	J$6516
	LD	C,(HL)
J$6516:	LD	C,A
	LD	D,(HL)
	LD	B,C
	LD	E,B
	LD	C,C
	LD	D,E
	JR	NZ,J$6571
J$651E:	LD	H,L
	LD	(HL),H
	LD	(HL),L
	LD	(HL),B
	JR	NZ,J$659A
	LD	H,L
	LD	(HL),D
	LD	(HL),E
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$655D
	LD	L,30H	; "0"
J$652D	EQU	$-1
	JR	C,J$6550
	JR	Z,J$6575
J.6531	EQU	$-1
	ADD	HL,HL
	JR	NZ,J$6566
	ADD	HL,SP
	ADD	HL,SP
	INC	(HL)
	DEC	L
	LD	SP,I.3939
	LD	(HL),20H	; " "
	LD	C,E
	LD	C,L
	LD	H,E
	LD	(HL),E
	RST	38H
	LD	D,02H	; 2 
J$6544	EQU	$-1
	LD	D,A
	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	(HL),H
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$65B0
	LD	A,C
	JR	NZ,J$659B
J$6550	EQU	$-1
	LD	(HL),L
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$65A3
J$6558:	LD	(HL),D
	LD	H,C
	LD	L,L
J$655B:	LD	H,L
	LD	(HL),D
J$655D:	JR	NZ,J$658C
	JR	NZ,J$6593
	DEC	(HL)
	CPL
	JR	NC,J$659D
	CPL
J$6566:	ADD	HL,SP
	LD	(HL),20H	; " "
	DEC	L
	RST	38H
	INC	BC
	ADD	HL,BC
	LD	E,E
	LD	C,B
	LD	E,L
	JR	NZ,J$659F
J$6571	EQU	$-1
	JR	NZ,J$65BC
	LD	L,A
J$6575:	LD	(HL),E
	LD	(HL),H
	JR	NZ,J$65C2
	LD	B,H
	JR	NZ,J$659C
	JR	NZ,J$659E
	JR	NZ,J$65A0
	JR	NZ,J$65A2
	JR	NZ,J$65A4
	JR	NZ,J$65A6
	JR	NZ,J$65A8
	LD	A,(D.2BFF)
	ADD	HL,BC
J$658C:	LD	E,E
	LD	D,H
	LD	E,L
	JR	NZ,J$65BE
	JR	NZ,J$65E7
J$6593:	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	(HL),H
	JR	NZ,J$65E3
J$659A:	LD	B,H
J$659B:	JR	NZ,J$65BD
J$659C	EQU	$-1
J$659D:	JR	NZ,J$65BF
J$659E	EQU	$-1
J$659F:	JR	NZ,J$65C1
J$65A0	EQU	$-1
	JR	NZ,J$65C3
J$65A2	EQU	$-1
J$65A3:	JR	NZ,J$65C5
J$65A4	EQU	$-1
	JR	NZ,J$65C7
J$65A6	EQU	$-1
	LD	A,(D.2BFF)
J$65A8	EQU	$-2
	LD	A,(BC)
	LD	E,E
	LD	B,C
	LD	E,L
	JR	NZ,J$65DD
J$65B0:	JR	NZ,J$6600
	LD	B,C
	LD	D,E
	LD	D,B
	LD	C,C
	JR	NZ,J$662B
	LD	(HL),L
	LD	(HL),B
	LD	(HL),B
	LD	L,A
J$65BC:	LD	(HL),D
J$65BD:	LD	(HL),H
J$65BE:	JR	NZ,J$65E0
J$65BF	EQU	$-1
	JR	NZ,J$65E2
J$65C1	EQU	$-1
J$65C2:	JR	NZ,J$65E4
J$65C3	EQU	$-1
	JR	NZ,J$65E6
J$65C5	EQU	$-1
	LD	A,(D$03FF)
J$65C7	EQU	$-2
	LD	A,(BC)
	LD	E,E
	LD	C,L
	LD	E,L
	JR	NZ,J$65FC
	JR	NZ,J$661E
	LD	(HL),L
	LD	L,H
	LD	(HL),H
	LD	L,C
	LD	(HL),B
	LD	L,H
	LD	H,L
	JR	NZ,J$6622
	LD	B,H
	LD	B,H
	JR	NZ,J$6651
J$65DD	EQU	$-1
	LD	(HL),L
	LD	(HL),B
J$65E0:	LD	(HL),B
	LD	L,A
J$65E2:	LD	(HL),D
J$65E3:	LD	(HL),H
J$65E4:	JR	NZ,J$6620
J$65E6:	RST	38H
J$65E7:	INC	BC
	DEC	BC
	LD	E,E
	LD	B,L
	LD	E,L
	JR	NZ,J$661B
	JR	NZ,J$6635
	LD	A,B
	LD	(HL),H
	LD	H,L
	LD	L,(HL)
	LD	H,H
	LD	H,L
	LD	H,H
	JR	NZ,J.6649
	LD	H,C
	LD	(HL),D
	LD	(HL),H
J$65FC:	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,A
J$6600:	LD	L,(HL)
	LD	(HL),E
	JR	NZ,J$6624
	LD	A,(D.2BFF)
	INC	C
	LD	E,E
	LD	D,D
	LD	E,L
	JR	NZ,J$663A
	JR	NZ,J$6661
	LD	H,L
	LD	(HL),E
	LD	H,E
	LD	H,C
	LD	L,(HL)
	RST	38H
	INC	BC
	LD	C,5BH	; "["
	LD	D,C
	LD	E,L
	JR	NZ,J.6649
J$661B	EQU	$-1
	JR	NZ,J.666F
J$661E:	LD	(HL),L
	LD	L,C
J$6620:	LD	(HL),H
	JR	NZ,J$669A
J$6622	EQU	$-1
	LD	L,C
J$6624:	LD	(HL),H
	LD	L,B
	LD	L,A
I$6627:	LD	(HL),L
	LD	(HL),H
	JR	NZ,J.669E
J$662B:	LD	H,C
	HALT

?.662D:	LD	H,L
	RST	38H
	DEC	HL
	LD	C,5BH	; "["
	LD	D,E
	LD	E,L
	JR	NZ,J$6663
J$6635	EQU	$-1
	JR	NZ,J$668B
	LD	H,C
	HALT

J$663A:	LD	H,L
	JR	NZ,J.669E
	LD	L,(HL)
	LD	H,H
	JR	NZ,J$66B2
	LD	(HL),L
	LD	L,C
	LD	(HL),H
	RST	38H
	INC	A
	LD	(DE),A
	LD	C,C
	LD	B,H
J.6649:	JR	NZ,J$666E
	LD	A,(D$3020)
	JR	NZ,J$6681
	JR	NZ,J$6684
J$6651	EQU	$-1
	JR	NZ,J$6687
	JR	NZ,J.668A
	JR	NZ,J$668D
	JR	NZ,J$6690
	JR	NZ,J$6693
	NOP
I$665D:	RST	38H
	LD	BC,I$5512
J$6661:	LD	L,(HL)
	LD	L,C
J$6663:	LD	(HL),H
	LD	(HL),E
	JR	NZ,J.66D6
	LD	L,(HL)
	LD	L,H
	LD	L,C
	LD	L,(HL)
	LD	H,L
	LD	A,(X.0020)
J$666E	EQU	$-1
J.666F:	RST	38H
	LD	BC,I$4314
	LD	(HL),L
	LD	(HL),D
	LD	(HL),D
	LD	H,L
	LD	L,(HL)
	LD	(HL),H
	JR	NZ,J$66CF
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	(HL),H
	LD	A,(D.2020)
J$6681	EQU	$-2
	JR	NZ,J.66A5
J$6684	EQU	$-1
	JR	NZ,J$66A7
J$6687:	JR	NZ,J$66A9
	JR	NZ,J.668A
J.668A	EQU	$-1
J$668B:	LD	DE,I$0014
J$668D	EQU	$-1
I$668E:	RST	38H
	DEC	DE
J$6690:	INC	D
	JR	NZ,J$66B3
J$6693:	JR	NZ,J$66B5
	JR	NZ,J$66B7
	JR	NZ,J$66B9
	JR	NZ,J$66BB
J$669A	EQU	$-1
	JR	NZ,J$66BD
	JR	NZ,J$66BF
J.669E	EQU	$-1
	JR	NZ,J.66C1
	RST	38H
	DEC	DE
	INC	D
	NOP
J.66A5:	LD	C,A
	LD	H,(HL)
J$66A7:	LD	H,(HL)
	LD	L,H
J$66A9:	LD	L,C
	LD	L,(HL)
	LD	H,L
	JR	NZ,J$66CE
	JR	NZ,J$66D0
	JR	NZ,J.66D2
J$66B2:	JR	NZ,J$66D4
J$66B3	EQU	$-1
	JR	NZ,J.66D6
J$66B5	EQU	$-1
	JR	NZ,J$66D8
J$66B7	EQU	$-1
	JR	NZ,J$66DA
J$66B9	EQU	$-1
	JR	NZ,J$66DC
J$66BB	EQU	$-1
	JR	NZ,J$66DE
J$66BD	EQU	$-1
	JR	NZ,J$66E0
J$66BF	EQU	$-1
	NOP
J.66C1:	RST	38H
	DEC	L
	INC	D
	LD	B,H
	LD	H,L
	HALT

?.66C7:	LD	L,C
	LD	H,E
	LD	H,L
	JR	NZ,J.6740
	LD	A,C
	LD	(HL),B
J$66CE:	LD	H,L
J$66CF:	LD	A,(X.0020)
J$66D0	EQU	$-2
J.66D2:	LD	B,H
	LD	L,C
J$66D4:	LD	(HL),E
	LD	H,C
J.66D6:	LD	H,D
	LD	L,H
J$66D8:	LD	H,L
	LD	H,H
J$66DA:	NOP
I.66DB:	LD	B,L
J$66DC:	LD	L,(HL)
	LD	H,C
J$66DE:	LD	H,D
	LD	L,H
J$66E0:	LD	H,L
	LD	H,H
	JR	NZ,J.66E4
J.66E4:	RST	38H
	LD	BC,I.4516
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$675C
	LD	H,L
	LD	(HL),A
	JR	NZ,J$673A
	LD	L,A
	LD	(HL),E
	LD	(HL),H
	JR	NZ,J.6740
	LD	B,H
	JR	NZ,J$6722
	INC	(HL)
	JR	NZ,J$672A
	JR	NZ,J$6736
	ADD	HL,HL
	NOP
I$6701:	RST	38H
	LD	BC,I.4516
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$6779
	LD	H,L
	LD	(HL),A
	JR	NZ,J$6763
	LD	H,C
	LD	(HL),D
	LD	H,A
	LD	H,L
	LD	(HL),H
	JR	NZ,J$675F
	LD	B,H
	JR	NZ,J$6741
	JR	NC,J$673B
	DEC	L
	JR	NZ,J$6755
	ADD	HL,HL
	NOP
I$6720:	RST	38H
	LD	BC,I$4916
J$6722	EQU	$-2
	LD	L,(HL)
	LD	(HL),B
	LD	(HL),L
	LD	(HL),H
	JR	NZ,J$6764
J$672A:	JR	NZ,J.672C
J.672C:	RST	38H
	LD	BC,I.4E18
	LD	B,C
	LD	D,E
	LD	D,B
	LD	C,C
	JR	NZ,J$67A9
J$6736:	LD	(HL),L
	LD	(HL),B
	LD	(HL),B
	LD	L,A
J$673A:	LD	(HL),D
J$673B:	LD	(HL),H
	JR	NZ,J$67AE
	LD	(HL),D
	LD	L,A
J.6740:	HALT

J$6741:	LD	L,C
	LD	H,H
	LD	H,L
	LD	(HL),E
	JR	NZ,J$67A8
	LD	L,(HL)
	JR	NZ,J$6793
	CPL
	LD	C,A
	JR	NZ,J$67B7
	LD	L,(HL)
	LD	H,H
	LD	H,L
	LD	(HL),B
	LD	H,L
	LD	L,(HL)
	LD	H,H
J$6755:	LD	H,L
	LD	L,(HL)
	LD	(HL),H
	JR	NZ,J$67CA
	LD	(HL),D
	LD	L,A
J$675C:	LD	H,A
	LD	(HL),D
	LD	H,C
J$675F:	LD	L,L
	LD	L,L
	LD	L,C
	LD	L,(HL)
J$6763:	LD	H,A
J$6764:	JR	NZ,J$67CF
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	LD	H,(HL)
	LD	H,C
	LD	H,E
	LD	H,L
	JR	NZ,J$6790
	JR	NZ,J$6792
	JR	NZ,J$6794
	JR	NZ,J$6796
	JR	NZ,J$6798
	JR	NZ,J$679A
J$6779	EQU	$-1
	JR	NZ,J$679C
	NOP
I$677D:	RST	38H
	LD	BC,I.4E18
	LD	B,C
	LD	D,E
	LD	D,B
	LD	C,C
	JR	NZ,J$67FA
	LD	(HL),L
	LD	(HL),B
	LD	(HL),B
	LD	L,A
	LD	(HL),D
	LD	(HL),H
	LD	A,(D.7720)
J$6790:	LD	L,B
	LD	H,L
J$6792:	LD	L,(HL)
J$6793:	JR	NZ,J$67F9
J$6794	EQU	$-1
	LD	L,C
J$6796:	LD	(HL),E
	LD	H,C
J$6798:	LD	H,D
	LD	L,H
J$679A:	LD	H,L
	LD	H,H
J$679C:	JR	NZ,J$6817
	LD	L,A
	LD	(HL),L
	JR	NZ,J$6805
	LD	H,C
	LD	L,(HL)
	LD	L,(HL)
	LD	L,A
	LD	(HL),H
	JR	NZ,J$681E
J$67A8	EQU	$-1
J$67A9:	LD	(HL),E
	LD	H,L
	JR	NZ,J$681D
	LD	(HL),D
J$67AE:	LD	L,A
	LD	H,A
	LD	(HL),D
	LD	H,C
	LD	L,L
	LD	(HL),E
	JR	NZ,J$682D
	LD	(HL),D
J$67B7:	LD	L,C
	LD	(HL),H
	LD	(HL),H
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$6824
	LD	L,A
	LD	(HL),D
	JR	NZ,J$682B
	LD	(HL),H
	JR	NZ,J$67E5
	JR	NZ,J$67E7
	JR	NZ,J$67E9
	JR	NZ,J$67EB
J$67CA	EQU	$-1
	JR	NZ,J$67ED
	NOP
I$67CE:	RST	38H
J$67CF:	LD	BC,I.4D18
I$67D0	EQU	$-2
	LD	(HL),L
	LD	L,H
	LD	(HL),H
	LD	L,C
	LD	(HL),B
	LD	L,H
	LD	H,L
	JR	NZ,J$6823
	LD	B,H
	LD	B,H
	LD	A,(D.7720)
	LD	L,B
	LD	H,L
	LD	L,(HL)
	JR	NZ,J.684A
J$67E5:	LD	L,(HL)
	LD	H,C
J$67E7:	LD	H,D
	LD	L,H
J$67E9:	LD	H,L
	LD	H,H
J$67EB:	JR	NZ,J$684E
J$67ED:	LD	L,H
	LD	L,H
	JR	NZ,J$6860
	LD	L,(HL)
	LD	L,H
	LD	L,C
	LD	L,(HL)
	LD	H,L
	JR	NZ,J$683C
	LD	L,C
J$67F9:	LD	(HL),D
J$67FA:	LD	H,L
	LD	H,E
	LD	(HL),H
	JR	NZ,J$6840
	LD	H,E
	LD	H,E
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J.684A
J$6805	EQU	$-1
	LD	H,L
	HALT

?.6808:	LD	L,C
	LD	H,E
	LD	H,L
	LD	(HL),E
	JR	NZ,J$6885
	LD	L,C
	LD	L,H
	LD	L,H
	JR	NZ,J$6875
	LD	H,L
	JR	NZ,J$687F
	LD	L,(HL)
J$6817:	LD	(HL),E
	LD	(HL),H
	LD	H,C
	LD	L,H
	LD	L,H
	LD	H,L
J$681D:	LD	H,H
J$681E:	NOP
I$681F:	RST	38H
	LD	BC,I.4D18
J$6823:	LD	(HL),L
J$6824:	LD	L,H
	LD	(HL),H
	LD	L,C
	LD	(HL),B
	LD	L,H
	LD	H,L
	JR	NZ,J$6874
J$682B	EQU	$-1
	LD	B,H
J$682D:	LD	B,H
	LD	A,(D.7720)
	LD	L,B
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$689A
	LD	L,C
	LD	(HL),E
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
J$683C:	LD	H,H
	JR	NZ,J$68AE
	LD	L,(HL)
J$6840:	LD	L,H
	LD	A,C
	JR	NZ,J$68B8
	LD	L,B
	LD	H,L
	JR	NZ,J$689C
	LD	H,C
	LD	(HL),D
J.684A:	LD	H,A
	LD	H,L
	LD	(HL),H
	JR	NZ,J$68C8
J$684E	EQU	$-1
	LD	L,A
	LD	(HL),L
	DAA
	HALT

?.6853:	LD	H,L
	JR	NZ,J$68C9
	LD	H,L
	LD	L,H
	LD	H,L
	LD	H,E
	LD	(HL),H
	LD	H,L
	LD	H,H
	JR	NZ,J$68D6
	LD	L,C
J$6860:	LD	L,H
	LD	L,H
	JR	NZ,J$68C6
	LD	H,L
	JR	NZ,J$68D0
	LD	L,(HL)
	LD	(HL),E
	LD	(HL),H
	LD	H,C
	LD	L,H
	LD	L,H
	LD	H,L
	LD	H,H
	NOP
I$6870:	RST	38H
	LD	BC,I.4518
J$6874:	LD	A,B
J$6875:	LD	(HL),H
	LD	H,L
	LD	L,(HL)
	LD	H,H
	LD	H,L
	LD	H,H
	JR	NZ,J$68CD
	LD	H,C
	LD	(HL),D
J$687F:	LD	(HL),H
	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
J$6885:	LD	(HL),E
	LD	A,(D.7720)
	LD	L,B
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$68F3
	LD	L,(HL)
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	LD	H,H
	JR	NZ,J$690F
	LD	L,A
	LD	(HL),L
	JR	NZ,J$68FD
J$689A:	LD	H,C
	LD	L,(HL)
J$689C:	JR	NZ,J$6913
	LD	(HL),E
	LD	H,L
	JR	NZ,J$6917
	LD	(HL),B
	JR	NZ,J$6919
	LD	L,A
	JR	NZ,J$68D9
	DEC	(HL)
	JR	NZ,J$691B
	LD	H,C
	LD	(HL),D
	LD	(HL),H
J$68AE:	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
	LD	(HL),E
	JR	NZ,J$6926
	LD	H,L
	LD	(HL),D
J$68B8:	JR	NZ,J.691E
	LD	(HL),D
	LD	L,C
	HALT

?.68BD:	LD	H,L
	JR	NZ,J$68E0
	NOP
I$68C1:	RST	38H
	LD	BC,I.4518
	LD	A,B
J$68C6:	LD	(HL),H
	LD	H,L
J$68C8:	LD	L,(HL)
J$68C9:	LD	H,H
	LD	H,L
	LD	H,H
	JR	NZ,J.691E
J$68CD	EQU	$-1
	LD	H,C
	LD	(HL),D
J$68D0:	LD	(HL),H
	LD	L,C
	LD	(HL),H
	LD	L,C
	LD	L,A
	LD	L,(HL)
J$68D6:	LD	(HL),E
	LD	A,(D.7720)
J$68D9	EQU	$-1
	LD	L,B
	LD	H,L
	LD	L,(HL)
	JR	NZ,J$6943
	LD	L,C
J$68E0:	LD	(HL),E
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	LD	H,H
	JR	NZ,J$6961
	LD	L,A
	LD	(HL),L
	JR	NZ,J$694F
	LD	H,C
	LD	L,(HL)
	JR	NZ,J$695F
	LD	L,(HL)
	LD	L,H
	LD	A,C
J$68F3:	JR	NZ,J$696A
	LD	(HL),E
	LD	H,L
	JR	NZ,J$696E
	LD	(HL),B
	JR	NZ,J$6970
	LD	L,A
J$68FD:	JR	NZ,J$6935
	JR	NZ,J$6971
	LD	H,C
	LD	(HL),D
	LD	(HL),H
	LD	L,20H	; " "
	LD	(HL),B
	LD	H,L
	LD	(HL),D
	JR	NZ,J$696F
	LD	(HL),D
	LD	L,C
	HALT

?.690E:	LD	H,L
J$690F:	JR	NZ,J$6931
	NOP
I.6912:	RST	38H
J$6913:	LD	BC,I$0D18
	DEC	DE
J$6917:	LD	C,E
	NOP
J$6919:	INC	BC
	NOP
J$691B:	LD	BC,I$1F00
J.691E:	DEFB	0,0,0
I$6921:	LD	C,E
	LD	C,L
	LD	H,E
	LD	(HL),E
	JR	NZ,J$6947
J$6926	EQU	$-1
	JR	NZ,J$6949
	LD	C,(HL)
	LD	C,A
	LD	D,(HL)
	LD	B,C
	LD	E,B
	LD	C,C
	LD	D,E
	JR	NZ,J$6985
J$6931	EQU	$-1
	LD	B,E
	LD	D,E
	LD	C,C
J$6935:	JR	NZ,J$6957
	JR	NZ,J$6959
	DEC	L
	JR	NZ,J$695C
	JR	NZ,J$693E
I$693D	EQU	$-1
J$693E:	DEFB	0,0,0,0,0
J$6943:	DEFB	0,0,0,0
J$6947:	DEFB	0,0
J$6949:	DEFB	0,0,0,0,0,0
J$694F:	DEFB	0,0,0,0,0,0,0,0
J$6957:	DEFB	0,0
J$6959:	DEFB	0,0,0
J$695C:	DEFB	0,0,0
J$695F:	DEFB	0,0
J$6961:	DEFB	0,0,0,0,0,0,0,0,0
J$696A:	DEFB	0,0,0,0
J$696E:	DEFB	0
J$696F:	DEFB	0
J$6970:	DEFB	0
J$6971:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J$6985:	DEFB	0,0,0,0,0,0,0,0
	DJNZ	J$6A0F
	NOP
	LD	BC,I.1000
	ADD	A,B
	NOP
	LD	BC,I.1000
	ADD	A,B
	NOP
	LD	BC,I.10FE
	LD	B,B
	NOP
	LD	BC,I.10FE
	ADD	A,B
	NOP
	LD	BC,I$00FE
	DEFB	0,0,0,0,0,0,0,0,0
	DJNZ	J$6A32
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0
	DJNZ	J$6A41
	DEFB	0,0,0
	DJNZ	J$6A46
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0
	LD	(BC),A
	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
	RET	NZ
	NOP
	LD	A,A
	RST	38H
	RET	M
I$6A05:	DEFB	0,0,0,0,0,0,0,0,0,0
J$6A0F:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
	RST	38H
I$6A2D:	LD	B,B
	NOP
	DJNZ	J$6A31
J$6A31:	INC	B
J$6A32:	NOP
	LD	BC,I.0000
	LD	B,B
	NOP
	DJNZ	J$6A3A
J$6A3A:	INC	B
	NOP
	LD	BC,I.0100
	LD	(BC),A
	INC	BC
J$6A41:	INC	B
	DEC	B
	LD	B,80H
	LD	BC,I.0200
J$6A46	EQU	$-2
	INC	BC
	INC	B
	DEC	B
	LD	B,80H
	LD	(BC),A
	NOP
	LD	BC,I.0403
	DEC	B
	LD	B,80H
	INC	BC
	NOP
	LD	BC,I.0402
	DEC	B
	LD	B,80H
	INC	B
	NOP
	LD	BC,I.0302
	DEC	B
	LD	B,80H
	DEC	B
	NOP
	LD	BC,I.0302
	INC	B
	LD	B,80H
	LD	B,00H
	LD	BC,I.0302
	INC	B
	DEC	B
	ADD	A,B
	NOP
	LD	BC,I.0302
	INC	B
	DEC	B
	RLCA
	ADD	A,B
	LD	BC,I.0200
	INC	BC
	INC	B
	DEC	B
	RLCA
	ADD	A,B
	LD	(BC),A
	NOP
	LD	BC,I.0403
	DEC	B
	RLCA
	ADD	A,B
	INC	BC
	NOP
	LD	BC,I.0402
	DEC	B
	RLCA
	ADD	A,B
	INC	B
	NOP
	LD	BC,I.0302
	DEC	B
	RLCA
	ADD	A,B
	DEC	B
	NOP
	LD	BC,I.0302
	INC	B
	RLCA
	ADD	A,B
	RLCA
	NOP
	LD	BC,I.0302
	INC	B
	DEC	B
	ADD	A,B
	NOP
	LD	BC,I.0302
	INC	B
	LD	B,07H	; 7 
	ADD	A,B
	LD	BC,I.0200
	INC	BC
	INC	B
	LD	B,07H	; 7 
	ADD	A,B
	LD	(BC),A
	NOP
	LD	BC,I.0403
	LD	B,07H	; 7 
	ADD	A,B
	INC	BC
	NOP
	LD	BC,I.0402
	LD	B,07H	; 7 
	ADD	A,B
	INC	B
	NOP
	LD	BC,I.0302
	LD	B,07H	; 7 
	ADD	A,B
	LD	B,00H
	LD	BC,I.0302
	INC	B
	RLCA
	ADD	A,B
	RLCA
	NOP
	LD	BC,I.0302
	INC	B
	LD	B,80H
	NOP
	LD	BC,I.0302
	DEC	B
	LD	B,07H	; 7 
	ADD	A,B
	LD	BC,I.0200
	INC	BC
	DEC	B
	LD	B,07H	; 7 
	ADD	A,B
	LD	(BC),A
	NOP
	LD	BC,I$0503
	LD	B,07H	; 7 
	ADD	A,B
	INC	BC
	NOP
	LD	BC,I$0502
	LD	B,07H	; 7 
	ADD	A,B
	DEC	B
	NOP
	LD	BC,I.0302
	LD	B,07H	; 7 
	ADD	A,B
	LD	B,00H
	LD	BC,I.0302
	DEC	B
	RLCA
	ADD	A,B
I$6B15:	NOP
	ADD	A,B
	LD	BC,I$0280
	ADD	A,B
	INC	BC
	ADD	A,B
	INC	B
	ADD	A,B
	DEC	B
	ADD	A,B
	LD	B,80H
	RLCA
	ADD	A,B
D$6B25:	INC	D
	ADC	A,C

	DEFS	07E00H-$,0FFH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$7E00:	LD	A,H
	CP	40H	; "@"
	RET	NZ
	LD	A,(D.FBEB)
	BIT	2,A
	RET	NZ
	LD	HL,I$7E6D
	CALL	C.7E64
J$7E10:	LD	A,(D.FBEB)
	BIT	2,A
	JR	Z,J$7E10
	LD	A,(D.F3DC)
	DEC	A
	LD	(D.F3DC),A
	LD	B,00H
J$7E20:	LD	A,(D.FBED)
	BIT	4,A
	CALL	Z,C$7E4A
	LD	A,(D.FBED)
	BIT	7,A
	CALL	Z,C$7E57
	LD	A,(D.FBEB)
	BIT	2,A
	JR	NZ,J$7E20
	LD	A,(D.F3DC)
	INC	A
	INC	A
	LD	(D.F3DC),A
	XOR	A
	LD	(D.F3DD),A
	XOR	A
	CP	B
	JP	NZ,J.4722
	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$7E4A:	LD	B,00H
	LD	HL,I$7EA7
	LD	A,16H
	LD	(D.F3DD),A
	JP	C.7E64

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$7E57:	LD	B,01H	; 1 
	LD	HL,I$7EAF
	LD	A,16H
	LD	(D.F3DD),A
	JP	C.7E64

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C.7E64:	LD	A,(HL)
	OR	A
	RET	Z
	CALL	C$00A2
	INC	HL
	JR	C.7E64

I$7E6D:	DEFB	"Novaxis SCSI will be disable",13,10
	DEFB	"if you press <GRAPH> again."
	DEFB	0

I$7EA7:	DEFB	"disable"
	DEFB	0

I$7EAF:	DEFB	"enable "
	DEFB	0

	DEFS	07F00H-$,0FFH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
C$7F00:	CALL	C.5BD0
J.7F03:	LD	A,(D.FBED)
	BIT	3,A
J$7F08:	JR	Z,J.7F03
	HALT
?.7F0B:	RET

	DEFS	07F80H-$,0FFH

I$7F80:	DEFB	"HD"
	DEFB	023H
	JP	C.578A			; SetWD3393
?.7F86:	JP	J.5651			; TermAct
?.7F89:	JP	C.5209			; RdLogBlk
?.7F8C:	JP	C.534B			; WrLogBlk
?.7F8F:	JP	C.5443			; ReqSense
?.7F92:	JP	C.54BC			; Inquiry
?.7F95:	JP	J$54FA			; ReadCap
?.7F98:	JP	J$54DB			; ModeSense
?.7F9B:	JP	J$5292			; ModeSel
?.7F9E:	JP	J$52C6			; FmtUnit
?.7FA1:	JP	C.5186			; TstUnitRdy
?.7FA4:	JP	J$472B			; Initialise
?.7FA7:	JP	C.4828			; InsWork
?.7FAA:	JP	C.4CE1			; ClrEndLn
; 2.3 BIOS CALLS
?.7FAD:	JP	C.530C			; Verify
?.7FB0:	JP	C.51A0			; StrtStpUn
?.7FB3:	JP	J$5174			; SndDiag
?.7FB6:	JP	J.46BE			; Reserved
?.7FB9:	JP	J.46BE			; Reserved
; NOVAXIS BIOS CALLS
?.7FBC:	JP	J$5616			; Copy
?.7FBF:	JP	J$55D6			; RdDefect
?.7FC2:	JP	C.403F			; GetWrk
?.7FC5:	JP	C.4CE9			; PartInfo
?.7FC8:	JP	C.4CF5			; GetUnitsOn
?.7FCB:	JP	J$50EA			; SetHOST_ID
?.7FCE:	JP	C.5A3F			; SetTargetID
?.7FD1:	JP	C.5A19			; GetTargetID
?.7FD4:	JP	C.5935			; GetHOST_ID
?.7FD7:	JP	C.59EF			; GetSense
?.7FDA:	JP	J$5633			; MedRemoval
?.7FDD:	JP	J.46BE			; Reserved
?.7FE0:	JP	J.46BE			; Reserved
?.7FE3:	JP	J.46BE			; Reserved
?.7FE6:	JP	C.601D
?.7FE9:	JP	J$5FE6
?.7FEC:	JP	C.5FB2

	DEFS	07FF0H-$,0

I$7FF0:	DEFB	"KMcs"
	DEFB	2			; MSX2+Turbo-R
	DEFB	001H
	DEFB	059H			; version 1.59
	DEFB	0B0H			; host ID = 7
	DEFB	034H			; I/O address

D$7FF9:	DEFB	064H
D.7FFA:	DEFB	000H
D$7FFB:	DEFB	037H

	DEFS	08000H-$,0

	END

