;  
;   FASTDROM -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA
;
	.Z80
	ORG	4000H
;
X.0000	EQU	0000H	; JC-LI
I.0001	EQU	0001H	; ----I
I.0002	EQU	0002H	; ----I
I.0003	EQU	0003H	; ----I
I.0004	EQU	0004H	; ----I
BDOS	EQU	0005H	; ----I
CPMADR	EQU	0006H	; ----I
I.0007	EQU	0007H	; ----I
I.0008	EQU	0008H	; ----I
I.0009	EQU	0009H	; ----I
I.000A	EQU	000AH	; ----I
I.000B	EQU	000BH	; ----I
C.000C	EQU	000CH	; -C--I
I.000D	EQU	000DH	; ----I
I.000E	EQU	000EH	; ----I
I$000F	EQU	000FH	; ----I
I.0010	EQU	0010H	; ----I
I.0011	EQU	0011H	; ----I
I.0012	EQU	0012H	; ----I
I$0013	EQU	0013H	; ----I
C.0014	EQU	0014H	; -C---
I.0015	EQU	0015H	; ----I
I$0016	EQU	0016H	; ----I
C.0018	EQU	0018H	; -C---
I.0019	EQU	0019H	; ----I
I$001A	EQU	001AH	; ----I
C.001C	EQU	001CH	; JC--I
I$001E	EQU	001EH	; ----I
X.0020	EQU	0020H	; -C-LI
I.0021	EQU	0021H	; ----I
I$0022	EQU	0022H	; ----I
I$0023	EQU	0023H	; ----I
C.0024	EQU	0024H	; JC--I
I.0025	EQU	0025H	; ----I
C.0028	EQU	0028H	; -C---
D.002B	EQU	002BH	; ---L-
D$002D	EQU	002DH	; ---L-
C.0030	EQU	0030H	; -C---
I$0034	EQU	0034H	; ----I
X.0038	EQU	0038H	; -CS-I
D$0039	EQU	0039H	; --S--
I$003B	EQU	003BH	; ----I
I$0045	EQU	0045H	; ----I
C$0046	EQU	0046H	; -C---
C$004B	EQU	004BH	; -C---
C$0059	EQU	0059H	; -C---
FCB1	EQU	005CH	; -C---
I$0064	EQU	0064H	; ----I
FCB2.1	EQU	006EH	; ----I
I$0071	EQU	0071H	; ----I
DBUF	EQU	0080H	; ----I
D$0092	EQU	0092H	; ---L-
I$0093	EQU	0093H	; ----I
I$009C	EQU	009CH	; ----I
I$009F	EQU	009FH	; ----I
I$00A0	EQU	00A0H	; ----I
I$00A2	EQU	00A2H	; ----I
I$00A5	EQU	00A5H	; ----I
I$00B7	EQU	00B7H	; ----I
C.00BD	EQU	00BDH	; -C---
J$00C3	EQU	00C3H	; J----
I.00C8	EQU	00C8H	; ----I
C$00CC	EQU	00CCH	; -C---
C$00D2	EQU	00D2H	; -C---
I$00FF	EQU	00FFH	; ----I
J.0100	EQU	0100H	; J---I
I$0102	EQU	0102H	; ----I
I$0107	EQU	0107H	; ----I
I$0117	EQU	0117H	; ----I
I$0140	EQU	0140H	; ----I
C.0141	EQU	0141H	; -C---
I$0156	EQU	0156H	; ----I
C.0159	EQU	0159H	; JC---
I.0163	EQU	0163H	; ----I
I$0168	EQU	0168H	; ----I
I$01B7	EQU	01B7H	; ----I
I$01F2	EQU	01F2H	; ----I
I.0200	EQU	0200H	; ----I
I$0206	EQU	0206H	; ----I
I$021E	EQU	021EH	; ----I
I$0270	EQU	0270H	; ----I
I$027B	EQU	027BH	; ----I
I$02CA	EQU	02CAH	; ----I
I.0301	EQU	0301H	; ----I
I$0302	EQU	0302H	; ----I
I$033E	EQU	033EH	; ----I
I$03F5	EQU	03F5H	; ----I
I$03F6	EQU	03F6H	; ----I
I.0400	EQU	0400H	; ----I
I$0406	EQU	0406H	; ----I
I$043E	EQU	043EH	; ----I
I$051E	EQU	051EH	; ----I
I.05B5	EQU	05B5H	; ----I
I$0600	EQU	0600H	; ----I
I$0601	EQU	0601H	; ----I
I$071E	EQU	071EH	; ----I
I$073E	EQU	073EH	; ----I
I$076C	EQU	076CH	; ----I
I$07BC	EQU	07BCH	; ----I
I$07D0	EQU	07D0H	; ----I
I$0800	EQU	0800H	; ----I
I$0802	EQU	0802H	; ----I
I$083E	EQU	083EH	; ----I
I$08D6	EQU	08D6H	; ----I
D.0A0D	EQU	0A0DH	; --S-I
I$0C00	EQU	0C00H	; ----I
I$0D00	EQU	0D00H	; ----I
I$0D1E	EQU	0D1EH	; ----I
I$0E00	EQU	0E00H	; ----I
I.0FF7	EQU	0FF7H	; ----I
I.0FFF	EQU	0FFFH	; ----I
I$116D	EQU	116DH	; ----I
D$200A	EQU	200AH	; ---L-
D.202E	EQU	202EH	; --S-I
I$2101	EQU	2101H	; ----I
I$23AC	EQU	23ACH	; ----I
C$268C	EQU	268CH	; -C---
I$269A	EQU	269AH	; ----I
C$289F	EQU	289FH	; -C---
I$2947	EQU	2947H	; ----I
I$2D41	EQU	2D41H	; ----I
I$2D48	EQU	2D48H	; ----I
I$2E30	EQU	2E30H	; ----I
C.2EF3	EQU	2EF3H	; -C---
J$2F08	EQU	2F08H	; J----
C$2F10	EQU	2F10H	; -C---
C.2F99	EQU	2F99H	; JC---
I$302E	EQU	302EH	; ----I
I.3038	EQU	3038H	; ----I
J$3042	EQU	3042H	; J----
C$30D1	EQU	30D1H	; -C---
I$321E	EQU	321EH	; ----I
C.325C	EQU	325CH	; -C---
I$32AF	EQU	32AFH	; ----I
I$341E	EQU	341EH	; ----I
I$351E	EQU	351EH	; ----I
I$361E	EQU	361EH	; ----I
I$371E	EQU	371EH	; ----I
I$381E	EQU	381EH	; ----I
D$3A00	EQU	3A00H	; ---L-
I$3B08	EQU	3B08H	; ----I
I$3B1E	EQU	3B1EH	; ----I
D$3C01	EQU	3C01H	; ---L-
I$3D1E	EQU	3D1EH	; ----I
D.3D2B	EQU	3D2BH	; ---L-
I$3E1E	EQU	3E1EH	; ----I
D$3E3F	EQU	3E3FH	; ---L-
I$3F00	EQU	3F00H	; ----I
I$3F1E	EQU	3F1EH	; ----I
I$3FD6	EQU	3FD6H	; ----I
I$8000	EQU	8000H	; ----I
J$8035	EQU	8035H	; J----
J$803A	EQU	803AH	; J----
I$C000	EQU	0C000H	; ----I
I$C001	EQU	0C001H	; ----I
J$C01E	EQU	0C01EH	; J----
D$C07C	EQU	0C07CH	; ---L-
D$C092	EQU	0C092H	; --S--
I$C0AB	EQU	0C0ABH	; ----I
C.C0CB	EQU	0C0CBH	; -C---
I$C0E4	EQU	0C0E4H	; ----I
I$C0EF	EQU	0C0EFH	; ----I
D.C0FA	EQU	0C0FAH	; --SLI
I$C0FB	EQU	0C0FBH	; ----I
D$C108	EQU	0C108H	; --S--
I.C200	EQU	0C200H	; ----I
I$C9A8	EQU	0C9A8H	; ----I
J$CD5B	EQU	0CD5BH	; J----
I$DDFF	EQU	0DDFFH	; ----I
C$E471	EQU	0E471H	; -C---
D$ED00	EQU	0ED00H	; ---L-
I.F1C9	EQU	0F1C9H	; ----I
C.F1D9	EQU	0F1D9H	; JC---
I$F1DE	EQU	0F1DEH	; ----I
J$F1E2	EQU	0F1E2H	; J----
C.F1E8	EQU	0F1E8H	; JC---
C.F1F4	EQU	0F1F4H	; JC---
I$F1F7	EQU	0F1F7H	; ----I
I.F20B	EQU	0F20BH	; ----I
D$F216	EQU	0F216H	; --S--
D$F221	EQU	0F221H	; ---L-
D$F223	EQU	0F223H	; ---L-
I$F22A	EQU	0F22AH	; ----I
I.F22B	EQU	0F22BH	; ----I
D$F22C	EQU	0F22CH	; --S--
D.F237	EQU	0F237H	; --SLI
D.F238	EQU	0F238H	; --SL-
D.F239	EQU	0F239H	; --SL-
D.F23B	EQU	0F23BH	; --SL-
D.F23C	EQU	0F23CH	; --SL-
D.F23D	EQU	0F23DH	; --SL-
D.F23F	EQU	0F23FH	; --SL-
D.F241	EQU	0F241H	; --SL-
D.F242	EQU	0F242H	; --SLI
D.F243	EQU	0F243H	; --SL-
D.F245	EQU	0F245H	; ---L-
D.F246	EQU	0F246H	; --SL-
D.F247	EQU	0F247H	; --SLI
D.F248	EQU	0F248H	; --SL-
D.F249	EQU	0F249H	; --SL-
D.F24A	EQU	0F24AH	; --SL-
D.F24C	EQU	0F24CH	; --S--
D$F24D	EQU	0F24DH	; --S--
D.F24E	EQU	0F24EH	; --SL-
C.F24F	EQU	0F24FH	; -C--I
X.F252	EQU	0F252H	; -C-L-
C$F255	EQU	0F255H	; -C---
C$F258	EQU	0F258H	; -C---
C$F25B	EQU	0F25BH	; -C---
C$F25E	EQU	0F25EH	; -C---
C$F261	EQU	0F261H	; -C---
C$F264	EQU	0F264H	; -C---
C$F267	EQU	0F267H	; -C---
C$F26A	EQU	0F26AH	; -C---
C$F26D	EQU	0F26DH	; -C---
C$F270	EQU	0F270H	; -C---
C$F273	EQU	0F273H	; -C---
C$F276	EQU	0F276H	; -C---
C$F279	EQU	0F279H	; -C---
C$F27C	EQU	0F27CH	; -C---
C$F27F	EQU	0F27FH	; -C---
C$F282	EQU	0F282H	; -C---
C$F285	EQU	0F285H	; -C---
C$F288	EQU	0F288H	; -C---
C$F28B	EQU	0F28BH	; -C---
C$F28E	EQU	0F28EH	; -C---
C$F291	EQU	0F291H	; -C---
C$F294	EQU	0F294H	; -C---
C$F297	EQU	0F297H	; -C---
C$F29A	EQU	0F29AH	; -C---
C$F29D	EQU	0F29DH	; -C---
C$F2A0	EQU	0F2A0H	; -C---
C$F2A3	EQU	0F2A3H	; -C---
C$F2A6	EQU	0F2A6H	; -C---
C$F2A9	EQU	0F2A9H	; -C---
C$F2AC	EQU	0F2ACH	; -C---
C$F2AF	EQU	0F2AFH	; -C---
C$F2B2	EQU	0F2B2H	; -C---
C$F2B5	EQU	0F2B5H	; -C---
D.F2B8	EQU	0F2B8H	; --SL-
I.F2B9	EQU	0F2B9H	; ----I
D.F2C4	EQU	0F2C4H	; --SL-
I.F2C5	EQU	0F2C5H	; ----I
I.F2D0	EQU	0F2D0H	; ----I
D.F2DC	EQU	0F2DCH	; --SL-
D.F2DD	EQU	0F2DDH	; --SL-
D.F2DE	EQU	0F2DEH	; --SL-
D.F2DF	EQU	0F2DFH	; --SL-
D.F2E0	EQU	0F2E0H	; --SL-
D.F2E1	EQU	0F2E1H	; --SL-
D.F2E2	EQU	0F2E2H	; --SL-
D.F2E4	EQU	0F2E4H	; --SL-
D.F2E6	EQU	0F2E6H	; --SL-
D$F2E7	EQU	0F2E7H	; --S--
D.F2E8	EQU	0F2E8H	; --SL-
D.F2EA	EQU	0F2EAH	; --SL-
D.F2EC	EQU	0F2ECH	; --SL-
D.F2EE	EQU	0F2EEH	; --SL-
D.F2F0	EQU	0F2F0H	; ---L-
D.F2F2	EQU	0F2F2H	; --S--
D.F2F4	EQU	0F2F4H	; --SLI
D.F2F6	EQU	0F2F6H	; --SL-
D.F2F8	EQU	0F2F8H	; --SL-
D.F2FA	EQU	0F2FAH	; --SL-
D.F2FC	EQU	0F2FCH	; --SL-
D.F2FE	EQU	0F2FEH	; --SL-
D.F2FF	EQU	0F2FFH	; --SL-
D.F300	EQU	0F300H	; --SL-
D.F302	EQU	0F302H	; ---L-
D.F306	EQU	0F306H	; --SL-
D.F307	EQU	0F307H	; --SL-
D.F309	EQU	0F309H	; --SL-
D.F30B	EQU	0F30BH	; --SL-
D.F30C	EQU	0F30CH	; --SL-
D.F30D	EQU	0F30DH	; --SL-
D.F30E	EQU	0F30EH	; --SL-
I.F30F	EQU	0F30FH	; ----I
D.F313	EQU	0F313H	; --SL-
D.F323	EQU	0F323H	; --SLI
D.F325	EQU	0F325H	; --SL-
I.F327	EQU	0F327H	; ----I
I$F331	EQU	0F331H	; ----I
D.F336	EQU	0F336H	; --SLI
D.F337	EQU	0F337H	; --SL-
D.F338	EQU	0F338H	; --SL-
D.F339	EQU	0F339H	; --SL-
D.F33B	EQU	0F33BH	; --SL-
D.F33D	EQU	0F33DH	; --SL-
D.F33E	EQU	0F33EH	; ---LI
D.F33F	EQU	0F33FH	; --SLI
D.F340	EQU	0F340H	; ---LI
D.F341	EQU	0F341H	; --SLI
D.F342	EQU	0F342H	; --SL-
D.F343	EQU	0F343H	; --SL-
D$F344	EQU	0F344H	; --S--
D.F345	EQU	0F345H	; --SLI
D.F346	EQU	0F346H	; --SL-
D.F347	EQU	0F347H	; --SLI
D.F348	EQU	0F348H	; --SLI
D.F349	EQU	0F349H	; --SL-
D.F34B	EQU	0F34BH	; --SL-
D.F34D	EQU	0F34DH	; --SL-
D.F34F	EQU	0F34FH	; --SL-
D.F351	EQU	0F351H	; --SL-
D.F353	EQU	0F353H	; --SL-
I.F355	EQU	0F355H	; ----I
X.F365	EQU	0F365H	; -CS--
D$F366	EQU	0F366H	; --S--
X.F368	EQU	0F368H	; -CS-I
D$F369	EQU	0F369H	; --S--
X.F36B	EQU	0F36BH	; -CS--
D$F36C	EQU	0F36CH	; --S--
D$F36E	EQU	0F36EH	; --S--
D$F36F	EQU	0F36FH	; --S--
J$F371	EQU	0F371H	; J----
D$F372	EQU	0F372H	; --S--
J$F374	EQU	0F374H	; J----
D$F375	EQU	0F375H	; --S--
I$F377	EQU	0F377H	; ----I
D$F378	EQU	0F378H	; --S--
I$F37A	EQU	0F37AH	; ----I
D$F37B	EQU	0F37BH	; --S--
C.F37D	EQU	0F37DH	; JC---
D$F37E	EQU	0F37EH	; --S--
C$F380	EQU	0F380H	; -C---
J$F385	EQU	0F385H	; J----
I.F38B	EQU	0F38BH	; ----I
J$F38C	EQU	0F38CH	; J----
I$F392	EQU	0F392H	; ----I
C$F398	EQU	0F398H	; -C---
D$F3B0	EQU	0F3B0H	; ---L-
D$F3DE	EQU	0F3DEH	; --S--
D$F415	EQU	0F415H	; ---L-
D$F416	EQU	0F416H	; ---L-
D$F41C	EQU	0F41CH	; --S--
I.F459	EQU	0F459H	; ----I
D.F4D9	EQU	0F4D9H	; --SLI
I$F4DB	EQU	0F4DBH	; ----I
I$F51F	EQU	0F51FH	; ----I
D$F55B	EQU	0F55BH	; --S--
I$F567	EQU	0F567H	; ----I
X.F568	EQU	0F568H	; -CSLI
I.F569	EQU	0F569H	; ----I
D.F56A	EQU	0F56AH	; --SL-
D$F56B	EQU	0F56BH	; --S--
I$F56C	EQU	0F56CH	; ----I
D.F574	EQU	0F574H	; --S--
D$F578	EQU	0F578H	; --S--
I.F579	EQU	0F579H	; ----I
D.F58D	EQU	0F58DH	; --S-I
I.F58E	EQU	0F58EH	; ----I
I$F59E	EQU	0F59EH	; ----I
I.F5B2	EQU	0F5B2H	; ----I
I$F5B3	EQU	0F5B3H	; ----I
D$F5BE	EQU	0F5BEH	; --S--
D.F5C0	EQU	0F5C0H	; --S--
D.F5C2	EQU	0F5C2H	; --S-I
I$F5C4	EQU	0F5C4H	; ----I
D$F5C6	EQU	0F5C6H	; ---L-
D$F5C8	EQU	0F5C8H	; ---L-
D$F5D3	EQU	0F5D3H	; --S--
D$F5D5	EQU	0F5D5H	; --S--
I.F5D7	EQU	0F5D7H	; ----I
D$F5E5	EQU	0F5E5H	; --S--
D$F5EB	EQU	0F5EBH	; --S--
D$F5ED	EQU	0F5EDH	; --S--
D$F5F8	EQU	0F5F8H	; --S--
D$F5FA	EQU	0F5FAH	; --S--
I.F5FC	EQU	0F5FCH	; ----I
I$F604	EQU	0F604H	; ----I
D$F661	EQU	0F661H	; ---L-
D.F663	EQU	0F663H	; --S--
D.F672	EQU	0F672H	; --SL-
D.F674	EQU	0F674H	; --SL-
D.F676	EQU	0F676H	; --SL-
D.F678	EQU	0F678H	; --SL-
I.F698	EQU	0F698H	; ----I
D$F699	EQU	0F699H	; ---L-
D.F69B	EQU	0F69BH	; ---LI
D.F6AB	EQU	0F6ABH	; ---L-
D$F6B1	EQU	0F6B1H	; --S--
D.F6C2	EQU	0F6C2H	; --SL-
D.F6C6	EQU	0F6C6H	; --S--
I.F7F6	EQU	0F7F6H	; ----I
D.F7F8	EQU	0F7F8H	; --S--
I$F844	EQU	0F844H	; ----I
I.F847	EQU	0F847H	; ----I
D.F85F	EQU	0F85FH	; --SL-
D.F860	EQU	0F860H	; --SL-
D.F862	EQU	0F862H	; --SL-
D.F864	EQU	0F864H	; --SL-
D.F866	EQU	0F866H	; ---LI
D.F87C	EQU	0F87CH	; --S--
D.F87D	EQU	0F87DH	; --SL-
I$FB20	EQU	0FB20H	; ----I
I.FB21	EQU	0FB21H	; ----I
I.FB22	EQU	0FB22H	; ----I
I.FB29	EQU	0FB29H	; ----I
D$FB6B	EQU	0FB6BH	; ---L-
D.FC48	EQU	0FC48H	; --SL-
D.FC4A	EQU	0FC4AH	; --SL-
D.FCAE	EQU	0FCAEH	; --S-I
D.FCBE	EQU	0FCBEH	; --SL-
D.FCBF	EQU	0FCBFH	; --SL-
D.FCC0	EQU	0FCC0H	; ---L-
D.FCC1	EQU	0FCC1H	; ---LI
I.FCC5	EQU	0FCC5H	; ----I
I$FCC9	EQU	0FCC9H	; ----I
I$FD00	EQU	0FD00H	; ----I
I$FD09	EQU	0FD09H	; ----I
I$FD89	EQU	0FD89H	; ----I
D.FD99	EQU	0FD99H	; --SLI
D.FD9F	EQU	0FD9FH	; --SL-
D.FDA0	EQU	0FDA0H	; --S-I
D$FDA1	EQU	0FDA1H	; --S--
D$FDA3	EQU	0FDA3H	; --S--
I.FDEA	EQU	0FDEAH	; ----I
I$FE00	EQU	0FE00H	; ----I
D$FE4E	EQU	0FE4EH	; ---L-
I$FEBC	EQU	0FEBCH	; ----I
I.FECB	EQU	0FECBH	; ----I
D$FECC	EQU	0FECCH	; --S--
D$FED0	EQU	0FED0H	; ---L-
D.FED5	EQU	0FED5H	; --S-I
D$FED6	EQU	0FED6H	; --S--
D$FEDA	EQU	0FEDAH	; ---L-
I$FF00	EQU	0FF00H	; ----I
I$FF7F	EQU	0FF7FH	; ----I
I$FFCA	EQU	0FFCAH	; ----I
C$FFCF	EQU	0FFCFH	; -C---
C$FFD4	EQU	0FFD4H	; -C---
I$FFF4	EQU	0FFF4H	; ----I
I$FFF5	EQU	0FFF5H	; ----I
I$FFF8	EQU	0FFF8H	; ----I
I$FFF9	EQU	0FFF9H	; ----I
I$FFFC	EQU	0FFFCH	; ----I
D.FFFF	EQU	0FFFFH	; --SLI

	DEFB	41H,42H,6FH,57H,0EEH,64H,00H,00H
	DEFB	00H,00H,00H,00H,00H,00H,00H,00H

I$4010:	JP	C.74A0
I$4013:	JP	J$7410
I$4016:	JP	C.7CFC
I$4019:	JP	J$766D
I$401C:	JP	J$7470
I$401F:	JP	C.5095
J.4022:	JP	J.5B91
?.4025:	SCF
	JP	C.6115
?.4029:	JP	J$61E7

?.402C:	NOP
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$402D:	JP	C.5FE0
;
;	-----------------
?.4030:	LD	HL,(D.F34B)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4034:	PUSH	IX
	LD	IX,I$00B7
	CALL	C.4097
	JR	NC,J$4049
	LD	A,03H	; 3 
	LD	(D.F336),A
	LD	(D.F337),A
	AND	A
	RET
;
;	-----------------
J$4049:	LD	A,(D.F336)
	AND	A
	LD	A,(D.F337)
	RET	NZ
;
	PUSH	IX
	LD	IX,I$009C
	CALL	C.4097
;
	RET	Z
;
	LD	A,0FFH
	LD	(D.F336),A
	CALL	C$4083
;
	LD	(D.F337),A
	OR	A
	RET
;
;	-----------------
I$4068:	LD	(BC),A
	LD	(HL),D
	NOP
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.406B:	XOR	A
	LD	(D.F336),A
I$406F:	PUSH	IX
	LD	IX,I$0156
	CALL	C.4097
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4078:	PUSH	HL
	LD	HL,D.F336
	XOR	A
	CP	(HL)
	LD	(HL),A
	INC	HL
	LD	A,(HL)
	POP	HL
	RET	NZ
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4083:	PUSH	IX
	LD	IX,I$009F
J.4089:	CALL	C.40AB
;
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.408F:	PUSH	IX
	LD	IX,I$00A2
	JR	J.4089
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4097:	CALL	C.40AB
;
	POP	IX
	EX	(SP),IX
	RET
;
;	-----------------
J.409F:	PUSH	IX
	LD	IX,I$00A5
	JR	J.4089
;
;	-----------------
?.40A7:	LD	IX,READYR
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.40AB:	PUSH	IY
	LD	IY,(D.FCC0)
	CALL	C.001C
;
	EI
	POP	IY
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$40B8:	LD	A,0DH	; 13 
	OUT	(0B4H),A
	LD	A,0AH	; 10 
	OUT	(0B5H),A
	XOR	A
	OUT	(0B4H),A
	LD	B,0FH	; 15 
J$40C5:	IN	A,(0B5H)
	AND	0FH	; 15 
	XOR	B
	OUT	(0B5H),A
	LD	C,A
	NOP
	IN	A,(0B5H)
	AND	0FH	; 15 
	CP	C
	RET	NZ
;
	XOR	B
	OUT	(0B5H),A
	DJNZ	J$40C5
;
	LD	A,0FFH
	LD	(D.F338),A
	LD	A,0DH	; 13 
	OUT	(0B4H),A
	LD	A,09H	; 9 
	OUT	(0B5H),A
	LD	A,0AH	; 10 
	OUT	(0B4H),A
	LD	A,01H	; 1 
	OUT	(0B5H),A
	LD	A,0DH	; 13 
	OUT	(0B4H),A
	XOR	A
	OUT	(0B5H),A
	LD	BC,I$0D00
J$40F8:	LD	A,C
	OUT	(0B4H),A
	IN	A,(0B5H)
	PUSH	AF
	INC	C
	DJNZ	J$40F8
;
	LD	A,0EH	; 14 
	OUT	(0B4H),A
	XOR	A
	OUT	(0B5H),A
	LD	B,0DH	; 13 
J$410A:	DEC	C
	LD	A,C
	OUT	(0B4H),A
	POP	AF
	OUT	(0B5H),A
	DJNZ	J$410A
;
	JR	C.4150
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4115:	LD	(D.F33B),HL
	LD	A,(D.F338)
	AND	A
	RET	Z
;
	LD	A,(D.F24A)
I$411E	EQU	$-2
	LD	B,A
	LD	A,(D.F249)
	LD	C,A
	LD	A,(D.F248)
	LD	D,A
	LD	E,07H	; 7 
	CALL	C.415B
;
	JR	J$4144
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4130:	LD	A,(D.F338)
	AND	A
	JP	Z,J$75E3
;
	LD	E,00H
	CALL	C.415B
;
	LD	A,0FH	; 15 
	OUT	(0B4H),A
	LD	A,02H	; 2 
	OUT	(0B5H),A
J$4144:	LD	H,D
	CALL	C.4162
;
	LD	H,C
	CALL	C.4162
;
	LD	H,B
	CALL	C.4162
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4150:	LD	A,0DH	; 13 
	OUT	(0B4H),A
	IN	A,(0B5H)
	OR	08H	; 8 
J.4158:	OUT	(0B5H),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.415B:	CALL	C.4150
;
	AND	04H	; 4 
	JR	J.4158
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4162:	XOR	A
	LD	L,08H	; 8 
J$4165:	RLC	H
	ADC	A,A
	DAA
	DEC	L
	JR	NZ,J$4165
;
	CALL	C.4173
;
	RRCA
	RRCA
	RRCA
	RRCA
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4173:	PUSH	AF
	LD	A,E
	INC	E
	OUT	(0B4H),A
	POP	AF
	JR	J.4158
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$417B:	CALL	C$75CC
;
	LD	HL,(D.F33B)
	AND	A
	RET	Z
;
	CALL	C.415B
;
	LD	E,0DH	; 13 
	CALL	C.41AB
;
	CALL	C.550A
;
	CALL	C.41AB
;
	LD	(D.F249),A
	CALL	C.41AB
;
	LD	(D.F248),A
	DEC	E
	CALL	C.41AB
;
	LD	B,A
	CALL	C.41AB
;
	LD	C,A
	CALL	C.41AB
;
	CALL	C.4150
;
	SCF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.41AB:	XOR	A
	CALL	C$41B3
;
	ADD	A,A
	ADD	A,A
	ADD	A,D
	ADD	A,A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$41B3:	LD	D,A
	DEC	E
	LD	A,E
	OUT	(0B4H),A
	IN	A,(0B5H)
	AND	0FH	; 15 
	ADD	A,D
	LD	D,A
	RET
;
;	-----------------
?.41BF:	DEFB	0,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.41C1:	PUSH	DE
	CALL	C$4EDD
	LD	E,A
	INC	E
	LD	D,0FFH
J.41C9:	INC	D
	LD	A,04H	; 4 
	CP	D
	SCF
	JR	Z,J$41DF
	LD	A,(IX)
	INC	IX
	INC	A
	JR	Z,J.41C9
	DEC	E
	JR	NZ,J.41C9
	DEC	IX
	XOR	A
	LD	A,D
J$41DF:	POP	DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.41E1:	LD	BC,I$0E00
	XOR	A
	JP	C.58E3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.41E8:	CALL	C$FFCF
	DI
	JP	C.517F			; enable I/O ports
;
;	-----------------
?.41EF:	LD	B,00H
	LD	A,22H	; """
	RET
;
;	-----------------
J$41F4:	PUSH	DE
	LD	E,L
	LD	D,H
	SRL	H
	RR	L
	RRA
	ADD	HL,DE
	POP	DE
	ADD	HL,DE
	RLA
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	JR	NC,J$4211
;
	SRL	H
	RRA
	SRL	H
	RRA
	SRL	H
	RRA
	SRL	H
	RRA
J$4211:	LD	L,A
	LD	A,H
	AND	0FH	; 15 
	LD	H,A
	OR	L
	RET
;
;	-----------------
J$4218:	PUSH	DE
	LD	E,L
	LD	D,H
	SRL	H
	RR	L
I$421E	EQU	$-1
	RRA
	ADD	HL,DE
	POP	DE
	ADD	HL,DE
	RLA
	JR	NC,J$423E
;
	SLA	C
	RL	B
	SLA	C
	RL	B
	SLA	C
	RL	B
	SLA	C
	RL	B
	LD	A,(HL)
	AND	0FH	; 15 
	OR	C
	LD	(HL),A
	INC	HL
	LD	(HL),B
	RET
;
;	-----------------
J$423E:	LD	(HL),C
	INC	HL
	LD	A,(HL)
	AND	0F0H
	OR	B
	LD	(HL),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4246:	LD	DE,I.F2B9
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4249:	LD	A,(DE)
	CP	(HL)
	INC	HL
	INC	DE
	RET	NZ
;
	DJNZ	C.4249
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4251:	CALL	C$F255
I$4253	EQU	$-1
;
	LD	HL,I$F1F7
	LD	C,05H	; 5 
J$4259:	LD	B,04H	; 4 
	CALL	C.4246
;
	JR	NZ,J$428F
;
	LD	B,04H	; 4 
J$4262:	LD	A,(DE)
	INC	DE
	CP	20H	; " "
	JR	NZ,J$429A
;
	DJNZ	J$4262
;
	LD	A,C
	NEG
	LD	(D$F216),A
	LD	HL,I.F2B9
	LD	DE,I.F20B
	LD	BC,I.0004
	LDIR
	CALL	C.547D
;
	LD	(D$F223),BC
	LD	(D$F221),DE
	LD	HL,I.F20B
	PUSH	HL
	POP	IY
	OR	01H	; 1 
	RET
;
;	-----------------
J$428F:	DEC	B
	LD	A,L
	ADD	A,B
	LD	L,A
	LD	A,H
	ADC	A,00H
	LD	H,A
	DEC	C
	JR	NZ,J$4259
;
J$429A:	SCF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.429C:	PUSH	DE
	LD	HL,I.000E
	ADD	HL,DE
	LD	(HL),00H
	CALL	C$42A8
;
	POP	DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$42A8:	CALL	C.440E
;
	RET	C
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.42AC:	CALL	C.4251
;
	RET	NC
;
	CALL	C$44D3
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.42B3:	CALL	C$F258
;
	CALL	C$4305
;
	RET	C
;
J$42BA:	LD	A,(HL)
	OR	A
	JR	Z,J.42F3
;
	CP	0E5H
	JR	Z,J.42F3
;
	PUSH	HL
	LD	B,0BH	; 11 
	LD	DE,I.F2B9
J$42C8:	CALL	C.4249
;
	JR	Z,J$42D3
;
	CP	3FH	; "?"
	JR	NZ,J$42EC
;
	DJNZ	J$42C8
;
J$42D3:	POP	HL
	PUSH	HL
	POP	IY
	LD	A,(D.F2C4)
	XOR	80H
	BIT	7,A
	RET	Z
;
	LD	A,(IY+11)
	AND	1EH
	RET	Z
;
	LD	A,(D.F2DC)
	OR	A
	RET	NZ
;
	JR	J.42ED
;
;	-----------------
J$42EC:	POP	HL
J.42ED:	CALL	C$433F
;
	JR	NC,J$42BA
;
	RET
;
;	-----------------
J.42F3:	LD	A,(D.F2FE)
	INC	A
	JR	NZ,J$42FF
;
	LD	A,(D.F2B8)
	LD	(D.F2FE),A
J$42FF:	LD	A,(HL)
	OR	A
	JR	NZ,J.42ED
;
	SCF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4305:	LD	A,(D.F2B8)
	INC	A
	CP	(IX+11)
	JR	NC,J.435E
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.430E:	CALL	C$F25B
;
	LD	(D.F2B8),A
	LD	C,A
	AND	(IX+4)
	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
I$431E:	ADD	HL,HL
	ADD	HL,HL
	LD	DE,(D.F351)
	ADD	HL,DE
	LD	B,(IX+5)
J$4328:	SRL	C
	DJNZ	J$4328
;
	LD	A,(D.F245)
	CP	C
	JR	NZ,J$4339
;
	LD	A,(D.F246)
	CP	(IX)
	RET	Z
;
J$4339:	PUSH	HL
	CALL	C.46A4
;
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$433F:	CALL	C$F25E
;
	LD	A,(D.F2B8)
	INC	A
	CP	(IX+11)
	JR	NC,J.435E
;
	LD	(D.F2B8),A
	LD	DE,X.0020
	ADD	HL,DE
	AND	(IX+4)
	RET	NZ
;
	INC	C
	CALL	C.46A4
;
	LD	HL,(D.F351)
	RET
;
;	-----------------
J.435E:	CALL	C.4743
;
	SCF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4363:	LD	BC,I$03F5
	JP	C.534C
;
;	-----------------
?.4369:	DEFB	0,0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$436C:	CALL	C.440E
;
	CALL	NC,C.42AC
;
	LD	A,0FFH
	RET	C
;
	RET	NZ
;
J$4376:	LD	A,0E5H
	LD	(D.F23C),A
	LD	(HL),A
	LD	L,(IY+26)
	LD	H,(IY+27)
	LD	A,H
	OR	L
	CALL	NZ,C.4F7A
;
	CALL	C.42B3
;
	JR	NC,J$4376
;
	CALL	C$4403
;
	JP	C.45CC
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4392:	CALL	C.440E
;
	JR	C,J.440B
;
	LD	DE,BDOS
	ADD	HL,DE
	LD	DE,I.F2C5
	CALL	C.F1F4
;
	CALL	NC,C.42AC
;
	JR	C,J.440B
;
	JR	NZ,J.440B
;
	LD	HL,I.F2B9
	LD	DE,I.F2D0
	LD	BC,C.000C
	LDIR
J$43B3:	LD	HL,I.F2C5
	LD	DE,I.F2B9
	LD	B,0BH	; 11 
J$43BB:	LD	A,(HL)
	CP	3FH	; "?"
	JR	NZ,J$43C3
;
	LD	A,(IY)
J$43C3:	LD	(DE),A
	INC	HL
	INC	DE
	INC	IY
	DJNZ	J$43BB
;
	LD	A,80H
	LD	(DE),A
	CALL	C.4251
;
	JR	NC,J.4408
;
	LD	A,(D.F2B8)
	PUSH	AF
	LD	A,0FFH
	LD	(D.F2B8),A
	CALL	C.42B3
;
	POP	BC
	JR	NC,J.4408
;
	LD	A,B
	CALL	C.430E
;
	EX	DE,HL
	LD	HL,I.F2B9
	LD	BC,I.000B
	LDIR
	LD	A,0FFH
	LD	(D.F23C),A
	LD	HL,I.F2D0
	LD	DE,I.F2B9
	LD	BC,C.000C
	LDIR
	CALL	C.42B3
D$4400	EQU	$-1
;
	JR	NC,J$43B3
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4403:	CALL	C.4743
;
	XOR	A
	RET
;
;	-----------------
J.4408:	CALL	C.4743
;
J.440B:	LD	A,0FFH
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.440E:	CALL	C$F261
;
	XOR	A
	LD	(D.F2DC),A
	EX	DE,HL
	LD	A,(HL)
	INC	HL
	LD	(D.F2C4),A
	AND	0FH	; 15 
	CALL	C.4427
I$441E	EQU	$-2
;
	RET	C
;
	LD	DE,I.F2B9
	JP	C.F1F4
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4427:	LD	C,A
	CALL	C$4F97
;
	RET	C
;
	LD	A,C
	DEC	A
	JP	P,J$4434
;
	LD	A,(D.F247)
J$4434:	LD	(D.F2E1),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4438:	LD	A,(IY+31)
	OR	A
	JR	NZ,J.445D
;
	LD	A,(IY+28)
	LD	C,(IY+29)
D$4443	EQU	$-1
	LD	B,(IY+30)
	ADD	A,A
	RL	C
	RL	B
	JR	C,J.445D
;
	OR	A
	JR	Z,J$4456
;
	INC	BC
	LD	A,B
	OR	C
	JR	Z,J.445D
;
J$4456:	LD	A,C
	RES	7,C
	ADD	A,A
	RL	B
	RET	NC
;
J.445D:	LD	BC,I$FF7F
	RET
;
;	-----------------
?.4461:	NOP
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4462:	CALL	C.429C
;
	JR	C,J.440B
;
	CALL	C.4438
;
	LD	A,(D.F30C)
	INC	B
	CP	B
	JR	NC,J.440B
;
J$4471:	CALL	C$F264
;
	EX	DE,HL
	LD	BC,I$000F
	ADD	HL,BC
	CALL	C.4438
;
	LD	A,(D.F30C)
	CP	B
	JR	Z,J.4488
;
	LD	C,80H
	JR	C,J.4488
;
	LD	C,00H
J.4488:	LD	(HL),C
	INC	HL
	EX	DE,HL
	LD	BC,C.001C
	ADD	HL,BC
	LD	C,04H	; 4 
	LDIR
	LD	BC,I$FFF8
	ADD	HL,BC
	LDI
	LDI
	LD	C,0FCH
	ADD	HL,BC
	LDI
	LDI
	LD	A,(IY+11)
	BIT	7,A
	JR	NZ,J$44AE
;
	LD	A,(IX)
	OR	40H	; "@"
J$44AE:	LD	(DE),A
	INC	DE
	LD	A,(D.F2B8)
	LD	(DE),A
	INC	DE
	LD	A,(IY+26)
	LD	(DE),A
	INC	DE
	INC	DE
	LD	(DE),A
	DEC	DE
	LD	A,(IY+27)
	LD	(DE),A
	INC	DE
	INC	DE
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	RET
;
;	-----------------
J$44CA:	LD	C,A
	LD	A,(D.F2E1)
	CALL	C$4702
;
	JR	C.44DB
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$44D3:	LD	A,0FFH
	LD	(D.F2B8),A
	LD	(D.F2FE),A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.44DB:	CALL	C$F267
;
	CALL	C.454F
;
	LD	A,(D.F2E1)
	LD	C,(IX+1)
	LD	B,00H
	OR	A
	CALL	C$607E
;
	JR	C,J$44CA
;
	CALL	C.45FB
;
	DEC	HL
	LD	A,B
	OR	(HL)
	LD	A,(D.F2E1)
	LD	HL,(D.F241)
	JP	M,J$4504
;
	RET	NZ
;
	CP	L
	JR	NZ,J.450D
;
	DEC	H
	RET	Z
;
J$4504:	SUB	L
	JR	NZ,J.450D
;
	LD	L,A
	LD	H,A
	DEC	L
	LD	(D.F241),HL
J.450D:	LD	A,0FFH
	LD	(D.F246),A
	PUSH	IX
	CALL	C.74C2
;
	LD	A,(IX)
	LD	L,(IX+2)
	LD	H,(IX+3)
I$451E	EQU	$-2
	POP	IX
	PUSH	HL
	CP	(IX)
	CALL	NZ,C.756E
;
	LD	A,(D.F2E1)
	LD	HL,X.0000
	CALL	C$752A
;
	POP	HL
	DEC	HL
	LD	(HL),00H
	INC	HL
	LD	B,(HL)
	LD	A,(D.F2E1)
	LD	C,(IX+1)
	PUSH	IX
	POP	HL
	CALL	C$6086
;
	PUSH	HL
	POP	IX
	EX	DE,HL
	CALL	C.455D
;
	LD	(HL),E
	INC	HL
	LD	(HL),D
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.454F:	CALL	C$F26A
;
	CALL	C.455D
;
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.455D:	LD	A,(D.F2E1)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4560:	LD	HL,I.F355
	ADD	A,A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4564:	ADD	A,L
	LD	L,A
	RET	NC
;
	INC	H
	RET
;
;	-----------------
?.4569:	NOP
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.456A:	LD	HL,I.0001
	PUSH	BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.456F:	PUSH	DE
	POP	IY
	CALL	C.440E
;
	LD	A,0FFH
	RET	C
;
	LD	A,(IY+24)
	AND	0C0H
	LD	A,00H
	RET	NZ
;
	LD	A,(D.F2E1)
	LD	HL,(D.F241)
	CP	L
	CALL	Z,C.472D
;
	CALL	C.454F
;
	LD	A,(IY+25)
	CALL	C.430E
;
	LD	B,0BH	; 11 
	CALL	C.4246
;
	JR	NZ,J$45D2
;
	PUSH	IY
	POP	DE
	LD	C,0BH	; 11 
	ADD	HL,BC
	EX	DE,HL
	LD	C,16H
	ADD	HL,BC
	LDI
	LDI
	LD	BC,I$FFFC
	ADD	HL,BC
	LDI
	LDI
	LD	BC,I.0004
	ADD	HL,BC
	LDI
	LDI
	LD	BC,I$FFF4
	ADD	HL,BC
	LD	BC,I.0004
	LDIR
	CALL	C.4748
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.45C4:	CALL	C.45FB
;
	DEC	HL
	LD	A,(HL)
	CP	01H	; 1 
	RET	NZ
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.45CC:	CALL	C$F26D
;
	JP	C.756E
;
;	-----------------
J$45D2:	CALL	C.45FB
;
	DEC	HL
	LD	(HL),00H
	LD	A,0FFH
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.45DB:	LD	A,(IX+10)
	CALL	C.45FB
;
	LD	B,(IX+16)
	LD	E,(IX+8)
	LD	D,(IX+9)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.45EB:	ADD	A,(IX+17)
	LD	E,A
	LD	D,(IX+18)
	JR	NC,J$45F5
;
	INC	D
J$45F5:	LD	HL,(D.F351)
	LD	B,01H	; 1 
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.45FB:	PUSH	IX
	CALL	C.74C2
;
	LD	L,(IX+2)
	LD	H,(IX+3)
	POP	IX
	RET
;
;	-----------------
I$4609:	EX	DE,HL
	CP	90H
	LD	C,L
	LD	D,E
	LD	E,B
	LD	E,A
	JR	NC,J$4642
;
	JR	NZ,J$4634
;
	NOP
	LD	(BC),A
	LD	(BC),A
	LD	BC,I.0200
	LD	(HL),B
	DEFB	0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.461D:	PUSH	DE
I$461E:	CALL	C.440E
I$4620	EQU	$-1
;
	JR	C,J.464D
;
	INC	HL
	INC	HL
	LD	(HL),00H
	LD	HL,I.F2B9
	LD	A,3FH	; "?"
	LD	BC,I.000B
	CPIR
	JR	Z,J.464D
;
	CALL	C.42AC
J$4634	EQU	$-2
;
	JR	NC,J$4651
;
	LD	A,(D.F2FE)
	CP	0FFH
	JR	Z,J.464D
;
	CALL	C.430E
;
J$4642:	PUSH	HL
	POP	IY
	JR	J.4669
;
;	-----------------
J$4647:	BIT	7,(IY+11)
	JR	NZ,J.468F
;
J.464D:	POP	DE
	LD	A,0FFH
	RET
;
;	-----------------
J$4651:	JR	NZ,J$4647
;
	LD	A,(D.F30C)
	OR	A
	JR	NZ,J.468F
;
	LD	L,(IY+26)
	LD	H,(IY+27)
	LD	A,H
	OR	L
	JR	Z,J.4669
;
	CALL	C.4F7A
;
I$4666:	CALL	C.45CC
;
J.4669:	PUSH	IY
	POP	DE
	LD	HL,I.F2B9
	LD	BC,I.000B
	LDIR
	LD	A,(HL)
	RLA
	LD	A,00H
	JR	NC,J$467C
;
	LD	A,06H	; 6 
J$467C:	LD	(DE),A
	INC	DE
	EX	DE,HL
	XOR	A
	LD	C,14H	; 20 
	CALL	C.58E3
;
	LD	C,09H	; 9 
	SBC	HL,BC
	CALL	C.4696
;
	CALL	C.4748
;
J.468F:	PUSH	IY
	POP	HL
	POP	DE
	JP	J$4471
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4696:	PUSH	HL
	CALL	C.547D
;
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),C
	INC	HL
	LD	(HL),B
	INC	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.46A4:	PUSH	BC
	CALL	C.4743
;
	POP	BC
	LD	B,(IX)
	LD	(D.F245),BC
	PUSH	BC
	LD	A,C
	CALL	C.45EB
;
	CALL	C.46C5
;
	POP	BC
	RET
;
;	-----------------
?.46BA:	LD	B,H
	LD	A,L
	LD	(D.F2E1),A
	CALL	C.454F
;
	LD	HL,(D.F23D)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.46C5:	CALL	C$F270
;
	XOR	A
	LD	(D.F2FF),A
	CALL	C.46D7
;
	RET	NC
;
	CALL	C.46E8
;
	DEC	A
	JR	Z,C.46C5
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.46D7:	LD	A,(IX)
	LD	C,(IX+1)
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C$6069
;
	POP	DE
	LD	C,D
	POP	DE
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.46E8:	PUSH	AF
	LD	A,C
	SUB	B
	LD	C,A
	PUSH	BC
	LD	B,00H
	EX	DE,HL
	ADD	HL,BC
	LD	B,C
	LD	C,00H
	SLA	B
	ADD	HL,BC
	POP	BC
	POP	AF
	LD	C,A
	LD	A,(D.F2FF)
	OR	C
	LD	C,A
I.46FF:	LD	A,(IX)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4702:	CALL	C$F273
;
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.F323)
	CALL	C.F1E8
;
	LD	A,C
	POP	HL
	POP	DE
	POP	BC
	CP	02H	; 2 
	RET	NZ
;
	JP	J$F1E2
;
;	-----------------
I$4718:	LD	B,L
	LD	H,L
	LD	D,E
	LD	H,B
	DEFB	0,0
I$471E:	DEFB	0,0
	LD	B,H
	LD	A,L
	LD	(D.F2E1),A
	CALL	C.454F
;
	LD	HL,(D.F23D)
	JR	C.4755
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.472D:	LD	HL,D.F242
	XOR	A
	CP	(HL)
	LD	(HL),A
	RET	Z
;
	LD	IX,(D.F243)
	LD	HL,(D.F34F)
	LD	B,01H	; 1 
	LD	DE,(D.F23F)
	JR	C.4755
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4743:	LD	A,(D.F23C)
	OR	A
	RET	Z
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4748:	CALL	C$F276
;
	XOR	A
	LD	(D.F23C),A
	LD	A,(D.F245)
	CALL	C.45EB
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4755:	CALL	C$F279
I$4756	EQU	$-2
;
	LD	A,01H	; 1 
	LD	(D.F2FF),A
	LD	A,(IX)
	LD	C,(IX+1)
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C$606B
;
	POP	DE
	LD	C,D
	POP	DE
	POP	HL
	RET	NC
;
	CALL	C.46E8
;
	DEC	A
	JR	Z,C.4755
;
	RET
;
;	-----------------
?.4775:	CALL	C.4EFD
;
	CALL	C.4B26
;
	JR	J$4783
;
;	-----------------
?.477D:	CALL	C.4EFD
;
	CALL	C.4CAF
;
J$4783:	CALL	C.486A
;
	JR	J$479C
;
;	-----------------
?.4788:	CALL	C.4857
;
	CALL	C.4B26
;
	JR	J$4799
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4790:	PUSH	IY
	POP	DE
	CALL	C.4857
;
	CALL	C.4CAF
;
J$4799:	CALL	C.4844
;
J$479C:	LD	A,L
	AND	7FH
	LD	(IY+32),A
	SLA	L
	RL	H
	LD	(IY+12),H
	RL	E
	LD	(IY+14),E
	LD	A,(D.F2DE)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.47B2:	XOR	A
	LD	(D.F306),A
	CALL	C.485A
;
	CALL	C.4B26
;
	JR	J$47C8
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.47BE:	XOR	A
	LD	(D.F306),A
	CALL	C.485A
;
	CALL	C.4CAF
;
J$47C8:	CALL	C.486A
;
	CALL	C.4844
;
	LD	L,C
	LD	H,B
	RET
;
;	-----------------
?.47D1:	PUSH	DE
	POP	IY
	LD	A,(IY+16)
	LD	C,(IY+17)
	LD	B,(IY+18)
	LD	E,(IY+19)
	ADD	A,A
	RL	C
	RL	B
	RL	E
	OR	A
	JR	Z,J.47F0
;
	INC	BC
	LD	A,B
	OR	C
	JR	NZ,J.47F0
;
	INC	E
J.47F0:	LD	L,(IY+33)
	LD	H,(IY+34)
	SBC	HL,BC
	JR	Z,C.4790
;
	LD	A,(IY+35)
	SBC	A,E
	JR	C,C.4790
;
	PUSH	HL
	CALL	C.4790
;
	POP	DE
	OR	A
	RET	NZ
;
	LD	HL,(D.F23D)
	PUSH	HL
	LD	HL,(D.F351)
	LD	(D.F23D),HL
	LD	B,80H
J$4813:	LD	(HL),A
	INC	HL
	DJNZ	J$4813
;
	DEC	A
	LD	(D.F246),A
	LD	L,(IY+33)
	LD	H,(IY+34)
	SBC	HL,DE
	LD	C,L
	LD	B,H
	EX	DE,HL
	LD	D,00H
	LD	A,(IY+35)
	SBC	A,D
	LD	E,A
J$482D:	PUSH	HL
	LD	HL,I.0001
	CALL	C.4CAF
;
	CALL	C.486A
;
	LD	C,L
	LD	B,H
	POP	HL
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,J$482D
;
	POP	HL
	LD	(D.F23D),HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4844:	LD	A,(D.F2DE)
	LD	(IY+33),L
	LD	(IY+34),H
	LD	(IY+35),E
	INC	D
	DEC	D
	RET	Z
;
	LD	(IY+36),D
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4857:	LD	HL,I.0001
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.485A:	PUSH	DE
	POP	IY
	LD	C,(IY+33)
	LD	B,(IY+34)
	LD	E,(IY+35)
	LD	D,(IY+36)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.486A:	RET	Z
;
	INC	HL
	LD	A,H
	OR	L
	RET	NZ
;
	INC	DE
	RET
;
;	-----------------
J$4871:	POP	HL
	LD	L,C
	LD	H,B
	LD	A,01H	; 1 
	LD	(D.F2DE),A
	XOR	A
	LD	C,A
	LD	B,A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.487D:	LD	(D.F2E8),HL
	LD	(D.F2E4),BC
	LD	(D.F2E6),DE
	LD	A,(IY)
	CALL	C.4427
;
	JR	C,J$4871
;
	LD	DE,DBUF
	LD	A,(D.F306)
	OR	A
	JR	NZ,J.48A8
;
	LD	A,(IY+14)
	LD	D,(IY+15)
	LD	E,A
	OR	D
	JR	NZ,J.48A8
;
	LD	E,80H
	LD	(IY+14),E
J.48A8:	INC	D
	DEC	D
	JR	NZ,J$48B1
;
	LD	A,E
	CP	40H	; "@"
	JR	C,J$48B5
;
J$48B1:	XOR	A
	LD	(D$F2E7),A
J$48B5:	LD	HL,(D.F23D)
	LD	(D.F2E2),HL
	XOR	A
	LD	(D.F2DE),A
	LD	(D.F2DF),A
	LD	BC,(D.F2E8)
	CALL	C.491C
;
	LD	A,(IY+24)
	OR	A
	RET	M
;
	PUSH	BC
	CALL	C.454F
;
	LD	BC,(D.F2E4)
	CALL	C.491C
;
	LD	(D.F2F4),BC
	PUSH	BC
	LD	BC,(D.F2E6)
	CALL	C.4922
;
	LD	(D.F2F6),BC
	LD	H,B
	LD	L,C
	POP	BC
	LD	D,B
	LD	E,C
	SRL	H
	RR	L
	RR	B
	LD	C,B
	LD	B,L
	LD	A,D
	AND	01H	; 1 
	LD	H,A
	LD	L,E
	LD	(D.F2F2),HL
	LD	(D.F2EE),BC
	LD	A,(IX+6)
	AND	C
	LD	(D.F2DD),A
	LD	A,(IX+7)
J$490C:	DEC	A
	JR	Z,J$4915
;
	SRL	B
	RR	C
	JR	J$490C
;
;	-----------------
J$4915:	LD	(D.F2EC),BC
	POP	BC
	XOR	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.491C:	CALL	C$F27C
;
	LD	HL,X.0000
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4922:	LD	A,B
	LD	B,11H	; 17 
	JR	J$492E
;
;	-----------------
J$4927:	JR	NC,J$492A
;
	ADD	HL,DE
J$492A:	RR	H
	RR	L
J$492E:	RRA
	RR	C
	DJNZ	J$4927
;
	LD	B,A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4935:	LD	HL,X.0000
	CALL	C$F27F
;
	LD	A,B
	LD	B,10H	; 16 
	RL	C
	RLA
J$4941:	RL	L
	RL	H
	JR	C,J$4954
;
	SBC	HL,DE
	JR	NC,J$494C
;
	ADD	HL,DE
J$494C:	CCF
J$494D:	RL	C
	RLA
	DJNZ	J$4941
;
	LD	B,A
	RET
;
;	-----------------
J$4954:	OR	A
	SBC	HL,DE
	JR	J$494D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4959:	LD	H,B
	LD	L,C
	LD	BC,(D.F2F2)
	LD	A,B
	OR	C
	LD	E,A
	LD	D,A
	JR	Z,J.4975
;
	LD	DE,I.0200
	EX	DE,HL
	SBC	HL,BC
	EX	DE,HL
	SBC	HL,DE
	JR	NC,J.4975
;
	ADD	HL,DE
	EX	DE,HL
	LD	HL,X.0000
J.4975:	LD	(D.F2F8),DE
	LD	C,L
	LD	B,H
	LD	A,H
	AND	01H	; 1 
	LD	H,A
	LD	C,B
	LD	B,00H
	SRL	C
	LD	(D.F2FA),HL
	LD	(D.F2FC),BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.498C:	CALL	C$F282
;
	LD	L,(IY+28)
	LD	H,(IY+29)
	LD	E,(IY+30)
	LD	D,(IY+31)
	LD	A,L
	OR	H
	JR	Z,J$49D2
;
	PUSH	BC
	LD	A,C
	SUB	E
	LD	C,A
	LD	A,B
	SBC	A,D
	LD	B,A
	JR	NC,J$49B3
;
	POP	BC
	LD	DE,X.0000
	LD	L,(IY+26)
	LD	H,(IY+27)
	PUSH	AF
J$49B3:	POP	AF
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.49B4:	CALL	C$F285
;
	LD	A,B
	OR	C
	RET	Z
;
	PUSH	DE
	PUSH	HL
	CALL	C.74E5
;
	POP	DE
	LD	A,H
	CP	0FH	; 15 
	JR	C,J$49CA
;
	LD	A,L
	CP	0F8H
	JR	NC,J$49CF
;
J$49CA:	POP	DE
	INC	DE
	DEC	BC
	JR	C.49B4
;
;	-----------------
J$49CF:	EX	DE,HL
	POP	DE
	RET
;
;	-----------------
J$49D2:	INC	BC
	DEC	DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.49D5:	LD	(D.F2E0),A
	LD	HL,(D.F2EC)
	LD	A,(D.F2DD)
	CALL	C.4EE3
;
	EX	DE,HL
	LD	HL,(D.F23F)
	SBC	HL,DE
	JR	NZ,J$49F3
;
	LD	A,(D.F2E1)
	LD	L,A
	LD	A,(D.F241)
	CP	L
	JR	Z,J$4A1E
;
J$49F3:	PUSH	DE
	PUSH	IX
	CALL	C.472D
;
	POP	IX
	POP	DE
	LD	A,(D.F2E0)
	OR	A
	JR	NZ,J$4A10
;
	DEC	A
	LD	(D.F241),A
	LD	HL,(D.F34F)
	LD	B,01H	; 1 
	PUSH	DE
	CALL	C.46C5
;
	POP	DE
J$4A10:	LD	(D.F23F),DE
	LD	A,(D.F2E1)
	LD	(D.F241),A
	LD	(D.F243),IX
J$4A1E:	LD	A,01H	; 1 
	LD	(D.F2DF),A
	LD	HL,(D.F2E2)
	PUSH	HL
	LD	BC,(D.F2F8)
	ADD	HL,BC
	LD	(D.F2E2),HL
	LD	HL,(D.F34F)
	LD	DE,(D.F2F2)
	ADD	HL,DE
	POP	DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4A39:	CALL	C$F288
;
	LD	HL,(D.F2F8)
	LD	A,H
	OR	L
	RET	Z
;
	XOR	A
	CALL	C.49D5
;
	JP	C.F1D9
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4A49:	CALL	C$F28B
;
	LD	HL,(D.F2F8)
	LD	A,H
	OR	L
	RET	Z
;
	LD	HL,(D.F2EE)
	INC	HL
	LD	(D.F2EE),HL
	XOR	A
	EX	DE,HL
	LD	HL,(D.F2F0)
	SBC	HL,DE
	RRA
	CALL	C.49D5
;
	EX	DE,HL
	CALL	C.F1D9
;
	LD	A,01H	; 1 
	LD	(D.F242),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4A6E:	LD	HL,X.0000
	LD	(D.F2F2),HL
	LD	HL,(D.F2FA)
	LD	(D.F2F8),HL
	LD	A,H
	OR	L
	SCF
	RET	Z
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4A7E:	LD	A,(D.F2DF)
	OR	A
	RET	Z
;
	LD	A,(D.F2DD)
	CP	(IX+6)
	JR	C,J$4AA5
;
	LD	DE,(D.F2EC)
	LD	HL,I.0FF7
	SBC	HL,DE
	RET	C
;
	EX	DE,HL
	CALL	C.74E5
;
	LD	(D.F2EC),HL
	LD	HL,(D.F2EA)
	INC	HL
	LD	(D.F2EA),HL
	LD	A,0FFH
J$4AA5:	INC	A
	LD	(D.F2DD),A
	OR	A
	RET
;
;	-----------------
J.4AAB:	LD	A,(HL)
	LDI
	CP	0DH	; 13 
	JR	NZ,J$4AB4
;
	LD	(HL),0AH	; 10 
J$4AB4:	CP	0AH	; 10 
	JR	Z,J$4ACD
;
	LD	A,B
	OR	C
	JR	NZ,J.4AAB
;
J.4ABC:	LD	(D.F300),HL
J.4ABF:	LD	(D.F2E2),DE
	JP	NZ,J.4BE0
;
	RES	6,(IY+24)
	JP	J.4BE0
;
;	-----------------
J$4ACD:	CALL	C.53A8
;
	LD	HL,X.0000
	LD	A,C
	OR	B
	JR	NZ,J$4AFC
;
	INC	A
	JR	J.4ABC
;
;	-----------------
J$4ADA:	LD	DE,(D.F2E2)
	INC	A
	JR	Z,J$4AF5
;
	INC	A
	JR	NZ,J.4ABF
;
J$4AE4:	CALL	C$546E
;
	LD	(DE),A
	INC	DE
	CP	1AH
	JR	Z,J.4ABF
;
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$4AE4
;
	INC	A
	JR	J.4ABF
;
;	-----------------
J$4AF5:	LD	HL,(D.F300)
	LD	A,H
	OR	L
	JR	NZ,J.4AAB
;
J$4AFC:	LD	HL,DBUF
I$4AFF:	LD	A,(D.F4D9)
	CP	L
	JR	Z,J$4B08
;
	LD	(D.F4D9),HL
J$4B08:	PUSH	BC
	PUSH	DE
	LD	DE,D.F4D9
	CALL	C.50E0
;
	POP	DE
	POP	BC
	LD	HL,I$F4DB
	LD	A,(HL)
	CP	1AH
	JR	NZ,J.4AAB
;
	LD	(DE),A
	INC	DE
	LD	A,0AH	; 10 
	CALL	C.53A8
;
	XOR	A
	LD	H,A
	LD	L,A
	JR	J.4ABC
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4B26:	CALL	C.487D
;
	JP	M,J$4ADA
;
	LD	L,(IY+16)
	LD	H,(IY+17)
D.4B30	EQU	$-2
	LD	DE,(D.F2F4)
	OR	A
	SBC	HL,DE
	PUSH	HL
	LD	L,(IY+18)
	LD	H,(IY+19)
	LD	DE,(D.F2F6)
	SBC	HL,DE
	POP	HL
	JP	C,J.4C95
;
	JR	NZ,J.4B59
;
	LD	A,H
	OR	L
	JP	Z,J.4C95
;
	PUSH	HL
	SBC	HL,BC
	POP	HL
	JR	NC,J.4B59
;
	LD	B,H
	LD	C,L
J.4B59:	CALL	C$F28E
;
	CALL	C.4959
;
	LD	BC,(D.F2EC)
	CALL	C.498C
;
	LD	A,B
	OR	C
	JP	NZ,J.4C95
;
	LD	(D.F2EC),HL
	LD	(D.F2EA),DE
	CALL	C.4A39
;
	LD	HL,(D.F2FC)
	LD	A,H
	OR	L
	JP	Z,J.4BDA
;
	CALL	C.4A7E
;
	JR	C,J.4BE0
;
	LD	A,01H	; 1 
	LD	(D.F2DF),A
	LD	A,(D.F2DD)
	LD	BC,(D.F2FC)
	LD	HL,(D.F2EC)
J$4B91:	PUSH	BC
	CALL	C.4E56
;
	PUSH	BC
	PUSH	AF
	LD	B,A
	CALL	C.46C5
;
	POP	AF
	LD	C,A
	LD	B,00H
	JR	C,J.4BBF
;
	LD	A,(D.F242)
	OR	A
	JR	Z,J.4BBF
;
	PUSH	BC
	PUSH	HL
	LD	HL,(D.F23F)
	SBC	HL,DE
	LD	B,L
	LD	C,00H
	SLA	B
	POP	HL
	ADD	HL,BC
	LD	B,02H	; 2 
	EX	DE,HL
	LD	HL,(D.F34F)
	CALL	C.F1D9
;
	POP	BC
J.4BBF:	POP	DE
	POP	HL
	OR	A
	SBC	HL,BC
	JR	Z,J.4BDA
;
	LD	C,L
	LD	B,H
	LD	HL,I.0FF7
	SBC	HL,DE
	JR	C,J.4BE0
;
	LD	HL,(D.F2EA)
	INC	HL
	LD	(D.F2EA),HL
	XOR	A
	EX	DE,HL
	JR	J$4B91
;
;	-----------------
J.4BDA:	CALL	C.4A6E
;
	CALL	NC,C.4A39
;
J.4BE0:	CALL	C$F291
;
	LD	HL,(D.F2E2)
	LD	DE,(D.F23D)
	OR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H
	LD	DE,DBUF
	LD	A,(D.F306)
	OR	A
	JR	NZ,J$4BFE
;
	LD	E,(IY+14)
	LD	D,(IY+15)
J$4BFE:	CALL	C.4935
;
	LD	A,H
	OR	L
	JR	Z,J$4C15
;
	INC	BC
	EX	DE,HL
	SBC	HL,DE
	LD	DE,(D.F2E2)
J$4C0D:	XOR	A
	LD	(DE),A
	INC	DE
	DEC	HL
	LD	A,H
	OR	L
	JR	NZ,J$4C0D
;
J$4C15:	LD	HL,(D.F2E8)
	SBC	HL,BC
	JR	Z,J.4C20
;
	INC	A
	LD	(D.F2DE),A
J.4C20:	CALL	C$F294
;
	LD	HL,(D.F2EC)
	LD	(IY+28),L
	LD	(IY+29),H
	LD	HL,(D.F2EA)
	LD	(IY+30),L
	LD	(IY+31),H
J.4C35:	LD	HL,(D.F2E4)
	LD	DE,(D.F2E6)
	LD	A,B
	OR	C
	RET	Z
;
	DEC	BC
	ADD	HL,BC
	INC	BC
	RET	NC
;
	INC	DE
	RET
;
;	-----------------
J$4C45:	LD	HL,(D.F23D)
	OR	40H	; "@"
	INC	A
	JR	Z,J.4C71
;
	INC	A
	JR	Z,J.4C61
;
	INC	A
J$4C51:	JR	Z,J.4C7F
;
	LD	A,(HL)
	INC	HL
	CP	1AH
	JR	Z,J.4C7F
;
	CALL	C$5466
;
	DEC	BC
	LD	A,B
	OR	C
I$4C5F:	JR	J$4C51
;
;	-----------------
J.4C61:	LD	A,(HL)
	INC	HL
	CALL	C$5475
;
	CP	1AH
	JR	Z,J.4C7F
;
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J.4C61
;
	JR	J.4C7F
;
;	-----------------
J.4C71:	LD	A,(HL)
	INC	HL
	CP	1AH
	JR	Z,J.4C7F
;
	CALL	C.53A8
;
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J.4C71
;
J.4C7F:	LD	BC,(D.F2E8)
	JR	J.4C35
;
;	-----------------
J$4C85:	LD	C,E
	LD	B,D
	CALL	C.49B4
;
	LD	A,B
	OR	C
	JP	Z,J.4D52
;
	CALL	C.4F17
;
	JP	NC,J.4D52
;
J.4C95:	CALL	C$F297
;
	XOR	A
	LD	C,A
	LD	B,A
	INC	A
	LD	(D.F2DE),A
	JR	J.4C35
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4CA1:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	CALL	C.472D
;
	CALL	C.45C4
;
	JP	J.75C5
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4CAF:	CALL	C.4CA1
;
	CALL	C.487D
;
	PUSH	AF
	PUSH	BC
	CALL	C.547D
;
	LD	(IY+20),C
	LD	(IY+21),B
	LD	(IY+22),E
	LD	(IY+23),D
	POP	BC
	POP	AF
	JP	M,J$4C45
;
	RES	6,(IY+24)
	PUSH	BC
	CALL	C.4959
;
	POP	BC
	LD	HL,(D.F2F4)
	LD	DE,(D.F2F6)
	LD	A,B
	OR	C
	JP	Z,J$4DEE
;
	DEC	BC
	ADD	HL,BC
	JR	NC,J$4CE5
;
	INC	DE
J$4CE5:	SRL	D
	RR	E
	RR	H
	LD	L,H
	LD	H,E
	LD	B,(IX+7)
	DEC	B
	JR	Z,J$4CF9
;
J$4CF3:	SRL	H
	RR	L
	DJNZ	J$4CF3
;
J$4CF9:	PUSH	HL
	LD	L,(IY+18)
	LD	H,(IY+19)
D$4D00:	LD	D,(IY+17)
	LD	C,D
	SRL	H
	RR	L
	RR	C
	LD	B,L
	LD	A,D
	AND	01H	; 1 
	LD	H,A
	LD	L,(IY+16)
	OR	L
	JR	Z,J$4D16
;
	INC	BC
J$4D16:	CALL	C$F29A
;
	LD	(D.F2F0),BC
	LD	BC,(D.F2EC)
	CALL	C.498C
;
	LD	(D.F2EC),HL
	LD	(D.F2EA),DE
	EX	(SP),HL
	OR	A
	SBC	HL,DE
	EX	DE,HL
	POP	HL
	JR	Z,J.4D52
;
	LD	A,B
	OR	C
	JP	Z,J$4C85
;
	PUSH	BC
	LD	C,E
	LD	B,D
	CALL	C.4F17
;
	POP	BC
	JP	C,J.4C95
;
	LD	DE,(D.F2EA)
	INC	DE
	DEC	BC
	CALL	C.49B4
;
	LD	(D.F2EC),HL
	LD	(D.F2EA),DE
J.4D52:	CALL	C.4A49
;
	LD	HL,(D.F2FC)
	LD	A,H
	OR	L
	JR	Z,J.4D9D
;
	LD	DE,(D.F2EE)
	ADD	HL,DE
	LD	(D.F2EE),HL
	CALL	C.4A7E
;
	LD	A,01H	; 1 
	LD	(D.F2DF),A
	LD	A,(D.F2DD)
	LD	HL,(D.F2EC)
	LD	BC,(D.F2FC)
J$4D76:	PUSH	BC
	CALL	C.4E56
;
	PUSH	BC
	PUSH	AF
	LD	B,A
	JR	C,J$4D84
;
	LD	A,0FFH
	LD	(D.F241),A
J$4D84:	CALL	C.4755
;
	POP	AF
	POP	DE
	POP	HL
	LD	C,A
	XOR	A
	LD	B,A
	SBC	HL,BC
	JR	Z,J.4D9D
;
	LD	C,L
	LD	B,H
	LD	HL,(D.F2EA)
	INC	HL
	LD	(D.F2EA),HL
	EX	DE,HL
	JR	J$4D76
;
;	-----------------
J.4D9D:	CALL	C$F29D
;
	CALL	C.4A6E
;
	CALL	NC,C.4A49
;
	LD	HL,(D.F2E2)
	LD	DE,(D.F23D)
	OR	A
	SBC	HL,DE
	LD	DE,(D.F2F4)
	ADD	HL,DE
	LD	DE,(D.F2F6)
	JR	NC,J$4DBC
;
	INC	DE
J$4DBC:	LD	(D.F2F4),HL
	LD	(D.F2F6),DE
	LD	C,(IY+16)
	LD	B,(IY+17)
	OR	A
	SBC	HL,BC
	LD	C,(IY+18)
	LD	B,(IY+19)
	EX	DE,HL
	SBC	HL,BC
	JR	C,J$4DE7
;
J$4DD7:	PUSH	IY
	POP	HL
	LD	DE,I.0010
	ADD	HL,DE
	EX	DE,HL
	LD	HL,D.F2F4
	LD	BC,I.0004
	LDIR
J$4DE7:	LD	BC,(D.F2E8)
	JP	J.4C20
;
;	-----------------
J$4DEE:	LD	A,H
	OR	L
	OR	D
	OR	E
	JR	Z,J$4E40
;
	LD	BC,I.0001
	SBC	HL,BC
	EX	DE,HL
	DEC	BC
	SBC	HL,BC
	SRL	H
	RR	L
	RR	D
	LD	C,D
	LD	B,L
	LD	A,(IX+7)
J$4E08:	DEC	A
	JR	Z,J$4E11
;
	SRL	B
	RR	C
	JR	J$4E08
;
;	-----------------
J$4E11:	CALL	C.498C
;
	LD	A,B
	OR	C
	JR	Z,J$4E34
;
	CALL	C.4F17
;
	JP	C,J.4C95
;
J.4E1E:	LD	BC,X.0000
	LD	(D.F2E8),BC
	LD	(D.F2EA),BC
	LD	L,(IY+26)
	LD	H,(IY+27)
	LD	(D.F2EC),HL
	JR	J$4DD7
;
;	-----------------
J$4E34:	LD	BC,I.0FFF
	CALL	C.4F7D
;
J$4E3A:	DEC	DE
	LD	A,01H	; 1 
	LD	(DE),A
	JR	J.4E1E
;
;	-----------------
J$4E40:	LD	L,(IY+26)
	LD	H,(IY+27)
	LD	A,H
	OR	L
	JR	Z,J.4E1E
;
	XOR	A
	LD	(IY+26),A
	LD	(IY+27),A
	CALL	C.4F7A
;
	JR	J$4E3A
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4E56:	CALL	C$F2A0
;
	LD	D,A
	PUSH	HL
	INC	B
	DEC	B
	JR	Z,J$4E61
;
	LD	C,0FFH
J$4E61:	LD	E,C
	PUSH	DE
	LD	A,(IX+6)
	LD	(D.F2DD),A
	INC	A
	SUB	D
	LD	B,A
J$4E6C:	LD	(D.F2EC),HL
	PUSH	HL
	CALL	C.74E5
;
	POP	DE
	LD	A,C
	SUB	B
	LD	C,A
	JR	Z,J.4E86
;
	LD	B,(IX+6)
	JR	C,J$4ED2
;
	INC	B
	INC	DE
	EX	DE,HL
	SBC	HL,DE
	EX	DE,HL
	JR	Z,J$4E6C
;
J.4E86:	POP	DE
	EX	(SP),HL
	PUSH	HL
	PUSH	DE
	LD	A,E
	SUB	C
	LD	E,A
	LD	D,00H
	ADD	A,A
	LD	B,A
	LD	C,D
	POP	AF
	LD	HL,(D.F2E2)
	PUSH	HL
	ADD	HL,BC
	LD	(D.F2E2),HL
	POP	BC
	POP	HL
	PUSH	BC
	PUSH	DE
	EX	DE,HL
	LD	HL,(D.F2EC)
	SBC	HL,DE
	LD	BC,(D.F2EA)
	ADD	HL,BC
	LD	(D.F2EA),HL
	EX	DE,HL
	CALL	C.4EE3
;
	EX	DE,HL
	POP	BC
	LD	A,(D.F241)
	CP	(IX)
	LD	A,C
	SCF
	JR	NZ,J.4ECF
;
	LD	HL,(D.F23F)
	OR	A
	SBC	HL,DE
	JR	C,J.4ECF
;
	LD	H,B
	LD	L,C
	DEC	HL
	ADD	HL,DE
	LD	BC,(D.F23F)
	SBC	HL,BC
J.4ECF:	POP	HL
	POP	BC
	RET
;
;	-----------------
J$4ED2:	ADD	A,B
	LD	(D.F2DD),A
	LD	C,00H
	JR	J.4E86
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4EDA:	CALL	C.5FEF			; GETWRK

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4EDD:	LD	DE,14
	ADD	IX,DE
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4EE2:	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4EE3:	CALL	C$F2A3
;
	PUSH	BC
	LD	B,(IX+7)
	DEC	HL
	DEC	HL
J$4EEC:	DEC	B
	JR	Z,J$4EF2
;
	ADD	HL,HL
	JR	J$4EEC
;
;	-----------------
J$4EF2:	OR	L
	LD	L,A
	LD	C,(IX+12)
	LD	B,(IX+13)
	ADD	HL,BC
	POP	BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4EFD:	PUSH	DE
	POP	IY
	LD	C,(IY+32)
	LD	B,(IY+12)
	LD	E,(IY+14)
	LD	D,00H
	SLA	C
	SRL	E
	RR	B
	RR	C
	LD	HL,I.0001
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4F17:	CALL	C$F2A6
;
	PUSH	HL
J$4F1B:	PUSH	BC
	PUSH	HL
	LD	D,H
	LD	E,L
J.4F1F:	PUSH	DE
	EX	DE,HL
	LD	L,(IX+14)
	LD	H,(IX+15)
	DEC	HL
	OR	A
	SBC	HL,DE
	EX	DE,HL
	POP	DE
	JR	NC,J$4F3E
;
	LD	A,E
	OR	D
	JR	NZ,J$4F46
;
	POP	HL
	POP	HL
	POP	HL
	LD	BC,I.0FFF
	CALL	C.4F7D
;
	SCF
	RET
;
;	-----------------
J$4F3E:	INC	HL
	CALL	C.4F4E
;
	LD	A,E
	OR	D
	JR	Z,J.4F1F
;
J$4F46:	DEC	DE
	EX	DE,HL
	CALL	C.4F4E
;
	EX	DE,HL
	JR	J.4F1F
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4F4E:	PUSH	HL
	PUSH	DE
	CALL	C.74E5
;
	POP	DE
	POP	HL
	RET	NZ
;
	POP	BC
	LD	C,L
	LD	B,H
	EX	(SP),HL
	CALL	C.74D1
;
	POP	HL
	POP	BC
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$4F1B
;
	LD	BC,I.0FFF
	CALL	C.74D1
;
	POP	HL
	PUSH	HL
	CALL	C.74E5
;
	POP	BC
	LD	A,C
	OR	B
	RET	NZ
;
	LD	(IY+26),L
	LD	(IY+27),H
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4F7A:	LD	BC,X.0000
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.4F7D:	CALL	C$F2A9
;
	PUSH	HL
	CALL	C.74E5
;
	EX	(SP),HL
	CALL	C.74D1
;
	POP	HL
	LD	A,H
	OR	L
	RET	Z
;
	LD	A,H
	CP	0FH	; 15 
	JR	C,C.4F7A
;
	LD	A,L
	CP	0F8H
	JR	C,C.4F7A
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4F97:	LD	A,(D.F347)
	OR	A
	SCF
	RET	Z
;
	CP	C
	RET
;
;	-----------------
I$4F9F:	LD	BC,I$0302
	INC	B
	DEC	B
	LD	B,07H	; 7 
	EX	AF,AF'
	ADD	HL,BC
I$4FA8:	LD	BC,I$0206
	RLCA
	INC	BC
	EX	AF,AF'
	INC	B
	ADD	HL,BC
	DEC	B
	PUSH	HL
	CALL	C$7E74
;
	POP	HL
	XOR	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$4FB8:	CALL	C.429C
;
J$4FBB:	JR	C,J.5000
;
	LD	A,(D.F2B8)
	JR	Z,J$4FC4
;
	LD	A,0FFH
J$4FC4:	LD	(D.F30B),A
	LD	(D.F309),IX
	LD	DE,(D.F23D)
	LD	A,(D.F2E1)
	INC	A
	LD	(DE),A
	INC	DE
	LD	A,(HL)
	CP	05H	; 5 
	JR	NZ,J$4FDC
;
	LD	(HL),0E5H
J$4FDC:	LD	BC,X.0020
	CALL	C.F1D9
;
	CALL	C.4438
;
	LD	A,(D.F30C)
	CP	B
	JR	Z,J$4FEF
;
	JR	NC,J.5000
;
	LD	C,80H
J$4FEF:	LD	HL,(D.F23D)
	LD	DE,C.000C
	ADD	HL,DE
	LD	B,(HL)
	LD	(HL),A
	INC	HL
	LD	(HL),B
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),C
	XOR	A
	RET
;
;	-----------------
J.5000:	LD	A,0FFH
	LD	(D.F30B),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5006:	CALL	C.440E
;
	JR	C,J.5000
;
	LD	A,(D.F30B)
	CP	0FFH
	JR	Z,J.5000
;
	LD	(D.F2B8),A
	LD	IX,(D.F309)
	CALL	C.42B3
;
	JR	J$4FBB
;
;	-----------------
?.501E:	CALL	C.429C
;
	LD	A,0FFH
	RET	C
;
	PUSH	DE
	POP	IX
	LD	A,(IY+28)
	LD	C,(IY+29)
	LD	B,(IY+30)
	LD	E,(IY+31)
	ADD	A,A
	RL	C
	RL	B
	RL	E
	OR	A
	JR	Z,J.5043
;
	INC	BC
	LD	A,B
	OR	C
	JR	NZ,J.5043
;
	INC	E
J.5043:	LD	(IX+33),C
	LD	(IX+34),B
	LD	(IX+35),E
	XOR	A
	RET
;
;	-----------------
?.504E:	LD	A,(D.F347)
	LD	B,A
	XOR	A
J$5053:	SCF
	RLA
	DJNZ	J$5053
;
	RET
;
;	-----------------
?.5058:	LD	(D.F23D),DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.505D:	XOR	A
	LD	(D.F306),A
	LD	A,E
	CALL	C.4427
;
	LD	A,0FFH
	RET	C
;
	CALL	C.44DB
;
	LD	HL,I.0002
	LD	B,H
	LD	C,H
	LD	E,(IX+14)
	LD	D,(IX+15)
	LD	A,(IX+6)
	INC	A
	DEC	DE
	PUSH	AF
	PUSH	DE
	CALL	C$75F6
;
	LD	H,B
	LD	L,C
	POP	DE
	POP	AF
	LD	BC,I.0200
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5088:	EI
	LD	B,05H	; 5 
J$508B:	HALT
;
;	-----------------
?.508C:	DJNZ	J$508B
;
	DI
	RET
;
;	-----------------
I$5090:	DEC	H
	DEC	B
	EX	AF,AF'
	DEC	B
	RST	38H

;	  Subroutine MTOFF
;	     Inputs  ________________________
;	     Outputs ________________________

C.5095:	PUSH	AF
	CALL	C.517F			; enable I/O ports
	XOR	A
	OUT	(0D4H),A
	JP	J$79DF			; disable I/O ports when needed

?.509F:	LD	HL,DBUF
	LD	(D.F23D),HL
	XOR	A
	LD	(D.F247),A
	CALL	C.472D
;
	CALL	C.45C4
;
	XOR	A
	RET
;
;	-----------------
I$50B1:	DJNZ	J$50C4
;
	INC	E
	LD	H,24H	; "$"
	RLCA
	LD	B,06H	; 6 
	INC	BC
	LD	D,03H	; 3 
	INC	H
	DEC	B
	INC	DE
	DEC	BC
	INC	B
	INC	BC
	LD	D,C
	RST	38H
J$50C4:	LD	A,(D.F247)
	RET
;
;	-----------------
?.50C8:	CALL	C.4EFD
;
	LD	(IY+33),L
	LD	(IY+34),H
	LD	(IY+35),E
	RET
;
;	-----------------
?.50D5:	LD	A,(D.F347)
	CP	E
	RET	C
;
	RET	Z
;
	LD	HL,D.F247
	LD	(HL),E
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.50E0:	PUSH	DE
	LD	A,(D.F237)
	LD	(D.F238),A
	XOR	A
	LD	(D.F239),A
	LD	H,D
	LD	L,E
	LD	B,A
	LD	C,(HL)
	INC	HL
	LD	D,A
	LD	E,(HL)
	INC	HL
	LD	IX,I.F459
	LD	A,E
	CP	C
	JR	NC,J$5103
;
	PUSH	HL
	ADD	HL,DE
	LD	A,(HL)
	POP	HL
	CP	0DH	; 13 
	JR	Z,J.5104
;
J$5103:	LD	E,D
J.5104:	CALL	C$F2AC
;
	CALL	C.544E
;
J.510A:	PUSH	HL
	PUSH	BC
	LD	HL,I$5374
	LD	BC,I.0011
	CPIR
	ADD	HL,BC
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,C
	POP	BC
	EX	(SP),HL
	RET
;
;	-----------------
?.511E:	CALL	C.544E
;
	CP	40H	; "@"
	JR	C,J.510A
;
	CP	60H	; "`"
	JR	NC,J.510A
;
	PUSH	AF
	LD	A,B
	INC	A
	CP	C
	JR	NC,J.515E
;
	LD	A,01H	; 1 
	LD	(IX),A
	INC	IX
	INC	B
	CALL	C.535D
;
	POP	AF
	PUSH	AF
	LD	A,B
	CP	C
	JR	NC,J.515E
;
	POP	AF
	LD	(IX),A
	INC	IX
	INC	B
	CALL	C.535D
;
	LD	A,(D.F239)
	OR	A
	JR	NZ,J.5104
;
	INC	D
	LD	A,E
	CP	D
	JR	C,J.5104
;
	LD	A,(HL)
	DEC	A
	INC	HL
	JR	NZ,J.5104
;
	INC	D
	INC	HL
	JR	J.5104
;
;	-----------------
J.515E:	POP	AF
	LD	A,07H	; 7 
	CALL	C.53A8
;
	JR	J.5104
;
;	-----------------
?.5166:	POP	DE
	LD	A,(D.F238)
	LD	B,A
	LD	A,(D.F237)
	SUB	B
	JR	Z,J$5177
;
	LD	B,A
J$5172:	CALL	C.531E
;
	DJNZ	J$5172
;
J$5177:	JP	C.50E0
;
;	-----------------
I$517A:	CALL	C.5183
;
J.517D:	JR	J.5104

;	  Subroutine enable I/O ports
;	     Inputs  ________________________
;	     Outputs ________________________

C.517F:	LD	(D$6205),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5183:	LD	A,0DH	; 13 
	CALL	C.53A8
;
	LD	A,0AH	; 10 
	JP	C.53A8
;
;	-----------------
?.518D:	POP	DE
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$518E:	CALL	C.53A8
;
	PUSH	DE
	INC	DE
	LD	A,B
	LD	(DE),A
	CP	C
	PUSH	AF
	INC	DE
	LD	C,B
	XOR	A
	LD	B,A
	OR	C
	JR	Z,J$51A3
;
	LD	HL,I.F459
	LDIR
J$51A3:	POP	AF
	JR	Z,J$51A9
;
	LD	A,0DH	; 13 
	LD	(DE),A
J$51A9:	POP	DE
	RET
;
;	-----------------
?.51AB:	INC	B
	DEC	B
	JR	Z,J.51D3
;
	DEC	B
	DEC	IX
	CALL	C.531E
;
	INC	B
	DEC	B
	JR	Z,J$51C5
;
	DEC	B
	DEC	IX
	LD	A,(IX)
	DEC	A
	JR	Z,J.51D3
;
	INC	B
	INC	IX
J$51C5:	LD	A,(IX)
	CP	20H	; " "
	JR	NC,J.51D3
;
	CP	09H	; 9 
	JR	Z,J$51F2
;
	CALL	C.531E
;
J.51D3:	LD	A,(D.F239)
	OR	A
	JR	NZ,J.517D
;
	INC	D
	DEC	D
	JR	Z,J.517D
;
	DEC	D
	LD	A,D
	CP	E
	JR	NC,J.517D
;
	DEC	HL
	LD	A,D
	CP	01H	; 1 
	JR	C,J.517D
;
	DEC	HL
	LD	A,(HL)
	DEC	A
	INC	HL
	JR	NZ,J.517D
;
	DEC	D
	DEC	HL
	JR	J.517D
;
;	-----------------
J$51F2:	PUSH	HL
	PUSH	BC
	LD	A,(D.F238)
	LD	C,A
	INC	B
	DEC	B
	JR	Z,J$5211
;
	LD	HL,I.F459
J$51FF:	LD	A,(HL)
	INC	HL
	CP	01H	; 1 
	JR	Z,J.520F
;
	INC	C
	CP	20H	; " "
	JR	NC,J.520F
;
	CP	09H	; 9 
	JR	Z,J$5221
;
	INC	C
J.520F:	DJNZ	J$51FF
;
J$5211:	LD	A,(D.F237)
	SUB	C
	JR	Z,J$521D
;
	LD	B,A
J$5218:	CALL	C.531E
;
I$521B:	DJNZ	J$5218
;
J$521D:	POP	BC
	POP	HL
I.521F:	JR	J.51D3
;
;	-----------------
J$5221:	LD	A,C
	ADD	A,07H	; 7 
	AND	0F8H
	LD	C,A
	JR	J.520F
;
;	-----------------
?.5229:	LD	A,(D.F239)
	XOR	01H	; 1 
	LD	(D.F239),A
	JP	J.5104
;
;	-----------------
?.5234:	LD	A,40H	; "@"
	POP	DE
	CALL	C$518E
;
	CALL	C.5183
;
	LD	A,(D.F238)
	OR	A
	JP	Z,C.50E0
;
	LD	B,A
	LD	A,20H	; " "
J$5247:	CALL	C.53A8
;
	DJNZ	J$5247
;
	JP	C.50E0
;
;	-----------------
?.524F:	LD	A,0FFH
	JR	J.5284
;
;	-----------------
?.5253:	CALL	C.52B2
;
	JP	C,J.5104
;
	PUSH	BC
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	POP	BC
	ADD	A,D
	LD	D,A
	JP	J.5104
;
;	-----------------
?.5264:	CALL	C.52B2
;
	JP	C,J.5104
;
	JR	J.5284
;
;	-----------------
?.526C:	LD	A,D
	CP	E
	JP	NC,J.5104
;
	INC	D
	LD	A,(HL)
	DEC	A
	INC	HL
	JP	NZ,J.5104
;
	INC	D
	INC	HL
	JP	J.5104
;
;	-----------------
?.527D:	LD	A,(HL)
	DEC	A
	LD	A,01H	; 1 
	JR	NZ,J.5284
;
	INC	A
J.5284:	PUSH	AF
	XOR	A
	LD	(D.F239),A
	LD	A,B
	CP	C
	JR	NC,J.52AE
;
	LD	A,D
	CP	E
	JR	NC,J.52AE
;
	LD	A,(HL)
	CP	01H	; 1 
	JR	NZ,J$529C
;
	LD	A,B
	INC	A
	CP	C
	JR	NC,J.52AE
;
	LD	A,(HL)
J$529C:	INC	HL
	LD	(IX),A
	INC	IX
	CALL	C.535D
;
	INC	B
	INC	D
	POP	AF
	DEC	A
	JR	NZ,J.5284
;
	JP	J.5104
;
;	-----------------
J.52AE:	POP	AF
	JP	J.5104
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.52B2:	CALL	C.544E
;
	CP	01H	; 1 
	JR	NZ,C.52EE
;
	CALL	C.544E
;
	CP	40H	; "@"
	JR	C,C.52EE
;
	CP	60H	; "`"
	JR	NC,C.52EE
;
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	IY,X.0000
J$52CB:	SCF
	PUSH	AF
	LD	A,01H	; 1 
	CALL	C.52EE
;
	JR	C,J$52E9
;
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	ADD	A,D
	LD	D,A
	PUSH	IY
	POP	AF
	ADD	A,C
	PUSH	AF
	POP	IY
	INC	HL
	POP	AF
	CP	(HL)
	DEC	HL
	JR	NZ,J$52CB
;
	PUSH	IY
J$52E9:	POP	AF
	POP	BC
	POP	DE
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.52EE:	PUSH	BC
	PUSH	AF
	LD	A,E
	SUB	D
	JR	C,J.531A
;
	JR	Z,J.531A
;
	DEC	A
	JR	Z,J.531A
;
	LD	C,A
	LD	B,00H
	POP	AF
	PUSH	HL
	PUSH	AF
	LD	A,(HL)
	DEC	A
	JR	NZ,J$5305
;
	INC	HL
	DEC	C
J$5305:	POP	AF
	INC	C
	DEC	C
	JR	NZ,J$530E
;
	POP	HL
	POP	BC
	SCF
	RET
;
;	-----------------
J$530E:	INC	HL
	CPIR
	POP	HL
	JR	NZ,J$531B
;
	LD	A,E
	SUB	D
	DEC	A
	SUB	C
	POP	BC
	RET
;
;	-----------------
J.531A:	POP	AF
J$531B:	POP	BC
	SCF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.531E:	LD	A,08H	; 8 
	CALL	C.53A8
;
	LD	A,20H	; " "
	CALL	C.53A8
;
	LD	A,08H	; 8 
	JR	C.53A8
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.532C:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	CALL	C.4EDA
;
	LD	BC,I.0400
J$5337:	LD	A,(IX)
	INC	A
	JR	Z,J$533E
;
	INC	C
J$533E:	INC	IX
	DJNZ	J$5337
;
	LD	A,C
	POP	IX
	POP	HL
	POP	DE
	POP	BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5349:	LD	BC,I$0C00
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.534C:	LD	(HL),C
	INC	HL
	DJNZ	C.534C
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5351:	LD	C,4EH	; "N"
	JR	C.534C
;
;	-----------------
?.5355:	NOP
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5356:	LD	A,D
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5357:	DEC	A
	RET	P
;
	LD	A,(D.F247)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.535D:	CP	20H	; " "
	JR	NC,C.53A8
;
	CP	09H	; 9 
	JR	Z,C.53A8
;
	CP	01H	; 1 
	JR	Z,C.53A8
;
	PUSH	AF
	LD	A,5EH	; "^"
	CALL	C.53A8
;
	POP	AF
	OR	40H	; "@"
	JR	C.53A8
;
;	-----------------
I$5374:	LD	B,7FH
	EX	AF,AF'
	DEC	C
	LD	A,(BC)
	DEC	D
	DEC	BC
	INC	C
	DEC	DE
	LD	(DE),A
	JR	J$539C
;
;	-----------------
?.5380:	DEC	E
	LD	E,1FH
	LD	BC,I$3B08
	LD	D,C
	LD	E,51H	; "Q"
	LD	C,A
	LD	D,D
	LD	H,(HL)
	LD	D,C
	XOR	E
	LD	D,C
	LD	A,L
	LD	D,D
	LD	H,H
	LD	D,D
	ADD	HL,HL
	LD	D,D
	LD	H,(HL)
	LD	D,C
	LD	D,E
	LD	D,D
	INC	(HL)
	LD	D,D
	LD	H,(HL)
J$539C:	LD	D,C
	LD	A,D
	LD	D,C
	ADC	A,L
	LD	D,C
	XOR	E
	LD	D,C
	LD	L,H
	LD	D,D
	INC	B
	LD	D,C
	LD	A,E
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.53A8:	CALL	C$F2AF
;
	CP	0BH	; 11 
	JR	Z,J.53E8
;
	CP	0CH	; 12 
	JR	Z,J.53E8
;
	CP	1CH
	JR	Z,J.53D5
;
	CP	1DH
	JR	Z,J.53F0
;
	CP	0DH	; 13 
	JR	Z,J.53E8
;
	CP	08H	; 8 
	JR	Z,J.53F0
;
	CP	09H	; 9 
	JR	Z,J.53F8
;
	CP	7FH
	JR	Z,J.53F0
;
	CP	20H	; " "
	JR	C,J.53D5
;
	PUSH	HL
	LD	HL,D.F237
	INC	(HL)
	POP	HL
J.53D5:	PUSH	BC
	LD	B,A
	CALL	C.5412
;
	LD	A,B
	CALL	C.408F
;
	LD	A,(D.F23B)
	OR	A
	LD	A,B
	POP	BC
	RET	Z
;
	JP	J.409F
;
;	-----------------
J.53E8:	PUSH	AF
	XOR	A
	LD	(D.F237),A
	POP	AF
	JR	J.53D5
;
;	-----------------
J.53F0:	PUSH	HL
	LD	HL,D.F237
	DEC	(HL)
	POP	HL
	JR	J.53D5
;
;	-----------------
J.53F8:	LD	A,20H	; " "
	CALL	C.53A8
;
	LD	A,(D.F237)
	AND	07H	; 7 
	JR	NZ,J.53F8
;
	RET
;
;	-----------------
J$5405:	CP	10H	; 16 
	JR	Z,C.541D
;
	CP	0EH	; 14 
	JR	Z,C.541D
;
	CP	03H	; 3 
	JR	Z,C.541D
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5412:	CALL	C.4034
;
	RET	Z
;
	CP	13H	; 19 
	JR	NZ,J$5405
;
	CALL	C.4078
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.541D:	CALL	C.4078
;
	CP	10H	; 16 
	JR	Z,J$5431
;
	CP	0EH	; 14 
	JR	Z,J$5437
;
	CP	03H	; 3 
	RET	NZ
;
	LD	HL,(D.F325)
	JP	C.F1E8
;
;	-----------------
J$5431:	LD	A,01H	; 1 
I.5432	EQU	$-1
	LD	(D.F23B),A
	RET
;
;	-----------------
J$5437:	XOR	A
	LD	(D.F23B),A
	RET
;
;	-----------------
?.543C:	CALL	C.5412
;
	LD	A,00H
	RET	Z
;
	OR	0FFH
	RET
;
;	-----------------
?.5445:	CALL	C.544E
;
	PUSH	AF
	CALL	C.53A8
;
	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.544E:	CALL	C.541D
;
	JR	Z,C.544E
;
	RET
;
;	-----------------
?.5454:	LD	A,E
	CP	0FFH
	JP	NZ,C.408F
;
	CALL	C.4034
;
	JP	NZ,C.4078
;
	XOR	A
	RET
;
;	-----------------
?.5462:	JP	C.4078
;
;	-----------------
?.5465:	LD	A,E
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5466:	PUSH	AF
	CALL	C.5412
;
	POP	AF
	JP	J.409F
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$546E:	CALL	C.5412
;
	JP	J$F371
;
;	-----------------
?.5474:	LD	A,E
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5475:	PUSH	AF
	CALL	C.5412
;
	POP	AF
	JP	J$F374
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.547D:	CALL	C$F2B2
;
	CALL	C.54A7
;
	LD	A,C
	ADD	A,A
	ADD	A,A
	ADD	A,A
	RL	B
	ADD	A,A
	RL	B
	ADD	A,A
	RL	B
	SRL	D
	OR	D
	LD	E,A
	LD	D,B
	LD	BC,(D.F249)
	LD	A,C
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	RL	B
	LD	C,A
	LD	A,(D.F248)
	OR	C
	LD	C,A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.54A7:	CALL	C$417B
;
	JR	C,J$54F2
;
	PUSH	DE
	PUSH	HL
	LD	DE,(D.F24C)
	OR	A
	SBC	HL,DE
	POP	HL
	POP	DE
	RET	Z
;
	LD	(D.F24C),HL
	PUSH	BC
	PUSH	DE
	LD	C,L
	LD	B,H
	LD	DE,I.05B5
	CALL	C.4935
;
	LD	A,C
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	B,00H
	LD	DE,I.551B
	CALL	C.54FC
;
	SRL	A
	JR	NC,J$54D9
;
	LD	DE,I.00C8
	ADD	HL,DE
J$54D9:	CALL	C.550A
;
	LD	A,01H	; 1 
	LD	DE,I.F22B
	CALL	C.54FC
;
	LD	(D.F249),A
	INC	L
	LD	A,L
	LD	(D.F248),A
J$54EC:	CALL	C$5588
;
	POP	DE
	POP	BC
	RET
;
;	-----------------
J$54F2:	PUSH	BC
	PUSH	DE
	LD	HL,(D.F24A)
I$54F7:	CALL	C.559D
;
	JR	J$54EC
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.54FC:	EX	DE,HL
	LD	C,(HL)
	INC	HL
	EX	DE,HL
	OR	A
	SBC	HL,BC
	JR	C,J$5508
;
	INC	A
	JR	C.54FC
;
;	-----------------
J$5508:	ADD	HL,BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.550A:	CALL	C$F2B5
;
	LD	(D.F24A),A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5510:	AND	03H	; 3 
	LD	A,1CH
	JR	NZ,J$5517
;
	INC	A
J$5517:	LD	(D$F22C),A
	RET
;
;	-----------------
I.551B:	RET	Z
;
	AND	(HL)
	RET	Z
;
	AND	L
	RET	Z
;
	AND	L
	RET	Z
;
	AND	L
I$5523:	NOP
	LD	(BC),A
	RRCA
	INC	B
	DEFB	0,0
	LD	BC,I.0200
I$552C:	LD	H,E
	LD	BC,I$02CA
	INC	A
	LD	BC,I$027B
	LD	H,B
	LD	BC,I.0163
	LD	A,(D$3C01)
	LD	BC,I$32AF
C$553C	EQU	$-2
	LD	B,0F3H
	CALL	C.54A7
D$5541	EQU	$-2
;
	LD	HL,(D.F24A)
	LD	DE,I$07BC
	ADD	HL,DE
	LD	DE,(D.F248)
	LD	A,(D.F24E)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5552:	LD	BC,I$F844
	ADD	HL,BC
	JR	NC,J.559A
;
	LD	A,H
	OR	A
	JR	NZ,J.559A
;
	LD	A,L
	CP	78H	; "x"
	JR	NC,J.559A
;
	CALL	C$5510
;
	INC	E
	DEC	E
	JR	Z,J.559A
;
	LD	A,D
	OR	A
	JR	Z,J.559A
;
	CP	0DH	; 13 
	JR	NC,J.559A
;
	PUSH	HL
	LD	HL,I$F22A
	ADD	A,L
	LD	L,A
	JR	NC,J$5579
;
	INC	H
J$5579:	LD	A,(HL)
	POP	HL
	CP	E
	JR	C,J.559A
;
	LD	(D.F248),DE
	CALL	C.559D
;
	CALL	C$4115
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5588:	LD	BC,(D.F24C)
	LD	DE,I.0007
	INC	BC
	INC	BC
	CALL	C.4935
;
	LD	A,L
	LD	(D.F24E),A
I$5597	EQU	$-1
	XOR	A
	RET
;
;	-----------------
J.559A:	LD	A,0FFH
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.559D:	LD	A,L
	CALL	C.550A
;
	LD	C,L
	SRL	C
	SRL	C
	LD	B,00H
	LD	DE,I.05B5
	CALL	C.491C
;
	LD	L,C
	LD	H,B
	LD	A,(D.F24A)
	AND	03H	; 3 
	ADD	A,A
	LD	DE,I.551B
	LD	B,00H
	INC	A
	CALL	C.55D2
;
	LD	DE,I.F22B
	LD	A,(D.F249)
	CALL	C.55D2
;
	LD	A,(D.F248)
	DEC	A
	LD	C,A
	ADD	HL,BC
	LD	(D.F24C),HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.55D2:	DEC	A
	RET	Z
;
	EX	DE,HL
	LD	C,(HL)
	INC	HL
	EX	DE,HL
	ADD	HL,BC
	JR	C.55D2
;
;	-----------------
?.55DB:	XOR	A
	LD	(D.F306),A
	CALL	C.54A7
;
	LD	H,B
	LD	L,C
	XOR	A
	RET
;
;	-----------------
?.55E6:	LD	B,H
	LD	C,L
	LD	A,B
	CP	18H
	JR	NC,J.559A
;
	LD	A,3BH	; ";"
	CP	C
	JR	C,J.559A
;
	CP	D
	JR	C,J.559A
;
	LD	A,E
	CP	64H	; "d"
	JR	NC,J.559A
;
	CALL	C$4130
;
	XOR	A
	RET
;
;	-----------------
?.55FF:	LD	A,E
	LD	(D.F30D),A
	RET
;
;	-----------------
J$5604:	LD	A,(HL)
	CP	20H	; " "
	SCF
	RET	Z
;
	LD	BC,I$0802
	CP	0E5H
	JR	NZ,J.5622
;
	LD	A,05H	; 5 
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
I$5616:	LD	A,0E5H
	CALL	C.5681
;
	JR	NC,J.5622
;
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
J.5622:	LD	A,(HL)
	CALL	C.5681
;
	JR	NC,J$5631
;
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	SCF
	RET	Z
;
	LD	A,(HL)
	JR	J$5667
;
;	-----------------
J$5631:	LD	A,(D.F30E)
	AND	A
	LD	A,(HL)
	JR	Z,J.564C
;
	CP	80H
	JR	C,J.564C
;
	CP	0BAH
	JR	NC,J.564C
;
	PUSH	HL
	PUSH	BC
	LD	C,A
	LD	B,00H
	LD	HL,I$5616
	ADD	HL,BC
	LD	A,(HL)
	POP	BC
	POP	HL
J.564C:	CP	61H	; "a"
	JR	C,J.5656
;
	CP	7BH	; "{"
	JR	NC,J.5656
;
	SUB	20H	; " "
J.5656:	CP	20H	; " "
	RET	C
;
	PUSH	HL
	PUSH	BC
	LD	HL,I$5677
	LD	BC,I.000A
	CPIR
	POP	BC
	POP	HL
	SCF
	RET	Z
;
J$5667:	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J.5622
;
	LD	B,03H	; 3 
	DEC	C
	JR	NZ,J.5622
;
	OR	A
	LD	A,(HL)
	LD	(D.F30C),A
	RET
;
;	-----------------
I$5677:	LD	L,22H	; """
	CPL
	LD	E,E
	LD	E,L
	LD	A,(D.3D2B)
	DEC	SP
	INC	L
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5681:	PUSH	HL
	LD	HL,I.F30F
	CP	(HL)
	CCF
	JR	NC,J.5694
;
	INC	HL
	CP	(HL)
	JR	C,J.5694
;
	INC	HL
	CP	(HL)
	CCF
	JR	NC,J.5694
;
	INC	HL
	CP	(HL)
J.5694:	POP	HL
	RET
;
;	-----------------
?.5696:	ADD	A,B
	SBC	A,D
	LD	B,L
	LD	B,C
	ADC	A,(HL)
	LD	B,C
	ADC	A,A
	ADD	A,B
	LD	B,L
	LD	B,L
	LD	B,L
	LD	C,C
	LD	C,C
	LD	C,C
	ADC	A,(HL)
	ADC	A,A
	SUB	B
	SUB	D
	SUB	D
	LD	C,A
	SBC	A,C
	LD	C,A
	LD	D,L
	LD	D,L
	LD	E,C
	SBC	A,C
	SBC	A,D
	SBC	A,E
	SBC	A,H
	SBC	A,L
	SBC	A,(HL)
	SBC	A,A
	LD	B,C
	LD	C,C
	LD	C,A
	LD	D,L
	AND	L
	AND	L
	AND	(HL)
	AND	A
	XOR	B
	XOR	C
	XOR	D
	XOR	E
	XOR	H
	XOR	L
	XOR	(HL)
	XOR	A
	OR	B
	OR	B
	OR	D
	OR	D
	OR	H
	OR	H
	OR	(HL)
	OR	(HL)
	CP	B
	CP	B
J$56D0:	XOR	A
	LD	B,A
	RET
;
;	-----------------
?.56D3:	EI
	LD	A,01H	; 1 
	LD	(D.F306),A
	LD	A,C
	CP	31H	; "1"
	JR	NC,J$56D0
;
	SUB	11H	; 17 
	JR	NZ,J$56E6
;
	LD	(D.F307),DE
J$56E6:	DEC	A
	JR	NZ,J$56ED
;
	LD	DE,(D.F307)
J$56ED:	PUSH	HL
	LD	HL,I$5700
	EX	(SP),HL
	PUSH	HL
	LD	HL,I.570D
	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	B,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,B
	EX	(SP),HL
	RET
;
;	-----------------
I$5700:	PUSH	AF
	LD	A,(D.F306)
	OR	A
	JR	Z,J$570B
;
	POP	AF
	LD	L,A
	LD	H,B
	RET
;
;	-----------------
J$570B:	POP	AF
	RET
;
;	-----------------
I.570D:	AND	A
	LD	B,B
	LD	B,L
	LD	D,H
	AND	A
	LD	D,E
	LD	L,(HL)
	LD	D,H
	LD	(HL),H
	LD	D,H
	LD	H,L
	LD	D,H
	LD	D,H
	LD	D,H
	LD	H,D
	LD	D,H
	LD	C,(HL)
	LD	D,H
	RET
;
;	-----------------
?.5720:	POP	AF
	RET	PO
;
	LD	D,B
	INC	A
	LD	D,H
	RST	28H
;
	LD	B,C
	SBC	A,A
	LD	D,B
	PUSH	DE
	LD	D,B
	LD	H,D
	LD	B,H
	LD	L,A
	LD	B,L
	CP	B
	LD	C,A
	LD	B,50H	; "P"
	LD	L,H
	LD	B,E
	LD	(HL),L
	LD	B,A
	LD	A,L
	LD	B,A
	DEC	E
	LD	B,(HL)
	SUB	D
	LD	B,E
	LD	C,(HL)
	LD	D,B
	CALL	NZ,C$5850
;
	LD	D,B
	LD	E,L
	LD	D,B
	RET	NC
;
	LD	D,(HL)
	RET	NC
;
	LD	D,(HL)
	RET	NC
;
	LD	D,(HL)
	RET	NC
;
	LD	D,(HL)
	RET	NC
;
	LD	D,(HL)
	ADC	A,B
	LD	B,A
	SUB	E
	LD	B,A
	LD	E,50H	; "P"
	RET	Z
;
	LD	D,B
	RET	NC
;
	LD	D,(HL)
	CP	(HL)
	LD	B,A
	OR	D
	LD	B,A
	POP	DE
	LD	B,A
	RET	NC
;
	LD	D,(HL)
	INC	A
	LD	D,L
	LD	D,D
	LD	D,L
	IN	A,(55H)
	AND	55H	; "U"
	RST	38H
	LD	D,L
	CP	D
	LD	B,(HL)
	JR	NZ,J$57B6
;
	CALL	C$7B87
;

C$576F:	DI
	LD	A,(D.FD99)
	AND	A
	RET	M
	JP	NZ,J$5823
	LD	HL,I$FB20
	BIT	0,(HL)
	JR	NZ,J$578E
	SET	0,(HL)
	LD	HL,I$FFCA
	LD	B,0FH	; 15 
J$5789:	LD	(HL),0C9H
	INC	HL
	DJNZ	J$5789
J$578E:	LD	HL,(D.FC48)
	LD	DE,I$C001
	RST	20H
	JR	NC,J$57A3
	LD	A,06H	; 6 
	CALL	C.0141
	DI
	RRCA
	JR	C,J$57A9
	LD	A,07H	; 7 
	RST	18H
;
J$57A3:	LD	A,0FFH
	LD	(D.FD99),A
	RET
;
;	-----------------
J$57A9:	LD	HL,I$F392
	LD	DE,I.F1C9
	AND	A
	SBC	HL,DE
	CALL	NC,C.5F0B
;
	RET	C
;
J$57B6:	PUSH	HL
	XOR	A
	LD	HL,I.F1C9
	LD	BC,I$01B7
	CALL	C.58E3
	LD	(D.F6AB),BC
	LD	HL,I.FB21
	LD	C,14H	; 20 
	CALL	C.58E3
	LD	HL,C.F24F
	LD	C,69H	; "i"
	LD	A,0C9H
	CALL	C.58E3
	LD	A,0DBH
	LD	HL,I$C9A8
	LD	(X.F365),A
	LD	(D$F366),HL
	LD	A,06H	; 6 
	CALL	C.0141
	AND	02H	; 2 
	LD	(D.F33F),A
	LD	A,07H	; 7 
	RST	18H
J$57EF:	LD	A,(D.F313)
	CP	13H	; 19 
	JR	NC,J$580C
	LD	HL,I$58DE
	LD	DE,I.FECB
	LD	BC,5
	LDIR
	CALL	C.5FE0
	LD	(D$FECC),A
	LD	A,13H	; 19 
	LD	(D.F313),A
J$580C:	POP	DE
	LD	A,(D$002D)
	CP	03H	; 3 
	JR	NZ,J.583F
	XOR	A
	CALL	C.0141
	BIT	1,A
	JR	NZ,J.583F
	LD	A,23H	; "#"
	LD	(D.F313),A
	JR	J.583F
;
;	-----------------
J$5823:	LD	HL,I.FB21
	LD	B,04H	; 4 
	XOR	A
J$5829:	ADD	A,(HL)
	JP	C,J.5EF3
	INC	HL
	INC	HL
	DJNZ	J$5829
	CP	09H	; 9 
	RET	NC
	LD	HL,I.0012
	CALL	C.5F0B
	RET	C
	EX	DE,HL
	PUSH	DE
	JR	J$57EF
;
;	-----------------
J.583F:	CALL	C.5FFA
;
	LD	(HL),E
	INC	HL
	LD	(HL),D
	LD	HL,(D.F6AB)
	LD	DE,I.0200
	RST	20H
;
	JR	NC,J$5852
;
	LD	(D.F6AB),DE
C$5850	EQU	$-2
J$5852:	CALL	C$7BD4
;
	LD	DE,I.FB21
	LD	BC,I.0400
J$585B:	LD	A,(DE)
	AND	A
	JR	Z,J$5868
;
	ADD	A,C
	LD	C,A
	INC	DE
	INC	DE
	DJNZ	J$585B
;
	JP	J.5EF3
;
;	-----------------
J$5868:	PUSH	BC
	PUSH	DE
	CALL	C.5FE0
;
	INC	DE
	LD	(DE),A
	POP	DE
	POP	BC
	LD	A,(D.F33F)
	AND	A
	LD	A,C
	CALL	C.7B67
;
	ADD	A,L
	CP	07H	; 7 
	LD	A,L
	JR	C,J$5882
;
	LD	A,09H	; 9 
	SUB	C
J$5882:	LD	(DE),A
	PUSH	BC
	PUSH	AF
	CALL	C.5FEF			; GETWRK
	POP	AF
	LD	(IX+5),A
	POP	BC
	LD	B,00H
	LD	HL,I.F355
	ADD	HL,BC
	ADD	HL,BC
	PUSH	HL
	LD	A,(DE)
	OR	A
	JR	Z,J$58D3
;
	PUSH	AF
	LD	C,A
	LD	DE,I.0015
	CALL	C.491C
;
	LD	L,C
	LD	H,B
	CALL	C.5EEF
;
	EX	DE,HL
	POP	BC
	XOR	A
	POP	HL
J$58AA:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	PUSH	HL
	PUSH	BC
	PUSH	DE
	PUSH	AF
	LD	HL,(D.F34D)
	PUSH	HL
	LD	HL,I$FD00
	ADD	HL,SP
	LD	(D.F34D),HL
	EX	DE,HL
	LD	B,0F9H
	CALL	C.7CFC
	POP	HL
	LD	(D.F34D),HL
	POP	AF
	POP	HL
	LD	DE,I.0015
	ADD	HL,DE
	EX	DE,HL
	POP	BC
	POP	HL
	INC	A
	DJNZ	J$58AA
;
J$58D3:	CALL	C$7347
;
	CALL	C$7BF7
;
	LD	HL,D.FD99
	INC	(HL)
	RET
;
;	-----------------
I$58DE:	RST	30H
;
	NOP
	EX	DE,HL
	LD	E,B
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.58E3:	LD	D,H
	LD	E,L
	INC	DE
	LD	(HL),A
	DEC	BC
	LDIR
	RET
;
;	-----------------
?.58EB:	LD	HL,I.FECB
	LD	B,05H	; 5 
J$58F0:	LD	(HL),0C9H
	INC	HL
	DJNZ	J$58F0
;
	LD	HL,D.FD99
	XOR	A
	CP	(HL)
	LD	(HL),A
	RET	P
;
	CALL	C$6207
;
	LD	(D.F348),A
	LD	HL,J.72D9
	LD	DE,I.F1C9
	LD	BC,FCB2.1
	LDIR
	LD	HL,I$0034
	LD	DE,I.F30F
	LD	BC,I.0004
	LDIR
	LD	A,(D.002B)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	07H	; 7 
	LD	(D.F30E),A
	LD	A,0FFH
	LD	(D.F241),A
	LD	(D.F246),A
	LD	(D$F24D),A
	LD	A,0DH	; 13 
	LD	(D$F55B),A
	LD	A,07H	; 7 
	LD	(D.F345),A
	LD	HL,I$23AC
	LD	(D.F33B),HL
	LD	B,08H	; 8 
	LD	HL,X.F368
J$5944:	LD	(HL),0C3H
	INC	HL
	INC	HL
	INC	HL
	DJNZ	J$5944
;
	LD	HL,(D.F6AB)
	PUSH	HL
	CALL	C.5EEF
;
	LD	(D.F34D),HL
	LD	(D.F34F),HL
	POP	HL
	CALL	C.5EEF
;
	LD	(D.F351),HL
	LD	(D.F349),HL
	LD	HL,I$0601
	CALL	C.5EEF
;
	LD	(D.F349),HL
	LD	(HL),0FFH
	INC	HL
	CALL	C.74C2
;
	LD	(IX+2),L
	LD	(IX+3),H
	LD	(IX),0FFH
	LD	(IX+1),0FFH
	LD	HL,I.FB21
	LD	B,04H	; 4 
	XOR	A
J$5985:	ADD	A,(HL)
	JP	C,J.5EF3
;
	INC	HL
	INC	HL
	DJNZ	J$5985
;
	CP	09H	; 9 
	JP	NC,J.5EF3
;
	LD	(D.F347),A
	OR	A
	JP	Z,J$59B8
;
	LD	B,A
	LD	C,00H
	LD	HL,I.F355
J$599F:	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	HL
	PUSH	DE
	POP	IX
	LD	(IX),C
	INC	C
	PUSH	BC
	LD	(IX+19),00H
	LD	(IX+20),00H
	POP	BC
	POP	HL
	DJNZ	J$599F
;
J$59B8:	LD	HL,I.F327
	LD	(HL),3EH	; ">"
	INC	HL
	LD	(HL),1AH
	LD	B,08H	; 8 
J$59C2:	INC	HL
	LD	(HL),0C9H
	DJNZ	J$59C2
;
	LD	HL,I.F327
	LD	(D$F372),HL
	LD	L,2CH	; ","
	LD	(D$F375),HL
	LD	L,31H	; "1"
	LD	(D$F37E),HL
	LD	HL,I$7D2F
	LD	A,(D.FCC1)
	CALL	C.000C
;
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	L,A
	INC	HL
	LD	A,(D.FCC1)
	CALL	C.000C
;
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	H,A
	LD	IY,(D.FCC0)
	CALL	C.001C
;
	CALL	C$7C43
;
	CALL	C$40B8
;
	CALL	C$5CC2
;
	LD	A,(D.FCC1)
	LD	(D.F341),A
	LD	(D.F342),A
	CALL	C$5FC5
;
	LD	(D.F343),A
	CALL	C$5FC2
;
	LD	(D$F344),A
	LD	C,00H
	CALL	C.5E79
;
	JR	C,J$5A1A
;
	LD	(D.F341),A
J$5A1A:	LD	C,40H	; "@"
	CALL	C.5E79
;
	JR	C,J$5A24
;
	LD	(D.F342),A
J$5A24:	LD	SP,I.C200
	LD	A,(D$FEDA)
	CP	0C9H
	JR	Z,J$5A34
;
	LD	IX,I$7D17
	JR	J$5A46
;
;	-----------------
J$5A34:	LD	HL,I$FCC9
	LD	B,40H	; "@"
J$5A39:	LD	A,(HL)
	ADD	A,A
	JR	C,J$5A42
;
	INC	HL
	DJNZ	J$5A39
;
	JR	J$5A4C
;
;	-----------------
J$5A42:	LD	IX,I$7E14
J$5A46:	CALL	C.5C6C
;
	JP	C.0159
;
;	-----------------
J$5A4C:	LD	HL,J.5B91
	PUSH	HL
	CALL	C$4EE2
;
	RET	C
;
	CALL	C.5B47
;
	RET	C
;
	CALL	C$5B38
;
	LD	HL,(D.FC48)
	LD	DE,I$8000
	RST	20H
;
	RET	NZ
;
	LD	HL,D.F341
	LD	A,(D.FCC1)
	CP	(HL)
	RET	Z
;
	INC	HL
	CP	(HL)
	RET	Z
;
	LD	A,01H	; 1 
J$5A70:	PUSH	AF
	XOR	A
	CALL	C.60CB
;
	LD	HL,(D.F349)
	LD	(D.F34B),HL
	POP	AF
	OR	A
	CALL	Z,C.5B47
;
	JP	C,J.5B91
;
	LD	A,0FFH
	LD	(D.F346),A
	LD	A,(D.F341)
	LD	H,00H
	CALL	C.6414
;
	XOR	A
	LD	L,A
	LD	H,A
J$5A93:	LD	(HL),A
	INC	L
	JR	NZ,J$5A93
;
	LD	BC,I$0023
	CALL	C.5ED4
;
	LD	(D$F36F),HL
	EX	DE,HL
	LD	HL,I$6313
	LDIR
	LD	BC,I.0019
	CALL	C.5ED4
;
	LD	E,L
	LD	D,H
	LD	(D$F369),HL
	INC	HL
	INC	HL
	LD	(D$F36C),HL
	LD	HL,I$6336
	LDIR
	LD	BC,I$0168
	CALL	C.5ED4
;
	PUSH	HL
	EX	DE,HL
	LD	HL,C.636C
	PUSH	HL
	LDIR
	POP	BC
	POP	DE
	PUSH	DE
	LD	HL,I$0117
	ADD	HL,DE
	LD	(HL),3BH	; ";"
	INC	HL
	LD	(HL),00H
	LD	HL,I$634F
	CALL	C.62A1
	LD	HL,I$5B74
	XOR	A
	LD	B,A
	LD	D,A
J$5AE1:	LD	E,(HL)
	CP	E
	JR	Z,J$5AF5
;
	INC	HL
	LD	C,(HL)
	INC	HL
	EX	(SP),HL
	ADD	HL,BC
	EX	DE,HL
	LD	(HL),0C3H
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	EX	DE,HL
	EX	(SP),HL
	JR	J$5AE1
;
;	-----------------
J$5AF5:	POP	HL
	LD	HL,C.64D4
	LD	DE,I$003B
	LD	BC,I$001A
	LDIR
	LD	BC,I$0045
	CALL	C.5ED4
;
	PUSH	HL
	EX	DE,HL
	LD	HL,I$62CE
	PUSH	HL
	LDIR
	POP	BC
	POP	DE
	PUSH	DE
	LD	HL,I$62CA
	CALL	C.62A1
	POP	HL
	LD	A,0C3H
	LD	(X.0038),A
	LD	(D$0039),HL
	LD	DE,I$0022
	ADD	HL,DE
	LD	DE,(D.F34B)
	LD	(HL),E
	INC	HL
	LD	(HL),D
	LD	BC,I$00A0
	CALL	C.5ED4
;
	LD	A,0C3H
	CALL	C$5CB8
;
	SCF
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5B38:	LD	HL,D.F323
	LD	DE,X.F368
	LD	A,(D.F340)
	CALL	C.517F			; enable I/O ports
	JP	J$C01E
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5B47:	LD	A,(D.F347)
	OR	A
	SCF
	RET	Z
;
	LD	A,0F9H
	LD	C,A
	LD	B,01H	; 1 
	LD	HL,(D.F351)
	PUSH	HL
	XOR	A
	LD	E,A
	LD	D,A
	CALL	C.606C
;
	POP	HL
	LD	A,0FFH
	LD	(D.F246),A
	RET	C
;
	LD	A,(HL)
	LD	DE,I$C000
	LD	BC,J.0100
	LDIR
	CP	0EBH
	RET	Z
;
	CP	0E9H
	RET	Z
;
	SCF
	RET
;
;	-----------------
I$5B74:	INC	C
	NOP
	INC	D
	LD	HL,I$2E30
	INC	E
	LD	(DE),A
	INC	H
	LD	B,A
	NOP
I$5B7F:	LD	D,D
	LD	D,L
	LD	C,(HL)
	LD	(D$5541),HL
I$5B83	EQU	$-2
	LD	D,H
	LD	C,A
	LD	B,L
	LD	E,B
	LD	B,L
	LD	B,E
	LD	B,D
	LD	B,C
	LD	D,E
	NOP
I$5B8F:	JP	PE,J$CD5B
J.5B91	EQU	$-1
;
	OR	(HL)
	LD	E,H
	LD	HL,I$5B7F
	LD	DE,X.F568
	LD	BC,I.0010
	LDIR
	LD	HL,D.F340
	LD	A,(HL)
	AND	A
	LD	(HL),H
	JR	NZ,J$5BC6
;
	LD	(D.F346),A
	LD	HL,I$5B8F
	LD	(D.F323),HL
	LD	DE,I.F579
	PUSH	DE
	LD	HL,I$5B83
	LD	(DE),A
	INC	DE
	LD	C,0CH	; 12 
	LDIR
	POP	DE
	CALL	C.4462
;
	INC	A
	JR	Z,J$5BEA
;
	JR	J.5BF8
;
;	-----------------
J$5BC6:	LD	A,(X.0000)
	CP	0C3H
	JR	NZ,J.5BF4
;
	LD	HL,DBUF
	LD	B,(HL)
	INC	B
	DEC	B
	JR	Z,J.5BF4
;
J$5BD5:	INC	HL
	LD	A,(HL)
	CP	20H	; " "
	JR	NZ,J$5BDF
;
	DJNZ	J$5BD5
;
	JR	J.5BF4
;
;	-----------------
J$5BDF:	XOR	A
	LD	C,B
	LD	B,A
	LD	DE,I$F56C
	LDIR
	LD	(DE),A
	JR	J.5BF8
;
;	-----------------
J$5BEA:	LD	SP,I.C200
	LD	A,(D.F338)
	AND	A
	CALL	Z,C$5D72
;
J.5BF4:	XOR	A
	LD	(D$F56B),A
J.5BF8:	LD	SP,I.C200
	LD	A,(D.F343)
	LD	H,80H
	CALL	C.0024
;
	LD	A,(D.FCC1)
	LD	H,00H
	CALL	C.0024
;
	LD	HL,(D.FC48)
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(D.F676),HL
	LD	(HL),A
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(D.F6C2),HL
	LD	HL,D.FFFF
	LD	(D$F41C),HL
	CALL	C.5C6C
;
	LD	SP,(D.F674)
	LD	A,0FFH
	LD	(D$F3DE),A
	LD	A,0CH	; 12 
	RST	18H
;
	LD	IX,I$7D31
	CALL	C.0159
;
	CALL	C.5FA9			; print embedded string
;
	LD	A,(BC)
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$5C83
;
	LD	B,C
	LD	D,E
	LD	C,C
	LD	B,E
	JR	NZ,J$5CBD
;
	LD	H,L
	LD	(HL),D
	LD	(HL),E
	LD	L,C
	LD	L,A
	LD	L,(HL)
	JR	NZ,J$5C80
;
	LD	L,30H	; "0"
	LD	A,(BC)
	NOP
	LD	HL,C.4173
	PUSH	HL
	LD	HL,I$F567
	PUSH	HL
	LD	HL,I$F59E
	PUSH	HL
	LD	(HL),0E1H
	INC	HL
	LD	(HL),0C9H
	LD	A,(D.FCC1)
	LD	H,40H	; "@"
	JP	C.0024
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5C6C:	LD	HL,I$4068
	LD	(D.F323),HL
	LD	HL,I.570D
	LD	(D.F325),HL
	LD	HL,(D.F349)
	LD	(D.FC4A),HL
	LD	A,(D.F345)
J$5C80	EQU	$-1
	LD	C,A
	LD	B,00H
J$5C83	EQU	$-1
	LD	DE,I.0025
	CALL	C.491C
;
	CALL	C.5EDF
;
	LD	(D.F353),HL
	LD	BC,I.0019
	CALL	C.5EDF
;
	LD	(D$F378),HL
	EX	DE,HL
	LD	HL,I$6288
	LDIR
	LD	HL,I$FFF5
	ADD	HL,DE
	LD	(D$F37B),HL
	LD	A,(D.F348)
	LD	DE,I$FFF9
	ADD	HL,DE
	LD	(HL),A
	LD	DE,I.000E
	ADD	HL,DE
	LD	(HL),A
	CALL	C$5F82
;
	LD	A,0C9H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5CB8:	LD	(X.F368),A
	LD	(X.F36B),A
J$5CBD	EQU	$-1
	LD	(D$F36E),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5CC2:	LD	HL,I$5CF4
	LD	DE,I$FEBC
	LD	BC,BDOS
	LDIR
	LD	BC,I$5CF9
	LD	HL,I$F331
J.5CD3:	LD	A,(BC)
	INC	BC
	LD	E,A
	LD	A,(BC)
	INC	BC
	LD	D,A
	CP	0FFH
	RET	Z
;
	CP	40H	; "@"
	JR	NC,J$5CE3
;
	ADD	HL,DE
	JR	J.5CD3
;
;	-----------------
J$5CE3:	LD	(HL),0F7H
	INC	HL
	LD	A,(D.F348)
	LD	(HL),A
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),0C9H
	INC	HL
	JR	J.5CD3
;
;	-----------------
I$5CF4:	INC	SP
	INC	SP
	JP	J$6F1D
;
;	-----------------
I$5CF9:	OUT	(56H),A
	CP	C
	LD	A,(BC)
	OR	6AH	; "j"
	DEC	B
	NOP
	LD	E,L
	LD	L,(HL)
	DEC	A
	LD	L,(HL)
	DEC	B
	NOP
	CP	C
	LD	L,A
	DEC	B
	NOP
	SBC	A,A
	LD	L,A
	PUSH	DE
	LD	L,D
	DEC	B
	NOP
	LD	B,L
	LD	L,H
	LD	B,H
	LD	L,H
	XOR	C
	LD	L,E
	RLCA
	LD	L,L
	LD	A,(BC)
	LD	L,L
	DEC	C
	LD	L,L
	DEC	HL
	LD	L,L
	LD	L,6DH	; "m"
	LD	SP,I$116D
	LD	H,(HL)
	DEC	B
	NOP
	JR	NZ,J$5D8F
;
	LD	L,C
	LD	H,(HL)
	DEC	A
	LD	L,B
	LD	A,(BC)
	NOP
	LD	A,E
	LD	L,B
	AND	(HL)
	LD	L,B
	PUSH	BC
	LD	L,L
	LD	A,(D$FB6B)
	LD	H,A
	ADD	A,(HL)
	LD	H,A
	LD	A,(BC)
	NOP
	LD	C,D
	LD	L,A
	LD	B,(HL)
	LD	L,A
	XOR	L
	LD	L,L
	DEC	B
	NOP
	JP	PO,J$6567
;
	LD	(HL),D
	CP	(HL)
	LD	(HL),D
	LD	B,C
	NOP
	ADD	HL,BC
	LD	(HL),C
	AND	L
	NOP
	LD	L,H
	LD	H,B
	INC	D
	LD	H,C
	RST	38H
	RST	38H
I$5D57:	LD	BC,I$2D48
	LD	BC,I$2D41
	LD	BC,I$2947
	LD	A,(D$4D00)
I$5D62	EQU	$-1
	DEC	L
	LD	B,H
	DEC	L
	LD	E,C
	ADD	HL,HL
	LD	A,(D$4400)
I$5D6A	EQU	$-1
	DEC	L
	LD	C,L
	DEC	L
	LD	E,C
	ADD	HL,HL
	LD	A,(D$ED00)
C$5D72	EQU	$-1
	LD	(HL),E
	RET	NZ
;
	PUSH	AF
	LD	A,14H	; 20 
	LD	(D.F5C2),A
J$5D7B:	CALL	C.5FA9			; print embedded string
;
	LD	A,(BC)
	LD	B,L
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	NZ,J$5DEA
;
	LD	H,C
	LD	(HL),H
	LD	H,L
	JR	NZ,J$5DB3
;
	NOP
	LD	A,(D.F30E)
J$5D8F:	CP	01H	; 1 
	LD	HL,I$5D57
	JR	C,J.5D9E
;
	LD	HL,I$5D62
	JR	Z,J.5D9E
;
	LD	HL,I$5D6A
J.5D9E:	CALL	C.5FAF			; print string
;
	LD	HL,I$5E72
	LD	(D.F325),HL
	LD	DE,D.F5C2
	CALL	C.50E0
;
	LD	HL,I$F5C4
	LD	A,(HL)
	CP	0DH	; 13 
J$5DB3:	RET	Z
;
	LD	A,(D.F30E)
	AND	A
	JR	NZ,J$5DCC
;
	CALL	C.5E34
;
	CALL	C.5E10
;
	LD	D,C
	LD	A,(HL)
	INC	HL
	CP	B
	JR	NZ,J.5DF8
;
	CALL	C.5E1F
;
	LD	E,C
	JR	J.5DE6
;
;	-----------------
J$5DCC:	CALL	C.5E1F
;
	LD	D,C
	CALL	C.5E10
;
	LD	E,C
	LD	A,(HL)
	INC	HL
	CP	B
	JR	NZ,J$5DDE
;
	CALL	C.5E34
;
	JR	J.5DE6
;
;	-----------------
J$5DDE:	PUSH	DE
	CALL	C$553C
;
	PUSH	HL
	POP	IX
	POP	DE
J.5DE6:	LD	A,(D.F30E)
	CP	02H	; 2 
J$5DEA	EQU	$-1
	JR	C,J$5DF0
;
	LD	A,E
	LD	E,D
	LD	D,A
J$5DF0:	PUSH	IX
	POP	HL
	CALL	C$5552
;
	OR	A
	RET	Z
;
J.5DF8:	LD	SP,(D.F5C0)
	CALL	C.5FA9			; print embedded string
;
	LD	A,(BC)
	LD	C,C
	LD	L,(HL)
	HALT
;
;	-----------------
?.5E03:	LD	H,C
	LD	L,H
	LD	L,C
	LD	H,H
	JR	NZ,J$5E6D
;
	LD	H,C
	LD	(HL),H
	LD	H,L
	NOP
	JP	J$5D7B
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5E10:	LD	A,(HL)
	INC	HL
	LD	B,A
	CP	2FH	; "/"
	JR	Z,C.5E1F
;
	CP	2EH	; "."
	JR	Z,C.5E1F
;
	CP	2DH	; "-"
	JR	NZ,J.5DF8
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5E1F:	CALL	C.5E68
;
	JR	C,J.5DF8
;
	LD	C,A
	CALL	C.5E68
;
	RET	C
;
	PUSH	AF
	LD	A,C
	ADD	A,A
	ADD	A,A
	ADD	A,C
	ADD	A,A
	LD	C,A
	POP	AF
	ADD	A,C
	LD	C,A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5E34:	CALL	C.5E1F
;
	LD	B,C
	CALL	C.5E68
;
	JR	C,J$5E53
;
	DEC	HL
	CALL	C.5E1F
;
	PUSH	HL
	PUSH	BC
	LD	C,B
	LD	B,00H
	PUSH	DE
	LD	DE,I$0064
	CALL	C.491C
;
	POP	DE
	POP	HL
	LD	H,00H
	JR	J.5E62
;
;	-----------------
J$5E53:	PUSH	HL
	LD	C,B
	LD	B,00H
	LD	HL,I$076C
	LD	A,C
	CP	50H	; "P"
	JR	NC,J.5E62
;
	LD	HL,I$07D0
J.5E62:	ADD	HL,BC
	PUSH	HL
	POP	IX
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5E68:	LD	A,(HL)
	SUB	30H	; "0"
	RET	C
;
	CP	0AH	; 10 
J$5E6D	EQU	$-1
	CCF
	RET	C
;
	INC	HL
	RET
;
;	-----------------
I$5E72:	LD	(HL),H
	LD	E,(HL)
	LD	SP,(D.F5C0)
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5E79:	LD	HL,D.FCC1
	LD	B,04H	; 4 
	XOR	A
J$5E7F:	AND	03H	; 3 
	OR	(HL)
J$5E82:	PUSH	BC
	PUSH	HL
	LD	H,C
J$5E85:	LD	L,10H	; 16 
J$5E87:	PUSH	AF
	CALL	C.000C
;
	CPL
	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF
	CALL	C.0014
;
	POP	AF
	POP	DE
	PUSH	AF
	PUSH	DE
	CALL	C.000C
;
	POP	BC
	LD	B,A
	LD	A,C
	CPL
	LD	E,A
	POP	AF
	PUSH	AF
	PUSH	BC
	CALL	C.0014
;
	POP	BC
	LD	A,C
	CP	B
	JR	NZ,J$5EC1
;
	POP	AF
	DEC	L
	JR	NZ,J$5E87
;
	INC	H
	INC	H
	INC	H
	INC	H
	LD	C,A
	LD	A,H
	CP	40H	; "@"
	JR	Z,J$5EBD
;
	CP	80H
	LD	A,C
	JR	NZ,J$5E85
;
J$5EBD:	LD	A,C
	POP	HL
	POP	HL
	RET
;
;	-----------------
J$5EC1:	POP	AF
	POP	HL
	POP	BC
	AND	A
	JP	P,J$5ECE
;
	ADD	A,04H	; 4 
	CP	90H
	JR	C,J$5E82
;
J$5ECE:	INC	HL
	INC	A
	DJNZ	J$5E7F
;
	SCF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5ED4:	LD	HL,(D.F34B)
	AND	A
	SBC	HL,BC
	LD	(D.F34B),HL
	JR	J$5EE8
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5EDF:	LD	HL,(D.FC4A)
	AND	A
	SBC	HL,BC
	LD	(D.FC4A),HL
J$5EE8:	JR	C,J.5EF3
;
	LD	A,H
	CP	0C2H
	JR	J$5EF2
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5EEF:	CALL	C.5F0B
;
J$5EF2:	RET	NC
;
J.5EF3:	CALL	C.5FA9			; print embedded string
;
	INC	C
	LD	C,(HL)
	LD	L,A
	LD	(HL),H
	JR	NZ,J$5F61
;
	LD	L,(HL)
	LD	L,A
	LD	(HL),L
	LD	H,A
	LD	L,B
	JR	NZ,J$5F70
;
	LD	H,L
	LD	L,L
	LD	L,A
	LD	(HL),D
	LD	A,C
	NOP
	DI
	HALT
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5F0B:	LD	A,L
	OR	H
	RET	Z
;
	XOR	A
	SUB	L
	LD	L,A
	LD	A,00H
	SBC	A,H
	LD	H,A
	LD	C,L
	LD	B,H
	ADD	HL,SP
	CCF
	RET	C
;
	LD	DE,(D.FC48)
	SBC	HL,DE
	RET	C
;
	LD	A,H
	CP	02H	; 2 
	RET	C
;
	PUSH	BC
	LD	HL,X.0000
	ADD	HL,SP
	LD	E,L
	LD	D,H
	ADD	HL,BC
	PUSH	HL
	LD	HL,(D.F674)
	AND	A
	SBC	HL,DE
	LD	C,L
	LD	B,H
	INC	BC
	POP	HL
	LD	SP,HL
	EX	DE,HL
	LDIR
	POP	BC
	LD	HL,(D.FC4A)
	ADD	HL,BC
	LD	(D.FC4A),HL
	LD	DE,I.FDEA
	ADD	HL,DE
	LD	(D.F860),HL
	EX	DE,HL
	LD	HL,(D.F672)
	ADD	HL,BC
	LD	(D.F672),HL
	LD	HL,(D.F862)
	ADD	HL,BC
	LD	(D.F862),HL
	LD	HL,(D.F674)
	ADD	HL,BC
J$5F5E:	LD	(D.F674),HL
J$5F61:	DEC	HL
	DEC	HL
	LD	(D$F6B1),HL
	LD	L,E
	LD	H,D
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,02H	; 2 
J$5F6E:	EX	DE,HL
	LD	(HL),E
J$5F70:	INC	HL
	LD	(HL),D
	INC	HL
	EX	DE,HL
	LD	BC,I.0007
	LD	(HL),B
	ADD	HL,BC
	LD	(HL),B
	LD	BC,I$0102
	ADD	HL,BC
	DEC	A
	JR	NZ,J$5F6E
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5F82:	LD	A,01H	; 1 
	LD	(D.F85F),A
	LD	HL,(D.FC4A)
	LD	DE,I.FDEA
	ADD	HL,DE
	LD	(D.F860),HL
	LD	E,L
	LD	D,H
	DEC	HL
	DEC	HL
	LD	(D.F672),HL
	LD	BC,I.00C8
	AND	A
	SBC	HL,BC
	PUSH	HL
	LD	HL,I.000D
	ADD	HL,DE
	LD	(D.F862),HL
	POP	HL
	JR	J$5F5E

;	  Subroutine print embedded string
;	     Inputs  ________________________
;	     Outputs ________________________

C.5FA9:	EX	(SP),HL
	CALL	C.5FAF			; print string
	EX	(SP),HL
	RET

;	  Subroutine print string
;	     Inputs  ________________________
;	     Outputs ________________________

C.5FAF:	LD	A,(HL)
	INC	HL
	AND	A
	RET	Z
	CP	0AH	; 10 
	LD	A,0DH	; 13 
	CALL	Z,C.408F
	DEC	HL
	LD	A,(HL)
	INC	HL
	CALL	C.408F
	JR	C.5FAF
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5FC2:	LD	B,06H	; 6 
	LD	HL,I$0406
C$5FC5	EQU	$-2
	CALL	X.F365
;
	PUSH	BC
J$5FCB:	RRCA
	DJNZ	J$5FCB
;
	CALL	C$6019
;
	POP	BC
	OR	(HL)
	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	DEC	B
	DEC	B
J$5FDB:	RRCA
	DJNZ	J$5FDB
;
	JR	J$5FEB
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5FE0:	CALL	C.6014
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$5FE3:	OR	(HL)
	RET	P
;
	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
J$5FEB:	AND	0CH	; 12 
	OR	C
	RET
;
;	-----------------
;
;	  Subroutine GETWRK
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5FEF:	CALL	C.5FFA
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	HL
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.5FFA:	CALL	C.6014
;
	ADD	A,A
	ADD	A,A
	ADD	A,A
	SCF
	ADC	A,A
	LD	C,A
	LD	A,(HL)
	ADD	A,A
	SBC	A,A
	AND	0CH	; 12 
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	AND	(HL)
	OR	C
	ADD	A,A
	LD	HL,I$FD09
	JR	J$601E
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6014:	CALL	X.F365
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6017:	RRCA
	RRCA
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6019:	AND	03H	; 3 
	LD	HL,D.FCC1
J$601E:	LD	B,00H
	LD	C,A
	ADD	HL,BC
	RET
;
;	-----------------
J$6023:	LD	A,(D.FD9F)
	CP	0C9H
	JR	Z,J$6054
;
	PUSH	HL
	CALL	C.5FE0
;
	LD	C,A
	LD	HL,I.FB22
	LD	B,04H	; 4 
J$6034:	LD	A,(HL)
	CP	C
	JR	Z,J$603E
;
	INC	HL
	INC	HL
	DJNZ	J$6034
;
	POP	HL
	RET
;
;	-----------------
J$603E:	LD	A,04H	; 4 
	SUB	B
	LD	B,A
	ADD	A,A
	ADD	A,B
	LD	HL,I.FB29
	CALL	C.4564
;
	EX	DE,HL
	LD	HL,D.FDA0
	LD	BC,I.0003
	LDIR
I.6053:	POP	HL
J$6054:	DI
	LD	A,0F7H
	LD	(D.FD9F),A
	LD	(D$FDA1),HL
	LD	A,0C9H
	LD	(D$FDA3),A
	CALL	C.5FE0
;
	LD	(D.FDA0),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6069:	AND	A
	JR	C,J$60A3
C$606B	EQU	$-1
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.606C:	PUSH	IX
	PUSH	IY
	PUSH	HL
	PUSH	AF
	CALL	C.60B7
;
	LD	L,A
	POP	AF
	LD	A,L
	LD	IX,I$4010
	JR	J$6092
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$607E:	PUSH	IX
	LD	IX,I$4013
	JR	J$608C

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$6086:	PUSH	IX
	LD	IX,I$4016
J$608C:	PUSH	IY
	PUSH	HL
	CALL	C.60B7
J$6092:	POP	HL
	PUSH	HL
	PUSH	HL
	LD	HL,I$60B1
	EX	(SP),HL
	PUSH	HL
	PUSH	BC
	PUSH	AF
	CALL	C.7BF1		; disable I/O ports
	CALL	C.5FE0
	DEFB	0FDH		; << Illegal Op Code Byte >>
J$60A3:	CP	H
	JR	NZ,J$60AB
	POP	AF
	POP	BC
	POP	HL
	JP	(IX)
;
;	-----------------
J$60AB:	POP	AF
	POP	BC
	POP	HL
	JP	C.001C

I$60B1:	CALL	C.517F			; enable I/O ports
	JP	J$6306
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.60B7:	LD	(D.F33F),A
	LD	HL,I.FB21
J$60BD:	SUB	(HL)
	JR	C,J$60C4
;
	INC	HL
	INC	HL
	JR	J$60BD
;
;	-----------------
J$60C4:	ADD	A,(HL)
	INC	HL
	LD	H,(HL)
	PUSH	HL
	POP	IY
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.60CB:	CALL	C.45FB
;
	DEC	HL
	LD	(HL),0FFH
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.60D2:	LD	A,(D.F347)
	DEC	A
	RET	Z
;
J$60D7:	CALL	C.5FA9			; print embedded string
;
	LD	B,H
	LD	(HL),D
	LD	L,C
	HALT
;
;	-----------------
?.60DE:	LD	H,L
	JR	NZ,J$614F
;
	LD	H,C
	LD	L,L
	LD	H,L
	CCF
	JR	NZ,J$610F
;
	NOP
	LD	A,(D.F347)
	LD	B,A
	LD	A,41H	; "A"
	JR	J$60F7
;
;	-----------------
J$60F0:	PUSH	AF
	LD	A,2CH	; ","
	CALL	C.408F
;
	POP	AF
J$60F7:	CALL	C.408F
;
	INC	A
	DJNZ	J$60F0
;
	CALL	C.5FA9			; print embedded string
;
	ADD	HL,HL
	JR	NZ,J$6103
;
J$6103:	CALL	C.61B4
;
	CALL	C.6266
;
	AND	0DFH
	SUB	41H	; "A"
	LD	HL,D.F347
J$610F	EQU	$-1
	CP	(HL)
	JR	NC,J$60D7
;
	RET
;
;	-----------------
?.6114:	AND	A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6115:	LD	(D.F339),SP
	CALL	NC,C.6276
;
	PUSH	HL
	PUSH	BC
	CALL	C.60D2
;
	CALL	C.60CB
;
	CALL	C.60B7
;
	PUSH	IY
	PUSH	AF
	PUSH	IY
	LD	IX,I$4019
	CALL	C.001C
;
	LD	A,L
	OR	H
	JR	Z,J$615E
;
	POP	AF
J$6138:	PUSH	AF
	CALL	C.000C
;
	AND	A
	JR	Z,J$6146
;
	CALL	C.408F
;
	INC	HL
	POP	AF
	JR	J$6138
;
;	-----------------
J$6146:	POP	AF
	CALL	C.5FA9			; print embedded string
;
	CCF
	JR	NZ,J.614D
;
J.614D:	CALL	C.61B4
J$614F	EQU	$-1
;
	SUB	31H	; "1"
	CP	09H	; 9 
	JR	NC,J.614D
;
	ADD	A,31H	; "1"
	CALL	C.6266
;
	SUB	30H	; "0"
	PUSH	AF
J$615E:	CALL	C.6198
;
	POP	AF
	POP	DE
	POP	IY
	POP	BC
	POP	HL
	LD	IX,I$401C
	CALL	C.001C
;
	LD	HL,I$71F2
	JR	NC,J.618F
;
	LD	HL,I$71B5
	CP	0FH	; 15 
	JR	NC,J.618F
;
	CP	0CH	; 12 
	JR	NC,J$6183
;
	CP	03H	; 3 
	JR	NC,J.618F
;
	LD	HL,I$08D6
J$6183	EQU	$-2
	LD	HL,I$6222
	CALL	C.4564
;
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
J.618F:	CALL	C.6269
J$6192:	CALL	C.5FAF			; print string
	JP	C.6269
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6198:	CALL	C.5FA9			; print embedded string
;
I$619B:	LD	D,B
	LD	(HL),D
	LD	H,L
	LD	(HL),E
	LD	(HL),E
	JR	NZ,J$6203
;
	JR	NZ,J$620F
;
	LD	H,L
	LD	A,C
	JR	NZ,J$621C
;
	LD	L,A
	JR	NZ,J$620E
;
	LD	L,A
	LD	L,(HL)
	LD	(HL),H
	LD	L,C
	LD	L,(HL)
	LD	(HL),L
	LD	H,L
	JR	NZ,C.61B4
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.61B4:	CALL	C.406B
;
	CP	03H	; 3 
	RET	NZ
;
	LD	SP,(D.F339)
	CALL	C.5FA9			; print embedded string
;
	LD	A,(BC)
	LD	B,C
	LD	H,D
	LD	L,A
	LD	(HL),D
	LD	(HL),H
	LD	H,L
	LD	H,H
	NOP
	RET
;
;	-----------------
J$61CB:	LD	DE,I.F698
	LD	HL,(D.F678)
	LD	(D.F7F8),HL
	LD	A,03H	; 3 
	LD	(D.F663),A
	CALL	C.2EF3
;
	LD	DE,D.F69B
	RST	20H
;
	LD	(D.F678),HL
	RET	NZ
;
	JP	J.7239

;	  Subroutine stop all disk motors
;	     Inputs  ________________________
;	     Outputs ________________________

J$61E7:	LD	HL,I.FB21
	LD	B,04H	; 4 
J$61EC:	INC	HL
	LD	A,(HL)
	PUSH	AF
	POP	IY
	INC	HL
	PUSH	HL
	PUSH	BC
	LD	HL,I$401F
	PUSH	HL
	POP	IX
	AND	A
	CALL	NZ,C.000C
;
	AND	A
	CALL	NZ,C.001C
;
	POP	BC
J$6203:	POP	HL
	DJNZ	J$61EC
D$6205	EQU	$-1
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6207:	LD	A,(D$FED0)
	CP	0C9H
	JR	Z,J$621F
;
J$620E:	LD	HL,I$7234
J$620F	EQU	$-2
	LD	DE,D.FED5
	LD	BC,BDOS
	LDIR
	CALL	C.5FE0
;
J$621C:	LD	(D$FED6),A
J$621F:	JP	C.5FE0
;
;	-----------------
I$6222:	AND	B
	LD	(HL),C
	CALL	NZ,C$E471
;
	LD	(HL),C
	RST	30H
;
	LD	E,(HL)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$622A:	PUSH	AF
	CALL	C.455D
;
	CALL	C.4CA1
;
	POP	AF
	ADD	A,41H	; "A"
	CALL	C.F24F
;
	PUSH	AF
	CALL	C.5FA9			; print embedded string
;
	LD	A,(BC)
	LD	C,C
	LD	L,(HL)
	LD	(HL),E
	LD	H,L
	LD	(HL),D
	LD	(HL),H
	JR	NZ,J$62A8
;
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$62AF
;
	LD	L,A
	LD	(HL),D
	JR	NZ,J$62B1
;
	LD	(HL),D
	LD	L,C
	HALT
;
;	-----------------
?.6250:	LD	H,L
	JR	NZ,J$6253
;
J$6253:	POP	AF
	CALL	C.6266
;
	LD	HL,I$619B
	CALL	C.5FAF			; print string
;
J$625D:	CALL	C.406B
;
	CP	03H	; 3 
	JR	Z,J$625D
;
	JR	C.6269
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6266:	CALL	C.408F
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6269:	PUSH	AF
	LD	A,0DH	; 13 
	CALL	C.408F
;
	LD	A,0AH	; 10 
	CALL	C.408F
;
	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6276:	LD	HL,I$FF00
	ADD	HL,SP
	LD	DE,(D.F6C6)
	XOR	A
	SBC	HL,DE
	LD	C,L
	LD	B,H
	EX	DE,HL
	RET	NC
;
	LD	C,A
	LD	B,A
	RET
;
;	-----------------
I$6288:	LD	A,D
	CP	09H	; 9 
	JP	NC,J.6EC9
;
	RST	30H
;
	NOP
	DEC	BC
	LD	L,D
	PUSH	HL
	JP	J$6EF4
;
;	-----------------
?.6296:	LD	A,D
	CP	09H	; 9 
	JP	NC,J.6E95
;
	RST	30H
;
	NOP
	LD	C,A
	LD	L,C
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.62A1:	PUSH	DE
	EX	DE,HL
	AND	A
	SBC	HL,BC
	PUSH	HL
	POP	IX
	EX	DE,HL
	POP	DE
J$62AB:	LD	A,(HL)
	CP	0FFH
	RET	Z
J$62AF:	INC	HL
	EX	DE,HL
J$62B1:	ADD	A,L
	LD	L,A
	JR	NC,J$62B6
	INC	H
J$62B6:	PUSH	HL
	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	HL
	PUSH	IX
	POP	HL
	ADD	HL,BC
	LD	C,L
	LD	B,H
	POP	HL
	LD	(HL),B
	DEC	HL
	LD	(HL),C
	EX	DE,HL
	POP	DE
	JR	J$62AB

I$62CA:	INC	C
	LD	(DE),A
	LD	DE,I$DDFF
I$62CE	EQU	$-1
	PUSH	HL
	PUSH	IY
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	EXX
	EX	AF,AF'
	PUSH	AF
	PUSH	HL
	LD	HL,(D.62F7)
	LD	A,L
	OR	H
	POP	HL
	LD	IX,X.0038
	LD	IY,(D.FCC0)
	JR	NZ,J$630D
;
	POP	AF
	LD	(D.62F7),SP
	LD	SP,X.0000
	CALL	C.001C
;
	DI
	LD	SP,X.0000
D.62F7	EQU	$-2
	PUSH	HL
	LD	HL,X.0000
	LD	(D.62F7),HL
	POP	HL
J$6301:	EX	AF,AF'
	EXX
	POP	AF
	POP	BC
	POP	DE
J$6306:	POP	HL
	POP	IY
	POP	IX
	EI
	RET
;
;	-----------------
J$630D:	POP	AF
	CALL	C.001C
;
	JR	J$6301
;
;	-----------------
I$6313:	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C$402D
;
	PUSH	AF
	LD	H,40H	; "@"
	LD	A,(D.F342)
	CALL	C.0024
;
	POP	AF
	POP	BC
	POP	DE
	POP	HL
	LDIR
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	H,40H	; "@"
	CALL	C.0024
;
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET
;
;	-----------------
I$6336:	JR	J$633E
;
;	-----------------
?.6338:	PUSH	AF
	LD	A,(D.F342)
	JR	J$6342
;
;	-----------------
J$633E:	PUSH	AF
	LD	A,(D.F348)
J$6342:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	H,40H	; "@"
	CALL	C.0024
;
	POP	BC
	POP	DE
	POP	HL
	POP	AF
	RET
;
;	-----------------
I$634F:	NOP
	INC	BC
	DEC	C
	INC	BC
	INC	B
	DEC	B
	LD	B,03H	; 3 
	INC	C
	INC	BC
	DEC	B
	LD	B,2AH	; "*"
	INC	BC
	INC	C
	INC	BC
	INC	BC
	LD	D,14H	; 20 
	INC	BC
	LD	A,(BC)
	INC	BC
	INC	B
	LD	L,(HL)
	RLCA
	RLCA
	DEC	C
	EX	AF,AF'
	RST	38H
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.636C:	CALL	C.643A
;
	JP	M,J$637C
;
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	CALL	C$F380
;
	LD	A,E
	RET
;
;	-----------------
J$637C:	CALL	C.6489
;
	JP	Z,J$6496
;
	PUSH	HL
	CALL	C.645F
;
	EX	(SP),HL
	PUSH	BC
	CALL	C.636C
;
	JR	J$63AE
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$638D:	PUSH	DE
	CALL	C.643A
;
	JP	M,J$639D
;
	POP	DE
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	JP	J$F385
;
;	-----------------
J$639D:	CALL	C.6489
;
	JP	Z,J$649C
;
	EX	(SP),HL
	PUSH	HL
	CALL	C.645F
;
	POP	DE
	EX	(SP),HL
	PUSH	BC
	CALL	C$638D
;
J$63AE:	POP	BC
	EX	(SP),HL
	PUSH	AF
	LD	A,B
	AND	3FH	; "?"
	OR	C
	CALL	C$0046
;
	POP	AF
	POP	HL
	RET
;
;	-----------------
?.63BB:	EX	(SP),HL
	PUSH	AF
	PUSH	DE
	LD	A,(HL)
	PUSH	AF
	POP	IY
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	DE
	POP	IX
	POP	DE
	POP	AF
	EX	(SP),HL
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$63CD:	EXX
	EX	AF,AF'
	PUSH	IY
	POP	AF
	PUSH	IX
	POP	HL
	CALL	C.643A
;
	JP	M,J$63E4
;
	IN	A,(0A8H)
	PUSH	AF
	AND	C
	OR	B
	EXX
	JP	J$F38C
;
;	-----------------
J$63E4:	CALL	C.6489
;
	JP	Z,J$64A4
;
	CALL	C.645F
;
	PUSH	AF
	POP	IY
	PUSH	HL
	PUSH	BC
	LD	C,A
	LD	B,00H
	LD	A,L
	AND	H
	OR	D
	LD	HL,I.FCC5
	ADD	HL,BC
	LD	(HL),A
	PUSH	HL
	EX	AF,AF'
	EXX
	CALL	C$63CD
;
	EXX
	EX	AF,AF'
	POP	HL
	POP	BC
	POP	DE
	LD	A,B
	AND	3FH	; "?"
	OR	C
	DI
	CALL	C$004B
;
	LD	(HL),E
	EX	AF,AF'
	EXX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6414:	CALL	C.643A
;
	JP	M,J$6421
;
	IN	A,(0A8H)
	AND	C
	OR	B
	OUT	(0A8H),A
	RET
;
;	-----------------
J$6421:	CALL	C.6489
;
	JP	Z,C.64B9
;
	PUSH	HL
	CALL	C.645F
;
	LD	C,A
	LD	B,00H
	LD	A,L
	AND	H
	OR	D
	LD	HL,I.FCC5
	ADD	HL,BC
	LD	(HL),A
	POP	HL
	LD	A,C
	JR	C.6414
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.643A:	DI
	PUSH	AF
	LD	A,H
	RLCA
	RLCA
	AND	03H	; 3 
	LD	E,A
	INC	E
	LD	A,0C0H
J$6445:	RLCA
	RLCA
	DEC	E
	JR	NZ,J$6445
;
	LD	E,A
	CPL
	LD	C,A
	POP	AF
	PUSH	AF
	AND	03H	; 3 
	LD	B,A
	INC	B
	LD	A,0ABH
J$6455:	ADD	A,55H	; "U"
	DJNZ	J$6455
;
	LD	D,A
	AND	E
	LD	B,A
	POP	AF
	AND	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.645F:	PUSH	AF
	LD	A,D
	AND	0C0H
	LD	C,A
	POP	AF
	PUSH	AF
	LD	D,A
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	OR	C
	PUSH	AF
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	INC	D
	LD	A,0ABH
J$6477:	ADD	A,55H	; "U"
	DEC	D
	JR	NZ,J$6477
;
	AND	E
	LD	D,A
	LD	A,E
	CPL
	LD	H,A
	POP	AF
	CALL	C.64D4
;
	POP	AF
	AND	03H	; 3 
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6489:	INC	D
	DEC	D
	RET	NZ
;
	PUSH	BC
	LD	C,A
	LD	A,(D.F341)
	AND	E
	CP	B
	LD	A,C
	POP	BC
	RET
;
;	-----------------
J$6496:	CALL	C.64C1
;
	LD	E,(HL)
	JR	C.64A1
;
;	-----------------
J$649C:	POP	DE
	CALL	C.64C1
;
	LD	(HL),E
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.64A1:	LD	A,B
	JR	J$64CF
;
;	-----------------
J$64A4:	CALL	C.64B9
;
	PUSH	HL
	PUSH	BC
	EX	AF,AF'
	EXX
	CALL	C$F398
;
	EXX
	EX	AF,AF'
	POP	BC
	CALL	C.64A1
;
	POP	HL
	LD	(HL),B
	EX	AF,AF'
	EXX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.64B9:	CALL	C.64C1
;
	LD	HL,I.FCC5
	LD	(HL),D
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.64C1:	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,(D.FFFF)
	CPL
	LD	B,A
	AND	0FCH
	OR	D
	LD	D,A
J$64CF:	LD	(D.FFFF),A
	LD	A,E
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.64D4:	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	LD	L,A
	AND	H
	OR	D
	JR	J.64E7
;
;	-----------------
?.64DF:	OUT	(0A8H),A
	LD	A,L
	JR	J.64E7
;
;	-----------------
?.64E4:	OUT	(0A8H),A
	LD	A,E
J.64E7:	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	RET
;
;	-----------------
?.64EE:	LD	A,(D$FE4E)
	CP	0C9H
	SCF
	RET	Z
;
	LD	DE,I$7D6B
J$64F8:	LD	A,(DE)
	OR	A
	SCF
	RET	Z
;
	PUSH	HL
	CALL	C$745F
;
	JR	NZ,J.6523
;
	EX	DE,HL
	LD	B,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	A,B
	BIT	0,A
	JR	Z,J.651C
;
	PUSH	HL
	CALL	C.5FE0
;
	LD	HL,D.F348
	CP	(HL)
	POP	HL
	JR	Z,J.651C
;
	POP	HL
	SCF
	RET
;
;	-----------------
J.651C:	EX	(SP),HL
	CALL	C.721F
;
	SCF
	CCF
	RET
;
;	-----------------
J.6523:	LD	A,(DE)
	INC	DE
	CP	20H	; " "
	JR	NC,J.6523
;
	INC	DE
	INC	DE
	POP	HL
	JR	J$64F8
;
;	-----------------
I$652E:	RET	NZ
;
	LD	A,(D.F346)
	AND	A
	JP	Z,J.7257
;
	LD	IX,CLSALL
	CALL	C.7260
;
	CALL	C$00D2
;
	CALL	C$00CC
;
	XOR	A
	JP	J$5A70
I.6545	EQU	$-2
;
;	-----------------
I$6547:	PUSH	HL
	PUSH	AF
	LD	A,(D.F347)
	OR	A
	JP	Z,J.7257
;
	POP	AF
	CALL	Z,C.6115
;
	POP	HL
	AND	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6557:	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C.5356
;
	LD	C,A
	LD	HL,(D.F860)
	LD	A,(D.F85F)
J$6564:	PUSH	AF
	LD	E,(HL)
	INC	HL
J$6567:	LD	D,(HL)
	INC	HL
	PUSH	HL
	EX	DE,HL
	LD	A,(HL)
	AND	A
	JR	Z,J.659B
;
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	CP	09H	; 9 
	JR	NC,J.659B
;
	DEC	HL
	DEC	HL
	LD	D,(HL)
	DEC	HL
	LD	E,(HL)
	LD	A,(DE)
	CALL	C$5357
;
	CP	C
	JR	NZ,J.659B
;
	INC	DE
	EX	DE,HL
	LD	DE,D.F866
	LD	B,0BH	; 11 
J$658B:	LD	A,(DE)
	CP	3FH	; "?"
	JR	Z,J$6593
;
	CP	(HL)
	JR	NZ,J.659B
;
J$6593:	INC	DE
	INC	HL
	DJNZ	J$658B
;
	POP	HL
	POP	HL
	JR	J.660D
;
;	-----------------
J.659B:	POP	HL
	POP	AF
	DEC	A
	JP	P,J$6564
;
	JR	J.660D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$65A3:	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	A,D
	LD	(X.F568),A
	CALL	C.65C4
;
	CALL	C.65B2
;
	JR	J.660D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.65B2:	LD	HL,I.F5B2
	LD	(D.F23D),HL
	LD	DE,X.F568
	XOR	A
	LD	(D.F574),A
	CALL	C$4FB8
;
	INC	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.65C4:	LD	DE,I.F569
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.65C7:	LD	HL,D.F866
	LD	BC,I.000B
	LDIR
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.65D0:	EI
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	A,(D.F348)
	ADD	A,A
	LD	HL,I.0010
	JR	NC,J$65E0
;
	LD	L,18H
J$65E0:	ADD	HL,SP
	PUSH	IX
	POP	BC
	LD	(HL),C
	INC	HL
	LD	(HL),B
	LD	HL,I.000A
	ADD	HL,SP
	EX	DE,HL
	JR	J$65FA
;
;	-----------------
J$65EE:	PUSH	IY
	POP	BC
J$65F1:	LD	C,(HL)
	LD	A,(DE)
	LD	(HL),A
	LD	A,C
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	J$65F1
;
J$65FA:	LD	A,(D.F348)
	ADD	A,A
	LD	HL,I.0012
	JR	NC,J$6605
;
	LD	L,1AH
J$6605:	ADD	HL,SP
	LD	A,E
	SUB	L
	LD	A,D
	SBC	A,H
	JR	C,J$65EE
;
J$660C:	POP	AF
J.660D:	POP	BC
	POP	DE
	POP	HL
	RET
;
;	-----------------
?.6611:	LD	IX,I.F38B
	LD	IY,I.0200
	CALL	C.65D0
;
	POP	HL
	LD	A,(HL)
	AND	A
	RET
;
;	-----------------
?.6620:	EI
	LD	BC,J.0100
	LD	(D.F33D),BC
	CALL	C.721F
;
	LD	A,E
	RET	Z
;
	PUSH	AF
	PUSH	HL
	LD	A,(D.F348)
	ADD	A,A
	LD	HL,C.000C
	JR	NC,J$663A
;
	LD	L,14H	; 20 
J$663A:	ADD	HL,SP
	LD	A,(HL)
	CP	04H	; 4 
	JP	NZ,J.725A
;
	INC	HL
	LD	A,(HL)
	CP	09H	; 9 
	JP	NC,J.725A
;
	POP	HL
	CALL	C.7215
;
	RST	38H
	CALL	C.7215
;
	SUB	D
	CALL	C.7215
;
	RST	28H
;
	LD	IX,I$4756
	CALL	C.7260
;
	DEC	DE
	INC	D
	DEC	D
	JP	NZ,J.7257
;
	INC	DE
	LD	(D.F33D),DE
	POP	AF
	RET
;
;	-----------------
?.6669:	EI
	RET	NC
;
	LD	IX,I.F38B
	LD	IY,I.0400
	CALL	C.65D0
;
	CALL	C$6EE6
;
	CALL	C.6557
;
	JP	Z,J$724B
;
	LD	(D.F864),HL
	LD	A,E
	CP	04H	; 4 
	JR	Z,J.668E
;
	LD	BC,I.0001
	LD	(D.F33D),BC
J.668E:	POP	AF
	PUSH	AF
	PUSH	HL
	PUSH	DE
	LD	HL,D.F345
	CP	(HL)
	JP	NC,J$724E
;
	LD	BC,I.0025
	LD	E,A
	LD	D,B
	LD	HL,(D.F353)
	CALL	C.4922
;
	XOR	A
	LD	HL,C.000C
	ADD	HL,BC
	LD	(HL),A
	POP	DE
	POP	HL
	INC	HL
	LD	(HL),C
	INC	HL
	LD	(HL),B
	INC	HL
	LD	(HL),A
	INC	HL
	LD	(HL),D
	INC	HL
	INC	HL
	LD	(HL),A
	CALL	C$65A3
;
	PUSH	BC
	PUSH	DE
	LD	A,D
	LD	(BC),A
	LD	E,C
	LD	D,B
	INC	DE
	CALL	C.65C7
;
	POP	DE
	POP	BC
	LD	A,E
	JR	NZ,J$66E5
;
	AND	86H
	JP	Z,J.7254
;
J.66CE:	PUSH	DE
	PUSH	BC
	LD	E,C
	LD	D,B
	CALL	C.461D
;
	AND	A
	JP	NZ,J.70E9
;
	POP	HL
	CALL	C.676B
;
	POP	DE
	LD	HL,(D.F864)
	LD	(HL),E
J.66E2:	POP	AF
	POP	HL
	RET
;
;	-----------------
J$66E5:	CP	08H	; 8 
	JR	Z,J$672E
;
	CP	02H	; 2 
	JR	Z,J.66CE
;
	CP	80H
	JR	Z,J.66CE
;
	PUSH	DE
	PUSH	BC
	LD	E,C
	LD	D,B
	CALL	C.4462
;
	POP	HL
	CALL	C.676B
;
	POP	DE
	LD	HL,(D.F864)
	LD	(HL),E
	LD	A,E
	CP	04H	; 4 
	JR	Z,J.66E2
;
	PUSH	HL
	LD	HL,D.FCAE
	XOR	A
	CP	(HL)
	LD	(HL),A
	POP	HL
	JR	NZ,J.66E2
;
	LD	BC,CPMADR
	ADD	HL,BC
	PUSH	HL
	LD	(HL),0FFH
	LD	HL,(D.F864)
	CALL	C.6797
;
	POP	HL
	DEC	HL
	DEC	HL
	DEC	HL
	LD	(HL),A
	CP	0FFH
	JR	NZ,J.66E2
;
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(HL),80H
J$672C:	JR	J.66E2
;
;	-----------------
J$672E:	PUSH	BC
	LD	E,C
	LD	D,B
	CALL	C.4462
;
	POP	HL
	PUSH	HL
	CALL	C.676B
;
	LD	HL,(D.F864)
	LD	(HL),01H	; 1 
	LD	BC,CPMADR
	ADD	HL,BC
	LD	(HL),0FFH
	LD	HL,(D.F864)
J$6747:	PUSH	HL
	CALL	C.6797
;
	POP	HL
	JR	NC,J$6747
;
	LD	(HL),02H	; 2 
	POP	HL
	LD	BC,I.0021
	ADD	HL,BC
	LD	C,04H	; 4 
	PUSH	HL
	SCF
J$6759:	LD	A,(HL)
	SBC	A,B
	LD	(HL),A
	INC	HL
	DEC	C
	JR	NZ,J$6759
;
	POP	HL
	INC	C
	JR	NC,J$6766
;
	LD	C,04H	; 4 
J$6766:	CALL	C.6780
;
	JR	J$672C
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.676B:	LD	BC,C.000C
	ADD	HL,BC
	LD	(HL),B
	INC	HL
	LD	(HL),B
	INC	HL
	LD	BC,(D.F33D)
	LD	(HL),C
	INC	HL
	LD	(HL),B
	LD	BC,I.0011
	ADD	HL,BC
	LD	C,05H	; 5 
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6780:	LD	(HL),B
	INC	HL
	DEC	C
	JR	NZ,C.6780
;
	RET
;
;	-----------------
?.6786:	LD	IX,I.F38B
	LD	IY,I$0600
	CALL	C.65D0
;
	CALL	C.6797
;
	JP	J.660D
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6797:	PUSH	HL
	LD	A,(HL)
	CP	01H	; 1 
	JP	NZ,J.70D7
;
	LD	E,L
	LD	D,H
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	A
	JR	NZ,J$67D3
;
	INC	HL
	INC	HL
	INC	HL
	INC	(HL)
	LD	A,(HL)
	INC	HL
	INC	HL
	INC	HL
	JR	NZ,J.67CE
;
	PUSH	HL
	LD	(D.F23D),HL
	EX	DE,HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,J.0100
	CALL	C.47B2
;
	LD	E,L
	LD	D,H
	DEC	H
	LD	A,L
	OR	H
	POP	HL
	JR	Z,J.67CE
;
	PUSH	HL
	ADD	HL,DE
	LD	(HL),1AH
	POP	HL
	XOR	A
J.67CE:	LD	C,A
	LD	B,00H
	ADD	HL,BC
	LD	A,(HL)
J$67D3:	LD	B,A
	SUB	1AH
	SUB	01H	; 1 
	LD	A,B
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(HL),00H
	RET	NC
;
	LD	(HL),A
	RET
;
;	-----------------
?.67E2:	EI
	PUSH	HL
	LD	A,(D.F348)
	ADD	A,A
	LD	HL,I.0008
	JR	NC,J$67EF
;
	LD	L,10H	; 16 
J$67EF:	ADD	HL,SP
	LD	(HL),41H	; "A"
	INC	HL
	LD	(HL),6EH	; "n"
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(HL),C
	RET
;
;	-----------------
?.67FB:	LD	IX,I.F38B
	LD	IY,I$0800
	CALL	C.65D0
;
	LD	A,(HL)
	CP	02H	; 2 
	JP	NZ,J.70D7
;
	POP	AF
	PUSH	AF
	CALL	C.6814
;
	JP	J$660C
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6814:	PUSH	HL
	LD	BC,CPMADR
	ADD	HL,BC
	LD	C,(HL)
	INC	(HL)
	INC	HL
	INC	HL
	INC	HL
	ADD	HL,BC
	LD	(HL),A
	POP	HL
	RET	NZ
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6822:	PUSH	HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	BC,I.0004
	ADD	HL,BC
	LD	A,(HL)
	INC	HL
	INC	HL
	INC	HL
	LD	(D.F23D),HL
	AND	A
	LD	L,A
	LD	H,B
	JR	NZ,J$6838
;
	INC	H
J$6838:	CALL	C.70CD
;
	POP	HL
	RET
;
;	-----------------
?.683D:	LD	IX,I.F38B
	LD	IY,I.0400
	CALL	C.65D0
;
	POP	HL
	LD	A,(HL)
	SUB	02H	; 2 
	JR	NZ,J.6861
;
	PUSH	HL
	LD	HL,D.FCAE
	CP	(HL)
	LD	(HL),A
	POP	HL
	JR	NZ,J.6861
;
	LD	(HL),04H	; 4 
	LD	A,1AH
	CALL	C.6814
;
	CALL	NZ,C$6822
;
J.6861:	PUSH	HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	CALL	C.456F
;
	POP	HL
	PUSH	HL
	LD	DE,I.0007
	ADD	HL,DE
	LD	(HL),D
	LD	L,D
	LD	H,D
	LD	(D.F864),HL
	POP	HL
	INC	(HL)
	DEC	(HL)
	LD	(HL),D
	POP	HL
	RET
;
;	-----------------
?.687B:	CALL	C.72C2
;
	PUSH	HL
	LD	IX,I$54F7
	CALL	C.7260
;
	LD	A,0FFH
	CALL	C.6934
;
	LD	HL,(D.F676)
	LD	(D.F23D),HL
	EX	DE,HL
	LD	HL,(D.F6C2)
	AND	A
	SBC	HL,DE
	CALL	C.70C9
;
	LD	(D.F87C),A
	POP	HL
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.689F:	LD	IX,I$6B24
	JP	C.7260
;
;	-----------------
?.68A6:	LD	IX,I$739A
	LD	IY,I.0200
	CALL	C.65D0
;
	POP	AF
	JP	Z,J.70D7
;
	LD	IX,CLSALL
	CALL	C.7260
;
	LD	HL,(D.F353)
	PUSH	HL
	CALL	C.676B
;
	POP	HL
	PUSH	HL
	LD	BC,I$0013
	ADD	HL,BC
	LD	A,(HL)
	AND	A
	JP	NZ,J.723F
;
	DEC	HL
	OR	(HL)
	JP	NZ,J.723F
;
	DEC	HL
	LD	D,(HL)
	DEC	HL
	LD	E,(HL)
	LD	HL,(D.F676)
	ADD	HL,DE
	JP	C,J.723F
;
	LD	BC,I$0093
	ADD	HL,BC
	JP	C,J.723F
;
	SBC	HL,SP
	JP	NC,J.723F
;
	EX	DE,HL
	EX	(SP),HL
	EX	DE,HL
	CALL	C.693D
;
	LD	HL,(D.F676)
	LD	(D.F23D),HL
	POP	HL
	DEC	HL
	CALL	C.47B2
;
	LD	DE,(D.F676)
	ADD	HL,DE
	LD	(D.F6C2),HL
	LD	IX,I$4253
	CALL	C.7260
;
	LD	A,(D.F866)
	AND	A
	RET	NZ
;
	LD	(D.F87C),A
	LD	HL,I$6926
	LD	DE,X.F568
	LD	BC,BDOS
	PUSH	DE
	LDIR
	POP	HL
	LD	IX,NEWSTT
	JP	C.7260
;
;	-----------------
I$6926:	LD	A,(D$0092)
	DEFB	0,0
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.692B:	PUSH	HL
	LD	A,L
	CALL	C.6938
;
	POP	HL
	LD	A,H
	JR	C.6938
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6934:	LD	DE,(D.F353)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6938:	LD	BC,C.47BE
	JR	J$6940
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.693D:	LD	BC,C.47B2
J$6940:	PUSH	AF
	LD	HL,I.0001
	ADD	HL,SP
	LD	(D.F23D),HL
	PUSH	DE
	CALL	C.456A
;
	POP	DE
	POP	AF
	RET
;
;	-----------------
?.694F:	PUSH	DE
	CALL	C.6ACA
;
	LD	(D.FCBF),DE
	PUSH	DE
	CALL	C.6ACA
;
	LD	(D.F87D),DE
	EX	(SP),HL
	EX	DE,HL
	RST	20H
;
	JP	C,J.7257
;
	EX	DE,HL
	EX	(SP),HL
	CALL	C.721F
;
	SCF
	JR	Z,J.6983
;
	CALL	C.7215
;
	INC	L
	CP	53H	; "S"
	JR	NZ,J$697B
;
	CALL	X.7220
;
	AND	A
	JR	J.6983
;
;	-----------------
J$697B:	CALL	C.6ACE
;
	LD	(D.FCBF),DE
	SCF
J.6983:	POP	BC
	JR	NC,J$698B
;
	INC	B
	DEC	B
	JP	P,J.7257
;
J$698B:	POP	DE
	PUSH	HL
	PUSH	BC
	PUSH	AF
	XOR	A
	LD	E,02H	; 2 
	LD	IX,I.6AFA
	CALL	C.7260
;
	LD	A,0FEH
	CALL	C.6934
;
	POP	AF
	POP	HL
	PUSH	HL
	PUSH	AF
	CALL	C.692B
;
	LD	HL,(D.F87D)
	CALL	C.692B
;
	LD	HL,(D.FCBF)
	CALL	C.692B
;
	POP	AF
	POP	BC
	PUSH	AF
	LD	(D.F23D),BC
	LD	HL,(D.F87D)
	AND	A
	SBC	HL,BC
	INC	HL
	POP	AF
	JR	NC,J$69D1
;
	CALL	C.70C9
;
J$69C5:	LD	A,0FFH
	LD	(D.FCAE),A
	XOR	A
	CALL	C.689F
;
	JP	J.6E35
;
;	-----------------
J$69D1:	CALL	C.70A3
;
J$69D4:	PUSH	HL
	LD	DE,(D.FCBF)
	RST	20H
;
	PUSH	AF
	LD	C,L
	LD	B,H
	LD	HL,(D.F87D)
	PUSH	HL
	ADD	HL,BC
	LD	(D.F87D),HL
	POP	HL
	LD	DE,(D.F23D)
	CALL	C$0059
;
	POP	AF
	JR	NC,J$6A02
;
	POP	HL
	PUSH	HL
	CALL	C.70C9
;
	LD	HL,(D.FCBF)
	POP	DE
	AND	A
	SBC	HL,DE
	LD	(D.FCBF),HL
	EX	DE,HL
	JR	J$69D4
;
;	-----------------
J$6A02:	POP	HL
	LD	HL,(D.FCBF)
	CALL	C.70C9
;
	JR	J$69C5
;
;	-----------------
?.6A0B:	PUSH	DE
	XOR	A
	LD	(D.FCBE),A
	LD	C,A
	LD	B,A
	CALL	C.721F
;
	JR	Z,J.6A34
;
	CALL	C.7215
;
	INC	L
	CP	52H	; "R"
	JR	Z,J$6A23
;
	CP	53H	; "S"
	JR	NZ,J$6A2F
;
J$6A23:	LD	(D.FCBE),A
	CALL	X.7220
;
	JR	Z,J.6A34
;
	CALL	C.7215
;
	INC	L
J$6A2F:	CALL	C.6ACE
;
	LD	B,D
	LD	C,E
J.6A34:	POP	DE
	PUSH	HL
	PUSH	BC
	LD	A,0FFH
	LD	(D.FCAE),A
	XOR	A
	LD	E,01H	; 1 
	LD	IX,I.6AFA
	CALL	C.7260
;
	LD	DE,(D.F353)
	CALL	C.693D
;
	CP	0FEH
	JP	NZ,J.70D7
;
	POP	BC
	CALL	C.6ABC
;
	PUSH	HL
	CALL	C.6ABC
;
	PUSH	HL
	CALL	C.6ABC
;
	LD	(D.FCBF),HL
	POP	HL
	POP	BC
	AND	A
	SBC	HL,BC
	INC	HL
	LD	(D.F23D),BC
	LD	A,(D.FCBE)
I.6A6D	EQU	$-1
	CP	53H	; "S"
	JR	Z,J$6A7A
;
	CALL	C.47B2
;
J$6A75:	CALL	C$6E36
;
	POP	HL
	RET
;
;	-----------------
J$6A7A:	CALL	C.70A3
;
J$6A7D:	PUSH	HL
	LD	DE,(D.FCBF)
	RST	20H
;
	PUSH	AF
	LD	DE,(D.F353)
	CALL	C.47B2
;
	POP	AF
	POP	BC
	PUSH	BC
	PUSH	AF
	LD	HL,(D.F87D)
	PUSH	HL
	ADD	HL,BC
	LD	(D.F87D),HL
	POP	DE
	LD	HL,(D.F23D)
	POP	AF
	JR	NC,J$6AAE
;
	CALL	FCB1
;
	LD	HL,(D.FCBF)
	POP	DE
	AND	A
	SBC	HL,DE
	LD	(D.FCBF),HL
	EX	DE,HL
	JR	J$6A7D
J$6AAD	EQU	$-1
;
;	-----------------
J$6AAE:	POP	BC
	LD	BC,(D.FCBF)
	CALL	FCB1
;
	XOR	A
	LD	(D.FCBE),A
	JR	J$6A75
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6ABC:	PUSH	BC
	CALL	C.693D
;
	PUSH	AF
	CALL	C.693D
;
	LD	H,A
	POP	AF
	LD	L,A
	POP	BC
	ADD	HL,BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6ACA:	CALL	C.7215
;
	INC	L
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6ACE:	LD	IX,I$6F0B
	JP	C.7260
;
;	-----------------
?.6AD5:	CALL	C.72C2
;
	CALL	X.7220
;
	CALL	C.7215
;
	JR	Z,J$6AAD
;
	DEC	H
	LD	L,E
	CALL	C.7215
;
	ADD	HL,HL
	PUSH	HL
	LD	HL,I$3FD6
	LD	(D.F7F8),HL
	POP	HL
	LD	A,03H	; 3 
	LD	(D.F663),A
	AND	A
	JR	J$6B01
;
;	-----------------
?.6AF6:	CALL	C.72C2
;
	CALL	C$6B25
I.6AFA	EQU	$-2
;
	CALL	C.721F
;
	RET	NZ
;
	SCF
J$6B01:	PUSH	AF
	PUSH	HL
	PUSH	DE
	LD	E,C
	CALL	C.505D
;
	INC	A
	JP	Z,J.70DA
;
	POP	DE
	POP	HL
	POP	AF
	PUSH	HL
	LD	A,0FFH
	LD	(D.F246),A
	LD	A,(IX)
	LD	B,01H	; 1 
	LD	C,(IX+1)
	LD	HL,(D.F351)
	CALL	C.606C
;
	POP	HL
I$6B24:	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6B25:	LD	IX,GETBYT
	CALL	C.7260
;
	PUSH	DE
	CALL	C.7215
;
	INC	L
	LD	IX,GETUIN
	CALL	C.7260
;
	POP	BC
	RET
;
;	-----------------
?.6B3A:	LD	IX,I.F38B
	LD	IY,I.0400
	CALL	C.65D0
;
	LD	A,(HL)
	CP	04H	; 4 
	JP	NZ,J.70D7
;
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	BC,I.0007
	ADD	HL,BC
	EX	(SP),HL
	CALL	C.721F
;
	JR	Z,J$6B89
;
	PUSH	DE
	CALL	C.7215
;
	INC	L
	LD	IX,FRMEVL
	CALL	C.7260
;
	PUSH	HL
	CALL	C$6D4B
;
	LD	A,C
	OR	B
	OR	L
	OR	H
	JP	Z,J.7257
;
	LD	A,C
	OR	B
	DEC	BC
	JR	NZ,J$6B76
;
	DEC	HL
J$6B76:	EX	DE,HL
	POP	HL
	EX	(SP),HL
	PUSH	HL
	PUSH	DE
	LD	DE,I.0021
	ADD	HL,DE
	POP	DE
	LD	(HL),C
	INC	HL
	LD	(HL),B
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	DE
	POP	HL
J$6B89:	EX	(SP),HL
	LD	(D.F23D),HL
	POP	HL
	POP	AF
	PUSH	HL
	AND	A
	LD	HL,I$7245
	LD	BC,C.47B2
	JR	Z,J$6B9F
;
	LD	HL,J.70E6
	LD	BC,C.47BE
J$6B9F:	PUSH	HL
	CALL	C.456A
;
	AND	A
	RET	NZ
;
	POP	HL
	JP	J.6E35
;
;	-----------------
?.6BA9:	CALL	C.72C2
;
	CP	23H	; "#"
	CALL	Z,X.7220
;
	LD	IX,GETBYT
	CALL	C.7260
;
	JP	Z,J.725A
;
	PUSH	HL
	LD	IX,I.6A6D
	CALL	C.7260
;
	LD	E,L
	LD	D,H
	JP	Z,J.7242
;
	JP	C,J.7257
;
	LD	A,(HL)
	CP	04H	; 4 
	JP	NZ,J.70D7
;
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	BC,I.000E
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	(X.F568),BC
	LD	HL,X.0000
	LD	(D.F56A),HL
	LD	BC,I.0009
	POP	HL
J$6BEB:	EX	DE,HL
	ADD	HL,BC
	EX	DE,HL
	LD	A,(HL)
	CP	2CH	; ","
	RET	NZ
;
	PUSH	DE
	LD	IX,I$521B
	CALL	C.7260
;
	PUSH	AF
	CALL	C.7215
;
	LD	B,C
	CALL	C.7215
;
	LD	D,E
	CALL	C.6C28
;
	POP	AF
	EX	(SP),HL
	PUSH	DE
	PUSH	HL
	LD	HL,(D.F56A)
	LD	C,A
	LD	B,00H
	ADD	HL,BC
	LD	(D.F56A),HL
	EX	DE,HL
	LD	HL,(X.F568)
	RST	20H
;
	JP	C,J$7248
;
	POP	DE
	POP	HL
	LD	(HL),C
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	LD	B,00H
	POP	HL
	JR	J$6BEB
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6C28:	LD	IX,PTRGET
	CALL	C$6C33
;
	JP	NZ,J.723C
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6C33:	CALL	C.7260
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6C36:	LD	IX,I$5597
	JP	C.7260
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6C3D:	LD	IX,FRESTR
	JP	C.7260
;
;	-----------------
?.6C44:	OR	37H	; "7"
	CALL	C.72C2
;
	PUSH	AF
	CALL	C.6C28
;
	PUSH	DE
	LD	IX,I$4C5F
	CALL	C.7260
;
	POP	BC
	EX	(SP),HL
	PUSH	HL
	PUSH	BC
	CALL	C.6C3D
;
	LD	B,(HL)
	EX	(SP),HL
	LD	A,(HL)
	LD	C,A
	PUSH	BC
	PUSH	HL
	PUSH	AF
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	OR	A
	JR	Z,J$6CC2
;
	LD	HL,(D.F862)
	DEC	HL
	RST	20H
;
	JR	C,J.6CA0
;
	LD	HL,(D.F6C2)
	RST	20H
;
	JR	C,J.6CA0
;
	LD	E,C
	LD	D,00H
	LD	HL,(D.F674)
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(D.F69B)
	RST	20H
;
	JR	C,J$6CD5
;
	POP	AF
J$6C86:	LD	A,C
	LD	IX,J.668E
	CALL	C.7260
;
	POP	HL
	POP	BC
	EX	(SP),HL
	PUSH	DE
	PUSH	BC
	CALL	C.6C3D
;
	POP	BC
	POP	DE
	EX	(SP),HL
	PUSH	BC
	PUSH	HL
	INC	HL
	PUSH	AF
	LD	(HL),E
	INC	HL
	LD	(HL),D
J.6CA0:	POP	AF
	POP	HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	BC
	POP	HL
	INC	HL
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	LD	A,C
	CP	B
	JR	NC,J$6CB2
;
	LD	B,A
J$6CB2:	SUB	B
	LD	C,A
	POP	AF
	CALL	NC,C.6CCC
;
	INC	B
J$6CB9:	DEC	B
	JR	Z,J$6CC7
;
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	JR	J$6CB9
;
;	-----------------
J$6CC2:	POP	BC
	POP	BC
	POP	BC
	POP	BC
	POP	BC
J$6CC7:	CALL	C,C.6CCC
;
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6CCC:	LD	A,20H	; " "
	INC	C
J$6CCF:	DEC	C
	RET	Z
;
	LD	(DE),A
	INC	DE
	JR	J$6CCF
;
;	-----------------
J$6CD5:	POP	AF
	POP	HL
	POP	BC
	EX	(SP),HL
	EX	DE,HL
	JR	NZ,J$6D01
;
	PUSH	BC
	LD	A,B
	LD	IX,STRINI
	CALL	C.7260
;
	LD	DE,I.F698
	LD	HL,(D.F678)
	LD	(D.F7F8),HL
	LD	A,03H	; 3 
	LD	(D.F663),A
	CALL	C.2EF3
;
	LD	DE,D.F69B
	RST	20H
;
	LD	(D.F678),HL
	JP	Z,J.7239
;
	POP	BC
J$6D01:	EX	(SP),HL
	PUSH	BC
	PUSH	HL
	JP	J$6C86
;
;	-----------------
?.6D07:	LD	A,02H	; 2 
	LD	BC,I$043E
	LD	BC,I$083E
	CALL	C.72C2
;
	PUSH	AF
	LD	IX,DOCNVF
	CALL	C.7260
;
	POP	AF
	LD	IX,STRINI
	CALL	C.7260
;
	LD	HL,(D$F699)
	CALL	C$2F10
;
	JP	J$61CB
;
;	-----------------
?.6D2B:	LD	A,01H	; 1 
	LD	BC,I$033E
	LD	BC,I$073E
	CALL	C.72C2
;
	PUSH	AF
	CALL	C.6C3D
;
	POP	AF
	CP	(HL)
	JP	NC,J.7257
;
	INC	A
	INC	HL
	LD	C,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,C
	LD	(D.F663),A
	JP	J$2F08
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6D4B:	CALL	C$6C36
;
	LD	BC,(D.F7F8)
	LD	HL,X.0000
	RET	M
;
	JP	Z,J.723C
;
	LD	HL,I.F7F6
	LD	DE,I.F5FC
	LD	BC,I.0008
	LDIR
	LD	HL,I$4718
	LD	DE,I.F847
	LD	C,08H	; 8 
	LDIR
	CALL	C$289F
;
	AND	A
	CALL	C$30D1
;
	LD	IX,I.5432
	CALL	C.7260
;
	PUSH	DE
	EX	DE,HL
	CALL	C$6F95
;
	LD	BC,I.6545
	LD	DE,I.6053
	CALL	C.325C
;
	LD	HL,I.F7F6
	LD	DE,I.F847
	LD	BC,I.0008
	LDIR
	LD	HL,I.F5FC
	LD	DE,I.F7F6
	LD	C,08H	; 8 
	LDIR
	CALL	C$268C
;
	LD	IX,I.5432
	CALL	C.7260
;
	LD	C,E
	LD	B,D
	POP	HL
	RET
;
;	-----------------
?.6DAD:	CALL	C.72C2
;
	PUSH	HL
	CALL	C.6797
;
	LD	HL,X.0000
	JR	NC,J$6DBA
;
	DEC	HL
J$6DBA:	PUSH	AF
	CALL	C.2F99
;
	POP	AF
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	LD	(HL),A
	RET
;
;	-----------------
?.6DC5:	CALL	C.72C2
;
	LD	D,00H
	JR	Z,J$6DD2
;
	CALL	C.6EBD
;
	PUSH	HL
	JR	J$6DD6
;
;	-----------------
J$6DD2:	PUSH	HL
	CALL	C.6F3B
;
J$6DD6:	CALL	C.6EA0
;
	LD	A,(D$F416)
	AND	A
	PUSH	AF
	CALL	C.65B2
;
	JP	Z,J.7254
;
	LD	IX,I$7323
	CALL	C.7260
;
J$6DEB:	LD	HL,I$F5B3
	LD	B,0BH	; 11 
J$6DF0:	LD	A,(HL)
	INC	HL
	RST	18H
;
	LD	A,B
	CP	04H	; 4 
	JR	NZ,J$6E00
;
	LD	A,(HL)
	CP	20H	; " "
	JR	Z,J$6DFF
;
	LD	A,2EH	; "."
J$6DFF:	RST	18H
;
J$6E00:	DJNZ	J$6DF0
;
	CALL	C.00BD
;
	POP	AF
	PUSH	AF
	LD	A,(D$F3B0)
	LD	B,A
	LD	A,(D$F661)
	JR	Z,J$6E15
;
	LD	B,50H	; "P"
	LD	A,(D$F415)
J$6E15:	AND	A
	JR	Z,J$6E27
;
	ADD	A,0CH	; 12 
	CP	B
	JR	NC,J$6E20
;
	LD	A,20H	; " "
	RST	18H
;
J$6E20:	LD	IX,I$7328
	CALL	NC,C.7260
;
J$6E27:	LD	DE,X.F568
	XOR	A
	LD	(D.F574),A
	CALL	C.5006
;
	INC	A
	JR	NZ,J$6DEB
;
	POP	AF
J.6E35:	POP	HL
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6E36:	LD	IX,I$4AFF
	JP	C.7260
;
;	-----------------
?.6E3D:	CALL	C.72C2
;
	CALL	C.6ED3
;
	CALL	C.721F
;
	RET	NZ
;
	CALL	C.6557
;
	JP	Z,J.70E0
;
	CALL	C.6EA0
;
	PUSH	HL
	LD	DE,X.F568
	CALL	C$436C
;
	AND	A
	JP	NZ,J.7254
;
	POP	HL
	RET
;
;	-----------------
?.6E5D:	CALL	C.72C2
;
	CALL	C.6ED3
;
	CALL	C.6557
;
	JP	Z,J.70E0
;
	CALL	C.6EA0
;
	PUSH	HL
	CALL	C.65B2
;
	JP	Z,J.7254
;
	POP	HL
	CALL	C.7215
;
	LD	B,C
	CALL	C.7215
;
	LD	D,E
	CALL	C.6ED3
;
	LD	A,D
	LD	(D$F578),A
	PUSH	HL
	LD	HL,(X.F568)
	AND	A
	JR	Z,J$6E8E
;
	CP	L
	JP	NZ,J$70F5
;
J$6E8E:	LD	DE,I.F579
	CALL	C.65C7
;
	LD	DE,X.F568
J.6E95	EQU	$-2
	CALL	C$4392
;
	AND	A
	JP	NZ,J$70E3
;
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6EA0:	CALL	C.5356
;
	INC	A
	LD	(X.F568),A
	PUSH	HL
	PUSH	DE
	CALL	C.65C4
;
	POP	DE
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6EAF:	LD	IX,FILEVL
	CALL	C.7260
;
	LD	A,D
	CP	09H	; 9 
	RET	C
;
	JP	J.70DA
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6EBD:	CALL	C.6EAF
;
	PUSH	HL
	LD	HL,D.F866
	LD	B,0BH	; 11 
J$6EC6:	LD	A,(HL)
	INC	HL
	CP	20H	; " "
J.6EC9	EQU	$-1
	JR	NZ,J.6ED7
;
	DJNZ	J$6EC6
;
	CALL	C.6F3B
;
	JR	J.6ED7
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6ED3:	CALL	C.6EAF
;
	PUSH	HL
J.6ED7:	LD	HL,D.F866
	LD	B,08H	; 8 
	CALL	C.6F32
;
	LD	B,03H	; 3 
	CALL	C.6F32
;
	POP	HL
	OR	37H	; "7"
C$6EE6	EQU	$-1
	PUSH	DE
	PUSH	HL
	LD	DE,D.F866
	PUSH	DE
	LD	B,0BH	; 11 
J$6EEF:	PUSH	BC
	LD	A,(DE)
	LD	HL,I$6F09
J$6EF4:	LD	BC,I.000D
	JR	C,J$6EFA
;
	DEC	BC
J$6EFA:	CPIR
	JR	Z,J.6F2F
;
	POP	BC
	INC	DE
	DJNZ	J$6EEF
;
	POP	HL
	CALL	C$6F16
;
	POP	HL
	POP	DE
	RET
;
;	-----------------
I$6F09:	LD	L,22H	; """
I$6F0B:	CPL
	LD	E,H
	LD	E,E
	LD	E,L
	LD	A,(D.3D2B)
	DEC	SP
	INC	L
	LD	HL,(D$3E3F)
C$6F16	EQU	$-1
	JR	NZ,J.6ED7
;
	JR	Z,J.6F2F
;
	LD	B,07H	; 7 
J$6F1D:	CALL	C.6F22
;
	LD	B,03H	; 3 
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6F22:	INC	HL
	CP	(HL)
	JR	Z,J.6F29
;
	DJNZ	C.6F22
;
	RET
;
;	-----------------
J.6F29:	DEC	B
	RET	Z
;
	INC	HL
	CP	(HL)
	JR	Z,J.6F29
;
J.6F2F:	JP	J.7251
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6F32:	LD	A,(HL)
	CP	2AH	; "*"
	JR	Z,J.6F40
;
	INC	HL
	DJNZ	C.6F32
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.6F3B:	LD	HL,D.F866
	LD	B,0BH	; 11 
J.6F40:	LD	(HL),3FH	; "?"
	INC	HL
	DJNZ	J.6F40
;
	RET
;
;	-----------------
?.6F46:	LD	BC,I.0010
	LD	DE,I$2101
	NOP
	CALL	C.72C2
;
	PUSH	BC
	LD	IX,I.521F
	CALL	C.7260
;
	LD	IX,I.6A6D
	CALL	C.7260
;
	JP	C,J.7257
;
	JP	Z,J.7242
;
	POP	BC
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	PUSH	BC
	LD	IX,I.46FF
	CALL	C.7260
;
	LD	BC,I.6545
	LD	DE,I.6053
	CALL	C.325C
;
	LD	HL,I.F7F6
	LD	DE,I.F847
	LD	BC,I.0008
	LDIR
	POP	HL
	LD	DE,I$269A
	PUSH	DE
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$6F95:	LD	IX,I.46FF
	CALL	C.7260
;
	JP	J$3042
;
;	-----------------
?.6F9F:	CALL	C.72C2
;
	LD	IX,I.521F
	CALL	C.7260
;
	LD	HL,D.F347
	CP	(HL)
	JR	Z,J$6FB2
;
	JP	NC,J.70DA
;
J$6FB2:	LD	E,A
	CALL	C.505D
;
	JP	C.2F99
;
;	-----------------
?.6FB9:	CALL	C.72C2
;
	CALL	C.6EBD
;
	CALL	C.6557
;
	JP	Z,J.70E0
;
	CALL	C.6EA0
;
	PUSH	HL
	LD	A,(D.F247)
	INC	A
	LD	(D.F58D),A
	LD	HL,I.F569
	LD	DE,I.F58E
	LD	BC,C.0024
	LDIR
	POP	HL
	CALL	C.721F
;
	JR	Z,J$7001
;
	CALL	C.7215
;
	EXX
	CALL	C.6EBD
;
	CALL	C.6557
;
	JP	Z,J.70E0
;
	CALL	C.5356
;
	INC	A
	LD	(D.F58D),A
	PUSH	HL
	LD	DE,I.F58E
	CALL	C.65C7
;
	POP	HL
	CALL	C.721F
;
	RET	NZ
;
J$7001:	PUSH	HL
	CALL	C.65B2
;
	JP	Z,J.7254
;
J$7008:	CALL	C.00BD
;
	LD	BC,D.F58D
	LD	DE,I.F5D7
	LD	HL,I.F5B2
	LD	A,0CH	; 12 
J$7016:	PUSH	AF
	LD	A,(BC)
	CP	3FH	; "?"
	JR	NZ,J$701D
;
	LD	A,(HL)
J$701D:	LD	(DE),A
	INC	BC
	INC	DE
	INC	HL
	POP	AF
	DEC	A
	JR	NZ,J$7016
;
	LD	HL,I.F5B2
	LD	DE,I.F5D7
	LD	B,0CH	; 12 
J$702D:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$7038
;
	INC	HL
	INC	DE
	DJNZ	J$702D
;
	JP	J.7257
;
;	-----------------
J$7038:	CALL	C$70AA
;
	PUSH	HL
	XOR	A
	LD	(D$F5BE),A
	LD	DE,I.F5B2
	CALL	C.4462
;
	LD	DE,I.F5D7
	CALL	C.461D
;
	AND	A
	JP	NZ,J.70E9
;
	LD	L,A
	LD	H,A
	LD	(D$F5D3),HL
	LD	(D$F5D5),HL
	LD	(D$F5F8),HL
	LD	(D$F5FA),HL
	INC	HL
	LD	(D.F5C0),HL
	LD	(D$F5E5),HL
	POP	HL
J$7066:	PUSH	HL
	LD	DE,I.F5B2
	CALL	C.47B2
;
	LD	A,L
	OR	H
	JR	Z,J$707A
;
	LD	DE,I.F5D7
	CALL	C.70CD
;
	POP	HL
	JR	J$7066
;
;	-----------------
J$707A:	POP	HL
	LD	HL,(D$F5C6)
	LD	(D$F5EB),HL
	LD	HL,(D$F5C8)
	LD	(D$F5ED),HL
	LD	DE,I.F5D7
	CALL	C.456F
;
	LD	HL,I.F5B2
	LD	(D.F23D),HL
	LD	DE,X.F568
	XOR	A
	LD	(D.F574),A
	CALL	C.5006
;
	INC	A
	JP	NZ,J$7008
;
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.70A3:	LD	(D.FCBF),HL
	LD	(D.F87D),BC
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$70AA:	LD	HL,I$FE00
	ADD	HL,SP
	JR	NC,J.70BD
;
	LD	DE,(D.F6C6)
	AND	A
	SBC	HL,DE
	JR	C,J.70BD
;
	LD	A,H
	AND	A
	JR	NZ,J$70C4
;
J.70BD:	LD	DE,(D.F862)
	LD	HL,J.0100
J$70C4:	LD	(D.F23D),DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.70C9:	LD	DE,(D.F353)
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.70CD:	CALL	C.47BE
;
	AND	A
	RET	Z
;
	JR	J.70E6
;
;	-----------------
J$70D4:	LD	E,3CH	; "<"
	LD	BC,I$3D1E
J.70D7	EQU	$-2
	LD	BC,I$3E1E
J.70DA	EQU	$-2
	LD	BC,I$3F1E
	LD	BC,I$401E
J.70E0	EQU	$-2
	LD	BC,I$411E
J$70E3	EQU	$-2
	LD	BC,I$421E
J.70E6	EQU	$-2
	LD	BC,I$431E
J.70E9	EQU	$-2
	LD	BC,I$441E
J$70EC	EQU	$-2
	LD	BC,I$451E
J$70EF	EQU	$-2
	LD	BC,I$461E
J$70F2	EQU	$-2
	LD	BC,I$471E
J$70F5	EQU	$-2
	LD	BC,X.0000
	XOR	A
	LD	(D.F87C),A
	LD	(D.FCAE),A
	PUSH	DE
	CALL	C.689F
;
	POP	DE
	JP	J$725C
;
;	-----------------
?.7109:	LD	A,E
	CP	3CH	; "<"
	RET	C
;
	CP	48H	; "H"
	RET	NC
;
	SUB	3BH	; ";"
	LD	B,A
	LD	HL,I$712B
D.7114	EQU	$-2
J.7116:	LD	A,(HL)
	AND	A
	INC	HL
	JR	NZ,J.7116
;
	DJNZ	J.7116
D.711C	EQU	$-1
;
	DEC	HL
	LD	DE,I$F604
	PUSH	DE
	LD	BC,I$0016
	LDIR
	LD	E,01H	; 1 
	POP	HL
	RET
;
;	-----------------
I$712B:	NOP
	LD	B,D
	LD	H,C
	LD	H,H
	JR	NZ,J$7177
;
	LD	B,C
	LD	D,H
	NOP
	LD	B,D
	LD	H,C
	LD	H,H
	JR	NZ,J$719F
;
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J.71AB
;
	LD	L,A
	LD	H,H
	LD	H,L
	NOP
	LD	B,D
	LD	H,C
	LD	H,H
	JR	NZ,J.71AB
;
	LD	(HL),D
	LD	L,C
	HALT
;
;	-----------------
?.714A:	LD	H,L
	JR	NZ,J$71BB
;
	LD	H,C
	LD	L,L
	LD	H,L
	NOP
	LD	B,D
	LD	H,C
	LD	H,H
	JR	NZ,J$71C9
;
	LD	H,L
	LD	H,E
	LD	(HL),H
	LD	L,A
	LD	(HL),D
	JR	NZ,J$71CB
;
	LD	(HL),L
	LD	L,L
	LD	H,D
	LD	H,L
	LD	(HL),D
	NOP
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$71DC
;
	LD	(HL),H
	LD	L,C
	LD	L,H
	LD	L,H
	JR	NZ,J$71DE
;
	LD	(HL),B
	LD	H,L
	LD	L,(HL)
	NOP
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
J$7177:	JR	NZ,J$71DA
;
	LD	L,H
	LD	(HL),D
	LD	H,L
	LD	H,C
	LD	H,H
	LD	A,C
	JR	NZ,J$71E6
;
	LD	A,B
	LD	L,C
	LD	(HL),E
	LD	(HL),H
	LD	(HL),E
	NOP
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$71F3
;
	LD	(HL),L
	LD	L,H
	LD	L,H
	NOP
	LD	D,H
	LD	L,A
	LD	L,A
	JR	NZ,J$7203
;
	LD	H,C
	LD	L,(HL)
	LD	A,C
	JR	NZ,J$7201
;
	LD	L,C
	LD	L,H
	LD	H,L
	LD	(HL),E
J$719F:	NOP
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$721D
;
	LD	(HL),D
	LD	L,C
	LD	(HL),H
	LD	H,L
	JR	NZ,J$721C
J.71AB	EQU	$-1
;
	LD	(HL),D
	LD	L,A
	LD	(HL),H
	LD	H,L
	LD	H,E
	LD	(HL),H
	LD	H,L
	LD	H,H
	NOP
I$71B5:	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$7204
;
J$71BB:	CPL
	LD	C,A
	JR	NZ,J$7224
;
	LD	(HL),D
	LD	(HL),D
	LD	L,A
	LD	(HL),D
	NOP
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J.7239
J$71C9	EQU	$-1
;
	LD	H,(HL)
J$71CB:	LD	H,(HL)
	LD	L,H
	LD	L,C
	LD	L,(HL)
	LD	H,L
	NOP
	LD	D,D
	LD	H,L
	LD	L,(HL)
	LD	H,C
	LD	L,L
	LD	H,L
	JR	NZ,J$723A
;
	LD	H,E
J$71DA:	LD	(HL),D
	LD	L,A
J$71DC:	LD	(HL),E
	LD	(HL),E
J$71DE:	JR	NZ,J$7244
;
	LD	L,C
	LD	(HL),E
	LD	L,E
	NOP
	LD	B,D
	LD	H,C
J$71E6:	LD	H,H
	JR	NZ,J$7259
;
	LD	H,C
	LD	(HL),D
	LD	H,C
	LD	L,L
	LD	H,L
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	NOP
I$71F2:	LD	B,(HL)
J$71F3:	LD	L,A
	LD	(HL),D
	LD	L,L
	LD	H,C
	LD	(HL),H
	JR	NZ,J$725D
;
	LD	L,A
	LD	L,L
	LD	(HL),B
	LD	L,H
	LD	H,L
	LD	(HL),H
	LD	H,L
J$7201:	NOP
	BIT	7,C
J$7203	EQU	$-1
J$7204:	JP	NZ,J$70D4
;
	LD	A,C
	AND	0FEH
	JP	Z,J$70EC
;
	CP	02H	; 2 
	JP	Z,J$70F2
;
	JP	J$70EF
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7215:	CALL	C.721F
;
	EX	(SP),HL
	CP	(HL)
	JR	NZ,J.725A
;
J$721C:	INC	HL
J$721D:	EX	(SP),HL
	INC	HL
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.721F:	DEC	HL
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
X.7220:	LD	IX,CHRGTR
J$7224:	JR	C.7260
;
;	-----------------
?.7226:	LD	A,0C9H
	LD	(D.FED5),A
	LD	DE,(D.FC4A)
	LD	(D.F349),DE
	RET
;
;	-----------------
I$7234:	RST	30H
;
	NOP
	LD	H,72H	; "r"
	RET
;
;	-----------------
J.7239:	LD	E,10H	; 16 
J$723A	EQU	$-1
	LD	BC,I$0D1E
J.723C	EQU	$-2
	LD	BC,I$071E
J.723F	EQU	$-2
	LD	BC,I$3B1E
J.7242	EQU	$-2
J$7244:	LD	BC,I$371E
I$7245	EQU	$-2
	LD	BC,I$321E
J$7248	EQU	$-2
	LD	BC,I$361E
J$724B	EQU	$-2
	LD	BC,I$341E
J$724E	EQU	$-2
	LD	BC,I$381E
J.7251	EQU	$-2
	LD	BC,I$351E
J.7254	EQU	$-2
	LD	BC,I$051E
J.7257	EQU	$-2
J$7259:	LD	BC,I$021E
J.725A	EQU	$-2
J$725C:	LD	IX,I$406F
J$725D	EQU	$-3
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7260:	CALL	C.0159
;
	EI
	RET
;
;	-----------------
?.7265:	EI
	PUSH	HL
	PUSH	DE
	LD	A,(D.F348)
	ADD	A,A
	LD	HL,I.0010
	JR	NC,J$7273
;
	LD	L,18H
J$7273:	ADD	HL,SP
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	PUSH	HL
	LD	HL,J.6E95
	RST	20H
;
	POP	HL
	JR	Z,J$728C
;
	PUSH	HL
	LD	HL,J.6EC9
	RST	20H
;
	POP	HL
	JR	NZ,J$7292
;
	LD	DE,I$F377
	JR	J$728F
;
;	-----------------
J$728C:	LD	DE,I$F37A
J$728F:	LD	(HL),D
	DEC	HL
	LD	(HL),E
J$7292:	POP	DE
	POP	HL
	LD	A,E
	CP	02H	; 2 
	RET	C
;
	LD	A,(HL)
	CP	3AH	; ":"
	JR	Z,J.7251
;
	INC	HL
	LD	A,(HL)
	CP	3AH	; ":"
	DEC	HL
	RET	NZ
;
	CALL	C.72C2
;
	LD	A,(HL)
	AND	0DFH
	SUB	40H	; "@"
	PUSH	HL
	LD	HL,D.F347
	CP	(HL)
	POP	HL
	JR	Z,J$72B6
;
	JP	NC,J.70DA
;
J$72B6:	INC	HL
	INC	HL
	DEC	E
	DEC	E
	PUSH	DE
	INC	E
	POP	DE
	RET
;
;	-----------------
?.72BE:	EI
	LD	A,00H
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.72C2:	EI
	PUSH	HL
	PUSH	AF
	LD	A,(D.F348)
	ADD	A,A
	LD	HL,C.000C
	JR	NC,J$72D0
;
	LD	L,14H	; 20 
J$72D0:	ADD	HL,SP
	LD	(HL),8BH
	INC	HL
	LD	(HL),0F3H
	POP	AF
	POP	HL
	RET
;
;	-----------------
J.72D9:	CALL	X.F36B
;
	LD	A,(DE)
	CALL	X.F368
;
	INC	DE
	CP	24H	; "$"
	RET	Z
;
	CALL	C.53A8
;
	JR	J.72D9
;
;	-----------------
?.72E9:	CALL	X.F36B
;
	LDIR
	CALL	X.F368
;
	RET
;
;	-----------------
?.72F2:	CALL	X.F36B
;
	JP	X.0000
;
;	-----------------
?.72F8:	LD	DE,I$F1DE
	PUSH	DE
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	CALL	X.F36B
;
	JP	(HL)
;
;	-----------------
?.7304:	JP	J$5604
;
;	-----------------
?.7307:	LD	D,B
	LD	D,D
	LD	C,(HL)
	JR	NZ,J$7358
;
	LD	D,E
	LD	D,H
	JR	NZ,J$735E
;
	LD	D,L
	LD	C,H
	JR	NZ,J$7355
;
	LD	D,L
	LD	E,B
	JR	NZ,J$735B
;
	LD	C,A
	LD	C,(HL)
	JR	NZ,J$733C
;
	JR	NZ,J$733E
;
	JR	NZ,J$7340
;
D$7320:	JR	NZ,J$7342
;
	JR	NZ,J$7344
I$7323	EQU	$-1
;
	JR	NZ,J$7346
;
	ADD	A,B
	DEFB	0
I$7328:	DEFB	0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	RRA
J$733C:	INC	E
	RRA
J$733E:	LD	E,1FH
J$7340:	LD	E,1FH
J$7342:	RRA
	LD	E,1FH
J$7344	EQU	$-1
	LD	E,1FH
J$7346	EQU	$-1
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7347:	LD	A,1
	LD	(D.F30D),A
	CALL	C.5FEF			; GETWRK
	XOR	A
	LD	BC,I.000E
	CALL	C.58E3
J$7355	EQU	$-1
;
	LD	A,(D.F33F)
J$7358	EQU	$-1
	AND	A
	CALL	C.532C
J$735B	EQU	$-2
;
	LD	B,(IX+5)
J$735E	EQU	$-2
	CP	B
	LD	A,0FEH
	JR	NZ,J$7366
;
	INC	A
J$7366:	LD	(IX+5),A
	LD	A,(D.002B)
	AND	80H
	LD	(IX+13),A
	LD	HL,I$7377
	JP	J$6023
;
;	-----------------
I$7377:	PUSH	AF
	CALL	C.5FEF			; GETWRK
;
	LD	A,(HL)
	AND	A
	JR	Z,J.738C
;
	DEC	A
	LD	(HL),A
	JR	NZ,J.738C
;
	PUSH	HL
	PUSH	IX
	CALL	C.5095
;
	POP	IX
	POP	HL
J.738C:	INC	HL
	LD	B,04H	; 4 
J$738F:	LD	A,(HL)
	AND	A
	JR	Z,J$7394
;
	DEC	(HL)
J$7394:	INC	HL
	DJNZ	J$738F
;
	LD	A,(D.F338)
I$739A:	OR	A
	JR	NZ,J$73E6
;
	LD	A,(IX+13)
	LD	C,0B2H
	LD	B,80H
	BIT	7,A
	JR	NZ,J$73AC
;
	LD	C,3CH	; "<"
	LD	B,00H
J$73AC:	INC	A
	CP	C
	JR	NZ,J$73E3
;
	PUSH	BC
	LD	C,(IX+12)
	LD	B,(IX+11)
	LD	E,(IX+10)
	INC	C
	LD	A,C
	CP	3CH	; "<"
	JR	NZ,J.73D9
;
	LD	C,00H
	INC	B
	LD	A,B
	CP	3CH	; "<"
	JR	NZ,J.73D9
;
	LD	B,00H
	INC	E
	LD	A,E
	CP	18H
	JR	NZ,J.73D9
;
	LD	E,00H
	LD	HL,(D.F33B)
	INC	HL
	LD	(D.F33B),HL
J.73D9:	LD	(IX+12),C
	LD	(IX+11),B
	LD	(IX+10),E
	POP	AF
J$73E3:	LD	(IX+13),A
J$73E6:	CALL	C.5FE0
;
	LD	B,04H	; 4 
	LD	DE,I.FB29
	LD	HL,I.FB22
J$73F1:	CP	(HL)
	JR	Z,J$73FD
;
	INC	DE
	INC	DE
	INC	DE
	INC	HL
	INC	HL
	DJNZ	J$73F1
;
J$73FB:	POP	AF
	RET
;
;	-----------------
J$73FD:	EX	DE,HL
	LD	A,(HL)
	AND	A
	JR	Z,J$73FB
;
	PUSH	AF
	POP	IY
	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	POP	IX
	POP	AF
	JP	C.001C

;	  Subroutine DSKCHG
;	     Inputs  ________________________
;	     Outputs ________________________

J$7410:	EI
	PUSH	HL
	PUSH	BC
	PUSH	AF
	CALL	C.5FEF			; GETWRK
	POP	AF
	POP	BC
	PUSH	AF
	INC	A
	LD	E,A
	LD	D,00H
	POP	AF
	ADD	HL,DE
	LD	B,(HL)
	POP	HL
	INC	B
	DEC	B
	LD	B,01H	; 1 
	RET	NZ
;
	PUSH	BC
	PUSH	HL
	LD	DE,I.0001
	LD	HL,(D.F34D)
	AND	A
	CALL	C.74A0
;
	JR	C,J.744C
;
	LD	HL,(D.F34D)
	LD	B,(HL)
	POP	HL
	PUSH	BC
	CALL	C.7CFC
	LD	A,0CH	; 12 
	JR	C,J.744C
	POP	AF
	POP	BC
	CP	C
	SCF
	CCF
	LD	B,0FFH
	RET	NZ
;
	INC	B
	RET
;
;	-----------------
J.744C:	POP	DE
	POP	DE
	RET
;
;	-----------------
?.744F:	LD	E,01H	; 1 
	JR	J$7455
;
;	-----------------
?.7453:	LD	E,00H
J$7455:	RET	NZ
;
	LD	C,2EH	; "."
	PUSH	HL
	CALL	C.F37D
;
	POP	HL
	XOR	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$745F:	LD	HL,I$FD89
J$7462:	LD	A,(DE)
	CP	20H	; " "
	JR	NC,J$746A
;
	XOR	A
	CP	(HL)
	RET
;
;	-----------------
J$746A:	CP	(HL)
	RET	NZ
;
	INC	HL
	INC	DE
	JR	J$7462

;	  Subroutine DSKFMT
;	     Inputs  ________________________
;	     Outputs ________________________

J$7470:	PUSH	AF
	LD	A,D
	CALL	C.747A
	LD	D,A
	POP	AF
	JP	J$7712
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.747A:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	AF
	CALL	C.5FEF			; GETWRK
	LD	HL,D.F33F
	LD	A,(IX+5)
	CP	0FFH
	JR	Z,J$749B
	CP	0FEH
	JR	Z,J$7494
	CP	(HL)
	POP	BC
	LD	B,00H
	PUSH	BC
J$7494:	LD	A,(HL)
	LD	(IX+5),A
	CALL	NZ,C$622A
;
J$749B:	POP	AF
	POP	HL
	POP	DE
	POP	BC
	RET
;
;	-----------------
;
;	  Subroutine DSKIO
;	     Inputs  ________________________
;	     Outputs ________________________

C.74A0:	CALL	C.747A
;
	PUSH	AF
	CALL	C$795D
;
	POP	DE
	PUSH	AF
	PUSH	BC
	CALL	C.5FEF			; GETWRK
	POP	BC
	LD	(HL),78H	; "x"
	INC	HL
	POP	AF
	PUSH	AF
	PUSH	BC
	LD	C,3CH	; "<"
	JR	NC,J$74BA
;
	LD	C,00H
J$74BA:	LD	E,D
	LD	D,00H
	ADD	HL,DE
	LD	(HL),C
	POP	BC
	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.74C2:	PUSH	AF
	PUSH	BC
	PUSH	HL
	CALL	C.5FEF			; GETWRK
	LD	BC,5
	ADD	IX,BC
	POP	HL
	POP	BC
	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.74D1:	LD	A,H
	OR	L
	JR	NZ,J$74DA
;
	LD	(D.F302),BC
	RET
;
;	-----------------
J$74DA:	CALL	C.74F8
;
	DEC	DE
	LD	A,01H	; 1 
	LD	(DE),A
	INC	DE
	JP	J$4218
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.74E5:	CALL	X.F252
;
	LD	A,H
	OR	L
	JR	NZ,J$74F2
;
	LD	HL,(D.F302)
	LD	A,H
	OR	L
	RET
;
;	-----------------
J$74F2:	CALL	C.74F8
;
	JP	J$41F4
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.74F8:	PUSH	IX
	CALL	C.74C2
;
	LD	A,(IX)
	LD	D,(IX+1)
	EX	(SP),IX
	CP	(IX)
	JR	Z,J$750F
;
	CALL	C.7527
;
	JR	J$7518
;
;	-----------------
J$750F:	LD	A,H
	RRA
	RRA
	AND	03H	; 3 
	CP	D
	CALL	NZ,C.7527
;
J$7518:	LD	A,H
	AND	03H	; 3 
	LD	H,A
	EX	(SP),IX
	LD	E,(IX+2)
	LD	D,(IX+3)
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7527:	CALL	C.756E
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$752A:	LD	A,(IX)
	PUSH	IX
	CALL	C.74C2
;
	LD	(IX),A
	LD	A,H
	RRA
	RRA
	AND	03H	; 3 
	LD	(IX+1),A
	POP	IX
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	C,A
	CALL	C.45DB
;
	LD	B,A
	LD	A,C
	ADD	A,A
	ADD	A,C
	ADD	A,E
	LD	E,A
	JR	NC,J.754F
;
	INC	D
J.754F:	PUSH	BC
	LD	B,03H	; 3 
	CALL	C.46D7
;
	POP	BC
	JR	NC,J$756A
;
	LD	A,(IX+16)
	ADD	A,E
	LD	E,A
	JR	NC,J$7560
;
	INC	D
J$7560:	DJNZ	J.754F
;
	CALL	C.45DB
;
	LD	B,03H	; 3 
	CALL	C.46C5
;
J$756A:	POP	BC
	POP	DE
	POP	HL
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.756E:	PUSH	BC
	PUSH	DE
	PUSH	HL
	PUSH	IX
	CALL	C.74C2
;
	LD	A,(IX)
	CP	0FFH
	JR	Z,J.75C5
;
	CALL	C$4560
;
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	A,(IX+1)
	PUSH	BC
	POP	IX
	LD	C,A
	CALL	C.45DB
;
	LD	B,A
	DEC	HL
	LD	A,(HL)
	LD	(HL),00H
	INC	HL
	CP	01H	; 1 
	JP	NZ,J.75C5
;
	LD	A,C
	ADD	A,A
	ADD	A,C
	ADD	A,E
	LD	E,A
	JR	NC,J.75A0
;
	INC	D
J.75A0:	PUSH	DE
	PUSH	BC
	PUSH	HL
	LD	A,C
	ADD	A,A
	ADD	A,C
	LD	B,A
	LD	A,(IX+16)
	SUB	B
	CP	03H	; 3 
	LD	B,A
	JR	C,J$75B2
;
	LD	B,03H	; 3 
J$75B2:	LD	A,(IX)
	CALL	C.4755
;
	POP	HL
	POP	BC
	POP	DE
	LD	A,E
	ADD	A,(IX+16)
	LD	E,A
	JR	NC,J$75C3
;
	INC	D
J$75C3:	DJNZ	J.75A0
;
J.75C5:	POP	IX
	POP	HL
	POP	DE
	POP	BC
	XOR	A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$75CC:	LD	A,(D.F338)
	OR	A
	RET	NZ
	PUSH	IX
	CALL	C.5FEF			; GETWRK
	LD	B,(IX+10)
	LD	C,(IX+11)
	LD	D,(IX+12)
	POP	IX
	XOR	A
	RET
;
;	-----------------
J$75E3:	PUSH	IX
	PUSH	BC
	CALL	C.5FEF			; GETWRK
	POP	BC
	LD	(IX+10),B
	LD	(IX+11),C
	LD	(IX+12),D
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$75F6:	LD	A,(X.F252)
	CP	0C9H
	JR	Z,J$760E
;
J$75FD:	PUSH	DE
	PUSH	HL
	CALL	C.74E5
;
	POP	HL
	POP	DE
	JR	NZ,J$7607
;
	INC	BC
J$7607:	INC	HL
	DEC	DE
	LD	A,E
	OR	D
	JR	NZ,J$75FD
;
	RET
;
;	-----------------
J$760E:	PUSH	IX
	LD	HL,I.0003
J$7613:	PUSH	DE
	LD	A,D
	CP	04H	; 4 
	JR	C,J.7622
;
	JR	NZ,J$761F
;
	LD	A,E
	OR	A
	JR	Z,J.7622
;
J$761F:	LD	DE,I.0400
J.7622:	PUSH	DE
	PUSH	HL
	PUSH	DE
	CALL	C.74F8
;
	EX	DE,HL
	POP	DE
	CALL	C$7647
;
	POP	HL
	LD	A,04H	; 4 
	ADD	A,H
	POP	DE
	POP	HL
	OR	A
	SBC	HL,DE
	EX	DE,HL
	LD	H,A
	LD	L,00H
	LD	A,D
	OR	E
	JR	NZ,J$7613
;
	CALL	C.45FB
;
	PUSH	HL
	POP	IY
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7647:	CALL	C.4564
;
J$764A:	LD	A,(HL)
	INC	HL
	OR	A
	JR	NZ,J.7655
;
	LD	A,(HL)
	AND	0FH	; 15 
	JR	NZ,J.7655
;
	INC	BC
J.7655:	DEC	DE
	LD	A,D
	OR	E
	RET	Z
;
	INC	HL
	LD	A,(HL)
	OR	A
	JR	NZ,J.7666
;
	DEC	HL
	LD	A,(HL)
	INC	HL
	AND	0F0H
	JR	NZ,J.7666
;
	INC	BC
J.7666:	DEC	DE
	INC	HL
	LD	A,D
	OR	E
	JR	NZ,J$764A
;
	RET

;	  Subroutine CHOICE
;	     Inputs  ________________________
;	     Outputs ________________________

J$766D:	LD	HL,I$7671
	RET
;
;	-----------------
I$7671:	DEC	C
	LD	A,(BC)
	LD	E,E
	LD	C,C
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	LD	L,H
	LD	H,L
	LD	H,C
	HALT
;
;	-----------------
?.767D:	LD	H,L
	JR	NZ,J$76B1
;
	LD	E,L
	DEC	C
	LD	A,(BC)
	LD	SP,D.202E
	LD	SP,I.3038
	LD	C,E
	LD	B,D
	JR	NZ,J$76C2
;
	LD	L,32H	; "2"
	DEC	(HL)
	LD	(D.0A0D),HL
	LD	(D.202E),A
	INC	SP
	LD	(HL),30H	; "0"
	LD	C,E
	LD	B,D
	JR	NZ,J$76D2
;
	LD	L,32H	; "2"
	DEC	(HL)
	LD	(D.0A0D),HL
	INC	SP
	LD	L,20H	; " "
	INC	SP
	LD	(HL),30H	; "0"
	LD	C,E
	LD	B,D
	JR	NZ,J$76E0
;
	LD	L,35H	; "5"
	LD	(D.0A0D),HL
J$76B1	EQU	$-1
	INC	(HL)
	LD	L,20H	; " "
	SCF
	LD	(D.4B30),A
	LD	B,D
	JR	NZ,J$76EF
;
	LD	L,35H	; "5"
	LD	(D.0A0D),HL
	LD	A,(BC)
J$76C2:	LD	E,E
	LD	C,C
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	LD	L,H
	LD	H,L
	LD	H,C
	HALT
;
;	-----------------
?.76CC:	LD	H,L
	JR	NZ,J$7701
;
	LD	E,L
	DEC	C
	LD	A,(BC)
J$76D2:	DEC	(HL)
	LD	L,20H	; " "
	LD	SP,I.3038
	LD	C,E
	LD	B,D
	JR	NZ,J$7711
;
	LD	L,32H	; "2"
	DEC	(HL)
	LD	(D.0A0D),HL
J$76E0	EQU	$-2
	LD	(HL),2EH	; "."
	JR	NZ,J$7719
;
	LD	(HL),30H	; "0"
	LD	C,E
	LD	B,D
	JR	NZ,J$7721
;
	LD	L,32H	; "2"
	DEC	(HL)
J$76EF:	LD	(D.0A0D),HL
	SCF
	LD	L,20H	; " "
	INC	SP
	LD	(HL),30H	; "0"
	LD	C,E
	LD	B,D
	JR	NZ,J$772F
;
	LD	L,35H	; "5"
	LD	(D.0A0D),HL
J$7701:	JR	C,J$7731
;
	JR	NZ,J$773C
;
	LD	(D.4B30),A
	LD	B,D
	JR	NZ,J$773E
;
	LD	L,35H	; "5"
	LD	(D.0A0D),HL
	LD	A,(BC)
J$7711:	NOP

J$7712:	DEC	A
	LD	E,A
	LD	A,07H	; 7 
	CP	E
	LD	A,0CH	; 12 
J$7719:	RET	C
	LD	A,B
	CP	18H
	LD	A,0EH	; 14 
	RET	C
	LD	A,D
J$7721:	CALL	C.41C1
	JR	NC,J$7729
	LD	A,2
	RET

J$7729:	LD	C,0FEH
	LD	(IX),C
	LD	D,A
	PUSH	HL
	PUSH	DE
	LD	HL,I.FB21
	LD	B,4
J$7736:	LD	C,(HL)
	INC	HL
	LD	A,(HL)
	INC	HL
	OR	C			; entry used ?
	JR	Z,J$7752		; nope, quit
	LD	C,A
	PUSH	HL
	PUSH	BC
	LD	HL,D.7114
	CALL	WRSLT
	POP	BC
	PUSH	BC
	LD	A,C
	LD	L,1CH
	CALL	WRSLT
	POP	BC
	POP	HL			; disable I/O ports
	DJNZ	J$7736			; next entry
J$7752:	POP	DE
	POP	HL
	LD	IY,I$4F9F
	BIT	2,E
	JR	Z,J$7760
	LD	IY,I$4FA8
J$7760:	LD	A,E
	LD	C,28H	; "("
	CP	02H	; 2 
	JR	C,J$7769
	LD	C,50H	; "P"
J$7769:	LD	A,E
	AND	01H	; 1 
	INC	A
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	H,A
	LD	A,E
	AND	03H	; 3 
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	L,A
	CALL	C.41E8
	LD	B,D
	LD	D,00H
J$777A:	LD	E,00H
J$777C:	CALL	C$78EA
;
	CALL	C$7867
;
	JR	NC,J$778A
;
	CALL	C.5095
;
	JP	J.79DA
;
;	-----------------
J$778A:	INC	E
	LD	A,E
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	CP	H
	JR	NZ,J$777C
;
	INC	D
	LD	A,C
	CP	D
	JR	NZ,J$777A
;
	PUSH	HL
	POP	IY
	PUSH	HL
	PUSH	BC
	PUSH	HL
	CALL	C.41E1
;
	POP	DE
	LD	HL,I$4609
	LD	C,13H	; 19 
	LDIR
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	A,L
	OR	A
	JR	NZ,J$77B4
;
	INC	A
	LD	(IY+13),A
	LD	A,40H	; "@"
	LD	(IY+23),A
J$77B4:	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	A,L
	ADD	A,31H	; "1"
	LD	(IY+8),A
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	A,H
	LD	(IY+26),A
	LD	B,A
	LD	A,00H
J$77C3:	ADD	A,09H	; 9 
	DJNZ	J$77C3
;
	POP	BC
	PUSH	BC
	LD	B,A
	LD	HL,X.0000
	LD	D,00H
	LD	E,C
J$77D0:	ADD	HL,DE
	DJNZ	J$77D0
;
	LD	(IY+19),L
	LD	(IY+20),H
	LD	A,09H	; 9 
	LD	(IY+24),A
	LD	D,02H	; 2 
	LD	E,0FCH
	DEFB	0DDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	A,L
	CP	02H	; 2 
	JR	C,J.77F1
;
	SUB	02H	; 2 
	LD	E,0F8H
	CP	01H	; 1 
	JR	NZ,J.77F1
;
	INC	D
J.77F1:	ADD	A,E
	LD	E,A
	LD	(IY+21),E
	LD	(IY+22),D
	PUSH	DE
	PUSH	IY
	POP	HL
	LD	DE,I$001E
	ADD	HL,DE
	EX	DE,HL
	LD	HL,I$7DA0
	LD	BC,I.0009
	LDIR
	EX	DE,HL
	PUSH	DE
	CALL	C.4696
;
	POP	DE
	LD	BC,BDOS
	ADD	HL,BC
	EX	DE,HL
	LD	C,0CBH
	LDIR
	POP	DE
	DEFB	0FDH		; << Illegal Op Code Byte >>
;	-----------------
;
	INC	H
	DEFB	0FDH		; << Illegal Op Code Byte >>
;	-----------------
;
	INC	H
	LD	B,02H	; 2 
J$7820:	LD	(IY),E
	LD	A,0FFH
	LD	(IY+1),A
	LD	(IY+2),A
	LD	A,D
	ADD	A,A
	DEFB	0FDH		; << Illegal Op Code Byte >>
;	-----------------
;
	ADD	A,H
	DEFB	0FDH		; << Illegal Op Code Byte >>
;	-----------------
;
	LD	H,A
	DJNZ	J$7820
;
	POP	BC
	POP	HL
	LD	D,B
	LD	C,E
	LD	B,05H	; 5 
	LD	A,C
	CP	0F9H
	JR	NZ,J$7840
;
	LD	B,07H	; 7 
J$7840:	SCF
	LD	A,D
	LD	DE,X.0000
	PUSH	AF
	PUSH	BC
	PUSH	HL
	CALL	C.74A0
	POP	HL
	JR	NC,J$7851
;
	POP	BC
	POP	BC
	RET
;
;	-----------------
J$7851:	PUSH	HL
	CALL	C.41E1
;
	POP	HL
	POP	BC
	LD	E,B
	LD	D,00H
	LD	B,07H	; 7 
	LD	A,C
	CP	0FCH
	JR	NZ,J$7863
;
	LD	B,04H	; 4 
J$7863:	POP	AF
	JP	C.74A0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7867:	PUSH	BC
	PUSH	DE
	CALL	C.7B3C
;
	CALL	C.7B4A
;
	SLA	E
	SLA	E
	SLA	E
	SLA	E
	OR	E
	OUT	(0D4H),A
	CALL	C.7B40
;
	LD	A,01H	; 1 
	OUT	(0D2H),A
	LD	A,D
	CALL	C.7B53
;
	LD	E,03H	; 3 
J$7887:	PUSH	HL
	PUSH	DE
	LD	C,0D3H
	LD	A,0F4H
	OUT	(0D0H),A
	CALL	C.7B5C
;
	LD	DE,I$789C
	PUSH	DE
	LD	DE,I$78A4
	JP	J.7B21
;
;	-----------------
I$789C:	JR	Z,J$78CC
;
	POP	DE
	POP	HL
	LD	A,80H
	JR	J.78DD
;
;	-----------------
I$78A4:	OUTI
	LD	DE,I.0301
	JR	J.78AE
;
;	-----------------
J$78AB:	AND	E
	JR	Z,J.78CB
;
J.78AE:	IN	A,(0D0H)
	CP	D
	JR	NZ,J$78AB
;
	OUTI
	LD	A,(HL)
	INC	A
	JP	NZ,J.78AE
;
	LD	H,4EH	; "N"
	JR	J.78C1
;
;	-----------------
J$78BE:	AND	E
	JR	Z,J.78CB
;
J.78C1:	IN	A,(0D0H)
	CP	D
	JR	NZ,J$78BE
;
	OUT	(C),H
	JP	J.78C1
;
;	-----------------
J.78CB:	POP	DE
J$78CC:	POP	DE
	POP	HL
	IN	A,(0D0H)
	AND	7CH	; "|"
	JP	Z,J$78E2
;
	BIT	6,A
	JR	NZ,J.78DD
;
	DEC	E
	JP	NZ,J$7887
;
J.78DD:	SCF
	CALL	C.79E8
;
	LD	A,C
J$78E2:	PUSH	AF
	CALL	C.7B3C
;
	POP	AF
	POP	DE
	POP	BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$78EA:	PUSH	BC
	PUSH	HL
	PUSH	IY
	LD	B,3EH	; ">"
	CALL	C.5351
;
	CALL	C.5349
;
	LD	BC,I$03F6
	CALL	C.534C
;
	LD	(HL),0FCH
	INC	HL
	LD	B,32H	; "2"
	CALL	C.5351
;
	LD	B,09H	; 9 
J$7906:	PUSH	BC
	CALL	C.5349
;
	CALL	C.4363
;
	LD	(HL),0FEH
	INC	HL
	LD	(HL),D
	INC	HL
	LD	(HL),E
	INC	HL
	LD	A,(IY)
	LD	(HL),A
	INC	HL
	INC	IY
	LD	(HL),02H	; 2 
	INC	HL
	LD	(HL),0F7H
	INC	HL
	LD	B,16H
	CALL	C.5351
;
	CALL	C.5349
;
	CALL	C.4363
;
	LD	(HL),0FBH
	INC	HL
	PUSH	DE
	LD	A,40H	; "@"
	LD	BC,I.0200
	CALL	C.58E3
;
	POP	DE
	INC	HL
	LD	(HL),0F7H
	INC	HL
	LD	B,54H	; "T"
	CALL	C.5351
;
	POP	BC
	DJNZ	J$7906
;
	LD	(HL),0FFH
	POP	IY
	POP	HL
	POP	BC
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.794C:	BIT	7,H
	SCF
	RET	NZ
;
	DEC	B
	LD	A,0FFH
	ADD	A,L
	LD	A,H
	ADC	A,01H	; 1 
	ADC	A,B
	ADC	A,B
	INC	B
	CP	40H	; "@"
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$795D:	PUSH	AF
	LD	A,D
	CP	06H	; 6 
	LD	A,04H	; 4 
	JR	NC,J$7970
;
	LD	A,C
	CP	0F8H
	JR	C,J.796E
;
	CP	0FEH
	JR	C,J$7975
;
J.796E:	LD	A,02H	; 2 
J$7970:	POP	BC
	LD	B,00H
	SCF
	RET
;
;	-----------------
J$7975:	POP	AF
	PUSH	AF
	CALL	C.41C1
;
	JR	C,J.796E
;
	EX	(SP),HL
	LD	H,A
	EX	(SP),HL
	PUSH	BC
	PUSH	HL
	CALL	C.794C
;
	JR	C,J$799C
;
	PUSH	DE
	LD	HL,I$7A04
	LD	DE,I$50B1
	LD	BC,I.0163
	LD	A,16H
	CALL	C$7BAF
	LD	HL,I$00FF
	LD	(D.F241),A
	POP	DE
J$799C:	CALL	C.41E8
	POP	HL
	POP	BC
	POP	AF
	PUSH	BC
	PUSH	AF
J$79A4:	POP	AF
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	AF
	CALL	C.794C
;
	JR	C,J$79BB
;
	POP	AF
	LD	IY,I$79BF
	PUSH	IY
	LD	IY,(D.F34D)
	JP	(IY)
;
;	-----------------
J$79BB:	POP	AF
	CALL	C.7A23
;
I$79BF:	POP	DE
	POP	BC
	JR	C,J$79CE
;
	INC	H
	INC	H
	INC	DE
	DEC	B
	JR	NZ,J$79A4
;
	POP	AF
	POP	BC
	XOR	A
	JR	J.79DA
;
;	-----------------
J$79CE:	LD	C,A
	POP	AF
	LD	A,C
	CALL	C.79E8
;
	POP	HL
	LD	A,H
	SUB	B
	LD	B,A
	LD	A,C
	SCF
J.79DA:	PUSH	AF
	EI
	CALL	C$FFD4

;	  Subroutine disable I/O ports when needed
;	     Inputs  ________________________
;	     Outputs ________________________

J$79DF:	LD	A,(D.F33E)
	OR	A
	CALL	NZ,C.7BF1		; disable I/O ports
	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.79E8:	JR	NC,J$79EF
;
	LD	C,00H
	BIT	6,A
	RET	NZ
;
J$79EF:	LD	C,02H	; 2 
	BIT	7,A
	RET	NZ
;
	LD	C,04H	; 4 
	BIT	3,A
	RET	NZ
;
	LD	C,06H	; 6 
	BIT	4,A
	RET	NZ
;
	LD	C,0AH	; 10 
	RET	C
;
	LD	C,0CH	; 12 
	RET

I$7A04:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	A,(D.F342)
	LD	H,HIGH 4000H
	CALL	C.0024
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	CALL	C.7A23
	PUSH	AF
	PUSH	HL
	LD	A,0
	LD	H,HIGH 4000H
	CALL	C.0024
	POP	HL
	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7A23:	PUSH	AF
	PUSH	BC
	CALL	C.7B40
	BIT	1,C
	LD	C,09H	; 9 
	JR	Z,J$7A2F
	DEC	C
J$7A2F:	LD	B,08H	; 8 
	EX	DE,HL
J$7A32:	ADD	HL,HL
	LD	A,H
	SUB	C
	JR	C,J$7A39
	LD	H,A
	INC	L
J$7A39:	DJNZ	J$7A32
	INC	H
	EX	DE,HL
	POP	BC
	POP	AF
	PUSH	AF
	LD	B,A
	CALL	C.7B4A
	BIT	0,C
	JR	Z,J.7A4E
	SRL	E
	JR	NC,J.7A4E
	OR	10H	; 16 
J.7A4E:	LD	B,A
	LD	A,C
	RRCA
	RRCA
	AND	0C0H
	OR	B
	LD	B,A
	OUT	(0D4H),A
	LD	A,D
	OUT	(0D2H),A
	LD	A,(IX+0)
	OUT	(0D1H),A
	CP	E
	JR	Z,J$7A6A
	LD	A,E
	LD	(IX),A
	CALL	C.7B53
J$7A6A:	POP	AF
	JR	C,J$7A73
	LD	D,9CH
	LD	A,80H
	JR	J$7A77

J$7A73:	LD	D,0FCH
	LD	A,0A0H
J$7A77:	BIT	6,B
	JR	Z,J.7A83
	OR	02H	; 2 
	BIT	4,B
	JR	Z,J.7A83
	OR	08H	; 8 
J.7A83:	LD	E,A
	LD	B,05H	; 5 
	LD	C,0D3H
J$7A88:	PUSH	HL
	PUSH	BC
	PUSH	DE
	CALL	C.7B40
	LD	A,E
	OUT	(0D0H),A
	PUSH	AF
	CALL	C.7B5C
	POP	AF
	BIT	5,A
	LD	DE,I.7AA4
	PUSH	DE
	JR	NZ,J$7AB7
	LD	DE,I$7AB3
	JP	J.7B21

I.7AA4:	JR	Z,J$7AD1
;
	POP	DE
	POP	BC
	POP	HL
	JR	J.7AE1
;
;	-----------------
J.7AAB:	IN	A,(0D0H)
	RRCA
	JR	NC,J.7AD0
	RRCA
	JR	NC,J.7AAB
I$7AB3:	INI
	JR	J.7AAB

J$7AB7:	LD	DE,I$7ABD
	JP	J.7B21

I$7ABD:	OUTI
	LD	DE,I.0301
	JR	J.7AC7

J$7AC4:	AND	E
	JR	Z,J.7AD0
J.7AC7:	IN	A,(0D0H)
	CP	D
	JR	NZ,J$7AC4
	OUTI
	JR	J.7AC7

J.7AD0:	POP	DE
J$7AD1:	POP	DE
	POP	BC
	POP	HL
	IN	A,(0D0H)
	AND	D
	JR	Z,J$7AE8
	BIT	6,A
	JR	NZ,J.7AE1
	DEC	B
	JP	NZ,J$7A88
;
J.7AE1:	SCF
J.7AE2:	PUSH	AF
	CALL	C.7B3C
;
	POP	AF
	RET
;
;	-----------------
J$7AE8:	BIT	5,E
	JR	Z,J.7AE2
;
	LD	A,(D.F30D)
	OR	A
	JR	Z,J.7AE2
;
	PUSH	HL
	LD	B,01H	; 1 
	PUSH	BC
	CALL	C.7B40
;
	RES	5,E
	LD	D,9CH
	PUSH	DE
	LD	A,E
	OUT	(0D0H),A
	LD	DE,I.7AA4
	PUSH	DE
	LD	DE,I$7B13
	JP	J.7B21
;
;	-----------------
J.7B0B:	IN	A,(0D0H)
	RRCA
	JR	NC,J.7AD0
;
	RRCA
	JR	NC,J.7B0B
;
I$7B13:	IN	A,(0D3H)
	CPI
	JR	Z,J.7B0B
;
	POP	DE
	POP	DE
	POP	BC
	POP	HL
	LD	A,24H	; "$"
	JR	J.7AE1
;
;	-----------------
J.7B21:	PUSH	DE
	LD	B,00H
	LD	DE,I$01F2
J.7B27:	IN	A,(0D0H)
	RRCA
	JR	NC,J$7B39
;
	RRCA
	RET	C
;
	DJNZ	J.7B27
;
	DEC	DE
	LD	A,D
	OR	E
	JR	NZ,J.7B27
;
	POP	DE
	OR	80H
	RET
;
;	-----------------
J$7B39:	XOR	A
	POP	DE
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7B3C:	LD	A,0D0H
	OUT	(0D0H),A
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7B40:	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
J$7B44:	IN	A,(0D0H)
	RRCA
	JR	C,J$7B44
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7B4A:	INC	B
	LD	A,80H
J$7B4D:	RLCA
	DJNZ	J$7B4D
;
	ADD	A,20H	; " "
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7B53:	OUT	(0D3H),A
	LD	A,10H	; 16 
	OUT	(0D0H),A
	CALL	C.7B40
;
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7B5C:	LD	A,0E0H
J.7B5E:	EX	(SP),HL
	DEC	A
	JR	NZ,J.7B5E
;
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7B63:	LD	A,2AH	; "*"
	JR	J.7B5E
;
;	-----------------
;
;	  Subroutine DRIVES
;	     Inputs  ________________________
;	     Outputs ________________________

C.7B67:	PUSH	AF
	CALL	C.532C
;
	LD	L,A
	CP	01H	; 1 
	JR	NZ,J$7B74
;
	POP	AF
	RET	Z
;
	PUSH	AF
	INC	L
J$7B74:	POP	AF
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7B76:	LD	HL,D.F33E
	XOR	A
	LD	(HL),A
	PUSH	HL
	CALL	C$7B9D
	CALL	X.F568
	POP	HL
	DEC	(HL)
	JP	C.517F			; enable I/O ports
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7B87:	CALL	C.7B76
	LD	A,0ACH
	OUT	(0D1H),A
	CALL	C$7B63
	IN	A,(0D1H)
	IN	A,(0D1H)
	CP	0ACH
	POP	HL
	RET	NZ
	PUSH	HL
	JP	C.7BF1			; disable I/O ports
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7B9D:	LD	HL,I$7F8F
	LD	DE,I$5090
	LD	BC,I$0071
	LD	A,6
	PUSH	DE
	PUSH	HL
	LD	DE,X.F568
	JR	J$7BB5

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$7BAF:	PUSH	DE
	PUSH	HL
	LD	DE,(D.F34D)
J$7BB5:	PUSH	DE
	PUSH	DE
	LDIR
	LD	D,0
	LD	E,A
	PUSH	DE
	IN	A,(0A8H)
	CALL	C$6017
	CALL	C$5FE3
	POP	DE
	POP	HL
	ADD	HL,DE
	LD	(HL),A
	POP	DE
	POP	BC
	POP	HL
	PUSH	IX
	CALL	C.62A1
	POP	IX
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7BD4:	CALL	C.7B76
;
	CALL	C.4EDA
;
	PUSH	IX
	LD	C,01H	; 1 
J$7BDE:	CALL	C.7BF8
;
	INC	IX
	RLC	C
	LD	A,C
	CP	10H	; 16 
	JR	NZ,J$7BDE
;
	POP	IX
	LD	C,01H	; 1 
	CALL	C.7BF8

;	  Subroutine disable I/O ports
;	     Inputs  ________________________
;	     Outputs ________________________

C.7BF1:	LD	(D.7114),A
	LD	(D.711C),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7BF7:	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7BF8:	DI
	XOR	A
	OUT	(0D4H),A
	LD	A,0D0H
	OUT	(0D0H),A
	LD	A,20H	; " "
	ADD	A,C
	OUT	(0D4H),A
	CALL	C.5088
;
	IN	A,(0D0H)
	BIT	7,A
	JR	NZ,J.7C2B
;
	AND	44H	; "D"
	JR	NZ,J.7C32
;
	XOR	A
	OUT	(0D3H),A
	LD	A,10H	; 16 
	OUT	(0D0H),A
	CALL	C.5088
;
	IN	A,(0D0H)
	BIT	0,A
	JR	NZ,J$7C26
;
	BIT	2,A
	JR	Z,J.7C2B
;
J$7C26:	CALL	C.7B40
;
	JR	J.7C32
;
;	-----------------
J.7C2B:	CALL	C.7B3C
;
	LD	A,0FFH
	JR	J$7C3C
;
;	-----------------
J.7C32:	CALL	C.7B3C
;
	XOR	A
	OUT	(0D0H),A
	CALL	C.7B40
;
	XOR	A
J$7C3C:	LD	(IX),A
	XOR	A
	OUT	(0D4H),A
	RET
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7C43:	CALL	C.5FA9			; print embedded string
;
	INC	C
	LD	B,(HL)
	LD	B,C
	LD	D,E
	LD	D,H
	LD	HL,I$4620
	LD	B,H
	LD	B,H
	JR	NZ,J$7C96
;
	LD	L,C
	LD	(HL),E
	LD	L,E
	LD	D,D
	LD	C,A
	LD	C,L
	JR	NZ,J$7CD0
;
	LD	(HL),D
	LD	L,20H	; " "
	LD	SP,I$302E
	LD	H,C
	LD	A,(BC)
	LD	(D$4443),HL
	LD	E,B
	DEC	L
	LD	(D$7320),A
	LD	(HL),H
	LD	H,C
	LD	L,(HL)
	LD	H,H
	LD	H,C
	LD	(HL),D
	LD	H,H
	LD	(X.7220),HL
	LD	H,L
	LD	L,H
	LD	H,L
	LD	H,C
	LD	(HL),E
	LD	H,L
	LD	A,(BC)
	JR	Z,J$7CE0
;
	ADD	HL,HL
	JR	NZ,J.7CB2
;
	JR	NC,J.7CB2
;
	DEC	(HL)
	JR	NZ,J$7CC6
;
	LD	H,4CH	; "L"
	JR	NZ,J.7CDC
;
	LD	L,A
	LD	H,(HL)
	LD	(HL),H
	LD	(HL),A
	LD	H,C
	LD	(HL),D
	LD	H,L
	LD	A,(BC)
	LD	A,(BC)
	LD	D,E
	LD	A,C
	LD	(HL),E
	LD	(HL),H
J$7C96:	LD	H,L
	LD	L,L
	LD	A,(D$3A00)
	LD	B,A
	DI
	CALL	C.7CBE
;
	CALL	C.532C
;
	LD	HL,J.7CDC
	CALL	C$7CC1
;
	LD	A,(D.F33F)
	AND	A
	CALL	C.7B67			; DRIVES
	LD	A,L
	CALL	C.7CBE
J.7CB2	EQU	$-2
;
	EI
	LD	B,0B4H
J$7CB7:	HALT
;
;	-----------------
?.7CB8:	DJNZ	J$7CB7
;
	XOR	A
	JP	J$00C3
;
;	-----------------
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C.7CBE:	LD	HL,I$7CF5
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7CC1:	PUSH	AF
	CALL	C.5FAF			; print string
	CALL	C.5FA9			; print embedded string
J$7CC6	EQU	$-2
;
	LD	L,C
	LD	H,E
	LD	H,C
	LD	L,H
	JR	NZ,J$7D32
;
	LD	(HL),D
	LD	L,C
J$7CD0:	HALT
;
;	-----------------
?.7CD1:	LD	H,L
	LD	(HL),E
	LD	A,(X.0020)
	POP	AF
	ADD	A,30H	; "0"
	JP	C.408F
;
;	-----------------
J.7CDC:	LD	A,(BC)
	LD	A,(BC)
	LD	D,H
	LD	L,B
J$7CE0:	LD	L,C
	LD	(HL),E
	JR	NZ,J$7D4D
;
	LD	L,(HL)
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	LD	H,(HL)
	LD	H,C
	LD	H,E
	LD	H,L
	LD	A,(D$200A)
	DEC	L
	LD	(HL),B
	LD	L,B
	LD	A,C
	LD	(HL),E
	NOP
I$7CF5:	LD	A,(BC)
	JR	NZ,J$7D25
;
	LD	L,H
	LD	L,A
	LD	H,A
	NOP

;	  Subroutine GETDPB
;	     Inputs  ________________________
;	     Outputs ________________________

C.7CFC:	EI
	LD	A,B
	CP	0F8H
	RET	C
;
	PUSH	IX
	PUSH	HL
	POP	IX
	INC	HL
	LD	(HL),A
	INC	HL
	EX	DE,HL
	LD	HL,I$5523
	LD	BC,I.0009
	LDIR
	LD	BC,I$0270
	LD	DE,I$0107
I$7D17	EQU	$-1
	CP	0FCH
	JR	C,J.7D26
;
	BIT	0,A
	JR	NZ,J.7D26
;
	LD	BC,I$0140
	LD	DE,I.0004
J$7D25	EQU	$-1
J.7D26:	LD	(IX+7),B
	LD	(IX+11),C
	LD	(IX+6),D
I$7D2F:	LD	B,01H	; 1 
I$7D31:	CP	0FEH
J$7D32	EQU	$-1
	JR	NC,J.7D3F
;
	CP	0FAH
	JR	Z,J.7D3F
;
	INC	B
	CP	0F9H
	JR	NZ,J.7D3F
;
	INC	B
J.7D3F:	LD	(IX+16),B
	SUB	0F8H
	LD	C,A
	LD	A,B
	ADD	A,A
	INC	A
	LD	(IX+17),A
	LD	(IX+18),00H
J$7D4D	EQU	$-2
	ADD	A,E
	LD	(IX+12),A
	LD	(IX+13),00H
	LD	HL,I$552C
	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	LD	(IX+14),C
	LD	(IX+15),B
	POP	IX
	XOR	A
	RET
;
;	-----------------
I$7D6B:	LD	D,E
	LD	E,C
	LD	D,E
	LD	D,H
	LD	B,L
	LD	C,L
	LD	BC,I$652E
	LD	B,(HL)
	LD	C,A
	LD	D,D
	LD	C,L
	LD	B,C
	LD	D,H
	LD	BC,I$6547
	LD	D,(HL)
	LD	B,L
	LD	D,D
	LD	C,C
	LD	B,(HL)
	LD	E,C
	JR	NZ,J$7DD4
;
	LD	C,(HL)
	NOP
	LD	C,A
	LD	(HL),H
	LD	D,(HL)
	LD	B,L
	LD	D,D
	LD	C,C
	LD	B,(HL)
	LD	E,C
	JR	NZ,J$7DE0
;
	LD	B,(HL)
	LD	B,(HL)
	NOP
	LD	D,E
	LD	(HL),H
	LD	B,E
	LD	C,B
	LD	C,E
	LD	B,H
	LD	D,E
	LD	C,E
	NOP
	OR	C
	LD	C,A
	NOP
I$7DA0:	JR	J$7DB2
;
;	-----------------
?.7DA2:	LD	D,(HL)
	LD	C,A
	LD	C,H
	LD	E,A
	LD	C,C
	LD	B,H
	NOP
	RET	NC
;
	LD	(D$C07C),DE
	LD	(D$C092),A
	LD	(HL),79H	; "y"
J$7DB2	EQU	$-1
	INC	HL
	LD	(HL),0C0H
J.7DB6:	LD	SP,I$F51F
	LD	HL,I$C0E4
	CALL	C.C0CB
;
	OR	A
	JR	Z,J$7DCB
;
	LD	HL,I$C0EF
	CALL	C.C0CB
;
	INC	A
	JR	Z,J$7DFE
;
J$7DCB:	LD	DE,J.0100
	LD	C,1AH
	CALL	C.F37D
;
	LD	A,(D.C0FA)
J$7DD4	EQU	$-2
	LD	E,00H
	LD	C,0EH	; 14 
	OR	A
	CALL	NZ,C.F37D
;
	LD	HL,I.0001
J$7DE0	EQU	$-1
	LD	(D$C108),HL
	LD	DE,D.C0FA
	LD	HL,I$3F00
	LD	C,27H	; "'"
	CALL	C.F37D
;
	JP	J.0100
;
;	-----------------
?.7DF2:	LD	E,B
	RET	NZ
;
	CALL	X.0000
;
	LD	A,C
	AND	0FEH
	CP	02H	; 2 
	JR	NZ,J$7E10
;
J$7DFE:	LD	A,(D.C0FA)
	CP	01H	; 1 
	LD	A,01H	; 1 
	LD	(D.C0FA),A
	JR	NZ,J.7DB6
;
	LD	A,00H
	AND	A
	JP	Z,J.4022
;
J$7E10:	LD	DE,I$C0AB
	LD	C,09H	; 9 
I$7E14	EQU	$-1
	CALL	C.F37D
;
	LD	C,07H	; 7 
	CALL	C.F37D
;
	CP	1BH
	JP	Z,J.4022
;
	JR	J.7DB6
;
;	-----------------
?.7E24:	LD	C,(HL)
	LD	L,A
	JR	NZ,J$7E6C
;
	LD	C,A
	LD	D,E
	LD	HL,D.0A0D
	LD	C,B
	LD	L,C
	LD	(HL),H
	JR	NZ,J$7E9D
;
	LD	H,L
	LD	A,C
	JR	NZ,J$7E5E
;
	LD	B,L
	LD	D,E
	LD	B,E
	DEC	A
	LD	B,D
	LD	B,C
	LD	D,E
	LD	C,C
	LD	B,E
	ADD	HL,HL
	LD	L,0DH	; 13 
	LD	A,(BC)
	INC	H
	LD	DE,I$C0FB
	LD	BC,I.000B
	LDIR
	PUSH	DE
	POP	HL
	INC	DE
	LD	(HL),00H
	LD	C,19H
	LDIR
	LD	DE,D.C0FA
	LD	C,0FH	; 15 
	JP	C.F37D
;
;	-----------------
?.7E5D:	LD	D,E
J$7E5E:	LD	C,A
	LD	C,H
	LD	E,B
	LD	B,H
	LD	C,A
	LD	D,E
	JR	NZ,J$7EB9
;
	LD	C,C
	LD	D,E
	LD	C,L
	LD	D,E
	LD	E,B
	LD	B,H
J$7E6C:	LD	C,A
	LD	D,E
	JR	NZ,J$7E90
;
	LD	D,E
	LD	E,C
	LD	D,E
	NOP
;
;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;
C$7E74:	LD	(D.F339),SP
	CALL	C.6276
;
	LD	A,B
	CP	20H	; " "
	JP	C,J.723F
;
	PUSH	HL
	CALL	C.60D2
;
	PUSH	AF
	CALL	C.6198
;
	POP	AF
	INC	A
	LD	E,A
	LD	C,1BH
	CALL	C.F37D
J$7E90	EQU	$-1
;
	LD	A,(IX+6)
	INC	A
	CP	11H	; 17 
	JP	NC,J.723F
;
	CCF
	SBC	HL,DE
J$7E9D:	JR	Z,J$7EDD
;
	CALL	C.5FA9			; print embedded string
;
	LD	A,(BC)
	LD	A,(BC)
	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J.7F12
;
	LD	H,C
	LD	(HL),E
	JR	NZ,J.7F12
;
	LD	H,C
	LD	(HL),H
	LD	H,C
	LD	A,(BC)
	LD	C,L
	LD	H,C
	LD	(HL),D
	LD	L,E
	LD	L,C
	LD	L,(HL)
	LD	H,A
J$7EB9:	JR	NZ,J$7F1D
;
	LD	H,C
	LD	H,H
	JR	NZ,J$7F22
;
	LD	L,H
	LD	(HL),L
	LD	(HL),E
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	LD	(HL),E
	JR	NZ,J.7F35
;
	LD	H,C
	LD	A,C
	JR	NZ,J$7F2F
;
	LD	L,A
	LD	(HL),D
	LD	(HL),D
	LD	(HL),L
	LD	(HL),B
	LD	(HL),H
	JR	NZ,J$7F3A
;
	LD	L,C
	LD	L,H
	LD	H,L
	LD	(HL),E
	LD	A,(BC)
	NOP
	CALL	C.6198
;
J$7EDD:	POP	HL
	LD	B,(IX+12)
	LD	DE,X.0000
	CALL	C.46D7
;
	JR	NC,J$7EEF
;
	LD	HL,I$7F55
	JP	J.618F
;
;	-----------------
J$7EEF:	LD	C,(IX+14)
	LD	B,(IX+15)
	DEC	BC
	LD	DE,I.0002
	LD	IY,X.0000
J$7EFD:	PUSH	BC
	PUSH	DE
	EX	DE,HL
I$7F00:	XOR	A
	CALL	C.4EE3
;
	EX	DE,HL
	LD	B,(IX+6)
	INC	B
	CALL	C.46D7
;
	POP	DE
	JR	NC,J$7F1C
;
	PUSH	DE
	PUSH	HL
	EX	DE,HL
J.7F12:	LD	BC,I.0FF7
	CALL	C.74D1
;
	INC	IY
	POP	HL
	POP	DE
J$7F1C:	POP	BC
J$7F1D:	INC	DE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,J$7EFD
J$7F22	EQU	$-1
;
	PUSH	IY
	POP	BC
	LD	A,B
	OR	C
	JR	Z,J$7F4F
;
	PUSH	HL
	CALL	C.45CC
;
	POP	HL
J$7F2F:	LD	DE,I.000A
	INC	H
	LD	(HL),00H
J.7F35:	PUSH	HL
	CALL	C.4935
;
	LD	A,L
J$7F3A:	ADD	A,30H	; "0"
	POP	HL
	DEC	HL
	LD	(HL),A
	LD	A,B
	OR	C
	JR	NZ,J.7F35
;
	CALL	C.6269
;
	CALL	C.5FAF			; print string
;
	LD	HL,I$7F78
	JP	J$6192
;
;	-----------------
J$7F4F:	LD	HL,I$7F70
	JP	J.618F
;
;	-----------------
I$7F55:	LD	D,H
	LD	(HL),D
	LD	H,C
	LD	H,E
	LD	L,E
	JR	NZ,J$7F8C
;
	JR	NZ,J$7FC0
;
	LD	H,C
	LD	H,H
	INC	L
	JR	NZ,J$7FC7
;
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$7FDD
;
	LD	L,(HL)
	LD	(HL),L
	LD	(HL),E
	LD	H,C
	LD	H,D
	LD	L,H
	LD	H,L
	NOP
I$7F70:	LD	B,H
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$7FC5
;
	LD	C,E
	NOP
I$7F78:	JR	NZ,J$7FDC
;
	LD	H,C
	LD	H,H
	JR	NZ,J$7FE1
;
	LD	L,H
	LD	(HL),L
	LD	(HL),E
	LD	(HL),H
	LD	H,L
	LD	(HL),D
	JR	Z,J$7FF9
;
	ADD	HL,HL
	JR	NZ,J$7FF6
;
	LD	H,C
	LD	(HL),D
	LD	L,E
J$7F8C:	LD	H,L
	LD	H,H
	NOP

I$7F8F:	LD	C,8FH+1
J.7F91:	DEC	C
	LD	H,HIGH 4000H
	LD	A,0
	BIT	7,C
	JP	Z,ENASLT
	LD	A,C
	CP	84H
	JR	C,J$7FAC
	AND	03H			; primairy slot
	INC	A
	OR	LOW (EXPTBL-1)
	LD	E,A
	LD	D,HIGH (EXPTBL-1)
	LD	A,(DE)
	RLCA				; slot expanded ?
	JR	NC,J.7F91		; nope, next
J$7FAC:	PUSH	BC
	LD	A,C
	CALL	ENASLT
	LD	HL,I.7FF5
	LD	DE,I.7FF5
	LD	B,11
	CALL	C.7FD3
	JR	Z,J.7FD0
	LD	HL,I$7F00
J$7FC1:	LD	DE,I$7FE6
	LD	B,15
	CALL	C.7FD3
	JR	Z,J.7FD0
	LD	A,H
	CP	80H
	JR	NZ,J$7FC1
J.7FD0:	POP	BC
	JR	J.7F91			; next

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.7FD3:	LD	A,(DE)
	CP	(HL)
	INC	HL
	RET	NZ
	INC	DE
	DJNZ	C.7FD3
	LD	(D.7114),A
	LD	(D.711C),A		; disable I/O ports
	LD	HL,D.F33E
	INC	(HL)
	XOR	A
	RET

I$7FE6:	DEFB	"DDX-DRIVE Inter"
	
I.7FF5:	DEFB	"FASTbyA&L05"

	END
